# -*- coding: utf-8 -*-
import json, os

doc = {
"slug": "new-tretyakov-gallery",
"name_vi": "Phòng trưng bày Tretyakov Mới trên phố Krymsky Val",
"name_ru": "Новая Третьяковка (Третьяковская галерея на Крымском Валу)",
"name_en": "New Tretyakov Gallery",
"subtitle": "Ngôi đền của nghệ thuật Nga thế kỷ 20–21: từ 'Hình vuông đen' của Malevich đến hiện thực xã hội chủ nghĩa, bên cạnh công viên điêu khắc Muzeon nơi an nghỉ của những tượng đài Xô Viết bị hạ bệ.",
"sections": [
 {"heading": "Giới thiệu chung", "paras": [
"""Nếu tòa nhà Tretyakov cổ ở phố Lavrushinsky là nơi lưu giữ hồn cốt của hội họa Nga cổ điển, thì Phòng trưng bày Tretyakov Mới (Novaya Tretyakovka) trên phố Krymsky Val chính là ngôi đền dành cho nghệ thuật thế kỷ 20 và 21. Đây là cơ sở thứ hai của Bảo tàng Quốc gia Tretyakov, một khối kiến trúc bê tông đồ sộ mang phong cách hiện đại Xô Viết, nằm bên bờ sông Moskva, giữa Công viên nghệ thuật Muzeon và cạnh Công viên Gorky. Với du khách quen thuộc với những biểu tượng vàng son của nước Nga cổ, nơi đây mở ra một chương hoàn toàn khác: đầy thử thách, gai góc và cách mạng.""",
"""Bộ sưu tập ở Krymsky Val kể lại một trong những thế kỷ dữ dội nhất của lịch sử nghệ thuật thế giới. Tại đây, người xem đối diện trực tiếp với 'Hình vuông đen' của Kazimir Malevich, tác phẩm được coi là điểm khởi đầu của nghệ thuật trừu tượng hình học, cùng những kiệt tác tiên phong (avant-garde) của Wassily Kandinsky, Marc Chagall, Pavel Filonov và Lyubov Popova. Đi tiếp, không gian chuyển sang thời kỳ hiện thực xã hội chủ nghĩa với những bức tranh khổ lớn ngợi ca công nhân, nông dân và lãnh tụ, rồi khép lại bằng nghệ thuật phi chính thống (underground) và đương đại đầy táo bạo.""",
"""Điều làm nên sức nặng đặc biệt của Tretyakov Mới là nó không chỉ trưng bày nghệ thuật, mà còn trưng bày cả tấn bi kịch và khát vọng của một dân tộc trong thế kỷ 20. Những bức tranh trừu tượng bị cấm đoán, những tác phẩm tuyên truyền hoành tráng, những thử nghiệm ngầm dưới lòng xã hội Xô Viết – tất cả cùng tồn tại dưới một mái nhà, tạo nên một cuộc đối thoại căng thẳng mà hiếm bảo tàng nào trên thế giới có được.""",
"""Ngay bên ngoài bảo tàng là Công viên nghệ thuật Muzeon, bảo tàng điêu khắc ngoài trời lớn nhất nước Nga với hơn một nghìn tác phẩm. Nơi đây từng được mệnh danh là 'nghĩa địa của những tượng đài bị lật đổ', bởi sau năm 1991 hàng loạt tượng lãnh tụ Xô Viết bị hạ bệ đã được đưa về đây. Chính sự cộng hưởng giữa bộ sưu tập trong nhà và vườn tượng ngoài trời khiến chuyến thăm Krymsky Val trở thành một trải nghiệm vừa thẩm mỹ vừa lịch sử đầy ám ảnh.""",
"""Với hướng dẫn viên và người thuyết minh, đây là một trong những điểm đến 'khó' nhưng đáng giá nhất Moscow: nó đòi hỏi phải kể được câu chuyện của cả một thế kỷ nghệ thuật gắn liền với cách mạng, chiến tranh, kiểm duyệt và tự do. Hiểu Tretyakov Mới cũng là hiểu cách nước Nga nhìn lại chính mình qua lăng kính của những nghệ sĩ vĩ đại và can đảm nhất.""",
"""Một lưu ý quan trọng: từ năm 2023, tòa nhà lịch sử trên phố Krymsky Val đã bước vào một đợt đại tu quy mô lớn, dự kiến kéo dài đến khoảng năm 2027–2028. Trong thời gian này, một phần bộ sưu tập được đưa vào kho, phần còn lại được trưng bày tạm tại cơ sở mới trên kè Kadashevskaya. Vì vậy, thông tin dưới đây vừa mang tính giới thiệu địa điểm, vừa là tư liệu nền để người thuyết minh nắm được bức tranh toàn cảnh về một trong những bảo tàng nghệ thuật hiện đại quan trọng nhất của Nga."""
 ]},
 {"heading": "Vị trí & cách di chuyển", "paras": [
"""Phòng trưng bày Tretyakov Mới tọa lạc tại số 10 phố Krymsky Val, quận trung tâm của Moscow, ngay bên bờ nam sông Moskva. Vị trí này rất đắc địa về mặt văn hóa: bảo tàng nằm liền kề Công viên nghệ thuật Muzeon, đối diện Công viên Gorky nổi tiếng, và chỉ cách Nhà thờ Chúa Cứu Thế bên kia sông một quãng ngắn. Tọa độ địa lý xấp xỉ 55,7345 vĩ bắc và 37,6049 kinh đông.""",
"""Cách thuận tiện nhất để đến đây là đi tàu điện ngầm. Hai ga gần nhất đều nằm trên tuyến Vòng (Koltsevaya) màu nâu: ga Park Kultury và ga Oktyabrskaya, từ mỗi ga đi bộ khoảng mười phút là tới. Từ ga Oktyabrskaya, du khách đi dọc theo phố Krymsky Val, còn từ Park Kultury thì băng qua cầu Krymsky – cây cầu treo duyên dáng bắc qua sông Moskva – để tận hưởng quang cảnh đôi bờ trước khi vào bảo tàng.""",
"""Với những ai yêu thích đi bộ, tuyến kè Krymskaya (Krymskaya Naberezhnaya) chạy dọc trước bảo tàng là một trong những không gian đi bộ đẹp nhất Moscow sau đợt cải tạo lớn năm 2013. Con đường lát đá, những luống hoa lâu năm, đài phun nước phun tia và các gian triển lãm ngoài trời nối liền khu Nhà máy sô-cô-la Tháng Mười Đỏ với Đồi Chim Sẻ, biến hành trình tản bộ tới bảo tàng thành một phần thú vị của trải nghiệm.""",
"""Nếu di chuyển bằng taxi hoặc các ứng dụng gọi xe như Yandex Go, du khách chỉ cần báo địa chỉ 'Krymsky Val 10' hoặc tên 'Novaya Tretyakovka'. Cần lưu ý phân biệt rõ với tòa nhà Tretyakov chính ở phố Lavrushinsky trong khu Zamoskvorechye, bởi hai cơ sở nằm cách nhau khoảng hai đến ba ki-lô-mét và trưng bày những bộ sưu tập hoàn toàn khác nhau – nhầm lẫn địa chỉ là lỗi thường gặp của khách lần đầu đến Moscow.""",
"""Khu vực quanh bảo tàng có hạ tầng du lịch rất tốt: bãi đỗ xe, trạm xe đạp công cộng, quán cà phê và nhà hàng dọc kè sông. Do nằm trong cụm công viên Gorky – Muzeon – Neskuchny, đây là nơi lý tưởng để kết hợp một buổi tham quan bảo tàng với việc dạo chơi, đạp xe hoặc ngắm hoàng hôn trên sông. Vào mùa hè, cả khu vực trở thành một trong những điểm hẹn sôi động nhất của người dân thủ đô.""",
"""Trong thời gian tòa nhà Krymsky Val đóng cửa đại tu, một phần trưng bày được chuyển tới cơ sở mới của Tretyakov trên kè Kadashevskaya, gần khu Zamoskvorechye và không xa tòa nhà chính ở Lavrushinsky. Vì vậy, trước mỗi chuyến đi, người thuyết minh nên kiểm tra website chính thức để xác nhận địa điểm nào đang mở cửa và bộ sưu tập nào đang được trưng bày ở đâu, tránh đưa đoàn đến nhầm cơ sở."""
 ]},
 {"heading": "Lịch sử hình thành và phát triển", "paras": [
"""Câu chuyện của mảnh đất bên cầu Krymsky bắt đầu từ thập niên 1920, khi các nhà quy hoạch Xô Viết dự tính biến khu vực ven sông Moskva thành một hệ thống công viên gắn với triển lãm nông nghiệp thường trực. Ý tưởng đó không thành, và trong nhiều thập kỷ tiếp theo, khu đất liên tục được đề xuất cho những công trình khác nhau: một 'Cung Nghệ thuật' vào năm 1930, rồi một trung tâm khoa học lớn sau khi Viện Hàn lâm Khoa học Liên Xô chuyển về Moscow năm 1936.""",
"""Năm 1936, một cuộc thi kiến trúc được tổ chức và phương án của Aleksei Shchusev – kiến trúc sư sau này thiết kế Lăng Lenin – đã giành chiến thắng. Việc xây dựng khởi công năm 1939 nhưng bị Chiến tranh Vệ quốc Vĩ đại làm gián đoạn, và công trường khoa học về sau được dời lên Đồi Chim Sẻ. Mãi đến năm 1959, khu đất ven sông mới chính thức được giao cho Phòng trưng bày Nghệ thuật Quốc gia Liên Xô, mở đường cho một bảo tàng nghệ thuật ra đời tại đây.""",
"""Địa điểm này mang một ý nghĩa biểu tượng: Pavel Tretyakov, nhà sưu tầm và thương gia đã sáng lập bộ sưu tập Tretyakov lừng danh, sinh năm 1832 tại con ngõ Golutvinsky ngay gần đó. Việc dựng một cơ sở mới của bảo tàng ngay trên quê hương người sáng lập được xem là sự tiếp nối tự nhiên và đầy tính tưởng niệm. Bản thiết kế cuối cùng thuộc về xưởng kiến trúc mang tên Ivan Zholtovsky, dựa trên phác thảo của hai kiến trúc sư Yuri Sheverdyaev và Nikolai Sukoyan theo phong cách hiện đại Xô Viết.""",
"""Việc xây dựng bắt đầu năm 1965. Ngay từ năm 1962, người ta đã quyết định tòa nhà sẽ phục vụ hai chủ thể: Phòng trưng bày Nghệ thuật Quốc gia và Nhà Nghệ sĩ Trung ương (TsDKh). Phần dành cho Hội Nghệ sĩ hoàn thành trước, và năm 1979 Nhà Nghệ sĩ Trung ương khai trương tại đây; toàn bộ công trình được hoàn tất vào năm 1985. Từ đó, hai định chế nghệ thuật lớn cùng chia sẻ một khối nhà khổng lồ bên sông Moskva.""",
"""Bước ngoặt đến vào năm 1986, khi Phòng trưng bày Nghệ thuật Quốc gia Liên Xô sáp nhập vào Bảo tàng Tretyakov. Những triển lãm đầu tiên mở cửa cùng năm, trong bối cảnh tòa nhà chính ở Lavrushinsky đang được trùng tu; nhân dịp này, phần lớn tác phẩm hội họa, đồ họa, điêu khắc và nghệ thuật trang trí thế kỷ 20 được chuyển sang Krymsky Val. Sau khi tòa nhà chính hoàn tất trùng tu năm 1996, bộ sưu tập nghệ thuật thế kỷ 20 chính thức an cư tại Krymsky Val và trở thành trưng bày thường trực đầu tiên tại đây.""",
"""Từ đó đến nay, Tretyakov Mới không ngừng lớn mạnh. Bộ sưu tập nghệ thuật đương đại được bồi đắp mạnh trong thập niên 1990 và 2000 nhờ các khoản mua của Bộ Văn hóa và những món quà hiến tặng, trong đó nổi bật là bộ sưu tập avant-garge đồ sộ của nhà sưu tầm George Costakis với hơn 800 tác phẩm. Năm 2015, tòa nhà được tái định vị thương hiệu thành 'Novaya Tretyakovka' – Tretyakov Mới – với hệ thống chỉ dẫn hiện đại, quán cà phê, giảng đường và cửa hàng lưu niệm, hướng tới hình ảnh một bảo tàng nghệ thuật đương đại năng động của thế kỷ 21."""
 ]},
 {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
"""Tòa nhà Krymsky Val là một ví dụ tiêu biểu của kiến trúc hiện đại Xô Viết giai đoạn cuối. Các kiến trúc sư hình dung nó như một 'gian pavilion trong công viên' hướng ra kè sông Moskva, hài hòa với quần thể Vườn Neskuchny và Công viên Gorky lân cận. Khối nhà thấp, trải rộng, với dãy cột chạy quanh chu vi tầng trệt, tạo cảm giác vững chãi và nghiêm cẩn – một thẩm mỹ chức năng đặc trưng của thập niên 1970–1980.""",
"""Nhìn từ bên ngoài, công trình có vẻ khô khan và thậm chí lạnh lùng, với những mảng bê tông lớn và đường nét hình học nghiêm ngặt. Nhưng chính sự tiết chế ấy lại phù hợp với vai trò của nó: một chiếc hộp trung tính, để nghệ thuật bên trong tự cất tiếng nói. Tổng diện tích các phòng trưng bày lên tới khoảng 12.000 mét vuông, biến đây thành một trong những không gian bảo tàng lớn nhất nước Nga.""",
"""Bên trong, bố cục truyền thống là một chuỗi phòng nối tiếp nhau (enfilade), dẫn dắt người xem đi theo dòng thời gian của nghệ thuật thế kỷ 20. Từ năm 2007, cách sắp đặt được đổi mới: hành trình xem bắt đầu từ nghệ thuật năm 1900, và các tác phẩm được nhóm theo chủ đề, cho phép một nghệ sĩ có thể xuất hiện ở nhiều phòng khác nhau. Hệ thống chỉ dẫn cũng được chia theo các khu vực đánh dấu bằng chữ cái, học theo mô hình của Bảo tàng Nghệ thuật Metropolitan ở New York.""",
"""Năm 2016, sau một đợt cải tạo, một khoảng sân trong rộng 4.000 mét vuông với đài phun nước và khán đài bậc thang (amphitheater) được mở ra cho các hoạt động: giảng bài, chương trình âm nhạc và sự kiện cộng đồng. Không gian này biến bảo tàng từ một khối đóng kín thành một điểm hẹn văn hóa sống động, nơi nghệ thuật tràn cả ra ngoài các phòng trưng bày.""",
"""Đáng chú ý, kiến trúc của Tretyakov Mới từng là tâm điểm của nhiều tranh luận. Năm 2008, chính quyền thành phố có kế hoạch phá bỏ phần Nhà Nghệ sĩ Trung ương để dựng một trung tâm triển lãm hình tròn mang tên 'Orange' do kiến trúc sư lừng danh Norman Foster thiết kế, kèm căn hộ, văn phòng và cửa hàng. Kế hoạch vấp phải làn sóng phản đối mạnh mẽ của công chúng và cuối cùng bị hủy bỏ, cho thấy giá trị di sản của khối nhà hiện đại Xô Viết này đã được xã hội thừa nhận.""",
"""Từ năm 2015, hãng kiến trúc OMA của Rem Koolhaas được giao nhiệm vụ tái thiết tòa nhà. Theo ý tưởng công bố năm 2018, công trình sẽ được chia thành bốn khu chức năng – kho lưu trữ, trung tâm giáo dục, không gian triển lãm và khán phòng; các ô cửa sổ sẽ được mở rộng, những bức tường quanh giếng trời được tháo dỡ để tòa nhà trở nên trong suốt, mở tầm nhìn ra Công viên Gorky, và những cầu thang được thay bằng thang cuốn nhiều màu. Đây chính là đợt đại tu đang diễn ra, hứa hẹn một diện mạo hoàn toàn mới cho Tretyakov Mới trong tương lai gần.""",
"""Bao quanh bảo tàng, phần kiến trúc cảnh quan cũng quan trọng không kém. Kè Krymskaya được tái thiết năm 2013 theo thiết kế của nhóm Wowhaus thành một dải đi bộ uốn lượn, với những gian triển lãm mái lượn sóng, luống hoa lâu năm và đài phun nước phun tia – đài phun thứ hai của Moscow. Sự kết hợp giữa khối nhà bê tông nghiêm cẩn và không gian công cộng mềm mại bên sông tạo nên một tổng thể hài hòa hiếm thấy."""
 ]},
 {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
"""Ngôi sao sáng nhất của bộ sưu tập chắc chắn là 'Hình vuông đen' (Chyorny Kvadrat) của Kazimir Malevich, sáng tác năm 1915. Chỉ là một hình vuông đen trên nền trắng, nhưng tác phẩm này đã tuyên bố khai sinh chủ nghĩa Tối cao (Suprematism) và trở thành một trong những biểu tượng cách mạng nhất của nghệ thuật hiện đại thế giới. Đứng trước nó, người xem không chiêm ngưỡng một hình ảnh, mà đối diện với một ý niệm: sự giải phóng hội họa khỏi mọi ràng buộc mô tả.""",
"""Kế đến là các kiệt tác trừu tượng của Wassily Kandinsky, trong đó có những bố cục lớn tràn đầy màu sắc và nhịp điệu như 'Bố cục VII', được nhiều nhà nghiên cứu coi là đỉnh cao của hội họa trừu tượng đầu thế kỷ 20. Bên cạnh đó là thế giới mộng mị của Marc Chagall, những cấu trúc phân mảnh đầy ám ảnh của Pavel Filonov, hình học động của Lyubov Popova và các thử nghiệm của Mikhail Larionov, Natalia Goncharova – cả một chòm sao avant-garde Nga rực rỡ.""",
"""Phòng mang tên nhà sưu tầm George Costakis, khai trương tháng 9 năm 2019, là một điểm dừng đặc biệt. Costakis đã cứu vớt và gìn giữ nghệ thuật tiên phong Nga trong những năm nó bị ruồng bỏ, rồi hiến tặng cho Tretyakov hơn 800 tác phẩm. Tại đây trưng bày những viên ngọc như 'Chân dung Matyushin' của Malevich, 'Bản giao hưởng Shostakovich' của Filonov và 'Quảng trường Đỏ' của Kandinsky.""",
"""Chuyển sang thời kỳ Xô Viết, người xem bước vào không gian của hiện thực xã hội chủ nghĩa. Ở đây có 'Moscow Mới' (1937) của Yuri Pimenov – hình ảnh một thiếu phụ lái ô-tô mui trần giữa thủ đô đang chuyển mình, biểu tượng thơ mộng của cuộc sống mới; 'Mùa xuân' và 'Mùa gặt cỏ' của Arkady Plastov; hay những bức chân dung lãnh tụ hoành tráng của Aleksandr Gerasimov. Đây là cơ hội hiếm hoi để hiểu nghệ thuật đã phục vụ tư tưởng như thế nào.""",
"""Không thể bỏ qua khu vực nghệ thuật phi chính thống và đương đại, với trưng bày thường trực 'Nghệ thuật Đương đại: 1960–2000. Tái khởi động' ra mắt năm 2016. Nơi đây quy tụ đủ các dòng chảy ngầm từng bị kiểm duyệt: trừu tượng, nghệ thuật động và thị giác (kinetic, op art), Sots Art châm biếm biểu tượng Xô Viết, và chủ nghĩa Ý niệm (conceptualism) với những tác phẩm nổi tiếng của Ilya Kabakov. Đó là tiếng nói của tự do nghệ thuật trong lòng một xã hội khép kín.""",
"""Cuối cùng, điểm nhấn không nằm trong nhà mà ngay ngoài cửa: Công viên nghệ thuật Muzeon với hơn một nghìn bức tượng, trong đó có bức tượng Felix Dzerzhinsky từng ngự trước trụ sở KGB và bức tượng Stalin bằng đá granite hồng với khuôn mặt từng bị đập vỡ. Dạo giữa vườn tượng này, người xem như đọc được cả một chương lịch sử đầy giông bão của nước Nga – một trải nghiệm mà không bảo tàng nào có thể tái hiện trong bốn bức tường."""
 ]},
 {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
"""Tretyakov Mới không đơn thuần là một bảo tàng nghệ thuật; nó là tấm gương phản chiếu cả thế kỷ 20 đầy biến động của nước Nga. Trong không gian này, người ta có thể lần theo mạch chảy từ khát vọng cách mạng của phái tiên phong, qua sự áp đặt của hiện thực xã hội chủ nghĩa, đến tiếng nói phản kháng ngầm của các nghệ sĩ phi chính thống, và cuối cùng là sự bung nở của nghệ thuật đương đại sau khi Liên Xô tan rã.""",
"""Bộ sưu tập avant-garde tại đây có tầm vóc thế giới. Đầu thế kỷ 20, nước Nga từng là một trong những cái nôi của nghệ thuật hiện đại, nơi Malevich, Kandinsky, Tatlin và các đồng nghiệp đặt nền móng cho trừu tượng, kiến tạo (constructivism) và chủ nghĩa Tối cao. Việc gìn giữ và trưng bày công khai những tác phẩm này mang ý nghĩa đặc biệt, bởi trong nhiều thập kỷ chúng bị coi là 'nghệ thuật hình thức chủ nghĩa' và bị cất giấu khỏi công chúng.""",
"""Ở chiều ngược lại, bộ sưu tập hiện thực xã hội chủ nghĩa cũng là một tư liệu vô giá. Dù mang chức năng tuyên truyền, những bức tranh này ghi lại thẩm mỹ, lý tưởng và cả những ảo tưởng của thời đại. Chúng cho thấy nghệ thuật đã được huy động để xây dựng hình ảnh về con người mới, xã hội mới ra sao – một bài học sâu sắc về mối quan hệ giữa quyền lực và sáng tạo.""",
"""Bên cạnh nghệ thuật, chính tòa nhà và khu đất cũng là một di sản. Từ những dự án dang dở thời tiền chiến, đến khối nhà hiện đại Xô Viết thập niên 1980, rồi cuộc tranh luận công khai năm 2008 quanh việc bảo tồn hay phá bỏ – tất cả phản ánh cách xã hội Nga đương đại đánh giá lại di sản kiến trúc của thời kỳ Xô Viết, vốn từng bị xem nhẹ.""",
"""Sự cộng sinh giữa bảo tàng và Công viên Muzeon còn mang một tầng nghĩa chính trị – ký ức. Việc đưa những tượng đài lãnh tụ bị hạ bệ về một công viên, thay vì đập bỏ, thể hiện một cách ứng xử riêng của nước Nga với quá khứ: không xóa sổ, mà đặt lịch sử vào bối cảnh để suy ngẫm. Mô hình 'công viên tượng đài' này về sau được nhắc đến bên cạnh những nơi tương tự ở Hungary, Litva hay Bulgaria.""",
"""Vì tất cả những lớp nghĩa ấy, Tretyakov Mới giữ vai trò như một trung tâm đối thoại về bản sắc và ký ức của nước Nga hiện đại. Nó nhắc nhở rằng nghệ thuật không tồn tại tách rời khỏi lịch sử, mà luôn là chiến trường của những giá trị, niềm tin và khát vọng tự do – điều khiến mỗi chuyến thăm nơi đây trở thành một cuộc suy tư chứ không chỉ là thưởng lãm."""
 ]},
 {"heading": "Trải nghiệm dành cho du khách", "paras": [
"""Một chuyến thăm Tretyakov Mới nên được hình dung như một hành trình xuyên thời gian. Bắt đầu từ tầng trưng bày nghệ thuật đầu thế kỷ 20, du khách lần lượt đi qua phái tiên phong, thời kỳ Xô Viết và nghệ thuật đương đại. Cách sắp đặt theo dòng thời gian và chủ đề giúp ngay cả người không chuyên cũng cảm nhận được sự chuyển động của lịch sử nghệ thuật, từ hân hoan cách mạng đến kiểm duyệt, rồi giải phóng.""",
"""Không gian rộng và thoáng là một lợi thế lớn. Khác với sự chật chội thường thấy ở nhiều bảo tàng cổ, các phòng ở Krymsky Val cao ráo, đủ chỗ để lùi lại và chiêm ngưỡng những tác phẩm khổ lớn. Điều này đặc biệt quan trọng với hội họa trừu tượng và tranh cổ động hoành tráng, vốn cần khoảng cách để phát huy hết hiệu ứng thị giác.""",
"""Bảo tàng thường xuyên tổ chức các triển lãm chuyên đề lớn, và chính những sự kiện này tạo nên bầu không khí sôi động. Triển lãm hồi cố về Valentin Serov năm 2016 từng thu hút hơn 485.000 lượt khách, gây nên cảnh xếp hàng dài chưa từng có. Các triển lãm về Aivazovsky, về thời kỳ 'Tan băng' hay về nghệ thuật năm 1917 cũng để lại dấu ấn mạnh, cho thấy sức hút của nơi đây vượt xa một bảo tàng thông thường.""",
"""Trải nghiệm không dừng lại trong nhà. Bước ra ngoài, du khách có thể thong dong dạo vườn tượng Muzeon, ngồi nghỉ bên đài phun nước trong sân, hay tản bộ dọc kè Krymskaya lộng gió. Sự chuyển tiếp mượt mà giữa nghệ thuật trong bảo tàng và nghệ thuật ngoài trời khiến một buổi chiều ở Krymsky Val trở nên trọn vẹn và thư thái.""",
"""Bảo tàng cũng chú trọng giáo dục và gia đình. Có xưởng sáng tạo dành cho trẻ em, các buổi giảng bài, chương trình âm nhạc và hoạt động cộng đồng diễn ra quanh năm. Nhờ đó, nơi đây không chỉ dành cho giới sành nghệ thuật mà còn thân thiện với du khách phổ thông, học sinh và các gia đình muốn có một ngày cuối tuần vừa vui vừa bổ ích.""",
"""Với đoàn khách Việt, người thuyết minh nên dành thời gian giải thích bối cảnh lịch sử trước khi vào xem, bởi nhiều tác phẩm sẽ trở nên khó hiểu nếu tách khỏi câu chuyện cách mạng, chiến tranh và kiểm duyệt phía sau. Khi được kể đúng câu chuyện, ngay cả một hình vuông đen tưởng chừng đơn giản cũng có thể khiến cả đoàn lặng đi vì xúc động."""
 ]},
 {"heading": "Mẹo tham quan", "paras": [
"""Trước hết, hãy kiểm tra kỹ website chính thức của Bảo tàng Tretyakov trước khi lên đường, đặc biệt trong giai đoạn 2023–2028 khi tòa nhà Krymsky Val đang đại tu. Cần xác nhận cơ sở nào đang mở cửa và bộ sưu tập nghệ thuật thế kỷ 20 đang được trưng bày ở đâu – tại Krymsky Val, tại cơ sở Kadashevskaya hay nơi khác – để tránh dẫn đoàn đến nhầm địa điểm.""",
"""Về thời gian, nên dành tối thiểu hai đến ba giờ cho riêng phần trưng bày cố định, và cộng thêm thời gian dạo Công viên Muzeon bên ngoài. Bảo tàng thường mở cửa từ 10 giờ sáng, đóng cửa muộn vào một số ngày trong tuần và nghỉ thứ Hai; giá vé trưng bày thường vào khoảng vài trăm rúp, có ưu đãi cho trẻ em và học sinh, nhưng có thể thay đổi tùy theo triển lãm đặc biệt.""",
"""Nên đi vào ngày trong tuần và tránh cuối tuần nếu muốn không gian yên tĩnh, bởi các triển lãm lớn thường gây cảnh xếp hàng đông đúc. Buổi chiều đẹp trời là thời điểm lý tưởng: sau khi xem tranh, du khách có thể ra kè sông ngắm hoàng hôn và tản bộ sang Công viên Gorky gần đó, kết hợp trọn vẹn giữa nghệ thuật và thư giãn.""",
"""Hãy cân nhắc mua vé trực tuyến trước để tiết kiệm thời gian, nhất là vào mùa cao điểm hoặc khi có triển lãm 'bom tấn'. Nhiều triển lãm chuyên đề bán vé riêng, tách khỏi vé trưng bày thường trực, nên cần đọc kỹ thông tin để chọn đúng loại vé phù hợp với nhu cầu của đoàn.""",
"""Đừng bỏ qua vườn tượng Muzeon – và tốt nhất nên xem nó như một phần bắt buộc chứ không phải tùy chọn. Đây là nơi câu chuyện lịch sử được kể một cách trực quan và giàu cảm xúc nhất. Nếu có thời gian, hãy đi bộ dọc kè Krymskaya để cảm nhận nhịp sống đương đại của Moscow, tương phản thú vị với những tượng đài quá khứ trong công viên.""",
"""Cuối cùng, hãy khuyến khích du khách chụp ảnh có chừng mực và tôn trọng quy định của bảo tàng về việc dùng đèn flash hay chân máy. Với những tác phẩm đồ họa nhạy cảm với ánh sáng, một số phòng có thể hạn chế chụp ảnh; tuân thủ các quy định này cũng là cách góp phần gìn giữ di sản cho những thế hệ sau."""
 ]},
 {"heading": "Khám phá xung quanh", "paras": [
"""Điểm đến gắn liền và không thể tách rời với bảo tàng là Công viên nghệ thuật Muzeon ngay bên cạnh. Đây là bảo tàng điêu khắc ngoài trời lớn nhất nước Nga, nơi hơn một nghìn tác phẩm được sắp đặt giữa cây xanh, bao gồm cả những tượng đài Xô Viết từng bị hạ bệ và các tác phẩm điêu khắc đương đại. Chỉ riêng việc dạo hết công viên cũng đủ cho một chương trình tham quan độc lập đầy ý nghĩa.""",
"""Đối diện bên kia đường là Công viên Gorky trứ danh – lá phổi xanh và trung tâm giải trí bậc nhất của Moscow. Sau đợt cải tạo lớn, nơi đây trở thành không gian hiện đại với bãi cỏ, quán cà phê, sân trượt và các hoạt động ngoài trời quanh năm. Kết hợp Tretyakov Mới với Công viên Gorky là một lịch trình lý tưởng cho cả ngày, cân bằng giữa văn hóa và thư giãn.""",
"""Dọc theo kè sông về hướng tây là khu Nhà máy sô-cô-la Tháng Mười Đỏ (Krasny Oktyabr), nay đã biến thành một cụm sáng tạo sầm uất với phòng trưng bày, quán bar, nhà hàng và không gian nghệ thuật. Từ đây, tầm nhìn mở ra tượng đài Pyotr Đại đế khổng lồ trên sông và Nhà thờ Chúa Cứu Thế bên kia bờ, tạo nên một trong những khung cảnh biểu tượng của thủ đô.""",
"""Với những ai muốn nối dài hành trình nghệ thuật, tòa nhà Tretyakov chính ở phố Lavrushinsky trong khu Zamoskvorechye cách đó không xa, nơi lưu giữ hội họa Nga cổ điển và các icon vô giá. Xem cả hai cơ sở trong cùng một chuyến đi sẽ cho một cái nhìn trọn vẹn về nghệ thuật Nga, từ thời trung cổ đến đương đại – một trải nghiệm mà ít thành phố nào trên thế giới có thể mang lại.""",
"""Khu Zamoskvorechye quanh bảo tàng chính cũng đáng để lang thang, với những con phố cổ yên tĩnh, nhà thờ mái vòm và các quán cà phê ấm cúng. Xa hơn một chút, du khách có thể tản bộ tới Đồi Chim Sẻ dọc theo kè sông đã được cải tạo, hoặc thăm Vườn Neskuchny – khu vườn cổ nhất Moscow – nằm liền kề Công viên Gorky.""",
"""Nhờ vị trí trung tâm và mạng lưới giao thông thuận tiện, Tretyakov Mới dễ dàng được lồng ghép vào nhiều lịch trình khác nhau: một buổi sáng nghệ thuật kết hợp buổi chiều công viên, hay một ngày đi bộ dọc sông Moskva nối liền các điểm nhấn văn hóa. Chính sự linh hoạt này khiến bảo tàng trở thành một mắt xích quý trong bản đồ khám phá thủ đô nước Nga."""
 ]},
 {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
"""Giai thoại nổi tiếng nhất gắn với 'Hình vuông đen' của Malevich. Khi ra mắt tại triển lãm mang tên '0,10' ở Petrograd năm 1915, bức tranh được treo ở góc cao nơi giao giữa hai bức tường – đúng vị trí 'góc thiêng' mà theo truyền thống người Nga vẫn đặt icon tôn giáo. Hành động đầy khiêu khích này ngầm tuyên bố hình vuông đen là 'icon' của một thời đại nghệ thuật mới, khiến giới phê bình đương thời vừa sửng sốt vừa phẫn nộ.""",
"""Bản thân 'Hình vuông đen' cũng ẩn chứa bí mật. Theo thời gian, lớp sơn nứt nẻ để lộ dấu vết của những hình vẽ bên dưới, và các nhà nghiên cứu của Tretyakov đã phát hiện dưới bề mặt còn có dòng chữ và tầng tranh cũ. Điều đó cho thấy tác phẩm tưởng chừng đơn giản nhất lại là kết quả của một quá trình sáng tạo phức tạp và nhiều lớp ý nghĩa, càng làm tăng sức hấp dẫn bí ẩn của nó.""",
"""Một câu chuyện cảm động khác thuộc về George Costakis, người đàn ông gốc Hy Lạp làm tài xế cho một đại sứ quán ở Moscow. Giữa lúc nghệ thuật tiên phong bị ruồng bỏ và có nguy cơ mất mát vĩnh viễn, ông lặng lẽ sưu tầm, cứu vớt từng bức tranh, từng bản vẽ. Khi rời Liên Xô cuối thập niên 1970, ông đã để lại phần lớn bộ sưu tập vô giá cho Tretyakov – một nghĩa cử đã cứu cả một chương của lịch sử nghệ thuật Nga khỏi lãng quên.""",
"""Triển lãm Valentin Serov năm 2016 để lại một giai thoại dở khóc dở cười. Dòng người xếp hàng đông đến mức có lúc xô đổ cả một cánh cửa của bảo tàng; cơ quan tình trạng khẩn cấp phải dựng bếp dã chiến phát cháo nóng cho khách chờ trong giá rét, và bảo tàng phải kéo dài giờ mở cửa tới mười lăm tiếng mỗi ngày. Câu chuyện 'cháo kiều mạch Serov' trở thành một huyền thoại nhỏ, minh chứng cho cơn khát nghệ thuật của công chúng Nga.""",
"""Vườn tượng Muzeon bên cạnh cũng đầy những câu chuyện lịch sử. Bức tượng Felix Dzerzhinsky – người sáng lập cơ quan mật vụ – bị kéo đổ khỏi Quảng trường Lubyanka đêm 22 tháng 8 năm 1991, sau cuộc đảo chính bất thành, rồi được đưa về đây. Sự kiện ấy được nhiều nhà sử học coi là khoảnh khắc châm ngòi cho làn sóng hạ bệ tượng đài Xô Viết trên khắp nước Nga.""",
"""Đặc biệt ám ảnh là cách vườn tượng đặt để lịch sử cạnh nhau. Nhà điêu khắc Evgeny Chubarov đã hiến tặng tác phẩm 'Nạn nhân của các trại giam thời Xô Viết' – 282 chiếc đầu đá xếp trong một chiếc lồng – với điều kiện nó phải được trưng bày ngay bên cạnh bức tượng Stalin bằng granite hồng. Sự đối mặt lặng lẽ giữa kẻ gây ra và những nạn nhân ấy khiến Muzeon trở thành một trong những không gian tưởng niệm giàu sức nặng nhất, nơi nghệ thuật và lịch sử hòa làm một."""
 ]}
],
"highlights": [
 "'Hình vuông đen' (1915) của Malevich cùng bộ sưu tập tiên phong (avant-garde) tầm cỡ thế giới: Kandinsky, Chagall, Filonov, Popova.",
 "Hội họa hiện thực xã hội chủ nghĩa ('Moscow Mới' của Pimenov) và nghệ thuật phi chính thống, đương đại (Ilya Kabakov, Sots Art).",
 "Công viên điêu khắc Muzeon ngay bên cạnh – nơi an nghỉ của tượng Dzerzhinsky, Stalin và hơn 1.000 tác phẩm.",
 "Tòa nhà hiện đại Xô Viết đang được hãng OMA của Rem Koolhaas tái thiết (đại tu 2023–khoảng 2027/2028)."
],
"images": [
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Krymsky_Val_Street_panoramic_view.jpeg", "caption": "Khu vực phố Krymsky Val bên sông Moskva, nơi tọa lạc Phòng trưng bày Tretyakov Mới."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Malevich.black-square.jpg", "caption": "'Hình vuông đen' (1915) của Kazimir Malevich – biểu tượng của chủ nghĩa Tối cao."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wassily_Kandinsky_Composition_VII.jpg", "caption": "'Bố cục VII' (1913) của Wassily Kandinsky – đỉnh cao hội họa trừu tượng."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/0.10_Exhibition.jpg", "caption": "Triển lãm '0,10' năm 1915 tại Petrograd, nơi 'Hình vuông đen' lần đầu ra mắt ở góc thiêng."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Moscow_09-13_img15_Muzeon.jpg", "caption": "Công viên nghệ thuật Muzeon – vườn tượng ngoài trời ngay cạnh bảo tàng."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Moscow_05-2017_img13_Krymsky_Bridge.jpg", "caption": "Cầu Krymsky và kè sông Moskva gần Tretyakov Mới."}
],
"references": [
 {"title": "Trang chính thức Bảo tàng Quốc gia Tretyakov (tretyakovgallery.ru)", "url": "https://tretyakovgallery.ru"},
 {"title": "Wikipedia (EN) — New Tretyakov Gallery", "url": "https://en.wikipedia.org/wiki/New_Tretyakov_Gallery"},
 {"title": "Wikipedia (EN) — Muzeon Park of Arts", "url": "https://en.wikipedia.org/wiki/Muzeon_Park_of_Arts"},
 {"title": "Wikipedia (EN) — Tretyakov Gallery", "url": "https://en.wikipedia.org/wiki/Tretyakov_Gallery"},
 {"title": "Wikipedia (EN) — Black Square (Malevich)", "url": "https://en.wikipedia.org/wiki/Black_Square"},
 {"title": "Wikipedia (EN) — New Moscow (painting)", "url": "https://en.wikipedia.org/wiki/New_Moscow_(painting)"},
 {"title": "Russia Beyond — 25 must-see masterpieces of the Tretyakov Gallery", "url": "https://www.rbth.com/arts/333811-masterpieces-tretyakov-gallery"},
 {"title": "Muzeon / Công viên Gorky — trang chính thức", "url": "https://park-gorkogo.com/en/muzeon"}
],
"sources": [
 "Wikipedia tiếng Anh 'New Tretyakov Gallery' — lịch sử khu đất và tòa nhà (KTS Yuri Sheverdyaev & Nikolai Sukoyan, xây 1965–1985), sáp nhập vào Tretyakov 1986, chuyển trưng bày nghệ thuật thế kỷ 20 sang Krymsky Val sau 1996, tái định vị 'Novaya Tretyakovka' 2015, dự án cải tạo của Rem Koolhaas/OMA, đóng cửa đại tu 2023–2027/2028.",
 "Wikipedia tiếng Anh 'Muzeon Park of Arts' — tượng Dzerzhinsky bị hạ bệ 22/8/1991, sắc lệnh của thị trưởng Luzhkov lập công viên tháng 1/1992, hơn 1.000 tác phẩm, tác phẩm của Chubarov cạnh tượng Stalin, cải tạo kè Krymskaya 2013.",
 "Wikipedia tiếng Anh 'Tretyakov Gallery' và 'Black Square (Malevich)' — bộ sưu tập avant-garde, hoàn cảnh ra đời 'Hình vuông đen' (1915) và triển lãm '0,10'.",
 "Tư liệu về bộ sưu tập George Costakis (hiến tặng hơn 800 tác phẩm avant-garde cho Tretyakov) và phòng trưng bày mang tên ông khai trương 9/2019.",
 "Nguồn báo chí Nga về triển lãm Valentin Serov 2016 (hơn 485.000 lượt khách) và các triển lãm chuyên đề Aivazovsky, 'Tan băng', 'Некто 1917'.",
 "Dữ liệu nội bộ dự án: data/regions/moscow.json (tọa độ, địa chỉ Krymsky Val 10, giờ mở cửa, giá vé, mẹo tham quan và lưu ý cải tạo 2027–2028)."
]
}

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "doc_new-tretyakov-gallery.json")
json.dump(doc, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
wc = sum(len(" ".join(s["paras"]).split()) for s in doc["sections"])
print("wrote", out)
print("sections:", len(doc["sections"]), "| paras:", sum(len(s["paras"]) for s in doc["sections"]), "| words:", wc)
