# -*- coding: utf-8 -*-
"""Builder: doc_shukhov-tower.json — nội dung nguyên gốc tiếng Việt."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))

d = {
 "slug": "shukhov-tower",
 "name_vi": "Tháp Shukhov trên phố Shabolovka",
 "name_ru": "Шуховская башня",
 "name_en": "Shukhov Tower (Shabolovka Radio Tower)",
 "subtitle": "Tháp phát sóng bằng thép hình mạng lưới hyperboloid do kỹ sư thiên tài Vladimir Shukhov thiết kế, xây dựng 1920–1922 — một kiệt tác kỹ thuật của thế kỷ 20 và biểu tượng của truyền hình Xô-viết.",
 "sections": [
  {"heading": "Giới thiệu chung", "paras": [
   "Tháp Shukhov (tiếng Nga: Шуховская башня), còn được gọi là tháp Shabolovka theo tên con phố nơi nó toạ lạc, là một trong những công trình kỹ thuật độc đáo và giàu tính biểu tượng nhất của nước Nga. Đây là một tháp phát sóng bằng thép được dựng nên trong những năm đầu đầy khó khăn của chính quyền Xô-viết non trẻ, và cho đến nay vẫn được giới kiến trúc, kỹ thuật trên toàn thế giới ngưỡng mộ như một tuyệt tác của tư duy hình học và vật liệu.",
   "Điều làm nên danh tiếng của tháp không phải chiều cao hay sự đồ sộ, mà là hình dáng đặc biệt của nó: một kết cấu mạng lưới thép mảnh mai, thắt eo ở giữa và xoè nhẹ ở hai đầu, tạo thành hình mà toán học gọi là mặt hyperboloid một tầng. Nhìn từ xa, tháp trông như được đan bằng những sợi chỉ thép, nhẹ nhàng và thanh thoát đến khó tin đối với một công trình cao hàng trăm mét.",
   "Với một hướng dẫn viên, tháp Shukhov là câu chuyện tuyệt vời để kể về thiên tài kỹ thuật Nga và về mối liên hệ bất ngờ giữa toán học thuần tuý với công trình xây dựng thực tế. Đây cũng là điểm đến dành cho những ai yêu thích kiến trúc hiện đại, kỹ thuật và lịch sử khoa học — một góc nhìn khác về Moskva bên cạnh các cung điện và nhà thờ cổ kính.",
   "Cần lưu ý ngay: tháp nằm trong khuôn viên một cơ sở phát sóng và hiện không mở cửa cho công chúng vào bên trong. Du khách chỉ có thể chiêm ngưỡng và chụp ảnh tháp từ bên ngoài, từ các con phố và khoảng sân xung quanh. Vì thế, đây là điểm 'ngắm và tìm hiểu' hơn là điểm 'tham quan có vé'.",
   "Dù vậy, giá trị của tháp Shukhov vượt xa một điểm chụp ảnh. Nó là chứng nhân của buổi bình minh ngành phát thanh và truyền hình Nga, là hiện thân của một ý tưởng kỹ thuật đi trước thời đại, và là tâm điểm của một cuộc vận động bảo tồn di sản gây tiếng vang toàn cầu trong thập niên 2010. Hiểu được những lớp ý nghĩa đó, du khách sẽ nhìn cấu trúc thép tưởng như đơn giản này bằng con mắt hoàn toàn khác.",
   "Một điểm thú vị là tháp Shukhov thường được ví với tháp Eiffel của Paris, nhưng hai công trình đại diện cho hai triết lý khác nhau. Nếu tháp Eiffel phô diễn sức mạnh của thép qua khối lượng đồ sộ, thì tháp Shukhov lại chinh phục bằng sự tối giản và thông minh của hình học. Với du khách Việt Nam, cách so sánh này giúp hình dung nhanh vì sao giới chuyên môn đánh giá cao công trình đến vậy. Tháp cũng phản ánh một khía cạnh ít được biết tới của nước Nga: bên cạnh nghệ thuật, âm nhạc và văn học, đây còn là quê hương của những bộ óc kỹ thuật hàng đầu thế giới, những người đã âm thầm góp phần định hình diện mạo của kỹ thuật hiện đại."
  ]},
  {"heading": "Vị trí & cách di chuyển", "paras": [
   "Tháp Shukhov toạ lạc trên phố Shabolovka, thuộc quận Donskoy ở phía nam trung tâm Moskva, cách Điện Kremlin khoảng 5 km. Đây là khu vực có bề dày lịch sử gắn với thời kỳ tiên phong của kiến trúc Kiến tạo (Constructivism) thập niên 1920, nên bản thân cả khu phố cũng mang giá trị di sản.",
   "Cách di chuyển đơn giản nhất là bằng tàu điện ngầm: ga Shabolovskaya thuộc tuyến số 6 (tuyến Kaluzhsko-Rizhskaya, màu cam) nằm rất gần tháp, chỉ cách vài phút đi bộ. Từ cửa ga, du khách đi bộ dọc phố Shabolovka là có thể thấy đỉnh tháp vươn lên phía trên các toà nhà.",
   "Từ khu trung tâm Quảng trường Đỏ, du khách có thể đi metro (đổi tuyến một lần) trong khoảng 20–25 phút, hoặc đi taxi/Yandex Go mất chừng 15–20 phút tuỳ tình hình giao thông. Khu vực này ít đông đúc khách du lịch hơn trung tâm, nên việc di chuyển và đi bộ khá dễ chịu.",
   "Vì không vào được bên trong, du khách nên xác định trước vài điểm 'ngắm đẹp' quanh tháp. Các khoảng sân, giao lộ và không gian mở dọc phố Shabolovka cho phép nhìn thấy toàn bộ dáng tháp. Ống kính góc rộng sẽ hữu ích để thu trọn kết cấu mạng lưới cao vút vào khung hình.",
   "Kết hợp lộ trình, có thể ghép tháp Shukhov với các điểm ở phía nam trung tâm như Tu viện Donskoy, Công viên Gorky hay khu Yakimanka. Đây đều là những địa danh nằm trên trục di chuyển thuận tiện, giúp buổi tham quan khu vực phía nam Moskva trở nên trọn vẹn hơn.",
   "Nếu có thời gian, du khách nên dành thêm ít phút quan sát khung cảnh đời sống thường nhật quanh phố Shabolovka — nơi vẫn giữ nhịp sinh hoạt bình dị của một khu dân cư Moskva, khác hẳn sự tấp nập của khu trung tâm du lịch. Chính sự tương phản giữa một biểu tượng kỹ thuật vĩ đại và khung cảnh phố phường giản dị xung quanh tạo nên nét duyên riêng cho trải nghiệm nơi đây. Đối với người chụp ảnh, buổi sáng sớm là lúc phố xá vắng vẻ, ánh sáng dịu và ít phương tiện qua lại, rất thuận lợi để có được những khung hình sạch sẽ, làm nổi bật dáng tháp trên nền trời."
  ]},
  {"heading": "Lịch sử hình thành và phát triển", "paras": [
   "Ý tưởng về tháp ra đời trong bối cảnh chính quyền Xô-viết non trẻ khao khát một phương tiện truyền thông có thể vươn tới mọi miền đất nước rộng lớn. Phát thanh vô tuyến được xem là công cụ lý tưởng — một 'tờ báo không cần giấy và không có khoảng cách'. Một sắc lệnh năm 1919 đã đặt hàng xây dựng một tháp ăng-ten mạnh ở Moskva, và người được giao trọng trách thiết kế chính là kỹ sư Vladimir Shukhov.",
   "Theo thiết kế ban đầu đầy tham vọng, tháp cao tới 350 mét — vượt cả tháp Eiffel — nhưng chỉ dùng lượng thép ít hơn nhiều lần nhờ nguyên lý hyperboloid. Tuy nhiên, giữa cảnh nội chiến và khủng hoảng, nước Nga thiếu thép trầm trọng. Dự án buộc phải thu nhỏ lại: tháp thực tế được xây với phần kết cấu cao khoảng 148,3 mét, gồm nhiều tầng lưới thép lồng lên nhau; về sau, cùng các ăng-ten lắp thêm, chiều cao hữu dụng đạt khoảng 160 mét.",
   "Công trình được xây dựng trong các năm 1920–1922 bằng một phương pháp độc đáo do chính Shukhov nghĩ ra: các tầng lưới được lắp ráp ngay dưới mặt đất rồi dùng tời kéo dựng lồng vào nhau theo kiểu ống nhòm, gần như không cần giàn giáo hay cần cẩu lớn — điều đặc biệt quý giá trong hoàn cảnh khan hiếm vật tư khi ấy. Cách làm này thể hiện tư duy tối ưu hoá triệt để của Shukhov.",
   "Ngày 19 tháng 3 năm 1922, các thiết bị phát của đài Shabolovka được thử nghiệm, và không lâu sau, những chương trình phát thanh đầu tiên đã được truyền đi từ đây. Đến năm 1939, tháp bắt đầu phục vụ phát sóng truyền hình, và trong nhiều thập niên sau đó, hình ảnh tháp Shukhov gắn liền với truyền hình trung ương Xô-viết, trở thành biểu trưng quen thuộc xuất hiện trên màn ảnh nhỏ.",
   "Sang thế kỷ 21, khi các cột phát sóng hiện đại như tháp Ostankino đảm nhận vai trò chính, tháp Shukhov dần mất chức năng kỹ thuật và xuống cấp vì thiếu bảo dưỡng. Khoảng năm 2014, đã có kế hoạch tháo dỡ tháp, làm dấy lên làn sóng phản đối mạnh mẽ. Cuối cùng, kế hoạch tháo dỡ bị bãi bỏ; tháp được gia cố để bảo tồn như một di sản kỹ thuật, dù không còn phát sóng như xưa.",
   "Trong suốt thời kỳ hoàng kim, tháp Shabolovka không chỉ là thiết bị kỹ thuật mà còn mang ý nghĩa chính trị và văn hoá to lớn. Sóng phát thanh rồi truyền hình phát đi từ đây đã kết nối một đất nước rộng lớn trải trên nhiều múi giờ, đưa thông tin, giáo dục và giải trí tới những vùng xa xôi nhất. Việc làm chủ công nghệ phát sóng khi ấy được xem là niềm tự hào quốc gia. Đến thập niên 1960–1970, khi tháp Ostankino cao hơn nhiều được xây dựng để đáp ứng nhu cầu truyền hình màu và số lượng kênh ngày càng tăng, vai trò kỹ thuật của tháp Shukhov dần lùi lại phía sau, nhưng vị thế biểu tượng của nó thì vẫn còn nguyên vẹn trong tâm thức người Nga."
  ]},
  {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
   "Trái tim của thiết kế là nguyên lý hyperboloid một tầng — một bề mặt cong trong hình học nhưng lại có thể được tạo nên hoàn toàn từ các thanh thẳng. Chính phát hiện tài tình này cho phép Shukhov dựng một kết cấu cong duyên dáng mà chỉ dùng những thanh thép thẳng, dễ sản xuất và dễ lắp ráp, thay vì các dầm cong đắt đỏ và phức tạp.",
   "Các thanh thép thẳng đan chéo nhau tạo thành mạng lưới hình thoi, tựa vào các vòng đai ngang. Kết quả là một cấu trúc vừa nhẹ, vừa cứng vững, có khả năng chịu tải trọng gió tốt vì gió lùa qua mạng lưới thay vì dồn ép lên một bề mặt kín. Đây là ví dụ kinh điển cho thấy hình học thông minh có thể thay thế cho việc chất thêm vật liệu.",
   "Tháp gồm nhiều đoạn (tầng) hình hyperboloid xếp chồng, mỗi đoạn thon dần khi lên cao, tạo dáng thắt eo mềm mại đặc trưng. Toàn bộ tháp chỉ dùng một lượng thép khiêm tốn so với các công trình cùng chiều cao thời đó — một minh chứng cho triết lý thiết kế 'ít vật liệu, nhiều hiệu quả' mà Shukhov theo đuổi suốt sự nghiệp.",
   "So sánh thường được nhắc tới là với tháp Eiffel: để đạt độ cao tương đương, thiết kế hyperboloid của Shukhov cần ít thép hơn nhiều lần. Sự tiết kiệm ấy không chỉ mang ý nghĩa kinh tế mà còn thể hiện một quan niệm thẩm mỹ mới — vẻ đẹp đến từ sự tối giản, hợp lý và trung thực với vật liệu, tư tưởng cốt lõi của kiến trúc hiện đại.",
   "Điều đáng kinh ngạc là hình thức hyperboloid không hề lỗi thời. Hơn một thế kỷ sau, các kiến trúc sư và kỹ sư khắp thế giới vẫn tiếp tục sử dụng kết cấu lưới hyperboloid và diagrid cho những công trình chọc trời hiện đại. Tháp Shukhov, vì thế, không chỉ là di sản quá khứ mà còn là nguồn cảm hứng sống động cho kiến trúc đương đại.",
   "Giới kỹ sư đặc biệt khâm phục cách Shukhov giải quyết bài toán chịu lực. Trong một tháp cao, thách thức lớn nhất thường là tải trọng gió; kết cấu càng kín và lớn thì lực gió tác động càng mạnh. Bằng cách để tháp 'rỗng' như một tấm lưới, Shukhov cho phép gió xuyên qua, giảm đáng kể áp lực lên công trình. Đồng thời, các thanh thẳng đan chéo phân bổ lực đều khắp cấu trúc, khiến toàn tháp hoạt động như một khối thống nhất vững chãi. Đây là lời giải vừa đẹp về hình thức, vừa tối ưu về kỹ thuật — sự hoà quyện hiếm có giữa cái đẹp và cái hữu dụng mà các kiến trúc sư hiện đại luôn theo đuổi."
  ]},
  {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
   "Điểm nhấn hiển nhiên nhất là chính dáng vẻ mạng lưới thép cao vút của tháp khi nhìn từ dưới lên. Góc nhìn ngước lên trục tháp cho thấy rõ nhất sự đan cài của các thanh thẳng tạo thành đường cong — một hiệu ứng thị giác vừa toán học vừa nghệ thuật, khiến nhiều người mê mẩn.",
   "Chi tiết các mối nối và vòng đai bằng đinh tán (rivet) là dấu ấn của kỹ thuật đầu thế kỷ 20, khi hàn thép chưa phổ biến. Những hàng đinh tán đều đặn không chỉ có vai trò kết cấu mà còn mang vẻ đẹp công nghiệp hoài cổ, gợi nhớ tinh thần chế tạo thủ công tỉ mỉ của thời kỳ ấy.",
   "Hình bóng tháp in trên nền trời Moskva, đặc biệt vào lúc hoàng hôn hay khi có mây, là khoảnh khắc đáng để chờ đợi. Mạng lưới thép mảnh mai hiện lên như một bức tranh đồ hoạ tinh tế, rất được các nhiếp ảnh gia kiến trúc yêu thích.",
   "Bối cảnh xung quanh tháp — khu phố Shabolovka với các công trình theo phong cách Kiến tạo — cũng là một 'điểm nhấn mở rộng'. Nơi đây từng là một trong những khu thử nghiệm kiến trúc tiên phong của Moskva thập niên 1920, nên tổng thể khu vực mang bầu không khí lịch sử đặc trưng.",
   "Cuối cùng, đừng bỏ lỡ việc quan sát cấu trúc gia cố được lắp thêm để chống đỡ tháp trong đợt bảo tồn. Dù không thuộc thiết kế nguyên bản, nó là chứng tích cho câu chuyện bảo tồn di sản đầy kịch tính, nhắc nhở du khách rằng những công trình quý giá cần được gìn giữ ra sao.",
   "Một chi tiết mà người quan sát tinh ý sẽ nhận ra là tỷ lệ thanh mảnh đến kinh ngạc của các cấu kiện thép so với chiều cao tổng thể của tháp. Cảm giác 'mong manh mà vững chãi' ấy chính là điều khiến tháp Shukhov khác biệt so với mọi tháp thép nặng nề cùng thời. Vào ban đêm, khi được chiếu sáng, mạng lưới thép hiện lên lung linh, biến tháp thành một tác phẩm nghệ thuật ánh sáng giữa lòng thành phố. Nhiều nhiếp ảnh gia coi việc bắt được khoảnh khắc tháp lên đèn trên nền trời chạng vạng là một 'phần thưởng' xứng đáng cho công sức đi tìm góc chụp quanh khu phố."
  ]},
  {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
   "Tháp Shukhov là biểu tượng cho một giai đoạn đặc biệt: thời điểm nước Nga vừa trải qua cách mạng và nội chiến nhưng vẫn khát khao vươn tới hiện đại, khoa học và tiến bộ kỹ thuật. Việc dựng nên một công trình tân tiến bậc nhất thế giới giữa muôn vàn thiếu thốn đã biến tháp thành một biểu tượng của ý chí và trí tuệ.",
   "Về mặt truyền thông, tháp gắn liền với sự ra đời của phát thanh và truyền hình ở Nga. Suốt nhiều thập niên, đây là 'trái tim' phát sóng của đất nước, đưa tiếng nói và hình ảnh tới hàng triệu gia đình. Với nhiều thế hệ người Nga, dáng tháp trên màn hình tivi là một ký ức tuổi thơ khó phai.",
   "Trong lịch sử kiến trúc và kỹ thuật thế giới, tháp Shukhov được xếp vào hàng những công trình tiên phong. Nó chứng minh rằng kết cấu lưới thép hyperboloid — một ý tưởng Shukhov đã cấp bằng sáng chế từ năm 1896 — có thể áp dụng cho các công trình lớn, mở đường cho vô số ứng dụng về sau trên khắp hành tinh.",
   "Tháp cũng trở thành biểu tượng của phong trào Kiến tạo Nga (Constructivism), khuynh hướng nghệ thuật – kiến trúc đề cao chức năng, vật liệu và kết cấu. Hình ảnh tháp xuất hiện trong nhiều tác phẩm nhiếp ảnh, hội hoạ và thiết kế đồ hoạ tiên phong, trở thành một 'nhân vật' quen thuộc của mỹ thuật Nga đầu thế kỷ 20.",
   "Cuối cùng, chiến dịch bảo vệ tháp khỏi bị tháo dỡ vào giữa thập niên 2010 đã nâng tầm ý nghĩa của nó thành một biểu tượng cho phong trào bảo tồn di sản hiện đại. Sự kiện này cho thấy giá trị của những công trình kỹ thuật – công nghiệp ngày càng được xã hội trân trọng, không kém gì các di tích cổ.",
   "Không phải ngẫu nhiên mà tháp Shukhov thường được nhắc đến trong các giáo trình kiến trúc và kỹ thuật trên khắp thế giới. Nó là bằng chứng cho thấy đổi mới thực sự thường đến từ việc tư duy lại vấn đề từ gốc rễ, chứ không phải chất thêm nguồn lực. Trong bối cảnh ngày nay, khi tính bền vững và tiết kiệm vật liệu trở thành ưu tiên hàng đầu của ngành xây dựng, triết lý 'làm nhiều hơn với ít hơn' của Shukhov lại càng mang tính thời sự. Vì thế, giá trị của tháp vừa thuộc về quá khứ vàng son, vừa hướng tới tương lai, tiếp tục truyền cảm hứng cho những thế hệ kỹ sư và kiến trúc sư mai sau."
  ]},
  {"heading": "Trải nghiệm dành cho du khách", "paras": [
   "Vì không vào được bên trong, trải nghiệm chính ở đây là ngắm nhìn, tìm hiểu và chụp ảnh tháp từ bên ngoài. Điều này nghe có vẻ hạn chế, nhưng với người yêu kiến trúc, việc đi vòng quanh để quan sát tháp từ nhiều góc, cảm nhận sự thay đổi của dáng lưới thép theo từng vị trí, lại là một trải nghiệm thú vị và tĩnh tại.",
   "Buổi tham quan tại chỗ thường không kéo dài — khoảng 20 đến 40 phút là đủ để ngắm, chụp ảnh và nghe thuyết minh. Chính vì thế, tháp phù hợp làm điểm dừng ngắn trong một lộ trình khám phá khu nam Moskva, hơn là một điểm đến độc lập chiếm trọn nửa ngày.",
   "Giá trị trải nghiệm phụ thuộc rất nhiều vào phần thuyết minh. Nếu hiểu được câu chuyện đằng sau — nguyên lý hyperboloid, hoàn cảnh xây dựng thời nội chiến, số phận của Shukhov, cuộc chiến bảo tồn — du khách sẽ thấy cấu trúc thép tưởng đơn giản này bỗng trở nên sống động và cuốn hút lạ thường.",
   "Đây là điểm đến lý tưởng cho các nhóm khách quan tâm tới khoa học, kỹ thuật, kiến trúc, cũng như sinh viên các ngành xây dựng, thiết kế. Với khách phổ thông, nên đóng khung tháp trong câu chuyện lớn hơn về 'thiên tài kỹ thuật Nga' để tạo hứng thú, tránh việc chỉ nhìn thấy 'một cái tháp thép'.",
   "Trải nghiệm cũng có thể được làm giàu bằng cách kết hợp với các mô hình, triển lãm hoặc tài liệu về Shukhov và kiến trúc Kiến tạo — chủ đề vốn có nhiều không gian trưng bày liên quan ở Moskva. Nhờ đó, câu chuyện về tháp được đặt trong bức tranh toàn cảnh của một thời đại sáng tạo rực rỡ.",
   "Với các đoàn khách chuyên đề, hướng dẫn viên có thể biến buổi ngắm tháp thành một 'bài học nhỏ' đầy hứng khởi: mang theo một sợi dây hay một mô hình đơn giản để minh hoạ cách các đường thẳng có thể tạo nên một mặt cong hyperboloid. Chỉ vài phút trình diễn trực quan như vậy cũng đủ khiến khách thích thú và hiểu ngay nguyên lý tưởng chừng trừu tượng. Đây cũng là cơ hội để giới thiệu rộng hơn về truyền thống toán học và kỹ thuật của nước Nga — mảng đề tài thường bị lu mờ trước các chủ đề nghệ thuật và lịch sử quen thuộc, nhưng lại rất cuốn hút với nhóm khách trẻ và ưa khám phá."
  ]},
  {"heading": "Mẹo tham quan", "paras": [
   "Hãy xác định trước rằng đây là điểm ngắm từ bên ngoài, không có vé vào cửa và không vào được chân tháp do nằm trong khu vực phát sóng có bảo vệ. Việc này giúp quản lý kỳ vọng của khách, tránh cảm giác hụt hẫng khi tới nơi.",
   "Về nhiếp ảnh, nên mang ống kính góc rộng để thu trọn chiều cao và kết cấu lưới của tháp. Thời điểm chụp đẹp là sáng sớm hoặc chiều muộn khi ánh sáng xiên làm nổi bật các thanh thép; trời có ít mây cũng tạo phông nền lý tưởng cho hình bóng tháp.",
   "Nên chọn nhiều góc quan sát khác nhau quanh phố Shabolovka: nhìn thẳng lên trục tháp cho hiệu ứng hình học ấn tượng, còn nhìn từ xa lại thấy được dáng tháp trong tương quan với khu phố. Đi bộ một vòng ngắn sẽ giúp khám phá góc đẹp nhất.",
   "Kết hợp lộ trình một cách thông minh: vì thời gian ở tháp ngắn, nên ghép chung với các điểm lân cận phía nam trung tâm để tối ưu di chuyển. Ga metro Shabolovskaya ngay gần đó khiến việc đến và đi rất thuận tiện.",
   "Cuối cùng, hãy chuẩn bị sẵn vài dữ kiện 'đắt' để kể cho khách: chiều cao thiết kế 350 m so với 148 m thực tế, việc dùng ít thép hơn tháp Eiffel, phương pháp dựng lồng như ống nhòm, và câu chuyện Shukhov bị kết án nhưng vẫn hoàn thành tháp. Những chi tiết này luôn khiến du khách trầm trồ.",
   "Về trang phục và thời điểm, do đây là hoạt động ngoài trời, nên nhắc khách mặc phù hợp với thời tiết Moskva — vốn có thể lạnh và nhiều gió, đặc biệt vào các mùa lạnh. Vào mùa đông, khung cảnh tháp thép phủ tuyết trên nền trời xám lại mang một vẻ đẹp rất riêng, rất 'chất Nga'. Ngoài ra, nên kiểm tra trước tình hình khu vực, vì đôi khi các công trình gia cố, bảo trì hoặc rào chắn có thể ảnh hưởng tới tầm nhìn. Một chút chuẩn bị nhỏ về thông tin và trang phục sẽ giúp trải nghiệm ngắm tháp trở nên trọn vẹn và thoải mái hơn nhiều cho cả đoàn."
  ]},
  {"heading": "Khám phá xung quanh", "paras": [
   "Ngay trong quận Donskoy, du khách có thể ghé Tu viện Donskoy — một quần thể tu viện cổ kính với nghĩa trang nổi tiếng, nơi an nghỉ của nhiều nhân vật lịch sử và văn hoá Nga. Đây là điểm đến giàu chiều sâu lịch sử, bổ sung tuyệt vời cho câu chuyện kỹ thuật hiện đại của tháp Shukhov.",
   "Khu phố Shabolovka bản thân là một 'bảo tàng ngoài trời' về kiến trúc Kiến tạo thập niên 1920, với các khu nhà ở kiểu công xã và những công trình thử nghiệm táo bạo. Người yêu kiến trúc hiện đại có thể dành thời gian dạo bộ để cảm nhận tinh thần tiên phong của giai đoạn này.",
   "Về phía bắc, không xa là Công viên Gorky và khu bờ sông Moskva sầm uất — không gian giải trí, đi dạo và ẩm thực bậc nhất Moskva. Việc chuyển từ tháp Shukhov trầm mặc sang không khí sôi động của công viên là một cách cân bằng lịch trình dễ chịu.",
   "Khu vực Yakimanka và đảo Bolotny gần đó có nhiều điểm đáng chú ý như các phòng trưng bày nghệ thuật, khu 'Tháng Mười Đỏ' (Krasny Oktyabr) sáng tạo, và tất nhiên cả tượng đài Pyotr Đại đế bên sông. Đây đều là những địa danh có thể ghép vào một ngày khám phá phía nam trung tâm.",
   "Với người mê metro, ga Shabolovskaya và các ga lân cận trên tuyến cam cũng đáng để trải nghiệm, bởi tàu điện ngầm Moskva vốn là một điểm tham quan độc đáo với nhiều nhà ga được ví như 'cung điện dưới lòng đất'.",
   "Rộng hơn nữa, khu vực phía nam trung tâm Moskva là một 'kho' điểm đến đa dạng: từ Phòng trưng bày Tretyakov Mới ở Công viên Nghệ thuật, các không gian sáng tạo ven sông, cho tới những khu chợ ẩm thực hiện đại. Việc kết hợp tháp Shukhov — biểu tượng của quá khứ tiên phong — với những không gian sáng tạo đương đại tạo nên một mạch tham quan thú vị về chủ đề 'tinh thần đổi mới của Moskva qua các thời kỳ'. Đây là cách kể chuyện giúp du khách cảm nhận thành phố như một cơ thể sống, liên tục sáng tạo và tái tạo chính mình từ đầu thế kỷ 20 cho tới hôm nay."
  ]},
  {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
   "Giai thoại nổi tiếng nhất gắn với việc xây tháp là số phận của chính Vladimir Shukhov. Trong quá trình thi công, một sự cố đã xảy ra khi một đoạn tháp bị đổ lúc đang kéo dựng. Trong bối cảnh khắc nghiệt thời ấy, Shukhov bị đưa ra xét xử và nhận một bản án tử hình 'treo' — tức tạm hoãn thi hành với điều kiện ông phải hoàn thành công trình. Ông đã hoàn thành xuất sắc, và bản án được huỷ bỏ. Câu chuyện này cho thấy áp lực khủng khiếp mà người kỹ sư phải gánh chịu.",
   "Nhật ký của Shukhov trong giai đoạn ấy phản ánh tâm trạng căng thẳng tột độ: vừa lo vật tư thiếu thốn, vừa đối mặt nguy cơ tính mạng nếu công trình thất bại. Việc ông vẫn giữ được sự minh mẫn để tạo ra một kiệt tác trong hoàn cảnh đó càng khiến hậu thế khâm phục tài năng và bản lĩnh của ông.",
   "Vladimir Shukhov (1853–1939) là một trong những kỹ sư vĩ đại nhất của Nga, được ví như 'Edison của nước Nga' vì sự đa tài. Ông không chỉ sáng tạo kết cấu hyperboloid mà còn có đóng góp lớn trong ngành dầu khí, đường ống, nồi hơi, mái vòm lưới và nhiều lĩnh vực kỹ thuật khác. Tháp Shabolovka chỉ là một trong vô số phát minh của ông.",
   "Ít người biết rằng công trình hyperboloid đầu tiên trên thế giới của Shukhov không phải tháp Shabolovka, mà là một tháp nước nhỏ trưng bày tại Triển lãm Toàn Nga ở Nizhny Novgorod năm 1896. Ý tưởng táo bạo ấy ra đời từ một quan sát đời thường — cách một chiếc giỏ đan hay sợi chỉ quấn có thể tạo nên hình dáng vững chắc — và đã thay đổi lịch sử kết cấu xây dựng.",
   "Câu chuyện gần đây nhất là cuộc 'giải cứu' tháp vào giữa thập niên 2010. Khi có nguy cơ tháp bị tháo dỡ, nhiều kiến trúc sư danh tiếng thế giới đã cùng ký tên kêu gọi bảo vệ công trình. Sự đoàn kết của cộng đồng kiến trúc quốc tế vì một cây tháp thép ở Moskva là minh chứng cảm động cho việc di sản kỹ thuật có thể chạm tới trái tim con người vượt mọi biên giới.",
   "Một giai thoại nhỏ nhưng giàu ý nghĩa: người ta kể rằng Shukhov luôn tâm niệm phải làm sao cho công trình vừa bền, vừa rẻ, vừa đẹp — ba tiêu chí mà ông cho là không thể tách rời. Chính quan niệm ấy đã dẫn ông tới hình dáng hyperboloid, nơi cái đẹp không phải là thứ trang trí thêm vào mà nảy sinh tự nhiên từ logic kết cấu. Với nhiều kiến trúc sư ngày nay, đó vẫn là một bài học kinh điển. Và mỗi khi đứng dưới chân tháp Shabolovka ngước nhìn mạng lưới thép vươn lên trời, người ta như còn nghe vang vọng niềm tin của người kỹ sư ấy: rằng trí tuệ con người có thể biến những thanh thép thẳng vô tri thành một bản giao hưởng của hình học."
  ]}
 ],
 "highlights": [
  "Kiệt tác kết cấu thép hình hyperboloid của kỹ sư thiên tài Vladimir Shukhov, xây dựng 1920–1922 giữa thời nội chiến.",
  "Thiết kế ban đầu cao 350 m (vượt tháp Eiffel) nhưng vì thiếu thép phải giảm còn ~148,3 m; dùng ít thép hơn nhiều so với các công trình cùng độ cao.",
  "Dựng bằng phương pháp lồng ống độc đáo, gần như không cần giàn giáo; là 'trái tim' phát thanh (1922) rồi truyền hình (1939) của Xô-viết trong nhiều thập niên.",
  "Nguyên lý hyperboloid: tạo mặt cong vững chắc chỉ từ các thanh thép thẳng — ý tưởng Shukhov cấp bằng sáng chế năm 1896.",
  "KHÔNG mở cửa vào bên trong (nằm trong khu phát sóng có bảo vệ) — chỉ ngắm và chụp ảnh từ bên ngoài; ga metro gần nhất: Shabolovskaya.",
  "Từng suýt bị tháo dỡ (~2014) nhưng được cứu nhờ làn sóng phản đối của giới kiến trúc quốc tế; nay được gia cố bảo tồn như di sản."
 ],
 "images": [
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Shukhov tower shabolovka moscow 01.jpg", "caption": "Tháp Shukhov trên phố Shabolovka — kết cấu mạng lưới thép hyperboloid đặc trưng."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Shukhov tower shabolovka moscow 02.jpg", "caption": "Cận cảnh các đoạn hyperboloid xếp chồng, thắt eo và đan chéo bằng thanh thép thẳng."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Черно белая шуховская башня.JPG", "caption": "Tháp Shukhov qua ảnh đen trắng — dáng lưới thép in trên nền trời Moskva."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/World First 1896 Hyperboloid Structure by Vladimir Shukhov in 2006.jpg", "caption": "Tháp nước hyperboloid đầu tiên trên thế giới của Shukhov (Polibino, 1896) — 'tiền thân' của tháp Shabolovka."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Shukhov Oka Towers 1988 photo by Igor Kazus.jpg", "caption": "Các tháp hyperboloid trên sông Oka (NiGRES) của Shukhov — minh chứng cho sức sống của nguyên lý này."}
 ],
 "references": [
  {"title": "Wikipedia — Shukhov Tower", "url": "https://en.wikipedia.org/wiki/Shukhov_Tower"},
  {"title": "WikiArquitectura — Shukhov Tower: Data, Photos & Plans", "url": "https://en.wikiarquitectura.com/building/shukhov-tower/"},
  {"title": "Architectuul — Shukhov Radio Tower", "url": "https://architectuul.com/architecture/shukhov-radio-tower"},
  {"title": "Mathematical Etudes — Shukhov Tower (hình học hyperboloid)", "url": "https://en.etudes.ru/etudes/shukhov-tower/"},
  {"title": "VICE — Architects to Putin: Save Shukhov Tower, Moscow's Futuristic Soviet 'Eiffel'!", "url": "https://www.vice.com/en/article/moscow-shukhov-tower/"},
  {"title": "Engines of Our Ingenuity — Shukhov's Hyperboloids", "url": "https://engines.egr.uh.edu/episode/2937"},
  {"title": "Wikimedia Commons — Category: Shukhov tower (Moscow)", "url": "https://commons.wikimedia.org/wiki/Category:Shukhov_tower_(Moscow)"}
 ],
 "sources": [
  "Wikipedia (bản tiếng Anh) mục 'Shukhov Tower' — lịch sử xây dựng 1920–1922, chiều cao, phát sóng 1922 và truyền hình 1939, kế hoạch tháo dỡ và bảo tồn; truy cập 7/2026.",
  "WikiArquitectura và Architectuul — dữ liệu kiến trúc, nguyên lý hyperboloid, phương pháp thi công dạng lồng, so sánh lượng thép với tháp Eiffel.",
  "Mathematical Etudes — giải thích hình học mặt hyperboloid một tầng tạo từ các đường thẳng.",
  "VICE và các bản tin 2014 — chiến dịch quốc tế kêu gọi bảo vệ tháp khỏi bị tháo dỡ; tên các kiến trúc sư ký tên tổng hợp từ báo chí.",
  "Thông tin về Vladimir Shukhov (1853–1939), bằng sáng chế hyperboloid 1896 và tháp nước Nizhny Novgorod 1896 tổng hợp từ Wikipedia và các nguồn lịch sử kỹ thuật.",
  "Số liệu (350 m thiết kế, ~148,3 m thực tế, ~160 m gồm ăng-ten) có thể chênh lệch đôi chút giữa các nguồn; giao thông và vị trí theo bản đồ Moskva. Ảnh từ Wikimedia Commons."
 ]
}

out = os.path.join(HERE, "doc_shukhov-tower.json")
json.dump(d, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
wc = sum(len(p.split()) for s in d["sections"] for p in s["paras"])
print("WROTE", out, "| sections", len(d["sections"]), "| words", wc)
