# -*- coding: utf-8 -*-
import json, os, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__))

d = {
"slug": "menshikov-tower",
"name_vi": "Tháp Menshikov (Nhà thờ Tổng lãnh thiên thần Gabriel)",
"name_ru": "Меншикова башня (Церковь Архангела Гавриила)",
"name_en": "Menshikov Tower (Church of the Archangel Gabriel)",
"subtitle": "Nhà thờ – tháp chuông baroque cao vút bên Ao Trong, do Hoàng thân Aleksandr Menshikov cho dựng đầu thế kỷ 18 — công trình baroque Petrine cổ nhất còn lại ở Moskva, từng cao hơn cả Tháp chuông Ivan Đại đế và là toà nhà cao nhất thành phố thời bấy giờ.",
"sections": [
 {"heading": "Giới thiệu chung", "paras": [
  "Ẩn mình trong một con ngõ nhỏ yên tĩnh gần Ao Trong (Chistye Prudy), giữa vành đai Đại lộ của Moskva, Tháp Menshikov — tên chính thức là Nhà thờ Tổng lãnh thiên thần Gabriel (tiếng Nga: Церковь Архангела Гавриила) — là một trong những công trình kiến trúc độc đáo và giàu câu chuyện bậc nhất của thủ đô. Vừa là một nhà thờ Chính thống giáo đang hoạt động, vừa là một tháp chuông baroque cao vút, công trình mang trong mình cả vẻ đẹp nghệ thuật lẫn những giai thoại lịch sử ly kỳ.",
  "Điều làm nên tầm quan trọng đặc biệt của tháp là vị trí của nó trong lịch sử kiến trúc Nga: đây được xem là công trình baroque Petrine — tức phong cách baroque thời Pyotr Đại đế — cổ nhất còn tồn tại ở Moskva. Ra đời vào những năm đầu thế kỷ 18, khi Pyotr Đại đế đang tiến hành cải cách sâu rộng và mở cửa nước Nga sang phương Tây, tháp là hiện thân của một thời đại chuyển mình, khi những hình thức kiến trúc châu Âu bắt đầu du nhập và hoà quyện với truyền thống bản địa.",
  "Người đứng sau công trình là Hoàng thân Aleksandr Menshikov — sủng thần quyền lực bậc nhất của Pyotr Đại đế, cũng là một trong những nhân vật đầy tranh cãi và bi kịch nhất lịch sử Nga. Chính tham vọng và sự giàu có của Menshikov đã sản sinh ra một công trình vượt tầm thời đại: một ngọn tháp cao đến mức từng vượt qua cả Tháp chuông Ivan Đại đế trong Điện Kremlin, trở thành toà nhà cao nhất Moskva thời bấy giờ. Vì lẽ đó, dân gian quen gọi công trình bằng chính tên chủ nhân của nó — Tháp Menshikov.",
  "Trải qua hơn ba thế kỷ với biết bao biến cố — từ một trận sét lịch sử thiêu rụi phần chóp, tới những lần trùng tu và cả thời kỳ bị đóng cửa dưới chính quyền Xô-viết — tháp vẫn đứng vững và giữ được nét đẹp baroque quyến rũ. Ngày nay, đây là một nhà thờ đang hoạt động, đồng thời là một điểm đến hấp dẫn cho những ai muốn khám phá một Moskva ít ồn ào hơn, nơi lịch sử và nghệ thuật lắng đọng trong từng chi tiết.",
  "Là tài liệu thuyết minh nội bộ, phần trình bày dưới đây tổng hợp và biên soạn lại từ các nguồn tư liệu tiếng Anh và tiếng Nga về lịch sử, kiến trúc và những giai thoại gắn với công trình. Mục tiêu là cung cấp cho hướng dẫn viên đầy đủ chất liệu để kể một câu chuyện hấp dẫn về ngọn tháp và về số phận thăng trầm của vị hoàng thân đã cho dựng nên nó."
 ]},
 {"heading": "Vị trí & cách di chuyển", "paras": [
  "Tháp Menshikov toạ lạc tại số 15a ngõ Arkhangelsky (Arkhangelsky pereulok), thuộc quận Basmanny, nằm trong vành đai Đại lộ (Bulvarnoye Koltso) và rất gần Ao Trong (Chistye Prudy) — một trong những góc lãng mạn và được yêu thích nhất của Moskva. Toạ độ địa lý xấp xỉ 55,76 độ vĩ Bắc và 37,64 độ kinh Đông. Do nằm khuất trong một con ngõ nhỏ, tháp mang lại cảm giác như một khám phá bất ngờ giữa lòng thành phố.",
  "Cách tiếp cận thuận tiện nhất là bằng tàu điện ngầm. Có tới ba ga nằm trong khoảng cách đi bộ hợp lý: ga Chistye Prudy (tuyến số 1, màu đỏ), ga Turgenevskaya (tuyến số 6, màu cam) và ga Sretensky Bulvar (tuyến số 10, màu xanh lá) — cả ba đều là các ga chuyển tuyến kết nối với nhau. Từ khu vực Ao Trong, du khách chỉ cần đi bộ vài phút men theo các con ngõ nhỏ là tới tháp.",
  "Vì tháp nằm khuất trong ngõ Arkhangelsky, du khách nên sử dụng bản đồ điện thoại để định vị chính xác, tránh đi lạc. Đây vừa là một thử thách nhỏ vừa là một phần thú vị của trải nghiệm, bởi con đường dẫn tới tháp đưa du khách len lỏi qua những góc phố cổ yên tĩnh, khác hẳn sự sầm uất của các đại lộ lớn. Cảm giác bất chợt bắt gặp ngọn tháp baroque vươn lên sau dãy nhà thấp là một ấn tượng khó quên.",
  "Nếu di chuyển bằng taxi hay xe công nghệ, du khách có thể lấy mốc là Ao Trong (Chistye Prudy) hoặc ngõ Arkhangelsky. Tuy nhiên, do khu vực trung tâm thường đông đúc và nhiều đường một chiều, việc kết hợp tàu điện ngầm với đi bộ vẫn là phương án linh hoạt và thú vị nhất. Khu vực này cũng rất thích hợp để tản bộ, nên du khách không cần vội vã.",
  "Về tổ chức lộ trình, tháp rất dễ ghép với một buổi dạo bộ khám phá vành đai Đại lộ và Ao Trong. Đây là điểm dừng lý tưởng để lồng vào hành trình đi bộ ngắm phố cổ, kết hợp với việc nghỉ chân bên hồ, thưởng thức cà phê và cảm nhận nhịp sống thư thái của người Moskva. Với thời lượng tham quan chỉ khoảng hai mươi đến ba mươi phút, tháp phù hợp làm một điểm nhấn nghệ thuật – tâm linh trong một buổi dạo chơi thảnh thơi."
 ]},
 {"heading": "Lịch sử hình thành và phát triển", "paras": [
  "Công trình được Hoàng thân Aleksandr Menshikov cho khởi dựng trong các năm 1704–1707, trên khu đất gần dinh thự của ông ở khu vực Ao Trong. Là sủng thần quyền lực và giàu có bậc nhất dưới triều Pyotr Đại đế, Menshikov muốn có một nhà thờ – tháp chuông tương xứng với địa vị của mình. Ông đã không tiếc tiền của để mời những người thợ giỏi nhất và cho xây một công trình vượt trội về cả chiều cao lẫn sự tinh xảo, đủ sức làm rạng danh gia tộc.",
  "Phần thiết kế và thi công được giao cho kiến trúc sư Ivan Zarudny, với sự tham gia của Domenico Trezzini cùng một nhóm thợ thủ công người Ý – Thụy Sĩ đến từ các bang Ticino và Fribourg, và những người thợ đá Nga lành nghề từ Kostroma và Yaroslavl. Sự cộng tác giữa thợ phương Tây và thợ Nga này chính là đặc trưng của thời đại Pyotr Đại đế, khi nước Nga chủ động tiếp thu kỹ thuật và thẩm mỹ châu Âu để hiện đại hoá. Kết quả là một công trình baroque Petrine tiêu biểu, kết hợp hình thức châu Âu với tay nghề bản địa.",
  "Khi hoàn thành, tháp cao khoảng tám mươi mốt tới tám mươi tư mét (tính cả phần chóp gỗ), vượt qua Tháp chuông Ivan Đại đế trong Điện Kremlin — vốn cao tám mươi mốt mét và từ lâu là công trình cao nhất Moskva. Đỉnh tháp là một chóp gỗ cao chừng ba mươi mét, trên cùng gắn tượng thiên thần mạ vàng cầm thánh giá. Tháp còn được trang bị tới năm mươi quả chuông và một chiếc đồng hồ điểm chuông kiểu Anh — những chi tiết xa hoa và tân tiến hiếm thấy vào thời đó, càng làm nổi bật sự giàu sang và tham vọng của chủ nhân.",
  "Số phận của tháp gắn với một biến cố nổi tiếng: năm 1723, một tia sét đã đánh trúng và thiêu rụi phần chóp gỗ cùng tượng thiên thần trên đỉnh. Sau tai hoạ, công trình rơi vào cảnh hư hại trong nhiều thập niên, một phần cũng vì chủ nhân của nó — Hoàng thân Menshikov — đã thất sủng và bị lưu đày. Mãi tới thập niên 1770, tháp mới được phục dựng, và diện mạo baroque với mái vòm như ta thấy ngày nay chính là kết quả của lần trùng tu này, không còn giữ được độ cao chót vót ban đầu.",
  "Trong thời kỳ Xô-viết, giống như nhiều nhà thờ khác, tháp bị đóng cửa (khoảng năm 1923) và ngừng hoạt động tôn giáo trong một thời gian dài. Tuy nhiên, nhờ giá trị kiến trúc đặc biệt, công trình được gìn giữ và không bị phá huỷ. Sau này, nhà thờ được khôi phục hoạt động và hiện gắn với đại diện của Giáo hội Chính thống Antioch tại Moskva. Ngày nay, tháp vừa là nơi thờ tự, vừa là một di sản kiến trúc quý được bảo vệ, tiếp tục kể câu chuyện của mình cho các thế hệ mới."
 ]},
 {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
  "Về mặt phong cách, Tháp Menshikov là hiện thân tiêu biểu của baroque Petrine — dòng baroque đặc thù của nước Nga thời Pyotr Đại đế. Khác với baroque Ý cổ điển vốn phô diễn sự rườm rà, nhiều chi tiết, baroque Petrine mang tính tiết chế, chú trọng sự cân đối, đăng đối và những đường nét khoẻ khoắn. Chính sự pha trộn giữa tinh thần châu Âu và cách xử lý chừng mực này tạo nên nét duyên riêng cho công trình.",
  "Cấu trúc của tháp gồm nhiều tầng thu nhỏ dần lên cao, tạo thành một khối vươn lên đầy khí thế. Các tầng dưới bằng đá được xây dựng vững chãi, với hệ thống cột, bổ trụ và các chi tiết trang trí điêu khắc tinh xảo. Những mảng phù điêu, hoa văn và tượng trang trí do các nghệ nhân Ý – Thụy Sĩ và thợ Nga thực hiện thể hiện trình độ điêu khắc cao, khiến bề mặt công trình sống động và giàu chiều sâu thị giác, chứ không đơn điệu như nhiều nhà thờ cùng thời.",
  "Nguyên bản, phần đỉnh tháp là một chóp gỗ cao vút gắn tượng thiên thần mạ vàng — chi tiết vừa mang ý nghĩa tôn giáo (thiên thần Gabriel, vị tổng lãnh thiên thần mà nhà thờ được cung hiến) vừa là điểm nhấn thẩm mỹ giúp tháp vươn lên tầm cao kỷ lục. Sau trận sét năm 1723 và lần phục dựng thập niên 1770, phần đỉnh được thay bằng một mái vòm baroque uốn lượn mềm mại như hiện nay, tuy thấp hơn nhưng vẫn giữ được vẻ thanh thoát đặc trưng.",
  "Một điểm đặc biệt trong lịch sử công trình là chiếc đồng hồ điểm chuông kiểu Anh cùng bộ năm mươi quả chuông — những thiết bị tân tiến và đắt đỏ vào đầu thế kỷ 18. Chi tiết này cho thấy tham vọng của Menshikov không chỉ dừng ở kiến trúc mà còn ở việc trang bị cho công trình những tiện nghi hiện đại nhất thời đại, biến tháp thành một biểu tượng của sự giàu sang và tầm nhìn hướng về phương Tây.",
  "Xét tổng thể, Tháp Menshikov là một tác phẩm kết tinh giữa tham vọng cá nhân, tài năng nghệ thuật và tinh thần cải cách của một thời đại. Việc công trình vẫn giữ được nét đẹp baroque sau bao thăng trầm khiến nó trở thành một 'chứng nhân' quý giá cho buổi giao thời của kiến trúc Nga, khi những ảnh hưởng châu Âu lần đầu để lại dấu ấn đậm nét trên bầu trời Moskva. Đây là lý do các nhà nghiên cứu luôn xếp tháp vào hàng những công trình có giá trị lịch sử – nghệ thuật đặc biệt của thành phố."
 ]},
 {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
  "Điểm nhấn đầu tiên là dáng vẻ tổng thể của ngọn tháp vươn cao giữa những dãy nhà thấp trong ngõ Arkhangelsky. Khoảnh khắc bất chợt bắt gặp tháp sau khi len qua các con ngõ nhỏ là một trải nghiệm thị giác đầy bất ngờ. Hướng dẫn viên nên chọn một góc nhìn đẹp để đoàn chiêm ngưỡng trọn vẹn hình khối nhiều tầng thu nhỏ dần và mái vòm baroque duyên dáng của công trình.",
  "Điểm nhấn thứ hai là các chi tiết điêu khắc và trang trí baroque trên bề mặt tháp. Những mảng phù điêu, hoa văn, cột và tượng do các nghệ nhân Ý – Thụy Sĩ và thợ Nga thực hiện là tinh hoa nghệ thuật của công trình. Việc quan sát kỹ những chi tiết này giúp du khách cảm nhận được trình độ tay nghề và sự cầu kỳ mà chủ nhân đã đầu tư, đồng thời hiểu rõ hơn đặc trưng của phong cách baroque Petrine.",
  "Điểm nhấn thứ ba là câu chuyện về chiều cao kỷ lục và trận sét lịch sử. Dù ngày nay tháp không còn cao như nguyên bản, việc hình dung về ngọn tháp từng vượt qua Tháp chuông Ivan Đại đế để trở thành công trình cao nhất Moskva, rồi bị sét đánh thiêu rụi phần chóp năm 1723, khiến điểm dừng trở nên sống động và giàu kịch tính. Đây là 'điểm nhấn kể chuyện' mà hướng dẫn viên nên khai thác.",
  "Điểm nhấn thứ tư là không gian nội thất của nhà thờ đang hoạt động. Nếu vào bên trong (tuân thủ quy tắc trang phục và giờ lễ), du khách có thể cảm nhận bầu không khí tôn nghiêm, tĩnh lặng cùng những chi tiết trang trí và biểu tượng Chính thống giáo. Trải nghiệm này giúp hiểu rằng công trình không phải một di tích chết mà vẫn là nơi sinh hoạt tâm linh sống động của cộng đoàn tín hữu.",
  "Cuối cùng, đừng bỏ lỡ khung cảnh xung quanh, đặc biệt là Ao Trong (Chistye Prudy) ngay gần đó. Sự kết hợp giữa ngọn tháp baroque cổ kính và không gian hồ nước lãng mạn với hàng cây, ghế đá tạo nên một tổng thể hài hoà, rất đáng để dạo bước và cảm nhận. Đây là điểm nhấn giúp trải nghiệm tham quan tháp trở nên trọn vẹn, kết nối di sản kiến trúc với nhịp sống thư thái của khu phố."
 ]},
 {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
  "Tháp Menshikov mang ý nghĩa lịch sử đặc biệt như một biểu tượng của thời đại Pyotr Đại đế — giai đoạn nước Nga quyết liệt cải cách, mở cửa và hướng về phương Tây. Với tư cách công trình baroque Petrine cổ nhất còn lại ở Moskva, tháp là một 'cột mốc' đánh dấu sự du nhập của kiến trúc và thẩm mỹ châu Âu vào nước Nga, mở đường cho hàng loạt công trình sau này, đặc biệt là ở kinh đô mới Saint Petersburg.",
  "Về mặt văn hoá, công trình gắn liền với một trong những nhân vật hấp dẫn và bi kịch nhất lịch sử Nga: Hoàng thân Aleksandr Menshikov. Câu chuyện về ngọn tháp vì thế không thể tách rời khỏi câu chuyện về sự thăng tiến chóng mặt và sụp đổ thảm khốc của chủ nhân nó. Tháp trở thành một 'đài tưởng niệm' bất đắc dĩ cho tham vọng con người, cho sự phù du của quyền lực và danh vọng — một bài học nhân sinh sâu sắc ẩn sau vẻ đẹp kiến trúc.",
  "Sự kiện tháp từng vượt chiều cao của Tháp chuông Ivan Đại đế cũng mang ý nghĩa biểu tượng thú vị. Trong nhiều thế kỷ, Tháp chuông Ivan Đại đế là công trình cao nhất Moskva và tồn tại một quy ước bất thành văn rằng không công trình nào được phép cao hơn nó. Việc Menshikov dám phá vỡ quy ước này thể hiện cả sự táo bạo của cá nhân ông lẫn tinh thần dám thách thức truyền thống của thời đại Pyotr — và trận sét năm 1723 sau đó dễ khiến người đương thời liên tưởng tới một sự 'trừng phạt' đầy màu sắc dân gian.",
  "Về mặt nghệ thuật, tháp là một mẫu mực để nghiên cứu phong cách baroque Petrine và quá trình chuyển tiếp của kiến trúc Nga. Sự cộng tác giữa kiến trúc sư và thợ Nga với các nghệ nhân châu Âu tại công trình phản ánh mô hình 'tiếp biến văn hoá' đặc trưng của thời đại — không sao chép nguyên xi mà tiếp thu, biến đổi để tạo nên một phong cách mang bản sắc riêng. Đây là giá trị khiến giới nghiên cứu kiến trúc luôn dành sự quan tâm đặc biệt cho công trình.",
  "Cuối cùng, việc tháp tồn tại và tiếp tục hoạt động như một nhà thờ cho tới ngày nay, vượt qua cả những giai đoạn khắc nghiệt nhất, cho thấy sức sống bền bỉ của di sản. Tháp không chỉ là một hiện vật để chiêm ngưỡng mà còn là một không gian tâm linh sống động, nơi quá khứ và hiện tại giao hoà. Trong ý nghĩa đó, công trình là một minh chứng cho khả năng của di sản trong việc kết nối các thế hệ và giữ gìn ký ức văn hoá của một dân tộc."
 ]},
 {"heading": "Trải nghiệm dành cho du khách", "paras": [
  "Trải nghiệm cốt lõi tại Tháp Menshikov là sự khám phá một viên ngọc kiến trúc ẩn giấu, mang lại cảm giác yên tĩnh và chiêm nghiệm rất khác so với các điểm đến đông đúc ở trung tâm. Việc len qua các con ngõ nhỏ để bất chợt bắt gặp ngọn tháp baroque vươn cao là một trải nghiệm giàu cảm xúc, đặc biệt hấp dẫn với những du khách thích tìm tòi những góc Moskva ít người biết.",
  "Đối với những ai yêu kiến trúc và lịch sử, tháp là một 'kho tư liệu sống' để tìm hiểu về phong cách baroque Petrine, về thời đại Pyotr Đại đế và về số phận của Hoàng thân Menshikov. Đứng trước công trình và nghe kể những câu chuyện gắn với nó, du khách có thể hình dung cả một chương lịch sử sống động, khi vẻ đẹp nghệ thuật đan xen với những bi kịch của quyền lực và tham vọng.",
  "Nếu có dịp vào bên trong nhà thờ (tuân thủ đúng quy tắc), du khách sẽ được trải nghiệm không gian tâm linh Chính thống giáo với sự tĩnh lặng và trang nghiêm đặc trưng. Đây là cơ hội để cảm nhận rằng công trình vẫn là một nơi thờ tự sống động, chứ không đơn thuần là hiện vật bảo tàng. Tuy nhiên, du khách cần lưu ý ăn mặc lịch sự, nữ nên trùm khăn, và giữ thái độ tôn trọng nếu đang có buổi lễ.",
  "Trải nghiệm tại tháp cũng nên được đặt trong một bối cảnh rộng hơn: một buổi dạo bộ thư thái quanh Ao Trong và vành đai Đại lộ. Sự kết hợp giữa việc chiêm ngưỡng di sản kiến trúc và thư giãn bên hồ nước, dưới bóng cây, tạo nên một trải nghiệm cân bằng giữa văn hoá và nghỉ ngơi. Đây chính là cách người Moskva tận hưởng khu vực này, và du khách có thể học theo để cảm nhận trọn vẹn tinh thần của nơi đây.",
  "Thời lượng tham quan hợp lý khoảng hai mươi đến ba mươi phút cho riêng ngọn tháp, hoặc lâu hơn nếu kết hợp dạo Ao Trong. Là một điểm dừng nhỏ nhưng giàu chất thơ và chiều sâu lịch sử, tháp phù hợp để mang lại một khoảnh khắc lắng đọng, khác biệt trong hành trình khám phá Moskva, đặc biệt với những đoàn khách yêu thích chiều sâu văn hoá hơn là những điểm đến hoành tráng nhưng đông đúc."
 ]},
 {"heading": "Mẹo tham quan", "paras": [
  "Về việc tìm đường, do tháp nằm khuất trong ngõ Arkhangelsky, du khách nên sử dụng bản đồ điện thoại và định vị sẵn trước khi xuất phát. Lấy Ao Trong (Chistye Prudy) làm mốc rồi men theo các ngõ nhỏ là cách dễ nhất. Đừng ngại việc phải đi lòng vòng đôi chút, bởi chính hành trình khám phá này là một phần thú vị của trải nghiệm.",
  "Về trang phục và ứng xử, vì đây là nhà thờ Chính thống đang hoạt động, du khách nên ăn mặc lịch sự: nữ nên có khăn trùm đầu và tránh mặc quá hở, nam nên bỏ mũ khi vào. Nếu đến đúng giờ lễ, hãy giữ im lặng, đi lại nhẹ nhàng và tránh chụp ảnh làm ảnh hưởng tới người đang cầu nguyện. Việc vào cửa thường miễn phí, có thể quyên góp tuỳ tâm.",
  "Về thời điểm, ban ngày với ánh sáng tốt là lúc lý tưởng để ngắm và chụp các chi tiết điêu khắc baroque tinh xảo trên thân tháp. Buổi sáng thường yên tĩnh hơn, thích hợp cho việc chiêm ngưỡng và chụp ảnh. Nếu muốn kết hợp không khí lãng mạn của Ao Trong, buổi chiều muộn khi nắng dịu cũng là một lựa chọn đẹp.",
  "Về lộ trình kết hợp, hãy tận dụng vị trí gần Ao Trong và vành đai Đại lộ để tổ chức một buổi dạo bộ khám phá phố cổ. Có thể ghép tháp với việc nghỉ chân bên hồ, thưởng thức cà phê tại các quán quanh khu vực, và tản bộ dọc các đại lộ rợp bóng cây. Đây là cách biến một điểm dừng nhỏ thành một trải nghiệm thư thái và đáng nhớ.",
  "Cuối cùng, về nội dung thuyết minh, hãy chuẩn bị những câu chuyện đắt giá: công trình baroque Petrine cổ nhất Moskva, tham vọng và bi kịch của Hoàng thân Menshikov, chiều cao kỷ lục từng vượt Tháp chuông Ivan Đại đế, và trận sét lịch sử năm 1723. Những giai thoại này, nếu được kể khéo léo, sẽ biến một ngọn tháp tưởng chừng khiêm nhường thành một điểm dừng đầy kịch tính và cuốn hút trong mắt du khách."
 ]},
 {"heading": "Khám phá xung quanh", "paras": [
  "Ngay gần tháp là Ao Trong (Chistye Prudy) — một trong những góc lãng mạn và được yêu thích nhất của Moskva. Hồ nước cùng Đại lộ Chistoprudny rợp bóng cây là nơi lý tưởng để dạo bộ, nghỉ ngơi và cảm nhận nhịp sống thư thái của người dân thủ đô. Vào mùa đông, mặt hồ có thể đóng băng và trở thành sân trượt băng ngoài trời, mang lại một khung cảnh đậm chất Nga.",
  "Vành đai Đại lộ (Bulvarnoye Koltso) mà tháp toạ lạc là một tuyến đi bộ đẹp, nối liền nhiều quảng trường, tượng đài và công trình kiến trúc thú vị. Dạo bộ dọc theo vành đai này, du khách có thể khám phá nhiều lớp lịch sử và kiến trúc của Moskva, từ các dinh thự cổ tới những công trình thời Xô-viết, trong một không gian xanh mát và dễ chịu.",
  "Không xa khu vực này là phố Myasnitskaya với nhiều công trình kiến trúc đáng chú ý, trong đó có toà nhà Bưu điện Trung tâm và các dinh thự mang phong cách đa dạng. Con phố này từng là một trong những trục thương mại quan trọng của Moskva và nay vẫn giữ được nhiều nét kiến trúc lịch sử, là điểm dạo bộ thú vị để bổ sung cho hành trình.",
  "Về phía trung tâm, du khách có thể dễ dàng tiếp cận khu vực Lubyanka và từ đó tới Quảng trường Đỏ, Kitay-Gorod với những nhà thờ cổ và các con phố lịch sử. Vị trí của tháp trong vành đai Đại lộ khiến nó trở thành một điểm khởi đầu hoặc điểm dừng thuận tiện cho những hành trình khám phá trung tâm Moskva bằng cách đi bộ.",
  "Khu vực quanh Ao Trong cũng nổi tiếng với đời sống về đêm và văn hoá cà phê sôi động, với nhiều quán ăn, quán bar và không gian sáng tạo. Sau khi tham quan tháp, du khách có thể nán lại thưởng thức một bữa ăn hoặc ly cà phê, hoà mình vào nhịp sống trẻ trung của một trong những khu phố được giới trẻ Moskva yêu thích nhất. Đây là cách kết thúc trải nghiệm một cách ấm áp và gần gũi."
 ]},
 {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
  "Không thể nói về Tháp Menshikov mà không kể câu chuyện ly kỳ về chủ nhân của nó — Hoàng thân Aleksandr Menshikov. Theo giai thoại phổ biến, Menshikov xuất thân hết sức khiêm tốn, thời trẻ được cho là từng bán bánh nướng rong trên đường phố Moskva. Nhờ tài năng, sự lanh lợi và lòng trung thành, ông trở thành bạn thân và cánh tay phải của Pyotr Đại đế, rồi vươn lên thành người quyền lực và giàu có bậc nhất nước Nga — một bước thăng tiến thần kỳ hiếm có trong lịch sử.",
  "Thế nhưng, số phận của Menshikov cũng bi kịch không kém phần huy hoàng. Sau khi Pyotr Đại đế qua đời, quyền lực của ông suy giảm nhanh chóng trong các cuộc tranh giành nơi cung đình. Cuối cùng, ông bị thất sủng, tước bỏ mọi chức tước và tài sản, rồi bị lưu đày tới Berezovo ở Siberia xa xôi, nơi ông qua đời trong cảnh hàn vi. Ngọn tháp lộng lẫy ông từng cho dựng vì thế trở thành một biểu tượng đầy ám ảnh về sự phù du của vinh hoa và quyền lực.",
  "Trận sét năm 1723 thiêu rụi phần chóp gỗ và tượng thiên thần trên đỉnh tháp cũng là một giai thoại được lưu truyền rộng rãi. Với người đương thời, hình ảnh ngọn tháp cao ngạo từng dám vượt qua Tháp chuông Ivan Đại đế rồi bị 'trời trừng phạt' bằng một tia sét mang màu sắc của một truyền thuyết dân gian, gợi những suy ngẫm về sự kiêu hãnh và giới hạn của con người. Chi tiết này khiến câu chuyện về tháp càng thêm phần kịch tính.",
  "Một chi tiết thú vị khác là truyền thống sử dụng nhà thờ theo mùa. Tháp Menshikov (Nhà thờ Tổng lãnh thiên thần Gabriel) theo truyền thống chỉ hành lễ vào mùa hè; còn mùa đông giá lạnh, cộng đoàn tín hữu chuyển sang nhà thờ Thánh Theodore Stratelates gần đó, được xây dựng trong khoảng các năm 1782–1806. Sự tồn tại của một cặp nhà thờ 'mùa hè – mùa đông' như vậy là một nét đặc trưng thú vị trong đời sống tôn giáo Nga, phản ánh sự thích ứng với khí hậu khắc nghiệt.",
  "Cuối cùng, mối liên hệ giữa Tháp Menshikov và kinh đô Saint Petersburg cũng là một giai thoại đáng suy ngẫm. Chính Menshikov là người được Pyotr Đại đế giao trọng trách trong việc xây dựng Saint Petersburg, và nhiều người thợ, ý tưởng kiến trúc từng góp mặt tại ngọn tháp ở Moskva về sau cũng gắn với công cuộc dựng xây kinh đô mới. Trong ý nghĩa đó, Tháp Menshikov như một 'khúc dạo đầu' cho làn sóng baroque Petrine sẽ nở rộ rực rỡ trên đất Saint Petersburg — một sợi dây kết nối tinh tế giữa hai thành phố lớn của nước Nga mà hướng dẫn viên có thể khéo léo gợi mở."
 ]}
],
"highlights": [
 "Công trình baroque Petrine cổ nhất còn lại ở Moskva, do Hoàng thân Aleksandr Menshikov cho dựng năm 1704–1707.",
 "Kiến trúc sư Ivan Zarudny cùng Domenico Trezzini, thợ Ý – Thụy Sĩ và thợ đá Nga từ Kostroma, Yaroslavl.",
 "Ban đầu cao khoảng 81–84 m — vượt Tháp chuông Ivan Đại đế (81 m) và là toà nhà cao nhất Moskva thời bấy giờ.",
 "Đỉnh nguyên bản là chóp gỗ ~30 m gắn tượng thiên thần mạ vàng, có 50 chuông và đồng hồ điểm chuông kiểu Anh.",
 "Năm 1723 bị sét đánh cháy phần chóp; phục dựng thập niên 1770 với mái vòm baroque hiện nay.",
 "Nay là nhà thờ Chính thống đang hoạt động (đại diện Giáo hội Antioch tại Moskva).",
 "Nằm khuất trong ngõ Arkhangelsky, gần Ao Trong (Chistye Prudy) trong vành đai Đại lộ.",
 "Gắn với số phận thăng trầm của Hoàng thân Menshikov — từ sủng thần quyền lực tới bị lưu đày ở Siberia."
],
"images": [
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Menshikov%20tower%20(1).jpg", "caption": "Tháp Menshikov (Nhà thờ Tổng lãnh thiên thần Gabriel) vươn cao giữa khu phố cổ gần Ao Trong."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Menshikov%20tower%20(2).jpg", "caption": "Cận cảnh khối tháp nhiều tầng và mái vòm baroque của công trình."}
],
"references": [
 {"title": "Menshikov Tower — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Menshikov_Tower"},
 {"title": "Styled in Petrine Baroque: the uniqueness of Menshikov Tower — mos.ru", "url": "https://www.mos.ru/en/news/item/95092073/"},
 {"title": "Menshikov Tower and St Theodore Stratelates' Church — Rusmania", "url": "https://rusmania.com/central/moscow-federal-city/moscow/krasnoselsky/around-the-boulevard-ring-chistoprudny-bulvar/menshikov-tower-and-st-theodore-stratelates-church"},
 {"title": "Church of Archangel Gabriel, Moscow — Advantour", "url": "https://www.advantour.com/russia/moscow/churches/church-of-archangel-gabriel.htm"},
 {"title": "Church of St Theodore Tyron and Archangel Gabriel — um.mos.ru", "url": "https://um.mos.ru/en/houses/church-of-st-theodore-tyron-and-archangel-gabriel/"}
],
"sources": [
 "Wikipedia tiếng Anh — mục 'Menshikov Tower' (xây 1704–1707 theo lệnh Menshikov, kiến trúc sư Ivan Zarudny cùng Domenico Trezzini và thợ Ý – Thụy Sĩ, baroque Petrine cổ nhất Moskva, chiều cao ~84 m với chóp gỗ và tượng thiên thần, sét đánh 1723, phục dựng thập niên 1770, đóng cửa 1923, nhà thờ mùa hè – mùa đông với St Theodore Stratelates).",
 "Cổng thông tin Chính quyền Moskva (mos.ru), bài 'Styled in Petrine Baroque: the uniqueness of Menshikov Tower' — đặc trưng phong cách và giá trị công trình.",
 "Rusmania — hồ sơ 'Menshikov Tower and St Theodore Stratelates' Church' (bố cục, vị trí, lịch sử).",
 "Advantour — mô tả lịch sử và kiến trúc Nhà thờ Tổng lãnh thiên thần Gabriel.",
 "um.mos.ru — hồ sơ di sản về cặp nhà thờ St Theodore Tyron và Archangel Gabriel.",
 "Dữ liệu dự án 'Cẩm nang Du lịch Nga' (data/regions/moscow) — địa chỉ ngõ Arkhangelsky 15a, số liệu chiều cao ~81 m, 50 chuông, đồng hồ kiểu Anh.",
 "Thông tin nền về Hoàng thân Aleksandr Menshikov (xuất thân, thăng tiến, lưu đày Berezovo) tổng hợp từ các nguồn bách khoa phổ biến.",
 "Thông tin nền về baroque Petrine và bối cảnh cải cách thời Pyotr Đại đế tổng hợp từ tư liệu lịch sử – kiến trúc phổ biến."
]
}

def norm(o):
    if isinstance(o, str): return unicodedata.normalize("NFC", o)
    if isinstance(o, list): return [norm(x) for x in o]
    if isinstance(o, dict): return {k: norm(v) for k, v in o.items()}
    return o
d = norm(d)

out = os.path.join(HERE, "doc_" + d["slug"] + ".json")
json.dump(d, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
wc = sum(len(p.split()) for s in d["sections"] for p in s["paras"])
print("WROTE", out, "| sections:", len(d["sections"]), "| body words:", wc)
