# -*- coding: utf-8 -*-
import json, os, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__))

d = {
"slug": "yaroslavsky-railway-station",
"name_vi": "Ga xe lửa Yaroslavsky",
"name_ru": "Ярославский вокзал",
"name_en": "Moscow Yaroslavsky Railway Station",
"subtitle": "Nhà ga nhộn nhịp bậc nhất Moskva và là điểm khởi đầu của Đường sắt xuyên Siberia — tuyến đường sắt dài nhất thế giới. Toà nhà do kiến trúc sư thiên tài Fyodor Shekhtel thiết kế theo phong cách Tân Nga pha Art Nouveau, với tháp cổng cao vút, mái lều và những mảng gạch men majolica gợi hình phương Bắc nước Nga.",
"sections": [
 {"heading": "Giới thiệu chung", "paras": [
  "Đứng trên Quảng trường Komsomolskaya — nơi người Moskva quen gọi bằng cái tên đầy hình ảnh 'Quảng trường Ba Nhà Ga' — Ga Yaroslavsky (tiếng Nga: Ярославский вокзал) là một trong những đầu mối giao thông đường sắt nhộn nhịp và nổi tiếng nhất của thủ đô nước Nga. Không chỉ là nơi đưa đón hàng chục nghìn lượt khách mỗi ngày, nhà ga còn mang một vị thế đặc biệt trong tâm thức người Nga: đây chính là điểm khởi đầu của Đường sắt xuyên Siberia huyền thoại, tuyến đường sắt dài nhất hành tinh nối liền Moskva với Viễn Đông.",
  "Điều khiến Ga Yaroslavsky trở thành một điểm tham quan chứ không đơn thuần là một nhà ga chức năng nằm ở toà nhà mặt tiền tuyệt đẹp của nó. Công trình hiện nay được xây dựng trong các năm 1902–1904 theo thiết kế của Fyodor Shekhtel — kiến trúc sư hàng đầu của trường phái Art Nouveau (Tân nghệ thuật) Nga. Với tháp cổng cao vút, những mái lều dốc kiểu Nga cổ và các mảng gạch men majolica ánh xanh ngọc, mặt tiền nhà ga trông như một cánh cổng thần thoại mở ra vùng đất phương Bắc và Siberia xa xôi.",
  "Về mặt biểu tượng, Ga Yaroslavsky gói trọn tinh thần của một cuộc hành trình vĩ đại. Từ sân ga này, những đoàn tàu lăn bánh về hướng Đông, băng qua dãy Ural, vượt Siberia bao la, để rồi sau gần chín nghìn ba trăm cây số dừng lại bên bờ Thái Bình Dương ở Vladivostok. Chính vì thế, ngay cả với những du khách không có ý định đi tàu, việc ghé thăm nhà ga cũng gợi lên cảm giác phiêu lưu, khát khao lên đường và chiêm ngưỡng sự mênh mông của nước Nga.",
  "Nhà ga nằm liền kề hai nhà ga lớn khác là Leningradsky và Kazansky, tạo thành cụm ba nhà ga độc đáo hiếm có trên thế giới. Vị trí trung tâm, ngay cạnh ga tàu điện ngầm Komsomolskaya, khiến nơi đây trở thành một trong những nút giao thông sầm uất nhất Moskva, đồng thời cũng là một bảo tàng kiến trúc ngoài trời, nơi ba phong cách và ba tầm nhìn kiến trúc khác nhau cùng phô diễn trên một quảng trường.",
  "Là tài liệu thuyết minh nội bộ, phần trình bày dưới đây tổng hợp và biên soạn lại từ các nguồn tư liệu tiếng Anh và tiếng Nga về lịch sử, kiến trúc và ý nghĩa của nhà ga. Mục tiêu là giúp hướng dẫn viên có đủ chất liệu để biến một điểm dừng tưởng chừng chỉ mang tính chức năng thành một câu chuyện hấp dẫn về nghệ thuật, lịch sử và những chuyến đi vĩ đại của nước Nga."
 ]},
 {"heading": "Vị trí & cách di chuyển", "paras": [
  "Ga Yaroslavsky nằm tại số 5 Quảng trường Komsomolskaya (Komsomolskaya ploshchad), thuộc quận Krasnoselsky ở phía Đông Bắc trung tâm Moskva, với mã bưu chính 107140. Quảng trường này nổi tiếng với biệt danh 'Quảng trường Ba Nhà Ga' vì là nơi hội tụ của ba đầu mối đường sắt lớn: Ga Yaroslavsky, Ga Leningradsky (đi Saint Petersburg) và Ga Kazansky. Toạ độ địa lý của nhà ga xấp xỉ 55,78 độ vĩ Bắc và 37,66 độ kinh Đông.",
  "Cách tiếp cận thuận tiện nhất là bằng tàu điện ngầm. Du khách xuống ga Komsomolskaya, vốn nằm trên cả tuyến vòng (tuyến số 5, màu nâu) lẫn tuyến Sokolnicheskaya (tuyến số 1, màu đỏ). Điều đặc biệt là bản thân ga tàu điện ngầm Komsomolskaya trên tuyến vòng cũng là một kiệt tác kiến trúc lộng lẫy theo phong cách Đế chế Stalin, với trần vòm dát vàng và các bức tranh khảm mosaic — nên hành trình tới nhà ga đã là một trải nghiệm thị giác thú vị ngay từ dưới lòng đất.",
  "Nếu di chuyển bằng taxi hoặc xe riêng, du khách có thể lấy mốc là Quảng trường Komsomolskaya. Tuy nhiên, cần lưu ý đây là một trong những khu vực đông đúc và phức tạp về giao thông nhất Moskva, đặc biệt vào giờ cao điểm khi dòng người và hành lý đổ về ba nhà ga cùng lúc. Vì vậy, phương tiện công cộng thường là lựa chọn tối ưu để tránh ùn tắc và khó khăn khi tìm chỗ đỗ.",
  "Việc vào tham quan khu vực sảnh và ngắm mặt tiền nhà ga là hoàn toàn tự do; du khách chỉ cần mua vé nếu có ý định đi tàu. Sảnh chính và các không gian chờ mở phục vụ hành khách trong phần lớn thời gian trong ngày, nên có thể linh hoạt sắp xếp thời điểm ghé thăm. Tuy vậy, do lượng người qua lại rất lớn, du khách cần đặc biệt chú ý giữ gìn tư trang và cảnh giác với tình trạng móc túi thường thấy ở các nhà ga lớn.",
  "Về tổ chức lộ trình, do nằm ngay trung tâm và cạnh ga tàu điện ngầm, Ga Yaroslavsky rất dễ ghép vào hành trình. Cách hay nhất là tham quan trọn cụm ba nhà ga trên Quảng trường Komsomolskaya trong cùng một lượt, kết hợp chiêm ngưỡng ga tàu điện ngầm Komsomolskaya lộng lẫy bên dưới. Điểm dừng này cũng phù hợp để mở đầu cho các chương trình đi tàu khám phá vùng Vành đai Vàng hay hành trình xuyên Siberia."
 ]},
 {"heading": "Lịch sử hình thành và phát triển", "paras": [
  "Lịch sử nhà ga bắt đầu từ năm 1862, khi một nhà ga đầu tiên được xây dựng để phục vụ tuyến đường sắt nối Moskva với thị trấn Sergiyev Posad — nơi có Tu viện Ba Ngôi Thánh Sergiy nổi tiếng, điểm hành hương quan trọng bậc nhất của Chính thống giáo Nga. Tuyến đường ban đầu này về sau được kéo dài tới thành phố Yaroslavl, và nhà ga vì thế mang tên Yaroslavsky. Toà nhà đầu tiên khá khiêm tốn, chưa tương xứng với vai trò ngày càng lớn của tuyến đường.",
  "Bước ngoặt đến vào đầu thế kỷ 20, khi tuyến đường sắt tiếp tục vươn dài về phương Đông và trở thành một phần của Đường sắt xuyên Siberia, biến nhà ga thành cửa ngõ dẫn tới cả một lục địa. Nhu cầu về một công trình bề thế, xứng tầm đã thúc đẩy việc xây dựng lại nhà ga. Nhiệm vụ được giao cho Fyodor Shekhtel, kiến trúc sư tài danh bậc nhất Moskva thời bấy giờ, và công trình mới được thực hiện trong các năm 1902–1904.",
  "Shekhtel đã tạo nên một tác phẩm gây tiếng vang: một mặt tiền vừa hoành tráng vừa giàu chất thơ, kết hợp giữa phong cách Tân Nga (neo-Russian) lấy cảm hứng từ kiến trúc cổ truyền và ngôn ngữ Art Nouveau hiện đại. Công trình lập tức được đón nhận như một biểu tượng mới của Moskva và là một trong những đỉnh cao trong sự nghiệp của Shekhtel. Nhà ga trở thành minh chứng cho thấy kiến trúc công nghiệp – giao thông cũng có thể vươn tới tầm nghệ thuật.",
  "Trong thời kỳ Xô-viết, nhà ga tiếp tục được mở rộng và cải tạo để đáp ứng lưu lượng hành khách ngày càng tăng, nhưng phần mặt tiền lịch sử của Shekhtel về cơ bản được gìn giữ. Nhà ga chứng kiến vô số cuộc chia ly và đoàn tụ, những chuyến đi khai phá Siberia, những đợt di dân và cả những trang sử bi tráng của đất nước. Qua bao thăng trầm, Yaroslavsky vẫn giữ vai trò là một trong những đầu mối đường sắt quan trọng nhất, kết nối thủ đô với miền Bắc và Viễn Đông.",
  "Ngày nay, Ga Yaroslavsky là nhà ga có lưu lượng hành khách vào loại lớn nhất Moskva, phục vụ cả tàu đường dài lẫn tàu ngoại ô. Từ đây, hành khách có thể lên những đoàn tàu huyền thoại đi Vladivostok theo tuyến xuyên Siberia, hay đi Bắc Kinh theo tuyến xuyên Mông Cổ. Sự song hành giữa một mặt tiền lịch sử được bảo tồn và nhịp vận hành hiện đại, tấp nập khiến nhà ga trở thành một 'di sản sống', vừa phục vụ đời sống đương đại vừa lưu giữ ký ức của hơn một thế kỷ rưỡi lịch sử đường sắt Nga."
 ]},
 {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
  "Mặt tiền Ga Yaroslavsky là một trong những ví dụ tiêu biểu và quyến rũ nhất của phong cách Tân Nga pha Art Nouveau. Điểm nhấn trung tâm là một tháp cổng lớn với mái dốc cao vút kiểu 'lều' (shatyor) — hình thức mái đặc trưng của kiến trúc gỗ và nhà thờ Nga cổ ở phương Bắc. Tháp cổng này vừa đóng vai trò lối vào chính, vừa như một biểu tượng thị giác gợi hình ảnh cánh cổng dẫn vào miền đất huyền thoại của Siberia và nước Nga phương Bắc.",
  "Khi thiết kế nhà ga, Shekhtel lấy cảm hứng từ kiến trúc của Điện Kremlin Moskva và Tu viện Cứu thế ở Yaroslavl, cũng như nghệ thuật cổ truyền của các vùng Yaroslavl và Arkhangelsk ở miền Bắc. Những đường nét mái dốc, tỷ lệ khối, và cách xử lý bề mặt đều gợi nhắc tới các công trình cổ, nhưng được nhào nặn lại bằng con mắt hiện đại và tinh thần Art Nouveau, tạo nên một tổng thể vừa hoài cổ vừa mới mẻ.",
  "Trang trí là phần làm nên linh hồn của mặt tiền. Một dải phù điêu gạch men (frieze) với hoa văn thực vật ánh xanh ngọc chạy quanh công trình, được chế tác theo phác thảo của Shekhtel tại xưởng gốm Abramtsevo nổi tiếng do nhà bảo trợ nghệ thuật Savva Mamontov gây dựng. Xưởng Abramtsevo chính là cái nôi của phong trào phục hưng nghệ thuật thủ công Nga, nên việc gạch men của nhà ga ra đời từ đây càng làm tăng giá trị nghệ thuật và tính bản địa của công trình.",
  "Trên mặt tiền, phía trên lối vào chính, Shekhtel bố trí phù hiệu (huy hiệu) của ba thành phố quan trọng trên tuyến đường sắt Yaroslavl: Moskva, Yaroslavl và Arkhangelsk. Xen kẽ là những hoạ tiết trang trí hình hoa lá cách điệu và hình ảnh các loài vật phương Bắc, gợi nhắc thiên nhiên và văn hoá của những vùng đất mà tuyến đường đi qua. Mỗi chi tiết đều mang một hàm ý, biến mặt tiền thành một bức tranh kể chuyện về hành trình lên phương Bắc và sang phương Đông.",
  "Tổng hoà lại, kiến trúc Ga Yaroslavsky là sự kết hợp nhuần nhuyễn giữa tính biểu tượng, tính trang trí và tính chức năng. Shekhtel đã chứng minh rằng một nhà ga — công trình vốn thuần tuý phục vụ giao thông — cũng có thể trở thành một tác phẩm nghệ thuật giàu ý nghĩa, phản ánh bản sắc dân tộc và tinh thần của thời đại. Chính vì thế, mặt tiền nhà ga được xem là một trong những công trình Art Nouveau đẹp nhất nước Nga và là niềm tự hào trong di sản kiến trúc của Moskva."
 ]},
 {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
  "Điểm nhấn đầu tiên và quan trọng nhất là tháp cổng chính với mái lều cao vút. Đây là hình ảnh biểu tượng của nhà ga, góc chụp ảnh đẹp nhất và cũng là chi tiết chứa đựng nhiều ý nghĩa nhất. Hướng dẫn viên nên dừng lại ở đây để đoàn chiêm ngưỡng dáng vẻ vừa cổ kính vừa huyền ảo của tháp cổng, đặc biệt ấn tượng khi được chiếu sáng vào buổi tối.",
  "Điểm nhấn thứ hai là dải gạch men majolica ánh xanh ngọc chạy quanh mặt tiền cùng các huy hiệu thành phố. Việc quan sát kỹ những mảng gốm này giúp du khách cảm nhận được sự tinh xảo của nghề gốm Nga đầu thế kỷ 20 và mối liên hệ của nhà ga với xưởng nghệ thuật Abramtsevo lừng danh. Đây là chi tiết dễ bị bỏ qua nếu chỉ nhìn lướt, nhưng lại là tinh hoa trang trí của công trình.",
  "Điểm nhấn thứ ba, và giàu cảm xúc bậc nhất, là ý niệm về 'điểm khởi đầu của Đường sắt xuyên Siberia'. Dù cột mốc số 0 chính thức nằm trong khu vực sân ga, chỉ riêng việc đứng tại nhà ga và hình dung về hành trình gần chín nghìn ba trăm cây số tới Vladivostok cũng đủ khơi dậy cảm giác phiêu lưu. Hướng dẫn viên nên kể về tuyến đường huyền thoại này để biến điểm dừng thành một câu chuyện đáng nhớ.",
  "Điểm nhấn thứ tư là toàn cảnh 'Quảng trường Ba Nhà Ga'. Từ trước Ga Yaroslavsky, du khách có thể chiêm ngưỡng cùng lúc ba công trình kiến trúc lớn với ba phong cách khác nhau: Yaroslavsky theo Tân Nga – Art Nouveau, Leningradsky theo phong cách cổ điển và Kazansky theo phong cách Nga hoành tráng của kiến trúc sư Shchusev. Đây là cơ hội hiếm có để so sánh và cảm nhận sự đa dạng của kiến trúc nhà ga Nga trong một tầm mắt.",
  "Cuối cùng, đừng bỏ lỡ ga tàu điện ngầm Komsomolskaya ngay bên dưới quảng trường. Nhà ga metro trên tuyến vòng này được xem là một trong những ga đẹp nhất thế giới, với trần vòm vàng rực, đèn chùm và các bức tranh khảm hoành tráng ca ngợi lịch sử nước Nga. Việc kết hợp tham quan mặt tiền nhà ga đường sắt phía trên và ga tàu điện ngầm lộng lẫy phía dưới tạo nên một trải nghiệm trọn vẹn và ấn tượng."
 ]},
 {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
  "Ga Yaroslavsky mang ý nghĩa lịch sử đặc biệt với tư cách là cửa ngõ dẫn tới Siberia và Viễn Đông — những vùng đất rộng lớn gắn liền với quá trình mở mang, khai phá của nước Nga. Đường sắt xuyên Siberia, khởi hành từ chính nhà ga này, là một trong những kỳ tích kỹ thuật vĩ đại nhất của nhân loại, đã kết nối phần châu Âu và châu Á của nước Nga, thúc đẩy di dân, giao thương và định hình bản đồ kinh tế – xã hội của cả một đế quốc rồi một liên bang.",
  "Về mặt văn hoá, nhà ga là hiện thân của khát vọng và tinh thần lãng mạn gắn với những chuyến đi dài. Trong văn học, điện ảnh và ký ức của người Nga, hành trình xuyên Siberia bằng tàu hoả luôn mang màu sắc huyền thoại — một cuộc phiêu lưu qua rừng taiga, hồ Baikal và những thảo nguyên vô tận. Ga Yaroslavsky, với tư cách điểm khởi đầu, đã trở thành một biểu tượng văn hoá gắn với ý niệm về không gian bao la và tinh thần khám phá của nước Nga.",
  "Về mặt nghệ thuật, công trình đánh dấu một cột mốc trong lịch sử kiến trúc Nga đầu thế kỷ 20, khi phong trào Tân Nga và Art Nouveau nở rộ. Việc một kiến trúc sư tầm cỡ như Shekhtel dồn tài năng vào một nhà ga cho thấy quan niệm tiến bộ rằng công trình công cộng phục vụ số đông cũng xứng đáng có giá trị thẩm mỹ cao. Nhà ga vì thế được trân trọng như một di sản kiến trúc, không chỉ là hạ tầng giao thông.",
  "Cụm ba nhà ga trên Quảng trường Komsomolskaya còn là một 'bảo tàng ngoài trời' độc đáo, nơi lịch sử kiến trúc nhà ga Nga được trưng bày qua ba công trình tiêu biểu của ba thời kỳ và phong cách khác nhau. Sự cùng tồn tại này phản ánh chiều dài lịch sử phát triển đường sắt Nga và biến quảng trường thành một địa điểm giàu giá trị nghiên cứu và tham quan về mặt kiến trúc – đô thị.",
  "Với du khách Việt Nam, Ga Yaroslavsky còn gợi những liên tưởng gần gũi: nhiều thế hệ người Việt từng học tập, lao động tại Liên Xô và Nga đã đi trên những tuyến tàu xuất phát từ đây, mang theo bao kỷ niệm về những chuyến đi dài. Vì thế, ghé thăm nhà ga không chỉ là chiêm ngưỡng kiến trúc, mà còn là dịp để cảm nhận một phần ký ức chung của mối quan hệ Việt – Nga qua hình ảnh những chuyến tàu và sân ga."
 ]},
 {"heading": "Trải nghiệm dành cho du khách", "paras": [
  "Trải nghiệm cốt lõi tại Ga Yaroslavsky là chiêm ngưỡng mặt tiền kiến trúc độc đáo và hoà mình vào nhịp sống sôi động của một nhà ga lớn. Du khách có thể đứng trước quảng trường để ngắm toàn cảnh tháp cổng và các mảng trang trí, sau đó bước vào sảnh để cảm nhận không khí tấp nập của những cuộc lên đường. Chính sự tương phản giữa vẻ đẹp tĩnh tại của kiến trúc và dòng chảy hối hả của hành khách tạo nên sức hấp dẫn riêng.",
  "Đối với những ai yêu thích nhiếp ảnh, nhà ga là một 'kho' góc chụp phong phú: từ tổng thể tháp cổng, các chi tiết gạch men và huy hiệu, cho tới những khoảnh khắc đời thường của hành khách. Buổi tối, khi mặt tiền được chiếu sáng, nhà ga khoác lên vẻ lung linh huyền ảo, rất đáng để ghi lại. Đây cũng là dịp để chụp chung khung hình cả ba nhà ga trên quảng trường.",
  "Với du khách có thời gian và muốn trải nghiệm sâu hơn, việc mua một vé tàu ngắn hoặc đơn giản là bước lên khu vực sân ga (theo quy định cho phép) để tận mắt thấy những đoàn tàu đường dài chuẩn bị lăn bánh về phương Đông là một trải nghiệm khó quên. Cảm giác đứng nơi khởi đầu của tuyến đường sắt dài nhất thế giới mang lại xúc cảm đặc biệt, khơi dậy khát khao được một lần thực hiện hành trình xuyên Siberia.",
  "Nhà ga cũng là nơi để cảm nhận 'văn hoá tàu hoả' rất đặc trưng của nước Nga — thứ văn hoá gắn với những chuyến đi kéo dài nhiều ngày, với toa tàu, trà nóng và những câu chuyện dọc đường. Quan sát hành khách chuẩn bị hành lý, mua đồ ăn dự trữ cho chuyến đi dài, du khách có thể hiểu thêm về một khía cạnh đời sống rất Nga mà khó tìm thấy ở nơi nào khác.",
  "Thời lượng tham quan hợp lý khoảng hai mươi đến bốn mươi phút cho phần mặt tiền và sảnh, hoặc lâu hơn nếu kết hợp với ga tàu điện ngầm và hai nhà ga còn lại. Đây là điểm dừng linh hoạt, có thể chỉ là một lần ngắm nhìn nhanh trên đường di chuyển, hoặc trở thành một chặng khám phá thú vị về kiến trúc và văn hoá đường sắt nếu được đầu tư thời gian và thuyết minh chu đáo."
 ]},
 {"heading": "Mẹo tham quan", "paras": [
  "Về an ninh, đây là điều cần lưu ý hàng đầu. Là một trong những nhà ga đông đúc nhất Moskva, khu vực này cũng là nơi dễ xảy ra tình trạng móc túi và lừa đảo nhắm vào du khách. Hướng dẫn viên nên nhắc đoàn giữ chặt tư trang, không để hành lý rời tầm mắt, cảnh giác với người lạ chủ động bắt chuyện hay chào mời, và giữ tài sản có giá trị ở nơi kín đáo.",
  "Về thời điểm, ban ngày là lúc thích hợp để thấy rõ sắc men majolica và các chi tiết trang trí tinh xảo của mặt tiền. Trong khi đó, buổi tối lại là thời điểm lý tưởng để chiêm ngưỡng tháp cổng được chiếu sáng lung linh. Nếu có thể, việc ghé thăm vào cả hai khung giờ sẽ cho hai ấn tượng thị giác khác nhau, đều rất đáng giá.",
  "Về lộ trình kết hợp, hãy tận dụng tối đa vị trí 'ba trong một' của Quảng trường Komsomolskaya: tham quan liền mạch cả ba nhà ga và ga tàu điện ngầm Komsomolskaya lộng lẫy bên dưới. Đây là cách sử dụng thời gian hiệu quả nhất, mang lại nhiều trải nghiệm phong phú chỉ trong một điểm dừng duy nhất mà không phải di chuyển xa.",
  "Về việc lên sân ga và chụp ảnh, du khách cần tuân thủ quy định của nhà ga: một số khu vực yêu cầu có vé mới được vào, và việc quay phim, chụp ảnh ở khu vực an ninh cần thận trọng. Nên quan sát biển báo và, nếu cần, hỏi nhân viên để tránh vi phạm quy định. Sự chủ động tìm hiểu này giúp chuyến tham quan diễn ra suôn sẻ.",
  "Cuối cùng, về nội dung thuyết minh, hãy chuẩn bị những câu chuyện đắt giá để nâng tầm điểm dừng: hành trình xuyên Siberia dài nhất thế giới, tài năng của kiến trúc sư Shekhtel, mối liên hệ với xưởng gốm Abramtsevo, và ý nghĩa của cụm ba nhà ga. Vài con số ấn tượng — như quãng đường gần chín nghìn ba trăm cây số tới Vladivostok — cùng những giai thoại kiến trúc sẽ khiến du khách nhìn nhà ga bằng con mắt hoàn toàn khác."
 ]},
 {"heading": "Khám phá xung quanh", "paras": [
  "Ngay trên cùng quảng trường là Ga Leningradsky — nhà ga cổ nhất Moskva, được xây theo phong cách cổ điển và là điểm khởi hành của các chuyến tàu đi Saint Petersburg, trong đó có tàu cao tốc Sapsan. Kề bên là Ga Kazansky, một công trình đồ sộ và tráng lệ theo phong cách Nga cổ do kiến trúc sư Aleksey Shchusev thiết kế, với tháp gợi hình tháp Söyembika ở Kazan. Ba nhà ga cùng nhau tạo nên một quần thể kiến trúc độc nhất vô nhị.",
  "Bên dưới quảng trường, ga tàu điện ngầm Komsomolskaya trên tuyến vòng là một điểm đến tự thân. Được thiết kế theo phong cách Đế chế Stalin, ga có trần vòm vàng rực, hàng cột nguy nga, đèn chùm và tám bức tranh khảm mosaic lớn ca ngợi các anh hùng và chiến thắng trong lịch sử Nga. Đây thường được coi là một trong những ga tàu điện ngầm đẹp và lộng lẫy nhất thế giới.",
  "Đi bộ một quãng ngắn về hướng trung tâm, du khách sẽ tới khu vực Krasnye Vorota (Cổng Đỏ) và các con phố với nhiều công trình kiến trúc thời Xô-viết, trong đó có một trong 'bảy toà nhà chị em' theo phong cách Stalin. Khu vực này cho thấy một lát cắt khác của đô thị Moskva thế kỷ 20, bổ sung cho trải nghiệm kiến trúc đa dạng quanh nhà ga.",
  "Theo tuyến tàu điện ngầm số 1 (màu đỏ) đi về phía Đông Bắc chỉ vài ga là tới Công viên Sokolniki — một trong những công viên lớn và lâu đời của Moskva, với những lối đi rợp bóng cây, khu vui chơi và không gian nghỉ ngơi thoáng đãng. Đây là lựa chọn lý tưởng để thư giãn sau khi tham quan khu vực nhà ga đông đúc và náo nhiệt.",
  "Khu vực quanh Quảng trường Komsomolskaya cũng có nhiều tiện ích phục vụ hành khách và du khách: quán ăn nhanh, cửa hàng tiện lợi, hiệu thuốc và các dịch vụ đi lại. Đây là nơi thích hợp để nghỉ chân, ăn nhẹ hoặc mua sắm nhanh trước khi tiếp tục hành trình. Tuy nhiên, do đông đúc, du khách nên chọn những địa điểm uy tín và tiếp tục giữ ý thức cảnh giác về an ninh."
 ]},
 {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
  "Câu chuyện nổi tiếng nhất gắn với Ga Yaroslavsky chính là Đường sắt xuyên Siberia — tuyến đường sắt dài nhất thế giới. Từ nhà ga này, đoàn tàu sẽ đi khoảng chín nghìn hai trăm tám mươi chín cây số để tới Vladivostok bên bờ Thái Bình Dương, băng qua tám múi giờ và vô số vùng địa lý khác nhau. Một hành trình trọn vẹn có thể kéo dài gần một tuần lễ, biến chuyến đi tàu thành một cuộc phiêu lưu đúng nghĩa qua chiều rộng của cả một lục địa.",
  "Một giai thoại thú vị về mặt kiến trúc là mối liên hệ giữa nhà ga và xưởng nghệ thuật Abramtsevo. Những mảng gạch men majolica trang trí mặt tiền được chế tác tại xưởng gốm do nhà tư sản – bảo trợ nghệ thuật Savva Mamontov gây dựng — cũng chính là nơi quy tụ nhiều hoạ sĩ Nga lừng danh và là cái nôi của phong trào phục hưng nghệ thuật thủ công dân tộc. Như vậy, nhà ga không chỉ là công trình của Shekhtel mà còn kết tinh tinh hoa của cả một trào lưu nghệ thuật.",
  "Bản thân kiến trúc sư Fyodor Shekhtel cũng là một nhân vật đầy giai thoại. Ông là bậc thầy của trường phái Art Nouveau Nga, tác giả của hàng loạt công trình danh tiếng ở Moskva như Dinh thự Ryabushinsky và Nhà hát Nghệ thuật Moskva. Điều thú vị là Shekhtel phần lớn tự học và vươn lên bằng tài năng thiên bẩm; dù cuối đời gặp nhiều khó khăn sau Cách mạng, di sản kiến trúc ông để lại vẫn là niềm tự hào của Moskva cho tới ngày nay.",
  "Cái tên 'Quảng trường Ba Nhà Ga' cũng gắn với nhiều câu chuyện đời thường. Đây là nơi đón những dòng người từ khắp nơi đổ về thủ đô, là điểm khởi đầu của biết bao giấc mơ đổi đời, cũng như là sân khấu của vô số cuộc chia ly và đoàn tụ. Trong tâm thức người Nga, quảng trường này vừa mang màu sắc hối hả, phồn tạp của một đầu mối giao thông lớn, vừa chất chứa những câu chuyện nhân sinh đầy cảm xúc.",
  "Cuối cùng, có một chi tiết thú vị về sự đối thoại kiến trúc trên quảng trường: Ga Kazansky của Shchusev ở phía đối diện được thiết kế với tháp mô phỏng tháp Söyembika ở Kazan — hướng về phương Đông, như một lời chào tới vùng đất Tatar và châu Á. Trong khi đó, Ga Yaroslavsky của Shekhtel lại gợi hình phương Bắc nước Nga. Hai nhà ga, hai hướng nhìn, cùng phô diễn trên một quảng trường, tạo nên một cuộc 'đối thoại' kiến trúc tinh tế mà không phải du khách nào cũng nhận ra — và đó chính là chi tiết đắt giá để khép lại phần thuyết minh."
 ]}
],
"highlights": [
 "Điểm khởi đầu của Đường sắt xuyên Siberia — tuyến đường sắt dài nhất thế giới, khoảng 9.289 km tới Vladivostok.",
 "Toà nhà hiện nay (1902–1904) là kiệt tác của kiến trúc sư Fyodor Shekhtel theo phong cách Tân Nga pha Art Nouveau.",
 "Tháp cổng mái lều cao vút gợi kiến trúc gỗ và nhà thờ phương Bắc nước Nga.",
 "Dải gạch men majolica ánh xanh ngọc chế tác tại xưởng gốm Abramtsevo của Savva Mamontov.",
 "Huy hiệu ba thành phố Moskva – Yaroslavl – Arkhangelsk cùng mô-típ hoa lá và thú phương Bắc trên mặt tiền.",
 "Toạ lạc trên 'Quảng trường Ba Nhà Ga' (Komsomolskaya) cùng ga Leningradsky và Kazansky.",
 "Ngay bên dưới là ga metro Komsomolskaya — một trong những ga tàu điện ngầm đẹp nhất thế giới.",
 "Vào cửa khu ga tự do; chỉ mua vé khi đi tàu; khu vực đông đúc, cần đề phòng móc túi."
],
"images": [
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Yaroslavsky%20Train%20Terminal,%20Moscow,%20Russia%20-%202013-05-19%20-%2090650652.jpg", "caption": "Mặt tiền Ga Yaroslavsky với tháp cổng mái lều đặc trưng."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Yaroslavsky%20vokzal%20in%20Moscow%20by%20Schechtel.jpg", "caption": "Toà nhà ga do kiến trúc sư Fyodor Shekhtel thiết kế (1902–1904)."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Transsib%20start.JPG", "caption": "Biểu tượng gắn với điểm khởi đầu của Đường sắt xuyên Siberia tại nhà ga."},
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Moscow,%20Yaroslavsky%20Rail%20Terminal%20(20625630504).jpg", "caption": "Nhà ga nhìn từ Quảng trường Komsomolskaya."}
],
"references": [
 {"title": "Moscow Yaroslavsky railway station — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Moscow_Yaroslavsky_railway_station"},
 {"title": "Fyodor Schechtel — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Fyodor_Schechtel"},
 {"title": "Yaroslavsky Railway Station — Rusmania", "url": "https://rusmania.com/central/moscow-federal-city/moscow/krasnoselsky/beyond-the-garden-ring-around-komsomolskaya-ploschad/yaroslavsky-railway-station"},
 {"title": "6 Moscow train stations that are temples of art, architecture and history — GW2RU", "url": "https://www.gw2ru.com/arts/58130-6-moscow-train-stations"},
 {"title": "Yaroslavsky railway station — All Pyrenees (all-andorra.com)", "url": "https://all-andorra.com/yaroslavsky-railway-station/"},
 {"title": "10 Most Beautiful Russian Art Nouveau Buildings — DailyArt Magazine", "url": "https://www.dailyartmagazine.com/russian-art-nouveau-buildings/"}
],
"sources": [
 "Wikipedia tiếng Anh — mục 'Moscow Yaroslavsky railway station' (mở cửa 1862, toà nhà 1902–1904 của Shekhtel, phong cách Tân Nga – Art Nouveau, gạch men majolica xưởng Abramtsevo, huy hiệu Moskva – Yaroslavl – Arkhangelsk, cảm hứng từ Kremlin và Tu viện Cứu thế Yaroslavl).",
 "Wikipedia tiếng Anh — mục 'Fyodor Schechtel' (tiểu sử và các công trình tiêu biểu của kiến trúc sư).",
 "Rusmania — hồ sơ 'Yaroslavsky Railway Station' (lịch sử tuyến đường tới Sergiyev Posad – Yaroslavl, vai trò đầu mối).",
 "GW2RU (Russia Beyond) — '6 Moscow train stations that are temples of art' (bối cảnh nghệ thuật của các nhà ga Moskva).",
 "Dữ liệu dự án 'Cẩm nang Du lịch Nga' (data/regions/moscow) — địa chỉ Komsomolskaya ploshchad 5, quãng đường ~9.289 km tới Vladivostok, cụm 'Quảng trường Ba Nhà Ga'.",
 "DailyArt Magazine — 'Most Beautiful Russian Art Nouveau Buildings' (đánh giá vị trí của nhà ga trong dòng kiến trúc Art Nouveau Nga).",
 "Thông tin nền về Đường sắt xuyên Siberia và tuyến xuyên Mông Cổ tổng hợp từ các nguồn bách khoa phổ biến.",
 "Thông tin nền về ga metro Komsomolskaya và cụm ga Leningradsky, Kazansky tổng hợp từ tư liệu du lịch phổ biến."
]
}

def norm(o):
    if isinstance(o, str): return unicodedata.normalize("NFC", o)
    if isinstance(o, list): return [norm(x) for x in o]
    if isinstance(o, dict): return {k: norm(v) for k, v in o.items()}
    return o
d = norm(d)

out = os.path.join(HERE, "doc_" + d["slug"] + ".json")
json.dump(d, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
wc = sum(len(p.split()) for s in d["sections"] for p in s["paras"])
print("WROTE", out, "| sections:", len(d["sections"]), "| body words:", wc)
