# -*- coding: utf-8 -*-
import json, os, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__))

d = {
"slug": "ho-chi-minh-monument",
"name_vi": "Tượng đài Chủ tịch Hồ Chí Minh (Moskva)",
"name_ru": "Памятник Хо Ши Мину",
"name_en": "Monument to Ho Chi Minh, Moscow",
"subtitle": "Bức tượng đồng bên Quảng trường mang tên Bác giữa lòng Moskva — biểu tượng sống động của tình hữu nghị Việt–Nga, nơi hội tụ của cộng đồng người Việt và điểm dừng đầy xúc cảm với mỗi du khách Việt trên đất Nga.",
"sections": [
 {"heading": "Giới thiệu chung", "paras": [
  "Giữa khu Tây Nam yên tĩnh của thủ đô Moskva, trên một quảng trường nhỏ mang tên Hồ Chí Minh (tiếng Nga: площадь Хо Ши Мина), có một bức tượng đồng khiến bất cứ người Việt nào đi ngang cũng phải dừng chân. Đó là Tượng đài Chủ tịch Hồ Chí Minh — công trình được khánh thành ngày 18 tháng 5 năm 1990, đúng dịp kỷ niệm 100 năm ngày sinh của Người. Với cộng đồng người Việt đang sinh sống, học tập và làm việc tại Nga, nơi đây từ lâu đã trở thành một địa chỉ thiêng liêng; còn với du khách Việt lần đầu đặt chân tới Moskva, được đứng trước tượng Bác nơi xứ người là một trải nghiệm đầy cảm xúc, gợi lên cảm giác vừa xa lạ vừa thân thuộc lạ thường.",
  "Khác với nhiều tượng đài lãnh tụ theo lối chân dung toàn thân quen thuộc, tượng đài ở Moskva được nhà điêu khắc thể hiện theo một ngôn ngữ tạo hình giàu tính biểu tượng. Trung tâm của cụm tượng là một chiếc đĩa đồng lớn hình tròn như vầng mặt trời đang lên, trên đó nổi bật gương mặt hiền hậu của Chủ tịch Hồ Chí Minh. Phía trước, dưới vầng mặt trời ấy, là hình một chàng trai Việt Nam đang vươn mình đứng dậy — hình ảnh cô đọng cho một dân tộc quật cường vùng lên giành lấy độc lập, tự do. Cách thể hiện này khiến tượng đài không chỉ là một chân dung, mà còn là một câu chuyện về ý chí và khát vọng của cả một dân tộc.",
  "Tượng đài nằm trong quận Akademichesky, khu vực tập trung nhiều viện nghiên cứu của Viện Hàn lâm Khoa học Nga, gần ga tàu điện ngầm Akademicheskaya. Vị trí này không phải ngẫu nhiên: việc đặt tên một quảng trường theo tên Chủ tịch Hồ Chí Minh và dựng tượng Người ngay tại trung tâm học thuật của Moskva thể hiện sự trân trọng mà nước Nga (khi đó là Liên Xô) dành cho vị lãnh tụ của Việt Nam, đồng thời là dấu ấn vật chất cho mối quan hệ gắn bó đặc biệt giữa hai dân tộc suốt nhiều thập niên.",
  "Là tài liệu thuyết minh nội bộ, phần trình bày dưới đây tổng hợp và biên soạn lại từ nhiều nguồn tư liệu tiếng Nga, tiếng Anh và tiếng Việt nhằm giúp hướng dẫn viên có một bức tranh đầy đủ về lịch sử ra đời, ý nghĩa nghệ thuật và giá trị tinh thần của tượng đài. Điểm tham quan này tuy nhỏ về quy mô và thường chỉ chiếm ít phút trong một hành trình khám phá Moskva, nhưng lại có sức nặng cảm xúc lớn, đặc biệt phù hợp để lồng ghép vào các chương trình tour dành cho đoàn khách Việt, các dịp lễ trọng hay những chuyến đi mang màu sắc lịch sử — chính trị."
 ]},
 {"heading": "Vị trí & cách di chuyển", "paras": [
  "Tượng đài toạ lạc trên Quảng trường Hồ Chí Minh, nằm ở khu vực giao giữa các phố Dmitry Ulyanov và Sixtieth Anniversary of October (đại lộ 60 năm Cách mạng Tháng Mười), thuộc quận Akademichesky ở phía Tây Nam Moskva. Toạ độ địa lý xấp xỉ 55,68 độ vĩ Bắc và 37,56 độ kinh Đông. Đây là khu dân cư kết hợp với hành lang các viện nghiên cứu khoa học, nhìn chung yên tĩnh, nhiều cây xanh và khá thoáng đãng, rất khác với sự sầm uất của khu vực trung tâm quanh Quảng trường Đỏ.",
  "Cách di chuyển thuận tiện nhất là bằng tàu điện ngầm. Du khách đi tuyến số 6 (tuyến Kaluzhsko-Rizhskaya, ký hiệu màu cam) và xuống tại ga Akademicheskaya. Từ cửa ra của ga, chỉ cần đi bộ khoảng năm tới bảy phút là tới quảng trường có tượng đài. Ga Akademicheskaya nằm ngay gần một trong những lối vào quảng trường, nên hầu như không thể lạc nếu bám theo bản đồ điện thoại; đây cũng là lý do tượng đài thường được giới thiệu gắn liền với tên ga tàu điện quen thuộc này.",
  "Nếu di chuyển bằng ô tô hoặc taxi công nghệ (Yandex Go là ứng dụng phổ biến nhất ở Nga), du khách có thể yêu cầu điểm đến là площадь Хо Ши Мина hoặc mốc dễ tìm là ga metro Akademicheskaya. Từ trung tâm Moskva, quãng đường chừng tám đến mười cây số, mất khoảng hai mươi đến ba mươi phút tuỳ tình hình giao thông. Khu vực xung quanh có chỗ đỗ xe ven đường, song nên ưu tiên phương tiện công cộng vào giờ cao điểm để tránh ùn tắc trên các trục đường lớn phía Tây Nam.",
  "Xét về tổ chức lộ trình, tượng đài không nằm trên trục tham quan trung tâm nên hướng dẫn viên nên chủ động sắp xếp nó thành một điểm dừng có chủ đích. Cách bố trí hợp lý là kết hợp với những địa điểm cùng khu Tây Nam như Bảo tàng Darwin (nằm rất gần, cũng ở khu Akademicheskaya), hoặc lồng vào hành trình ra – vào sân bay Vnukovo, hay ghép cùng chuyến tham quan Đại học Tổng hợp Moskva và Đồi Chim Sẻ ở phía Tây. Với đoàn khách Việt, nhiều đơn vị lữ hành xem đây là điểm dừng đầu tiên hoặc cuối cùng của chương trình như một cách chào và tạm biệt Moskva đầy ý nghĩa.",
  "Một lưu ý về thời tiết và thời gian: vì là không gian ngoài trời hoàn toàn, trải nghiệm ở tượng đài phụ thuộc nhiều vào mùa. Mùa hè từ tháng 5 đến tháng 9 là lý tưởng nhất, cây cối xanh mát, ánh sáng đẹp và thuận tiện cho việc dâng hoa, chụp ảnh. Mùa đông tuyết phủ mang lại khung cảnh trang nghiêm nhưng lạnh giá, đoàn nên rút ngắn thời gian dừng và chuẩn bị trang phục ấm."
 ]},
 {"heading": "Lịch sử hình thành và phát triển", "paras": [
  "Ý tưởng dựng một tượng đài tưởng niệm Chủ tịch Hồ Chí Minh tại Moskva ra đời trong bối cảnh quan hệ Việt Nam – Liên Xô ở giai đoạn nồng ấm và gắn bó bậc nhất. Trải qua nhiều thập niên, Liên Xô là chỗ dựa quan trọng của Việt Nam trong sự nghiệp đấu tranh giành độc lập và tái thiết đất nước; hàng vạn cán bộ, sinh viên, nghiên cứu sinh Việt Nam đã được đào tạo trên đất nước này. Việc thành phố Moskva dành một quảng trường mang tên Hồ Chí Minh và cho dựng tượng Người là sự ghi nhận ở cấp độ biểu tượng cho tình hữu nghị đó, đồng thời tôn vinh một nhân vật đã trở thành biểu tượng của phong trào giải phóng dân tộc trên thế giới.",
  "Công trình được giao cho nhà điêu khắc Xô-viết lừng danh Vladimir Yefimovich Tsigal đảm nhận phần tạo hình, cùng kiến trúc sư Roman Grigoryevich Kananin phụ trách phần kiến trúc và bố cục tổng thể. Theo các tư liệu, để chuẩn bị cho tác phẩm, Tsigal đã sang Việt Nam vào năm 1985 nhằm tìm hiểu sâu về cuộc đời, con người và bối cảnh văn hoá gắn với Chủ tịch Hồ Chí Minh. Chuyến đi thực tế này giúp ông nắm bắt được thần thái nhân vật cũng như những mô-típ mang đậm bản sắc Việt như cây tre, hoa nhiệt đới, để đưa vào ngôn ngữ điêu khắc của mình.",
  "Tượng đài chính thức được khánh thành ngày 18 tháng 5 năm 1990, ngay trước thềm dịp kỷ niệm tròn một trăm năm ngày sinh Chủ tịch Hồ Chí Minh (19 tháng 5 năm 1890 – 19 tháng 5 năm 1990). Thời điểm khánh thành mang ý nghĩa đặc biệt: đây là món quà tưởng niệm đúng vào dịp trọng đại, đồng thời diễn ra trong những năm cuối cùng của Liên Xô, khép lại một chương lịch sử và mở ra giai đoạn mới của quan hệ song phương. Dù bối cảnh chính trị ở Nga sau đó có nhiều biến động, quảng trường và tượng đài vẫn được gìn giữ nguyên vẹn cho đến ngày nay.",
  "Từ khi ra đời, tượng đài dần trở thành điểm hẹn truyền thống của cộng đồng người Việt tại Nga. Vào các dịp trọng đại như ngày sinh Chủ tịch Hồ Chí Minh (19 tháng 5), Quốc khánh Việt Nam (2 tháng 9), Tết Nguyên đán hay các chuyến thăm cấp cao, đại diện Đại sứ quán, các hội đoàn, lưu học sinh và bà con kiều bào thường tề tựu về đây dâng hoa, tưởng niệm. Nhiều đoàn đại biểu Việt Nam sang thăm Nga cũng đưa việc đặt hoa tại tượng đài vào chương trình chính thức, biến địa điểm này thành một 'địa chỉ đỏ' trong đời sống tinh thần của người Việt xa xứ.",
  "Theo thời gian, chính quyền thành phố Moskva và cộng đồng người Việt đã phối hợp chăm nom, tu bổ khuôn viên quảng trường để giữ cho không gian luôn trang nghiêm, sạch đẹp. Việc tượng đài tồn tại bền vững qua hơn ba thập niên, vượt qua cả những thăng trầm của thời cuộc, cho thấy sức sống của một biểu tượng đã ăn sâu vào ký ức và tình cảm của hai dân tộc, chứ không đơn thuần là một sản phẩm của một giai đoạn lịch sử nhất định."
 ]},
 {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
  "Về mặt tạo hình, tượng đài là một cụm tác phẩm điêu khắc – kiến trúc bằng đồng và đá granit, được bố cục cô đọng nhưng giàu tầng nghĩa. Thành phần trung tâm và gây ấn tượng mạnh nhất là một chiếc đĩa tròn lớn bằng đồng, thường được người xem liên tưởng tới hình ảnh vầng mặt trời đang mọc. Trên bề mặt đĩa, gương mặt Chủ tịch Hồ Chí Minh được thể hiện theo lối chạm nổi (phù điêu), với thần thái điềm đạm, ánh nhìn hướng về phía trước — vừa gần gũi, vừa toát lên vẻ ung dung của một bậc hiền triết.",
  "Ngay phía trước và bên dưới vầng mặt trời là hình tượng một chàng trai Việt Nam trong tư thế đang vươn mình đứng dậy. Đây là chi tiết mang tính biểu tượng cao nhất của toàn bộ tác phẩm: hình ảnh con người bừng tỉnh, rũ bỏ xiềng xích để đứng thẳng, tượng trưng cho cả một dân tộc vùng lên từ thân phận nô lệ, thuộc địa để giành lấy quyền tự quyết. Sự đối thoại giữa vầng mặt trời (ánh sáng, lý tưởng, sự dẫn dắt) và chàng trai đứng dậy (dân tộc, hành động, khát vọng) tạo nên chiều sâu tư tưởng cho tượng đài.",
  "Bao quanh và làm nền cho khối tượng chính là những hoạ tiết trang trí đậm chất phương Đông nhiệt đới: hình những đoá hoa vùng nhiệt đới và hai thân tre cong mềm mại. Cây tre — biểu tượng quen thuộc của làng quê và cốt cách Việt Nam, dẻo dai mà kiên cường — được nhà điêu khắc khéo léo đưa vào như một cách gợi nhắc quê hương của nhân vật, đồng thời làm dịu đi tính hoành tráng của khối đồng, mang lại cảm giác gần gũi. Chính những chi tiết mang bản sắc dân tộc này khiến tác phẩm không bị hoà lẫn vào vô số tượng đài lãnh tụ theo phong cách hiện thực xã hội chủ nghĩa khác ở Nga.",
  "Dưới chân tượng đài có khắc câu nói bất hủ của Chủ tịch Hồ Chí Minh bằng tiếng Nga: 'Нет ничего дороже независимости, свободы' — tức là 'Không có gì quý hơn độc lập, tự do'. Đây là chân lý mà Người đã đúc kết và trở thành phương châm hành động của cả dân tộc Việt Nam. Việc chọn chính câu nói này để khắc lên bệ tượng giữa lòng Moskva cho thấy sự thấu hiểu và trân trọng của những người thực hiện đối với tư tưởng cốt lõi mà Chủ tịch Hồ Chí Minh theo đuổi suốt đời.",
  "Xét tổng thể, tác giả Vladimir Tsigal đã lựa chọn một giải pháp nghệ thuật vừa hoành tráng vừa hàm súc. Thay vì phô diễn kích thước, ông dồn sức vào tính biểu tượng và sự hoà quyện giữa các mô-típ Nga – Việt. Khối đồng sẫm màu nổi bật trên nền granit và cây xanh, ánh sáng phản chiếu trên mặt đĩa tròn thay đổi theo thời khắc trong ngày khiến tác phẩm luôn có một sức sống riêng. Đây được xem là một trong những tượng đài nước ngoài đẹp và giàu ý nghĩa nhất về Chủ tịch Hồ Chí Minh, kết tinh tài năng của một trong những nhà điêu khắc tượng đài hàng đầu của nền nghệ thuật Xô-viết."
 ]},
 {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
  "Điểm nhấn đầu tiên và quan trọng nhất chính là vầng mặt trời với chân dung Chủ tịch Hồ Chí Minh. Hướng dẫn viên nên dành thời gian để đoàn quan sát kỹ gương mặt được chạm nổi trên đĩa đồng: nét mặt thanh thoát, vầng trán cao, chòm râu đặc trưng và ánh nhìn hiền từ. Đây là góc để du khách chụp bức ảnh lưu niệm trang trọng nhất, và cũng là điểm dâng hoa quen thuộc của các đoàn.",
  "Điểm nhấn thứ hai là hình tượng chàng trai đang vươn dậy dưới vầng mặt trời. Nhiều du khách thoạt nhìn chỉ chú ý tới khối đĩa lớn mà bỏ qua chi tiết giàu ý nghĩa này. Khi được giải thích rằng đó là biểu tượng cho dân tộc Việt Nam đứng lên giành độc lập, du khách thường có cái nhìn khác hẳn và cảm nhận sâu sắc hơn thông điệp mà tác phẩm gửi gắm. Đây là chi tiết cần được thuyết minh kỹ để phát huy trọn vẹn giá trị cảm xúc.",
  "Điểm nhấn thứ ba là dòng chữ 'Không có gì quý hơn độc lập, tự do' khắc bằng tiếng Nga. Với du khách Việt, được nhìn thấy chân lý quen thuộc của Bác hiện diện trang trọng trên đất Nga là một khoảnh khắc đầy tự hào. Hướng dẫn viên có thể đọc to câu nói này bằng cả tiếng Việt lẫn tiếng Nga, tạo nên một điểm nhấn giàu tính nghi thức trong buổi tham quan.",
  "Điểm nhấn thứ tư là những chi tiết mang bản sắc Việt: cây tre và hoa nhiệt đới. Đây là những mô-típ bất ngờ giữa một quảng trường ở Moskva, cho thấy sự tinh tế của nhà điêu khắc khi cố gắng đưa hồn quê hương của nhân vật vào tác phẩm. Việc chỉ ra và lý giải những chi tiết nhỏ này giúp câu chuyện thuyết minh trở nên sinh động và có chiều sâu văn hoá.",
  "Cuối cùng, đừng bỏ qua chính tấm biển tên quảng trường — 'площадь Хо Ши Мина' (Quảng trường Hồ Chí Minh). Một tấm ảnh bên biển tên quảng trường mang tên Bác giữa thủ đô nước Nga là kỷ niệm ý nghĩa mà nhiều du khách Việt trân trọng. Sự hiện diện của một địa danh chính thức mang tên Chủ tịch Hồ Chí Minh trên bản đồ Moskva tự thân đã là một điểm nhấn đáng nhớ của điểm tham quan này."
 ]},
 {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
  "Tượng đài Chủ tịch Hồ Chí Minh ở Moskva trước hết là một biểu tượng vật chất cho tình hữu nghị Việt – Nga, mối quan hệ đã được thử thách và vun đắp qua nhiều thập niên. Việc một quốc gia dành hẳn một quảng trường và dựng tượng để tôn vinh lãnh tụ của một dân tộc khác là điều không phổ biến; nó phản ánh vị thế đặc biệt của Chủ tịch Hồ Chí Minh trong nhận thức của giới lãnh đạo và nhân dân Liên Xô, cũng như chiều sâu của quan hệ hai nước trong thế kỷ 20.",
  "Ở tầng nghĩa rộng hơn, tác phẩm góp phần khẳng định tầm vóc quốc tế của Chủ tịch Hồ Chí Minh như một biểu tượng của phong trào giải phóng dân tộc và đấu tranh vì độc lập, tự do trên toàn thế giới. Hình tượng con người vùng dậy dưới vầng mặt trời không chỉ nói về Việt Nam mà còn mang thông điệp phổ quát về khát vọng tự do của các dân tộc bị áp bức. Đặt trong khu học thuật của Moskva, tượng đài như một lời nhắc nhở về lý tưởng và trách nhiệm của tri thức đối với các giá trị nhân văn.",
  "Với cộng đồng người Việt tại Nga — vốn đông đảo và có bề dày lịch sử gắn với các thế hệ lưu học sinh, người lao động — tượng đài là điểm tựa tinh thần và là nơi kết nối cộng đồng. Mỗi lần tề tựu về dâng hoa trước tượng Bác là một dịp để bà con xa quê nhắc nhớ về cội nguồn, hun đúc tình đoàn kết và gìn giữ bản sắc dân tộc nơi đất khách. Trong ý nghĩa đó, tượng đài không phải một di tích tĩnh tại mà là một không gian sống động của đời sống cộng đồng.",
  "Về mặt nghệ thuật, tác phẩm là một minh chứng cho trường phái điêu khắc tượng đài Xô-viết ở giai đoạn chín muồi, khi các nghệ sĩ hàng đầu như Vladimir Tsigal đã vượt qua lối minh hoạ đơn thuần để hướng tới sự khái quát và tính biểu tượng. Cách kết hợp mô-típ dân tộc của nhân vật (tre, hoa nhiệt đới) với ngôn ngữ tạo hình hiện đại cho thấy một tư duy sáng tạo cởi mở, tôn trọng văn hoá của đối tượng được tôn vinh — điều làm nên giá trị lâu bền của tượng đài.",
  "Cuối cùng, trong bối cảnh quan hệ quốc tế nhiều biến động, sự tồn tại vững bền của tượng đài và quảng trường mang tên Hồ Chí Minh tại Moskva còn có ý nghĩa như một 'cây cầu ký ức' nối liền quá khứ và hiện tại. Nó nhắc nhở các thế hệ mới của cả hai nước về một chặng đường lịch sử chung, đồng thời là điểm khởi đầu cho những câu chuyện về giao lưu, hợp tác và tình người vượt qua khoảng cách địa lý."
 ]},
 {"heading": "Trải nghiệm dành cho du khách", "paras": [
  "Trải nghiệm cốt lõi tại tượng đài là một khoảnh khắc lắng đọng mang tính tưởng niệm. Không giống những điểm đến ồn ào, náo nhiệt, không gian nơi đây tĩnh lặng và trang nghiêm, rất phù hợp để du khách dừng lại, ngắm nhìn và suy ngẫm. Với nhiều người Việt, chỉ vài phút đứng lặng trước tượng Bác giữa Moskva cũng đủ để lại một ấn tượng khó quên trong cả hành trình.",
  "Hoạt động phổ biến và ý nghĩa nhất là dâng hoa. Các đoàn khách Việt, đặc biệt trong những chuyến đi mang tính về nguồn hoặc vào các dịp lễ, thường chuẩn bị sẵn hoa tươi để đặt dưới chân tượng đài. Nghi thức dâng hoa, dành một phút mặc niệm và chụp ảnh lưu niệm tập thể tạo nên một trải nghiệm giàu cảm xúc, gắn kết các thành viên trong đoàn và để lại kỷ niệm sâu sắc. Hướng dẫn viên có thể chủ động gợi ý và hỗ trợ đoàn chuẩn bị hoa từ trước.",
  "Đây cũng là một địa điểm chụp ảnh giàu ý nghĩa. Khung cảnh tượng đồng nổi bật trên nền cây xanh (mùa hè) hoặc tuyết trắng (mùa đông), cùng tấm biển tên quảng trường bằng tiếng Nga, tạo nên những bức ảnh vừa trang trọng vừa đậm dấu ấn cá nhân. Nhiều du khách xem tấm ảnh bên tượng Bác nơi xứ người là một trong những kỷ vật đáng quý nhất của chuyến đi Nga.",
  "Bên cạnh giá trị tưởng niệm, khu vực quanh tượng đài còn là một lát cắt để du khách cảm nhận nhịp sống thường nhật của Moskva ngoài khu trung tâm du lịch. Đây là khu dân cư và viện nghiên cứu, nên xung quanh có người dân địa phương qua lại, có ghế đá, cây xanh và không khí đời thường bình dị. Trải nghiệm này giúp du khách hiểu thêm về một Moskva 'đời hơn', khác với hình ảnh lộng lẫy thường thấy trên trục Quảng trường Đỏ – Kremlin.",
  "Thời lượng tham quan lý tưởng chỉ khoảng mười lăm đến ba mươi phút, đủ để nghe thuyết minh, dâng hoa (nếu có) và chụp ảnh. Vì là điểm dừng ngắn, trải nghiệm ở đây thường được đặt xen giữa các điểm lớn hơn hoặc gắn với việc di chuyển, nhưng chính sự cô đọng ấy lại làm nổi bật giá trị tinh thần đặc biệt mà không địa điểm nào khác trong hành trình có thể thay thế."
 ]},
 {"heading": "Mẹo tham quan", "paras": [
  "Về thời điểm, nên chọn ban ngày và ưu tiên mùa ấm (khoảng tháng 5 đến tháng 9) để có ánh sáng đẹp, cây xanh và điều kiện thuận lợi cho việc dâng hoa, chụp ảnh. Nếu muốn gắn với dịp đặc biệt, ngày 19 tháng 5 (sinh nhật Bác) và ngày 2 tháng 9 (Quốc khánh) là những thời điểm mà không khí tại tượng đài trở nên trang trọng và đông đảo cộng đồng người Việt, rất đáng để trải nghiệm — song cũng cần lưu ý sắp xếp thời gian vì có thể trùng các hoạt động tập thể.",
  "Về việc chuẩn bị hoa, nếu đoàn có ý định dâng hoa, hướng dẫn viên nên đặt hoa trước tại các cửa hàng hoa ở Moskva (rất sẵn) hoặc nhờ đối tác địa phương chuẩn bị. Một bó hoa trang nhã, màu sắc phù hợp sẽ làm cho nghi thức thêm ý nghĩa. Nên nhắc đoàn giữ thái độ trang nghiêm khi làm lễ, tránh nói cười ồn ào để tôn trọng không gian tưởng niệm.",
  "Về di chuyển, hãy tận dụng ga metro Akademicheskaya làm điểm mốc. Do tượng đài không nằm trên trục trung tâm, việc căn thời gian đi lại rất quan trọng để không làm xáo trộn lịch trình chung. Nếu dùng taxi, nên lưu sẵn địa chỉ bằng tiếng Nga (площадь Хо Ши Мина) để đưa cho tài xế, vì không phải ai cũng quen với tên gọi tiếng Anh hay tiếng Việt.",
  "Về trang phục, vì đây là không gian ngoài trời hoàn toàn, du khách cần chuẩn bị theo mùa: mùa hè mang theo mũ, nước uống; mùa đông cần áo ấm, giày chống trượt vì tuyết và băng. Thời gian dừng ngắn nên không cần nhiều vật dụng, nhưng nên có sẵn máy ảnh hoặc điện thoại đủ pin để ghi lại khoảnh khắc.",
  "Cuối cùng, hãy chuẩn bị nội dung thuyết minh cô đọng nhưng giàu cảm xúc. Vì thời gian dừng ngắn, hướng dẫn viên nên chọn lọc vài thông tin đắt giá: hoàn cảnh ra đời năm 1990, tác giả Vladimir Tsigal, ý nghĩa của vầng mặt trời và chàng trai đứng dậy, câu nói khắc trên bệ tượng. Một bài thuyết minh ngắn gọn, chạm tới cảm xúc sẽ hiệu quả hơn nhiều so với việc liệt kê dài dòng, giúp đoàn giữ được ấn tượng đẹp về điểm dừng đặc biệt này."
 ]},
 {"heading": "Khám phá xung quanh", "paras": [
  "Ngay gần tượng đài, trong cùng khu Akademichesky, là Bảo tàng Darwin Quốc gia — một trong những bảo tàng lịch sử tự nhiên lớn và hiện đại bậc nhất châu Âu. Với hệ thống trưng bày sinh động về tiến hoá, đa dạng sinh học và nhiều khu tương tác hấp dẫn, đây là điểm ghép lý tưởng để bổ sung cho hành trình, đặc biệt phù hợp với các đoàn có trẻ em. Việc kết hợp tượng đài với Bảo tàng Darwin giúp lấp đầy một buổi tham quan trọn vẹn ở khu Tây Nam Moskva.",
  "Cũng thuộc trục Tây Nam, đại lộ Leninsky (Leninsky Prospekt) là một trong những đại lộ lớn và đẹp của Moskva, với kiến trúc thời Xô-viết bề thế. Trên trục này có Quảng trường Gagarin cùng tượng đài Yuri Gagarin — nhà du hành vũ trụ đầu tiên của nhân loại — làm bằng titan, cao vút và rất ấn tượng. Đây là một điểm dừng thú vị khác nếu đoàn muốn tìm hiểu thêm về niềm tự hào chinh phục vũ trụ của nước Nga.",
  "Khu Cheryomushki lân cận là một 'bảo tàng sống' về kiến trúc nhà ở thời Xô-viết — nơi khởi nguồn của mô hình các khu chung cư lắp ghép hàng loạt từng lan rộng khắp Liên Xô. Dạo qua khu vực này, du khách có thể hình dung phần nào đời sống đô thị của người dân Moskva trong thế kỷ 20, một góc nhìn khác biệt và chân thực so với những công trình hoàng gia tráng lệ ở trung tâm.",
  "Về phía Tây, không quá xa, là cụm điểm đến nổi tiếng gồm Đại học Tổng hợp Quốc gia Moskva (toà nhà chính theo phong cách 'bánh cưới' Stalin) và Đồi Chim Sẻ với đài quan sát nhìn toàn cảnh thành phố. Từ khu Akademicheskaya, việc nối tuyến sang hướng này khá thuận tiện, tạo thành một hành trình khám phá phía Tây và Tây Nam Moskva logic về mặt địa lý.",
  "Nếu còn thời gian và muốn kết hợp ẩm thực, khu Tây Nam Moskva có nhiều quán ăn, trong đó rải rác có các nhà hàng, quán ăn Việt phục vụ cộng đồng đông đảo người Việt tại đây. Một bữa ăn với hương vị quê nhà sau khi viếng tượng đài Bác sẽ khép lại trải nghiệm một cách ấm áp và trọn vẹn, đặc biệt ý nghĩa với các đoàn khách Việt lần đầu tới Nga."
 ]},
 {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
  "Một chi tiết ít người biết là để tạc nên tượng đài, nhà điêu khắc Vladimir Tsigal đã đích thân sang Việt Nam vào năm 1985. Với một nghệ sĩ tượng đài tầm cỡ, việc lặn lội tới tận quê hương của nhân vật để cảm nhận không khí, con người và cảnh vật cho thấy sự nghiêm túc và tôn trọng hiếm có. Chính chuyến đi ấy đã giúp ông đưa được những hình ảnh rất Việt Nam — cây tre, hoa nhiệt đới — vào một tác phẩm dựng giữa lòng Moskva, điều mà một nghệ sĩ chỉ ngồi ở xưởng vẽ khó lòng làm được thuyết phục đến vậy.",
  "Bản thân tác giả Vladimir Yefimovich Tsigal (1917–2013) là một trong những tên tuổi lớn nhất của nền điêu khắc tượng đài Xô-viết. Ông là tác giả của nhiều công trình nổi tiếng, trong đó có các cụm tượng đài hoành tráng tưởng niệm chiến tranh và các nhân vật lịch sử. Việc một bậc thầy như ông được chọn để thực hiện tượng đài Chủ tịch Hồ Chí Minh cho thấy tầm quan trọng mà phía Liên Xô dành cho công trình này — đây không phải một tác phẩm 'làm cho có', mà là sản phẩm của tài năng đỉnh cao.",
  "Có một sự trùng hợp giàu ý nghĩa về mặt thời gian: tượng đài được khánh thành ngày 18 tháng 5 năm 1990, chỉ một ngày trước lễ kỷ niệm 100 năm ngày sinh Chủ tịch Hồ Chí Minh. Như vậy, công trình ra đời đúng vào thời khắc cả thế giới hướng về kỷ niệm trọng đại này, và cũng nằm trong số những tượng đài cuối cùng được dựng ở Moskva dưới thời Liên Xô, trước khi đất nước này bước sang một trang sử mới chỉ hơn một năm sau đó.",
  "Trong ký ức của nhiều thế hệ người Việt từng học tập tại Nga, tượng đài gắn liền với những kỷ niệm khó quên. Không ít cựu lưu học sinh kể rằng vào ngày sinh nhật Bác hay dịp Tết, họ cùng nhau ra tượng đài dâng hoa, hát những bài ca cách mạng, và cảm thấy như quê hương ở thật gần. Với họ, đây không chỉ là một tượng đài, mà là một mảnh hồn Việt Nam trên đất Nga, nơi lưu giữ tuổi trẻ và tình yêu Tổ quốc của cả một thế hệ.",
  "Cuối cùng, câu nói được khắc trên bệ tượng — 'Không có gì quý hơn độc lập, tự do' — cũng có một hành trình riêng đầy ý nghĩa. Đó là lời được Chủ tịch Hồ Chí Minh nêu lên trong những năm tháng kháng chiến cam go, sau này trở thành chân lý và phương châm sống của cả dân tộc. Việc chân lý ấy được dịch sang tiếng Nga và khắc trang trọng giữa Moskva khiến nó vượt khỏi biên giới một quốc gia để trở thành thông điệp chung về khát vọng tự do — một giai thoại đẹp về sức lan toả của tư tưởng Hồ Chí Minh trên trường quốc tế."
 ]}
],
"highlights": [
 "Biểu tượng sống động của tình hữu nghị Việt – Nga, khánh thành ngày 18 tháng 5 năm 1990 nhân dịp 100 năm ngày sinh Chủ tịch Hồ Chí Minh.",
 "Tác giả: nhà điêu khắc Xô-viết lừng danh Vladimir Tsigal và kiến trúc sư Roman Kananin; Tsigal từng sang Việt Nam năm 1985 để nghiên cứu.",
 "Cụm tượng đồng với vầng mặt trời chạm nổi chân dung Bác và hình chàng trai Việt Nam vươn mình đứng dậy — biểu tượng cho dân tộc giành độc lập.",
 "Khắc câu nói bất hủ 'Không có gì quý hơn độc lập, tự do' bằng tiếng Nga trên bệ tượng.",
 "Chi tiết đậm bản sắc Việt: cây tre và hoa nhiệt đới hoà cùng ngôn ngữ điêu khắc hiện đại.",
 "Toạ lạc trên Quảng trường Hồ Chí Minh (площадь Хо Ши Мина), quận Akademichesky, gần ga metro Akademicheskaya.",
 "Điểm hẹn truyền thống của cộng đồng người Việt tại Nga vào các dịp 19/5, 2/9 và Tết.",
 "Điểm dừng ngắn nhưng giàu cảm xúc, lý tưởng để mở đầu hoặc kết thúc hành trình Moskva cho đoàn khách Việt."
],
"images": [
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ho%20Chi%20Minh%20-%201946%20Portrait.jpg", "caption": "Chân dung Chủ tịch Hồ Chí Minh (1946) — nhân vật được tôn vinh qua tượng đài tại Moskva. (Ảnh tư liệu, Wikimedia Commons; kho ảnh mở hiện chưa có ảnh tự do rõ nét về chính tượng đài.)"}
],
"references": [
 {"title": "Ho Chi Minh Monument, Moscow — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Ho_Chi_Minh_Monument,_Moscow"},
 {"title": "Ho Chi Minh Monument (Moscow) — Wikidata (Q13668691)", "url": "https://www.wikidata.org/wiki/Q13668691"},
 {"title": "Tượng đài Hồ Chí Minh ở Moskva: biểu tượng hữu nghị Việt – Nga — Báo Nhân Dân (EN)", "url": "https://en.nhandan.vn/ho-chi-minh-monument-in-moscow-a-symbol-of-vietnam-russia-friendship-post85896.html"},
 {"title": "President Ho Chi Minh in memories of Russian people — Vietnam+ (VietnamPlus)", "url": "https://en.vietnamplus.vn/president-ho-chi-minh-in-memories-of-russian-people-post201689.vnp"},
 {"title": "Visiting Ho Chi Minh Square in Moscow — Hours, Tickets, Travel Tips (Audiala)", "url": "https://audiala.com/en/russia/moscow/ho-chi-minh-monument-moscow"},
 {"title": "Ho Chi Minh monument – Moscow (Left side of the road, ghi chép du hành)", "url": "https://michaelharrison.org.uk/2024/07/ho-chi-minh-monument-moscow/"}
],
"sources": [
 "Wikipedia tiếng Anh — mục 'Ho Chi Minh Monument, Moscow' (vị trí, tác giả Vladimir Tsigal & Roman Kananin, khánh thành 18/5/1990, mô tả đĩa đồng – chàng trai – tre – hoa, câu khắc tiếng Nga).",
 "Wikidata Q13668691 — dữ liệu định danh và toạ độ tượng đài.",
 "Báo Nhân Dân (bản tiếng Anh) — ý nghĩa biểu tượng hữu nghị Việt – Nga và hoạt động dâng hoa của cộng đồng.",
 "VietnamPlus (Thông tấn xã Việt Nam) — ký ức của người Nga và cộng đồng người Việt về Chủ tịch Hồ Chí Minh.",
 "Audiala — thông tin thực dụng về Quảng trường Hồ Chí Minh, ga metro Akademicheskaya, cách tiếp cận.",
 "Ghi chép du hành 'Left side of the road' (michaelharrison.org.uk, 2024) — quan sát thực địa về vị trí và bố cục tượng đài.",
 "Dữ kiện nền về nhà điêu khắc Vladimir Yefimovich Tsigal (1917–2013) tổng hợp từ tiểu sử phổ biến trên Wikipedia.",
 "Câu nói 'Không có gì quý hơn độc lập, tự do' — theo tư liệu lịch sử Việt Nam về lời kêu gọi của Chủ tịch Hồ Chí Minh."
]
}

d = json.loads(json.dumps(d), object_hook=lambda o: {k: (unicodedata.normalize("NFC", v) if isinstance(v, str) else v) for k, v in o.items()})

def norm(o):
    if isinstance(o, str): return unicodedata.normalize("NFC", o)
    if isinstance(o, list): return [norm(x) for x in o]
    if isinstance(o, dict): return {k: norm(v) for k, v in o.items()}
    return o
d = norm(d)

out = os.path.join(HERE, "doc_" + d["slug"] + ".json")
json.dump(d, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
wc = sum(len(p.split()) for s in d["sections"] for p in s["paras"])
print("WROTE", out, "| sections:", len(d["sections"]), "| body words:", wc)
