# -*- coding: utf-8 -*-
import json, os, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__))

d = {
"slug": "cabin-of-peter-the-great",
"name_vi": "Ngôi nhà nhỏ của Pyotr Đại đế",
"name_ru": "Домик Петра I",
"name_en": "Cabin of Peter the Great",
"subtitle": "Công trình cổ nhất còn lại của Saint Petersburg — ngôi nhà gỗ được lính trung đoàn Semyonovsky dựng chỉ trong ba ngày vào tháng 5 năm 1703, ngay khi thành phố vừa khai sinh; là 'cung điện' đầu tiên của Sa hoàng Pyotr I, nay nằm trong một mái che bằng gạch và mở cửa làm bảo tàng.",
"sections": [
 {"heading": "Giới thiệu chung", "paras": [
  "Bên bờ kè Petrovskaya nhìn ra sông Neva, ở khu Petrograd của Saint Petersburg, có một ngôi nhà gỗ nhỏ bé nép mình bên trong một lớp 'vỏ' bằng gạch. Đó là Ngôi nhà nhỏ của Pyotr Đại đế (tiếng Nga: Домик Петра I) — công trình cổ nhất còn tồn tại của cả thành phố Saint Petersburg. Trong khi thành phố nổi tiếng với những cung điện nguy nga, quảng trường rộng lớn và nhà thờ tráng lệ, thì chính ngôi nhà gỗ khiêm nhường này lại là 'viên gạch đầu tiên', gắn liền với khoảnh khắc khai sinh của một trong những đô thị đẹp nhất thế giới.",
  "Điều khiến ngôi nhà trở nên đặc biệt không nằm ở quy mô hay sự lộng lẫy, mà ở ý nghĩa lịch sử vô giá của nó. Đây là nơi ở đầu tiên của Sa hoàng Pyotr I (Pyotr Đại đế) tại thành phố mà chính ông sáng lập, nơi ông cư ngụ trong những năm tháng đầu tiên khi đích thân giám sát việc xây dựng Pháo đài Thánh Phêrô và Phaolô cùng cả kinh đô mới. Ngôi nhà vì thế là chứng nhân trực tiếp cho buổi bình minh của Saint Petersburg và cho tầm nhìn phi thường của vị Sa hoàng cải cách.",
  "Ngôi nhà được dựng bằng gỗ chỉ trong vòng ba ngày vào tháng 5 năm 1703, bởi những người lính của trung đoàn Semyonovsky — một tốc độ đáng kinh ngạc phản ánh sự khẩn trương của công cuộc lập thành. Với diện tích chỉ khoảng sáu mươi mét vuông, ngôi nhà mang dáng dấp kết hợp giữa nhà gỗ izba truyền thống của Nga và kiểu nhà Hà Lan mà Pyotr Đại đế yêu thích, với những ô cửa sổ lớn và mái dốc cao. Sự khiêm tốn của công trình cũng phản ánh tính cách giản dị và thực tế của vị Sa hoàng.",
  "Để bảo vệ ngôi nhà gỗ mong manh khỏi thời tiết khắc nghiệt và sự tàn phá của thời gian, ngay từ năm 1723, người ta đã cho dựng một lớp 'vỏ' che bên ngoài, về sau được thay bằng mái che gạch như hiện nay. Chính nhờ sự bảo vệ này mà ngôi nhà tồn tại được qua hơn ba thế kỷ. Ngày nay, ngôi nhà mở cửa làm bảo tàng (chi nhánh của Bảo tàng Nga), cho phép du khách bước vào không gian sống giản dị của vị Sa hoàng vĩ đại nhất lịch sử Nga.",
  "Là tài liệu thuyết minh nội bộ, phần trình bày dưới đây tổng hợp và biên soạn lại từ các nguồn tư liệu tiếng Anh và tiếng Nga về lịch sử, kiến trúc và ý nghĩa của công trình. Mục tiêu là cung cấp cho hướng dẫn viên đầy đủ chất liệu để giới thiệu một điểm đến tuy nhỏ bé nhưng mang ý nghĩa biểu tượng to lớn — nơi khởi đầu của cả một thành phố và của một chương mới trong lịch sử nước Nga."
 ]},
 {"heading": "Vị trí & cách di chuyển", "paras": [
  "Ngôi nhà nhỏ của Pyotr Đại đế toạ lạc tại số 6 bờ kè Petrovskaya (Petrovskaya naberezhnaya), thuộc khu Petrograd của Saint Petersburg, ngay bên sông Neva. Toạ độ địa lý xấp xỉ 59,955 độ vĩ Bắc và 30,331 độ kinh Đông. Vị trí bên bờ sông này rất đẹp và giàu ý nghĩa lịch sử, gần nhiều điểm đến nổi tiếng của khu Petrograd, thuận tiện để kết hợp trong một hành trình tham quan.",
  "Cách tiếp cận thuận tiện nhất là bằng tàu điện ngầm. Ga gần nhất là Gorkovskaya (tuyến số 2, màu xanh dương), từ đó du khách chỉ cần đi bộ vài phút là tới ngôi nhà. Ga Gorkovskaya cũng gần Pháo đài Petro-Pavlovsk và dinh thự Kshesinskaya, nên khu vực này rất thuận tiện để tham quan nhiều điểm đến gần nhau trong cùng một buổi.",
  "Nếu di chuyển bằng taxi hay xe công nghệ, du khách có thể lấy mốc là bờ kè Petrovskaya hoặc Pháo đài Petro-Pavlovsk. Từ trung tâm lịch sử bên kia sông Neva, quãng đường khá ngắn, chỉ mất khoảng mười tới mười lăm phút. Việc kết hợp phương tiện công cộng với đi bộ dọc bờ kè là lựa chọn lý tưởng, vừa thuận tiện vừa cho phép du khách chiêm ngưỡng khung cảnh sông Neva tuyệt đẹp.",
  "Về giờ mở cửa và vé, ngôi nhà hoạt động như một bảo tàng thuộc Bảo tàng Nga; thường đóng cửa một ngày trong tuần và có thể có thêm một ngày vệ sinh hằng tháng, nên hướng dẫn viên cần kiểm tra lịch trước khi đưa đoàn tới. Vé vào cửa ở mức thấp, có ưu đãi cho học sinh, sinh viên và người cao tuổi. Vì ngôi nhà rất nhỏ, thời gian tham quan bên trong khá ngắn, phù hợp để ghé nhanh trong một hành trình lớn hơn.",
  "Về tổ chức lộ trình, do quy mô nhỏ và thời lượng tham quan chỉ khoảng ba mươi tới bốn mươi lăm phút, ngôi nhà rất phù hợp để ghép với các điểm đến lân cận. Cách bố trí hợp lý là kết hợp với chuyến dạo bờ kè Petrovskaya, ghé tuần dương hạm Rạng Đông gần đó, và kết nối với Pháo đài Petro-Pavlovsk hay dinh thự Kshesinskaya. Đây là điểm dừng lý tưởng để mở đầu cho một buổi khám phá khu Petrograd, bắt đầu từ chính nơi thành phố khai sinh."
 ]},
 {"heading": "Lịch sử hình thành và phát triển", "paras": [
  "Lịch sử ngôi nhà gắn liền với khoảnh khắc khai sinh của Saint Petersburg vào tháng 5 năm 1703. Khi ấy, Sa hoàng Pyotr I vừa giành được vùng đất bên bờ sông Neva từ tay Thụy Điển trong cuộc Đại chiến phương Bắc, và quyết định xây dựng tại đây một thành phố – cảng biển mới, một 'cửa sổ nhìn ra châu Âu' cho nước Nga. Để có nơi ở ngay tại công trường, một ngôi nhà gỗ đã được dựng lên khẩn trương cho vị Sa hoàng.",
  "Điều đáng kinh ngạc là ngôi nhà được những người lính trung đoàn Semyonovsky dựng xong chỉ trong ba ngày. Tốc độ này phản ánh cả sự khẩn trương của công cuộc lập thành lẫn tính cách quyết liệt, thực tế của Pyotr Đại đế — người không muốn chờ đợi tiện nghi mà cần có mặt ngay tại chỗ để chỉ đạo công việc. Ngôi nhà gỗ giản dị này trở thành 'cung điện' đầu tiên của Sa hoàng tại thành phố mang tên ông.",
  "Pyotr Đại đế đã sống trong ngôi nhà này trong những năm đầu của thành phố, khoảng từ năm 1703 tới 1708, đúng vào giai đoạn ông đích thân giám sát việc xây dựng Pháo đài Thánh Phêrô và Phaolô cùng những công trình nền móng của kinh đô mới. Từ ngôi nhà nhỏ bên sông, ông có thể quan sát và điều hành công cuộc kiến thiết đang diễn ra sôi động khắp nơi. Ngôi nhà vì thế là 'tổng hành dinh' đầu tiên của cả dự án vĩ đại mang tên Saint Petersburg.",
  "Ý thức được giá trị lịch sử của ngôi nhà, ngay từ năm 1723, Pyotr Đại đế đã cho dựng một lớp che bảo vệ bên ngoài để gìn giữ công trình gỗ mong manh. Ông muốn ngôi nhà được bảo tồn cho hậu thế như một kỷ vật về sự khiêm tốn của bản thân và về buổi đầu khai sinh thành phố. Qua các thời kỳ sau, lớp vỏ bảo vệ này được cải tạo và thay thế — trong đó có việc xây dựng lại bằng gạch vào thế kỷ 19 — để bảo đảm ngôi nhà tồn tại vững chắc qua thời gian.",
  "Trải qua hơn ba thế kỷ với biết bao biến động lịch sử — từ thời đế quốc, qua các cuộc cách mạng, hai cuộc thế chiến cho tới ngày nay — ngôi nhà vẫn được gìn giữ nguyên vẹn nhờ lớp bảo vệ và sự trân trọng của các thế hệ. Ngày nay, ngôi nhà là một chi nhánh của Bảo tàng Nga, mở cửa đón du khách tới chiêm ngưỡng và tìm hiểu về buổi bình minh của thành phố. Việc một công trình gỗ nhỏ bé tồn tại được lâu đến vậy là một kỳ tích, và là minh chứng cho ý nghĩa biểu tượng đặc biệt mà nó nắm giữ."
 ]},
 {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
  "Về mặt kiến trúc, ngôi nhà là một công trình gỗ nhỏ với diện tích chỉ khoảng sáu mươi mét vuông — khiêm tốn đến bất ngờ đối với nơi ở của một vị Sa hoàng. Chính sự giản dị này lại là đặc điểm nổi bật nhất, phản ánh tính cách thực tế, không ưa phô trương của Pyotr Đại đế, người sẵn sàng sống trong một ngôi nhà đơn sơ để có mặt ngay tại công trường xây dựng thành phố.",
  "Ngôi nhà mang một sự pha trộn kiến trúc thú vị: vừa gợi hình dáng nhà gỗ izba truyền thống của Nga, vừa mang ảnh hưởng của kiểu nhà Hà Lan mà Pyotr Đại đế đặc biệt yêu thích sau chuyến đi khảo sát châu Âu. Dấu ấn Hà Lan thể hiện qua những ô cửa sổ lớn, được chăm chút và phần mái dốc cao. Sự kết hợp Đông – Tây này phản ánh chính con người Pyotr: một vị Sa hoàng Nga say mê học hỏi kỹ thuật và văn hoá phương Tây để hiện đại hoá đất nước.",
  "Một chi tiết đặc sắc là các bức tường bên trong được sơn màu đỏ để giả làm gạch — một thủ pháp trang trí khiến ngôi nhà gỗ trông như được xây bằng gạch. Vì đặc điểm này, ngôi nhà đôi khi được gọi là 'ngôi nhà đỏ' hay 'căn phòng đỏ'. Chi tiết nhỏ này cho thấy dù giản dị, ngôi nhà vẫn được chăm chút về mặt thẩm mỹ, đồng thời phản ánh gu thẩm mỹ và sự tinh tế trong cách bài trí thời bấy giờ.",
  "Đặc điểm kiến trúc độc đáo nhất, xét về tổng thể, chính là lớp 'vỏ' bảo vệ bao bọc bên ngoài ngôi nhà gỗ. Việc một công trình được đặt bên trong một công trình khác — ngôi nhà gỗ nằm gọn trong mái che bằng gạch — là một giải pháp bảo tồn độc đáo và hiếm thấy. Lớp vỏ này không chỉ có chức năng bảo vệ mà còn tạo nên một 'khung' trang trọng, tôn vinh giá trị di tích của ngôi nhà bên trong, biến toàn bộ tổ hợp thành một dạng 'quan tài kính' khổng lồ gìn giữ báu vật lịch sử.",
  "Bên trong ngôi nhà, không gian được bài trí để tái hiện điều kiện sống của Pyotr Đại đế thời bấy giờ, với những vật dụng, đồ đạc gắn với ông. Sự đơn sơ của nội thất càng làm nổi bật sự tương phản giữa tầm vóc lịch sử của nhân vật và sự giản dị trong đời sống thường nhật của ông. Đây chính là điều tạo nên sức lay động đặc biệt của ngôi nhà: nó cho thấy một khía cạnh rất người, rất đời thường của một trong những nhân vật vĩ đại nhất lịch sử Nga."
 ]},
 {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
  "Điểm nhấn đầu tiên và quan trọng nhất chính là ý nghĩa 'công trình cổ nhất Saint Petersburg' của ngôi nhà. Hướng dẫn viên nên nhấn mạnh rằng du khách đang đứng trước 'viên gạch đầu tiên' của cả thành phố, nơi khởi đầu của mọi công trình lộng lẫy khác. Nhận thức này biến một ngôi nhà gỗ nhỏ bé thành một điểm đến mang ý nghĩa biểu tượng sâu sắc, đáng để dừng chân và chiêm nghiệm.",
  "Điểm nhấn thứ hai là lớp 'vỏ' bảo vệ bằng gạch bao quanh ngôi nhà gỗ — một giải pháp bảo tồn độc đáo. Việc quan sát cách ngôi nhà gỗ được đặt gọn bên trong một công trình che chở khác là một trải nghiệm thị giác thú vị, đồng thời cho thấy sự trân trọng mà các thế hệ dành cho di tích. Đây là chi tiết đặc biệt mà ít công trình nào trên thế giới có được.",
  "Điểm nhấn thứ ba là không gian nội thất giản dị bên trong, nơi tái hiện điều kiện sống của Pyotr Đại đế. Việc chiêm ngưỡng những căn phòng nhỏ, các vật dụng đơn sơ và các bức tường sơn đỏ giả gạch giúp du khách hình dung đời sống thường nhật của vị Sa hoàng trong những năm tháng đầu xây dựng thành phố. Sự tương phản giữa tầm vóc nhân vật và sự khiêm tốn của nơi ở là điều gây ấn tượng mạnh.",
  "Điểm nhấn thứ tư là các hiện vật và câu chuyện gắn với Pyotr Đại đế được trưng bày trong bảo tàng. Những đồ vật cá nhân, dụng cụ và tư liệu giúp du khách hiểu thêm về con người, sở thích và tầm nhìn của vị Sa hoàng. Đây là cơ hội để tiếp cận một khía cạnh gần gũi, cụ thể của một nhân vật lịch sử vĩ đại, thay vì chỉ biết đến ông qua những thành tựu to lớn và trừu tượng.",
  "Cuối cùng, đừng bỏ lỡ khung cảnh bên ngoài, đặc biệt là vị trí đẹp bên bờ sông Neva. Bờ kè Petrovskaya với tầm nhìn ra dòng sông và các công trình lịch sử là một không gian tuyệt đẹp để dạo bộ và chụp ảnh. Trên bờ kè gần đó còn có những bức tượng sư tử đá mang phong cách phương Đông, tạo nên điểm nhấn thú vị. Sự kết hợp giữa ngôi nhà lịch sử và khung cảnh sông nước khiến trải nghiệm tham quan thêm trọn vẹn và đáng nhớ."
 ]},
 {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
  "Ngôi nhà nhỏ của Pyotr Đại đế mang ý nghĩa lịch sử vô giá như biểu tượng cho sự khai sinh của Saint Petersburg — thành phố đã trở thành kinh đô của Đế quốc Nga trong hơn hai thế kỷ và là một trong những trung tâm văn hoá lớn của thế giới. Là công trình cổ nhất còn lại, ngôi nhà là sợi dây kết nối trực tiếp với khoảnh khắc năm 1703, khi tầm nhìn của Pyotr Đại đế bắt đầu biến vùng đầm lầy bên sông Neva thành một đô thị tráng lệ.",
  "Ngôi nhà cũng là biểu tượng cho tính cách và tầm vóc của chính Pyotr Đại đế — vị Sa hoàng cải cách vĩ đại nhất lịch sử Nga. Sự giản dị của nơi ở, cùng việc ông đích thân có mặt tại công trường, phản ánh một phong cách lãnh đạo thực tế, quyết liệt và không ngại xắn tay vào việc. Ngôi nhà cho thấy một Pyotr Đại đế không chỉ ra lệnh từ xa mà trực tiếp lăn xả vào công cuộc kiến thiết, một hình ảnh đầy cảm hứng về người lãnh đạo dấn thân.",
  "Việc Pyotr Đại đế chủ động cho bảo tồn ngôi nhà ngay từ năm 1723 cũng mang ý nghĩa văn hoá đặc biệt: nó cho thấy ý thức sớm về việc gìn giữ di sản và ký ức lịch sử. Ông muốn các thế hệ sau ghi nhớ về buổi đầu khiêm tốn của thành phố và về chính sự giản dị của mình. Đây có thể xem là một trong những hành động 'bảo tồn di tích' có ý thức đầu tiên trong lịch sử Nga, đi trước thời đại của mình.",
  "Trong bối cảnh Saint Petersburg nổi tiếng với vô số cung điện, nhà thờ và công trình nguy nga, sự tồn tại của ngôi nhà gỗ khiêm nhường này tạo nên một sự tương phản giàu ý nghĩa. Nó nhắc nhở rằng ngay cả những đô thị tráng lệ nhất cũng khởi đầu từ những điều giản dị, và rằng đằng sau vẻ hào nhoáng luôn có một câu chuyện về khát vọng, lao động và tầm nhìn của con người. Ngôi nhà vì thế mang một thông điệp nhân văn sâu sắc.",
  "Với du khách, và đặc biệt là du khách Việt Nam, câu chuyện về Pyotr Đại đế và ngôi nhà nhỏ này gợi nhiều liên tưởng và cảm hứng. Hình ảnh một nhà lãnh đạo giản dị, quyết đoán, đích thân dấn thân vào công cuộc dựng xây đất nước là điều dễ đồng cảm và ngưỡng mộ. Ngôi nhà vì thế không chỉ là một di tích để chiêm ngưỡng mà còn là nguồn cảm hứng về ý chí, tầm nhìn và tinh thần dấn thân — những giá trị vượt qua mọi biên giới quốc gia và thời đại."
 ]},
 {"heading": "Trải nghiệm dành cho du khách", "paras": [
  "Trải nghiệm cốt lõi tại ngôi nhà là cảm giác được chạm vào khoảnh khắc khai sinh của Saint Petersburg. Dù chỉ là một công trình nhỏ, ngôi nhà mang lại một cảm xúc đặc biệt: du khách đang đứng nơi mọi thứ bắt đầu, nơi tầm nhìn của Pyotr Đại đế được hiện thực hoá bằng những viên gạch, tấm gỗ đầu tiên. Đây là một trải nghiệm mang tính biểu tượng và giàu ý nghĩa hơn nhiều so với quy mô khiêm tốn của công trình.",
  "Việc tham quan bên trong ngôi nhà, dù ngắn gọn, mang lại cảm giác thân mật và gần gũi hiếm có. Được đứng trong chính không gian mà Pyotr Đại đế từng sống, ngắm nhìn những căn phòng nhỏ và các bức tường sơn đỏ giả gạch, du khách có thể hình dung đời sống thường nhật của vị Sa hoàng. Cảm giác kết nối trực tiếp với một nhân vật lịch sử vĩ đại qua không gian sống của ông là điều đặc biệt lay động.",
  "Đối với những ai yêu lịch sử, ngôi nhà là một điểm khởi đầu lý tưởng để hiểu về Pyotr Đại đế và công cuộc xây dựng Saint Petersburg. Các hiện vật và câu chuyện được trưng bày giúp du khách nắm bắt bối cảnh lịch sử và tầm vóc của nhân vật. Từ điểm khởi đầu này, du khách có thể tiếp tục hành trình khám phá các công trình lớn hơn của thành phố với một sự hiểu biết và cảm nhận sâu sắc hơn.",
  "Khung cảnh bên ngoài, với vị trí đẹp bên bờ sông Neva, mang lại một trải nghiệm dễ chịu và thư thái. Du khách có thể dạo bộ dọc bờ kè Petrovskaya, ngắm nhìn dòng sông và các công trình lịch sử phía bên kia, đồng thời chiêm ngưỡng những bức tượng sư tử đá độc đáo trên bờ kè. Sự kết hợp giữa tham quan di tích và tận hưởng khung cảnh sông nước tạo nên một trải nghiệm cân bằng và thú vị.",
  "Thời lượng tham quan hợp lý khoảng ba mươi tới bốn mươi lăm phút, phù hợp để ghé nhanh trong một hành trình lớn hơn khám phá khu Petrograd. Là một điểm dừng nhỏ nhưng giàu ý nghĩa, ngôi nhà mang lại một khoảnh khắc lắng đọng và một sự khởi đầu ý nghĩa cho việc tìm hiểu về Saint Petersburg. Đây là lựa chọn tuyệt vời để mở đầu một buổi tham quan, đặt nền tảng cho sự cảm nhận về lịch sử và tầm vóc của thành phố."
 ]},
 {"heading": "Mẹo tham quan", "paras": [
  "Về giờ giấc, hãy kiểm tra trước lịch mở cửa trên trang của Bảo tàng Nga, vì ngôi nhà thường đóng cửa một ngày trong tuần và có thể có thêm một ngày vệ sinh hằng tháng. Việc xác nhận trước giúp tránh tình huống đưa đoàn tới nơi lại gặp ngày đóng cửa. Vì ngôi nhà nhỏ, nên căn thời gian hợp lý và không cần dành quá nhiều thời gian cho riêng điểm này.",
  "Về việc kết hợp lộ trình, hãy tận dụng vị trí bên bờ kè Petrovskaya để ghép ngôi nhà vào một hành trình khám phá khu Petrograd. Có thể kết hợp với chuyến thăm tuần dương hạm Rạng Đông gần đó, Pháo đài Petro-Pavlovsk và dinh thự Kshesinskaya. Cách bố trí này giúp tạo nên một buổi tham quan liền mạch, giàu ý nghĩa lịch sử, bắt đầu từ chính nơi thành phố khai sinh.",
  "Về việc chuẩn bị kiến thức, hướng dẫn viên nên tìm hiểu trước về Pyotr Đại đế, về hoàn cảnh xây dựng Saint Petersburg và về ý nghĩa của ngôi nhà. Việc kể những câu chuyện hấp dẫn — như việc ngôi nhà được dựng trong ba ngày, hay việc chính Sa hoàng cho bảo tồn nó — sẽ biến một điểm dừng nhỏ thành một trải nghiệm đáng nhớ. Chất lượng thuyết minh là yếu tố quyết định giá trị của chuyến tham quan điểm đến này.",
  "Về thời điểm, mùa hè với thời tiết ấm áp và ngày dài là lúc lý tưởng nhất để tham quan, vì du khách có thể kết hợp dạo bộ dọc bờ kè Petrovskaya và tận hưởng khung cảnh sông Neva. Mùa đông tuyết phủ cũng mang lại một khung cảnh đẹp và trang nghiêm, nhưng cần chuẩn bị trang phục ấm và rút ngắn thời gian ở ngoài trời do giá lạnh.",
  "Cuối cùng, hãy nhắc đoàn dành thời gian quan sát lớp 'vỏ' bảo vệ độc đáo của ngôi nhà và các chi tiết như những bức tường sơn đỏ giả gạch bên trong. Đừng quên ghé thăm những bức tượng sư tử đá trên bờ kè gần đó và tận hưởng khung cảnh sông nước. Việc chú ý tới những chi tiết nhỏ này sẽ giúp du khách cảm nhận trọn vẹn nét độc đáo và ý nghĩa của công trình cổ nhất Saint Petersburg."
 ]},
 {"heading": "Khám phá xung quanh", "paras": [
  "Ngay gần ngôi nhà, dọc theo bờ sông, là tuần dương hạm Rạng Đông (Aurora) — con tàu lịch sử gắn liền với Cách mạng Tháng Mười năm 1917. Là một trong những biểu tượng nổi tiếng nhất của Saint Petersburg, con tàu nay là bảo tàng nổi, cho phép du khách lên tham quan. Việc kết hợp thăm ngôi nhà của Pyotr Đại đế với tuần dương hạm Rạng Đông tạo nên một hành trình thú vị, kết nối hai đầu của lịch sử thành phố: từ buổi khai sinh tới thời cách mạng.",
  "Không xa là Pháo đài Petro-Pavlovsk (Peter and Paul Fortress) — nơi khai sinh thành phố và là công trình mà chính Pyotr Đại đế đã giám sát xây dựng khi sống trong ngôi nhà nhỏ. Với nhà thờ chính toà có ngọn tháp vàng cao vút, nơi an nghỉ của các Sa hoàng, pháo đài là điểm đến biểu tượng bậc nhất. Sự gắn kết lịch sử giữa ngôi nhà và pháo đài khiến việc tham quan cả hai trở nên đặc biệt ý nghĩa.",
  "Cũng trong khu Petrograd là dinh thự Kshesinskaya — công trình Art Nouveau tuyệt đẹp từng thuộc về nữ nghệ sĩ ballet lừng danh, nay là Bảo tàng Lịch sử Chính trị Nga. Việc ghép ngôi nhà của Pyotr Đại đế với dinh thự này mang lại một trải nghiệm tương phản thú vị về kiến trúc và lịch sử, từ ngôi nhà gỗ khiêm nhường của thế kỷ 18 tới một dinh thự lộng lẫy đầu thế kỷ 20 gắn với cách mạng.",
  "Bờ kè Petrovskaya và khu vực xung quanh cũng là một không gian đẹp để dạo bộ, với tầm nhìn ra sông Neva và các công trình lịch sử phía bên kia bờ. Trên bờ kè gần ngôi nhà có những bức tượng sư tử đá mang phong cách phương Đông (Shih Tsza), là điểm nhấn độc đáo và cũng là địa điểm chụp ảnh được nhiều du khách yêu thích. Khung cảnh sông nước nơi đây mang lại cảm giác thư thái, dễ chịu.",
  "Về ẩm thực và nghỉ ngơi, khu Petrograd có nhiều nhà hàng, quán cà phê đa dạng phục vụ cả ẩm thực Nga truyền thống lẫn quốc tế. Đây là nơi thích hợp để dừng chân sau khi tham quan, thưởng thức một bữa ăn hoặc ly trà nóng. Việc kết hợp giữa khám phá lịch sử và thưởng thức ẩm thực địa phương sẽ mang lại một trải nghiệm cân bằng và trọn vẹn về khu Petrograd — một trong những khu vực giàu bản sắc và lịch sử nhất của Saint Petersburg."
 ]},
 {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
  "Câu chuyện ấn tượng nhất về ngôi nhà chính là việc nó được dựng xong chỉ trong ba ngày vào tháng 5 năm 1703. Những người lính trung đoàn Semyonovsky đã hoàn thành công trình với tốc độ đáng kinh ngạc, phản ánh sự khẩn trương của công cuộc lập thành và ý chí quyết liệt của Pyotr Đại đế. Chi tiết này luôn khiến du khách ngạc nhiên và thích thú, đồng thời cho thấy tinh thần 'thần tốc' trong công cuộc xây dựng thành phố ngay từ những ngày đầu tiên.",
  "Một giai thoại thú vị là việc ngôi nhà gỗ của một vị Sa hoàng lại được sơn tường màu đỏ để giả làm gạch. Chi tiết này cho thấy khát vọng của Pyotr Đại đế muốn thành phố mới của mình mang dáng dấp của những đô thị châu Âu xây bằng gạch đá, ngay cả khi điều kiện thực tế buộc phải dùng gỗ. Nó cũng phản ánh một sự tinh tế bất ngờ trong cách bài trí, và là chi tiết khiến ngôi nhà có biệt danh 'căn phòng đỏ'.",
  "Việc chính Pyotr Đại đế ra lệnh bảo tồn ngôi nhà từ năm 1723 là một giai thoại giàu ý nghĩa. Ông muốn công trình được gìn giữ như một kỷ vật về sự khiêm tốn của mình và về buổi đầu của thành phố. Ý thức bảo tồn di sản sớm sủa này rất đáng chú ý, cho thấy một tầm nhìn vượt thời đại: Pyotr không chỉ xây dựng cho hiện tại mà còn nghĩ tới việc lưu giữ ký ức cho hậu thế. Nhờ tầm nhìn ấy mà ngôi nhà tồn tại tới ngày nay.",
  "Sự tương phản giữa ngôi nhà nhỏ bé và tầm vóc vĩ đại của Saint Petersburg mà nó khởi đầu là một 'giai thoại' đáng suy ngẫm. Thật kỳ diệu khi nghĩ rằng từ một ngôi nhà gỗ giản dị chỉ sáu mươi mét vuông, cả một kinh đô tráng lệ với những cung điện, nhà thờ và quảng trường lộng lẫy đã mọc lên. Ngôi nhà như một lời nhắc nhở rằng mọi điều vĩ đại đều có thể bắt đầu từ những khởi điểm khiêm nhường — một thông điệp đầy cảm hứng.",
  "Cuối cùng, những bức tượng sư tử đá mang phong cách phương Đông (thường gọi là Shih Tsza) đặt trên bờ kè gần ngôi nhà cũng có câu chuyện riêng. Những bức tượng này, được đưa từ vùng Mãn Châu về, là biểu tượng cho mối liên hệ và giao lưu của nước Nga với phương Đông. Sự hiện diện của chúng bên cạnh ngôi nhà của Pyotr Đại đế — vị Sa hoàng vốn hướng về phương Tây — tạo nên một sự đối thoại thú vị giữa Đông và Tây, phản ánh vị thế đặc biệt của nước Nga nằm giữa hai nền văn minh. Đây là chi tiết nhỏ nhưng giàu ý nghĩa để hướng dẫn viên khép lại phần thuyết minh."
 ]}
],
"highlights": [
 "Công trình cổ nhất còn lại của Saint Petersburg, dựng bằng gỗ chỉ trong ba ngày vào tháng 5 năm 1703.",
 "Do lính trung đoàn Semyonovsky xây; là 'cung điện' đầu tiên của Sa hoàng Pyotr I tại thành phố ông sáng lập.",
 "Pyotr I sống tại đây khoảng 1703–1708 khi giám sát xây Pháo đài Thánh Phêrô và Phaolô và cả kinh đô mới.",
 "Diện tích chỉ khoảng 60 m²; pha trộn nhà gỗ izba Nga với kiểu nhà Hà Lan (cửa sổ lớn, mái dốc cao).",
 "Tường trong sơn đỏ giả gạch — vì thế được gọi là 'căn phòng đỏ'.",
 "Được che trong lớp 'vỏ' bảo vệ từ năm 1723 (sau xây lại bằng gạch) theo lệnh của chính Pyotr Đại đế.",
 "Nay là chi nhánh của Bảo tàng Nga; gần ga metro Gorkovskaya trên bờ kè Petrovskaya.",
 "Trên bờ kè gần đó có tượng sư tử đá phương Đông (Shih Tsza) và gần tuần dương hạm Rạng Đông."
],
"images": [
 {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Domick%20Petra%20I-2.jpg", "caption": "Ngôi nhà nhỏ của Pyotr Đại đế nằm trong lớp mái che bảo vệ bằng gạch bên bờ kè Petrovskaya."}
],
"references": [
 {"title": "Cabin of Peter the Great — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Cabin_of_Peter_the_Great"},
 {"title": "Peter the Great's Cabin — saint-petersburg.com (museums)", "url": "http://www.saint-petersburg.com/museums/cabin-of-peter-the-great/"},
 {"title": "Peter the Great's Cabin — Rusmania", "url": "https://rusmania.com/north-western/st-petersburg-federal-city/st-petersburg/north-of-the-centre/on-petrogradsky-island/peter-the-greats-cabin"},
 {"title": "Cabin of Peter the Great — A View On Cities", "url": "https://aviewoncities.com/st-petersburg/cabin-of-peter-the-great"},
 {"title": "The Cabin of Peter the Great — saint-petersburg.com (virtual tour)", "url": "http://www.saint-petersburg.com/virtual-tour/cabin/"}
],
"sources": [
 "Wikipedia tiếng Anh — mục 'Cabin of Peter the Great' (công trình cổ nhất Saint Petersburg, dựng trong 3 ngày tháng 5/1703 bởi lính trung đoàn Semyonovsky, Pyotr ở 1703–1708, ~60 m², kết hợp izba Nga và nhà Hà Lan, lớp vỏ bảo vệ 1723).",
 "saint-petersburg.com — hồ sơ 'Peter the Great's Cabin' (mô tả 'căn phòng đỏ', tường sơn đỏ giả gạch, công năng bảo tàng thuộc Bảo tàng Nga).",
 "Rusmania — hồ sơ 'Peter the Great's Cabin' (lịch sử, vị trí trên đảo Petrogradsky).",
 "A View On Cities — mô tả ngôi nhà và lớp che bảo vệ.",
 "Dữ liệu dự án 'Cẩm nang Du lịch Nga' (data/regions/saint-petersburg) — địa chỉ Petrovskaya naberezhnaya 6, gần metro Gorkovskaya, gợi ý kết hợp tuần dương hạm Rạng Đông.",
 "Thông tin nền về Pyotr Đại đế và việc sáng lập Saint Petersburg năm 1703 tổng hợp từ các nguồn bách khoa phổ biến.",
 "Thông tin nền về các lần cải tạo lớp vỏ bảo vệ (thế kỷ 18–19) tổng hợp từ hồ sơ di sản Wikimedia Commons (Category: Cabin of Peter the Great).",
 "Thông tin nền về tượng sư tử đá phương Đông (Shih Tsza) trên bờ kè Petrovskaya tổng hợp từ tư liệu du lịch phổ biến."
]
}

def norm(o):
    if isinstance(o, str): return unicodedata.normalize("NFC", o)
    if isinstance(o, list): return [norm(x) for x in o]
    if isinstance(o, dict): return {k: norm(v) for k, v in o.items()}
    return o
d = norm(d)

out = os.path.join(HERE, "doc_" + d["slug"] + ".json")
json.dump(d, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
wc = sum(len(p.split()) for s in d["sections"] for p in s["paras"])
print("WROTE", out, "| sections:", len(d["sections"]), "| body words:", wc)
