# -*- coding: utf-8 -*-
"""Nghệ An — batch 3 (9 địa điểm). Chèn an toàn."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
F = os.path.join(ROOT, "data", "regions", "vn-nghe-an.json")
REG, RN, FD, UPD = "vn-nghe-an", "Nghệ An", "Miền Trung", "2026-07-27"


def rec(slug, name_vi, name_en, name_ru, cats, lat, lon, addr, rating, review_vi,
        ps_vi, ps_en, ps_ru, pl_vi, pl_en, pl_ru, h_vi, h_en, h_ru, practical, tags, sources, photo=None):
    return {"id": f"{REG}-{slug}", "slug": slug, "region": REG, "country": "vietnam",
            "region_name_vi": RN, "federal_district": FD, "name_vi": name_vi, "name_ru": name_ru,
            "name_en": name_en, "categories": cats, "coordinates": {"lat": lat, "lon": lon},
            "address_vi": addr, "rating": rating, "review_summary_vi": review_vi,
            "presentation_short_vi": ps_vi, "presentation_short_en": ps_en, "presentation_short_ru": ps_ru,
            "presentation_long_vi": pl_vi, "presentation_long_en": pl_en, "presentation_long_ru": pl_ru,
            "highlights_vi": h_vi, "highlights_en": h_en, "highlights_ru": h_ru,
            "practical": practical, "photo": photo, "photo_credit": None, "official_site": None,
            "sources": sources, "tags": tags, "status": "enriched", "last_updated": UPD}


new = [

rec("bao-tang-xo-viet-nghe-tinh",
    "Bảo tàng Xô Viết Nghệ Tĩnh",
    "Soviet Nghe Tinh Museum",
    "Музей Советов Нгетинь",
    ["museum", "monument"],
    18.6778, 105.6805,
    "Trong khuôn viên Thành cổ Vinh, phường Cửa Nam, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.5, "count": 600, "source": "Google", "as_of": "2026-07"},
    "Bảo tàng chuyên đề về phong trào Xô Viết Nghệ Tĩnh 1930–1931; nhiều hiện vật, tư liệu quý. Không gian trong thành cổ, thuyết minh cuốn hút với người thích lịch sử.",
    "Bảo tàng Xô Viết Nghệ Tĩnh nằm trong khuôn viên Thành cổ Vinh, trưng bày về cao trào cách mạng Xô Viết Nghệ Tĩnh 1930–1931 – đỉnh cao đầu tiên của cách mạng Việt Nam dưới sự lãnh đạo của Đảng. Bảo tàng lưu giữ nhiều hiện vật, hình ảnh, tư liệu quý về phong trào.",
    "The Soviet Nghe Tinh Museum, in the grounds of Vinh Citadel, presents the revolutionary high tide of the Nghe Tinh Soviets of 1930-1931, the first peak of Vietnam's revolution under Party leadership. It preserves many precious objects, images and documents about the movement.",
    "Музей Советов Нгетинь на территории крепости Винь рассказывает о революционном подъёме Советов Нгетинь 1930-1931 годов — первой вершине вьетнамской революции под руководством Партии. Он хранит множество ценных предметов, изображений и документов о движении.",
    "Bảo tàng Xô Viết Nghệ Tĩnh tọa lạc ngay trong khuôn viên Thành cổ Vinh, được thành lập nhằm lưu giữ và giới thiệu về phong trào Xô Viết Nghệ Tĩnh những năm 1930–1931 – một cao trào cách mạng rộng lớn của công nông hai tỉnh Nghệ An và Hà Tĩnh dưới sự lãnh đạo của Đảng Cộng sản Việt Nam vừa mới ra đời. Trong phong trào này, nhân dân đã đứng lên đấu tranh mạnh mẽ, ở nhiều nơi chính quyền địch tan rã và các 'Xô viết' – hình thức chính quyền của công nông đầu tiên ở Việt Nam – được thành lập, thực hiện nhiều chính sách tiến bộ. Đây được xem là cuộc tổng diễn tập đầu tiên cho thắng lợi của Cách mạng Tháng Tám sau này. Bảo tàng trưng bày hàng nghìn hiện vật, tài liệu, hình ảnh, bản đồ, mô hình sinh động tái hiện bối cảnh, diễn biến và ý nghĩa của cao trào, cũng như sự hy sinh anh dũng của các chiến sĩ cách mạng và quần chúng. Qua các gian trưng bày, du khách hiểu thêm về truyền thống yêu nước, tinh thần đấu tranh kiên cường của người dân xứ Nghệ. Nằm trong không gian cổ kính của thành cổ, bảo tàng là điểm đến ý nghĩa cho những ai muốn tìm hiểu lịch sử cách mạng Việt Nam, đặc biệt phù hợp với các đoàn học sinh, sinh viên và du khách yêu lịch sử.",
    "The Soviet Nghe Tinh Museum sits within the grounds of Vinh Citadel and was founded to preserve and present the Nghe Tinh Soviet movement of 1930-1931, a broad revolutionary high tide of the workers and peasants of Nghe An and Ha Tinh provinces under the leadership of the newly born Communist Party of Vietnam. In this movement the people rose up in fierce struggle; in many places the enemy's authority collapsed and 'Soviets', the first form of worker-peasant government in Vietnam, were established, carrying out many progressive policies. It is regarded as the first general rehearsal for the later victory of the August Revolution. The museum displays thousands of objects, documents, images, maps and vivid models re-creating the context, course and significance of the high tide, as well as the heroic sacrifice of revolutionaries and the masses. Through its galleries, visitors gain a deeper understanding of the patriotic tradition and indomitable fighting spirit of the people of Nghe An. Set in the ancient space of the citadel, the museum is a meaningful destination for anyone wishing to learn about Vietnam's revolutionary history, especially suited to school and student groups and history-loving travellers.",
    "Музей Советов Нгетинь находится на территории крепости Винь и был основан, чтобы хранить и представлять движение Советов Нгетинь 1930-1931 годов — широкий революционный подъём рабочих и крестьян провинций Нгеан и Хатинь под руководством только что родившейся Коммунистической партии Вьетнама. В ходе этого движения народ поднялся на ожесточённую борьбу; во многих местах власть врага рухнула, и были созданы «Советы» — первая форма рабоче-крестьянской власти во Вьетнаме, проводившая множество прогрессивных мер. Оно считается первой генеральной репетицией будущей победы Августовской революции. Музей демонстрирует тысячи предметов, документов, изображений, карт и живых макетов, воссоздающих контекст, ход и значение подъёма, а также героическую жертву революционеров и масс. Через залы посетители глубже понимают патриотическую традицию и несокрушимый боевой дух жителей Нгеана. Расположенный в древнем пространстве крепости, музей — значимое место для всех, кто хочет узнать революционную историю Вьетнама, особенно подходящее для школьных и студенческих групп и любящих историю путешественников.",
    ["Bảo tàng chuyên đề về cao trào Xô Viết Nghệ Tĩnh 1930–1931",
     "Hàng nghìn hiện vật, tư liệu, hình ảnh, mô hình sinh động",
     "Nằm trong Thành cổ Vinh; điểm học lịch sử ý nghĩa"],
    ["A museum on the Nghe Tinh Soviet high tide of 1930-1931",
     "Thousands of objects, documents, images and vivid models",
     "Located in Vinh Citadel; a meaningful history stop"],
    ["Музей о подъёме Советов Нгетинь 1930-1931 годов",
     "Тысячи предметов, документов, изображений и макетов",
     "Расположен в крепости Винь; значимое место для истории"],
    {"hours_vi": "Khoảng 7:30–11:30 và 13:30–17:00 (nghỉ trưa); nên hỏi trước.",
     "ticket_vi": "Miễn phí hoặc phí thấp.",
     "duration_vi": "Khoảng 45–60 phút.",
     "best_time_vi": "Quanh năm; kết hợp thăm Thành cổ Vinh.",
     "tips_vi": "Nên đi cùng hướng dẫn để hiểu bối cảnh lịch sử; kết hợp trung tâm Vinh."},
    ["history", "museum", "culture", "indoor"],
    [{"title": "Wikipedia (VI) — Xô viết Nghệ Tĩnh", "url": "https://vi.wikipedia.org/wiki/X%C3%B4_vi%E1%BA%BFt_Ngh%E1%BB%87_T%C4%A9nh"}]),

rec("nui-quyet-phuong-hoang-trung-do",
    "Núi Quyết và Phượng Hoàng Trung Đô",
    "Quyet Mountain and Phuong Hoang Trung Do",
    "Гора Куйет и Фыонг Хоанг Чунг До",
    ["monument", "park_garden"],
    18.6580, 105.7150,
    "Phường Trung Đô, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.4, "count": 1400, "source": "Google", "as_of": "2026-07"},
    "Ngọn núi bên sông Lam gắn với kinh đô dang dở của vua Quang Trung; có đền thờ, view sông núi đẹp. Hợp leo núi, ngắm cảnh, tìm hiểu lịch sử Tây Sơn.",
    "Núi Quyết (Lâm viên Núi Quyết) bên bờ sông Lam ở TP. Vinh là nơi vua Quang Trung từng chọn xây kinh đô Phượng Hoàng Trung Đô. Nay là công viên lâm viên với đền thờ vua Quang Trung, cây xanh và điểm ngắm toàn cảnh thành phố, sông Lam và núi Hồng.",
    "Quyet Mountain (Nui Quyet Park) on the bank of the Lam River in Vinh City is where King Quang Trung once chose to build the capital Phuong Hoang Trung Do. Today it is a forest park with a temple to King Quang Trung, greenery and viewpoints over the city, the Lam River and Hong Mountain.",
    "Гора Куйет (парк Нуйкуйет) на берегу реки Лам в городе Винь — место, где король Куанг Чунг некогда выбрал построить столицу Фыонг Хоанг Чунг До. Сегодня это лесопарк с храмом королю Куанг Чунгу, зеленью и смотровыми площадками на город, реку Лам и гору Хонг.",
    "Núi Quyết là ngọn núi nằm ở phường Trung Đô, thành phố Vinh, bên bờ sông Lam, gắn liền với một sự kiện lịch sử quan trọng cuối thế kỷ 18. Năm 1788, sau khi lên ngôi, vua Quang Trung – Nguyễn Huệ đã chọn vùng đất dưới chân núi Quyết, nơi có thế 'sơn thủy hữu tình' với núi Dũng Quyết và núi Kỳ Lân, để xây dựng kinh đô mới mang tên Phượng Hoàng Trung Đô, với ý định dời đô về đây nhằm khống chế cả hai miền Nam – Bắc. Tuy nhiên, do vua Quang Trung mất sớm, công trình còn dang dở và kinh đô này chưa bao giờ được hoàn thành. Ngày nay, khu vực núi Quyết được quy hoạch thành Lâm viên Núi Quyết – một công viên rừng rộng lớn với nhiều cây xanh, đường dạo, cùng đền thờ vua Quang Trung uy nghi được xây dựng trên núi để tưởng nhớ vị anh hùng áo vải. Từ trên đỉnh núi, du khách có thể phóng tầm mắt ngắm toàn cảnh thành phố Vinh, dòng sông Lam uốn khúc đổ ra biển, núi Hồng Lĩnh phía Hà Tĩnh và cầu Bến Thủy nối đôi bờ. Đây là điểm đến kết hợp giữa tham quan di tích lịch sử, dâng hương và tận hưởng không gian thiên nhiên, ngắm cảnh, rất được người dân và du khách yêu thích, nhất là vào buổi chiều mát.",
    "Quyet Mountain lies in Trung Do ward, Vinh City, on the bank of the Lam River, and is tied to an important event of the late 18th century. In 1788, after ascending the throne, King Quang Trung-Nguyen Hue chose the land at the foot of Quyet Mountain, with its 'harmonious mountains and water' between Dung Quyet and Ky Lan hills, to build a new capital named Phuong Hoang Trung Do, intending to move the capital here to command both south and north. However, because King Quang Trung died early, the work remained unfinished and the capital was never completed. Today the Quyet Mountain area is planned as Nui Quyet Forest Park, a large woodland park with greenery, walking paths and a dignified temple to King Quang Trung built on the mountain in memory of the 'cloth-robed hero'. From the summit, visitors can survey the whole of Vinh City, the winding Lam River flowing to the sea, the Hong Linh mountains in Ha Tinh and the Ben Thuy Bridge linking the two banks. It is a destination combining a historical visit, incense offering and enjoyment of nature and views, much loved by residents and travellers, especially in the cool of the afternoon.",
    "Гора Куйет находится в квартале Чунгдо города Винь, на берегу реки Лам, и связана с важным событием конца XVIII века. В 1788 году, взойдя на трон, король Куанг Чунг-Нгуен Хюэ выбрал землю у подножия горы Куйет с её «гармонией гор и воды» между холмами Зунгкуйет и Килан, чтобы построить новую столицу под названием Фыонг Хоанг Чунг До, намереваясь перенести сюда столицу, чтобы держать под контролем и юг, и север. Однако из-за ранней смерти короля Куанг Чунга работы остались незавершёнными, и столица так и не была достроена. Сегодня район горы Куйет спланирован как лесопарк Нуйкуйет — большой лесной парк с зеленью, дорожками и величественным храмом королю Куанг Чунгу, построенным на горе в память о «герое в холщовом одеянии». С вершины гости могут окинуть взглядом весь город Винь, извивающуюся реку Лам, текущую к морю, горы Хонглинь в Хатине и мост Бентхюи, соединяющий два берега. Это место сочетает посещение исторического памятника, воскурение благовоний и наслаждение природой и видами, любимое жителями и путешественниками, особенно в прохладу второй половины дня.",
    ["Nơi vua Quang Trung định xây kinh đô Phượng Hoàng Trung Đô (1788)",
     "Lâm viên Núi Quyết với đền thờ vua Quang Trung trên núi",
     "View toàn cảnh TP. Vinh, sông Lam, núi Hồng và cầu Bến Thủy"],
    ["Where King Quang Trung planned the capital Phuong Hoang Trung Do (1788)",
     "Nui Quyet Forest Park with a mountain temple to King Quang Trung",
     "Panoramas of Vinh City, the Lam River, Hong Mountain and Ben Thuy Bridge"],
    ["Место, где король Куанг Чунг задумал столицу Фыонг Хоанг Чунг До (1788)",
     "Лесопарк Нуйкуйет с горным храмом королю Куанг Чунгу",
     "Панорамы Виня, реки Лам, горы Хонг и моста Бентхюи"],
    {"hours_vi": "Ban ngày; đền thờ khoảng 7:00–17:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 1–1,5 giờ.",
     "best_time_vi": "Chiều mát để ngắm hoàng hôn trên sông Lam.",
     "tips_vi": "Đi giày thoải mái để leo núi; kết hợp dạo TP. Vinh; mang nước uống."},
    ["history", "monument", "viewpoint", "nature", "outdoor", "family"],
    [{"title": "Wikipedia (VI) — Phượng Hoàng Trung Đô", "url": "https://vi.wikipedia.org/wiki/Ph%C6%B0%E1%BB%A3ng_Ho%C3%A0ng_Trung_%C4%90%C3%B4"}]),

rec("chua-can-linh",
    "Chùa Cần Linh (Chùa Sư Nữ)",
    "Can Linh Pagoda",
    "Пагода Канлинь",
    ["church", "monument"],
    18.6710, 105.6880,
    "Phường Cửa Nam, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.6, "count": 900, "source": "Google", "as_of": "2026-07"},
    "Ngôi chùa cổ hàng nghìn năm giữa lòng TP. Vinh, kiến trúc truyền thống yên tĩnh. Không gian thanh tịnh, hợp lễ Phật, vãn cảnh; dịp lễ Vu Lan, đầu năm đông khách.",
    "Chùa Cần Linh, còn gọi là chùa Sư Nữ, là ngôi chùa cổ nhất thành phố Vinh, tương truyền có từ thời nhà Đường. Chùa mang kiến trúc Phật giáo truyền thống, không gian cổ kính, thanh tịnh giữa lòng đô thị, là chốn tâm linh quen thuộc của người dân xứ Nghệ.",
    "Can Linh Pagoda, also called the Nuns' Pagoda, is the oldest pagoda in Vinh City, said to date from the Tang era. With traditional Buddhist architecture and an ancient, serene space in the heart of the city, it is a familiar spiritual site for the people of Nghe An.",
    "Пагода Канлинь, называемая также Монашеской пагодой, — старейшая пагода города Винь, по преданию возникшая в эпоху Тан. С традиционной буддийской архитектурой и древним, безмятежным пространством в сердце города она — привычное духовное место для жителей Нгеана.",
    "Chùa Cần Linh, dân gian quen gọi là chùa Sư Nữ, tọa lạc ở phường Cửa Nam, thành phố Vinh, được xem là ngôi chùa cổ và lớn nhất của thành phố. Theo truyền thuyết và các tư liệu, chùa được khởi dựng từ rất sớm, khoảng thế kỷ 9 dưới thời nhà Đường, trải qua nhiều lần trùng tu, tôn tạo qua các triều đại. Chùa mang đậm phong cách kiến trúc Phật giáo truyền thống Bắc Trung Bộ với tam quan, tòa bái đường, thượng điện, nhà tổ, tháp chuông và khuôn viên rợp bóng cây cổ thụ, ao sen, tạo nên không gian tĩnh lặng, trang nghiêm giữa phố phường sầm uất. Bên trong chùa lưu giữ nhiều pho tượng Phật cổ, chuông đồng, hoành phi câu đối và các hiện vật có giá trị lịch sử, nghệ thuật. Đây là nơi tu hành của các ni sư, đồng thời là điểm sinh hoạt tín ngưỡng quen thuộc của phật tử và người dân địa phương. Vào các ngày rằm, mồng một, lễ Phật đản, Vu Lan hay dịp đầu xuân, chùa đón đông đảo người đến lễ Phật, cầu an, thắp hương. Với bề dày lịch sử và giá trị văn hóa – tâm linh, chùa Cần Linh đã được công nhận là di tích lịch sử – văn hóa cấp quốc gia, trở thành điểm đến ý nghĩa cho du khách muốn tìm chút bình yên và tìm hiểu đời sống tín ngưỡng của người xứ Nghệ.",
    "Can Linh Pagoda, popularly called the Nuns' Pagoda, stands in Cua Nam ward, Vinh City, and is regarded as the oldest and largest pagoda in the city. According to legend and records, it was founded very early, around the 9th century under the Tang, and restored many times across the dynasties. It strongly reflects the traditional Buddhist architecture of north-central Vietnam, with a triple gate, worship hall, upper sanctum, patriarch's house, bell tower and grounds shaded by ancient trees and a lotus pond, creating a quiet, solemn space amid the busy city. Inside it keeps many old Buddha statues, a bronze bell, horizontal lacquered boards, parallel sentences and objects of historical and artistic value. It is a place of practice for nuns and a familiar site of worship for local Buddhists and residents. On full-moon and new-moon days, Buddha's Birthday, the Vu Lan festival and the new year, the pagoda welcomes crowds who come to worship, pray for peace and offer incense. With its long history and cultural-spiritual value, Can Linh Pagoda is recognised as a national historical and cultural relic and is a meaningful destination for visitors seeking calm and an insight into the religious life of Nghe An.",
    "Пагода Канлинь, в народе называемая Монашеской пагодой, стоит в квартале Кыанам города Винь и считается старейшей и крупнейшей пагодой города. Согласно преданию и записям, она была основана очень рано, около IX века при династии Тан, и многократно реставрировалась при разных династиях. Она ярко отражает традиционную буддийскую архитектуру северо-центрального Вьетнама: тройные ворота, молитвенный зал, верхнее святилище, дом патриарха, колокольня и территория, затенённая вековыми деревьями и лотосовым прудом, создают тихое, торжественное пространство среди оживлённого города. Внутри хранятся многие старинные статуи Будды, бронзовый колокол, лаковые доски, парные изречения и предметы исторической и художественной ценности. Это место практики монахинь и привычное место поклонения для местных буддистов и жителей. В дни полнолуния и новолуния, в день рождения Будды, на праздник Вулан и в новый год пагода принимает толпы приходящих поклоняться, молиться о мире и воскурять благовония. С долгой историей и культурно-духовной ценностью пагода Канлинь признана национальным историко-культурным памятником и является значимым местом для гостей, ищущих покой и знакомство с религиозной жизнью Нгеана.",
    ["Ngôi chùa cổ nhất TP. Vinh, tương truyền có từ thời nhà Đường (thế kỷ 9)",
     "Kiến trúc Phật giáo truyền thống, không gian thanh tịnh giữa phố",
     "Di tích lịch sử – văn hóa quốc gia; đông khách dịp lễ Phật, đầu năm"],
    ["The oldest pagoda in Vinh, said to date from the Tang era (9th c.)",
     "Traditional Buddhist architecture, a serene space in the city",
     "A national relic; busy on Buddhist holidays and the new year"],
    ["Старейшая пагода Виня, по преданию — эпохи Тан (IX век)",
     "Традиционная буддийская архитектура, безмятежность в городе",
     "Национальный памятник; многолюдна в буддийские праздники и новый год"],
    {"hours_vi": "Khoảng 6:00–18:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 30–45 phút.",
     "best_time_vi": "Ngày rằm, mồng một, lễ Vu Lan, Phật đản, đầu xuân.",
     "tips_vi": "Ăn mặc kín đáo, giữ yên tĩnh; bỏ dép trước khi vào điện thờ."},
    ["spiritual", "temple", "culture", "history", "indoor"],
    [{"title": "Wikipedia (VI) — Chùa Cần Linh", "url": "https://vi.wikipedia.org/wiki/Ch%C3%B9a_C%E1%BA%A7n_Linh"}]),

rec("den-hong-son",
    "Đền Hồng Sơn (TP. Vinh)",
    "Hong Son Temple (Vinh City)",
    "Храм Хонгшон (город Винь)",
    ["church", "monument"],
    18.6725, 105.6905,
    "Phường Hồng Sơn, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.5, "count": 700, "source": "Google", "as_of": "2026-07"},
    "Ngôi đền cổ trung tâm Vinh thờ Hưng Đạo Vương và các vị thần; kiến trúc chạm khắc đẹp. Không gian tâm linh giữa phố, đông khách dịp lễ; hợp vãn cảnh, chiêm bái.",
    "Đền Hồng Sơn là ngôi đền cổ ở trung tâm thành phố Vinh, thờ Hưng Đạo Đại Vương Trần Quốc Tuấn cùng nhiều vị thần, thánh trong tín ngưỡng dân gian. Đền có kiến trúc truyền thống, chạm khắc tinh xảo, là một trong những trung tâm sinh hoạt tín ngưỡng lớn của xứ Nghệ.",
    "Hong Son Temple is an ancient temple in central Vinh City honouring Hung Dao Dai Vuong Tran Quoc Tuan and many folk deities and saints. With traditional architecture and fine carving, it is one of Nghe An's major centres of religious life.",
    "Храм Хонгшон — древний храм в центре города Винь, посвящённый Хынг Дао Дай Выонгу Чан Куок Туану и многим народным божествам и святым. С традиционной архитектурой и тонкой резьбой он — один из главных центров религиозной жизни Нгеана.",
    "Đền Hồng Sơn nằm ở phường Hồng Sơn, ngay khu vực trung tâm thành phố Vinh, gần chợ Vinh. Đây là một ngôi đền cổ có quy mô lớn, được xây dựng từ thời Nguyễn, ban đầu là Võ Miếu thờ các danh tướng, về sau thờ chính Hưng Đạo Đại Vương Trần Quốc Tuấn – vị anh hùng dân tộc ba lần đánh thắng quân Nguyên Mông, cùng nhiều vị thần, thánh khác như Thánh Mẫu, các vị trong tín ngưỡng thờ Mẫu. Ngôi đền mang phong cách kiến trúc truyền thống với hệ thống cổng, sân, các tòa điện thờ được bố trí hài hòa, nổi bật là nghệ thuật chạm khắc gỗ tinh xảo trên các cột kèo, hoành phi, câu đối, cùng nhiều hiện vật, đồ thờ cổ có giá trị. Nằm giữa lòng đô thị nhộn nhịp, đền Hồng Sơn vẫn giữ được nét cổ kính, trầm mặc, là chốn tâm linh quen thuộc của người dân địa phương. Vào các dịp lễ, đặc biệt là ngày giỗ Đức Thánh Trần (20 tháng Tám âm lịch) và các ngày lễ thờ Mẫu, đền thu hút đông đảo người dân và du khách đến dâng hương, cầu tài lộc, bình an, tham dự các nghi lễ và hoạt động tín ngưỡng truyền thống. Đền Hồng Sơn đã được xếp hạng di tích lịch sử – văn hóa quốc gia, là điểm đến tâm linh và văn hóa đáng chú ý khi tham quan thành phố Vinh.",
    "Hong Son Temple stands in Hong Son ward, in the central area of Vinh City near Vinh Market. It is a large ancient temple built in the Nguyen era, originally a Military Shrine honouring famous generals and later dedicated chiefly to Hung Dao Dai Vuong Tran Quoc Tuan, the national hero who thrice defeated the Yuan-Mongol armies, along with other deities and saints such as the Holy Mother and figures of the Mother Goddess tradition. The temple follows traditional architecture with a system of gates, courtyards and worship halls harmoniously arranged, notable for the fine wood carving on its columns, beams, lacquered boards and parallel sentences, and many valuable objects and old ritual items. Amid the bustling city, Hong Son Temple keeps its ancient, contemplative character and is a familiar spiritual site for locals. On festival days, especially the memorial day of Saint Tran (the 20th of the eighth lunar month) and Mother Goddess ceremonies, the temple draws crowds of residents and visitors who come to offer incense, pray for prosperity and peace and take part in traditional rites. Recognised as a national historical and cultural relic, Hong Son Temple is a notable spiritual and cultural destination when touring Vinh City.",
    "Храм Хонгшон стоит в квартале Хонгшон, в центральной части города Винь рядом с рынком Виня. Это большой древний храм, построенный в эпоху Нгуен, изначально военное святилище в честь прославленных полководцев, а позднее посвящённый главным образом Хынг Дао Дай Выонгу Чан Куок Туану — национальному герою, трижды разгромившему юаньско-монгольские армии, — а также другим божествам и святым, таким как Святая Мать и фигуры традиции культа Богини-Матери. Храм выдержан в традиционной архитектуре с системой ворот, дворов и молитвенных залов, гармонично расположенных, и примечателен тонкой резьбой по дереву на колоннах, балках, лаковых досках и парных изречениях, а также множеством ценных предметов и старинной ритуальной утвари. Среди оживлённого города храм Хонгшон сохраняет древний, созерцательный характер и остаётся привычным духовным местом для местных жителей. В праздничные дни, особенно в день памяти Святого Чана (20-е число восьмого лунного месяца) и на церемонии культа Богини-Матери, храм собирает толпы жителей и гостей, приходящих воскурить благовония, молиться о достатке и мире и участвовать в традиционных обрядах. Признанный национальным историко-культурным памятником, храм Хонгшон — заметное духовное и культурное место при осмотре города Винь.",
    ["Đền cổ trung tâm Vinh thờ Hưng Đạo Vương Trần Quốc Tuấn và các vị thần",
     "Kiến trúc truyền thống, chạm khắc gỗ tinh xảo; di tích quốc gia",
     "Đông khách dịp giỗ Đức Thánh Trần và lễ thờ Mẫu"],
    ["An ancient central-Vinh temple to Tran Quoc Tuan and various deities",
     "Traditional architecture with fine wood carving; a national relic",
     "Busy on Saint Tran's memorial day and Mother Goddess ceremonies"],
    ["Древний храм в центре Виня в честь Чан Куок Туана и разных божеств",
     "Традиционная архитектура с тонкой резьбой; национальный памятник",
     "Многолюден в день памяти Святого Чана и на церемониях культа Матери"],
    {"hours_vi": "Khoảng 6:00–18:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 30–45 phút.",
     "best_time_vi": "Dịp giỗ Đức Thánh Trần (20/8 âm lịch), lễ thờ Mẫu, đầu xuân.",
     "tips_vi": "Ăn mặc lịch sự; cẩn thận tư trang khi đông; kết hợp dạo chợ Vinh gần đó."},
    ["spiritual", "temple", "history", "culture", "indoor"],
    [{"title": "Wikipedia (VI) — Đền Hồng Sơn", "url": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%81n_H%E1%BB%93ng_S%C6%A1n"}]),

rec("cho-vinh",
    "Chợ Vinh",
    "Vinh Market",
    "Рынок Винь",
    ["square_street", "other"],
    18.6740, 105.6870,
    "Phường Hồng Sơn, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.2, "count": 2000, "source": "Google", "as_of": "2026-07"},
    "Khu chợ trung tâm lớn nhất Vinh, bán đủ hàng hóa, đặc sản xứ Nghệ; nhộn nhịp, giá phải chăng. Nơi trải nghiệm đời sống địa phương, mua quà và ăn đặc sản.",
    "Chợ Vinh là khu chợ trung tâm lớn nhất và lâu đời của thành phố Vinh, đầu mối buôn bán sầm uất của cả vùng Nghệ An – Hà Tĩnh. Đây là nơi du khách có thể tìm mua đủ loại hàng hóa, đặc sản xứ Nghệ và trải nghiệm nhịp sống, văn hóa chợ búa địa phương.",
    "Vinh Market is the largest and long-established central market of Vinh City, a bustling trading hub for the whole Nghe An-Ha Tinh region. Here visitors can buy all kinds of goods and Nghe An specialities and experience the rhythm and culture of local market life.",
    "Рынок Винь — крупнейший и старейший центральный рынок города Винь, оживлённый торговый узел для всего края Нгеан-Хатинь. Здесь гости могут купить всевозможные товары и деликатесы Нгеана и ощутить ритм и культуру местной рыночной жизни.",
    "Chợ Vinh nằm ở phường Hồng Sơn, khu vực trung tâm thành phố Vinh, là một trong những khu chợ lớn và sầm uất bậc nhất khu vực Bắc Trung Bộ. Có lịch sử lâu đời, chợ Vinh từ xưa đã là đầu mối giao thương quan trọng, nơi tập trung buôn bán hàng hóa của cả vùng Nghệ An – Hà Tĩnh và các tỉnh lân cận. Chợ được xây dựng khang trang với nhiều tầng và khu vực bán hàng phân theo ngành hàng: từ quần áo, vải vóc, giày dép, đồ gia dụng, điện tử đến thực phẩm tươi sống, hàng khô, gia vị và đặc biệt là các loại đặc sản xứ Nghệ. Đến chợ Vinh, du khách có thể tìm mua nhiều món quà và đặc sản nổi tiếng như cam Vinh, tương Nam Đàn, nhút Thanh Chương, bánh đa Đô Lương, cá thu, mực khô, các loại hải sản, cùng nhiều món ăn vặt hấp dẫn của địa phương. Không khí chợ nhộn nhịp, tấp nập kẻ mua người bán, phản ánh sinh động đời sống thường nhật và văn hóa buôn bán của người dân xứ Nghệ. Với du khách phương xa, chợ Vinh không chỉ là nơi mua sắm mà còn là điểm trải nghiệm văn hóa, ẩm thực địa phương thú vị, nơi có thể cảm nhận rõ nét nhất hơi thở cuộc sống của thành phố bên bờ sông Lam.",
    "Vinh Market lies in Hong Son ward, in the central area of Vinh City, and is one of the largest and busiest markets in north-central Vietnam. With a long history, it has long been an important trading hub gathering the goods of the whole Nghe An-Ha Tinh region and neighbouring provinces. The market is well built, with several floors and areas divided by trade: from clothes, fabrics, footwear, household goods and electronics to fresh food, dry goods, spices and, above all, Nghe An specialities. At Vinh Market, visitors can buy many famous gifts and specialities such as Vinh oranges, Nam Dan soybean sauce, Thanh Chuong nhut (salted jackfruit), Do Luong rice crackers, mackerel, dried squid, various seafood and many tempting local snacks. The market is lively and crowded with buyers and sellers, vividly reflecting the daily life and trading culture of the people of Nghe An. For travellers from afar, Vinh Market is not only a place to shop but also an interesting spot to experience local culture and cuisine, where one can most clearly feel the breath of life in this city by the Lam River.",
    "Рынок Винь находится в квартале Хонгшон, в центральной части города Винь, и является одним из крупнейших и оживлённейших рынков северо-центрального Вьетнама. С долгой историей он давно служит важным торговым узлом, собирающим товары всего края Нгеан-Хатинь и соседних провинций. Рынок хорошо построен, с несколькими этажами и зонами по видам торговли: от одежды, тканей, обуви, хозтоваров и электроники до свежих продуктов, сухих товаров, специй и прежде всего деликатесов Нгеана. На рынке Винь гости могут купить множество знаменитых подарков и деликатесов — апельсины Виня, соевый соус Намдан, нют Тханьтьыонга (солёное джекфрутовое блюдо), рисовые лепёшки Долыонга, скумбрию, сушёный кальмар, разные морепродукты и множество заманчивых местных закусок. Рынок оживлён и полон покупателей и продавцов, ярко отражая повседневную жизнь и торговую культуру жителей Нгеана. Для путешественников издалека рынок Винь — не только место покупок, но и интересная точка знакомства с местной культурой и кухней, где яснее всего ощущается дыхание жизни города у реки Лам.",
    ["Chợ trung tâm lớn nhất, lâu đời của TP. Vinh và vùng Bắc Trung Bộ",
     "Mua đặc sản xứ Nghệ: cam Vinh, tương Nam Đàn, nhút, bánh đa, hải sản khô",
     "Trải nghiệm đời sống, ẩm thực và văn hóa chợ địa phương"],
    ["The largest, long-established central market of Vinh and north-central Vietnam",
     "Buy Nghe An specialities: Vinh oranges, Nam Dan sauce, nhut, rice crackers, dried seafood",
     "Experience local life, food and market culture"],
    ["Крупнейший, старейший центральный рынок Виня и северо-центрального Вьетнама",
     "Деликатесы Нгеана: апельсины Виня, соус Намдан, нют, лепёшки, сушёные морепродукты",
     "Знакомство с местной жизнью, едой и рыночной культурой"],
    {"hours_vi": "Khoảng 6:00–18:00 (một số khu bán sớm/muộn hơn).",
     "ticket_vi": "Miễn phí vào chợ.",
     "duration_vi": "Khoảng 45–90 phút.",
     "best_time_vi": "Buổi sáng đông vui, hàng tươi ngon nhất.",
     "tips_vi": "Nên hỏi giá và mặc cả; giữ tư trang cẩn thận; thử đặc sản và mua quà."},
    ["market", "food", "shopping", "culture", "indoor", "family"],
    [{"title": "Wikipedia (VI) — Chợ Vinh", "url": "https://vi.wikipedia.org/wiki/Ch%E1%BB%A3_Vinh"}]),

rec("thac-sao-va",
    "Thác Sao Va",
    "Sao Va Waterfall",
    "Водопад Шаова",
    ["park_garden", "other"],
    19.5800, 104.9000,
    "Xã Đồng Văn, huyện Quế Phong, tỉnh Nghệ An",
    {"value": 4.4, "count": 500, "source": "Google", "as_of": "2026-07"},
    "Thác nước đẹp giữa rừng miền Tây Nghệ An, nước trong xanh, mát lạnh; hợp tắm thác, dã ngoại. Đường xa nhưng cảnh hoang sơ, yên tĩnh, ít khách.",
    "Thác Sao Va là thác nước đẹp ở huyện miền núi Quế Phong, phía tây bắc Nghệ An, cao khoảng 20–24 m, nước đổ xuống hồ tự nhiên trong xanh giữa rừng. Đây là điểm du lịch sinh thái hoang sơ, mát lành, gắn với văn hóa đồng bào Thái vùng cao.",
    "Sao Va Waterfall is a beautiful fall in the mountainous Que Phong district of north-western Nghe An, about 20-24 metres high, its water dropping into a clear natural pool amid the forest. It is a wild, refreshing eco-tourism spot linked to the culture of the upland Thai people.",
    "Водопад Шаова — красивый водопад в горном уезде Куэфонг на северо-западе Нгеана, высотой около 20-24 метров; его вода падает в прозрачную природную заводь среди леса. Это дикое, освежающее место экотуризма, связанное с культурой горного народа тхай.",
    "Thác Sao Va nằm ở xã Đồng Văn, huyện Quế Phong, vùng núi phía tây bắc tỉnh Nghệ An, cách thành phố Vinh khoảng 170 km. Thác có độ cao khoảng 20–24 m, dòng nước từ trên cao đổ xuống một hồ nước tự nhiên trong xanh, được bao quanh bởi rừng cây rậm rạp, vách đá và thảm thực vật phong phú, tạo nên khung cảnh hoang sơ, thơ mộng. Theo tiếng địa phương, 'Sao Va' có nghĩa liên quan đến hình ảnh dòng thác như con hươu, con nai; cũng có cách giải thích gắn với vẻ đẹp huyền ảo của thác. Nước thác quanh năm mát lạnh, trong vắt, dưới chân thác là hồ nước sâu vừa phải, khá an toàn để tắm mát, bơi lội và vui chơi. Xung quanh thác là không gian núi rừng yên tĩnh, không khí trong lành, thích hợp cho các hoạt động dã ngoại, cắm trại, khám phá thiên nhiên. Khu vực Quế Phong còn là nơi sinh sống của đồng bào các dân tộc Thái, Thổ, Khơ Mú với nhiều nét văn hóa, ẩm thực đặc sắc, nên chuyến đi tới thác Sao Va thường được kết hợp trải nghiệm bản làng, thưởng thức đặc sản vùng cao. Dù đường đi khá xa và còn nhiều đoạn quanh co, nhưng vẻ đẹp nguyên sơ, thanh bình của thác Sao Va là phần thưởng xứng đáng cho những ai yêu thích du lịch sinh thái, ưa khám phá miền Tây xứ Nghệ.",
    "Sao Va Waterfall lies in Dong Van commune, Que Phong district, in the north-western mountains of Nghe An, about 170 km from Vinh City. The fall is around 20-24 metres high, its water dropping from above into a clear natural pool surrounded by dense forest, cliffs and rich vegetation, creating a wild, poetic scene. In the local tongue, 'Sao Va' relates to the image of the fall as a deer or roe, while some explanations tie it to the fall's magical beauty. The water is cool and crystal-clear year-round, and the pool at its foot is moderately deep and fairly safe for bathing, swimming and play. Around the fall lies quiet mountain forest with fresh air, ideal for picnics, camping and nature exploration. The Que Phong area is also home to the Thai, Tho and Kho Mu peoples, with distinctive culture and cuisine, so a trip to Sao Va is often combined with visiting villages and tasting upland specialities. Although the road is quite long and winding, the pristine, peaceful beauty of Sao Va Waterfall is a fitting reward for those who love eco-tourism and exploring western Nghe An.",
    "Водопад Шаова находится в общине Донгван уезда Куэфонг, в северо-западных горах Нгеана, примерно в 170 км от города Винь. Высота водопада около 20-24 метров; вода падает сверху в прозрачную природную заводь, окружённую густым лесом, скалами и богатой растительностью, создавая дикую, поэтичную картину. На местном языке «Шаова» связано с образом водопада как оленя или косули, а некоторые объяснения соотносят его с волшебной красотой водопада. Вода прохладна и кристально чиста круглый год, а заводь у подножия умеренно глубока и достаточно безопасна для купания, плавания и игр. Вокруг водопада — тихий горный лес со свежим воздухом, идеальный для пикников, кемпинга и изучения природы. Район Куэфонг также населяют народы тхай, тхо и кхому с самобытной культурой и кухней, поэтому поездку к Шаове часто сочетают с посещением деревень и дегустацией горных деликатесов. Хотя дорога довольно длинна и извилиста, первозданная, мирная красота водопада Шаова — достойная награда для любителей экотуризма и исследования западного Нгеана.",
    ["Thác cao ~20–24 m đổ xuống hồ tự nhiên trong xanh giữa rừng",
     "Điểm du lịch sinh thái hoang sơ ở vùng cao Quế Phong",
     "Kết hợp trải nghiệm bản làng Thái, Thổ, Khơ Mú và đặc sản vùng cao"],
    ["A ~20-24 m fall dropping into a clear natural pool amid the forest",
     "A wild eco-tourism spot in upland Que Phong",
     "Combine with Thai, Tho and Kho Mu villages and upland specialities"],
    ["Водопад ~20-24 м, падающий в прозрачную заводь среди леса",
     "Дикое место экотуризма в горном Куэфонге",
     "Сочетается с деревнями тхай, тхо, кхому и горными деликатесами"],
    {"hours_vi": "Ban ngày.",
     "ticket_vi": "Miễn phí hoặc phí thấp.",
     "duration_vi": "Khoảng 1,5–2 giờ (chưa kể di chuyển xa).",
     "best_time_vi": "Mùa hè để tắm mát; sau mưa thác nhiều nước (chú ý an toàn).",
     "tips_vi": "Đường xa, nên đi xe khỏe, khởi hành sớm; mang đồ bơi, đồ ăn; hỏi người dân về mực nước."},
    ["nature", "waterfall", "ecotourism", "outdoor", "family", "daytrip"],
    [{"title": "Wikipedia (VI) — Quế Phong", "url": "https://vi.wikipedia.org/wiki/Qu%E1%BA%BF_Phong"}]),

rec("muong-long",
    "Mường Lống (Kỳ Sơn)",
    "Muong Long (Ky Son)",
    "Мыонглонг (Кишон)",
    ["park_garden", "other"],
    19.3600, 104.1900,
    "Xã Mường Lống, huyện Kỳ Sơn, tỉnh Nghệ An",
    {"value": 4.5, "count": 700, "source": "Google", "as_of": "2026-07"},
    "Thung lũng vùng cao mát mẻ quanh năm, được ví như 'Sa Pa xứ Nghệ'; mây mù, ruộng bậc thang, bản Mông. Cảnh đẹp hoang sơ, hợp trekking, săn mây, khám phá văn hóa.",
    "Mường Lống là một xã vùng cao ở huyện biên giới Kỳ Sơn, nằm trên độ cao gần 1.500 m giữa dãy Trường Sơn, được ví như 'Sa Pa của xứ Nghệ'. Nơi đây có khí hậu mát mẻ quanh năm, mây mù bao phủ, bản làng người Mông và cảnh sắc núi rừng hoang sơ, hùng vĩ.",
    "Muong Long is an upland commune in the border district of Ky Son, at nearly 1,500 metres in the Truong Son range, likened to the 'Sa Pa of Nghe An'. It has a cool climate year-round, drifting mist, Hmong villages and wild, majestic mountain scenery.",
    "Мыонглонг — горная община в приграничном уезде Кишон, на высоте почти 1500 метров в хребте Чыонгшон, которую сравнивают с «Сапой Нгеана». Здесь прохладный климат круглый год, плывущий туман, деревни хмонгов и дикие, величественные горные пейзажи.",
    "Mường Lống là một xã vùng cao thuộc huyện Kỳ Sơn – huyện biên giới cực tây của tỉnh Nghệ An, giáp với nước bạn Lào. Nằm trong một thung lũng trên độ cao trung bình khoảng 1.400–1.500 m so với mực nước biển, giữa những dãy núi cao của Trường Sơn, Mường Lống có khí hậu mát mẻ, se lạnh quanh năm, thường xuyên chìm trong mây mù, nên được nhiều người ví như 'Sa Pa' hay 'cổng trời' của xứ Nghệ. Cảnh quan nơi đây mang vẻ đẹp hoang sơ, hùng vĩ với núi non trùng điệp, những thửa ruộng bậc thang, vườn mận, đào và các bản làng của đồng bào dân tộc Mông sinh sống lâu đời. Đến Mường Lống, du khách có thể trải nghiệm không khí trong lành, săn mây trên các đỉnh núi, ngắm bình minh và hoàng hôn tuyệt đẹp, khám phá đời sống, trang phục, ẩm thực và các phong tục độc đáo của người Mông. Vào mùa xuân, hoa mận, hoa đào nở trắng hồng khắp các sườn đồi tạo nên khung cảnh nên thơ; mùa lúa chín, ruộng bậc thang lại nhuộm vàng thung lũng. Dù đường lên Mường Lống khá xa và quanh co, hiểm trở, nhưng vẻ đẹp nguyên sơ cùng bản sắc văn hóa vùng cao khiến nơi đây ngày càng hấp dẫn du khách ưa khám phá, đặc biệt là giới trẻ đam mê 'phượt' và du lịch trải nghiệm ở miền Tây Nghệ An.",
    "Muong Long is an upland commune in Ky Son, the far-western border district of Nghe An bordering Laos. Set in a valley at an average altitude of about 1,400-1,500 metres among the high mountains of the Truong Son range, Muong Long has a cool, chilly climate year-round and is often shrouded in mist, so many liken it to the 'Sa Pa' or 'heaven's gate' of Nghe An. Its scenery is wild and majestic, with layered mountains, terraced fields, plum and peach gardens, and long-settled villages of the Hmong people. In Muong Long, visitors can enjoy fresh air, chase clouds on the peaks, watch beautiful sunrises and sunsets, and explore the life, dress, cuisine and unique customs of the Hmong. In spring, plum and peach blossoms bloom white and pink across the slopes for a poetic scene; in the ripe-rice season, the terraces turn the valley golden. Although the road up is quite long, winding and rugged, the pristine beauty and upland cultural identity make it increasingly appealing to explorers, especially young backpackers and experiential travellers in western Nghe An.",
    "Мыонглонг — горная община в Кишоне, крайнем западном приграничном уезде Нгеана, граничащем с Лаосом. Расположенная в долине на средней высоте около 1400-1500 метров среди высоких гор хребта Чыонгшон, Мыонглонг имеет прохладный, зябкий климат круглый год и часто окутана туманом, поэтому многие сравнивают её с «Сапой» или «небесными вратами» Нгеана. Её пейзажи дики и величественны: гряды гор, террасные поля, сливовые и персиковые сады и издавна обжитые деревни народа хмонг. В Мыонглонге гости могут наслаждаться свежим воздухом, ловить облака на вершинах, встречать красивые восходы и закаты и знакомиться с жизнью, одеждой, кухней и самобытными обычаями хмонгов. Весной сливовый и персиковый цвет распускается белым и розовым по склонам, создавая поэтичную картину; в сезон спелого риса террасы золотят долину. Хотя дорога наверх довольно длинна, извилиста и труднопроходима, первозданная красота и горная культурная самобытность делают это место всё более привлекательным для исследователей, особенно молодых бэкпекеров и любителей опытного туризма на западе Нгеана.",
    ["Thung lũng vùng cao ~1.500 m, 'Sa Pa của xứ Nghệ', mát mẻ quanh năm",
     "Săn mây, ruộng bậc thang, vườn mận đào, bản người Mông",
     "Mùa xuân hoa mận, hoa đào nở; mùa lúa chín ruộng bậc thang vàng"],
    ["An upland valley at ~1,500 m, the 'Sa Pa of Nghe An', cool year-round",
     "Cloud-hunting, terraced fields, plum and peach gardens, Hmong villages",
     "Plum and peach blossoms in spring; golden terraces at harvest"],
    ["Горная долина ~1500 м, «Сапа Нгеана», прохладная круглый год",
     "Охота за облаками, террасы, сливовые и персиковые сады, деревни хмонгов",
     "Весной цветение сливы и персика; золотые террасы в жатву"],
    {"hours_vi": "Cả ngày (điểm đến vùng cao); nên lưu trú qua đêm.",
     "ticket_vi": "Miễn phí (chi phí lưu trú, dịch vụ homestay).",
     "duration_vi": "Nên đi 2 ngày 1 đêm.",
     "best_time_vi": "Mùa hoa mận đào (khoảng tháng 1–2) và mùa lúa chín; sáng sớm săn mây.",
     "tips_vi": "Đường xa, đèo dốc, đi xe khỏe và lái vững; mang áo ấm; đặt homestay bản Mông trước; tôn trọng phong tục địa phương."},
    ["nature", "mountain", "viewpoint", "ethnic", "trekking", "outdoor", "top"],
    [{"title": "Wikipedia (VI) — Mường Lống", "url": "https://vi.wikipedia.org/wiki/M%C6%B0%E1%BB%9Dng_L%E1%BB%91ng"}]),

rec("rung-sang-le-tuong-duong",
    "Rừng săng lẻ Tương Dương",
    "Sang Le (Crape-myrtle) Forest, Tuong Duong",
    "Лес санглэ (лагерстрёмии), Тыонгзыонг",
    ["park_garden", "other"],
    19.1900, 104.6400,
    "Xã Tam Đình, huyện Tương Dương, tỉnh Nghệ An",
    {"value": 4.4, "count": 400, "source": "Google", "as_of": "2026-07"},
    "Rừng săng lẻ cổ thụ thẳng tắp bên Quốc lộ 7, cao vút, xanh mát; khung cảnh nên thơ, độc đáo. Điểm dừng chân chụp ảnh, nghỉ mát khi đi miền Tây Nghệ An.",
    "Rừng săng lẻ Tương Dương là khu rừng cây săng lẻ (bằng lăng rừng) cổ thụ hàng trăm năm tuổi, thân cao thẳng tắp bên Quốc lộ 7, thuộc huyện Tương Dương. Rừng cây độc đáo, xanh mát, tạo khung cảnh nên thơ và là điểm dừng chân quen thuộc trên hành trình lên miền Tây xứ Nghệ.",
    "The Sang Le Forest in Tuong Duong is a stand of centuries-old crape-myrtle (sang le) trees, tall and straight, beside National Highway 7 in Tuong Duong district. This unusual, cool green forest forms a poetic scene and a familiar stop on the way into western Nghe An.",
    "Лес санглэ в Тыонгзыонге — роща вековых деревьев лагерстрёмии (санглэ), высоких и прямых, у национального шоссе 7 в уезде Тыонгзыонг. Этот необычный прохладный зелёный лес образует поэтичную картину и привычную остановку на пути в западный Нгеан.",
    "Rừng săng lẻ Tương Dương nằm ở xã Tam Đình, huyện Tương Dương, ngay bên Quốc lộ 7 – tuyến đường huyết mạch lên các huyện miền Tây Nghệ An và sang cửa khẩu Nậm Cắn (Lào), cách thành phố Vinh khoảng 150 km. Đây là một khu rừng đặc biệt với quần thể cây săng lẻ (còn gọi là bằng lăng rừng) cổ thụ, nhiều cây đã hàng trăm năm tuổi, thân cao thẳng tắp, vươn lên tới vài chục mét, tán lá xanh mát rợp bóng cả một vùng. Điều đặc biệt là rừng gần như thuần loài săng lẻ, tạo nên cảnh quan hiếm có với những hàng cây cao vút, thẳng đứng như những cột chống trời, ánh nắng xuyên qua kẽ lá tạo khung cảnh huyền ảo, nên thơ. Vào mùa săng lẻ ra hoa (khoảng cuối hè), rừng điểm xuyết sắc tím hồng của hoa bằng lăng rừng càng thêm quyến rũ; mùa cây thay lá, rừng lại khoác lên vẻ đẹp khác lạ. Nhờ vẻ đẹp độc đáo và vị trí thuận tiện ngay ven đường, rừng săng lẻ trở thành điểm dừng chân lý tưởng để du khách nghỉ ngơi, tránh nắng, hít thở không khí trong lành và chụp ảnh trên hành trình khám phá miền Tây Nghệ An. Khu rừng cũng gắn với đời sống của đồng bào Thái địa phương và được gìn giữ như một 'báu vật xanh' của huyện Tương Dương.",
    "The Sang Le Forest in Tuong Duong lies in Tam Dinh commune, Tuong Duong district, right beside National Highway 7, the key route into the western districts of Nghe An and on to the Nam Can border gate with Laos, about 150 km from Vinh City. It is a special forest with a stand of ancient sang le (forest crape-myrtle) trees, many centuries old, their trunks tall and straight, rising tens of metres, their cool green canopy shading a whole area. Remarkably, the forest is almost purely sang le, creating a rare landscape of soaring, upright trees like pillars propping up the sky, with sunlight filtering through the leaves for a magical, poetic effect. When the sang le blooms (around late summer), the forest is touched with the pink-purple of forest crape-myrtle flowers, all the more enchanting; when the trees change their leaves, the forest takes on another kind of beauty. Thanks to its unique beauty and convenient roadside location, the Sang Le Forest has become an ideal stop for visitors to rest, escape the sun, breathe fresh air and take photos while exploring western Nghe An. The forest is also bound to the life of the local Thai people and is preserved as a 'green treasure' of Tuong Duong district.",
    "Лес санглэ в Тыонгзыонге находится в общине Тамдинь уезда Тыонгзыонг, прямо у национального шоссе 7 — ключевой дороги в западные уезды Нгеана и далее к пограничному переходу Намкан с Лаосом, примерно в 150 км от города Винь. Это особый лес с рощей вековых деревьев санглэ (лесная лагерстрёмия), многим из которых сотни лет; их стволы высоки и прямы, поднимаются на десятки метров, а прохладный зелёный полог затеняет целую местность. Примечательно, что лес почти чисто санглэ, что создаёт редкий пейзаж из взмывающих ввысь прямых деревьев, словно колонн, подпирающих небо, где солнечный свет, пробиваясь сквозь листья, даёт волшебный, поэтичный эффект. Когда санглэ цветёт (примерно в конце лета), лес трогает розово-фиолетовый цвет лесной лагерстрёмии, ещё более чарующий; когда деревья меняют листву, лес обретает иную красоту. Благодаря уникальной красоте и удобному расположению у дороги лес санглэ стал идеальной остановкой, где гости могут отдохнуть, укрыться от солнца, подышать свежим воздухом и фотографировать во время путешествия по западному Нгеану. Лес также связан с жизнью местного народа тхай и сохраняется как «зелёное сокровище» уезда Тыонгзыонг.",
    ["Rừng săng lẻ cổ thụ thuần loài, cao thẳng tắp bên Quốc lộ 7",
     "Cảnh quan hiếm có, nên thơ; mùa hoa điểm sắc tím hồng",
     "Điểm dừng chân nghỉ mát, chụp ảnh khi đi miền Tây Nghệ An"],
    ["A pure stand of tall, straight ancient crape-myrtle by Highway 7",
     "A rare, poetic landscape; touched with pink-purple flowers in bloom",
     "A rest and photo stop on the way into western Nghe An"],
    ["Чистая роща высоких прямых вековых лагерстрёмий у шоссе 7",
     "Редкий, поэтичный пейзаж; в цвету — розово-фиолетовые оттенки",
     "Остановка для отдыха и фото по пути в западный Нгеан"],
    {"hours_vi": "Cả ngày (ven Quốc lộ 7).",
     "ticket_vi": "Miễn phí.",
     "duration_vi": "Khoảng 20–40 phút.",
     "best_time_vi": "Mùa hoa săng lẻ cuối hè; ban ngày nắng xuyên kẽ lá đẹp.",
     "tips_vi": "Dừng xe nơi an toàn ven đường; kết hợp hành trình lên Mường Lống, cửa khẩu Nậm Cắn."},
    ["nature", "forest", "viewpoint", "outdoor", "daytrip"],
    [{"title": "Wikipedia (VI) — Tương Dương", "url": "https://vi.wikipedia.org/wiki/T%C6%B0%C6%A1ng_D%C6%B0%C6%A1ng"}]),

rec("km0-duong-ho-chi-minh",
    "Cột mốc Km số 0 đường Hồ Chí Minh (Tân Kỳ)",
    "Kilometre Zero of the Ho Chi Minh Trail (Tan Ky)",
    "Нулевой километр тропы Хо Ши Мина (Танки)",
    ["monument", "other"],
    19.0350, 105.2050,
    "Thị trấn Tân Kỳ, huyện Tân Kỳ, tỉnh Nghệ An",
    {"value": 4.5, "count": 500, "source": "Google", "as_of": "2026-07"},
    "Cột mốc khởi đầu 'đường Trường Sơn' huyền thoại; di tích lịch sử ý nghĩa. Không gian trang trọng, hợp tìm hiểu lịch sử kháng chiến; nhiều đoàn về nguồn ghé thăm.",
    "Cột mốc Km số 0 ở thị trấn Tân Kỳ là điểm khởi đầu của đường Trường Sơn – đường Hồ Chí Minh huyền thoại, tuyến chi viện chiến lược cho miền Nam trong kháng chiến chống Mỹ. Đây là di tích lịch sử quốc gia, biểu tượng của con đường huyền thoại thời chiến.",
    "Kilometre Zero in Tan Ky town marks the starting point of the Truong Son Road, the legendary Ho Chi Minh Trail that supplied the South during the war against America. It is a national historical relic and a symbol of that legendary wartime route.",
    "Нулевой километр в посёлке Танки отмечает начало Дороги Чыонгшон — легендарной тропы Хо Ши Мина, снабжавшей Юг во время войны против США. Это национальный исторический памятник и символ той легендарной военной дороги.",
    "Cột mốc Km số 0 nằm ở thị trấn Tân Kỳ, huyện Tân Kỳ, được xác định là điểm khởi đầu (cây số 0) của tuyến đường Trường Sơn – đường Hồ Chí Minh lịch sử. Trong cuộc kháng chiến chống Mỹ cứu nước, đây là nơi bắt đầu của tuyến đường vận tải chiến lược huyền thoại, kéo dài hàng nghìn ki-lô-mét xuyên dãy Trường Sơn, qua cả đất Lào và Campuchia, làm nhiệm vụ chi viện sức người, sức của từ hậu phương miền Bắc cho tiền tuyến miền Nam. Con đường này gắn liền với biết bao gian khổ, hy sinh của bộ đội, thanh niên xung phong, dân công hỏa tuyến và trở thành biểu tượng bất khuất của ý chí thống nhất đất nước. Để ghi dấu ý nghĩa lịch sử ấy, cột mốc Km số 0 đã được dựng lên tại Tân Kỳ và khu vực này được xếp hạng di tích lịch sử quốc gia. Ngày nay, nơi đây có cột mốc, tượng đài và khuôn viên được xây dựng khang trang, trang nghiêm. Du khách, cựu chiến binh và các đoàn học sinh, sinh viên thường tìm đến để tham quan, chụp ảnh lưu niệm bên cột mốc, dâng hương tưởng nhớ và ôn lại một trang sử hào hùng của dân tộc. Cột mốc Km số 0 không chỉ là điểm đến lịch sử mà còn là nơi giáo dục truyền thống cách mạng, khơi dậy lòng tự hào và biết ơn đối với các thế hệ cha anh.",
    "Kilometre Zero stands in Tan Ky town, Tan Ky district, marked as the starting point (kilometre zero) of the historic Truong Son Road, the Ho Chi Minh Trail. During the war of resistance against America, this was the beginning of the legendary strategic transport route that ran thousands of kilometres through the Truong Son range and across Laos and Cambodia, carrying manpower and supplies from the northern rear to the southern front. The road is bound up with the hardship and sacrifice of soldiers, youth volunteers and frontline labourers and became an indomitable symbol of the will to reunify the country. To mark this historical significance, the Kilometre Zero marker was erected in Tan Ky and the area was ranked a national historical relic. Today it has a marker, a monument and a dignified, well-built compound. Visitors, veterans and school and student groups often come to sightsee, take souvenir photos by the marker, offer incense in remembrance and revisit a heroic chapter of the nation's history. Kilometre Zero is not only a historical destination but also a place of revolutionary education that awakens pride and gratitude toward earlier generations.",
    "Нулевой километр стоит в посёлке Танки уезда Танки и обозначен как начальная точка (нулевой километр) исторической Дороги Чыонгшон — тропы Хо Ши Мина. Во время войны сопротивления против США это было начало легендарного стратегического транспортного маршрута, тянувшегося на тысячи километров через хребет Чыонгшон и по территории Лаоса и Камбоджи, доставлявшего людей и грузы из северного тыла на южный фронт. Дорога связана с лишениями и жертвами солдат, молодых добровольцев и фронтовых рабочих и стала несокрушимым символом воли к объединению страны. Чтобы отметить это историческое значение, в Танки был установлен знак нулевого километра, а район получил статус национального исторического памятника. Сегодня здесь есть знак, монумент и благоустроенный, торжественный комплекс. Гости, ветераны и школьные и студенческие группы часто приезжают осмотреть, сфотографироваться на память у знака, воскурить благовония в память и вновь пережить героическую страницу истории народа. Нулевой километр — не только историческое место, но и точка революционного воспитания, пробуждающая гордость и благодарность к прежним поколениям.",
    ["Điểm khởi đầu (Km0) của đường Trường Sơn – đường Hồ Chí Minh huyền thoại",
     "Tuyến chi viện chiến lược cho miền Nam thời chống Mỹ",
     "Di tích lịch sử quốc gia; có cột mốc, tượng đài để tưởng niệm"],
    ["The starting point (Km0) of the legendary Truong Son / Ho Chi Minh Trail",
     "A strategic supply route to the South in the war against America",
     "A national relic with a marker and monument for remembrance"],
    ["Начальная точка (Км0) легендарной Дороги Чыонгшон / тропы Хо Ши Мина",
     "Стратегический маршрут снабжения Юга во время войны с США",
     "Национальный памятник со знаком и монументом для памяти"],
    {"hours_vi": "Ban ngày.",
     "ticket_vi": "Miễn phí.",
     "duration_vi": "Khoảng 30–45 phút.",
     "best_time_vi": "Quanh năm; dịp lễ 30/4, 27/7, 19/5 nhiều đoàn về nguồn.",
     "tips_vi": "Giữ trang nghiêm; nên nghe thuyết minh; kết hợp khám phá vùng Tân Kỳ."},
    ["history", "monument", "memorial", "culture", "outdoor"],
    [{"title": "Wikipedia (VI) — Đường Trường Sơn", "url": "https://vi.wikipedia.org/wiki/%C4%90%C6%B0%E1%BB%9Dng_Tr%C6%B0%E1%BB%9Dng_S%C6%A1n"}]),

]

d = json.load(open(F, encoding="utf-8")) if os.path.exists(F) else []
have = {p["slug"] for p in d}
added = [p for p in new if p["slug"] not in have]
d += added
json.dump(d, open(F, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("batch3 them:", len(added), "| gio co:", len(d))
