# -*- coding: utf-8 -*-
"""Bổ sung địa điểm du lịch nổi tiếng tỉnh Nghệ An (đơn vị hành chính MỚI, giữ nguyên sau sáp nhập 2025).
Chèn an toàn: nạp -> append (bỏ qua slug đã có) -> ghi.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
F = os.path.join(ROOT, "data", "regions", "vn-nghe-an.json")

REG = "vn-nghe-an"
RN = "Nghệ An"
FD = "Miền Trung"
UPD = "2026-07-27"


def rec(slug, name_vi, name_en, name_ru, cats, lat, lon, addr,
        rating, review_vi, ps_vi, ps_en, ps_ru, pl_vi, pl_en, pl_ru,
        h_vi, h_en, h_ru, practical, tags, sources, photo=None):
    return {
        "id": f"{REG}-{slug}",
        "slug": slug,
        "region": REG,
        "country": "vietnam",
        "region_name_vi": RN,
        "federal_district": FD,
        "name_vi": name_vi,
        "name_ru": name_ru,
        "name_en": name_en,
        "categories": cats,
        "coordinates": {"lat": lat, "lon": lon},
        "address_vi": addr,
        "rating": rating,
        "review_summary_vi": review_vi,
        "presentation_short_vi": ps_vi,
        "presentation_short_en": ps_en,
        "presentation_short_ru": ps_ru,
        "presentation_long_vi": pl_vi,
        "presentation_long_en": pl_en,
        "presentation_long_ru": pl_ru,
        "highlights_vi": h_vi,
        "highlights_en": h_en,
        "highlights_ru": h_ru,
        "practical": practical,
        "photo": photo,
        "photo_credit": None,
        "official_site": None,
        "sources": sources,
        "tags": tags,
        "status": "enriched",
        "last_updated": UPD,
    }


new = [

rec("ho-chi-minh-square-vinh",
    "Quảng trường Hồ Chí Minh và Tượng đài Bác Hồ (TP. Vinh)",
    "Ho Chi Minh Square and Statue (Vinh City)",
    "Площадь Хо Ши Мина и памятник (город Винь)",
    ["square_street", "monument"],
    18.6699, 105.6819,
    "Đường Hồ Tùng Mậu, phường Trường Thi, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.7, "count": 9200, "source": "Google", "as_of": "2026-07"},
    "Không gian rộng rãi, thoáng đãng ngay trung tâm Vinh; tượng đài Bác uy nghi trên nền núi Chung mô phỏng. Buổi tối đông người dân dạo mát, chụp ảnh, trẻ em vui chơi.",
    "Quảng trường Hồ Chí Minh là trái tim của thành phố Vinh, nơi đặt tượng đài Chủ tịch Hồ Chí Minh cao 18 m bằng đồng, phía sau là mô hình núi Chung. Đây là điểm sinh hoạt cộng đồng, lễ hội và là biểu tượng của tình cảm người dân xứ Nghệ với Bác.",
    "Ho Chi Minh Square is the heart of Vinh City, home to an 18-metre bronze statue of President Ho Chi Minh set against a re-created Chung Mountain. It is the city's main civic and festival space and a symbol of the people of Nghe An's affection for their most famous son.",
    "Площадь Хо Ши Мина — сердце города Винь, где установлен 18-метровый бронзовый памятник президенту Хо Ши Мину на фоне воссозданной горы Тюнг. Это главное место городских праздников и символ любви жителей Нгеана к своему земляку.",
    "Nằm ở trung tâm thành phố Vinh, Quảng trường Hồ Chí Minh được khánh thành năm 2003 nhân kỷ niệm ngày sinh của Bác và nhanh chóng trở thành không gian công cộng lớn nhất, đẹp nhất xứ Nghệ. Điểm nhấn là tượng đài Chủ tịch Hồ Chí Minh đúc bằng đồng, cao 18 m (riêng phần tượng cao 12 m), đứng uy nghi trên bệ đá granit, tay phải giơ cao như đang vẫy chào đồng bào. Phía sau tượng là công trình mô phỏng núi Chung – ngọn núi gắn với tuổi thơ của Người ở làng Sen – được đắp bằng đá và trồng cây xanh, cây cảnh từ nhiều vùng miền gửi về. Quảng trường rộng khoảng 11 ha, lát đá sạch đẹp, có hệ thống đài phun nước, cột cờ, thảm cỏ và hàng cây rợp bóng. Đây là nơi diễn ra các sự kiện chính trị, văn hóa lớn của tỉnh, các buổi mít tinh, biểu diễn nghệ thuật và bắn pháo hoa dịp lễ. Vào buổi chiều tối, người dân Vinh đổ về đây đi bộ, tập thể dục, thả diều, còn trẻ nhỏ chơi xe điện, tạo nên khung cảnh sống động, thanh bình. Với du khách, quảng trường là điểm dừng chân dễ chịu để cảm nhận nhịp sống và tình cảm đặc biệt mà người xứ Nghệ dành cho Bác Hồ.",
    "Opened in 2003 to mark President Ho Chi Minh's birthday, Ho Chi Minh Square quickly became the largest and finest public space in Nghe An. Its centrepiece is an 18-metre bronze statue of Ho Chi Minh (the figure alone standing 12 metres) on a granite plinth, his right hand raised as if greeting the people. Behind it rises a re-creation of Chung Mountain, the hill linked to his childhood in Sen village, built of stone and planted with trees and ornamental plants sent from across the country. The square covers about 11 hectares, neatly paved and dotted with fountains, a flagpole, lawns and shady rows of trees. It hosts the province's major political and cultural events, rallies, performances and holiday fireworks. In the late afternoon and evening, Vinh residents flood in to stroll, exercise and fly kites while children ride electric cars, creating a lively yet peaceful scene. For visitors it is a pleasant stop to feel the rhythm of the city and the special affection the people of Nghe An hold for Uncle Ho.",
    "Открытая в 2003 году к дню рождения президента Хо Ши Мина, площадь быстро стала крупнейшим и красивейшим общественным пространством провинции Нгеан. Её центр — 18-метровый бронзовый памятник Хо Ши Мину (сама фигура высотой 12 метров) на гранитном постаменте; правая рука поднята, будто приветствуя народ. За памятником возвышается воссозданная гора Тюнг, связанная с его детством в деревне Сен, сложенная из камня и засаженная деревьями и растениями со всей страны. Площадь занимает около 11 гектаров, аккуратно вымощена, украшена фонтанами, флагштоком, газонами и тенистыми аллеями. Здесь проходят главные политические и культурные события провинции, митинги, концерты и праздничные фейерверки. Под вечер жители Виня приходят сюда гулять, заниматься спортом и запускать воздушных змеев, а дети катаются на электромобилях, создавая живую и вместе с тем мирную атмосферу. Для гостей это приятная остановка, где можно почувствовать ритм города и особую любовь жителей Нгеана к «дядюшке Хо».",
    ["Tượng đài Bác Hồ bằng đồng cao 18 m trên nền núi Chung mô phỏng",
     "Quảng trường rộng ~11 ha, trung tâm sinh hoạt của thành phố Vinh",
     "Khánh thành năm 2003; nơi tổ chức lễ hội, mít tinh, bắn pháo hoa"],
    ["An 18-metre bronze statue of Ho Chi Minh against a re-created Chung Mountain",
     "About 11 hectares — the civic heart of Vinh City",
     "Opened in 2003; venue for festivals, rallies and fireworks"],
    ["18-метровый бронзовый памятник Хо Ши Мину на фоне воссозданной горы Тюнг",
     "Около 11 гектаров — гражданское сердце города Винь",
     "Открыта в 2003 году; место праздников, митингов и фейерверков"],
    {"hours_vi": "Mở cửa cả ngày; đẹp nhất buổi tối.",
     "ticket_vi": "Miễn phí.",
     "duration_vi": "Khoảng 30–60 phút.",
     "best_time_vi": "Chiều tối mát mẻ, đông vui; dịp lễ có sự kiện, pháo hoa.",
     "tips_vi": "Kết hợp dạo phố Vinh, thăm thành cổ và bảo tàng gần đó; buổi tối có phố đi bộ."},
    ["monument", "square", "culture", "top", "outdoor", "family"],
    [{"title": "Wikipedia (VI) — Quảng trường Hồ Chí Minh (Vinh)", "url": "https://vi.wikipedia.org/wiki/Qu%E1%BA%A3ng_tr%C6%B0%E1%BB%9Dng_H%E1%BB%93_Ch%C3%AD_Minh_(Vinh)"}]),

rec("den-ong-hoang-muoi",
    "Đền Ông Hoàng Mười (Đền Mỏ Hạc)",
    "Ong Hoang Muoi Temple",
    "Храм Онг Хоанг Мыой",
    ["church", "monument"],
    18.6470, 105.6850,
    "Xã Hưng Thịnh (Làng Xuân Am), huyện Hưng Nguyên, tỉnh Nghệ An",
    {"value": 4.6, "count": 5400, "source": "Google", "as_of": "2026-07"},
    "Ngôi đền linh thiêng bậc nhất xứ Nghệ, đông khách hành hương cầu tài lộc, công danh. Không gian ven sông Lam yên bình, kiến trúc cổ kính; dịp lễ hội rất đông.",
    "Đền Ông Hoàng Mười ở huyện Hưng Nguyên là một trong những đền thờ nổi tiếng và linh thiêng nhất xứ Nghệ, gắn với tín ngưỡng thờ Mẫu và ông Hoàng Mười trong đạo Tứ Phủ. Du khách về đây cầu công danh, tài lộc, bình an, nhất là dịp cuối năm.",
    "Ong Hoang Muoi Temple in Hung Nguyen is one of the most famous and revered shrines in Nghe An, tied to the Mother Goddess religion and the deity Ong Hoang Muoi of the Four Palaces. Pilgrims come to pray for career success, prosperity and peace, especially at year's end.",
    "Храм Онг Хоанг Мыой в уезде Хынгнгуен — одно из самых известных и почитаемых святилищ провинции Нгеан, связанное с культом Богини-Матери и божеством Онг Хоанг Мыой в веровании «Четырёх дворцов». Паломники приходят молиться об успехе в карьере, достатке и мире, особенно в конце года.",
    "Đền Ông Hoàng Mười, còn gọi là đền Mỏ Hạc, tọa lạc bên dòng sông Lam ở làng Xuân Am, xã Hưng Thịnh, huyện Hưng Nguyên, cách thành phố Vinh khoảng 7 km. Đền thờ ông Hoàng Mười – một vị thánh trong hệ thống tín ngưỡng thờ Mẫu Tứ Phủ của người Việt, được dân gian xem là vị thần ban lộc về công danh, học hành và sự nghiệp. Tương truyền ông Hoàng Mười giáng trần gắn với hình tượng những danh tướng, danh nhân có công với quê hương xứ Nghệ. Ngôi đền có lịch sử hàng trăm năm, kiến trúc truyền thống với tam quan, các tòa bái đường và hậu cung chạm khắc tinh xảo, mái ngói rêu phong, cây cối um tùm tạo không gian trầm mặc, linh thiêng. Hằng năm, đền tổ chức nhiều kỳ lễ, lớn nhất là lễ hội vào rằm tháng Ba và lễ giỗ ông Hoàng Mười ngày 10 tháng Mười âm lịch, thu hút hàng vạn người hành hương với các nghi lễ rước, hầu đồng, hát chầu văn đặc sắc. Du khách đến đây không chỉ dâng hương cầu may mà còn được hòa mình vào không khí văn hóa tâm linh đậm đà bản sắc của vùng đất bên bờ sông Lam.",
    "Ong Hoang Muoi Temple, also called Mo Hac Temple, sits beside the Lam River in Xuan Am hamlet, Hung Thinh commune, Hung Nguyen district, about 7 km from Vinh City. It honours Ong Hoang Muoi, a saint in the Vietnamese Mother Goddess (Four Palaces) tradition, popularly regarded as a deity who bestows blessings on careers, study and success. Legend links him to renowned generals and worthies who served the land of Nghe An. Several centuries old, the temple follows traditional architecture with a triple gate, worship halls and a finely carved rear sanctum, its mossy tiled roofs and lush trees creating a solemn, sacred atmosphere. Each year it holds several ceremonies, the largest being the festival on the fifteenth day of the third lunar month and Ong Hoang Muoi's memorial day on the tenth day of the tenth lunar month, drawing tens of thousands of pilgrims with processions, spirit-mediumship rituals and distinctive chau van singing. Visitors come not only to offer incense and pray for luck but also to immerse themselves in the deeply traditional spiritual culture of this riverside land.",
    "Храм Онг Хоанг Мыой, называемый также храмом Мо Хак, стоит у реки Лам в деревне Суанам общины Хынгтхинь уезда Хынгнгуен, примерно в 7 км от города Винь. Он посвящён Онг Хоанг Мыою — святому во вьетнамской традиции культа Богини-Матери («Четыре дворца»), которого в народе почитают как божество, дарующее удачу в карьере, учёбе и делах. Предание связывает его с прославленными полководцами и достойными людьми, служившими земле Нгеан. Храму несколько столетий; он выстроен в традиционном стиле с тройными воротами, молитвенными залами и тонко резным задним святилищем, а замшелые черепичные крыши и густая зелень создают торжественную, священную атмосферу. Ежегодно здесь проводят несколько церемоний; крупнейшие — праздник в пятнадцатый день третьего лунного месяца и день памяти Онг Хоанг Мыоя в десятый день десятого лунного месяца, собирающие десятки тысяч паломников с процессиями, ритуалами медиумов и самобытным пением тямван. Гости приходят не только воскурить благовония и попросить удачи, но и погрузиться в глубоко традиционную духовную культуру этого приречного края.",
    ["Đền linh thiêng thờ ông Hoàng Mười trong tín ngưỡng thờ Mẫu Tứ Phủ",
     "Bên bờ sông Lam, cách Vinh ~7 km; kiến trúc cổ, không gian trầm mặc",
     "Lễ hội lớn rằm tháng Ba và giỗ 10/10 âm lịch với hầu đồng, chầu văn"],
    ["A revered shrine to Ong Hoang Muoi in the Mother Goddess tradition",
     "On the Lam River, ~7 km from Vinh; old architecture, solemn setting",
     "Major festivals in the third lunar month and on the 10th day of the 10th month"],
    ["Почитаемое святилище Онг Хоанг Мыоя в традиции культа Богини-Матери",
     "На реке Лам, ~7 км от Виня; старинная архитектура, торжественная атмосфера",
     "Крупные праздники в третьем лунном месяце и 10-го числа десятого месяца"],
    {"hours_vi": "Khoảng 6:00–18:00; dịp lễ mở muộn hơn.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 1–1,5 giờ.",
     "best_time_vi": "Dịp lễ hội tháng Ba và tháng Mười âm lịch; cuối năm đông khách cầu lộc.",
     "tips_vi": "Ăn mặc lịch sự, giữ trật tự; cẩn thận tư trang khi đông người; kết hợp thăm thành phố Vinh."},
    ["spiritual", "temple", "culture", "festival", "outdoor"],
    [{"title": "Wikipedia (VI) — Đền Ông Hoàng Mười", "url": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%81n_%C3%94ng_Ho%C3%A0ng_M%C6%B0%E1%BB%9Di"}]),

rec("pu-mat-national-park",
    "Vườn quốc gia Pù Mát",
    "Pu Mat National Park",
    "Национальный парк Пумат",
    ["park_garden", "other"],
    18.7670, 104.4000,
    "Địa phận các huyện Con Cuông, Anh Sơn, Tương Dương, tỉnh Nghệ An",
    {"value": 4.6, "count": 2100, "source": "Google", "as_of": "2026-07"},
    "Rừng nguyên sinh rộng lớn, đa dạng sinh học cao; du khách thích trekking, tắm thác, thăm bản làng dân tộc. Đường vào một số điểm còn khó, nên đi có hướng dẫn.",
    "Vườn quốc gia Pù Mát trải trên ba huyện miền Tây Nghệ An là khu rừng nguyên sinh lớn nhất Bắc Trung Bộ, lõi của Khu dự trữ sinh quyển thế giới miền Tây Nghệ An. Nơi đây có hệ động thực vật phong phú cùng nhiều thác nước, sông suối và bản làng dân tộc thiểu số.",
    "Pu Mat National Park, spread across three districts of western Nghe An, is the largest primary forest in north-central Vietnam and the core of the Western Nghe An World Biosphere Reserve. It shelters rich flora and fauna along with waterfalls, streams and ethnic minority villages.",
    "Национальный парк Пумат, раскинувшийся на трёх уездах западного Нгеана, — крупнейший первичный лес северо-центрального Вьетнама и ядро всемирного биосферного заповедника Западный Нгеан. Здесь обитают богатая флора и фауна, есть водопады, реки и деревни этнических меньшинств.",
    "Vườn quốc gia Pù Mát nằm trên sườn đông dãy Trường Sơn, thuộc ba huyện Con Cuông, Anh Sơn và Tương Dương, cách thành phố Vinh khoảng 130 km về phía tây. Với diện tích vùng lõi hơn 94.000 ha, đây là khu rừng nguyên sinh lớn nhất khu vực Bắc Trung Bộ và là trung tâm của Khu dự trữ sinh quyển thế giới miền Tây Nghệ An được UNESCO công nhận. Pù Mát nổi tiếng bởi đa dạng sinh học bậc cao với hàng nghìn loài thực vật cùng nhiều loài thú quý hiếm như sao la, voi, hổ, vượn đen má trắng, các loài linh trưởng và chim đặc hữu. Đến với vườn, du khách có thể trekking xuyên rừng, khám phá thác Khe Kèm hùng vĩ, ngược dòng sông Giăng bằng thuyền, tắm suối nước Mọc mát lạnh, thăm rừng săng lẻ cổ thụ và trải nghiệm văn hóa của đồng bào Thái, Đan Lai sống trong vùng đệm. Khí hậu ở đây trong lành, cảnh quan hoang sơ với núi rừng trùng điệp, suối trong và không khí mát mẻ quanh năm. Pù Mát là điểm đến lý tưởng cho những ai yêu thiên nhiên, thích du lịch sinh thái, nghiên cứu và mạo hiểm giữa đại ngàn miền Tây xứ Nghệ.",
    "Pu Mat National Park lies on the eastern slope of the Truong Son range across the districts of Con Cuong, Anh Son and Tuong Duong, about 130 km west of Vinh City. With a core zone of over 94,000 hectares, it is the largest primary forest in north-central Vietnam and the heart of the UNESCO-recognised Western Nghe An World Biosphere Reserve. Pu Mat is famed for its high biodiversity, with thousands of plant species and rare mammals such as the saola, elephant, tiger, white-cheeked gibbon, other primates and endemic birds. Visitors can trek through the forest, admire the mighty Khe Kem Waterfall, travel upstream on the Giang River by boat, bathe in the cool Moc spring, walk among ancient sang le (crape-myrtle) groves and experience the culture of the Thai and Dan Lai peoples living in the buffer zone. The air is clean and the scenery wild, with layered mountains, clear streams and a cool climate year-round. Pu Mat is an ideal destination for nature lovers and those drawn to eco-tourism, research and adventure deep in the forests of western Nghe An.",
    "Национальный парк Пумат расположен на восточном склоне хребта Чыонгшон в уездах Конкуонг, Аншон и Тыонгзыонг, примерно в 130 км к западу от города Винь. С ядром площадью более 94 000 гектаров это крупнейший первичный лес северо-центрального Вьетнама и сердце признанного ЮНЕСКО всемирного биосферного заповедника Западный Нгеан. Пумат славится высоким биоразнообразием: тысячи видов растений и редкие млекопитающие — саола, слон, тигр, белощёкий гиббон, другие приматы и эндемичные птицы. Здесь можно совершать треккинг по лесу, любоваться могучим водопадом Кхекем, подниматься по реке Зянг на лодке, купаться в прохладном источнике Мок, гулять среди древних рощ криптомерии-лагерстрёмии и знакомиться с культурой народов тхай и данлай, живущих в буферной зоне. Воздух чист, а пейзажи первозданны: гряды гор, прозрачные ручьи и прохладный климат круглый год. Пумат — идеальное место для любителей природы, экотуризма, исследований и приключений в лесах западного Нгеана.",
    ["Rừng nguyên sinh lớn nhất Bắc Trung Bộ, vùng lõi ~94.000 ha",
     "Trung tâm Khu dự trữ sinh quyển thế giới miền Tây Nghệ An (UNESCO)",
     "Trekking, thác Khe Kèm, sông Giăng, suối nước Mọc, bản người Thái/Đan Lai"],
    ["The largest primary forest in north-central Vietnam, core ~94,000 ha",
     "Heart of the UNESCO Western Nghe An World Biosphere Reserve",
     "Trekking, Khe Kem Waterfall, Giang River, Moc spring, Thai/Dan Lai villages"],
    ["Крупнейший первичный лес северо-центрального Вьетнама, ядро ~94 000 га",
     "Сердце биосферного заповедника ЮНЕСКО Западный Нгеан",
     "Треккинг, водопад Кхекем, река Зянг, источник Мок, деревни тхай/данлай"],
    {"hours_vi": "Ban ngày; cần đăng ký/hướng dẫn ở một số tuyến.",
     "ticket_vi": "Có phí tham quan và dịch vụ (thuyền, hướng dẫn) tùy tuyến.",
     "duration_vi": "Từ nửa ngày đến 2–3 ngày tùy hành trình.",
     "best_time_vi": "Mùa khô (khoảng tháng 10–4); thác nhiều nước sau mùa mưa.",
     "tips_vi": "Đi giày trekking, mang chống côn trùng; nên thuê hướng dẫn địa phương; đặt trước dịch vụ thuyền sông Giăng."},
    ["nature", "ecotourism", "trekking", "unesco", "outdoor", "top", "daytrip"],
    [{"title": "Wikipedia (VI) — Vườn quốc gia Pù Mát", "url": "https://vi.wikipedia.org/wiki/V%C6%B0%E1%BB%9Dn_qu%E1%BB%91c_gia_P%C3%B9_M%C3%A1t"}]),

rec("thac-khe-kem",
    "Thác Khe Kèm",
    "Khe Kem Waterfall",
    "Водопад Кхекем",
    ["park_garden", "other"],
    18.9000, 104.7200,
    "Xã Lục Dạ, huyện Con Cuông (trong Vườn quốc gia Pù Mát), tỉnh Nghệ An",
    {"value": 4.5, "count": 1300, "source": "Google", "as_of": "2026-07"},
    "Thác nước nguyên sơ cao, buông mình qua rừng như dải lụa trắng; nước mát, cảnh đẹp. Du khách thích tắm thác, chụp ảnh; đường vào đã thuận tiện hơn.",
    "Thác Khe Kèm nằm sâu trong Vườn quốc gia Pù Mát, cao khoảng 150 m, được ví như một trong những thác nước còn nguyên sơ đẹp nhất Việt Nam. Dòng nước đổ qua nhiều tầng đá giữa rừng già tạo khung cảnh hùng vĩ, mát lành.",
    "Khe Kem Waterfall, deep inside Pu Mat National Park, drops roughly 150 metres and is regarded as one of Vietnam's most pristine falls. Its waters cascade over rock tiers amid old-growth forest, creating a majestic, refreshing scene.",
    "Водопад Кхекем в глубине национального парка Пумат падает примерно на 150 метров и считается одним из самых нетронутых водопадов Вьетнама. Его воды каскадом стекают по уступам скал среди древнего леса, создавая величественную и освежающую картину.",
    "Thác Khe Kèm là một thắng cảnh nổi tiếng nằm trong vùng lõi Vườn quốc gia Pù Mát, thuộc huyện Con Cuông, cách thị trấn Con Cuông khoảng 20 km về phía tây nam. Thác có độ cao khoảng 150 m, dòng nước bắt nguồn từ những đỉnh núi cao của dãy Trường Sơn, len qua rừng nguyên sinh rồi buông mình xuống nhiều bậc đá dựng đứng, trắng xóa như một dải lụa vắt giữa đại ngàn xanh thẳm. Các nhà nghiên cứu đánh giá Khe Kèm là một trong những thác nước còn giữ được vẻ hoang sơ, nguyên vẹn bậc nhất cả nước, chưa bị tác động nhiều bởi con người. Dưới chân thác là những vũng nước trong mát, quanh năm rợp bóng cây rừng, không khí trong lành, mát lạnh, rất thích hợp để tắm mát, nghỉ ngơi và chụp ảnh. Xung quanh thác, hệ thực vật phong phú với nhiều loài phong lan, dương xỉ, cây cổ thụ và tiếng chim rừng khiến khung cảnh thêm phần thơ mộng. Đường tới thác nay đã được nâng cấp, du khách có thể đi ô tô, xe máy vào gần chân thác. Khe Kèm thường được kết hợp trong hành trình khám phá Pù Mát cùng sông Giăng, đập Phà Lài và các bản làng người Thái, mang lại trải nghiệm sinh thái trọn vẹn giữa miền Tây xứ Nghệ.",
    "Khe Kem Waterfall is a celebrated beauty spot in the core of Pu Mat National Park, in Con Cuong district, about 20 km southwest of Con Cuong town. Around 150 metres high, its waters rise from the high peaks of the Truong Son range, thread through primary forest and tumble down steep rock tiers, foaming white like a silk band draped across the deep green forest. Researchers rate Khe Kem among the most pristine, untouched falls in the whole country. At its foot lie clear, cool pools shaded year-round by forest trees, with fresh, chilly air perfect for bathing, resting and photography. The surrounding vegetation is rich in orchids, ferns and ancient trees, and the calls of forest birds make the scene all the more poetic. The road to the falls has been upgraded, so visitors can drive a car or motorbike close to the base. Khe Kem is usually combined into a Pu Mat itinerary with the Giang River, Pha Lai weir and Thai ethnic villages, offering a complete eco-experience in western Nghe An.",
    "Водопад Кхекем — знаменитая достопримечательность в ядре национального парка Пумат, в уезде Конкуонг, примерно в 20 км к юго-западу от посёлка Конкуонг. Высотой около 150 метров, его воды берут начало на высоких вершинах хребта Чыонгшон, пробиваются сквозь первичный лес и низвергаются по крутым уступам скал, пенясь белым, словно шёлковая лента на фоне тёмно-зелёного леса. Исследователи относят Кхекем к числу самых нетронутых водопадов всей страны. У его подножия лежат прозрачные прохладные заводи, круглый год затенённые лесными деревьями, а свежий и холодный воздух идеален для купания, отдыха и фотографий. Окружающая растительность богата орхидеями, папоротниками и вековыми деревьями, а пение лесных птиц делает пейзаж ещё поэтичнее. Дорога к водопаду обновлена, поэтому подъехать к его подножию можно на автомобиле или мотоцикле. Кхекем обычно включают в маршрут по Пумату вместе с рекой Зянг, плотиной Фалай и деревнями народа тхай, что дарит полноценный экологический опыт в западном Нгеане.",
    ["Thác nguyên sơ cao ~150 m trong Vườn quốc gia Pù Mát",
     "Một trong những thác đẹp, hoang sơ bậc nhất Việt Nam",
     "Tắm mát dưới chân thác; kết hợp sông Giăng, đập Phà Lài, bản Thái"],
    ["A pristine ~150 m waterfall inside Pu Mat National Park",
     "Among the most beautiful, untouched falls in Vietnam",
     "Swim at its foot; combine with the Giang River, Pha Lai weir and Thai villages"],
    ["Нетронутый водопад высотой ~150 м в национальном парке Пумат",
     "Среди самых красивых и первозданных водопадов Вьетнама",
     "Купание у подножия; сочетается с рекой Зянг, плотиной Фалай и деревнями тхай"],
    {"hours_vi": "Ban ngày.",
     "ticket_vi": "Có phí tham quan Vườn quốc gia/dịch vụ.",
     "duration_vi": "Khoảng 2–3 giờ (chưa kể di chuyển).",
     "best_time_vi": "Sau mùa mưa (khoảng tháng 9–11) thác nhiều nước; mùa hè tắm mát.",
     "tips_vi": "Mang dép chống trơn, đồ bơi; cẩn thận đá trơn; kết hợp khám phá Pù Mát."},
    ["nature", "waterfall", "ecotourism", "outdoor", "family", "daytrip"],
    [{"title": "Cổng thông tin du lịch Việt Nam — Pù Mát, thác Khe Kèm", "url": "https://vietnamtourism.gov.vn/post/23786"}]),

rec("dao-che-thanh-chuong",
    "Đảo chè Thanh Chương (Hồ Cầu Cau)",
    "Thanh Chuong Tea Island (Cau Cau Lake)",
    "Чайный остров Тханьтьыонг (озеро Каукау)",
    ["park_garden", "other"],
    18.6950, 105.3050,
    "Xã Thanh An, huyện Thanh Chương, tỉnh Nghệ An",
    {"value": 4.5, "count": 3600, "source": "Google", "as_of": "2026-07"},
    "Những ốc đảo chè xanh mướt nổi giữa hồ nước, đẹp như tranh; du khách chèo thuyền, chụp ảnh 'sống ảo'. Sáng sớm sương phủ rất nên thơ; dịch vụ còn đơn giản.",
    "Đảo chè Thanh Chương là những đồi chè xanh mướt nổi lên giữa mặt hồ Cầu Cau, tạo nên khung cảnh nên thơ hiếm có ở xứ Nghệ. Du khách đi thuyền len giữa các 'ốc đảo' chè, hít thở không khí trong lành và chụp những bức ảnh tuyệt đẹp.",
    "Thanh Chuong Tea Island is a cluster of lush green tea hills rising from Cau Cau Lake, forming a rare, picturesque scene in Nghe An. Visitors glide by boat between the tea 'islets', breathe the fresh air and take stunning photographs.",
    "Чайный остров Тханьтьыонг — группа сочно-зелёных чайных холмов, поднимающихся из озера Каукау и образующих редкий живописный пейзаж в Нгеане. Гости плывут на лодке между чайными «островками», дышат свежим воздухом и делают потрясающие снимки.",
    "Đảo chè Thanh Chương nằm ở xã Thanh An, huyện Thanh Chương, cách thành phố Vinh khoảng 45–50 km về phía tây. Đây vốn là vùng đồi trồng chè của nông trường, khi hồ Cầu Cau tích nước đã biến những quả đồi chè thành hàng chục hòn đảo lớn nhỏ nổi giữa mặt nước xanh biếc, tạo nên một bức tranh thiên nhiên độc đáo được ví như 'Hạ Long xanh' trên cạn của xứ Nghệ. Từng luống chè được trồng uốn lượn theo hình bát úp, xanh mướt quanh năm, phản chiếu xuống làn nước phẳng lặng khiến khung cảnh thêm phần thơ mộng. Du khách đến đây thường thuê thuyền máy hoặc thuyền chèo dạo quanh hồ, len lỏi giữa các đảo chè, ngắm cảnh, câu cá và chụp ảnh; nhiều người chọn thời điểm sáng sớm khi sương mờ giăng trên mặt hồ hoặc lúc hoàng hôn buông để có những khoảnh khắc đẹp nhất. Không khí ở đây trong lành, yên tĩnh, rất hợp cho những chuyến dã ngoại, cắm trại nhẹ nhàng. Gần đảo chè còn có đền Cửa Lũy và các vườn cây ăn quả để kết hợp tham quan. Với vẻ đẹp bình dị mà cuốn hút, đảo chè Thanh Chương đã trở thành một trong những điểm 'check-in' được yêu thích nhất Nghệ An trong những năm gần đây.",
    "Thanh Chuong Tea Island lies in Thanh An commune, Thanh Chuong district, about 45-50 km west of Vinh City. Once a state farm's tea-growing hills, the area was transformed when Cau Cau Lake filled: the tea hills became dozens of large and small islands floating on the blue water, an unusual natural picture nicknamed the 'green Ha Long' of Nghe An. The tea is planted in curving, dome-shaped rows, green all year and mirrored in the still water for an even more poetic effect. Visitors usually hire a motorboat or rowboat to cruise the lake, weaving among the tea islands to sightsee, fish and take photos; many choose early morning, when mist drifts over the water, or sunset for the finest moments. The air is fresh and quiet, ideal for gentle picnics and camping. Nearby are Cua Luy Temple and fruit orchards to combine into a visit. With its simple yet captivating beauty, Thanh Chuong Tea Island has become one of Nghe An's most beloved check-in spots in recent years.",
    "Чайный остров Тханьтьыонг находится в общине Тханьан уезда Тханьтьыонг, примерно в 45-50 км к западу от города Винь. Некогда чайные холмы государственной фермы преобразились, когда наполнилось озеро Каукау: холмы стали десятками больших и малых островов, плывущих по синей воде, — необычная природная картина, прозванная «зелёным Халонгом» Нгеана. Чай посажен изогнутыми куполообразными рядами, зелёными круглый год и отражающимися в неподвижной воде, что делает пейзаж ещё поэтичнее. Гости обычно нанимают моторную или гребную лодку, чтобы плыть по озеру, лавируя между чайными островами, любоваться видами, рыбачить и фотографировать; многие выбирают раннее утро, когда над водой стелется туман, или закат для лучших кадров. Воздух свеж и тих, идеален для спокойных пикников и кемпинга. Рядом — храм Кыалуй и фруктовые сады, которые можно посетить заодно. Своей простой, но пленительной красотой чайный остров Тханьтьыонг в последние годы стал одним из самых любимых мест для фотографий в Нгеане.",
    ["Đồi chè xanh nổi giữa hồ Cầu Cau — 'Hạ Long xanh' của xứ Nghệ",
     "Đi thuyền len giữa các ốc đảo chè, chụp ảnh, câu cá",
     "Đẹp nhất lúc sáng sớm sương phủ hoặc hoàng hôn"],
    ["Green tea hills floating on Cau Cau Lake — the 'green Ha Long' of Nghe An",
     "Boat among the tea islets to sightsee, fish and take photos",
     "At its best in the misty early morning or at sunset"],
    ["Зелёные чайные холмы на озере Каукау — «зелёный Халонг» Нгеана",
     "Лодка между чайными островками для видов, рыбалки и фото",
     "Прекраснее всего туманным ранним утром или на закате"],
    {"hours_vi": "Ban ngày (khoảng 6:00–18:00).",
     "ticket_vi": "Phí thuyền theo lượt/nhóm (thỏa thuận tại bến).",
     "duration_vi": "Khoảng 2–3 giờ.",
     "best_time_vi": "Sáng sớm hoặc chiều muộn; mùa xuân, đầu hè trời đẹp.",
     "tips_vi": "Mang mũ nón, kem chống nắng; mặc áo phao khi đi thuyền; đi sớm tránh nắng và đông."},
    ["nature", "lake", "viewpoint", "outdoor", "family", "daytrip", "top"],
    [{"title": "Traveloka — Đảo chè Thanh Chương", "url": "https://www.traveloka.com/vi-vn/explore/destination/dao-che-thanh-chuong-acc/245803"}]),

rec("den-cuong",
    "Đền Cuông (đền thờ An Dương Vương)",
    "Den Cuong Temple (An Duong Vuong Temple)",
    "Храм Дэнкуонг (храм короля Ан Зыонг Выонга)",
    ["church", "monument"],
    18.9550, 105.5850,
    "Núi Mộ Dạ, xã Diễn An (nay thuộc Diễn Châu), tỉnh Nghệ An",
    {"value": 4.5, "count": 1500, "source": "Google", "as_of": "2026-07"},
    "Ngôi đền cổ kính bên núi Mộ Dạ, gắn truyền thuyết An Dương Vương; không gian linh thiêng, cây cối cổ thụ. Lễ hội đầu năm rất đông; nhiều người leo núi vãn cảnh.",
    "Đền Cuông tọa lạc trên núi Mộ Dạ ở huyện Diễn Châu, thờ Thục Phán An Dương Vương – vị vua nước Âu Lạc gắn với truyền thuyết Loa Thành và nỏ thần. Ngôi đền cổ kính giữa rừng cây, gắn với sự tích công chúa Mỵ Châu và câu chuyện lịch sử bi tráng.",
    "Den Cuong Temple stands on Mo Da Mountain in Dien Chau district, honouring Thuc Phan An Duong Vuong, king of Au Lac, tied to the legend of the Co Loa citadel and the magic crossbow. The ancient temple amid the forest is linked to Princess My Chau and a tragic historical tale.",
    "Храм Дэнкуонг стоит на горе Мода в уезде Зьентяу и посвящён Тхук Фан Ан Зыонг Выонгу, королю государства Аулак, связанному с легендой о цитадели Колоа и волшебном арбалете. Древний храм среди леса связан с принцессой Ми Тяу и трагической исторической легендой.",
    "Đền Cuông là một ngôi đền cổ nằm trên sườn núi Mộ Dạ, bên Quốc lộ 1A thuộc xã Diễn An, huyện Diễn Châu, cách thành phố Vinh khoảng 30 km về phía bắc. Đền thờ Thục Phán An Dương Vương – vị vua đã lập nên nhà nước Âu Lạc và xây thành Cổ Loa – gắn liền với truyền thuyết nỏ thần, mối tình Mỵ Châu – Trọng Thủy và kết cục bi tráng khi nhà vua theo thần Kim Quy đi về phía biển tại chính vùng đất này. Đền được xây dựng từ lâu đời, kiến trúc theo lối truyền thống với tam quan, tòa trung điện và thượng điện, mái ngói rêu phong, cột kèo chạm khắc, nép mình dưới những tán cây cổ thụ xanh tốt trên núi Mộ Dạ tạo nên không gian trầm mặc, linh thiêng. Từ đền, du khách có thể leo lên núi ngắm cảnh rừng cây, phóng tầm mắt ra biển Cửa Hiền và vùng đồng bằng Diễn Châu. Hằng năm, lễ hội đền Cuông diễn ra vào rằm tháng Hai âm lịch, kéo dài nhiều ngày với các nghi lễ rước, tế và phần hội sôi nổi, thu hút đông đảo nhân dân và du khách thập phương về dâng hương, tưởng nhớ vị vua trong buổi đầu dựng nước. Đền Cuông đã được công nhận là di tích lịch sử – văn hóa cấp quốc gia.",
    "Den Cuong is an ancient temple on the slope of Mo Da Mountain beside National Highway 1A in Dien An commune, Dien Chau district, about 30 km north of Vinh City. It honours Thuc Phan An Duong Vuong, the king who founded the state of Au Lac and built the Co Loa citadel, and is bound to the legend of the magic crossbow, the romance of My Chau and Trong Thuy, and the tragic ending when the king followed the Golden Turtle deity toward the sea in this very area. Long established, the temple follows traditional architecture with a triple gate, middle hall and upper sanctum, its mossy tiled roofs and carved beams nestled beneath ancient trees on Mo Da Mountain, creating a solemn, sacred space. From the temple, visitors can climb the hill to enjoy forest views and gaze out over Cua Hien beach and the Dien Chau plain. Each year the Den Cuong festival takes place on the fifteenth day of the second lunar month, lasting several days with processions, rites and lively activities that draw crowds of pilgrims to offer incense in memory of the king of Vietnam's founding era. Den Cuong is recognised as a national historical and cultural relic.",
    "Дэнкуонг — древний храм на склоне горы Мода у национального шоссе 1А в общине Зьенан уезда Зьентяу, примерно в 30 км к северу от города Винь. Он посвящён Тхук Фан Ан Зыонг Выонгу — королю, основавшему государство Аулак и построившему цитадель Колоа, — и связан с легендой о волшебном арбалете, романом Ми Тяу и Чонг Тхюи и трагическим финалом, когда король последовал за божеством Золотой Черепахой к морю именно в этих краях. Издавна построенный храм выдержан в традиционном стиле с тройными воротами, средним залом и верхним святилищем; замшелые черепичные крыши и резные балки укрыты под вековыми деревьями на горе Мода, создавая торжественное, священное пространство. От храма посетители могут подняться на холм, чтобы любоваться лесом и видами на пляж Кыахьен и равнину Зьентяу. Ежегодно праздник Дэнкуонг проходит в пятнадцатый день второго лунного месяца и длится несколько дней с процессиями, обрядами и оживлёнными гуляньями, привлекая толпы паломников, воскуряющих благовония в память о короле эпохи основания страны. Дэнкуонг признан национальным историко-культурным памятником.",
    ["Đền cổ trên núi Mộ Dạ thờ An Dương Vương, gắn truyền thuyết nỏ thần",
     "Không gian linh thiêng dưới cây cổ thụ, nhìn ra biển và đồng bằng Diễn Châu",
     "Lễ hội rằm tháng Hai âm lịch; di tích lịch sử – văn hóa quốc gia"],
    ["Ancient temple on Mo Da Mountain to An Duong Vuong, tied to the magic-crossbow legend",
     "Sacred setting under old trees, overlooking the sea and Dien Chau plain",
     "Festival on the 15th of the second lunar month; national relic"],
    ["Древний храм на горе Мода в честь Ан Зыонг Выонга и легенды о волшебном арбалете",
     "Священное место под старыми деревьями, вид на море и равнину Зьентяу",
     "Праздник 15-го числа второго лунного месяца; национальный памятник"],
    {"hours_vi": "Khoảng 6:00–18:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 1–2 giờ (kể cả leo núi).",
     "best_time_vi": "Lễ hội rằm tháng Hai âm lịch; đầu xuân đông khách.",
     "tips_vi": "Ăn mặc lịch sự; đi giày đế bám để leo núi; kết hợp thăm biển Diễn Thành gần đó."},
    ["spiritual", "temple", "history", "culture", "festival", "outdoor"],
    [{"title": "Wikipedia (VI) — Đền Cuông", "url": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%81n_Cu%C3%B4ng"}]),

]

# ---- Chèn an toàn ----
d = json.load(open(F, encoding="utf-8")) if os.path.exists(F) else []
have = {p["slug"] for p in d}
added = [p for p in new if p["slug"] not in have]
d += added
json.dump(d, open(F, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("batch1 them:", len(added), "| gio co:", len(d))
