# -*- coding: utf-8 -*-
"""Bổ sung địa điểm du lịch tỉnh Cà Mau MỚI (Cà Mau + Bạc Liêu cũ, sáp nhập 1/7/2025).
Chạy: python3 tools/_add_vn_ca_mau_20260727.py"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
F = os.path.join(ROOT, "data", "regions", "vn-ca-mau.json")

REG = "vn-ca-mau"
RNAME = "Cà Mau"
FD = "Miền Nam"


def rec(slug, name_vi, name_en, name_ru, cats, lat, lon, addr, rating,
        rsum, ps_vi, ps_en, ps_ru, pl_vi, pl_en, pl_ru, h_vi, h_en, h_ru,
        practical, tags, photo=None):
    return {
        "id": f"{REG}-{slug}", "slug": slug, "region": REG, "country": "vietnam",
        "region_name_vi": RNAME, "federal_district": FD,
        "name_vi": name_vi, "name_ru": name_ru, "name_en": name_en,
        "categories": cats, "coordinates": {"lat": lat, "lon": lon},
        "address_vi": addr, "rating": rating, "review_summary_vi": rsum,
        "presentation_short_vi": ps_vi, "presentation_short_en": ps_en, "presentation_short_ru": ps_ru,
        "presentation_long_vi": pl_vi, "presentation_long_en": pl_en, "presentation_long_ru": pl_ru,
        "highlights_vi": h_vi, "highlights_en": h_en, "highlights_ru": h_ru,
        "practical": practical, "photo": photo, "photo_credit": None, "maps": {},
        "official_site": None,
        "sources": [
            {"title": "Wikipedia (VI)", "url": "https://vi.wikipedia.org/wiki/Special:Search?search=" + name_vi.replace(" ", "%20")},
            {"title": "Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Special:Search?search=" + name_en.replace(" ", "%20")},
        ],
        "tags": tags, "status": "enriched", "last_updated": "2026-07-27",
    }


NEW = []

# 1. Hòn Đá Bạc
NEW.append(rec(
    "hon-da-bac", "Hòn Đá Bạc", "Hon Da Bac (Silver Stone Island)", "Остров Хондабак",
    ["park_garden", "monument"], 9.0980, 104.8300,
    "Xã Khánh Bình Tây, huyện Trần Văn Thời, tỉnh Cà Mau",
    {"value": 4.3, "count": 1400, "source": "Google", "as_of": "2026-07"},
    "Du khách thích cụm đảo đá granite sát bờ biển tây Cà Mau, nối nhau bằng cầu, cảnh biển đẹp và hải sản tươi. Nhiều người khen di tích lịch sử, đền thờ và những khối đá hình thù kỳ lạ.",
    "Hòn Đá Bạc là cụm ba hòn đảo đá granite nhỏ nằm sát bờ biển tây tỉnh Cà Mau, thuộc huyện Trần Văn Thời. Nơi đây nổi tiếng với những khối đá xếp chồng lấp lánh dưới nắng, cây cầu nối các đảo và giá trị lịch sử của chuyên án chống gián điệp CM12.",
    "Hon Da Bac is a cluster of three small granite islands just off the western coast of Ca Mau province, in Tran Van Thoi district. It is known for its glittering stacked rocks, the bridges linking the islands and its history as the site of the CM12 counter-espionage operation.",
    "Хондабак — группа из трёх небольших гранитных островов у западного побережья провинции Камау, в уезде Чанвантхой. Он известен блестящими на солнце нагромождениями камней, мостами между островами и историей контрразведывательной операции «CM12».",
    "Hòn Đá Bạc là một cụm gồm ba hòn đảo đá nhỏ gồm Hòn Ông Ngộ, Hòn Trọi và Hòn Đá Bạc, nằm sát bờ biển phía tây tỉnh Cà Mau, cách trung tâm thành phố khoảng 50 km về hướng huyện Trần Văn Thời. Đảo có tên như vậy bởi trên bề mặt là vô số khối đá granite lớn nhỏ xếp chồng lên nhau qua hàng triệu năm, khi nắng chiếu vào ánh lên màu xám bạc lấp lánh, tạo nên những hình thù độc đáo được người dân đặt tên như bàn tay tiên, giếng tiên, sân tiên. Ba hòn đảo được nối với nhau và với đất liền bằng những cây cầu bắc qua mặt biển, thuận tiện cho du khách dạo bộ ngắm cảnh. Ngoài vẻ đẹp thiên nhiên, Hòn Đá Bạc còn là di tích lịch sử quốc gia, gắn với chuyên án CM12 nổi tiếng của lực lượng an ninh; trên đảo có đền thờ, tượng đài và khu trưng bày. Du khách đến đây có thể leo lên các mỏm đá ngắm biển, viếng đền thờ cá Ông (Lăng Ông Nam Hải), câu cá và thưởng thức hải sản tươi. Với sự kết hợp giữa cảnh quan biển đảo và ý nghĩa lịch sử, Hòn Đá Bạc là điểm đến tiêu biểu của vùng biển tây tỉnh Cà Mau.",
    "Hon Da Bac is a cluster of three small rocky islands — Hon Ong Ngo, Hon Troi and Hon Da Bac — just off the western coast of Ca Mau province, about 50 km from the city centre towards Tran Van Thoi district. It owes its name, meaning silver stone, to the countless granite boulders large and small piled up over millions of years, which shimmer a silvery grey in the sun and form unusual shapes locals have named the fairy's hand, the fairy's well and the fairy's yard. The three islands are joined to one another and to the mainland by bridges over the sea, letting visitors stroll and admire the scenery. Beyond its natural beauty, Hon Da Bac is a national historical relic tied to the famous CM12 security operation; on the island are a shrine, a monument and an exhibition area. Visitors can climb the rocks to gaze at the sea, visit the Whale God temple (Lang Ong Nam Hai), fish and enjoy fresh seafood. Combining island scenery with historical significance, Hon Da Bac is a signature destination on the western coast of Ca Mau province.",
    "Хондабак — группа из трёх небольших скалистых островов: Хононгнго, Хончой и Хондабак, у западного побережья провинции Камау, примерно в 50 км от центра города в сторону уезда Чанвантхой. Своё название, означающее «серебряный камень», он получил из-за бесчисленных гранитных валунов, накопленных за миллионы лет: на солнце они отливают серебристо-серым и образуют причудливые формы, которые местные жители назвали «рукой феи», «колодцем феи» и «двором феи». Три острова соединены между собой и с материком мостами над морем, что позволяет гостям прогуливаться и любоваться пейзажем. Помимо природной красоты, Хондабак — национальный исторический памятник, связанный со знаменитой операцией безопасности «CM12»; на острове есть святилище, монумент и выставочная зона. Гости могут взбираться на камни, глядя на море, посещать храм Кита-Бога (Ланг Онг Намхай), рыбачить и наслаждаться свежими морепродуктами. Сочетая островной пейзаж и историческую значимость, Хондабак — характерная достопримечательность западного побережья провинции Камау.",
    ["Cụm ba đảo đá granite lấp lánh nối nhau bằng cầu trên biển", "Di tích lịch sử quốc gia gắn với chuyên án an ninh CM12", "Đền thờ cá Ông, câu cá và hải sản tươi ven biển tây"],
    ["Three glittering granite islands linked by bridges over the sea", "National historical relic tied to the CM12 security operation", "Whale God temple, fishing and fresh seafood on the west coast"],
    ["Три сверкающих гранитных острова, соединённых мостами над морем", "Национальный памятник, связанный с операцией «CM12»", "Храм Кита-Бога, рыбалка и свежие морепродукты на западном берегу"],
    {"hours_vi": "Khoảng 7:00–17:00 hằng ngày.", "ticket_vi": "Vé vào khoảng 20.000–40.000 VND/người.", "duration_vi": "1,5–2 giờ.", "best_time_vi": "Mùa khô tháng 12–4, biển lặng.", "tips_vi": "Mang giày bám tốt khi leo đá; cẩn thận đá trơn; kết hợp thăm rừng U Minh Hạ gần đó."},
    ["nature", "sea", "history", "island"]))

# 2. Đầm Thị Tường
NEW.append(rec(
    "dam-thi-tuong", "Đầm Thị Tường", "Thi Tuong Lagoon", "Лагуна Тхитыонг",
    ["park_garden"], 9.0520, 104.9600,
    "Giáp các xã huyện Trần Văn Thời, Phú Tân và Cái Nước, tỉnh Cà Mau",
    {"value": 4.3, "count": 720, "source": "Google", "as_of": "2026-07"},
    "Du khách thích đầm nước lợ rộng mênh mông được ví như 'biển Hồ' của Cà Mau, ngắm hoàng hôn và ăn hải sản trên nhà sàn giữa đầm. Nhiều người khen trải nghiệm đi vỏ lãi và cuộc sống ngư dân bình dị.",
    "Đầm Thị Tường là đầm nước tự nhiên lớn nhất vùng Đồng bằng sông Cửu Long, nằm giữa các huyện Trần Văn Thời, Phú Tân và Cái Nước. Đầm rộng mênh mông, giàu tôm cá, được người dân ví như 'biển Hồ' của Cà Mau với những chòi canh, nhà sàn nuôi thủy sản.",
    "Thi Tuong Lagoon is the largest natural lagoon in the Mekong Delta, lying among the districts of Tran Van Thoi, Phu Tan and Cai Nuoc. Vast and rich in shrimp and fish, it is likened by locals to a 'sea lake' of Ca Mau, dotted with watch-huts and stilt houses for aquaculture.",
    "Лагуна Тхитыонг — крупнейшая природная лагуна дельты Меконга, лежащая между уездами Чанвантхой, Футан и Кайныок. Огромная и богатая креветками и рыбой, она сравнивается местными жителями с «морским озером» Камау и усеяна сторожевыми хижинами и свайными домами для аквакультуры.",
    "Đầm Thị Tường là đầm nước lợ tự nhiên lớn nhất khu vực Đồng bằng sông Cửu Long, trải rộng trên địa phận giáp ranh ba huyện Trần Văn Thời, Phú Tân và Cái Nước của tỉnh Cà Mau. Đầm được hình thành từ phù sa bồi lắng và thông với biển qua các con sông, tạo nên vùng nước rộng mênh mông mà người dân thường ví von như 'biển Hồ' giữa lòng Cà Mau. Mặt đầm phẳng lặng, in bóng mây trời, đặc biệt đẹp vào lúc bình minh và hoàng hôn khi cả không gian nhuộm màu vàng cam rực rỡ. Đầm rất giàu nguồn lợi thủy sản với tôm, cua, cá, sò huyết; xung quanh là những chòi canh, nhà sàn của ngư dân nuôi trồng và đánh bắt. Du khách đến đây có thể ngồi vỏ lãi hoặc xuồng máy dạo quanh đầm, tận mắt xem người dân giăng lưới, đặt lú bắt cá, rồi dừng chân tại các nhà sàn giữa đầm để thưởng thức hải sản tươi vừa đánh bắt. Trải nghiệm ngắm hoàng hôn trên đầm, nghe kể chuyện sông nước và tận hưởng không khí bình yên khiến Đầm Thị Tường trở thành điểm du lịch sinh thái, trải nghiệm hấp dẫn của tỉnh Cà Mau.",
    "Thi Tuong Lagoon is the largest natural brackish-water lagoon in the Mekong Delta, spreading across the borderlands of three districts — Tran Van Thoi, Phu Tan and Cai Nuoc — in Ca Mau province. Formed by silt deposits and linked to the sea through rivers, it creates a vast expanse of water that locals often liken to a 'sea lake' in the heart of Ca Mau. Its calm surface mirrors the clouds and sky and is especially beautiful at dawn and dusk, when the whole scene turns a brilliant orange-gold. The lagoon teems with shrimp, crab, fish and blood cockles; around it stand the watch-huts and stilt houses of fishermen who farm and catch there. Visitors can take a small motor sampan around the lagoon, watch people cast nets and set fish traps, then stop at the stilt houses in the middle to enjoy freshly caught seafood. Watching the sunset over the water, hearing tales of river life and soaking up the peaceful air make Thi Tuong Lagoon an appealing eco-tourism and experiential destination in Ca Mau province.",
    "Лагуна Тхитыонг — крупнейшая природная солоноватоводная лагуна дельты Меконга, раскинувшаяся на стыке трёх уездов — Чанвантхой, Футан и Кайныок — провинции Камау. Образованная илистыми наносами и связанная с морем через реки, она создаёт огромное водное пространство, которое местные жители часто сравнивают с «морским озером» в сердце Камау. Её спокойная гладь отражает облака и небо и особенно красива на рассвете и закате, когда весь пейзаж окрашивается в яркий оранжево-золотой цвет. Лагуна изобилует креветками, крабами, рыбой и кровяными моллюсками; вокруг стоят сторожевые хижины и свайные дома рыбаков, которые здесь ловят и разводят. Гости могут проплыть на моторном сампане по лагуне, наблюдать, как забрасывают сети и ставят ловушки, а затем остановиться в свайных домах посреди воды, чтобы отведать только что пойманные морепродукты. Наблюдение за закатом над водой, рассказы о речной жизни и умиротворённый воздух делают лагуну Тхитыонг привлекательным экотуристическим направлением провинции Камау.",
    ["Đầm nước tự nhiên lớn nhất Đồng bằng sông Cửu Long", "'Biển Hồ' của Cà Mau, đẹp nhất lúc bình minh và hoàng hôn", "Đi vỏ lãi, xem ngư dân giăng lưới, ăn hải sản trên nhà sàn"],
    ["The largest natural lagoon in the Mekong Delta", "A 'sea lake' of Ca Mau, loveliest at dawn and dusk", "Sampan rides, watching net-casting, seafood on stilt houses"],
    ["Крупнейшая природная лагуна дельты Меконга", "«Морское озеро» Камау, прекраснее всего на рассвете и закате", "Прогулки на сампане, ловля сетями, морепродукты в свайных домах"],
    {"hours_vi": "Cả ngày; đẹp lúc bình minh và hoàng hôn.", "ticket_vi": "Miễn phí; thuê vỏ lãi/xuồng theo thỏa thuận.", "duration_vi": "2–3 giờ.", "best_time_vi": "Mùa khô tháng 12–4; chiều muộn ngắm hoàng hôn.", "tips_vi": "Thỏa thuận giá thuyền trước; mang chống nắng, chống muỗi; đặt trước bữa hải sản nhà sàn."},
    ["nature", "lake", "local", "outdoor"]))

# 3. Chợ nổi Cà Mau
NEW.append(rec(
    "cho-noi-ca-mau", "Chợ nổi Cà Mau", "Ca Mau Floating Market", "Плавучий рынок Камау",
    ["other"], 9.1720, 105.1520,
    "Trên sông Gành Hào, phường 8, TP. Cà Mau, tỉnh Cà Mau",
    {"value": 4.1, "count": 980, "source": "Google", "as_of": "2026-07"},
    "Du khách thích chợ nổi ngay trong lòng thành phố Cà Mau, buôn bán nông sản, trái cây trên ghe. Nhiều người khen không khí sông nước bình dị, đi ghe ngắm cảnh và mua trái cây miệt vườn.",
    "Chợ nổi Cà Mau họp trên sông Gành Hào ngay trong thành phố, là nơi giao thương nông sản, trái cây của vùng cực Nam. Từ sáng sớm, hàng chục ghe thuyền tụ về, treo bẹo hàng, tạo nên nét văn hóa thương hồ đặc trưng miền Tây.",
    "Ca Mau Floating Market gathers on the Ganh Hao River right in the city, a trading place for the farm produce and fruit of the far south. From early morning dozens of boats converge, hanging sample poles, forming the distinctive boat-trading culture of the Delta.",
    "Плавучий рынок Камау собирается на реке Ганьхао прямо в городе — место торговли сельхозпродукцией и фруктами крайнего юга. С раннего утра сходятся десятки лодок с шестами-образцами, образуя самобытную речную торговую культуру дельты.",
    "Chợ nổi Cà Mau nằm trên sông Gành Hào, thuộc địa phận phường 8, ngay trong lòng thành phố Cà Mau, là một trong những chợ nổi ở vị trí cực Nam của Tổ quốc. Dù quy mô không lớn bằng một số chợ nổi khác ở miền Tây, chợ nổi Cà Mau vẫn giữ được nét sinh hoạt buôn bán trên sông đặc trưng và gần gũi. Từ sáng sớm, hàng chục chiếc ghe, xuồng chở đầy nông sản, rau củ, trái cây từ các miệt vườn theo sông rạch tụ về, neo đậu san sát hai bên bờ. Trên mỗi ghe, người ta cắm một cây sào cao gọi là 'cây bẹo', treo lủng lẳng những mẫu hàng như khóm, dưa, bí, khoai để người mua từ xa nhận biết ghe bán thứ gì. Khung cảnh mua bán tấp nập, tiếng máy nổ, tiếng gọi nhau vang trên mặt sông tạo nên bức tranh sông nước sinh động. Du khách có thể thuê ghe len lỏi giữa chợ, trò chuyện với thương hồ, mua trái cây tươi và cảm nhận nếp sống của người dân vùng sông nước. Là nét văn hóa thương hồ truyền thống đang dần mai một, chợ nổi Cà Mau là điểm đến thú vị để hiểu thêm về đời sống miền cực Nam.",
    "Ca Mau Floating Market lies on the Ganh Hao River in ward 8, right in the heart of Ca Mau city, one of the southernmost floating markets in the country. Though smaller than some other floating markets of the Delta, it still keeps its distinctive, homely river-trading life. From early morning dozens of boats laden with farm produce, vegetables and fruit come from the orchards along the rivers and canals and moor close together on both banks. On each boat a tall pole called a 'beo' hangs samples such as pineapple, melon, gourd and sweet potato so buyers can tell from afar what it sells. The bustling trade, the throb of engines and the calls across the water make a lively river scene. Visitors can hire a boat to weave through the market, chat with the traders, buy fresh fruit and sense the way of life of the river people. As a traditional boat-trading culture that is gradually fading, Ca Mau Floating Market is an engaging place to understand more about life in the far south.",
    "Плавучий рынок Камау находится на реке Ганьхао в квартале 8, в самом сердце города Камау, — один из самых южных плавучих рынков страны. Хотя он меньше некоторых других рынков дельты, он сохраняет самобытный, домашний уклад речной торговли. С раннего утра десятки лодок, гружённых сельхозпродукцией, овощами и фруктами, приходят из садов вдоль рек и каналов и швартуются вплотную у обоих берегов. На каждой лодке высокий шест — «бео» — с образцами, такими как ананас, дыня, тыква и батат, чтобы покупатели издали видели, чем торгуют. Оживлённая торговля, стук моторов и переклички над водой создают живую речную картину. Гости могут нанять лодку, чтобы пробраться сквозь рынок, поговорить с торговцами, купить свежие фрукты и почувствовать уклад речных жителей. Как постепенно угасающая традиция речной торговли, плавучий рынок Камау — увлекательное место, чтобы больше узнать о жизни крайнего юга.",
    ["Chợ nổi ở vị trí cực Nam Tổ quốc, ngay trong TP. Cà Mau", "Ghe treo 'cây bẹo' bán nông sản, trái cây miệt vườn", "Nét văn hóa thương hồ truyền thống đang dần mai một"],
    ["A floating market in the far south, right in Ca Mau city", "Boats hang 'beo' poles selling farm produce and orchard fruit", "A fading tradition of river-trading culture"],
    ["Плавучий рынок крайнего юга, прямо в городе Камау", "Лодки с шестами «бео», торгующие продукцией и фруктами", "Угасающая традиция речной торговой культуры"],
    {"hours_vi": "Nhộn nhịp nhất khoảng 5:00–8:00 sáng.", "ticket_vi": "Miễn phí; thuê ghe theo thỏa thuận.", "duration_vi": "1–1,5 giờ.", "best_time_vi": "Sáng sớm; mùa khô tháng 12–4.", "tips_vi": "Đi sớm để chợ còn đông; thỏa thuận giá ghe; mang chống nắng."},
    ["market", "river", "local"]))

# 4. Khu du lịch sinh thái Khai Long
NEW.append(rec(
    "khu-du-lich-khai-long", "Khu du lịch sinh thái Khai Long", "Khai Long Eco-Tourism Area", "Экотуристическая зона Кхайлонг",
    ["other", "park_garden"], 8.5900, 104.8300,
    "Ấp Khai Long, xã Đất Mũi, huyện Ngọc Hiển, tỉnh Cà Mau",
    {"value": 4.0, "count": 560, "source": "Google", "as_of": "2026-07"},
    "Du khách thích bãi biển cát vàng hiếm hoi ở vùng Đất Mũi, nhìn ra cụm đảo Hòn Khoai. Nhiều người khen không gian yên tĩnh, rừng phòng hộ và trải nghiệm biển bãi bồi cực Nam.",
    "Khu du lịch sinh thái Khai Long nằm ở vùng Đất Mũi, huyện Ngọc Hiển, nổi bật với bãi biển cát vàng hiếm có ở vùng cực Nam. Từ bãi biển, du khách nhìn ra cụm đảo Hòn Khoai và tận hưởng khung cảnh rừng ngập mặn, biển bãi bồi hoang sơ.",
    "Khai Long Eco-Tourism Area lies in the Dat Mui region of Ngoc Hien district, notable for a rare stretch of golden-sand beach in the far south. From the shore, visitors look out to the Hon Khoai islands and enjoy scenery of mangrove forest and wild mudflat coast.",
    "Экотуристическая зона Кхайлонг расположена в районе Датмуй уезда Нгокхьен и примечательна редким для крайнего юга участком золотистого песчаного пляжа. С берега гости смотрят на острова Хонкхоай и любуются мангровым лесом и диким илистым побережьем.",
    "Khu du lịch sinh thái Khai Long tọa lạc tại ấp Khai Long, vùng Đất Mũi thuộc huyện Ngọc Hiển, là một trong số ít nơi ở cực Nam Tổ quốc có bãi biển cát vàng trải dài. Điều này khá đặc biệt bởi phần lớn bờ biển Cà Mau là bãi bồi phù sa và rừng ngập mặn, hiếm có bãi cát đẹp. Bãi biển Khai Long thoai thoải, nước biển pha màu phù sa, phía sau lưng là rừng phi lao và rừng phòng hộ xanh mát chắn gió. Đứng trên bờ, du khách có thể phóng tầm mắt ra khơi ngắm cụm đảo Hòn Khoai xanh mờ phía xa, đặc biệt đẹp vào lúc bình minh và hoàng hôn. Khu du lịch từng được đầu tư nhiều hạng mục nghỉ dưỡng, vui chơi, tượng đài và khu tâm linh; du khách có thể tắm biển, dạo rừng, câu cá, thưởng thức hải sản và các món đặc sản vùng Đất Mũi như ba khía, cua Cà Mau, vọp, sò. Nằm gần điểm cực Nam Đất Mũi, Khai Long thường được kết hợp trong hành trình khám phá vùng đất tận cùng Tổ quốc, mang lại trải nghiệm biển bãi bồi và rừng ngập mặn hoang sơ đặc trưng của tỉnh Cà Mau.",
    "Khai Long Eco-Tourism Area lies in Khai Long hamlet, in the Dat Mui region of Ngoc Hien district, one of the few places at the country's southern tip with a long golden-sand beach. This is quite special, since most of the Ca Mau coast is silt mudflat and mangrove forest with few fine sandy beaches. Khai Long's beach slopes gently, its water tinged with silt, backed by casuarina groves and a cool green protective forest that shields it from the wind. Standing on the shore, visitors can gaze out to the Hon Khoai islands looming faint and blue in the distance, especially lovely at dawn and dusk. The area was once developed with lodging, recreation, a monument and a spiritual zone; visitors can swim, walk in the forest, fish and enjoy seafood and Dat Mui specialties such as ba khia (fermented crabs), Ca Mau crab, mud clams and cockles. Near the southern tip at Dat Mui, Khai Long is often included in journeys to explore the country's farthest land, offering the mudflat-coast and wild mangrove experience typical of Ca Mau province.",
    "Экотуристическая зона Кхайлонг находится в деревне Кхайлонг, в районе Датмуй уезда Нгокхьен, — одно из немногих мест на южной оконечности страны с длинным золотистым песчаным пляжем. Это довольно необычно, поскольку большая часть побережья Камау — илистые отмели и мангровые леса, где красивые песчаные пляжи редки. Пляж Кхайлонг полого спускается, вода с оттенком ила, за спиной — рощи казуарин и прохладный зелёный защитный лес, укрывающий от ветра. Стоя на берегу, гости могут смотреть вдаль на острова Хонкхоай, синеющие в дымке, особенно красивые на рассвете и закате. Зона когда-то была застроена жильём, развлечениями, монументом и духовным комплексом; гости могут купаться, гулять по лесу, рыбачить и пробовать морепродукты и деликатесы Датмуй — ба-кхиа (ферментированных крабов), крабов Камау, моллюсков и ракушки. Рядом с южной оконечностью Датмуй Кхайлонг часто включают в маршруты по самому дальнему краю страны, предлагая знакомство с илистым побережьем и диким мангровым лесом провинции Камау.",
    ["Bãi biển cát vàng hiếm có ở vùng cực Nam Đất Mũi", "Nhìn ra cụm đảo Hòn Khoai, đẹp lúc bình minh, hoàng hôn", "Rừng phòng hộ, hải sản và đặc sản ba khía, cua Cà Mau"],
    ["A rare golden-sand beach at the far-southern Dat Mui region", "Views out to the Hon Khoai islands, lovely at dawn and dusk", "Protective forest, seafood and specialties like ba khia and Ca Mau crab"],
    ["Редкий золотистый пляж в районе крайнего юга Датмуй", "Виды на острова Хонкхоай, красиво на рассвете и закате", "Защитный лес, морепродукты и деликатесы ба-кхиа и крабы Камау"],
    {"hours_vi": "Khoảng 7:00–17:00 hằng ngày.", "ticket_vi": "Vé/giữ xe khoảng 20.000–50.000 VND tùy dịch vụ.", "duration_vi": "1,5–2 giờ.", "best_time_vi": "Mùa khô tháng 12–4; sáng sớm hoặc chiều muộn.", "tips_vi": "Kết hợp thăm điểm cực Nam Đất Mũi; mang chống nắng, chống muỗi; thử đặc sản ba khía."},
    ["nature", "beach", "eco", "south"]))

# 5. Đảo Hòn Khoai
NEW.append(rec(
    "hon-khoai", "Đảo Hòn Khoai", "Hon Khoai Island", "Остров Хонкхоай",
    ["other", "monument"], 8.4300, 104.8330,
    "Xã Đất Mũi (Rạch Gốc), huyện Ngọc Hiển, tỉnh Cà Mau",
    {"value": 4.5, "count": 480, "source": "Google", "as_of": "2026-07"},
    "Du khách mê hòn đảo hoang sơ ngoài khơi cực Nam với rừng nguyên sinh, hải đăng cổ và di tích khởi nghĩa Hòn Khoai. Nhiều người khen biển trong, đá đẹp nhưng lưu ý cần xin phép vì là khu vực quân sự.",
    "Hòn Khoai là hòn đảo đẹp nằm ngoài khơi vùng biển cực Nam Tổ quốc, cách Đất Mũi khoảng 14 km. Đảo còn giữ được rừng nguyên sinh, bãi đá, cùng ngọn hải đăng cổ do người Pháp xây và di tích cuộc khởi nghĩa Hòn Khoai năm 1940.",
    "Hon Khoai is a beautiful island off the country's southernmost sea, about 14 km from Dat Mui. It still keeps primary forest and rocky shores, together with an old French-built lighthouse and the relic of the 1940 Hon Khoai uprising.",
    "Хонкхоай — красивый остров у самого южного моря страны, примерно в 14 км от Датмуй. Он сохраняет девственный лес и скалистые берега, а также старый маяк, построенный французами, и памятник восстанию на Хонкхоай 1940 года.",
    "Hòn Khoai là một hòn đảo hoang sơ và tươi đẹp nằm ngoài khơi vùng biển cực Nam của Tổ quốc, thuộc huyện Ngọc Hiển, cách mũi Đất Mũi khoảng 14 km. Đảo có diện tích chừng 4 km² và là hòn lớn nhất trong cụm đảo cùng tên, nổi bật với thảm rừng nguyên sinh còn khá nguyên vẹn, nơi sinh sống của nhiều loài động, thực vật quý. Bao quanh đảo là những bãi đá granite với đủ hình thù, xen kẽ các bãi cát và làn nước biển trong xanh, thích hợp cho việc tắm biển, câu cá và ngắm cảnh. Trên đỉnh cao nhất của đảo là ngọn hải đăng cổ do người Pháp xây dựng từ cuối thế kỷ 19, đến nay vẫn hoạt động và trở thành điểm ngắm toàn cảnh biển trời. Hòn Khoai còn là di tích lịch sử gắn với cuộc khởi nghĩa Hòn Khoai năm 1940 do thầy giáo Phan Ngọc Hiển lãnh đạo, một dấu son trong lịch sử đấu tranh của quân dân Cà Mau. Do đảo nằm ở vị trí trọng yếu và có yếu tố quân sự, du khách muốn ra đảo tham quan thường cần đăng ký, xin phép trước. Với vẻ đẹp hoang sơ và bề dày lịch sử, Hòn Khoai là điểm đến đặc biệt của vùng biển cực Nam tỉnh Cà Mau.",
    "Hon Khoai is a pristine, beautiful island off the country's southernmost sea, in Ngoc Hien district, about 14 km from the tip at Dat Mui. Covering some 4 km², it is the largest of the cluster that shares its name and stands out for its fairly intact primary forest, home to many valuable plants and animals. The island is ringed by granite boulders of every shape, interspersed with sandy stretches and clear blue water, well suited to swimming, fishing and sightseeing. On its highest peak stands an old lighthouse built by the French in the late 19th century, still working today and now a spot for panoramic sea-and-sky views. Hon Khoai is also a historical relic tied to the 1940 Hon Khoai uprising led by the teacher Phan Ngoc Hien, a milestone in the struggle of the people of Ca Mau. As the island lies in a strategic location with a military presence, visitors wishing to go there usually need to register and obtain permission in advance. With its wild beauty and depth of history, Hon Khoai is a special destination in the far-southern sea of Ca Mau province.",
    "Хонкхоай — нетронутый, красивый остров у самого южного моря страны, в уезде Нгокхьен, примерно в 14 км от оконечности Датмуй. Площадью около 4 км², он крупнейший в одноимённой группе и выделяется довольно сохранным девственным лесом, где обитает множество ценных растений и животных. Остров окружён гранитными валунами всевозможных форм вперемежку с песчаными участками и прозрачной голубой водой, удобной для купания, рыбалки и осмотра. На высшей вершине стоит старый маяк, построенный французами в конце XIX века, действующий и поныне и ставший местом панорамных видов на море и небо. Хонкхоай — также исторический памятник, связанный с восстанием на Хонкхоай 1940 года под руководством учителя Фан Нгок Хьена, вехой в борьбе жителей Камау. Поскольку остров находится в стратегическом месте с военным присутствием, желающим его посетить обычно нужно заранее зарегистрироваться и получить разрешение. Дикой красотой и глубиной истории Хонкхоай — особое направление в крайне южном море провинции Камау.",
    ["Đảo hoang sơ ngoài khơi cực Nam với rừng nguyên sinh", "Hải đăng cổ Pháp xây, ngắm toàn cảnh biển trời", "Di tích khởi nghĩa Hòn Khoai 1940 của thầy Phan Ngọc Hiển"],
    ["Pristine island off the far south with primary forest", "Old French-built lighthouse with panoramic sea views", "Relic of the 1940 Hon Khoai uprising led by Phan Ngoc Hien"],
    ["Нетронутый остров у крайнего юга с девственным лесом", "Старый французский маяк с панорамными видами на море", "Памятник восстанию на Хонкхоай 1940 года под руководством Фан Нгок Хьена"],
    {"hours_vi": "Đi trong ngày; cần đăng ký, xin phép trước khi ra đảo.", "ticket_vi": "Chi phí thuê tàu theo nhóm; thủ tục qua cơ quan chức năng.", "duration_vi": "Cả ngày.", "best_time_vi": "Mùa khô tháng 12–4, biển lặng.", "tips_vi": "Bắt buộc xin phép vì là khu vực quân sự; theo dõi thời tiết; mang đủ nước, đồ dùng cá nhân."},
    ["nature", "island", "history", "south"]))

# 6. Nhà Công tử Bạc Liêu
NEW.append(rec(
    "nha-cong-tu-bac-lieu", "Nhà Công tử Bạc Liêu", "House of the Bac Lieu Playboy Prince", "Дом «принца-повесы» Бакльеу",
    ["palace", "museum"], 9.2857, 105.7245,
    "Đường Điện Biên Phủ, phường 3, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.3, "count": 3600, "source": "Google", "as_of": "2026-07"},
    "Du khách thích ngôi biệt thự cổ bề thế gắn với giai thoại Công tử Bạc Liêu ăn chơi khét tiếng. Nhiều người khen kiến trúc Pháp, nội thất gỗ quý và những câu chuyện lịch sử thú vị.",
    "Nhà Công tử Bạc Liêu là dinh thự cổ xây đầu thế kỷ 20, gắn với giai thoại về Trần Trinh Huy – vị công tử giàu có, ăn chơi bậc nhất Nam Kỳ xưa. Ngôi nhà mang kiến trúc Pháp sang trọng, lưu giữ nhiều nội thất gỗ quý và hiện vật cổ.",
    "The House of the Bac Lieu Playboy Prince is an early-20th-century mansion tied to the legend of Tran Trinh Huy, the wealthiest and most extravagant young master of old Cochinchina. It has elegant French architecture and preserves fine wooden furnishings and antiques.",
    "Дом «принца-повесы» Бакльеу — особняк начала XX века, связанный с легендой о Чан Чинь Хюи, богатейшем и самом расточительном молодом господине старой Кохинхины. Он выстроен в изящном французском стиле и хранит ценную деревянную мебель и антиквариат.",
    "Nhà Công tử Bạc Liêu là một dinh thự cổ nằm bên bờ sông ở trung tâm thành phố Bạc Liêu, được xây dựng vào khoảng năm 1917–1919, gắn liền với giai thoại nổi tiếng về Công tử Bạc Liêu Trần Trinh Huy – người con của gia đình đại điền chủ giàu có bậc nhất Nam Kỳ lục tỉnh đầu thế kỷ 20. Ngôi nhà mang phong cách kiến trúc Pháp sang trọng, bề thế với hệ thống cột, vòm, ban công tinh xảo; vật liệu xây dựng và nhiều đồ nội thất được cho là nhập từ Pháp. Bên trong còn lưu giữ những bộ bàn ghế, giường, tủ bằng gỗ quý cẩn xà cừ, đèn, đồng hồ cổ và các hiện vật gắn với cuộc sống xa hoa của gia đình. Du khách đến đây được nghe kể nhiều giai thoại thú vị về sự giàu có và lối ăn chơi khét tiếng của Công tử Bạc Liêu, như chuyện 'đốt tiền nấu trứng', đi máy bay riêng thăm ruộng, phản ánh một phần đời sống của tầng lớp đại điền chủ Nam Bộ xưa. Ngày nay, ngôi nhà được bảo tồn thành điểm tham quan, một phần được khai thác làm nhà hàng, khách sạn. Là biểu tượng du lịch của Bạc Liêu cũ, Nhà Công tử Bạc Liêu là điểm đến hấp dẫn của tỉnh Cà Mau sau sáp nhập.",
    "The House of the Bac Lieu Playboy Prince is an old mansion on the riverbank in the centre of Bac Lieu city, built around 1917–1919 and bound to the famous legend of the 'Bac Lieu prince' Tran Trinh Huy, son of one of the wealthiest landlord families of Cochinchina in the early 20th century. The house is in an elegant, imposing French style, with refined columns, arches and balconies; its materials and much of its furniture are said to have been imported from France. Inside it keeps tables, chairs, beds and cabinets of precious wood inlaid with mother-of-pearl, along with antique lamps, clocks and objects from the family's lavish life. Visitors here hear many colourful tales of the prince's wealth and notorious extravagance — such as burning banknotes to boil eggs and flying a private plane to inspect his fields — reflecting part of the life of the great southern landlord class of old. Today the house is preserved as a sightseeing spot, with part of it used as a restaurant and hotel. As a tourism emblem of former Bac Lieu, the House of the Bac Lieu Playboy Prince is an appealing destination in Ca Mau province after the merger.",
    "Дом «принца-повесы» Бакльеу — старинный особняк на берегу реки в центре города Бакльеу, построенный около 1917–1919 годов и связанный со знаменитой легендой о «принце Бакльеу» Чан Чинь Хюи, сыне одной из богатейших помещичьих семей Кохинхины начала XX века. Дом выстроен в изящном, внушительном французском стиле с утончёнными колоннами, арками и балконами; материалы и значительная часть мебели, как говорят, были ввезены из Франции. Внутри хранятся столы, стулья, кровати и шкафы из ценного дерева с перламутровой инкрустацией, а также старинные лампы, часы и предметы роскошного быта семьи. Гости слышат здесь множество ярких историй о богатстве и печально известной расточительности принца — например, как он сжигал банкноты, чтобы сварить яйца, и летал на личном самолёте осматривать поля, — что отражает часть жизни крупного помещичьего сословия старого юга. Сегодня дом сохранён как место осмотра, часть его используется под ресторан и отель. Как туристический символ прежнего Бакльеу, Дом «принца-повесы» — привлекательное направление провинции Камау после слияния.",
    ["Dinh thự Pháp cổ đầu thế kỷ 20 giữa trung tâm Bạc Liêu", "Nội thất gỗ quý cẩn xà cừ, đồ cổ nhập từ Pháp", "Giai thoại ăn chơi khét tiếng của Công tử Bạc Liêu"],
    ["An early-20th-century French mansion in central Bac Lieu", "Precious mother-of-pearl-inlaid furniture and French antiques", "Colourful legends of the prince's notorious extravagance"],
    ["Французский особняк начала XX века в центре Бакльеу", "Ценная мебель с перламутром и французский антиквариат", "Яркие легенды о расточительности «принца Бакльеу»"],
    {"hours_vi": "Khoảng 8:00–17:00 hằng ngày.", "ticket_vi": "Vé vào khoảng 30.000–60.000 VND/người.", "duration_vi": "45–60 phút.", "best_time_vi": "Quanh năm; nên đi buổi sáng hoặc chiều.", "tips_vi": "Nên thuê thuyết minh hoặc nghe hướng dẫn để hiểu các giai thoại; kết hợp tham quan các điểm khác ở Bạc Liêu."},
    ["heritage", "history", "museum", "architecture"]))

# 7. Cánh đồng điện gió Bạc Liêu
NEW.append(rec(
    "canh-dong-dien-gio-bac-lieu", "Cánh đồng điện gió Bạc Liêu", "Bac Lieu Wind Farm", "Ветропарк Бакльеу",
    ["other"], 9.2280, 105.7900,
    "Xã Vĩnh Trạch Đông, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.4, "count": 4200, "source": "Google", "as_of": "2026-07"},
    "Du khách thích cánh đồng tuabin gió khổng lồ trên biển bãi bồi, được ví như 'trời Âu' giữa miền Tây. Nhiều người khen cảnh check-in độc đáo, đường cầu ra biển và hoàng hôn trên những cột quạt gió.",
    "Cánh đồng điện gió Bạc Liêu là nhà máy điện gió ven biển với hàng chục tuabin trắng khổng lồ dựng trên bãi bồi và mặt nước. Cảnh quan độc đáo, thường được ví như trời Âu, trở thành điểm 'check-in' nổi tiếng bậc nhất Bạc Liêu.",
    "The Bac Lieu Wind Farm is a coastal wind-power plant with dozens of giant white turbines rising from the mudflats and shallows. Its unusual scenery, often likened to Europe, has become one of Bac Lieu's most famous photo spots.",
    "Ветропарк Бакльеу — прибрежная ветроэлектростанция с десятками гигантских белых турбин, поднимающихся над илистыми отмелями и мелководьем. Необычный пейзаж, часто сравниваемый с Европой, стал одним из самых известных мест для фото в Бакльеу.",
    "Cánh đồng điện gió Bạc Liêu là một trong những nhà máy điện gió ven biển đầu tiên và lớn của Việt Nam, nằm ở xã Vĩnh Trạch Đông, cách trung tâm thành phố Bạc Liêu khoảng 20 km. Công trình gồm hàng chục cột tuabin gió khổng lồ màu trắng, mỗi cột cao khoảng 80 mét với ba cánh quạt dài, được dựng trên vùng bãi bồi ven biển và mặt nước. Nhìn từ xa, những trụ điện gió sừng sững vươn lên giữa trời nước mênh mông, cánh quạt quay chậm rãi, tạo nên khung cảnh vừa hùng vĩ vừa lạ mắt, được nhiều du khách ví von như khung cảnh trời Âu ngay giữa đồng bằng sông Cửu Long. Để ra gần khu vực tuabin, du khách đi theo con đường và cầu dẫn bằng bê tông chạy giữa bãi bồi, hai bên là rừng ngập mặn, tha hồ chụp ảnh với những cột quạt gió. Nơi đây đặc biệt đẹp vào lúc bình minh và hoàng hôn, khi ánh sáng vàng cam nhuộm lên nền trời và mặt nước. Là biểu tượng phát triển năng lượng sạch và điểm 'check-in' nổi tiếng, cánh đồng điện gió Bạc Liêu là điểm đến không thể bỏ qua khi tới vùng đất này, nay thuộc tỉnh Cà Mau.",
    "The Bac Lieu Wind Farm is one of Vietnam's first and largest coastal wind-power plants, in Vinh Trach Dong commune about 20 km from the centre of Bac Lieu city. It comprises dozens of giant white turbine towers, each around 80 metres tall with three long blades, set on the coastal mudflats and shallow water. From afar the towers rise sheer amid a vast expanse of sky and water, their blades turning slowly, making a scene at once grand and unusual that many travellers liken to Europe set right in the Mekong Delta. To get close to the turbines, visitors follow a concrete road and causeway across the mudflat, flanked by mangroves, with ample chances to photograph the towers. It is especially beautiful at dawn and dusk, when orange-gold light washes over the sky and water. As a symbol of clean-energy development and a famous photo spot, the Bac Lieu Wind Farm is an unmissable stop in this land, now part of Ca Mau province.",
    "Ветропарк Бакльеу — одна из первых и крупнейших прибрежных ветроэлектростанций Вьетнама, в общине Виньчать Донг примерно в 20 км от центра города Бакльеу. Он состоит из десятков гигантских белых башен-турбин, каждая около 80 метров высотой, с тремя длинными лопастями, установленных на прибрежных отмелях и мелководье. Издалека башни отвесно вздымаются среди огромного простора неба и воды, их лопасти медленно вращаются, создавая картину одновременно величественную и необычную, которую многие путешественники сравнивают с Европой посреди дельты Меконга. Чтобы приблизиться к турбинам, гости идут по бетонной дороге и дамбе через отмель, окаймлённой мангром, с массой возможностей сфотографировать башни. Особенно красиво здесь на рассвете и закате, когда оранжево-золотой свет заливает небо и воду. Как символ развития чистой энергии и знаменитое место для фото, ветропарк Бакльеу — обязательная остановка в этом краю, ныне входящем в провинцию Камау.",
    ["Hàng chục tuabin gió cao 80 m trên biển bãi bồi", "Cảnh 'trời Âu' giữa miền Tây, đẹp lúc bình minh, hoàng hôn", "Cầu dẫn ra biển giữa rừng ngập mặn để check-in"],
    ["Dozens of 80-metre turbines rising from the coastal mudflats", "A slice of 'Europe' in the Delta, lovely at dawn and dusk", "A causeway to the sea through mangroves for photos"],
    ["Десятки 80-метровых турбин над прибрежными отмелями", "Кусочек «Европы» в дельте, красиво на рассвете и закате", "Дамба к морю сквозь мангры для фото"],
    {"hours_vi": "Cả ngày; đẹp lúc bình minh và hoàng hôn.", "ticket_vi": "Vé tham quan/cầu dẫn khoảng 30.000–60.000 VND.", "duration_vi": "1–1,5 giờ.", "best_time_vi": "Mùa khô tháng 12–4; chiều muộn ngắm hoàng hôn.", "tips_vi": "Mang chống nắng, chống muỗi; đi cẩn thận trên cầu dẫn; hỏi lịch mở cửa khu tuabin."},
    ["scenic", "outdoor", "photo"]))

# 8. Chùa Xiêm Cán
NEW.append(rec(
    "chua-xiem-can", "Chùa Xiêm Cán", "Xiem Can Khmer Pagoda", "Кхмерская пагода Сьемкан",
    ["church"], 9.2380, 105.8050,
    "Xã Vĩnh Trạch Đông, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.5, "count": 2800, "source": "Google", "as_of": "2026-07"},
    "Du khách ấn tượng với ngôi chùa Khmer lộng lẫy, chạm khắc tinh xảo, màu sắc rực rỡ. Nhiều người khen kiến trúc Angkor độc đáo, khuôn viên rộng và không gian văn hóa Khmer đặc sắc.",
    "Chùa Xiêm Cán là một trong những ngôi chùa Khmer lớn và đẹp nhất Nam Bộ, nằm gần biển Bạc Liêu. Chùa nổi bật với kiến trúc Angkor rực rỡ, mái tháp nhọn, phù điêu và hoa văn chạm khắc tinh xảo trong khuôn viên rộng rợp bóng cây.",
    "Xiem Can Pagoda is one of the largest and most beautiful Khmer temples in southern Vietnam, near the Bac Lieu coast. It stands out for its vivid Angkor-style architecture, pointed spires, reliefs and finely carved motifs set in spacious, tree-shaded grounds.",
    "Пагода Сьемкан — один из крупнейших и красивейших кхмерских храмов юга Вьетнама, близ побережья Бакльеу. Она выделяется яркой архитектурой в стиле Ангкора, остроконечными шпилями, рельефами и тонко вырезанными узорами в просторном, тенистом дворе.",
    "Chùa Xiêm Cán tọa lạc tại xã Vĩnh Trạch Đông, cách trung tâm thành phố Bạc Liêu khoảng 10 km về phía biển, là một trong những ngôi chùa Khmer cổ, lớn và lộng lẫy bậc nhất khu vực Nam Bộ. Chùa được xây dựng từ cuối thế kỷ 19 và trải qua nhiều lần trùng tu, mang đậm phong cách kiến trúc Angkor của người Khmer với cổng chùa, chính điện, tháp và các công trình phụ được trang trí công phu. Nổi bật là những mái tháp nhọn vươn cao, các bức phù điêu, tượng thần, chằn (yak) và hoa văn chạm khắc tỉ mỉ, sơn son thếp vàng rực rỡ dưới nắng. Khuôn viên chùa rộng, rợp bóng cây thốt nốt và sao dầu, tạo không gian thanh tịnh, mát mẻ. Đây không chỉ là nơi tu hành, sinh hoạt tôn giáo của cộng đồng người Khmer địa phương mà còn là trung tâm gìn giữ, truyền dạy chữ viết, kinh sách và các lễ hội truyền thống Khmer như Chôl Chnăm Thmây, Sen Đôn Ta, Óc Om Bóc. Với vẻ đẹp kiến trúc độc đáo và giá trị văn hóa sâu sắc, chùa Xiêm Cán là điểm đến tâm linh, văn hóa tiêu biểu của tỉnh Cà Mau sau sáp nhập.",
    "Xiem Can Pagoda stands in Vinh Trach Dong commune, about 10 km from the centre of Bac Lieu city towards the coast, and is one of the oldest, largest and most resplendent Khmer temples in southern Vietnam. Built in the late 19th century and restored many times, it strongly reflects the Angkor architecture of the Khmer, with an ornate gateway, main hall, spires and outbuildings all richly decorated. It is notable for its tall pointed spires, reliefs, statues of deities and yaks (giants) and painstakingly carved motifs, gilded and painted to glow in the sun. The spacious grounds, shaded by sugar palms and hopea trees, create a serene, cool space. It is not only a place of worship and religious life for the local Khmer community but also a centre for preserving and teaching Khmer script, scriptures and traditional festivals such as Chol Chnam Thmay, Sen Dolta and Ok Om Bok. With its unique architectural beauty and deep cultural value, Xiem Can Pagoda is a leading spiritual and cultural destination in Ca Mau province after the merger.",
    "Пагода Сьемкан находится в общине Виньчать Донг, примерно в 10 км от центра города Бакльеу в сторону побережья, и является одним из старейших, крупнейших и самых великолепных кхмерских храмов юга Вьетнама. Построенная в конце XIX века и многократно реставрировавшаяся, она ярко отражает ангкорскую архитектуру кхмеров: богато украшенные ворота, главный зал, шпили и подсобные постройки. Она примечательна высокими остроконечными шпилями, рельефами, статуями божеств и якшей (великанов) и кропотливо вырезанными узорами, позолоченными и расписанными так, что они сияют на солнце. Просторный двор в тени пальм тхот-нот и деревьев хопеа создаёт умиротворённое, прохладное пространство. Это не только место поклонения и религиозной жизни местной кхмерской общины, но и центр сохранения и обучения кхмерской письменности, священных текстов и традиционных праздников — Чол Чнам Тхмай, Сен Донта и Ок Ом Бок. Уникальной архитектурной красотой и глубокой культурной ценностью пагода Сьемкан — ведущее духовное и культурное направление провинции Камау после слияния.",
    ["Chùa Khmer lớn, lộng lẫy bậc nhất Nam Bộ, kiến trúc Angkor", "Mái tháp nhọn, phù điêu, hoa văn chạm khắc sơn son thếp vàng", "Trung tâm văn hóa Khmer, gìn giữ lễ hội truyền thống"],
    ["One of the grandest Khmer temples in the south, Angkor-style", "Pointed spires, reliefs and gilded, finely carved motifs", "A Khmer cultural centre keeping traditional festivals"],
    ["Один из величественнейших кхмерских храмов юга в стиле Ангкора", "Остроконечные шпили, рельефы и позолоченные узоры", "Кхмерский культурный центр, хранящий традиционные праздники"],
    {"hours_vi": "Khoảng 6:00–18:00 hằng ngày.", "ticket_vi": "Miễn phí (có hòm công đức).", "duration_vi": "45–60 phút.", "best_time_vi": "Sáng hoặc chiều mát; dịp lễ hội Khmer rất đặc sắc.", "tips_vi": "Ăn mặc kín đáo, lịch sự; giữ yên tĩnh; xin phép khi chụp ảnh sư sãi và nghi lễ."},
    ["temple", "culture", "khmer", "architecture"]))

# 9. Khu lưu niệm nhạc sĩ Cao Văn Lầu
NEW.append(rec(
    "khu-luu-niem-cao-van-lau", "Khu lưu niệm nhạc sĩ Cao Văn Lầu", "Cao Van Lau Memorial", "Мемориал музыканта Као Ван Лау",
    ["monument", "museum"], 9.2830, 105.7370,
    "Phường 2, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.4, "count": 1500, "source": "Google", "as_of": "2026-07"},
    "Du khách yêu thích khu tưởng niệm cha đẻ bản 'Dạ cổ hoài lang', cái nôi của đờn ca tài tử và cải lương. Nhiều người khen không gian trang trọng, biểu tượng cây đờn kìm và giá trị văn hóa nghệ thuật.",
    "Khu lưu niệm nhạc sĩ Cao Văn Lầu tôn vinh người sáng tác bản 'Dạ cổ hoài lang' – nền tảng của nghệ thuật cải lương và đờn ca tài tử Nam Bộ. Khu gồm mộ nhạc sĩ, tượng đài, nhà trưng bày và biểu tượng cây đờn kìm cách điệu.",
    "The Cao Van Lau Memorial honours the composer of 'Da co hoai lang', the foundation of cai luong theatre and southern don ca tai tu music. It includes the musician's tomb, a monument, an exhibition hall and a stylised moon-lute emblem.",
    "Мемориал Као Ван Лау чтит автора пьесы «Зако хоай ланг» — основы театра кайлыонг и южной музыки дон-ка-тай-ты. В него входят могила музыканта, монумент, выставочный зал и стилизованная эмблема лунной лютни.",
    "Khu lưu niệm nhạc sĩ Cao Văn Lầu tọa lạc tại phường 2, thành phố Bạc Liêu, là nơi tôn vinh và tưởng nhớ nhạc sĩ Cao Văn Lầu (1892–1976) – tác giả của bản 'Dạ cổ hoài lang' bất hủ. Ra đời vào khoảng năm 1919, bản 'Dạ cổ hoài lang' được xem là viên gạch nền tảng, khởi nguồn cho sự phát triển của bản vọng cổ và nghệ thuật sân khấu cải lương, đờn ca tài tử Nam Bộ – di sản văn hóa phi vật thể đã được UNESCO ghi danh. Khu lưu niệm được xây dựng khang trang trên khuôn viên rộng, gồm khu mộ của nhạc sĩ và gia đình, tượng đài, nhà trưng bày lưu giữ hình ảnh, hiện vật, nhạc cụ và tư liệu về cuộc đời, sự nghiệp của ông cùng lịch sử đờn ca tài tử. Điểm nhấn kiến trúc là biểu tượng cây đờn kìm (nguyệt cầm) cách điệu vươn cao – nhạc cụ tiêu biểu của đờn ca tài tử, cùng đài nghinh phong và các hạng mục trưng bày ngoài trời. Đến đây, du khách không chỉ tìm hiểu về một danh nhân âm nhạc mà còn cảm nhận sâu sắc về cái nôi của đờn ca tài tử, cải lương. Đây là điểm đến văn hóa, nghệ thuật tiêu biểu và niềm tự hào của vùng đất Bạc Liêu, nay thuộc tỉnh Cà Mau.",
    "The Cao Van Lau Memorial stands in ward 2 of Bac Lieu city, honouring and remembering the musician Cao Van Lau (1892–1976), composer of the immortal piece 'Da co hoai lang'. Created around 1919, 'Da co hoai lang' is regarded as the founding cornerstone of the vong co song and of cai luong theatre and southern don ca tai tu music — an intangible cultural heritage recognised by UNESCO. The memorial is handsomely built on spacious grounds, comprising the tombs of the musician and his family, a monument and an exhibition hall keeping images, objects, instruments and documents about his life and career and the history of don ca tai tu. Its architectural highlight is a tall stylised emblem of the moon lute (dan kim), the signature instrument of don ca tai tu, along with a wind pavilion and outdoor displays. Here visitors not only learn about a great figure of music but also feel deeply the cradle of don ca tai tu and cai luong. It is a leading cultural and artistic destination and a source of pride for the land of Bac Lieu, now part of Ca Mau province.",
    "Мемориал Као Ван Лау находится в квартале 2 города Бакльеу и чтит память музыканта Као Ван Лау (1892–1976), автора бессмертной пьесы «Зако хоай ланг». Созданная около 1919 года, «Зако хоай ланг» считается краеугольным камнем песни вонгко, а также театра кайлыонг и южной музыки дон-ка-тай-ты — нематериального культурного наследия, признанного ЮНЕСКО. Мемориал красиво выстроен на просторной территории и включает могилы музыканта и его семьи, монумент и выставочный зал с изображениями, предметами, инструментами и документами о его жизни и творчестве и об истории дон-ка-тай-ты. Архитектурная доминанта — высокая стилизованная эмблема лунной лютни (данким), характерного инструмента дон-ка-тай-ты, а также павильон ветра и уличные экспозиции. Здесь гости не только узнают о великой фигуре музыки, но и глубоко ощущают колыбель дон-ка-тай-ты и кайлыонг. Это ведущее культурное и художественное направление и предмет гордости края Бакльеу, ныне входящего в провинцию Камау.",
    ["Tôn vinh tác giả 'Dạ cổ hoài lang', khởi nguồn vọng cổ, cải lương", "Mộ nhạc sĩ, tượng đài, nhà trưng bày nhạc cụ và tư liệu", "Biểu tượng cây đờn kìm cách điệu, cái nôi đờn ca tài tử"],
    ["Honours the composer of 'Da co hoai lang', root of vong co and cai luong", "The musician's tomb, a monument and an instrument-and-document hall", "A stylised moon-lute emblem, the cradle of don ca tai tu"],
    ["Чтит автора «Зако хоай ланг», истока вонгко и кайлыонга", "Могила музыканта, монумент и зал инструментов и документов", "Стилизованная эмблема лунной лютни, колыбель дон-ка-тай-ты"],
    {"hours_vi": "Khoảng 7:00–17:00 hằng ngày.", "ticket_vi": "Miễn phí hoặc vé nhỏ.", "duration_vi": "30–45 phút.", "best_time_vi": "Quanh năm; dịp lễ hội Dạ cổ hoài lang càng đặc sắc.", "tips_vi": "Kết hợp tham quan Nhà Công tử Bạc Liêu gần đó; tìm hiểu trước về đờn ca tài tử để thêm ý nghĩa."},
    ["culture", "music", "heritage", "museum"]))

# 10. Quán Âm Phật Đài
NEW.append(rec(
    "quan-am-phat-dai-bac-lieu", "Quán Âm Phật Đài (Mẹ Nam Hải)", "Quan Am Buddhist Statue (Mother of the South Sea)", "Статуя Гуаньинь (Мать Южного моря)",
    ["church", "monument"], 9.2560, 105.7620,
    "Phường Nhà Mát, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.6, "count": 3900, "source": "Google", "as_of": "2026-07"},
    "Du khách thành kính viếng tượng Phật Bà Quán Âm cao lớn hướng ra biển, nơi hành hương nổi tiếng của miền Tây. Nhiều người khen không gian trang nghiêm, gió biển và lễ hội Quán Âm đông đúc.",
    "Quán Âm Phật Đài, còn gọi là Mẹ Nam Hải, là khu hành hương với tượng Phật Bà Quán Thế Âm cao khoảng 11 mét đứng hướng ra biển ở phường Nhà Mát. Đây là một trong những điểm tâm linh nổi tiếng và linh thiêng bậc nhất của Bạc Liêu.",
    "Quan Am Buddhist Statue, also called the Mother of the South Sea, is a pilgrimage site with an Avalokitesvara statue about 11 metres tall facing the sea in Nha Mat ward. It is one of the most famous and revered spiritual places in Bac Lieu.",
    "Статуя Гуаньинь, называемая также Матерью Южного моря, — место паломничества со статуей Авалокитешвары около 11 метров высотой, обращённой к морю, в квартале Нямат. Это одно из самых известных и почитаемых духовных мест Бакльеу.",
    "Quán Âm Phật Đài, người dân quen gọi là Mẹ Nam Hải, tọa lạc tại phường Nhà Mát ven biển thành phố Bạc Liêu, là một trong những điểm hành hương tâm linh nổi tiếng và linh thiêng nhất của vùng đất này. Trung tâm của khu là pho tượng Phật Bà Quán Thế Âm Bồ Tát cao khoảng 11 mét, đứng uy nghi trên đài sen, hướng mặt ra biển Đông như dõi theo, che chở cho ngư dân ra khơi và người dân trong vùng. Trước đây, tượng nằm sát mép biển, nhưng do quá trình bồi lắng phù sa, ngày nay vị trí tượng đã lùi sâu vào đất liền hơn so với bờ nước. Khuôn viên khu Phật Đài rộng rãi, thoáng đãng, ngày càng được mở rộng, xây dựng thêm nhiều công trình như cổng tam quan, điện thờ, các tượng Phật, La Hán và khu vực cho khách hành hương. Hằng năm, vào dịp lễ vía Quán Âm (khoảng tháng 3 âm lịch), nơi đây đón hàng vạn tăng ni, phật tử và du khách khắp nơi về dâng hương, cầu an, tạo nên không khí lễ hội trang nghiêm mà nhộn nhịp. Với vị trí ven biển lộng gió, không gian thanh tịnh và ý nghĩa tâm linh sâu sắc, Quán Âm Phật Đài là điểm đến quan trọng của tỉnh Cà Mau sau sáp nhập.",
    "Quan Am Buddhist Statue, commonly called the Mother of the South Sea, stands in the coastal Nha Mat ward of Bac Lieu city and is one of the most famous and sacred pilgrimage sites in this land. At its heart is a statue of the Bodhisattva Avalokitesvara about 11 metres tall, standing majestically on a lotus dais and facing the East Sea as if watching over and protecting fishermen who put out to sea and the people of the region. The statue once stood at the water's edge, but as silt has built up the coastline, it now lies further inland from the shore. The grounds are spacious and airy and have been steadily enlarged with a triple gate, worship halls, statues of Buddhas and arhats and areas for pilgrims. Each year, at the festival of Quan Am around the third lunar month, the site welcomes tens of thousands of monks, nuns, Buddhists and visitors from everywhere who come to offer incense and pray for peace, creating a solemn yet lively festive atmosphere. With its breezy coastal setting, serene space and deep spiritual meaning, the Quan Am Buddhist Statue is an important destination in Ca Mau province after the merger.",
    "Статуя Гуаньинь, которую в народе называют Матерью Южного моря, стоит в прибрежном квартале Нямат города Бакльеу и является одним из самых известных и священных мест паломничества этого края. В её центре — статуя бодхисаттвы Авалокитешвары около 11 метров высотой, величественно стоящая на лотосовом постаменте и обращённая к Восточному морю, словно оберегая рыбаков, выходящих в море, и жителей края. Прежде статуя стояла у самой кромки воды, но по мере намыва ила берег отступил, и теперь она находится дальше от воды. Территория просторная и открытая, постепенно расширялась и дополнялась тройными воротами, молитвенными залами, статуями будд и архатов и зонами для паломников. Ежегодно на празднике Гуаньинь около третьего лунного месяца сюда стекаются десятки тысяч монахов, монахинь, буддистов и гостей отовсюду, чтобы возжечь благовония и молиться о мире, создавая торжественную, но оживлённую праздничную атмосферу. Ветреным приморским расположением, умиротворённым пространством и глубоким духовным смыслом статуя Гуаньинь — важное направление провинции Камау после слияния.",
    ["Tượng Phật Bà Quán Âm cao ~11 m hướng ra biển Đông", "Điểm hành hương linh thiêng bậc nhất Bạc Liêu", "Lễ vía Quán Âm tháng 3 âm lịch đón hàng vạn người"],
    ["An ~11 m Avalokitesvara statue facing the East Sea", "One of Bac Lieu's most sacred pilgrimage sites", "The Quan Am festival in the third lunar month draws huge crowds"],
    ["Статуя Гуаньинь около 11 м, обращённая к Восточному морю", "Одно из самых священных мест паломничества Бакльеу", "Праздник Гуаньинь в третьем лунном месяце собирает толпы"],
    {"hours_vi": "Khoảng 6:00–18:00 hằng ngày.", "ticket_vi": "Miễn phí (có hòm công đức).", "duration_vi": "30–45 phút.", "best_time_vi": "Sáng hoặc chiều mát; lễ vía Quán Âm tháng 3 âm lịch.", "tips_vi": "Ăn mặc kín đáo; giữ trang nghiêm; dịp lễ rất đông nên giữ tư trang cẩn thận."},
    ["temple", "pilgrimage", "sea", "monument"]))

# 11. Nhà thờ Tắc Sậy
NEW.append(rec(
    "nha-tho-tac-say", "Nhà thờ Tắc Sậy (Cha Diệp)", "Tac Say Church (Father Diep)", "Церковь Тактьяй (отец Зьеп)",
    ["church"], 9.1500, 105.4500,
    "Xã Tân Phong, thị xã Giá Rai, tỉnh Cà Mau",
    {"value": 4.6, "count": 4100, "source": "Google", "as_of": "2026-07"},
    "Du khách và giáo dân từ khắp nơi hành hương đến nhà thờ gắn với linh mục Trương Bửu Diệp. Nhiều người khen kiến trúc bề thế ba tầng, không gian trang nghiêm và lượng khách hành hương đông quanh năm.",
    "Nhà thờ Tắc Sậy, gắn với linh mục Phanxicô Trương Bửu Diệp, là một trung tâm hành hương Công giáo nổi tiếng ở thị xã Giá Rai. Nhà thờ có kiến trúc bề thế nhiều tầng, phần mộ và khu tưởng niệm Cha Diệp thu hút đông đảo khách thập phương.",
    "Tac Say Church, associated with the priest Francis Truong Buu Diep, is a famous Catholic pilgrimage centre in Gia Rai town. It has an imposing multi-storey design, with the tomb and memorial of Father Diep drawing crowds of pilgrims.",
    "Церковь Тактьяй, связанная со священником Франциском Чыонг Быу Зьепом, — известный центр католического паломничества в городе Зярай. У неё внушительная многоярусная архитектура; могила и мемориал отца Зьепа привлекают толпы паломников.",
    "Nhà thờ Tắc Sậy, còn được biết đến với tên Nhà thờ Cha Diệp, tọa lạc tại xã Tân Phong, thị xã Giá Rai, là một trong những trung tâm hành hương Công giáo lớn và nổi tiếng nhất khu vực Đồng bằng sông Cửu Long. Nhà thờ gắn liền với linh mục Phanxicô Xaviê Trương Bửu Diệp (1897–1946), người từng coi sóc họ đạo Tắc Sậy và được nhiều tín hữu tôn kính vì lòng bác ái, tận tụy với giáo dân. Sau khi ông qua đời, phần mộ và nơi tưởng niệm ông trở thành điểm hành hương thu hút không chỉ người Công giáo mà cả nhiều người ngoài Công giáo đến cầu nguyện, tạ ơn. Ngôi nhà thờ hiện nay được xây dựng khang trang, bề thế với kiến trúc nhiều tầng độc đáo, mái ngói cong, không gian thánh đường rộng lớn và khu nhà mộ Cha Diệp được trang trí trang nghiêm. Quanh năm, đặc biệt vào các dịp lễ và ngày giỗ Cha Diệp, nơi đây đón hàng vạn lượt khách hành hương từ khắp các tỉnh thành đổ về, tạo nên khung cảnh tấp nập, sốt sắng. Với ý nghĩa tâm linh sâu sắc và kiến trúc ấn tượng, nhà thờ Tắc Sậy là điểm đến tôn giáo tiêu biểu của tỉnh Cà Mau sau sáp nhập.",
    "Tac Say Church, also known as Father Diep's Church, stands in Tan Phong commune, Gia Rai town, and is one of the largest and most famous Catholic pilgrimage centres in the Mekong Delta. The church is bound to the priest Francis Xavier Truong Buu Diep (1897–1946), who once served the Tac Say parish and is revered by many faithful for his charity and devotion to his people. After his death, his tomb and memorial became a pilgrimage site drawing not only Catholics but also many non-Catholics who come to pray and give thanks. The present church is handsomely and imposingly built, with a distinctive multi-storey design, curved tiled roofs, a vast sanctuary and a solemnly decorated tomb hall for Father Diep. All year round, and especially on feast days and the anniversary of his death, the site welcomes tens of thousands of pilgrims from provinces across the country, creating a bustling, fervent scene. With its deep spiritual meaning and striking architecture, Tac Say Church is a leading religious destination in Ca Mau province after the merger.",
    "Церковь Тактьяй, известная также как церковь отца Зьепа, стоит в общине Танфонг города Зярай и является одним из крупнейших и известнейших центров католического паломничества дельты Меконга. Церковь связана со священником Франциском Ксаверием Чыонг Быу Зьепом (1897–1946), который некогда служил в приходе Тактьяй и почитается многими верующими за милосердие и преданность своей пастве. После его смерти его могила и мемориал стали местом паломничества, привлекающим не только католиков, но и многих некатоликов, приходящих молиться и благодарить. Нынешняя церковь красиво и внушительно построена, с самобытной многоярусной архитектурой, изогнутыми черепичными крышами, огромным залом и торжественно украшенной усыпальницей отца Зьепа. Круглый год, особенно в праздники и в годовщину его смерти, сюда приходят десятки тысяч паломников из провинций всей страны, создавая оживлённую, ревностную картину. Глубоким духовным смыслом и эффектной архитектурой церковь Тактьяй — ведущее религиозное направление провинции Камау после слияния.",
    ["Trung tâm hành hương Công giáo lớn gắn với Cha Trương Bửu Diệp", "Kiến trúc nhà thờ nhiều tầng bề thế, khu mộ Cha Diệp trang nghiêm", "Đông khách hành hương quanh năm, cả người ngoài Công giáo"],
    ["A major Catholic pilgrimage centre tied to Father Truong Buu Diep", "Imposing multi-storey church with Father Diep's solemn tomb hall", "Crowded with pilgrims all year, including non-Catholics"],
    ["Крупный центр католического паломничества, связанный с отцом Чыонг Быу Зьепом", "Внушительная многоярусная церковь с усыпальницей отца Зьепа", "Толпы паломников круглый год, включая некатоликов"],
    {"hours_vi": "Mở cửa cả ngày cho khách hành hương.", "ticket_vi": "Miễn phí.", "duration_vi": "30–45 phút.", "best_time_vi": "Quanh năm; dịp giỗ Cha Diệp (khoảng 11–12/3) rất đông.", "tips_vi": "Ăn mặc lịch sự, trang nghiêm; giữ trật tự; dịp lễ đông nên đề phòng móc túi."},
    ["church", "pilgrimage", "architecture"]))

# 12. Vườn chim Bạc Liêu
NEW.append(rec(
    "vuon-chim-bac-lieu", "Vườn chim Bạc Liêu", "Bac Lieu Bird Sanctuary", "Птичий заказник Бакльеу",
    ["park_garden"], 9.2680, 105.7500,
    "Xã Hiệp Thành, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.1, "count": 620, "source": "Google", "as_of": "2026-07"},
    "Du khách thích khu rừng ngập mặn ngay gần thành phố với hàng nghìn con chim, cò, vạc về trú ngụ. Nhiều người khen đi bộ trên đường mòn, đài quan sát ngắm chim và không khí trong lành.",
    "Vườn chim Bạc Liêu là khu bảo tồn thiên nhiên rừng ngập mặn nằm gần trung tâm thành phố, nơi trú ngụ của hàng nghìn cá thể chim thuộc nhiều loài. Du khách có thể đi theo đường mòn, lên đài quan sát để ngắm chim, cò, vạc và tìm hiểu hệ sinh thái.",
    "The Bac Lieu Bird Sanctuary is a mangrove nature reserve near the city centre, home to thousands of birds of many species. Visitors can follow trails and climb observation towers to watch storks, herons and night herons and learn about the ecosystem.",
    "Птичий заказник Бакльеу — мангровый природный резерват близ центра города, приют тысяч птиц многих видов. Гости могут идти по тропам и подниматься на смотровые вышки, чтобы наблюдать аистов, цапель и кваков и узнавать об экосистеме.",
    "Vườn chim Bạc Liêu là một khu bảo tồn thiên nhiên đặc biệt nằm ở xã Hiệp Thành, chỉ cách trung tâm thành phố Bạc Liêu khoảng 5 km, là một trong số ít sân chim nằm gần đô thị ở Việt Nam. Khu vực rộng hàng trăm héc-ta với hệ sinh thái rừng ngập mặn và rừng tràm, tạo môi trường sống lý tưởng cho hàng nghìn, thậm chí hàng chục nghìn cá thể chim thuộc nhiều loài như cò, vạc, diệc, cồng cộc, quắm, le le, trong đó có những loài quý hiếm cần được bảo vệ. Vào mùa sinh sản (thường từ khoảng tháng 5 đến tháng 10), chim kéo về làm tổ đông đúc, đậu trắng cả những tán cây, tạo nên khung cảnh thiên nhiên sống động. Du khách tham quan vườn chim đi theo các con đường mòn và cầu gỗ len lỏi giữa rừng, dừng chân ở đài quan sát để lặng ngắm đàn chim bay lượn, kiếm ăn, chăm con, đồng thời hít thở bầu không khí trong lành, mát mẻ. Bên cạnh giá trị du lịch, vườn chim còn đóng vai trò quan trọng trong nghiên cứu, bảo tồn đa dạng sinh học của vùng đồng bằng ven biển. Đây là điểm đến sinh thái hấp dẫn, gần gũi của tỉnh Cà Mau sau sáp nhập.",
    "The Bac Lieu Bird Sanctuary is a special nature reserve in Hiep Thanh commune, only about 5 km from the centre of Bac Lieu city, one of the few bird sanctuaries near a town in Vietnam. Covering hundreds of hectares of mangrove and melaleuca forest, it provides an ideal habitat for thousands, even tens of thousands, of birds of many species — storks, night herons, herons, cormorants, ibises and teal — including rare species in need of protection. In the breeding season, usually around May to October, birds gather in great numbers to nest, whitening the tree canopies and creating a vivid natural scene. Visitors follow trails and wooden walkways through the forest and stop at observation towers to quietly watch the birds wheel, feed and tend their young, while breathing the fresh, cool air. Besides its tourism value, the sanctuary plays an important role in research and in conserving the biodiversity of the coastal delta. It is an appealing, easily reached eco-destination in Ca Mau province after the merger.",
    "Птичий заказник Бакльеу — особый природный резерват в общине Хьептхань, всего примерно в 5 км от центра города Бакльеу, один из немногих птичьих заказников близ города во Вьетнаме. Занимая сотни гектаров мангрового и мелалеукового леса, он создаёт идеальную среду обитания для тысяч и даже десятков тысяч птиц многих видов — аистов, кваков, цапель, бакланов, ибисов и чирков, включая редкие виды, нуждающиеся в охране. В сезон размножения, обычно с мая по октябрь, птицы массово слетаются гнездиться, добела покрывая кроны деревьев и создавая живую природную картину. Гости идут по тропам и деревянным настилам сквозь лес и останавливаются у смотровых вышек, чтобы тихо наблюдать, как птицы кружат, кормятся и заботятся о птенцах, вдыхая свежий прохладный воздух. Помимо туристической ценности, заказник играет важную роль в исследованиях и сохранении биоразнообразия прибрежной дельты. Это привлекательное, легкодоступное экологическое направление провинции Камау после слияния.",
    ["Sân chim rừng ngập mặn ngay gần trung tâm TP. Bạc Liêu", "Hàng nghìn chim cò, vạc, diệc về trú ngụ, làm tổ", "Đường mòn, đài quan sát ngắm chim, không khí trong lành"],
    ["A mangrove bird sanctuary just near central Bac Lieu", "Thousands of storks, night herons and herons roost and nest", "Trails and observation towers for birdwatching in fresh air"],
    ["Мангровый птичий заказник у центра Бакльеу", "Тысячи аистов, кваков и цапель гнездятся здесь", "Тропы и вышки для наблюдения за птицами на свежем воздухе"],
    {"hours_vi": "Khoảng 7:00–17:00 hằng ngày.", "ticket_vi": "Vé vào khoảng 20.000–40.000 VND/người.", "duration_vi": "1–2 giờ.", "best_time_vi": "Mùa sinh sản tháng 5–10; sáng sớm hoặc chiều chim hoạt động nhiều.", "tips_vi": "Mang chống muỗi, ống nhòm; đi nhẹ, nói khẽ để không làm chim hoảng; giày phù hợp đường rừng."},
    ["nature", "wildlife", "eco", "birdwatching"]))

# 13. Tháp cổ Vĩnh Hưng
NEW.append(rec(
    "thap-co-vinh-hung", "Tháp cổ Vĩnh Hưng", "Vinh Hung Ancient Tower", "Древняя башня Виньхынг",
    ["monument"], 9.3830, 105.6280,
    "Xã Vĩnh Hưng A, huyện Vĩnh Lợi, tỉnh Cà Mau",
    {"value": 4.2, "count": 380, "source": "Google", "as_of": "2026-07"},
    "Du khách thích ngọn tháp gạch cổ nghìn năm tuổi thuộc văn hóa Óc Eo, di tích hiếm hoi còn lại ở miền Tây. Nhiều người khen giá trị khảo cổ, không gian yên tĩnh và các hiện vật trưng bày.",
    "Tháp cổ Vĩnh Hưng là ngọn tháp gạch cổ thuộc nền văn hóa Óc Eo, có niên đại khoảng hơn một nghìn năm, nằm ở huyện Vĩnh Lợi. Đây là một trong số rất ít kiến trúc tháp cổ còn tồn tại ở Đồng bằng sông Cửu Long, mang giá trị khảo cổ và lịch sử đặc biệt.",
    "The Vinh Hung Ancient Tower is an old brick tower of the Oc Eo culture, dating back more than a thousand years, in Vinh Loi district. It is one of very few surviving ancient tower structures in the Mekong Delta, with special archaeological and historical value.",
    "Древняя башня Виньхынг — старинная кирпичная башня культуры Окэо возрастом более тысячи лет, в уезде Виньлой. Это одно из очень немногих сохранившихся древних башенных сооружений дельты Меконга, обладающее особой археологической и исторической ценностью.",
    "Tháp cổ Vĩnh Hưng tọa lạc tại xã Vĩnh Hưng A, huyện Vĩnh Lợi, là một di tích kiến trúc cổ độc đáo và quý hiếm của vùng Đồng bằng sông Cửu Long. Ngọn tháp được xây dựng bằng gạch theo phong cách kiến trúc gắn với nền văn hóa Óc Eo – hậu Óc Eo, có niên đại được xác định khoảng hơn một nghìn năm, thuộc vào loại cổ nhất còn tồn tại ở khu vực Nam Bộ. Tháp có bình đồ gần vuông, tường xây bằng những viên gạch lớn xếp khít, cao khoảng hơn 8 mét, trải qua thời gian dài vẫn giữ được phần lớn cấu trúc dù đã nhuốm màu rêu phong cổ kính. Qua các đợt khai quật khảo cổ, người ta đã tìm thấy tại đây và khu vực xung quanh nhiều hiện vật giá trị như tượng thần, linh vật, đồ trang sức, mảnh gốm bằng đá, đồng và vàng, phản ánh đời sống tôn giáo, văn hóa của cư dân cổ. Ngày nay, di tích được bảo vệ, có nhà trưng bày giới thiệu các hiện vật và thông tin khảo cổ để du khách tham quan, tìm hiểu. Nằm trong không gian yên tĩnh của làng quê, tháp cổ Vĩnh Hưng là điểm đến giàu giá trị lịch sử, khảo cổ của tỉnh Cà Mau sau sáp nhập.",
    "The Vinh Hung Ancient Tower stands in Vinh Hung A commune, Vinh Loi district, a unique and rare ancient architectural relic of the Mekong Delta. The tower is built of brick in a style linked to the Oc Eo and post-Oc Eo culture, dated to more than a thousand years ago and among the oldest surviving structures in southern Vietnam. Nearly square in plan, with walls of large bricks laid tightly together and standing more than 8 metres high, it has kept much of its structure through the ages despite the mossy patina of time. Archaeological excavations here and nearby have uncovered many valuable objects — statues of deities, sacred figures, jewellery and fragments of stone, bronze and gold artefacts — reflecting the religious and cultural life of the ancient inhabitants. Today the relic is protected, with an exhibition house presenting the objects and archaeological information for visitors to explore. Set in the quiet space of the countryside, the Vinh Hung Ancient Tower is a destination rich in historical and archaeological value in Ca Mau province after the merger.",
    "Древняя башня Виньхынг стоит в общине Виньхынг А уезда Виньлой — уникальный и редкий древний архитектурный памятник дельты Меконга. Башня сложена из кирпича в стиле, связанном с культурой Окэо и пост-Окэо, датируется возрастом более тысячи лет и относится к числу древнейших сохранившихся сооружений юга Вьетнама. Почти квадратная в плане, со стенами из плотно уложенного крупного кирпича и высотой более 8 метров, она сохранила большую часть структуры сквозь века, несмотря на мшистую патину времени. Археологические раскопки здесь и поблизости открыли множество ценных предметов — статуи божеств, священные фигуры, украшения и фрагменты каменных, бронзовых и золотых изделий, отражающие религиозную и культурную жизнь древних жителей. Сегодня памятник охраняется, при нём есть выставочный дом с предметами и археологической информацией для посетителей. Расположенная в тихом пространстве сельской местности, древняя башня Виньхынг — направление, богатое исторической и археологической ценностью, в провинции Камау после слияния.",
    ["Tháp gạch cổ hơn nghìn năm thuộc văn hóa Óc Eo", "Một trong số rất ít kiến trúc tháp cổ còn lại ở miền Tây", "Nhà trưng bày hiện vật khảo cổ: tượng thần, đồ đá, đồng, vàng"],
    ["A thousand-year-old brick tower of the Oc Eo culture", "One of very few surviving ancient towers in the Delta", "Exhibition of archaeological finds: deity statues, stone, bronze, gold"],
    ["Тысячелетняя кирпичная башня культуры Окэо", "Одна из немногих сохранившихся древних башен дельты", "Выставка находок: статуи божеств, камень, бронза, золото"],
    {"hours_vi": "Khoảng 7:00–17:00 hằng ngày.", "ticket_vi": "Miễn phí hoặc vé nhỏ.", "duration_vi": "30–45 phút.", "best_time_vi": "Quanh năm; nên đi ban ngày.", "tips_vi": "Không sờ, trèo lên tháp để bảo vệ di tích; kết hợp tìm hiểu văn hóa Óc Eo ở nhà trưng bày."},
    ["history", "archaeology", "heritage", "monument"]))

# 14. Khu du lịch Nhà Mát (biển Bạc Liêu)
NEW.append(rec(
    "khu-du-lich-nha-mat", "Khu du lịch Nhà Mát (biển Bạc Liêu)", "Nha Mat Tourist Area (Bac Lieu Beach)", "Туристическая зона Нямат (пляж Бакльеу)",
    ["other", "park_garden"], 9.2450, 105.7750,
    "Phường Nhà Mát, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 3.9, "count": 1300, "source": "Google", "as_of": "2026-07"},
    "Du khách thích khu du lịch biển gần thành phố với công viên nước, khu vui chơi và bãi biển bãi bồi. Nhiều người thấy tiện cho gia đình, gần Quán Âm Phật Đài và cánh đồng điện gió.",
    "Khu du lịch Nhà Mát là khu vui chơi, giải trí ven biển ở phường Nhà Mát, thành phố Bạc Liêu. Nơi đây có công viên nước, khu trò chơi, khu tâm linh và bãi biển bãi bồi, là điểm đến quen thuộc của người dân và du khách trong vùng.",
    "Nha Mat Tourist Area is a seaside leisure complex in Nha Mat ward, Bac Lieu city. It has a water park, amusement zones, a spiritual area and a mudflat beach, and is a familiar destination for locals and regional visitors.",
    "Туристическая зона Нямат — приморский развлекательный комплекс в квартале Нямат города Бакльеу. Здесь есть аквапарк, зоны аттракционов, духовная зона и илистый пляж; это привычное место для местных жителей и гостей края.",
    "Khu du lịch Nhà Mát là một trong những khu vui chơi, giải trí ven biển quen thuộc và sầm uất của thành phố Bạc Liêu, nằm ở phường Nhà Mát, cách trung tâm thành phố khoảng 8 km. Do bờ biển Bạc Liêu chủ yếu là bãi bồi phù sa, không có bãi cát đẹp như nhiều nơi khác, nên khu du lịch được đầu tư nhiều hạng mục vui chơi nhân tạo để phục vụ nhu cầu giải trí. Điểm nhấn của khu là công viên nước với hệ thống hồ bơi, đường trượt nước nhiều tầng, khu vui chơi cảm giác mạnh và các trò chơi dành cho trẻ em, thu hút đông đảo gia đình vào dịp cuối tuần, lễ tết. Ngoài ra còn có khu ẩm thực hải sản, khu tâm linh với các công trình thờ tự và lối đi ra ngắm biển bãi bồi, rừng ngập mặn. Nhà Mát nằm ngay gần các điểm nổi tiếng khác của Bạc Liêu như Quán Âm Phật Đài và cánh đồng điện gió, nên thường được kết hợp trong cùng một hành trình tham quan. Tuy không mang vẻ hoang sơ tự nhiên, khu du lịch Nhà Mát vẫn là lựa chọn tiện lợi, phù hợp cho các gia đình muốn vui chơi, thư giãn khi đến vùng đất Bạc Liêu, nay thuộc tỉnh Cà Mau.",
    "Nha Mat Tourist Area is one of the familiar, busy seaside leisure complexes of Bac Lieu city, in Nha Mat ward about 8 km from the centre. Because the Bac Lieu coast is mostly silt mudflat with no fine sandy beaches like elsewhere, the area has been developed with many man-made attractions to meet the demand for entertainment. Its highlight is a water park with swimming pools, multi-level water slides, thrill rides and children's games, drawing many families at weekends and holidays. There are also a seafood dining area and a spiritual zone with places of worship and paths out to view the mudflat coast and mangrove forest. Nha Mat lies close to other famous Bac Lieu sites such as the Quan Am Buddhist Statue and the wind farm, so it is often combined in the same itinerary. Though it lacks wild natural charm, Nha Mat Tourist Area remains a convenient choice, well suited to families who want to play and relax when visiting the land of Bac Lieu, now part of Ca Mau province.",
    "Туристическая зона Нямат — один из привычных, оживлённых приморских развлекательных комплексов города Бакльеу, в квартале Нямат примерно в 8 км от центра. Поскольку побережье Бакльеу — в основном илистые отмели без красивых песчаных пляжей, как в других местах, зона застроена множеством искусственных аттракционов, отвечающих спросу на развлечения. Её изюминка — аквапарк с бассейнами, многоуровневыми водными горками, экстремальными аттракционами и детскими играми, привлекающий множество семей в выходные и праздники. Есть также зона морепродуктов и духовная зона с местами поклонения и дорожками к видам на илистое побережье и мангровый лес. Нямат расположена рядом с другими известными местами Бакльеу — статуей Гуаньинь и ветропарком, поэтому её часто включают в один маршрут. Хотя ей недостаёт дикой природной прелести, туристическая зона Нямат остаётся удобным выбором для семей, желающих поиграть и отдохнуть при посещении края Бакльеу, ныне входящего в провинцию Камау.",
    ["Khu vui chơi ven biển với công viên nước, trò chơi cho trẻ", "Khu ẩm thực hải sản và lối ngắm biển bãi bồi, rừng ngập mặn", "Gần Quán Âm Phật Đài và cánh đồng điện gió Bạc Liêu"],
    ["A seaside play area with a water park and children's rides", "Seafood dining and paths to the mudflat coast and mangroves", "Near the Quan Am statue and the Bac Lieu wind farm"],
    ["Приморская зона отдыха с аквапарком и детскими аттракционами", "Зона морепродуктов и дорожки к отмелям и мангру", "Рядом со статуей Гуаньинь и ветропарком Бакльеу"],
    {"hours_vi": "Khoảng 8:00–18:00; công viên nước theo lịch riêng.", "ticket_vi": "Vé công viên nước/khu trò chơi khoảng 60.000–150.000 VND tùy dịch vụ.", "duration_vi": "2–3 giờ.", "best_time_vi": "Cuối tuần, ngày lễ; mùa khô tháng 12–4.", "tips_vi": "Mang đồ bơi nếu chơi công viên nước; kết hợp thăm Quán Âm Phật Đài và điện gió gần đó."},
    ["family", "beach", "entertainment"]))

# 15. Vườn nhãn Bạc Liêu (Giồng Nhãn)
NEW.append(rec(
    "vuon-nhan-bac-lieu", "Vườn nhãn cổ Bạc Liêu (Giồng Nhãn)", "Bac Lieu Ancient Longan Gardens (Giong Nhan)", "Старинные лонгановые сады Бакльеу",
    ["park_garden"], 9.2680, 105.8000,
    "Xã Hiệp Thành và Vĩnh Trạch Đông, TP. Bạc Liêu, tỉnh Cà Mau",
    {"value": 4.0, "count": 410, "source": "Google", "as_of": "2026-07"},
    "Du khách thích vườn nhãn cổ trăm năm tuổi ven biển, không gian mát mẻ và đờn ca tài tử miệt vườn. Nhiều người khen trải nghiệm hái nhãn, ăn trái cây và tìm hiểu văn hóa vùng giồng cát.",
    "Vườn nhãn cổ Bạc Liêu, hay Giồng Nhãn, là vùng trồng nhãn lâu năm trên dải giồng cát ven biển, có những gốc nhãn cả trăm tuổi. Nơi đây mang không gian miệt vườn mát mẻ, gắn với văn hóa đờn ca tài tử và ẩm thực dân dã Nam Bộ.",
    "The Bac Lieu Ancient Longan Gardens, or Giong Nhan, are long-established longan groves on a coastal sand ridge, with some trees a century old. They offer a cool orchard setting, tied to don ca tai tu music and rustic southern cuisine.",
    "Старинные лонгановые сады Бакльеу, или Зёнгньян, — давние лонгановые рощи на прибрежной песчаной гряде, где некоторым деревьям по сто лет. Они дарят прохладную садовую атмосферу, связанную с музыкой дон-ка-тай-ты и простой южной кухней.",
    "Vườn nhãn cổ Bạc Liêu, người dân quen gọi là Giồng Nhãn, là một vùng trồng nhãn lâu đời nằm trên dải giồng cát ven biển thuộc các xã Hiệp Thành và Vĩnh Trạch Đông, cách trung tâm thành phố Bạc Liêu khoảng 6–7 km. Vườn nhãn trải dài nhiều cây số dọc theo giồng cát, trong đó có không ít gốc nhãn cổ thụ đã hàng trăm năm tuổi, thân xù xì, tán rộng, được người dân nâng niu gìn giữ qua nhiều thế hệ. Dưới bóng những tán nhãn xanh mát là không gian miệt vườn yên bình, thoáng đãng, rất được du khách yêu thích để dạo chơi, nghỉ ngơi, tránh cái nắng gay gắt của vùng ven biển. Đến đây vào mùa nhãn chín (thường khoảng tháng 5 đến tháng 9), du khách có thể tham quan vườn, tự tay hái và thưởng thức những chùm nhãn ngọt thơm ngay tại gốc. Nhiều nhà vườn còn kết hợp phục vụ ẩm thực đồng quê, đặc sản Bạc Liêu và các buổi giao lưu đờn ca tài tử – loại hình nghệ thuật gắn bó với vùng đất này. Với vẻ đẹp bình dị, mát lành và đậm chất văn hóa miệt vườn, vườn nhãn cổ Bạc Liêu là điểm đến thư giãn thú vị của tỉnh Cà Mau sau sáp nhập.",
    "The Bac Lieu Ancient Longan Gardens, commonly called Giong Nhan, are long-established longan groves on a coastal sand ridge in Hiep Thanh and Vinh Trach Dong communes, about 6–7 km from the centre of Bac Lieu city. The groves stretch for several kilometres along the sand ridge and include many ancient longan trees hundreds of years old, with gnarled trunks and broad canopies, cherished and preserved by local families over generations. Beneath the cool green canopies lies a peaceful, airy orchard space that visitors love for strolling and resting away from the harsh coastal sun. Coming here in the longan season, usually around May to September, visitors can tour the gardens and pick and enjoy sweet, fragrant longans straight from the tree. Many garden households also serve country food and Bac Lieu specialties and hold sessions of don ca tai tu, the art form bound to this land. With its plain, cool beauty and strong orchard-culture character, the Bac Lieu Ancient Longan Gardens are a pleasant place to relax in Ca Mau province after the merger.",
    "Старинные лонгановые сады Бакльеу, которые в народе называют Зёнгньян, — давние лонгановые рощи на прибрежной песчаной гряде в общинах Хьептхань и Виньчать Донг, примерно в 6–7 км от центра города Бакльеу. Рощи тянутся на несколько километров вдоль песчаной гряды и включают множество древних лонгановых деревьев возрастом в сотни лет, с корявыми стволами и широкими кронами, любовно сохраняемых местными семьями из поколения в поколение. Под прохладными зелёными кронами раскинулось спокойное, открытое садовое пространство, которое гости любят для прогулок и отдыха вдали от палящего приморского солнца. Приезжая сюда в сезон лонгана, обычно с мая по сентябрь, гости могут осматривать сады и срывать и пробовать сладкие, ароматные лонганы прямо с дерева. Многие садовые хозяйства также подают деревенскую еду и деликатесы Бакльеу и устраивают сеансы дон-ка-тай-ты — искусства, связанного с этим краем. Простой, прохладной красотой и сильным садово-культурным характером старинные лонгановые сады Бакльеу — приятное место для отдыха в провинции Камау после слияния.",
    ["Vườn nhãn cổ trăm năm tuổi trên giồng cát ven biển", "Không gian miệt vườn mát mẻ, hái và thưởng thức nhãn tại vườn", "Ẩm thực đồng quê và giao lưu đờn ca tài tử Nam Bộ"],
    ["Century-old longan groves on a coastal sand ridge", "A cool orchard setting for picking and eating longans", "Country food and don ca tai tu music sessions"],
    ["Столетние лонгановые рощи на прибрежной песчаной гряде", "Прохладный сад, где срывают и едят лонганы", "Деревенская еда и сеансы музыки дон-ка-тай-ты"],
    {"hours_vi": "Cả ngày; mùa nhãn chín khoảng tháng 5–9.", "ticket_vi": "Miễn phí hoặc phí nhỏ; trả tiền trái cây, dịch vụ ăn uống.", "duration_vi": "1–2 giờ.", "best_time_vi": "Mùa nhãn chín tháng 5–9; sáng hoặc chiều mát.", "tips_vi": "Hỏi giá trước khi hái nhãn, ăn uống; kết hợp thăm chùa Xiêm Cán, điện gió gần đó."},
    ["nature", "orchard", "culture", "local"]))

# 16. Chùa Ghositaram
NEW.append(rec(
    "chua-ghositaram", "Chùa Ghositaram (chùa Cù Lao)", "Ghositaram Khmer Pagoda", "Кхмерская пагода Госитарам",
    ["church"], 9.3050, 105.6600,
    "Xã Hưng Hội, huyện Vĩnh Lợi, tỉnh Cà Mau",
    {"value": 4.5, "count": 640, "source": "Google", "as_of": "2026-07"},
    "Du khách trầm trồ trước ngôi chùa Khmer với nội thất chạm khắc, đắp vẽ cực kỳ công phu, được ví như 'bảo tàng nghệ thuật'. Nhiều người khen các nghệ nhân địa phương và màu sắc, hoa văn tinh xảo.",
    "Chùa Ghositaram, còn gọi là chùa Cù Lao, là ngôi chùa Khmer nổi tiếng ở huyện Vĩnh Lợi với nghệ thuật trang trí công phu bậc nhất. Chính điện được các nghệ nhân Khmer địa phương chạm khắc, đắp nổi và vẽ hoa văn tỉ mỉ, rực rỡ như một tác phẩm nghệ thuật.",
    "Ghositaram Pagoda, also called Cu Lao Pagoda, is a famous Khmer temple in Vinh Loi district with some of the most elaborate decorative art. Its main hall is carved, moulded and painted with meticulous, vivid motifs by local Khmer artisans, like a work of art.",
    "Пагода Госитарам, называемая также пагодой Кулао, — известный кхмерский храм в уезде Виньлой с одним из самых искусных декоративных убранств. Её главный зал вырезан, вылеплен и расписан кропотливыми, яркими узорами местными кхмерскими мастерами, словно произведение искусства.",
    "Chùa Ghositaram, người dân địa phương thường gọi là chùa Cù Lao, tọa lạc tại xã Hưng Hội, huyện Vĩnh Lợi, là một trong những ngôi chùa Khmer nổi tiếng và độc đáo bậc nhất của vùng đất Bạc Liêu xưa. Chùa được biết đến không chỉ bởi lịch sử lâu đời mà đặc biệt bởi nghệ thuật trang trí, kiến trúc vô cùng công phu, tinh xảo, được nhiều người ví như một 'bảo tàng nghệ thuật' của người Khmer Nam Bộ. Điểm gây ấn tượng mạnh nhất là ngôi chính điện, với hệ thống cột, trần, tường được các nghệ nhân Khmer địa phương dày công chạm khắc, đắp nổi phù điêu và vẽ những mảng hoa văn, hình tượng Phật, tiên nữ, chằn, hoa lá rực rỡ sắc màu, dát vàng lộng lẫy. Mỗi chi tiết đều thể hiện bàn tay tài hoa và tâm huyết của những người thợ, phản ánh đậm nét thẩm mỹ và tín ngưỡng Phật giáo Nam tông Khmer. Bên cạnh giá trị nghệ thuật, chùa còn là trung tâm sinh hoạt tôn giáo, văn hóa, giáo dục của cộng đồng Khmer trong vùng, nơi diễn ra các lễ hội truyền thống. Với vẻ đẹp lộng lẫy hiếm có, chùa Ghositaram là điểm đến văn hóa, tâm linh đặc sắc của tỉnh Cà Mau sau sáp nhập.",
    "Ghositaram Pagoda, which locals usually call Cu Lao Pagoda, stands in Hung Hoi commune, Vinh Loi district, and is one of the most famous and distinctive Khmer temples of the former Bac Lieu land. It is known not only for its long history but especially for its extraordinarily elaborate, refined decorative art and architecture, often likened to an 'art museum' of the southern Khmer. Its most striking feature is the main hall, whose columns, ceiling and walls have been painstakingly carved, moulded in relief and painted by local Khmer artisans with vividly coloured, richly gilded motifs, images of Buddhas, apsaras, yaks and foliage. Every detail shows the skill and devotion of the craftsmen and strongly reflects the aesthetics and Theravada Khmer Buddhist faith. Beyond its artistic value, the temple is a centre of religious, cultural and educational life for the region's Khmer community, where traditional festivals are held. With its rare, resplendent beauty, Ghositaram Pagoda is an outstanding cultural and spiritual destination in Ca Mau province after the merger.",
    "Пагода Госитарам, которую местные жители обычно называют пагодой Кулао, стоит в общине Хынгхой уезда Виньлой и является одним из самых известных и самобытных кхмерских храмов бывшего края Бакльеу. Она известна не только долгой историей, но особенно необычайно искусным, утончённым декоративным убранством и архитектурой, которые часто сравнивают с «музеем искусства» южных кхмеров. Её самая эффектная часть — главный зал, чьи колонны, потолок и стены кропотливо вырезаны, вылеплены рельефом и расписаны местными кхмерскими мастерами яркими, богато позолоченными узорами, изображениями будд, апсар, якшей и растений. Каждая деталь отражает мастерство и преданность ремесленников и ярко выражает эстетику и буддизм тхеравады кхмеров. Помимо художественной ценности, храм — центр религиозной, культурной и образовательной жизни кхмерской общины края, где проводятся традиционные праздники. Редкой, великолепной красотой пагода Госитарам — выдающееся культурное и духовное направление провинции Камау после слияния.",
    ["Chùa Khmer với nghệ thuật trang trí công phu như 'bảo tàng nghệ thuật'", "Chính điện chạm khắc, đắp vẽ, dát vàng do nghệ nhân Khmer thực hiện", "Trung tâm văn hóa, tín ngưỡng Phật giáo Nam tông Khmer"],
    ["A Khmer temple with elaborate decor, like an 'art museum'", "Main hall carved, painted and gilded by Khmer artisans", "A centre of Theravada Khmer Buddhist culture and faith"],
    ["Кхмерский храм с искусным убранством, как «музей искусства»", "Главный зал вырезан, расписан и позолочен кхмерскими мастерами", "Центр культуры и веры буддизма тхеравады кхмеров"],
    {"hours_vi": "Khoảng 6:00–18:00 hằng ngày.", "ticket_vi": "Miễn phí (có hòm công đức).", "duration_vi": "30–45 phút.", "best_time_vi": "Sáng hoặc chiều mát; dịp lễ hội Khmer đặc sắc.", "tips_vi": "Ăn mặc kín đáo, lịch sự; giữ yên tĩnh; xin phép khi chụp ảnh trong chính điện và sư sãi."},
    ["temple", "culture", "khmer", "art"]))

# ---- Ghi an toàn: nạp – append (bỏ qua slug đã có) – ghi ----
d = json.load(open(F, encoding="utf-8")) if os.path.exists(F) else []
have = {p["slug"] for p in d}
added = [p for p in NEW if p["slug"] not in have]
d += added
json.dump(d, open(F, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("Da them:", len(added), "| Bo qua trung:", len(NEW) - len(added), "| Tong Ca Mau:", len(d))
print("Slugs them:", ", ".join(p["slug"] for p in added))
