# -*- coding: utf-8 -*-
"""Bổ sung địa điểm du lịch Hà Nội (batch A - trung tâm nội thành).
Chèn an toàn: nạp -> append -> ghi; bỏ qua slug đã có. Maps để rỗng cho
retrofit_map_links.py tự sinh (trỏ thẳng thẻ địa điểm)."""
import json, os, urllib.parse

REG = "vn-ha-noi"
REGION_NAME_VI = "Hà Nội"
FED = "Miền Bắc"
LU = "2026-07-28"
F = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data", "regions", "vn-ha-noi.json")


def rec(slug, name_vi, name_en, name_ru, cats, lat, lon, address_vi,
        ss_vi, ss_en, ss_ru, sl_vi, sl_en, sl_ru,
        hl_vi, hl_en, hl_ru, practical, rating=None, review_vi=None, tags=None):
    return {
        "id": f"{REG}-{slug}",
        "slug": slug,
        "region": REG,
        "country": "vietnam",
        "region_name_vi": REGION_NAME_VI,
        "federal_district": FED,
        "name_vi": name_vi,
        "name_ru": name_ru,
        "name_en": name_en,
        "categories": cats,
        "coordinates": {"lat": lat, "lon": lon},
        "address_vi": address_vi,
        "rating": rating,
        "review_summary_vi": review_vi,
        "presentation_short_vi": ss_vi,
        "presentation_short_en": ss_en,
        "presentation_short_ru": ss_ru,
        "presentation_long_vi": sl_vi,
        "presentation_long_en": sl_en,
        "presentation_long_ru": sl_ru,
        "highlights_vi": hl_vi,
        "highlights_en": hl_en,
        "highlights_ru": hl_ru,
        "practical": practical,
        "photo": None,
        "photo_credit": None,
        "maps": {},
        "official_site": None,
        "sources": [
            {"title": "Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Special:Search?search=" + urllib.parse.quote(name_en)},
            {"title": "Wikipedia (VI)", "url": "https://vi.wikipedia.org/wiki/Special:Search?search=" + urllib.parse.quote(name_vi)},
        ],
        "tags": tags or [],
        "status": "enriched",
        "last_updated": LU,
    }


new = [
    rec(
        "den-quan-thanh",
        "Đền Quán Thánh (Trấn Vũ Quán)",
        "Quan Thanh Temple",
        "Храм Куантхань",
        ["church", "monument"],
        21.0453, 105.8352,
        "Đường Thanh Niên, phường Quán Thánh, quận Ba Đình, Hà Nội",
        "Đền Quán Thánh là một trong Thăng Long tứ trấn, trấn giữ phía bắc kinh thành và thờ thần Huyền Thiên Trấn Vũ. Đền nổi tiếng với pho tượng đồng đen cao gần 4 mét, nặng khoảng 4 tấn, đúc năm 1677, tọa lạc bên hồ Tây thơ mộng.",
        "Quan Thanh Temple is one of the Four Sacred Temples of Thang Long, guarding the northern gate of the old capital and dedicated to the deity Huyen Thien Tran Vu. It is famous for a nearly four-metre black-bronze statue weighing about four tonnes, cast in 1677, standing beside romantic West Lake.",
        "Храм Куантхань — один из «Четырёх священных храмов» древней столицы Тханглонг, охранявший её северные врата и посвящённый божеству Хюйентхьен Чанву. Он знаменит статуей из чёрной бронзы высотой почти четыре метра и весом около четырёх тонн, отлитой в 1677 году, у романтичного Западного озера.",
        "Nằm ở góc giao giữa hồ Tây và hồ Trúc Bạch, đền Quán Thánh (còn gọi Trấn Vũ Quán) là một trong bốn ngôi đền thiêng trấn giữ bốn phương của kinh thành Thăng Long xưa, ứng với hướng bắc. Đền được lập từ thời Lý, thờ Huyền Thiên Trấn Vũ, vị thần cai quản phương bắc và trừ tà ma, thủy quái. Báu vật của đền là pho tượng Trấn Vũ bằng đồng đen cao gần 4 mét, nặng khoảng 4 tấn, đúc năm 1677, tay trái bắt quyết, tay phải chống gươm có rắn quấn và rùa đỡ dưới chân, được xem là kiệt tác đúc đồng của người Thăng Long. Cổng tam quan, nghi môn và những mảng chạm khắc gỗ, hoành phi câu đối cổ tạo nên không gian trầm mặc, cổ kính. Du khách thường xoa chân tượng để cầu may, thắp hương cầu bình an, rồi tản bộ trên con đường Thanh Niên lộng gió ven hồ. Gần Lăng Bác và chùa Trấn Quốc, đền là điểm dừng chân lý tưởng để hiểu thêm về tín ngưỡng và nghệ thuật của người Hà Nội.",
        "Standing where West Lake meets Truc Bach Lake, Quan Thanh Temple (also called Tran Vu Temple) is one of the four sacred shrines that once protected the four directions of the old capital, Thang Long, marking the north. Founded under the Ly dynasty, it honours Huyen Thien Tran Vu, the deity who rules the northern quarter and repels evil spirits and water demons. The temple's treasure is a statue of Tran Vu cast in black bronze, nearly four metres tall and weighing around four tonnes, made in 1677: the left hand forms a mudra while the right rests on a sword entwined by a serpent and supported by a tortoise, a masterpiece of Thang Long bronze-casting. A triple gateway, ceremonial arch and time-worn wooden carvings, lacquered boards and parallel sentences give the courtyard a hushed, ancient air. Visitors often rub the statue's foot for luck, light incense for peace, then stroll the breezy lakeside Thanh Nien Road. Close to the Ho Chi Minh Mausoleum and Tran Quoc Pagoda, the temple is an ideal stop for understanding the beliefs and craftsmanship of Hanoi.",
        "На стрелке между Западным озером и озером Чукбать стоит храм Куантхань (также храм Чанву) — одно из четырёх священных святилищ, некогда оберегавших стороны света древней столицы Тханглонг; он отмечает север. Основанный при династии Ли, храм посвящён Хюйентхьен Чанву, божеству северной стороны, изгоняющему злых духов и водяных чудовищ. Главная реликвия — статуя Чанву из чёрной бронзы высотой почти четыре метра и весом около четырёх тонн, отлитая в 1677 году: левая рука сложена в жесте, правая опирается на меч, обвитый змеёй, а у ног черепаха — шедевр бронзолитейного дела Тханглонга. Тройные ворота, церемониальная арка, потемневшая от времени резьба по дереву, лаковые доски с изречениями создают тихую, старинную атмосферу. Гости часто трут ногу статуи на удачу, зажигают благовония ради покоя, а затем гуляют по продуваемой ветром набережной Тханьниен. Рядом с мавзолеем Хо Ши Мина и пагодой Чанкуок храм — прекрасная остановка, чтобы ближе узнать верования и мастерство ханойцев.",
        ["Một trong Thăng Long tứ trấn, trấn giữ phương bắc kinh thành", "Tượng Huyền Thiên Trấn Vũ bằng đồng đen cao gần 4 m, đúc năm 1677", "Vị trí đẹp bên hồ Tây và hồ Trúc Bạch, gần Lăng Bác"],
        ["One of the Four Sacred Temples of Thang Long, guarding the north", "Black-bronze statue of Tran Vu, nearly 4 m tall, cast in 1677", "Scenic setting between West Lake and Truc Bach Lake, near the Mausoleum"],
        ["Один из «Четырёх священных храмов» Тханглонга, страж севера", "Статуя Чанву из чёрной бронзы высотой почти 4 м, отлита в 1677 году", "Живописное место между Западным озером и озером Чукбать, у мавзолея"],
        {"hours_vi": "Khoảng 8:00-17:00 hằng ngày (đông khách vào ngày rằm, mùng một).", "ticket_vi": "Vé vào cửa khoảng 10.000 VND/người.", "duration_vi": "Khoảng 30-45 phút.", "best_time_vi": "Sáng sớm hoặc chiều mát; dịp lễ Tết rất đông.", "tips_vi": "Ăn mặc lịch sự khi vào đền; kết hợp dạo đường Thanh Niên, chùa Trấn Quốc và Lăng Bác gần đó."},
        rating={"value": 4.5, "count": 6800, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách khen không gian cổ kính, yên tĩnh ngay sát hồ Tây và ấn tượng mạnh với pho tượng đồng đen khổng lồ. Nhiều người thích ghé đền rồi đi bộ trên đường Thanh Niên; một số lưu ý đền khá nhỏ nên tham quan nhanh.",
        tags=["historic", "temple", "top"],
    ),
    rec(
        "chua-quan-su",
        "Chùa Quán Sứ",
        "Quan Su Pagoda",
        "Пагода Куанши",
        ["church"],
        21.0248, 105.8447,
        "73 phố Quán Sứ, quận Hoàn Kiếm, Hà Nội",
        "Chùa Quán Sứ là trụ sở của Giáo hội Phật giáo Việt Nam, một trong những ngôi chùa quan trọng bậc nhất Hà Nội. Điểm đặc biệt là các câu đối, hoành phi được viết bằng chữ Quốc ngữ thay vì chữ Hán, thể hiện tinh thần Phật giáo hiện đại.",
        "Quan Su Pagoda is the headquarters of the Vietnam Buddhist Sangha and one of Hanoi's most important temples. Unusually, its couplets and horizontal boards are written in the modern Vietnamese alphabet rather than Chinese characters, reflecting a spirit of modern Buddhism.",
        "Пагода Куанши — резиденция Буддийской сангхи Вьетнама и один из важнейших храмов Ханоя. Её особенность в том, что парные надписи и таблички выполнены современным вьетнамским алфавитом, а не иероглифами, что отражает дух современного буддизма.",
        "Tọa lạc trên con phố cùng tên giữa lòng Hà Nội, chùa Quán Sứ có nguồn gốc từ thế kỷ 15, khi triều đình dựng một công quán để đón sứ thần các nước láng giềng theo đạo Phật, trong khuôn viên có ngôi chùa nhỏ để họ hành lễ, từ đó thành tên. Ngày nay chùa là trụ sở của Giáo hội Phật giáo Việt Nam, nơi diễn ra nhiều đại lễ và hoạt động Phật sự lớn. Kiến trúc chùa mang nét đặc trưng Bắc Bộ với tam quan ba tầng, mái cong, chính điện trang nghiêm thờ các vị Phật, Bồ Tát và thiền sư. Điểm độc đáo hiếm thấy là các câu đối, hoành phi trong chùa được viết bằng chữ Quốc ngữ, giúp Phật tử dễ đọc, dễ hiểu, thể hiện tinh thần nhập thế và hiện đại của Phật giáo Việt Nam. Không gian chùa tuy nằm giữa phố xá nhộn nhịp nhưng vẫn giữ được sự tĩnh lặng, khói hương trầm mặc. Vào ngày rằm, mùng một và các dịp lễ Phật đản, Vu Lan, chùa đón rất đông người dân tới lễ bái, cầu an.",
        "Set on the street that bears its name in central Hanoi, Quan Su Pagoda dates to the fifteenth century, when the court built a guest house to receive Buddhist envoys from neighbouring states; a small shrine in its grounds let them worship, and so the name arose. Today it is the headquarters of the Vietnam Buddhist Sangha and the venue for major ceremonies and religious affairs. Its architecture is typically northern, with a three-tiered gateway, curving roofs and a solemn main hall enshrining Buddhas, bodhisattvas and Zen patriarchs. A rare and distinctive touch is that the couplets and lacquered boards are written in the modern Vietnamese alphabet rather than Chinese script, making them easy for the faithful to read and reflecting the engaged, modern spirit of Vietnamese Buddhism. Though it sits amid busy streets, the pagoda keeps a quiet, incense-scented calm. On the new and full moon and during festivals such as the Buddha's Birthday and Vu Lan, crowds of city dwellers come to pray for peace and blessings.",
        "На улице, носящей её имя, в центре Ханоя пагода Куанши восходит к XV веку, когда двор построил гостевой дом для приёма буддийских послов из соседних государств; небольшое святилище в его дворе позволяло им молиться — отсюда и название. Сегодня это резиденция Буддийской сангхи Вьетнама и место крупных церемоний и религиозных дел. Её архитектура типична для севера: трёхъярусные ворота, изогнутые крыши и торжественный главный зал с изваяниями будд, бодхисаттв и дзенских патриархов. Редкая особенность в том, что парные надписи и лаковые таблички выполнены современным вьетнамским алфавитом, а не иероглифами, что облегчает чтение верующим и отражает деятельный, современный дух вьетнамского буддизма. Хотя пагода стоит среди оживлённых улиц, она хранит тихий, напоённый благовониями покой. В новолуние и полнолуние, а также в праздники — день рождения Будды и Вулан — сюда стекаются толпы горожан, чтобы помолиться о мире и благополучии.",
        ["Trụ sở của Giáo hội Phật giáo Việt Nam", "Câu đối, hoành phi viết bằng chữ Quốc ngữ hiếm thấy", "Trung tâm sinh hoạt Phật giáo giữa lòng Hà Nội"],
        ["Headquarters of the Vietnam Buddhist Sangha", "Rare couplets written in the modern Vietnamese alphabet", "A hub of Buddhist life in central Hanoi"],
        ["Резиденция Буддийской сангхи Вьетнама", "Редкие парные надписи на современном вьетнамском алфавите", "Центр буддийской жизни в сердце Ханоя"],
        {"hours_vi": "Khoảng 6:00-19:00 hằng ngày.", "ticket_vi": "Miễn phí.", "duration_vi": "Khoảng 30 phút.", "best_time_vi": "Sáng sớm; đông vào ngày rằm, mùng một và đại lễ Phật giáo.", "tips_vi": "Ăn mặc kín đáo, giữ yên tĩnh; gần ga Hà Nội và Nhà tù Hỏa Lò."},
        rating={"value": 4.5, "count": 5200, "source": "Google", "as_of": "2026-07"},
        review_vi="Nhiều người tới lễ Phật khen chùa trang nghiêm, thanh tịnh và có ý nghĩa tâm linh lớn. Du khách nước ngoài thích tìm hiểu vai trò trung tâm Phật giáo; một số nhắc chùa nằm trên phố đông nên chú ý gửi xe.",
        tags=["temple", "historic", "free"],
    ),
    rec(
        "bao-tang-dan-toc-hoc",
        "Bảo tàng Dân tộc học Việt Nam",
        "Vietnam Museum of Ethnology",
        "Вьетнамский музей этнологии",
        ["museum"],
        21.0410, 105.7985,
        "Đường Nguyễn Văn Huyên, quận Cầu Giấy, Hà Nội",
        "Bảo tàng Dân tộc học Việt Nam giới thiệu văn hóa của 54 dân tộc anh em qua hiện vật, hình ảnh và những ngôi nhà truyền thống dựng ngoài trời. Đây là một trong những bảo tàng hấp dẫn và được yêu thích nhất Hà Nội.",
        "The Vietnam Museum of Ethnology presents the cultures of the country's 54 ethnic groups through artefacts, photographs and full-size traditional houses in its open-air grounds. It is one of Hanoi's most engaging and best-loved museums.",
        "Вьетнамский музей этнологии знакомит с культурами 54 народов страны через предметы быта, фотографии и настоящие традиционные дома под открытым небом. Это один из самых интересных и любимых музеев Ханоя.",
        "Nằm ở quận Cầu Giấy, Bảo tàng Dân tộc học Việt Nam là nơi lưu giữ, nghiên cứu và tôn vinh sự đa dạng văn hóa của 54 dân tộc trên khắp đất nước. Khu trưng bày trong nhà, tòa nhà hình trống đồng, giới thiệu hàng nghìn hiện vật: trang phục, nhạc cụ, công cụ lao động, đồ thờ cúng, cùng phim tư liệu và ảnh sống động về đời sống của người Kinh, Tày, Thái, Mông, Ê Đê, Ba Na và nhiều tộc người khác. Hấp dẫn nhất là vườn kiến trúc ngoài trời, nơi phục dựng nguyên bản những ngôi nhà truyền thống: nhà rông Tây Nguyên cao vút, nhà dài Ê Đê, nhà sàn Tày, nhà trình tường người Hà Nhì và nhà mồ với tượng gỗ độc đáo. Du khách có thể bước vào từng ngôi nhà, cảm nhận không gian sống thật của mỗi dân tộc. Bảo tàng còn có khu trưng bày văn hóa Đông Nam Á và thường xuyên tổ chức trình diễn múa rối nước, làm bánh, in tranh dân gian, đặc biệt nhộn nhịp vào dịp Tết Trung thu và Tết Nguyên đán. Đây là điểm đến lý tưởng cho gia đình và những ai muốn hiểu sâu bức tranh văn hóa muôn màu của Việt Nam.",
        "In Cau Giay District, the Vietnam Museum of Ethnology preserves, studies and celebrates the cultural diversity of the country's 54 ethnic groups. Its indoor building, shaped like a bronze drum, displays thousands of artefacts — costumes, musical instruments, tools and ritual objects — alongside documentary films and vivid photographs of the lives of the Kinh, Tay, Thai, Hmong, Ede, Bahnar and many other peoples. The highlight is the open-air architecture garden, where traditional dwellings are rebuilt to full scale: a soaring Central Highlands communal house, a long Ede house, a Tay stilt house, a rammed-earth Ha Nhi home and a tomb house with striking wooden figures. Visitors can step inside each building and sense the real living space of every group. The museum also has a Southeast Asian gallery and regularly stages water-puppet shows, cake-making and folk woodblock printing, growing especially lively at the Mid-Autumn Festival and Lunar New Year. It is an ideal destination for families and for anyone wishing to understand the vivid mosaic of Vietnamese culture.",
        "В районе Зяй музей этнологии Вьетнама хранит, изучает и прославляет культурное многообразие 54 народов страны. В крытом корпусе, по форме напоминающем бронзовый барабан, выставлены тысячи предметов — костюмы, музыкальные инструменты, орудия труда и ритуальная утварь, — а также документальные фильмы и живые фотографии из жизни кинь, тай, тхай, хмонгов, эде, банар и многих других народов. Изюминка — сад архитектуры под открытым небом, где в натуральную величину воссозданы традиционные жилища: устремлённый ввысь общинный дом Центрального нагорья, длинный дом эде, свайный дом тай, глинобитный дом ханьи и погребальный дом с выразительными деревянными фигурами. Посетители могут войти в каждое строение и ощутить настоящее жизненное пространство народа. В музее есть и зал культуры Юго-Восточной Азии, регулярно проходят представления кукол на воде, лепка лакомств и печать народных гравюр — особенно оживлённо в праздник середины осени и лунный Новый год. Это идеальное место для семей и для всех, кто хочет глубже понять яркую мозаику вьетнамской культуры.",
        ["Trưng bày văn hóa của cả 54 dân tộc Việt Nam", "Vườn kiến trúc ngoài trời với nhà truyền thống dựng nguyên bản", "Trình diễn múa rối nước và nghề thủ công dân gian"],
        ["Displays the cultures of all 54 Vietnamese ethnic groups", "Open-air garden of full-size traditional houses", "Water-puppet shows and folk craft demonstrations"],
        ["Показывает культуры всех 54 народов Вьетнама", "Сад под открытым небом с традиционными домами в натуральную величину", "Представления кукол на воде и народные ремёсла"],
        {"hours_vi": "8:30-17:30, đóng cửa thứ Hai và Tết Nguyên đán.", "ticket_vi": "Người lớn khoảng 40.000 VND; sinh viên, học sinh được giảm.", "duration_vi": "Khoảng 2-3 giờ.", "best_time_vi": "Cuối tuần có trình diễn; đẹp cả sáng lẫn chiều.", "tips_vi": "Dành thời gian cho khu nhà ngoài trời; đi giày thoải mái; phù hợp cho gia đình có trẻ nhỏ."},
        rating={"value": 4.6, "count": 15000, "source": "Google", "as_of": "2026-07"},
        review_vi="Được đánh giá là một trong những bảo tàng đáng đi nhất Hà Nội. Du khách thích khu nhà truyền thống ngoài trời, phần trưng bày công phu và dễ hiểu; nhiều gia đình khen phù hợp cho trẻ em. Một số góp ý nên đi lúc trời mát vì khu ngoài trời khá rộng.",
        tags=["museum", "family", "top"],
    ),
    rec(
        "bao-tang-lich-su-quoc-gia",
        "Bảo tàng Lịch sử Quốc gia",
        "National Museum of Vietnamese History",
        "Национальный музей истории Вьетнама",
        ["museum"],
        21.0245, 105.8600,
        "Số 1 Tràng Tiền và 216 Trần Quang Khải, quận Hoàn Kiếm, Hà Nội",
        "Bảo tàng Lịch sử Quốc gia trưng bày dòng chảy lịch sử Việt Nam từ thời tiền sử tới hiện đại, với nhiều bảo vật quốc gia như trống đồng Đông Sơn. Tòa nhà chính mang phong cách Đông Dương độc đáo, kết hợp kiến trúc Pháp và Á Đông.",
        "The National Museum of Vietnamese History traces the country's story from prehistory to modern times, with many national treasures such as Dong Son bronze drums. Its main building is a striking example of Indochine architecture, blending French and Asian design.",
        "Национальный музей истории Вьетнама прослеживает историю страны от доисторических времён до современности, храня множество национальных сокровищ, в том числе бронзовые барабаны Донгшон. Его главное здание — яркий образец «индокитайского» стиля, соединяющего французскую и азиатскую архитектуру.",
        "Bảo tàng Lịch sử Quốc gia là nơi hội tụ những dấu mốc quan trọng nhất trong hàng nghìn năm lịch sử dân tộc Việt Nam. Bộ sưu tập trải dài từ thời đại đồ đá, văn hóa Đông Sơn với những chiếc trống đồng tinh xảo, qua các triều đại Lý, Trần, Lê, Nguyễn, tới thời cận đại và cuộc đấu tranh giành độc lập. Du khách được chiêm ngưỡng nhiều bảo vật quốc gia: trống đồng Ngọc Lũ, tượng Phật, bia đá, gốm sứ, ấn triện và các hiện vật khảo cổ vô giá. Cơ sở chính tọa lạc trong tòa nhà xây năm 1932, vốn là Bảo tàng Louis Finot của Trường Viễn Đông Bác Cổ, do kiến trúc sư Ernest Hébrard thiết kế theo phong cách Đông Dương: mái ngói cong, sảnh bát giác, kết hợp hài hòa nét Pháp và Á Đông, bản thân đã là một tác phẩm nghệ thuật. Phần trưng bày về lịch sử cách mạng và kháng chiến đặt tại cơ sở gần đó. Nằm ngay sau Nhà hát Lớn, bảo tàng là điểm đến không thể bỏ qua với ai muốn hiểu ngọn nguồn văn hóa và lịch sử Việt Nam.",
        "The National Museum of Vietnamese History gathers the most important milestones of the nation's several thousand years of history. Its collection reaches from the Stone Age and the Dong Son culture, with its finely worked bronze drums, through the Ly, Tran, Le and Nguyen dynasties to the modern era and the struggle for independence. Visitors can admire many national treasures: the Ngoc Lu bronze drum, Buddhist statues, stone steles, ceramics, seals and priceless archaeological finds. The main branch occupies a building of 1932, formerly the Louis Finot Museum of the French School of the Far East, designed by architect Ernest Hébrard in the Indochine style: curving tiled roofs and an octagonal hall harmoniously blending French and Asian elements — a work of art in itself. Displays on the revolution and resistance wars are housed in a nearby branch. Standing just behind the Opera House, the museum is an essential stop for anyone wishing to understand the roots of Vietnamese culture and history.",
        "Национальный музей истории Вьетнама собирает важнейшие вехи многотысячелетней истории страны. Его коллекция простирается от каменного века и культуры Донгшон с её тонко отлитыми бронзовыми барабанами через династии Ли, Чан, Ле и Нгуен до Нового времени и борьбы за независимость. Посетители могут увидеть множество национальных сокровищ: бронзовый барабан Нгоклу, статуи Будды, каменные стелы, керамику, печати и бесценные археологические находки. Главный корпус занимает здание 1932 года — бывший музей Луи Фино Французской школы Дальнего Востока, построенный архитектором Эрнестом Эбраром в «индокитайском» стиле: изогнутые черепичные крыши и восьмиугольный зал гармонично соединяют французские и азиатские черты — само по себе произведение искусства. Экспозиция о революции и войнах Сопротивления размещена в соседнем корпусе. Стоящий сразу за Оперным театром, музей — обязательная остановка для всех, кто хочет понять истоки вьетнамской культуры и истории.",
        ["Nhiều bảo vật quốc gia, tiêu biểu là trống đồng Đông Sơn", "Tòa nhà kiến trúc Đông Dương của Ernest Hébrard (1932)", "Kể trọn dòng lịch sử từ tiền sử đến hiện đại"],
        ["Many national treasures, notably Dong Son bronze drums", "Indochine-style building by Ernest Hébrard (1932)", "Tells the full story from prehistory to modern times"],
        ["Множество национальных сокровищ, прежде всего барабаны Донгшон", "Здание в «индокитайском» стиле Эрнеста Эбрара (1932)", "Полная история от древности до современности"],
        {"hours_vi": "8:00-12:00 và 13:30-17:00, thường đóng cửa thứ Hai đầu tháng.", "ticket_vi": "Người lớn khoảng 40.000 VND; giảm cho học sinh, sinh viên.", "duration_vi": "Khoảng 1,5-2 giờ.", "best_time_vi": "Buổi sáng; kết hợp tham quan Nhà hát Lớn gần đó.", "tips_vi": "Có thuyết minh và bảng tiếng Anh; giữ trật tự, không dùng đèn flash với hiện vật cổ."},
        rating={"value": 4.4, "count": 7300, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách đánh giá cao bộ sưu tập phong phú và tòa nhà kiến trúc đẹp. Nhiều người ấn tượng với trống đồng và cổ vật; một số mong có thêm chú thích tiếng Anh chi tiết hơn.",
        tags=["museum", "historic", "architecture"],
    ),
    rec(
        "bao-tang-my-thuat",
        "Bảo tàng Mỹ thuật Việt Nam",
        "Vietnam Fine Arts Museum",
        "Вьетнамский музей изящных искусств",
        ["museum"],
        21.0309, 105.8373,
        "66 phố Nguyễn Thái Học, quận Ba Đình, Hà Nội",
        "Bảo tàng Mỹ thuật Việt Nam lưu giữ kho tàng nghệ thuật từ tượng Phật cổ, tranh dân gian tới hội họa hiện đại sơn mài, lụa và sơn dầu. Đây là nơi hội tụ tinh hoa mỹ thuật của đất nước qua nhiều thế kỷ.",
        "The Vietnam Fine Arts Museum holds a treasury of art, from ancient Buddhist sculpture and folk prints to modern lacquer, silk and oil painting. It brings together the finest of the country's art across many centuries.",
        "Вьетнамский музей изящных искусств хранит сокровищницу искусства — от древней буддийской скульптуры и народных гравюр до современной лаковой живописи, картин на шёлке и маслом. Здесь собрано лучшее из искусства страны за многие века.",
        "Tọa lạc trong một tòa nhà kiểu Pháp trên phố Nguyễn Thái Học, đối diện Văn Miếu, Bảo tàng Mỹ thuật Việt Nam là điểm đến hàng đầu cho những ai yêu nghệ thuật. Bộ sưu tập trải dài từ nghệ thuật cổ với tượng Phật gỗ, tượng Quan Âm nghìn mắt nghìn tay, điêu khắc đình chùa và gốm men ngọc, qua tranh dân gian Đông Hồ, Hàng Trống, tới hội họa hiện đại nửa đầu thế kỷ 20. Đây là nơi trưng bày nhiều kiệt tác của các danh họa trường Cao đẳng Mỹ thuật Đông Dương như Nguyễn Phan Chánh, Tô Ngọc Vân, Nguyễn Gia Trí, Bùi Xuân Phái, với những chất liệu độc đáo của Việt Nam: sơn mài, lụa, khắc gỗ. Người xem có thể cảm nhận vẻ đẹp trầm ấm của tranh sơn mài, sự mềm mại của tranh lụa và cái nhìn tinh tế về làng quê, phố cổ, người phụ nữ Việt. Không gian bảo tàng yên tĩnh, sáng sủa, được sắp đặt theo dòng thời gian giúp khách tham quan dễ theo dõi. Đây là nơi lý tưởng để hiểu tâm hồn và bản sắc dân tộc qua ngôn ngữ của màu sắc và hình khối.",
        "Housed in a French-era building on Nguyen Thai Hoc Street, opposite the Temple of Literature, the Vietnam Fine Arts Museum is a leading destination for art lovers. Its collection ranges from ancient art — wooden Buddha images, the thousand-eyed, thousand-armed Avalokiteshvara, communal-house carvings and celadon ceramics — through Dong Ho and Hang Trong folk prints to modern painting of the early twentieth century. Here hang many masterpieces by artists of the Indochina Fine Arts College, such as Nguyen Phan Chanh, To Ngoc Van, Nguyen Gia Tri and Bui Xuan Phai, in media distinctive to Vietnam: lacquer, silk and woodcut. Visitors can feel the warm depth of lacquer painting, the softness of silk and a tender eye for village life, the old quarter and Vietnamese women. The galleries are quiet and well lit, arranged chronologically so the story is easy to follow. It is an ideal place to sense the nation's soul and identity through the language of colour and form.",
        "Размещённый в здании французской эпохи на улице Нгуен Тхай Хок, напротив Храма литературы, Вьетнамский музей изящных искусств — одно из главных мест для любителей искусства. Его собрание простирается от древнего искусства — деревянных изваяний Будды, тысячерукой и тысячеглазой Авалокитешвары, резьбы общинных домов и селадоновой керамики — через народные гравюры Донгхо и Хангчонг до живописи начала XX века. Здесь висят многие шедевры художников Индокитайского училища изящных искусств — Нгуен Фан Тьаня, То Нгок Вана, Нгуен Зя Чи, Буй Суан Фая — в характерных для Вьетнама техниках: лак, шёлк, ксилография. Посетители ощущают тёплую глубину лаковой живописи, мягкость шёлка и нежный взгляд на деревенскую жизнь, Старый квартал и вьетнамских женщин. Залы тихи и хорошо освещены, устроены хронологически, так что повествование легко проследить. Это идеальное место, чтобы почувствовать душу и самобытность народа языком цвета и формы.",
        ["Kiệt tác sơn mài, lụa của các danh họa Đông Dương", "Tượng Quan Âm nghìn mắt nghìn tay và điêu khắc cổ", "Đối diện Văn Miếu, trong tòa nhà kiểu Pháp yên tĩnh"],
        ["Lacquer and silk masterpieces by Indochina-era artists", "The thousand-eyed, thousand-armed Avalokiteshvara and ancient sculpture", "Opposite the Temple of Literature, in a quiet French-era building"],
        ["Шедевры лаковой и шёлковой живописи мастеров индокитайской эпохи", "Тысячерукая и тысячеглазая Авалокитешвара и древняя скульптура", "Напротив Храма литературы, в тихом здании французской эпохи"],
        {"hours_vi": "8:30-17:00 hằng ngày.", "ticket_vi": "Người lớn khoảng 40.000 VND; giảm cho học sinh, sinh viên.", "duration_vi": "Khoảng 1,5-2 giờ.", "best_time_vi": "Buổi sáng yên tĩnh; kết hợp Văn Miếu đối diện.", "tips_vi": "Có thể thuê thuyết minh; đừng bỏ lỡ khu tranh sơn mài và lụa hiện đại."},
        rating={"value": 4.5, "count": 4600, "source": "Google", "as_of": "2026-07"},
        review_vi="Người yêu nghệ thuật đánh giá rất cao bộ sưu tập tranh sơn mài, lụa và tượng cổ. Nhiều khách nước ngoài khen cách trưng bày theo dòng thời gian; một số cho rằng vé và không gian xứng đáng, nên đi lúc vắng để thưởng thức trọn vẹn.",
        tags=["museum", "art"],
    ),
    rec(
        "bao-tang-ho-chi-minh",
        "Bảo tàng Hồ Chí Minh",
        "Ho Chi Minh Museum",
        "Музей Хо Ши Мина",
        ["museum"],
        21.0361, 105.8339,
        "19 phố Ngọc Hà, quận Ba Đình, Hà Nội",
        "Bảo tàng Hồ Chí Minh giới thiệu cuộc đời và sự nghiệp của Chủ tịch Hồ Chí Minh qua nghệ thuật trưng bày hiện đại, giàu tính biểu tượng. Tòa nhà hình bông sen trắng nằm ngay cạnh Lăng Bác và Chùa Một Cột.",
        "The Ho Chi Minh Museum presents the life and work of President Ho Chi Minh through a modern, symbol-rich exhibition. Its building, shaped like a white lotus, stands beside the Mausoleum and the One Pillar Pagoda.",
        "Музей Хо Ши Мина рассказывает о жизни и деятельности президента Хо Ши Мина с помощью современной, насыщенной символами экспозиции. Здание в форме белого лотоса стоит рядом с мавзолеем и Пагодой на одном столбе.",
        "Khánh thành năm 1990 nhân kỷ niệm 100 năm ngày sinh Chủ tịch Hồ Chí Minh, bảo tàng nằm trong quần thể quảng trường Ba Đình lịch sử, ngay cạnh Lăng Bác và Chùa Một Cột. Tòa nhà lớn màu trắng được thiết kế cách điệu hình bông sen — loài hoa gắn với quê hương và phẩm chất thanh cao của Người. Bên trong, phần trưng bày kể lại hành trình cuộc đời Bác từ thời niên thiếu ở Nghệ An, những năm bôn ba tìm đường cứu nước qua nhiều châu lục, tới khi lãnh đạo cách mạng và lập nên nước Việt Nam Dân chủ Cộng hòa. Điều đặc biệt của bảo tàng là ngôn ngữ trưng bày hiện đại, giàu tính ẩn dụ: các gian được bố trí theo chủ đề, kết hợp hiện vật, hình ảnh, tài liệu với những biểu tượng nghệ thuật lớn phản ánh bối cảnh thế giới cùng thời. Du khách vừa tìm hiểu tiểu sử một nhân vật lịch sử, vừa cảm nhận không khí của thế kỷ 20 đầy biến động. Bảo tàng thường được ghép cùng hành trình viếng Lăng, thăm Nhà sàn và Chùa Một Cột, tạo thành cụm tham quan quan trọng bậc nhất ở khu Ba Đình.",
        "Opened in 1990 for the centenary of President Ho Chi Minh's birth, the museum lies within the historic Ba Dinh Square complex, next to the Mausoleum and the One Pillar Pagoda. The large white building is stylised as a lotus blossom — a flower tied to his homeland and to his ideals of purity. Inside, the exhibition follows his life from his youth in Nghe An, through the years he travelled across continents seeking a path to save his country, to his leadership of the revolution and the founding of the Democratic Republic of Vietnam. What sets the museum apart is its modern, metaphor-rich display: themed halls combine artefacts, photographs and documents with large artistic symbols reflecting the world context of each period. Visitors learn the biography of a historic figure while sensing the turbulent atmosphere of the twentieth century. The museum is usually combined with a visit to the Mausoleum, the stilt house and the One Pillar Pagoda, forming one of the most important sightseeing clusters in the Ba Dinh district.",
        "Открытый в 1990 году к столетию со дня рождения президента Хо Ши Мина, музей расположен в историческом ансамбле площади Бадинь, рядом с мавзолеем и Пагодой на одном столбе. Крупное белое здание стилизовано под цветок лотоса — символ его родины и идеалов чистоты. Внутри экспозиция прослеживает его жизнь от юности в провинции Нгеан через годы странствий по континентам в поисках пути спасения страны до руководства революцией и основания Демократической Республики Вьетнам. Особенность музея — современный, насыщенный метафорами показ: тематические залы соединяют предметы, фотографии и документы с крупными художественными символами, отражающими мировой контекст каждой эпохи. Посетители узнают биографию исторической личности и одновременно ощущают бурную атмосферу XX века. Осмотр музея обычно объединяют с посещением мавзолея, свайного дома и Пагоды на одном столбе, образуя один из важнейших экскурсионных ансамблей района Бадинь.",
        ["Tòa nhà cách điệu hình bông sen trắng", "Trưng bày hiện đại, giàu biểu tượng về cuộc đời Chủ tịch Hồ Chí Minh", "Nằm trong cụm di tích Ba Đình, cạnh Lăng Bác và Chùa Một Cột"],
        ["Building stylised as a white lotus blossom", "Modern, symbol-rich display of President Ho Chi Minh's life", "Part of the Ba Dinh cluster, beside the Mausoleum and One Pillar Pagoda"],
        ["Здание в форме белого лотоса", "Современная, символичная экспозиция о жизни президента Хо Ши Мина", "В ансамбле Бадинь, рядом с мавзолеем и Пагодой на одном столбе"],
        {"hours_vi": "8:00-12:00 và 14:00-16:30; thường đóng chiều thứ Hai và thứ Sáu.", "ticket_vi": "Khoảng 40.000 VND/người.", "duration_vi": "Khoảng 1-1,5 giờ.", "best_time_vi": "Buổi sáng, kết hợp viếng Lăng Bác (thường mở buổi sáng).", "tips_vi": "Kiểm tra lịch mở cửa của khu Lăng; ăn mặc lịch sự; đi cùng cụm Ba Đình để tiết kiệm thời gian."},
        rating={"value": 4.4, "count": 8100, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách thấy cách trưng bày sáng tạo, khác lạ so với bảo tàng truyền thống. Nhiều người thích kiến trúc bông sen và vị trí thuận tiện trong cụm Ba Đình; một số nói phần biểu tượng nghệ thuật cần thuyết minh mới hiểu hết.",
        tags=["museum", "historic"],
    ),
    rec(
        "khu-di-tich-phu-chu-tich",
        "Khu di tích Phủ Chủ tịch (Nhà sàn Bác Hồ)",
        "Presidential Palace Historical Site (Ho Chi Minh's Stilt House)",
        "Мемориальный комплекс Президентского дворца (свайный дом Хо Ши Мина)",
        ["palace", "monument", "park_garden"],
        21.0390, 105.8340,
        "Số 1 phố Hoàng Hoa Thám / Ngọc Hà, quận Ba Đình, Hà Nội",
        "Khu di tích Phủ Chủ tịch là nơi Chủ tịch Hồ Chí Minh sống và làm việc từ 1954 đến 1969. Điểm nhấn là ngôi nhà sàn gỗ giản dị bên ao cá, tương phản với tòa Phủ Chủ tịch kiểu Pháp nguy nga gần đó.",
        "The Presidential Palace Historical Site is where President Ho Chi Minh lived and worked from 1954 to 1969. Its centrepiece is a simple wooden stilt house beside a fish pond, in quiet contrast to the grand French-era Presidential Palace nearby.",
        "Мемориальный комплекс Президентского дворца — место, где президент Хо Ши Мин жил и работал с 1954 по 1969 год. Его сердце — простой деревянный свайный дом у рыбного пруда, тихо контрастирующий с пышным Президентским дворцом французской эпохи неподалёку.",
        "Nằm trong khuôn viên xanh mát phía sau Lăng Bác, khu di tích Phủ Chủ tịch gắn liền với 15 năm cuối đời của Chủ tịch Hồ Chí Minh. Tòa Phủ Chủ tịch bốn tầng màu vàng, xây thời Pháp làm dinh Toàn quyền Đông Dương, nay chỉ dùng cho nghi lễ; điều khiến du khách xúc động là Bác đã không ở trong dinh thự sang trọng ấy mà chọn sống trong ngôi nhà sàn gỗ mộc mạc dựng năm 1958, mô phỏng nhà sàn vùng Việt Bắc. Ngôi nhà nhỏ hai tầng, tầng dưới để tiếp khách và họp, tầng trên là phòng ngủ và phòng làm việc đơn sơ với bàn ghế, sách vở còn giữ nguyên. Bên cạnh là ao cá Bác thường cho ăn mỗi chiều, vườn cây trái với những loài cây từ khắp mọi miền, con đường xoài rợp bóng. Du khách còn thăm nhà 54, nhà 67 và chiếc xe Bác từng dùng. Tất cả toát lên lối sống giản dị, gần gũi thiên nhiên và tinh thần thanh cao của Người. Đây là điểm dừng chân đầy cảm xúc trong hành trình khám phá khu Ba Đình lịch sử.",
        "Set in green grounds behind the Mausoleum, the Presidential Palace Historical Site is bound up with the last fifteen years of President Ho Chi Minh's life. The four-storey yellow Presidential Palace, built by the French as the residence of the Governor-General of Indochina, is now used only for ceremonies; what moves visitors is that Ho Chi Minh chose not to live in that grand mansion but in a plain wooden stilt house built in 1958, modelled on the dwellings of the Viet Bac highlands. The small two-level house has a lower floor for receiving guests and meetings and, above, a simple bedroom and study with desk, chairs and books kept as they were. Beside it lies the fish pond he fed each afternoon, an orchard of trees gathered from every region and a shaded mango avenue. Visitors also see House 54, House 67 and a car he used. Everything expresses his simple way of life, his closeness to nature and his lofty spirit. It is a deeply moving stop on any tour of the historic Ba Dinh district.",
        "В зелёном парке за мавзолеем мемориальный комплекс Президентского дворца связан с последними пятнадцатью годами жизни президента Хо Ши Мина. Четырёхэтажный жёлтый Президентский дворец, построенный французами как резиденция генерал-губернатора Индокитая, теперь используется лишь для церемоний; посетителей трогает то, что Хо Ши Мин предпочёл жить не в этом роскошном особняке, а в простом деревянном свайном доме 1958 года, повторяющем жилища нагорья Вьетбак. В небольшом двухъярусном доме нижний этаж служил для приёма гостей и совещаний, а наверху — скромные спальня и рабочий кабинет со столом, стульями и книгами, сохранёнными как были. Рядом — рыбный пруд, который он кормил каждый вечер, сад с деревьями со всех концов страны и тенистая манговая аллея. Гости видят также дом 54, дом 67 и автомобиль, которым он пользовался. Всё говорит о его простом образе жизни, близости к природе и высоком духе. Это глубоко трогательная остановка на маршруте по историческому району Бадинь.",
        ["Nhà sàn gỗ giản dị của Bác Hồ bên ao cá", "Tương phản với dinh Toàn quyền kiểu Pháp bề thế", "Vườn cây, đường xoài và không gian xanh yên bình"],
        ["Ho Chi Minh's simple wooden stilt house by a fish pond", "Contrast with the grand French Governor-General's palace", "Orchards, a mango avenue and peaceful green grounds"],
        ["Простой деревянный свайный дом Хо Ши Мина у рыбного пруда", "Контраст с пышным французским дворцом генерал-губернатора", "Сады, манговая аллея и тихая зелень"],
        {"hours_vi": "7:30-11:00 và 13:30-16:00; kiểm tra lịch theo mùa.", "ticket_vi": "Khoảng 40.000 VND/người.", "duration_vi": "Khoảng 1 giờ.", "best_time_vi": "Buổi sáng, ghép cùng viếng Lăng Bác và Chùa Một Cột.", "tips_vi": "Ăn mặc lịch sự, đi theo lối tham quan quy định; đường đi bộ nhiều nên mang giày thoải mái."},
        rating={"value": 4.6, "count": 9400, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách xúc động trước sự giản dị của ngôi nhà sàn và khuôn viên xanh mát. Nhiều người coi đây là điểm ý nghĩa nhất khu Ba Đình; một số lưu ý nên đi sớm cùng buổi viếng Lăng để tránh nắng và đông.",
        tags=["historic", "outdoor", "top"],
    ),
    rec(
        "cot-co-ha-noi",
        "Cột cờ Hà Nội (Kỳ đài)",
        "Hanoi Flag Tower",
        "Ханойская флаговая башня",
        ["monument", "fortress"],
        21.0324, 105.8406,
        "28A Điện Biên Phủ, quận Ba Đình, Hà Nội (trong Bảo tàng Lịch sử Quân sự)",
        "Cột cờ Hà Nội là kỳ đài cao hơn 33 mét, xây dưới triều Nguyễn đầu thế kỷ 19 và là một trong những biểu tượng của thủ đô. Đây là công trình hiếm hoi còn nguyên vẹn của thành Hà Nội xưa.",
        "The Hanoi Flag Tower is a flag pedestal over 33 metres high, built under the Nguyen dynasty in the early nineteenth century and one of the capital's emblems. It is among the few structures of the old Hanoi citadel to survive intact.",
        "Ханойская флаговая башня — флаговый постамент высотой более 33 метров, возведённый при династии Нгуен в начале XIX века и ставший одним из символов столицы. Это одно из немногих сохранившихся в целости сооружений старой ханойской цитадели.",
        "Cột cờ Hà Nội, hay Kỳ đài, được xây dựng trong khoảng năm 1805-1812 dưới triều vua Gia Long, nằm ở phía nam Hoàng thành Thăng Long. Công trình cao hơn 33 mét (tính cả trụ treo cờ), gồm ba tầng đế hình chóp cụt vuông xếp chồng và thân cột hình trụ tám cạnh, bên trong có cầu thang xoắn ốc dẫn lên vọng lâu trên đỉnh. Những ô cửa nhỏ hình hoa thị và hình rẻ quạt vừa lấy sáng, thông gió, vừa tạo nét duyên dáng cho khối kiến trúc quân sự. Trải qua bao biến động lịch sử, khi phần lớn thành Hà Nội bị phá dỡ thời Pháp thuộc, Cột cờ vẫn đứng vững và trở thành nhân chứng của thủ đô ngàn năm. Ngày 10 tháng 10 năm 1954, lá cờ đỏ sao vàng tung bay trên đỉnh cột trong ngày tiếp quản Thủ đô, khắc sâu hình ảnh Cột cờ vào ký ức dân tộc. Hiện nay công trình nằm trong khuôn viên Bảo tàng Lịch sử Quân sự Việt Nam; du khách có thể leo lên vọng lâu để phóng tầm mắt ngắm khu vực Ba Đình và cảm nhận chiều sâu lịch sử của Hà Nội.",
        "The Hanoi Flag Tower, or Ky Dai, was built between about 1805 and 1812 under Emperor Gia Long, at the southern side of the Thang Long Imperial Citadel. It rises more than 33 metres, including the flag mast, with three stacked square truncated-pyramid tiers and an octagonal cylindrical shaft holding a spiral staircase up to a watch pavilion at the top. Small flower- and fan-shaped openings admit light and air while lending grace to this military structure. Through many upheavals — when most of the Hanoi citadel was demolished in the colonial era — the Flag Tower stood firm and became a witness to the thousand-year capital. On 10 October 1954, the red flag with a golden star flew from its summit on the day the capital was handed back, fixing the tower in the nation's memory. Today it stands within the grounds of the Vietnam Military History Museum; visitors can climb to the watch pavilion for a sweeping view over the Ba Dinh area and a strong sense of Hanoi's historical depth.",
        "Ханойская флаговая башня, или Кидай, была построена примерно между 1805 и 1812 годами при императоре Зя Лонге, у южной стороны императорской цитадели Тханглонг. Она поднимается более чем на 33 метра вместе с флагштоком и состоит из трёх составленных друг на друга квадратных усечённых пирамид и восьмигранного цилиндрического ствола со спиральной лестницей, ведущей к смотровому павильону на вершине. Небольшие проёмы в форме цветов и вееров пропускают свет и воздух, придавая изящество этому военному сооружению. Пережив множество потрясений — когда большая часть ханойской цитадели была снесена в колониальную эпоху, — башня устояла и стала свидетелем тысячелетней столицы. 10 октября 1954 года красный флаг с золотой звездой взвился над её вершиной в день возвращения столицы, навсегда запечатлев башню в народной памяти. Сегодня она стоит на территории Музея военной истории Вьетнама; посетители могут подняться к смотровому павильону ради широкого вида на район Бадинь и ощущения исторической глубины Ханоя.",
        ["Kỳ đài cao hơn 33 m, xây thời vua Gia Long", "Công trình hiếm hoi còn nguyên vẹn của thành Hà Nội xưa", "Gắn với ngày tiếp quản Thủ đô 10/10/1954"],
        ["Flag pedestal over 33 m high, built under Emperor Gia Long", "A rare intact structure of the old Hanoi citadel", "Linked to the handover of the capital on 10 October 1954"],
        ["Флаговый постамент высотой более 33 м, эпохи императора Зя Лонга", "Редкое уцелевшее сооружение старой ханойской цитадели", "Связана с возвращением столицы 10 октября 1954 года"],
        {"hours_vi": "Theo giờ mở cửa Bảo tàng Lịch sử Quân sự, khoảng 8:00-16:30 (thường nghỉ một số ngày trong tuần).", "ticket_vi": "Vé tham quan bảo tàng, khoảng 40.000 VND.", "duration_vi": "Khoảng 30-45 phút.", "best_time_vi": "Buổi sáng; trời quang để ngắm cảnh từ vọng lâu.", "tips_vi": "Bậc thang lên đỉnh khá hẹp và tối; kết hợp tham quan bảo tàng trong cùng khuôn viên."},
        rating={"value": 4.4, "count": 3800, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách thích leo lên đỉnh ngắm toàn cảnh và tìm hiểu lịch sử. Nhiều người xem đây là biểu tượng quen thuộc của Hà Nội; một số nhắc cầu thang bên trong hẹp, nên đi cẩn thận.",
        tags=["historic", "monument", "viewpoint"],
    ),
    rec(
        "o-quan-chuong",
        "Ô Quan Chưởng",
        "Quan Chuong Gate (Old East Gate)",
        "Ворота Куантьыонг",
        ["fortress", "monument"],
        21.0378, 105.8516,
        "Phố Ô Quan Chưởng, phường Đồng Xuân, quận Hoàn Kiếm, Hà Nội",
        "Ô Quan Chưởng là cửa ô duy nhất còn lại của tòa thành đất bao quanh kinh thành Thăng Long xưa, xây năm 1749. Cổng gạch cổ kính với vọng lâu là chứng tích quý giá ngay cửa ngõ khu phố cổ.",
        "Quan Chuong Gate is the only surviving gate of the earthen rampart that once encircled old Thang Long, built in 1749. Its ancient brick archway and watch pavilion are a precious relic at the very entrance to the Old Quarter.",
        "Ворота Куантьыонг — единственные уцелевшие ворота земляного вала, некогда окружавшего древний Тханглонг, построенные в 1749 году. Старинная кирпичная арка со смотровым павильоном — драгоценная реликвия у самого входа в Старый квартал.",
        "Ô Quan Chưởng, tên chữ là Đông Hà Môn, được xây năm 1749 dưới thời vua Lê Hiển Tông và tu bổ vào thế kỷ 19. Đây là cửa ô cuối cùng còn sót lại trong số nhiều cửa ô của lũy thành đất từng bao quanh kinh thành Thăng Long, nơi kiểm soát người và hàng hóa ra vào phía đông thành, hướng ra sông Hồng. Cổng xây bằng gạch theo kiểu vọng lâu, gồm một cửa chính lớn cuốn vòm và hai cửa phụ nhỏ hai bên, phía trên là chòi canh có mái. Trên tường cổng vẫn còn tấm bia đá khắc lệnh của Tổng đốc Hoàng Diệu năm 1881 cấm binh lính sách nhiễu dân qua lại. Tên gọi Ô Quan Chưởng gắn với sự tích một viên quan Chưởng cơ cùng binh lính đã anh dũng chống Pháp và hy sinh tại đây năm 1873. Trải qua gần ba thế kỷ, cổng thành rêu phong vẫn đứng vững giữa phố phường tấp nập, là biểu tượng cho sức sống của Hà Nội cổ. Nằm ngay đầu khu phố cổ, gần chợ Đồng Xuân và sông Hồng, đây là điểm check-in và tìm hiểu lịch sử được nhiều du khách yêu thích.",
        "Quan Chuong Gate, formally called Dong Ha Mon, was built in 1749 under Emperor Le Hien Tong and restored in the nineteenth century. It is the last surviving gate among the many that once pierced the earthen rampart encircling old Thang Long, controlling people and goods entering the city from the east, towards the Red River. Built of brick in watch-pavilion style, it has one large arched main passage flanked by two smaller side passages, with a roofed lookout above. On the gate wall a stone stele still bears an 1881 order by Governor Hoang Dieu forbidding soldiers from harassing passers-by. The name Quan Chuong recalls a commanding officer (Chuong Co) who, with his men, resisted the French and fell here in 1873. After nearly three centuries the moss-covered gate still stands amid busy streets, a symbol of old Hanoi's endurance. Right at the head of the Old Quarter, near Dong Xuan Market and the Red River, it is a much-loved spot for photos and for touching the city's history.",
        "Ворота Куантьыонг, официально называемые Донгхамон, были построены в 1749 году при императоре Ле Хиен Тонге и отреставрированы в XIX веке. Это последние уцелевшие ворота из многих, что некогда прорезали земляной вал вокруг древнего Тханглонга, они контролировали въезд людей и товаров в город с востока, со стороны Красной реки. Сложенные из кирпича в стиле сторожевого павильона, они имеют один большой арочный проезд с двумя меньшими боковыми проходами и крытую вышку сверху. На стене ворот до сих пор сохранилась каменная стела с указом губернатора Хоанг Зьеу 1881 года, запрещавшим солдатам притеснять прохожих. Название Куантьыонг напоминает о командире (тьыонг ко), который вместе со своими воинами оборонялся от французов и пал здесь в 1873 году. Спустя почти три века поросшие мхом ворота всё ещё стоят среди оживлённых улиц — символ стойкости старого Ханоя. У самого начала Старого квартала, рядом с рынком Донгсуан и Красной рекой, это любимое место для фотографий и знакомства с историей города.",
        ["Cửa ô duy nhất còn lại của thành Thăng Long xưa (1749)", "Bia đá khắc lệnh cấm sách nhiễu dân của Tổng đốc Hoàng Diệu", "Nằm ngay đầu khu phố cổ, gần chợ Đồng Xuân"],
        ["The only surviving gate of old Thang Long (1749)", "A stone stele bearing Governor Hoang Dieu's anti-harassment order", "At the head of the Old Quarter, near Dong Xuan Market"],
        ["Единственные уцелевшие ворота старого Тханглонга (1749)", "Каменная стела с указом губернатора Хоанг Зьеу", "У начала Старого квартала, рядом с рынком Донгсуан"],
        {"hours_vi": "Xem tự do ngoài trời cả ngày.", "ticket_vi": "Miễn phí.", "duration_vi": "Khoảng 15-20 phút.", "best_time_vi": "Sáng sớm hoặc chiều tối; đẹp khi lên đèn.", "tips_vi": "Cổng nằm ở ngã tư đông xe, chú ý an toàn khi chụp ảnh; kết hợp dạo phố cổ và chợ Đồng Xuân."},
        rating={"value": 4.4, "count": 4200, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách thích nét cổ kính hiếm hoi còn sót lại giữa phố cổ và coi đây là điểm chụp ảnh đẹp. Nhiều người ghé khi đi bộ quanh phố cổ; một số lưu ý giao thông quanh cổng khá đông đúc.",
        tags=["historic", "monument", "free"],
    ),
    rec(
        "cho-dong-xuan",
        "Chợ Đồng Xuân",
        "Dong Xuan Market",
        "Рынок Донгсуан",
        ["square_street", "monument"],
        21.0382, 105.8496,
        "Phố Đồng Xuân, phường Đồng Xuân, quận Hoàn Kiếm, Hà Nội",
        "Chợ Đồng Xuân là khu chợ lớn và lâu đời nhất trong khu phố cổ Hà Nội, có từ cuối thế kỷ 19. Đây là trung tâm buôn bán sầm uất với đủ loại hàng hóa và khu ẩm thực đường phố hấp dẫn về đêm.",
        "Dong Xuan Market is the largest and oldest market in Hanoi's Old Quarter, dating from the late nineteenth century. It is a bustling trading hub offering every kind of goods, with a lively street-food scene by night.",
        "Рынок Донгсуан — крупнейший и старейший рынок Старого квартала Ханоя, существующий с конца XIX века. Это оживлённый торговый центр со всевозможными товарами и живой уличной едой по вечерам.",
        "Chợ Đồng Xuân được người Pháp xây dựng kiên cố năm 1889 trên nền một khu chợ họp lâu đời gần cửa sông Tô Lịch, trở thành ngôi chợ lớn nhất và biểu tượng thương mại của Hà Nội. Mặt tiền chợ với năm vòm cửa cuốn đặc trưng đã in đậm trong ký ức bao thế hệ người dân thủ đô. Bên trong, ba tầng lầu bày bán đủ loại mặt hàng: vải vóc, quần áo, giày dép, đồ gia dụng, phụ kiện, đồ khô, bánh kẹo, hàng lưu niệm, phần lớn theo hình thức bán buôn cho tiểu thương khắp miền Bắc. Chợ cũng là nơi lưu giữ ký ức lịch sử: khu vực này từng diễn ra những trận chiến ác liệt trong những ngày đầu Toàn quốc kháng chiến cuối năm 1946, nay có đài tưởng niệm nhắc nhớ. Khi màn đêm buông xuống, khu vực quanh chợ và phố Đồng Xuân biến thành thiên đường ẩm thực đường phố với bún riêu, bún chả, chè, ốc, hoa quả dầm; cuối tuần còn có chợ đêm kéo dài qua nhiều tuyến phố cổ. Đến chợ Đồng Xuân, du khách không chỉ mua sắm mà còn cảm nhận nhịp sống buôn bán rất Hà Nội, náo nhiệt mà thân thuộc.",
        "Dong Xuan Market was solidly rebuilt by the French in 1889 on the site of a long-established market near the mouth of the To Lich River, becoming Hanoi's largest market and a symbol of its commerce. Its façade, with five distinctive arched bays, is fixed in the memory of generations of city dwellers. Inside, three floors sell every kind of goods — fabrics, clothes, shoes, household items, accessories, dried foods, sweets and souvenirs — mostly wholesale to traders across the north. The market also holds historical memory: this area saw fierce fighting in the first days of the nationwide resistance in late 1946, now marked by a memorial. When night falls, the streets around the market and Dong Xuan Street turn into a street-food paradise, with bun rieu, bun cha, sweet soups, snails and fruit salads; at weekends a night market stretches through several old streets. At Dong Xuan, visitors not only shop but feel the very Hanoian rhythm of trade — busy yet familiar.",
        "Рынок Донгсуан был капитально перестроен французами в 1889 году на месте давнего рынка у устья реки Толить и стал крупнейшим рынком Ханоя и символом его торговли. Его фасад с пятью характерными арочными пролётами запечатлён в памяти поколений горожан. Внутри три этажа торгуют всевозможными товарами — тканями, одеждой, обувью, хозяйственными мелочами, аксессуарами, сухими продуктами, сладостями и сувенирами — в основном оптом для торговцев со всего севера. Рынок хранит и историческую память: здесь шли ожесточённые бои в первые дни всенародного Сопротивления в конце 1946 года, о чём напоминает мемориал. С наступлением вечера улицы вокруг рынка и улица Донгсуан превращаются в рай уличной еды — бунзиеу, бунтя, сладкие супы, улитки, фруктовые салаты; по выходным ночной рынок тянется через несколько старых улиц. На Донгсуане гости не только делают покупки, но и ощущают истинно ханойский ритм торговли — шумный и в то же время родной.",
        ["Chợ lớn và lâu đời nhất phố cổ, xây năm 1889", "Mặt tiền năm vòm cửa cuốn mang tính biểu tượng", "Khu ẩm thực và chợ đêm sôi động cuối tuần"],
        ["The largest and oldest Old Quarter market, built in 1889", "Iconic façade with five arched bays", "Lively street food and weekend night market"],
        ["Крупнейший и старейший рынок Старого квартала, 1889 год", "Знаковый фасад с пятью арочными пролётами", "Оживлённая уличная еда и ночной рынок по выходным"],
        {"hours_vi": "Khoảng 6:00-18:00; chợ đêm phố cổ tối thứ Sáu-Chủ nhật.", "ticket_vi": "Miễn phí vào chợ.", "duration_vi": "Khoảng 45-60 phút.", "best_time_vi": "Buổi tối cuối tuần để trải nghiệm chợ đêm và ẩm thực.", "tips_vi": "Nên mặc cả khi mua; giữ tư trang nơi đông người; thử món ăn ở ngõ phía sau chợ."},
        rating={"value": 4.2, "count": 12000, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách thấy chợ nhộn nhịp, nhiều hàng hóa và đồ ăn ngon, đặc biệt về đêm. Nhiều người thích không khí chợ đêm cuối tuần; một số nhắc chủ yếu bán buôn nên nhớ mặc cả và cẩn thận tư trang.",
        tags=["market", "shopping", "night"],
    ),
    rec(
        "cau-long-bien",
        "Cầu Long Biên",
        "Long Bien Bridge",
        "Мост Лонгбьен",
        ["bridge", "monument"],
        21.0440, 105.8555,
        "Bắc qua sông Hồng, nối quận Hoàn Kiếm với quận Long Biên, Hà Nội",
        "Cầu Long Biên là cây cầu thép bắc qua sông Hồng, do Pháp xây dựng đầu thế kỷ 20 và từng là một trong những cây cầu dài nhất châu Á. Chứng nhân của bao thăng trầm lịch sử, cầu nay là biểu tượng hoài niệm của Hà Nội.",
        "Long Bien Bridge is a steel bridge across the Red River, built by the French in the early twentieth century and once among the longest bridges in Asia. A witness to many historical upheavals, it is now a nostalgic emblem of Hanoi.",
        "Мост Лонгбьен — стальной мост через Красную реку, построенный французами в начале XX века и некогда один из длиннейших мостов Азии. Свидетель многих исторических потрясений, сегодня он — ностальгический символ Ханоя.",
        "Cầu Long Biên được người Pháp xây dựng trong những năm 1899-1902 và mang tên Toàn quyền Paul Doumer, là cây cầu thép đầu tiên bắc qua sông Hồng nối Hà Nội với vùng châu thổ phía bắc. Với chiều dài hơn 2.400 mét, thời đó cầu được coi là một trong những công trình đồ sộ nhất Đông Dương và cả châu Á, do hãng liên quan đến kỹ thuật của Gustave Eiffel tham gia. Kết cấu dầm thép hình răng cưa độc đáo, tuyến đường sắt chạy giữa và hai làn đường bộ hai bên đã trở thành hình ảnh quen thuộc. Cầu là chứng nhân của lịch sử: từng bị bom Mỹ đánh phá nhiều lần trong chiến tranh và được sửa chữa, vá víu bằng nhiều loại vật liệu, khiến các nhịp cầu mang dáng vẻ chắp nối rất riêng. Ngày nay xe lửa, xe máy, xe đạp và người đi bộ vẫn qua lại; du khách thường tản bộ trên cầu lúc bình minh hay hoàng hôn để ngắm sông Hồng, bãi giữa xanh mướt và chụp những bức ảnh hoài cổ. Long Biên không chỉ là công trình giao thông mà còn là ký ức sống động, lãng mạn của người Hà Nội qua hơn một thế kỷ.",
        "Long Bien Bridge was built by the French between 1899 and 1902 and named after Governor-General Paul Doumer; it was the first steel bridge across the Red River, linking Hanoi with the northern delta. More than 2,400 metres long, it was then considered one of the mightiest structures in Indochina and Asia, built with engineering linked to Gustave Eiffel's firm. Its distinctive saw-toothed steel girders, a railway running down the middle and two road lanes on either side became a familiar sight. The bridge is a witness to history: bombed repeatedly by US aircraft during the war and patched with many kinds of material, its spans have a uniquely mismatched look. Today trains, motorbikes, bicycles and pedestrians still cross it; visitors often stroll it at dawn or dusk to watch the Red River, the green sandbank island midstream and take nostalgic photographs. Long Bien is not merely a transport structure but a living, romantic memory of Hanoi across more than a century.",
        "Мост Лонгбьен был построен французами между 1899 и 1902 годами и назван в честь генерал-губернатора Поля Думера; это был первый стальной мост через Красную реку, связавший Ханой с северной дельтой. Длиной более 2400 метров, он тогда считался одним из величайших сооружений Индокитая и Азии и был возведён с участием инженерной фирмы, связанной с Гюставом Эйфелем. Характерные зубчатые стальные фермы, железная дорога посередине и две автомобильные полосы по бокам стали привычным видом. Мост — свидетель истории: во время войны его многократно бомбила американская авиация, и его латали разными материалами, отчего пролёты приобрели неповторимый разнородный облик. Сегодня по нему по-прежнему идут поезда, мотоциклы, велосипеды и пешеходы; гости часто гуляют по мосту на рассвете или закате, любуясь Красной рекой, зелёным островом-отмелью посреди русла, и делают ностальгические снимки. Лонгбьен — не просто транспортное сооружение, а живая, романтичная память Ханоя, охватывающая более века.",
        ["Cầu thép đầu tiên qua sông Hồng, xây 1899-1902", "Kết cấu dầm thép răng cưa và tuyến đường sắt chạy giữa", "Điểm ngắm bình minh, hoàng hôn và chụp ảnh hoài cổ"],
        ["The first steel bridge across the Red River, 1899-1902", "Saw-toothed steel girders and a central railway line", "A spot for sunrise, sunset and nostalgic photos"],
        ["Первый стальной мост через Красную реку, 1899-1902", "Зубчатые стальные фермы и центральная железная дорога", "Место для рассветов, закатов и ностальгических фото"],
        {"hours_vi": "Đi bộ tự do cả ngày (đường bộ hai bên).", "ticket_vi": "Miễn phí.", "duration_vi": "Khoảng 45-60 phút nếu đi bộ và chụp ảnh.", "best_time_vi": "Bình minh hoặc hoàng hôn; trời quang để ngắm sông Hồng.", "tips_vi": "Đi sát lối bộ hành, tránh làn tàu và xe máy; kết hợp thăm bãi giữa và chợ Long Biên."},
        rating={"value": 4.5, "count": 14000, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách yêu thích vẻ cổ kính, hoài niệm và view sông Hồng, nhất là lúc hoàng hôn. Nhiều bạn trẻ tới chụp ảnh; một số nhắc cầu đã cũ, đông xe máy nên cần chú ý an toàn khi đi bộ.",
        tags=["historic", "outdoor", "viewpoint"],
    ),
    rec(
        "den-bach-ma",
        "Đền Bạch Mã",
        "Bach Ma Temple",
        "Храм Батьма",
        ["church", "monument"],
        21.0357, 105.8502,
        "76 phố Hàng Buồm, quận Hoàn Kiếm, Hà Nội",
        "Đền Bạch Mã là một trong Thăng Long tứ trấn, trấn giữ phía đông kinh thành và được coi là ngôi đền cổ nhất khu phố cổ Hà Nội. Đền thờ thần Long Đỗ, vị thần bảo hộ của thành Thăng Long.",
        "Bach Ma Temple is one of the Four Sacred Temples of Thang Long, guarding the eastern gate and regarded as the oldest temple in Hanoi's Old Quarter. It honours the deity Long Do, the guardian spirit of Thang Long.",
        "Храм Батьма — один из «Четырёх священных храмов» Тханглонга, охранявший восточные врата и считающийся старейшим храмом Старого квартала Ханоя. Он посвящён божеству Лонгдо, духу-хранителю Тханглонга.",
        "Nằm khiêm nhường trên phố Hàng Buồm nhộn nhịp, đền Bạch Mã (Ngựa Trắng) là một trong Thăng Long tứ trấn, trấn giữ phương đông và được xem là ngôi đền cổ nhất khu phố cổ. Đền thờ thần Long Đỗ, thần bảo hộ của kinh thành Thăng Long. Tương truyền khi vua Lý Thái Tổ dời đô ra Thăng Long năm 1010 và cho đắp thành nhưng cứ đắp lại lở, nhà vua tới cầu khấn thì thấy một con ngựa trắng từ trong đền đi ra, vòng quanh một lượt rồi biến mất; vua cho xây thành theo dấu chân ngựa và thành đứng vững, từ đó phong thần làm Thành hoàng và đền mang tên Bạch Mã. Kiến trúc đền còn giữ nhiều nét cổ với hệ thống cột gỗ lim, mái vòm, những mảng chạm khắc tinh xảo, hoành phi câu đối sơn son thếp vàng và kiệu thờ, hương án cổ. Không gian trầm mặc, khói hương nghi ngút giữa khu phố buôn bán tấp nập tạo nên sự tương phản đầy cuốn hút. Với người Hà Nội, đền Bạch Mã là chốn linh thiêng gắn với cội nguồn dựng đô; với du khách, đây là điểm đến giàu chiều sâu văn hóa ngay trong lòng phố cổ.",
        "Standing modestly on busy Hang Buom Street, Bach Ma (White Horse) Temple is one of the Four Sacred Temples of Thang Long, guarding the east and regarded as the oldest temple in the Old Quarter. It honours Long Do, the guardian deity of the capital. Legend tells that when King Ly Thai To moved the capital to Thang Long in 1010 and built ramparts that kept collapsing, he came here to pray and saw a white horse emerge from the temple, circle once and vanish; the king built the wall along the horse's tracks and it held firm, whereupon he named the deity the city's tutelary god and the temple Bach Ma. The building keeps many ancient features — ironwood columns, vaulted roofs, exquisite carvings, gilded lacquered boards and couplets, old palanquins and altars. Its hushed, incense-filled space amid a bustling commercial quarter makes a captivating contrast. For Hanoians, Bach Ma is a sacred place bound to the founding of the capital; for visitors, it is a culturally rich stop right in the heart of the Old Quarter.",
        "Скромно стоящий на оживлённой улице Хангбуом храм Батьма (Белой лошади) — один из «Четырёх священных храмов» Тханглонга, страж востока и, как считается, старейший храм Старого квартала. Он посвящён Лонгдо, божеству-хранителю столицы. Легенда гласит, что когда король Ли Тхай То перенёс столицу в Тханглонг в 1010 году и возводил валы, которые всё время обрушивались, он пришёл сюда помолиться и увидел белую лошадь, вышедшую из храма, обошедшую круг и исчезнувшую; король построил стену по следам лошади, и она устояла, после чего он объявил божество городским покровителем, а храм назвал Батьма. Здание сохранило многие древние черты — колонны из железного дерева, сводчатые крыши, изысканную резьбу, позолоченные лаковые таблички и парные надписи, старинные паланкины и алтари. Его тихое, напоённое благовониями пространство среди шумного торгового квартала создаёт пленительный контраст. Для ханойцев Батьма — священное место, связанное с основанием столицы; для гостей — насыщенная культурой остановка в самом сердце Старого квартала.",
        ["Một trong Thăng Long tứ trấn, trấn giữ phương đông", "Ngôi đền được coi là cổ nhất khu phố cổ Hà Nội", "Gắn với truyền thuyết ngựa trắng và việc dựng thành Thăng Long"],
        ["One of the Four Sacred Temples of Thang Long, guarding the east", "Regarded as the oldest temple in Hanoi's Old Quarter", "Tied to the white-horse legend and the building of the citadel"],
        ["Один из «Четырёх священных храмов» Тханглонга, страж востока", "Считается старейшим храмом Старого квартала Ханоя", "Связан с легендой о белой лошади и возведении цитадели"],
        {"hours_vi": "Khoảng 8:00-17:00; đông vào ngày rằm, mùng một.", "ticket_vi": "Miễn phí.", "duration_vi": "Khoảng 20-30 phút.", "best_time_vi": "Sáng sớm hoặc khi dạo phố cổ; dịp lễ rất đông.", "tips_vi": "Ăn mặc lịch sự, giữ yên tĩnh; kết hợp khám phá các phố Hàng và chợ Đồng Xuân gần đó."},
        rating={"value": 4.5, "count": 3100, "source": "Google", "as_of": "2026-07"},
        review_vi="Du khách ấn tượng với nét cổ kính, linh thiêng và bề dày lịch sử của đền ngay giữa phố cổ. Nhiều người thích truyền thuyết ngựa trắng; một số nói đền nhỏ, nằm khuất trên phố Hàng Buồm nên dễ đi lướt qua.",
        tags=["temple", "historic"],
    ),
]

d = json.load(open(F, encoding="utf-8")) if os.path.exists(F) else []
have = {p["slug"] for p in d}
added = [p for p in new if p["slug"] not in have]
d += added
json.dump(d, open(F, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("batch A: them", len(added), "/", len(new), "-> gio co", len(d))
