# -*- coding: utf-8 -*-
"""Nghệ An — batch 2 (9 địa điểm). Chèn an toàn."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
F = os.path.join(ROOT, "data", "regions", "vn-nghe-an.json")
REG, RN, FD, UPD = "vn-nghe-an", "Nghệ An", "Miền Trung", "2026-07-27"


def rec(slug, name_vi, name_en, name_ru, cats, lat, lon, addr, rating, review_vi,
        ps_vi, ps_en, ps_ru, pl_vi, pl_en, pl_ru, h_vi, h_en, h_ru, practical, tags, sources, photo=None):
    return {"id": f"{REG}-{slug}", "slug": slug, "region": REG, "country": "vietnam",
            "region_name_vi": RN, "federal_district": FD, "name_vi": name_vi, "name_ru": name_ru,
            "name_en": name_en, "categories": cats, "coordinates": {"lat": lat, "lon": lon},
            "address_vi": addr, "rating": rating, "review_summary_vi": review_vi,
            "presentation_short_vi": ps_vi, "presentation_short_en": ps_en, "presentation_short_ru": ps_ru,
            "presentation_long_vi": pl_vi, "presentation_long_en": pl_en, "presentation_long_ru": pl_ru,
            "highlights_vi": h_vi, "highlights_en": h_en, "highlights_ru": h_ru,
            "practical": practical, "photo": photo, "photo_credit": None, "official_site": None,
            "sources": sources, "tags": tags, "status": "enriched", "last_updated": UPD}


new = [

rec("bien-quynh",
    "Biển Quỳnh (Quỳnh Lưu)",
    "Quynh Beach (Quynh Luu)",
    "Пляж Куинь (Куиньлыу)",
    ["park_garden", "other"],
    19.1650, 105.6750,
    "Vùng biển các xã Quỳnh Bảng, Quỳnh Phương, Tiến Thủy (Quỳnh Lưu, Hoàng Mai), tỉnh Nghệ An",
    {"value": 4.3, "count": 1900, "source": "Google", "as_of": "2026-07"},
    "Bãi biển dài, cát mịn, còn hoang sơ, hải sản tươi ngon và rẻ; làng chài nhộn nhịp. Ít chen chúc hơn Cửa Lò, hợp nghỉ dưỡng bình dân, ngắm bình minh trên biển.",
    "Biển Quỳnh là tên gọi chung cho dải bãi biển đẹp, hoang sơ ở vùng Quỳnh Lưu – Hoàng Mai, phía bắc Nghệ An. Nơi đây có bãi cát dài phẳng mịn, nước biển trong, làng chài sầm uất và hải sản tươi ngon, là điểm nghỉ mát yên bình được nhiều du khách yêu thích.",
    "Quynh Beach is the collective name for the lovely, unspoilt stretch of coast in the Quynh Luu-Hoang Mai area of northern Nghe An. It offers long, flat, fine sand, clear water, busy fishing villages and fresh seafood, making it a peaceful seaside retreat that many travellers love.",
    "Пляж Куинь — общее название красивой нетронутой полосы побережья в районе Куиньлыу-Хоангмай на севере Нгеана. Здесь длинный, ровный и мелкий песок, чистая вода, оживлённые рыбацкие деревни и свежие морепродукты, что делает его тихим морским уголком, любимым многими путешественниками.",
    "Biển Quỳnh là tên gọi chung cho chuỗi các bãi tắm trải dài dọc bờ biển huyện Quỳnh Lưu và thị xã Hoàng Mai ở phía bắc tỉnh Nghệ An, cách thành phố Vinh khoảng 60–70 km. Khác với sự sầm uất của Cửa Lò, biển Quỳnh vẫn giữ được nét hoang sơ, mộc mạc với bãi cát vàng mịn thoai thoải, sóng êm và hàng phi lao xanh chạy dài ven bờ. Các bãi tắm nổi tiếng như Quỳnh Bảng, Quỳnh Phương, Quỳnh Nghĩa, Tiến Thủy thu hút du khách bởi không gian thoáng đãng, trong lành và cảm giác gần gũi với đời sống làng chài. Đây là vùng biển gắn với nghề đánh bắt lâu đời, mỗi sớm mai những đoàn thuyền đầy ắp cá tôm lại cập bến, tạo nên khung cảnh chợ cá nhộn nhịp, đầy sắc màu. Nhờ vậy, du khách đến biển Quỳnh có thể thưởng thức hải sản tươi sống với giá bình dân, từ ghẹ, mực, tôm đến các loại cá biển. Bình minh trên biển Quỳnh đặc biệt đẹp khi mặt trời đỏ rực nhô lên khỏi mặt nước, phía sau là những con thuyền và bóng người ngư dân. Với chi phí hợp lý, không khí yên bình và hải sản hấp dẫn, biển Quỳnh là lựa chọn lý tưởng cho những chuyến nghỉ dưỡng, dã ngoại tránh xa ồn ào phố thị.",
    "Quynh Beach is the collective name for a chain of bathing beaches running along the coast of Quynh Luu district and Hoang Mai town in northern Nghe An, about 60-70 km from Vinh City. Unlike the bustle of Cua Lo, Quynh Beach keeps its wild, rustic character, with gently sloping fine golden sand, calm waves and long rows of green casuarina trees. Famous beaches such as Quynh Bang, Quynh Phuong, Quynh Nghia and Tien Thuy draw visitors with their open, fresh air and closeness to fishing-village life. This is a coast of long-standing fisheries: each morning boats laden with fish and shrimp return to shore, creating a lively, colourful fish market. As a result, visitors can enjoy fresh seafood at modest prices, from crab, squid and shrimp to many kinds of sea fish. Sunrise over Quynh Beach is especially beautiful as the fiery red sun climbs from the water behind the boats and the silhouettes of fishermen. With reasonable costs, a peaceful atmosphere and tempting seafood, Quynh Beach is an ideal choice for a restful getaway far from the noise of the city.",
    "Пляж Куинь — общее название цепочки купальных пляжей вдоль побережья уезда Куиньлыу и города Хоангмай на севере Нгеана, примерно в 60-70 км от города Винь. В отличие от суеты Кыало, пляж Куинь сохраняет дикий, деревенский характер: полого спускающийся мелкий золотистый песок, спокойные волны и длинные ряды зелёных казуарин. Известные пляжи — Куиньбанг, Куиньфыонг, Куиньнгиа и Тьентхюи — привлекают гостей простором, свежим воздухом и близостью к жизни рыбацких деревень. Это побережье давних рыбных промыслов: каждое утро лодки, полные рыбы и креветок, возвращаются к берегу, создавая живой, красочный рыбный рынок. Благодаря этому гости могут отведать свежие морепродукты по скромным ценам — от крабов, кальмаров и креветок до разной морской рыбы. Восход над пляжем Куинь особенно красив, когда огненно-красное солнце поднимается из воды за лодками и силуэтами рыбаков. С разумными ценами, спокойной атмосферой и заманчивыми морепродуктами пляж Куинь — идеальный выбор для спокойного отдыха вдали от городского шума.",
    ["Bãi biển dài, hoang sơ, ít đông đúc hơn Cửa Lò",
     "Làng chài lâu đời, hải sản tươi ngon giá bình dân",
     "Bình minh trên biển tuyệt đẹp cùng cảnh thuyền cá cập bến"],
    ["Long, unspoilt beach, quieter than Cua Lo",
     "Age-old fishing villages with fresh, affordable seafood",
     "Beautiful sunrises with fishing boats returning to shore"],
    ["Длинный нетронутый пляж, спокойнее, чем Кыало",
     "Старинные рыбацкие деревни со свежими недорогими морепродуктами",
     "Красивые восходы с возвращающимися рыбацкими лодками"],
    {"hours_vi": "Cả ngày; tắm biển hợp buổi sáng và chiều.",
     "ticket_vi": "Miễn phí (có phí gửi xe, dịch vụ).",
     "duration_vi": "Nửa ngày đến cả ngày.",
     "best_time_vi": "Mùa hè (tháng 5–8); đi sớm ngắm bình minh và mua hải sản.",
     "tips_vi": "Mua hải sản tại chợ cá buổi sáng; mang kem chống nắng; hỏi giá dịch vụ trước."},
    ["beach", "nature", "seafood", "outdoor", "family", "daytrip"],
    [{"title": "Wikipedia (VI) — Quỳnh Lưu", "url": "https://vi.wikipedia.org/wiki/Qu%E1%BB%B3nh_L%C6%B0u"}]),

rec("truong-bon",
    "Khu di tích lịch sử Truông Bồn",
    "Truong Bon Historical Relic Site",
    "Мемориал Чыонгбон",
    ["monument", "museum"],
    18.8850, 105.4180,
    "Xã Mỹ Sơn, huyện Đô Lương, tỉnh Nghệ An",
    {"value": 4.7, "count": 2300, "source": "Google", "as_of": "2026-07"},
    "Địa chỉ đỏ xúc động tưởng niệm 13 chiến sĩ thanh niên xung phong hy sinh; khuôn viên trang nghiêm, thuyết minh cảm động. Nhiều đoàn về nguồn, dâng hương tri ân.",
    "Truông Bồn ở huyện Đô Lương là 'tọa độ lửa' huyền thoại trên tuyến đường chi viện thời chống Mỹ, nơi 13 chiến sĩ thanh niên xung phong hy sinh anh dũng ngày 31/10/1968. Khu di tích là 'địa chỉ đỏ' thiêng liêng để tưởng niệm và giáo dục truyền thống.",
    "Truong Bon in Do Luong district is a legendary 'coordinate of fire' on a wartime supply route, where 13 Youth Volunteer soldiers died heroically on 31 October 1968. The relic site is a sacred 'red address' for remembrance and patriotic education.",
    "Чыонгбон в уезде Долыонг — легендарная «огненная точка» на военной дороге снабжения, где 31 октября 1968 года героически погибли 13 бойцов молодёжного добровольческого отряда. Мемориал — священный «красный адрес» памяти и патриотического воспитания.",
    "Khu di tích lịch sử Truông Bồn nằm ở xã Mỹ Sơn, huyện Đô Lương, cách thành phố Vinh khoảng 30 km. Trong kháng chiến chống Mỹ, Truông Bồn là điểm nút giao thông trọng yếu trên tuyến đường chiến lược 15A, nơi mọi chuyến xe chi viện cho chiến trường miền Nam đều phải đi qua, vì thế trở thành 'tọa độ lửa' bị máy bay địch đánh phá ác liệt suốt ngày đêm. Tại đây, những đội thanh niên xung phong đã ngày đêm bám trụ, san lấp hố bom, thông đường cho xe qua. Rạng sáng 31 tháng 10 năm 1968, chỉ vài giờ trước khi có lệnh ngừng ném bom miền Bắc, một trận bom dữ dội đã cướp đi sinh mạng của 13 chiến sĩ thanh niên xung phong thuộc 'Tiểu đội thép', hầu hết còn rất trẻ. Sự hy sinh anh dũng của họ trở thành biểu tượng bất tử của chủ nghĩa anh hùng cách mạng. Ngày nay, khu di tích được xây dựng khang trang, trang nghiêm với đền thờ, nhà tưởng niệm, khu mộ và tượng đài, cùng hồ nước, cây xanh và các công trình tái hiện lịch sử. Mỗi năm, Truông Bồn đón hàng vạn lượt khách, cựu chiến binh, học sinh sinh viên về dâng hương tri ân và tìm hiểu về một trang sử bi tráng, hào hùng của dân tộc.",
    "The Truong Bon Historical Relic Site lies in My Son commune, Do Luong district, about 30 km from Vinh City. During the war against America, Truong Bon was a vital junction on strategic route 15A: every supply convoy heading to the southern front had to pass through, making it a 'coordinate of fire' pounded relentlessly by enemy aircraft. Here, teams of Youth Volunteers held their ground day and night, filling bomb craters and clearing the road for vehicles. At dawn on 31 October 1968, just hours before the order to halt bombing of the North, a fierce raid killed 13 Youth Volunteers of the 'Steel Squad', most of them very young. Their heroic sacrifice became an immortal symbol of revolutionary heroism. Today the site is dignified and well built, with a temple, memorial house, tombs and a monument, together with a lake, greenery and structures re-creating its history. Each year Truong Bon welcomes tens of thousands of visitors, veterans and students who come to offer incense in gratitude and learn about a tragic yet glorious chapter of the nation's history.",
    "Мемориал Чыонгбон находится в общине Мишон уезда Долыонг, примерно в 30 км от города Винь. Во время войны против США Чыонгбон был важнейшим узлом на стратегической дороге 15А: каждый конвой снабжения, идущий на южный фронт, должен был проходить здесь, что превратило его в «огненную точку», которую вражеская авиация нещадно бомбила днём и ночью. Здесь отряды молодых добровольцев держались круглые сутки, засыпая воронки и расчищая дорогу для машин. На рассвете 31 октября 1968 года, всего за несколько часов до приказа прекратить бомбардировки Севера, жестокий налёт унёс жизни 13 добровольцев «Стального отделения», большинство из которых были совсем юными. Их героическая жертва стала бессмертным символом революционного героизма. Сегодня мемориал благоустроен и торжественен: храм, дом памяти, могилы и монумент, а также озеро, зелень и сооружения, воссоздающие его историю. Ежегодно Чыонгбон принимает десятки тысяч посетителей, ветеранов и учащихся, приходящих воскурить благовония в знак благодарности и узнать о трагической, но славной странице истории народа.",
    ["Tưởng niệm 13 chiến sĩ thanh niên xung phong hy sinh 31/10/1968",
     "'Tọa độ lửa' trên tuyến đường 15A chi viện chiến trường miền Nam",
     "Đền thờ, nhà tưởng niệm, tượng đài; địa chỉ đỏ giáo dục truyền thống"],
    ["Memorial to 13 Youth Volunteers who died on 31 October 1968",
     "A 'coordinate of fire' on supply route 15A to the southern front",
     "Temple, memorial house and monument; a 'red address' for education"],
    ["Память о 13 молодых добровольцах, погибших 31 октября 1968 года",
     "«Огненная точка» на дороге снабжения 15А к южному фронту",
     "Храм, дом памяти и монумент; «красный адрес» воспитания"],
    {"hours_vi": "Khoảng 7:00–17:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 1–1,5 giờ.",
     "best_time_vi": "Dịp 27/7, 31/10 và các ngày lễ tri ân; quanh năm đều viếng được.",
     "tips_vi": "Giữ trang nghiêm, ăn mặc lịch sự; nên nghe thuyết minh để hiểu ý nghĩa lịch sử."},
    ["history", "memorial", "monument", "culture", "top", "outdoor"],
    [{"title": "Tỉnh ủy Nghệ An — Truông Bồn", "url": "https://nghean.dcs.vn/vi-vn/tin/truong-bon---bieu-tuong-cao-dep-cua-chu-nghia-anh-hung-cach-mang/24021-682955-868013"}]),

rec("den-qua-son",
    "Đền Quả Sơn",
    "Qua Son Temple",
    "Храм Куашон",
    ["church", "monument"],
    18.9250, 105.3480,
    "Xã Bồi Sơn, huyện Đô Lương, tỉnh Nghệ An",
    {"value": 4.6, "count": 900, "source": "Google", "as_of": "2026-07"},
    "Ngôi đền cổ linh thiêng dưới chân núi Quả, thờ Uy Minh Vương Lý Nhật Quang; cảnh quan đẹp bên sông Lam. Lễ hội đầu năm đông vui với lễ rước độc đáo.",
    "Đền Quả Sơn ở huyện Đô Lương là một trong 'tứ đại' đền linh thiêng của xứ Nghệ, thờ Uy Minh Vương Lý Nhật Quang – vị Tri châu có công lớn với vùng đất Nghệ An thời Lý. Đền nằm dưới chân núi Quả, cảnh quan hữu tình bên dòng sông Lam.",
    "Qua Son Temple in Do Luong district is one of the 'four great' sacred temples of Nghe An, honouring Uy Minh Vuong Ly Nhat Quang, a governor who did great service for the land in the Ly dynasty. It sits at the foot of Qua Mountain in a charming setting by the Lam River.",
    "Храм Куашон в уезде Долыонг — один из «четырёх великих» священных храмов Нгеана, посвящённый Уи Минь Выонгу Ли Нят Куангу, наместнику, много сделавшему для этого края при династии Ли. Он стоит у подножия горы Куа в живописном месте у реки Лам.",
    "Đền Quả Sơn tọa lạc dưới chân núi Quả, thuộc xã Bồi Sơn, huyện Đô Lương, bên bờ sông Lam thơ mộng, cách thành phố Vinh khoảng 70 km. Đây được xem là một trong bốn ngôi đền linh thiêng và có quy mô bậc nhất xứ Nghệ ('nhất Cờn, nhì Quả, tam Bạch Mã, tứ Chiêu Trưng'). Đền thờ Uy Minh Vương Lý Nhật Quang – con trai vua Lý Thái Tổ, người được cử vào làm Tri châu Nghệ An dưới thời Lý. Ông có công lớn trong việc khai khẩn đất đai, phát triển nông nghiệp, mở mang giáo dục, ổn định đời sống nhân dân và giữ yên bờ cõi phía nam của quốc gia, nên được nhân dân tôn kính, lập đền thờ phụng. Ngôi đền cổ có kiến trúc bề thế, gồm nhiều tòa điện, được bao bọc bởi núi non và cây cối xanh mát, phía trước là dòng sông Lam uốn lượn tạo nên khung cảnh 'sơn thủy hữu tình'. Hằng năm, lễ hội đền Quả Sơn diễn ra vào khoảng ngày 19–21 tháng Giêng âm lịch với nhiều nghi lễ truyền thống, đặc sắc nhất là lễ rước thần bằng thuyền trên sông và rước bộ, thu hút đông đảo người dân và du khách. Đền Quả Sơn không chỉ là nơi sinh hoạt tín ngưỡng mà còn là di tích lịch sử – văn hóa giá trị của vùng đất Đô Lương.",
    "Qua Son Temple sits at the foot of Qua Mountain in Boi Son commune, Do Luong district, beside the poetic Lam River, about 70 km from Vinh City. It is regarded as one of the four most sacred and imposing temples of Nghe An (in the local ranking 'first Con, second Qua, third Bach Ma, fourth Chieu Trung'). The temple honours Uy Minh Vuong Ly Nhat Quang, a son of King Ly Thai To sent to govern Nghe An under the Ly dynasty. He did great service in reclaiming land, developing agriculture, spreading education, stabilising people's lives and securing the country's southern frontier, and so was revered and enshrined. The ancient temple has grand architecture with several halls, encircled by mountains and cool greenery, with the winding Lam River before it forming a scene of 'harmonious mountains and water'. Each year the Qua Son festival takes place around the 19th-21st days of the first lunar month with many traditional rites, the most striking being the deity procession by boat on the river and on foot, drawing large crowds. Qua Son Temple is not only a place of worship but also a valuable historical and cultural relic of the Do Luong area.",
    "Храм Куашон стоит у подножия горы Куа в общине Бойшон уезда Долыонг, у поэтичной реки Лам, примерно в 70 км от города Винь. Он считается одним из четырёх самых священных и внушительных храмов Нгеана (в местном порядке «первый Кон, второй Куа, третий Батьма, четвёртый Тьеучынг»). Храм посвящён Уи Минь Выонгу Ли Нят Куангу — сыну короля Ли Тхай То, направленному управлять Нгеаном при династии Ли. Он много сделал для освоения земель, развития сельского хозяйства, распространения образования, стабилизации жизни людей и охраны южных рубежей страны, за что был почитаем и увековечен в храме. Древний храм имеет величественную архитектуру с несколькими залами, окружён горами и прохладной зеленью, а перед ним извивается река Лам, образуя пейзаж «гармонии гор и воды». Ежегодно праздник Куашон проходит около 19-21-го числа первого лунного месяца со множеством традиционных обрядов; самый яркий — процессия божества на лодках по реке и пешком, собирающая большие толпы. Храм Куашон — не только место поклонения, но и ценный историко-культурный памятник края Долыонг.",
    ["Một trong 'tứ đại' đền linh thiêng xứ Nghệ, thờ Lý Nhật Quang",
     "Dưới chân núi Quả, cảnh sơn thủy hữu tình bên sông Lam",
     "Lễ hội tháng Giêng với lễ rước thần bằng thuyền độc đáo"],
    ["One of the 'four great' sacred temples of Nghe An, honouring Ly Nhat Quang",
     "At the foot of Qua Mountain, harmonious mountains and water by the Lam River",
     "First-lunar-month festival with a striking deity procession by boat"],
    ["Один из «четырёх великих» священных храмов Нгеана в честь Ли Нят Куанга",
     "У подножия горы Куа, гармония гор и воды у реки Лам",
     "Праздник первого лунного месяца с яркой процессией на лодках"],
    {"hours_vi": "Khoảng 6:00–18:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 1–1,5 giờ.",
     "best_time_vi": "Lễ hội 19–21 tháng Giêng âm lịch; đầu xuân cảnh đẹp.",
     "tips_vi": "Ăn mặc lịch sự; kết hợp thăm Truông Bồn và các di tích Đô Lương."},
    ["spiritual", "temple", "history", "culture", "festival", "outdoor"],
    [{"title": "Wikipedia (VI) — Đền Quả Sơn", "url": "https://vi.wikipedia.org/wiki/%C4%90%E1%BB%81n_Qu%E1%BA%A3_S%C6%A1n"}]),

rec("chua-dai-tue",
    "Chùa Đại Tuệ",
    "Dai Tue Pagoda",
    "Пагода Дайтюэ",
    ["church", "monument"],
    18.7550, 105.4680,
    "Núi Đại Huệ, xã Nam Anh, huyện Nam Đàn, tỉnh Nghệ An",
    {"value": 4.7, "count": 2600, "source": "Google", "as_of": "2026-07"},
    "Ngôi chùa trên đỉnh núi Đại Huệ, cảnh quan hùng vĩ, view nhìn toàn cảnh Nam Đàn. Kiến trúc bề thế, nhiều kỷ lục; không gian thanh tịnh, hợp vãn cảnh, chiêm bái.",
    "Chùa Đại Tuệ tọa lạc trên đỉnh núi Đại Huệ ở huyện Nam Đàn, độ cao gần 500 m, là ngôi chùa cổ gắn với nhiều truyền thuyết và giữ nhiều kỷ lục. Từ chùa có thể phóng tầm mắt ngắm toàn cảnh vùng quê Nam Đàn và dòng sông Lam.",
    "Dai Tue Pagoda stands on the summit of Dai Hue Mountain in Nam Dan district at nearly 500 metres, an ancient temple linked to many legends and holding several records. From it one can gaze over the whole Nam Dan countryside and the Lam River.",
    "Пагода Дайтюэ стоит на вершине горы Дайхюэ в уезде Намдан на высоте почти 500 метров — древний храм, связанный со множеством легенд и хранящий несколько рекордов. Отсюда открывается вид на всю сельскую местность Намдана и реку Лам.",
    "Chùa Đại Tuệ nằm trên đỉnh động Thăng Thiên của dãy núi Đại Huệ, thuộc xã Nam Anh, huyện Nam Đàn, ở độ cao gần 500 m so với mực nước biển, cách thành phố Vinh khoảng 25 km. Đây là ngôi chùa cổ có lịch sử lâu đời, tương truyền gắn với các triều đại và những nhân vật lịch sử như vua Mai Hắc Đế, Hồ Quý Ly và cả vua Quang Trung – Nguyễn Huệ trên đường hành quân ra Bắc đại phá quân Thanh. Chùa thờ Phật Bà Đại Tuệ – tượng trưng cho trí tuệ lớn của nhà Phật. Sau nhiều lần trùng tu, tôn tạo, ngày nay chùa Đại Tuệ trở thành một quần thể kiến trúc bề thế, uy nghi giữa mây núi, gồm nhiều hạng mục như cổng tam quan, các tòa bảo điện, tháp chuông, tượng Phật và hệ thống câu đối bằng chữ thư pháp thuần Việt. Chùa được ghi nhận nhiều kỷ lục quốc gia như ngôi chùa trên núi có hồ nhân tạo lớn, hệ thống câu đối bằng thư pháp thuần Việt nhiều nhất. Đứng từ sân chùa, du khách có thể ngắm toàn cảnh vùng quê Nam Đàn trù phú, dòng sông Lam và núi Thiên Nhẫn trải dài phía xa. Không gian thanh tịnh, khí hậu mát mẻ cùng cảnh quan hùng vĩ khiến chùa Đại Tuệ trở thành điểm hành hương và du lịch tâm linh hấp dẫn của xứ Nghệ.",
    "Dai Tue Pagoda stands atop the Thang Thien peak of the Dai Hue range in Nam Anh commune, Nam Dan district, at nearly 500 metres above sea level, about 25 km from Vinh City. This ancient temple has a long history and is said to be linked to several dynasties and historical figures such as King Mai Hac De, Ho Quy Ly and even King Quang Trung-Nguyen Hue on his march north to crush the Qing army. It venerates the Buddha of Great Wisdom (Dai Tue), a symbol of the Buddha's profound wisdom. After many restorations, Dai Tue is today a grand, dignified architectural complex amid mountain clouds, comprising a triple gate, main halls, a bell tower, Buddha statues and a set of parallel sentences in pure Vietnamese calligraphy. It holds several national records, such as the mountain pagoda with a large artificial lake and the most parallel sentences in pure Vietnamese calligraphy. From the courtyard, visitors can survey the fertile Nam Dan countryside, the Lam River and the distant Thien Nhan mountains. Its serene atmosphere, cool climate and majestic scenery make Dai Tue Pagoda an appealing pilgrimage and spiritual-tourism site in Nghe An.",
    "Пагода Дайтюэ стоит на вершине Тхангтхьен хребта Дайхюэ в общине Намань уезда Намдан, на высоте почти 500 метров над уровнем моря, примерно в 25 км от города Винь. У этого древнего храма долгая история; предание связывает его с несколькими династиями и историческими фигурами — королём Май Хак Дэ, Хо Куи Ли и даже королём Куанг Чунгом-Нгуен Хюэ во время его похода на север, чтобы разгромить цинскую армию. Храм чтит Будду Великой Мудрости (Дайтюэ) — символ глубокой мудрости Будды. После многих реставраций Дайтюэ сегодня — величественный, торжественный архитектурный комплекс среди горных облаков: тройные ворота, главные залы, колокольня, статуи Будды и набор парных изречений на чистой вьетнамской каллиграфии. Он хранит несколько национальных рекордов, например горная пагода с большим искусственным озером и наибольшим числом парных изречений вьетнамской каллиграфии. С храмового двора видны плодородная сельская местность Намдана, река Лам и далёкие горы Тхьеннян. Безмятежная атмосфера, прохладный климат и величественные пейзажи делают пагоду Дайтюэ привлекательным местом паломничества и духовного туризма в Нгеане.",
    ["Chùa cổ trên đỉnh núi Đại Huệ (~500 m), nhiều kỷ lục quốc gia",
     "Gắn truyền thuyết vua Mai Hắc Đế, Hồ Quý Ly, Quang Trung",
     "View toàn cảnh Nam Đàn, sông Lam; không gian thanh tịnh, mát mẻ"],
    ["Ancient pagoda atop Dai Hue Mountain (~500 m) with several national records",
     "Linked to legends of King Mai Hac De, Ho Quy Ly and Quang Trung",
     "Panoramic views of Nam Dan and the Lam River; serene, cool setting"],
    ["Древняя пагода на вершине горы Дайхюэ (~500 м) с рядом рекордов",
     "Связана с легендами о короле Май Хак Дэ, Хо Куи Ли и Куанг Чунге",
     "Панорама Намдана и реки Лам; безмятежная прохладная атмосфера"],
    {"hours_vi": "Khoảng 6:00–18:00.",
     "ticket_vi": "Miễn phí (công đức tùy tâm; có phí gửi xe).",
     "duration_vi": "Khoảng 1,5–2 giờ.",
     "best_time_vi": "Sáng sớm hoặc chiều mát; đầu xuân đông khách hành hương.",
     "tips_vi": "Đi giày thoải mái; đường lên núi dốc, lái xe cẩn thận; kết hợp thăm quê Bác Kim Liên."},
    ["spiritual", "temple", "viewpoint", "culture", "outdoor", "top"],
    [{"title": "Wikipedia (VI) — Chùa Đại Tuệ", "url": "https://vi.wikipedia.org/wiki/Ch%C3%B9a_%C4%90%E1%BA%A1i_Tu%E1%BB%87"}]),

rec("khu-di-tich-phan-boi-chau",
    "Khu lưu niệm Phan Bội Châu (Nam Đàn)",
    "Phan Boi Chau Memorial Site (Nam Dan)",
    "Мемориал Фан Бой Тяу (Намдан)",
    ["monument", "museum"],
    18.7000, 105.5000,
    "Thị trấn Nam Đàn, huyện Nam Đàn, tỉnh Nghệ An",
    {"value": 4.6, "count": 700, "source": "Google", "as_of": "2026-07"},
    "Nơi lưu niệm nhà chí sĩ yêu nước Phan Bội Châu với nhà tranh, kỷ vật giản dị. Không gian yên tĩnh, ý nghĩa lịch sử; hợp tìm hiểu phong trào yêu nước đầu thế kỷ 20.",
    "Khu lưu niệm Phan Bội Châu ở thị trấn Nam Đàn là nơi gắn với thời niên thiếu của nhà chí sĩ yêu nước Phan Bội Châu – lãnh tụ phong trào Đông Du. Khu di tích gồm ngôi nhà tranh xưa cùng các kỷ vật, tư liệu về cuộc đời và sự nghiệp cách mạng của cụ.",
    "The Phan Boi Chau Memorial Site in Nam Dan town preserves the youth home of the patriotic scholar Phan Boi Chau, leader of the Dong Du (Go East) movement. It includes his old thatched house along with keepsakes and documents on his life and revolutionary work.",
    "Мемориал Фан Бой Тяу в посёлке Намдан хранит дом юности патриота-учёного Фан Бой Тяу, лидера движения Донгзу («Идти на восток»). В него входят его старый тростниковый дом, а также реликвии и документы о его жизни и революционной деятельности.",
    "Khu lưu niệm Phan Bội Châu nằm ở thị trấn Nam Đàn, huyện Nam Đàn, quê hương của nhà chí sĩ yêu nước Phan Bội Châu (1867–1940) – một trong những lãnh tụ tiêu biểu của phong trào yêu nước và cách mạng Việt Nam đầu thế kỷ 20, người khởi xướng phong trào Đông Du đưa thanh niên sang Nhật Bản học tập để về cứu nước. Khu di tích bảo tồn ngôi nhà tranh đơn sơ ba gian nơi cụ đã sống thời niên thiếu, cùng nhà thờ, giếng nước, mảnh vườn và nhiều hiện vật, tư liệu quý phản ánh cuộc đời hoạt động sôi nổi, đầy gian truân của một nhà nho yêu nước. Tại đây, du khách được tìm hiểu về tấm gương học tập, ý chí và tinh thần yêu nước mãnh liệt của cụ Phan qua các trước tác, thư từ, hình ảnh và kỷ vật được trưng bày. Không gian khu lưu niệm mộc mạc, yên tĩnh, mang đậm nét làng quê xứ Nghệ, gợi nhớ về một thời kỳ lịch sử đầy biến động khi các sĩ phu yêu nước trăn trở tìm đường giải phóng dân tộc. Khu lưu niệm đã được xếp hạng di tích quốc gia và thường được kết hợp trong hành trình về Nam Đàn cùng quê Bác Kim Liên, tạo thành cụm di tích giàu ý nghĩa lịch sử – văn hóa.",
    "The Phan Boi Chau Memorial Site is in Nam Dan town, Nam Dan district, the homeland of the patriotic scholar Phan Boi Chau (1867-1940), one of the leading figures of Vietnam's early-20th-century patriotic and revolutionary movement and the initiator of the Dong Du movement, which sent young people to study in Japan to return and save the country. The site preserves the simple three-compartment thatched house where he spent his youth, along with an ancestral shrine, a well, a garden and many precious objects and documents reflecting the eventful, arduous life of a patriotic Confucian scholar. Here visitors learn about Phan's example of study, willpower and fierce patriotism through his writings, letters, photographs and displayed keepsakes. The memorial's rustic, quiet setting is rich in the character of the Nghe An countryside and recalls a turbulent era when patriotic scholars agonised over the path to national liberation. Ranked a national relic, it is often combined into a Nam Dan itinerary with Uncle Ho's homeland at Kim Lien, forming a cluster of great historical and cultural significance.",
    "Мемориал Фан Бой Тяу находится в посёлке Намдан уезда Намдан — на родине патриота-учёного Фан Бой Тяу (1867-1940), одного из ведущих деятелей вьетнамского патриотического и революционного движения начала XX века и зачинателя движения Донгзу, отправлявшего молодёжь учиться в Японию, чтобы вернуться и спасти страну. Мемориал хранит простой трёхсекционный тростниковый дом, где он провёл юность, а также родовое святилище, колодец, сад и множество ценных предметов и документов, отражающих насыщенную, трудную жизнь патриотичного конфуцианского учёного. Здесь посетители узнают о примере учёбы, воле и пламенном патриотизме Фана через его сочинения, письма, фотографии и выставленные реликвии. Скромная, тихая обстановка мемориала пропитана духом сельской местности Нгеана и напоминает о бурной эпохе, когда патриотичные учёные мучительно искали путь к национальному освобождению. Признанный национальным памятником, он часто включается в маршрут по Намдану вместе с родиной «дядюшки Хо» в Кимльене, образуя комплекс большого историко-культурного значения.",
    ["Quê hương nhà chí sĩ Phan Bội Châu, lãnh tụ phong trào Đông Du",
     "Nhà tranh thời niên thiếu cùng kỷ vật, tư liệu quý",
     "Di tích quốc gia; kết hợp cụm di tích Nam Đàn cùng quê Bác Kim Liên"],
    ["Homeland of the scholar Phan Boi Chau, leader of the Dong Du movement",
     "His youth thatched house with keepsakes and precious documents",
     "A national relic; combine with the Nam Dan cluster near Kim Lien"],
    ["Родина учёного Фан Бой Тяу, лидера движения Донгзу",
     "Тростниковый дом юности с реликвиями и ценными документами",
     "Национальный памятник; сочетается с комплексом Намдана у Кимльена"],
    {"hours_vi": "Khoảng 7:00–17:00.",
     "ticket_vi": "Miễn phí.",
     "duration_vi": "Khoảng 45–60 phút.",
     "best_time_vi": "Quanh năm; kết hợp hành trình về Nam Đàn.",
     "tips_vi": "Nên thuê thuyết minh; đi cùng quê Bác Kim Liên và đền vua Mai để trọn cụm di tích."},
    ["history", "monument", "culture", "memorial", "outdoor"],
    [{"title": "Wikipedia (VI) — Phan Bội Châu", "url": "https://vi.wikipedia.org/wiki/Phan_B%E1%BB%99i_Ch%C3%A2u"}]),

rec("den-vua-mai",
    "Đền thờ Vua Mai Hắc Đế",
    "King Mai Hac De Temple",
    "Храм короля Май Хак Дэ",
    ["church", "monument"],
    18.6920, 105.5150,
    "Thị trấn Nam Đàn, huyện Nam Đàn, tỉnh Nghệ An",
    {"value": 4.5, "count": 800, "source": "Google", "as_of": "2026-07"},
    "Khu đền và lăng mộ tưởng nhớ vua Mai Hắc Đế, người lãnh đạo khởi nghĩa chống Đường. Không gian cổ kính, lễ hội đầu năm đông vui; ý nghĩa lịch sử sâu sắc.",
    "Đền thờ Vua Mai Hắc Đế ở huyện Nam Đàn tưởng nhớ Mai Thúc Loan – thủ lĩnh cuộc khởi nghĩa chống ách đô hộ nhà Đường đầu thế kỷ 8, xưng đế và lập nên nhà nước độc lập. Quần thể gồm đền thờ, lăng mộ và khu tưởng niệm giữa vùng quê Nam Đàn.",
    "The King Mai Hac De Temple in Nam Dan district commemorates Mai Thuc Loan, leader of the early-8th-century uprising against Tang rule who proclaimed himself emperor and founded an independent state. The complex includes a temple, tomb and memorial area in the Nam Dan countryside.",
    "Храм короля Май Хак Дэ в уезде Намдан посвящён Май Тхук Лоану — предводителю восстания начала VIII века против танского владычества, который провозгласил себя императором и основал независимое государство. В комплекс входят храм, гробница и мемориальная зона среди сельской местности Намдана.",
    "Đền thờ Vua Mai Hắc Đế nằm ở thị trấn Nam Đàn, huyện Nam Đàn, gắn với tên tuổi Mai Thúc Loan – vị anh hùng dân tộc quê ở vùng đất này. Đầu thế kỷ 8, trước ách đô hộ hà khắc của nhà Đường, Mai Thúc Loan đã tập hợp nhân dân dựng cờ khởi nghĩa, đánh đuổi quân xâm lược, xưng đế lấy hiệu là Mai Hắc Đế (Vua Đen họ Mai) và lập nên chính quyền độc lập với kinh đô Vạn An bên bờ sông Lam. Cuộc khởi nghĩa Hoan Châu do ông lãnh đạo là một trong những mốc son chói lọi trong lịch sử chống ngoại xâm của dân tộc. Để tưởng nhớ công lao của ông, nhân dân đã lập đền thờ và lăng mộ tại quê hương. Quần thể di tích gồm đền thờ chính, khu lăng mộ vua Mai và mộ thân mẫu, nằm giữa vùng núi Vệ, rú Đụn với cây cối xanh mát, mang không khí trang nghiêm, cổ kính. Hằng năm, lễ hội đền vua Mai được tổ chức vào dịp Rằm tháng Giêng, kéo dài nhiều ngày với các nghi lễ rước, tế truyền thống cùng nhiều trò chơi dân gian như đua thuyền, đấu vật, thu hút đông đảo nhân dân và du khách. Đây là di tích lịch sử quốc gia có giá trị, góp phần giáo dục truyền thống yêu nước cho các thế hệ.",
    "The King Mai Hac De Temple stands in Nam Dan town, Nam Dan district, tied to the name of Mai Thuc Loan, a national hero from this land. In the early 8th century, faced with the harsh rule of the Tang, Mai Thuc Loan rallied the people to raise the banner of revolt, drove out the invaders, proclaimed himself emperor under the title Mai Hac De (the Black Emperor of the Mai clan) and founded an independent government with its capital, Van An, by the Lam River. The Hoan Chau uprising he led is one of the brilliant milestones in the nation's history of resisting foreign aggression. To honour his merit, the people built a temple and tomb in his homeland. The relic complex comprises the main temple, the tomb of King Mai and his mother's tomb, set among the Ve and Dun hills with cool greenery and a solemn, ancient air. Each year the King Mai festival is held around the full moon of the first lunar month, lasting several days with traditional processions and rites and folk games such as boat racing and wrestling, drawing large crowds. It is a valuable national historical relic that helps pass patriotic tradition to new generations.",
    "Храм короля Май Хак Дэ стоит в посёлке Намдан уезда Намдан и связан с именем Май Тхук Лоана — национального героя из этих мест. В начале VIII века, столкнувшись с жестоким владычеством Тан, Май Тхук Лоан поднял народ на восстание, изгнал захватчиков, провозгласил себя императором под именем Май Хак Дэ («Чёрный император из рода Май») и основал независимое правление со столицей Ванан у реки Лам. Возглавленное им восстание Хоантяу — одна из блистательных вех в истории борьбы народа с иноземной агрессией. В честь его заслуг народ построил храм и гробницу на его родине. Комплекс включает главный храм, гробницу короля Мая и гробницу его матери среди холмов Ве и Зун с прохладной зеленью и торжественной, древней атмосферой. Ежегодно праздник короля Мая проводится около полнолуния первого лунного месяца и длится несколько дней с традиционными процессиями, обрядами и народными играми — лодочными гонками и борьбой, — собирая большие толпы. Это ценный национальный памятник, помогающий передавать патриотическую традицию новым поколениям.",
    ["Tưởng nhớ Mai Thúc Loan – Mai Hắc Đế, thủ lĩnh khởi nghĩa chống Đường (thế kỷ 8)",
     "Quần thể đền thờ và lăng mộ giữa vùng núi Vệ, rú Đụn",
     "Lễ hội Rằm tháng Giêng với đua thuyền, đấu vật; di tích quốc gia"],
    ["Commemorates Mai Thuc Loan-Mai Hac De, leader of the 8th-century anti-Tang revolt",
     "A temple-and-tomb complex among the Ve and Dun hills",
     "First-lunar-month festival with boat racing and wrestling; a national relic"],
    ["Память о Май Тхук Лоане-Май Хак Дэ, вожде восстания против Тан (VIII век)",
     "Комплекс храма и гробницы среди холмов Ве и Зун",
     "Праздник первого лунного месяца с гонками лодок и борьбой; национальный памятник"],
    {"hours_vi": "Khoảng 6:30–17:30.",
     "ticket_vi": "Miễn phí (công đức tùy tâm).",
     "duration_vi": "Khoảng 1 giờ.",
     "best_time_vi": "Lễ hội Rằm tháng Giêng âm lịch; đầu xuân.",
     "tips_vi": "Kết hợp cụm di tích Nam Đàn: quê Bác, khu lưu niệm Phan Bội Châu."},
    ["history", "temple", "monument", "culture", "festival", "outdoor"],
    [{"title": "Wikipedia (VI) — Mai Hắc Đế", "url": "https://vi.wikipedia.org/wiki/Mai_H%E1%BA%AFc_%C4%90%E1%BA%BF"}]),

rec("dao-lan-chau",
    "Đảo Lan Châu (Cửa Lò)",
    "Lan Chau Island (Cua Lo)",
    "Остров Лантяу (Кыало)",
    ["park_garden", "other"],
    18.8230, 105.7180,
    "Phường Thu Thủy, thị xã Cửa Lò (nay thuộc TP. Vinh), tỉnh Nghệ An",
    {"value": 4.3, "count": 1200, "source": "Google", "as_of": "2026-07"},
    "Hòn đảo nhỏ nhô ra biển ngay cạnh bãi tắm Cửa Lò; leo lên ngắm toàn cảnh biển rất đẹp. Có bãi đá, biệt thự cổ; hoàng hôn và bình minh lãng mạn.",
    "Đảo Lan Châu là hòn đảo nhỏ nằm ngay sát bãi biển Cửa Lò, nhô ra biển như một 'hòn ngọc' chia bãi tắm thành hai phần. Leo lên đảo, du khách được ngắm toàn cảnh biển Cửa Lò, bãi đá và tận hưởng khung cảnh lãng mạn lúc bình minh, hoàng hôn.",
    "Lan Chau Island is a small island right beside Cua Lo Beach, jutting into the sea like a 'gem' that splits the bathing beach in two. Climbing it, visitors enjoy a panorama of Cua Lo, its rocky shore and a romantic scene at sunrise and sunset.",
    "Остров Лантяу — небольшой остров прямо у пляжа Кыало, выступающий в море словно «жемчужина», которая делит пляж надвое. Поднявшись на него, гости любуются панорамой Кыало, скалистым берегом и романтичным пейзажем на восходе и закате.",
    "Đảo Lan Châu, còn gọi là Rú Cóc, là một hòn đảo nhỏ nằm ngay trong khu vực bãi biển Cửa Lò, cách bờ chỉ vài trăm mét và khi thủy triều xuống có thể đi bộ ra đảo. Đảo có diện tích khiêm tốn nhưng địa hình độc đáo: một bên là bãi cát, một bên là ghềnh đá lô nhô bị sóng biển bào mòn tạo thành nhiều hình thù kỳ thú. Trên đảo có ngọn đồi nhỏ, đường mòn dẫn lên đỉnh, nơi từng có tòa lâu đài nghỉ mát của vua Bảo Đại xây dựng từ đầu thế kỷ 20. Từ trên cao, du khách có thể phóng tầm mắt bao quát toàn cảnh bãi biển Cửa Lò cong cong ôm lấy bờ, những rặng phi lao xanh, thị xã biển sầm uất và mặt biển mênh mông với thuyền bè qua lại. Đây là địa điểm lý tưởng để ngắm bình minh khi mặt trời nhô lên từ biển và hoàng hôn buông xuống nhuộm vàng cả một vùng trời nước. Đảo Lan Châu gắn với đền thờ Nguyễn Sư Hồi và nhiều truyền thuyết dân gian, tạo thêm sức hấp dẫn về văn hóa, tâm linh. Kết hợp tắm biển Cửa Lò với leo đảo Lan Châu, thưởng thức hải sản tươi ngon, du khách sẽ có một hành trình nghỉ dưỡng biển trọn vẹn nơi xứ Nghệ.",
    "Lan Chau Island, also called Ru Coc, is a small island right within the Cua Lo beach area, only a few hundred metres offshore, reachable on foot at low tide. It is modest in size but has unusual terrain: sand on one side and jagged, wave-worn rocks on the other, sculpted into fascinating shapes. On the island a small hill and a path lead to the summit, where King Bao Dai built a holiday chateau in the early 20th century. From the top, visitors can take in the whole curving sweep of Cua Lo beach embracing the shore, the green casuarina rows, the busy seaside town and the vast sea dotted with boats. It is an ideal spot to watch the sunrise as the sun lifts from the sea and the sunset gilding the sky and water. Lan Chau Island is linked to the Nguyen Su Hoi shrine and many folk legends, adding cultural and spiritual appeal. Combining a swim at Cua Lo with a climb of Lan Chau and fresh seafood gives visitors a complete seaside retreat in Nghe An.",
    "Остров Лантяу, называемый также Рукок, — небольшой остров прямо в зоне пляжа Кыало, всего в нескольких сотнях метров от берега, до которого при отливе можно дойти пешком. Он невелик, но обладает необычным рельефом: с одной стороны песок, с другой — зубчатые, обточенные волнами скалы причудливых форм. На острове небольшой холм и тропа ведут к вершине, где в начале XX века король Бао Дай построил летний замок. С вершины гости охватывают взглядом всю изгибающуюся дугу пляжа Кыало, обнимающую берег, зелёные ряды казуарин, оживлённый приморский городок и бескрайнее море с лодками. Это идеальное место, чтобы встречать восход, когда солнце поднимается из моря, и закат, золотящий небо и воду. Остров Лантяу связан со святилищем Нгуен Ши Хоя и множеством народных легенд, что добавляет культурной и духовной привлекательности. Сочетая купание в Кыало с подъёмом на Лантяу и свежими морепродуктами, гости получают полноценный морской отдых в Нгеане.",
    ["Đảo nhỏ ngay cạnh bãi tắm Cửa Lò, khi triều xuống đi bộ ra được",
     "Có ghềnh đá kỳ thú và dấu tích lâu đài nghỉ mát của vua Bảo Đại",
     "Điểm ngắm bình minh, hoàng hôn và toàn cảnh biển Cửa Lò"],
    ["A small island beside Cua Lo beach, reachable on foot at low tide",
     "Fascinating rocks and traces of King Bao Dai's holiday chateau",
     "A spot to watch sunrise, sunset and the panorama of Cua Lo"],
    ["Небольшой остров у пляжа Кыало, при отливе доступен пешком",
     "Причудливые скалы и следы летнего замка короля Бао Дая",
     "Место для восходов, закатов и панорамы Кыало"],
    {"hours_vi": "Ban ngày; chú ý lịch thủy triều khi ra đảo.",
     "ticket_vi": "Miễn phí (có thể có phí dịch vụ).",
     "duration_vi": "Khoảng 1–1,5 giờ.",
     "best_time_vi": "Bình minh hoặc hoàng hôn; mùa hè kết hợp tắm biển Cửa Lò.",
     "tips_vi": "Đi dép bám đá, cẩn thận ghềnh trơn; xem giờ thủy triều; kết hợp tắm biển và ăn hải sản."},
    ["beach", "island", "viewpoint", "nature", "outdoor", "family"],
    [{"title": "Wikipedia (VI) — Cửa Lò", "url": "https://vi.wikipedia.org/wiki/C%E1%BB%ADa_L%C3%B2"}]),

rec("bai-lu",
    "Khu du lịch Bãi Lữ",
    "Bai Lu Resort",
    "Курорт Байлы",
    ["park_garden", "other"],
    18.8480, 105.7650,
    "Xã Nghi Yên, huyện Nghi Lộc, tỉnh Nghệ An",
    {"value": 4.2, "count": 1500, "source": "Google", "as_of": "2026-07"},
    "Bãi biển đẹp lưng tựa núi, mặt hướng biển, không gian riêng tư yên tĩnh; hợp nghỉ dưỡng. Có khu resort, cảnh quan xanh mát; dịch vụ đang hoàn thiện thêm.",
    "Bãi Lữ là khu du lịch nghỉ dưỡng ven biển ở huyện Nghi Lộc, nổi bật với bãi biển cong hình vòng cung, lưng tựa vào những dãy đồi thông xanh mát. Không gian yên tĩnh, riêng tư cùng bãi cát sạch và làn nước trong khiến nơi đây thích hợp cho kỳ nghỉ thư giãn.",
    "Bai Lu is a coastal resort area in Nghi Loc district, notable for its arc-shaped beach backed by cool green pine-clad hills. Its quiet, private setting with clean sand and clear water makes it ideal for a relaxing holiday.",
    "Байлы — приморская курортная зона в уезде Нгилок, примечательная пляжем в форме дуги, за которым поднимаются прохладные зелёные сосновые холмы. Тихая, уединённая обстановка с чистым песком и прозрачной водой делает её идеальной для спокойного отдыха.",
    "Khu du lịch Bãi Lữ nằm ở xã Nghi Yên, huyện Nghi Lộc, bên Quốc lộ ven biển, cách thành phố Vinh khoảng 25 km và không xa biển Cửa Lò. Đây là một trong những bãi biển đẹp và đặc biệt của Nghệ An bởi địa thế 'sơn thủy hữu tình': một bên là bãi cát vàng cong hình vòng cung ôm lấy vịnh biển, một bên là những dãy đồi thấp phủ rừng thông và cây xanh mát rượi chạy sát mép nước. Chính nhờ địa hình núi bao bọc, sóng ở đây khá êm, nước trong, không gian kín đáo, yên tĩnh và trong lành, mang lại cảm giác riêng tư, tách biệt khỏi sự ồn ào. Bãi Lữ đã được đầu tư thành khu nghỉ dưỡng với hệ thống khách sạn, biệt thự, khu vui chơi, nhà hàng hải sản và các dịch vụ tắm biển, thể thao. Du khách đến đây có thể tắm biển, dạo bộ trên bãi cát, leo đồi thông ngắm toàn cảnh vịnh, chèo thuyền, câu cá hoặc đơn giản là nghỉ ngơi, thư giãn giữa thiên nhiên. Buổi sớm, bình minh trên vịnh Bãi Lữ rất đẹp với ánh nắng phản chiếu trên mặt nước phẳng lặng. Với khung cảnh hài hòa giữa biển và rừng, Bãi Lữ là lựa chọn hấp dẫn cho những kỳ nghỉ dưỡng yên bình bên bờ biển xứ Nghệ.",
    "Bai Lu Resort lies in Nghi Yen commune, Nghi Loc district, along the coastal highway, about 25 km from Vinh City and not far from Cua Lo beach. It is one of Nghe An's loveliest and most distinctive beaches thanks to its 'harmonious mountains and water' setting: on one side an arc of golden sand embraces the bay, while on the other low hills clad in pine and cool greenery run right down to the water's edge. Sheltered by the surrounding hills, the waves here are fairly gentle, the water clear and the atmosphere secluded, quiet and fresh, giving a sense of privacy away from the noise. Bai Lu has been developed into a resort with hotels, villas, play areas, seafood restaurants and bathing and sports services. Visitors can swim, stroll the sand, climb the pine hills for bay panoramas, row boats, fish or simply rest and relax amid nature. At dawn, sunrise over Bai Lu bay is beautiful, the light reflecting on the still water. With its harmony of sea and forest, Bai Lu is an appealing choice for a peaceful seaside holiday in Nghe An.",
    "Курорт Байлы находится в общине Нгиен уезда Нгилок, вдоль прибрежного шоссе, примерно в 25 км от города Винь и недалеко от пляжа Кыало. Это один из красивейших и самобытнейших пляжей Нгеана благодаря обстановке «гармонии гор и воды»: с одной стороны дуга золотого песка обнимает залив, с другой — низкие холмы, покрытые сосной и прохладной зеленью, спускаются прямо к воде. Защищённые окружающими холмами, волны здесь довольно спокойны, вода прозрачна, а атмосфера уединённа, тиха и свежа, что создаёт ощущение приватности вдали от шума. Байлы превращён в курорт с отелями, виллами, игровыми зонами, ресторанами морепродуктов и услугами купания и спорта. Гости могут купаться, гулять по песку, подниматься на сосновые холмы ради панорам залива, кататься на лодках, рыбачить или просто отдыхать среди природы. На рассвете восход над заливом Байлы прекрасен, свет отражается в неподвижной воде. С гармонией моря и леса Байлы — привлекательный выбор для спокойного морского отдыха в Нгеане.",
    ["Bãi biển hình vòng cung lưng tựa đồi thông, sóng êm, nước trong",
     "Không gian riêng tư, yên tĩnh; khu nghỉ dưỡng ven biển",
     "Leo đồi thông ngắm vịnh; bình minh trên biển rất đẹp"],
    ["An arc-shaped beach backed by pine hills, gentle waves and clear water",
     "A private, quiet setting; a coastal resort",
     "Climb the pine hills for bay views; beautiful sunrises"],
    ["Пляж в форме дуги за сосновыми холмами, спокойные волны и чистая вода",
     "Уединённая тихая обстановка; приморский курорт",
     "Подъём на сосновые холмы ради видов залива; красивые восходы"],
    {"hours_vi": "Cả ngày (khu nghỉ dưỡng).",
     "ticket_vi": "Có phí vào cổng/dịch vụ tùy khu.",
     "duration_vi": "Nửa ngày đến vài ngày (nghỉ dưỡng).",
     "best_time_vi": "Mùa hè (tháng 4–8); đi sớm ngắm bình minh trên vịnh.",
     "tips_vi": "Đặt phòng trước dịp cao điểm; mang đồ bơi, kem chống nắng; hỏi rõ dịch vụ và giá."},
    ["beach", "resort", "nature", "outdoor", "family", "daytrip"],
    [{"title": "Wikipedia (VI) — Nghi Lộc", "url": "https://vi.wikipedia.org/wiki/Nghi_L%E1%BB%99c"}]),

rec("thanh-co-vinh",
    "Thành cổ Vinh (Thành Nghệ An)",
    "Vinh Citadel (Nghe An Citadel)",
    "Крепость Винь (цитадель Нгеан)",
    ["fortress", "monument"],
    18.6785, 105.6810,
    "Phường Cửa Nam, thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.3, "count": 1100, "source": "Google", "as_of": "2026-07"},
    "Di tích thành cổ thời Nguyễn với ba cổng thành rêu phong còn lại; không gian hoài cổ giữa lòng thành phố. Hợp dạo bộ, chụp ảnh, tìm hiểu lịch sử Vinh.",
    "Thành cổ Vinh là tòa thành quân sự – hành chính thời Nguyễn, xây dựng đầu thế kỷ 19 để trấn giữ vùng Nghệ An. Ngày nay còn lại ba cổng thành cổ kính (Tiền, Tả, Hữu) rêu phong, là chứng tích lịch sử và điểm hoài niệm giữa trung tâm thành phố Vinh.",
    "Vinh Citadel was a military-administrative fortress of the Nguyen dynasty, built in the early 19th century to guard the Nghe An region. Today its three mossy old gates (Front, Left, Right) survive as historical evidence and a nostalgic spot in the centre of Vinh City.",
    "Крепость Винь была военно-административной цитаделью династии Нгуен, построенной в начале XIX века для охраны края Нгеан. Сегодня сохранились её трое старых замшелых ворот (Передние, Левые, Правые) — историческое свидетельство и ностальгическое место в центре города Винь.",
    "Thành cổ Vinh, còn gọi là thành Nghệ An, được xây dựng dưới triều Nguyễn vào đầu thế kỷ 19 (khởi dựng thời vua Gia Long, hoàn thiện dưới thời Minh Mạng) nhằm làm trung tâm hành chính và quân sự trấn giữ cả vùng Nghệ An – Hà Tĩnh. Ban đầu thành đắp bằng đất, sau được xây lại bằng đá ong kiên cố theo kiểu thành Vauban với sáu cạnh, hào nước bao quanh và ba cửa: cửa Tiền (phía nam), cửa Tả (phía đông) và cửa Hữu (phía tây). Trong thành xưa có hành cung, dinh thự, kho tàng, trại lính và nhiều công trình quan trọng. Trải qua chiến tranh và thời gian, phần lớn tường thành và công trình bên trong đã không còn, nhưng ba cổng thành cổ kính với lối kiến trúc vòm đá, rêu phong vẫn được bảo tồn, trở thành biểu tượng lịch sử của thành phố Vinh. Ngày nay, khu vực thành cổ là không gian xanh giữa lòng đô thị, nơi người dân đi dạo, tập thể dục, còn du khách thì tìm đến để chiêm ngưỡng dấu tích xưa, chụp ảnh và tìm hiểu về lịch sử vùng đất. Gần đó là Bảo tàng Xô Viết Nghệ Tĩnh nằm ngay trong khuôn viên thành, giúp du khách có cái nhìn đầy đủ hơn về truyền thống đấu tranh cách mạng của người dân xứ Nghệ.",
    "Vinh Citadel, also called Nghe An Citadel, was built under the Nguyen dynasty in the early 19th century (begun under King Gia Long and completed under Minh Mang) as an administrative and military centre guarding the whole Nghe An-Ha Tinh region. Originally an earthen rampart, it was later rebuilt solidly in laterite in the Vauban style, with six sides, a surrounding moat and three gates: the Front Gate (south), Left Gate (east) and Right Gate (west). Within it once stood a royal residence, mansions, storehouses, barracks and other important structures. Through war and time, most of the walls and interior buildings are gone, but the three ancient gates with their mossy stone arches survive as a historical symbol of Vinh City. Today the citadel area is a green space in the heart of the city where residents stroll and exercise, and visitors come to admire the old traces, take photos and learn about the region's history. Nearby, the Soviet Nghe Tinh Museum sits within the citadel grounds, giving visitors a fuller picture of the revolutionary struggle tradition of the people of Nghe An.",
    "Крепость Винь, называемая также цитаделью Нгеан, была построена при династии Нгуен в начале XIX века (начата при короле Зя Лонге и завершена при Минь Манге) как административный и военный центр, охраняющий весь край Нгеан-Хатинь. Изначально земляной вал, она позже была прочно перестроена из латерита в стиле Вобана — с шестью сторонами, окружающим рвом и тремя воротами: Передними (юг), Левыми (восток) и Правыми (запад). Внутри некогда стояли королевская резиденция, дворцы, склады, казармы и другие важные сооружения. Сквозь войны и время большая часть стен и внутренних построек исчезла, но трое древних ворот с замшелыми каменными арками сохранились как исторический символ города Винь. Сегодня территория крепости — зелёное пространство в сердце города, где жители гуляют и занимаются спортом, а гости приходят полюбоваться старинными следами, фотографировать и узнавать историю края. Рядом, на территории крепости, расположен музей Советов Нгетинь, дающий гостям более полное представление о традиции революционной борьбы жителей Нгеана.",
    ["Thành quân sự – hành chính thời Nguyễn (đầu thế kỷ 19) kiểu Vauban",
     "Còn lại ba cổng thành rêu phong: Tiền, Tả, Hữu",
     "Không gian hoài cổ giữa TP. Vinh; gần Bảo tàng Xô Viết Nghệ Tĩnh"],
    ["A Nguyen-dynasty military-administrative fortress (early 19th c.) in Vauban style",
     "Three surviving mossy gates: Front, Left and Right",
     "A nostalgic space in central Vinh; near the Soviet Nghe Tinh Museum"],
    ["Военно-административная крепость династии Нгуен (нач. XIX в.) в стиле Вобана",
     "Сохранились трое замшелых ворот: Передние, Левые, Правые",
     "Ностальгическое место в центре Виня; рядом музей Советов Нгетинь"],
    {"hours_vi": "Khu vực cổng thành: cả ngày.",
     "ticket_vi": "Miễn phí (tham quan cổng thành).",
     "duration_vi": "Khoảng 30–45 phút.",
     "best_time_vi": "Sáng sớm hoặc chiều mát; quanh năm.",
     "tips_vi": "Kết hợp thăm Bảo tàng Xô Viết Nghệ Tĩnh và trung tâm Vinh; chụp ảnh ở cổng cổ."},
    ["history", "fortress", "monument", "culture", "outdoor"],
    [{"title": "Wikipedia (VI) — Thành cổ Vinh", "url": "https://vi.wikipedia.org/wiki/Th%C3%A0nh_c%E1%BB%95_Vinh"}]),

]

d = json.load(open(F, encoding="utf-8")) if os.path.exists(F) else []
have = {p["slug"] for p in d}
added = [p for p in new if p["slug"] not in have]
d += added
json.dump(d, open(F, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("batch2 them:", len(added), "| gio co:", len(d))
