# -*- coding: utf-8 -*-
"""Bổ sung các NHÀ GA nổi tiếng, biểu tượng của các tỉnh/thành (đơn vị MỚI sau sáp nhập 1/7/2025).
Toạ độ THẬT (OSM/Wikidata). Chèn an toàn theo từng file: bỏ qua slug đã có. maps để trống (retrofit sinh).
"""
import json, os

def rec(file, rn, fd, slug, name_vi, name_en, name_ru, cats, lat, lon, addr, rating, review,
        ps_vi, ps_en, ps_ru, pl_vi, pl_en, pl_ru, hi_vi, hi_en, hi_ru, practical, tags, sources,
        photo=None, photo_credit=None):
    region = file
    return (file, {
        "id": f"{region}-{slug}", "slug": slug, "region": region, "country": "vietnam",
        "region_name_vi": rn, "federal_district": fd,
        "name_vi": name_vi, "name_ru": name_ru, "name_en": name_en,
        "categories": cats, "coordinates": {"lat": lat, "lon": lon},
        "address_vi": addr, "rating": rating, "review_summary_vi": review,
        "presentation_short_vi": ps_vi, "presentation_short_en": ps_en, "presentation_short_ru": ps_ru,
        "presentation_long_vi": pl_vi, "presentation_long_en": pl_en, "presentation_long_ru": pl_ru,
        "highlights_vi": hi_vi, "highlights_en": hi_en, "highlights_ru": hi_ru,
        "practical": practical, "photo": photo, "photo_credit": photo_credit,
        "maps": {}, "official_site": None, "sources": sources, "tags": tags,
        "status": "enriched", "last_updated": "2026-07-28",
    })

CATS = ["other", "monument"]
ITEMS = []
ITEMS.append(rec(
    "vn-ha-noi", "Hà Nội", "Miền Bắc", "ga-ha-noi",
    "Ga Hà Nội", "Hanoi Railway Station", "Железнодорожный вокзал Ханоя",
    CATS, 21.0235, 105.8405,
    "120 Lê Duẩn, quận Hoàn Kiếm (khu vực trung tâm), thành phố Hà Nội",
    {"value": 4.3, "count": 6000, "source": "Google", "as_of": "2026-07"},
    "Du khách thích vẻ cổ kính pha hiện đại của ga, vị trí trung tâm và không khí nhộn nhịp; nhiều người coi việc bắt chuyến tàu đêm Thống Nhất từ đây là kỷ niệm khó quên.",
    "Ga Hà Nội là nhà ga trung tâm của thủ đô, khánh thành năm 1902 với tên Ga Hàng Cỏ. Đây là đầu mối lớn nhất miền Bắc và điểm khởi đầu tuyến đường sắt Thống Nhất Bắc – Nam.",
    "Hanoi Railway Station is the capital's central station, opened in 1902 as Hang Co Station. It is the largest hub in the north and the starting point of the North–South Reunification railway.",
    "Железнодорожный вокзал Ханоя — центральный вокзал столицы, открытый в 1902 году как вокзал Хангко. Это крупнейший узел севера и начальная точка объединяющей железной дороги Север–Юг.",
    "Nằm ngay trung tâm thủ đô trên phố Lê Duẩn, Ga Hà Nội là nhà ga xe lửa lớn và quan trọng nhất miền Bắc Việt Nam. Được người Pháp xây dựng và khánh thành năm 1902 với tên gọi Ga Hàng Cỏ, nhà ga từng là công trình bề thế bậc nhất Đông Dương. Trong kháng chiến, khối nhà chính bị bom phá hỏng và về sau được xây lại ở giữa theo phong cách hiện đại, trong khi hai cánh hai bên vẫn giữ nét kiến trúc Pháp cổ, tạo nên diện mạo độc đáo 'cũ – mới' đan xen. Đây là ga khởi đầu của tuyến đường sắt Thống Nhất dài hơn 1.700 km nối Hà Nội với Thành phố Hồ Chí Minh, cùng các tuyến đi Lào Cai, Hải Phòng, Đồng Đăng. Mỗi ngày, hàng nghìn lượt khách qua lại nơi đây, và với nhiều du khách, được ngồi trên chuyến tàu Thống Nhất rời Ga Hà Nội là một trải nghiệm hoài niệm rất riêng. Không chỉ là đầu mối giao thông, Ga Hà Nội còn gắn với ký ức của bao thế hệ người dân thủ đô.",
    "In the very centre of the capital on Le Duan Street, Hanoi Railway Station is the largest and most important train station in northern Vietnam. Built by the French and opened in 1902 as Hang Co Station, it was once among the grandest buildings in Indochina. During the war its main block was destroyed by bombing and later rebuilt in the centre in a modern style, while the two wings kept their old French architecture, giving it a distinctive blend of old and new. It is the starting point of the 1,700-kilometre Reunification railway linking Hanoi with Ho Chi Minh City, along with lines to Lao Cai, Hai Phong and Dong Dang. Thousands of passengers pass through each day, and for many travellers, boarding the Reunification Express as it leaves Hanoi Station is a uniquely nostalgic experience. More than a transport hub, the station is woven into the memories of generations of the capital's people.",
    "В самом центре столицы на улице Ледуан железнодорожный вокзал Ханоя — крупнейший и важнейший вокзал севера Вьетнама. Построенный французами и открытый в 1902 году как вокзал Хангко, он был одним из самых величественных зданий Индокитая. Во время войны его главный корпус разрушила бомбёжка, и позже центр отстроили в современном стиле, тогда как два крыла сохранили старую французскую архитектуру, что придало ему характерное сочетание старого и нового. Это начальная точка объединяющей железной дороги длиной 1700 км, связывающей Ханой с Хошимином, а также линий на Лаокай, Хайфон и Донгданг. Каждый день здесь проходят тысячи пассажиров, и для многих путешественников поездка на «Экспрессе воссоединения», отходящем от вокзала Ханоя, — по-особому ностальгическое переживание. Больше чем транспортный узел, вокзал вплетён в память поколений жителей столицы.",
    ["Khánh thành 1902 (Ga Hàng Cỏ), ga trung tâm lớn nhất miền Bắc",
     "Điểm khởi đầu tuyến đường sắt Thống Nhất Bắc – Nam hơn 1.700 km",
     "Kiến trúc 'cũ – mới' đan xen ngay trung tâm thủ đô"],
    ["Opened in 1902 (Hang Co), the largest central station in the north",
     "Starting point of the 1,700 km North–South Reunification railway",
     "A blend of old and new architecture in the city centre"],
    ["Открыт в 1902 (Хангко), крупнейший центральный вокзал севера",
     "Начало объединяющей ж/д Север–Юг длиной более 1700 км",
     "Сочетание старой и новой архитектуры в центре столицы"],
    {"hours_vi": "Phục vụ theo lịch tàu hằng ngày; sảnh ga mở gần như cả ngày.",
     "ticket_vi": "Vào ga không mất phí; giá vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 20–40 phút tham quan, chụp ảnh.",
     "best_time_vi": "Ban ngày; ga đẹp và tiện chụp ảnh vào sáng sớm.",
     "tips_vi": "Đi tàu nên đặt vé trước dịp lễ, Tết; giữ an toàn tư trang nơi đông người."},
    ["railway", "historic", "photo", "architecture", "city", "family"],
    [{"title": "Hanoi railway station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Hanoi_railway_station"}],
))
ITEMS.append(rec(
    "vn-ha-noi", "Hà Nội", "Miền Bắc", "ga-long-bien",
    "Ga Long Biên", "Long Bien Railway Station", "Железнодорожная станция Лонгбьен",
    CATS, 21.0372, 105.8502,
    "Phố Gầm Cầu, đầu cầu Long Biên, quận Hoàn Kiếm, thành phố Hà Nội",
    {"value": 4.3, "count": 1500, "source": "Google", "as_of": "2026-07"},
    "Du khách thích ga nhỏ cổ kính ngay đầu cầu Long Biên lịch sử, là điểm chụp ảnh và ngắm tàu qua cầu rất được ưa chuộng; không gian hoài cổ, gần phố cổ.",
    "Ga Long Biên là nhà ga nhỏ nằm ngay đầu cầu Long Biên lịch sử bắc qua sông Hồng. Gắn với cây cầu hơn trăm tuổi, đây là điểm ngắm tàu, chụp ảnh hoài cổ nổi tiếng của Hà Nội.",
    "Long Bien Station is a small station right at the head of the historic Long Bien Bridge over the Red River. Tied to the century-old bridge, it is a famous Hanoi spot for train-watching and nostalgic photos.",
    "Станция Лонгбьен — маленькая станция прямо у начала исторического моста Лонгбьен через Красную реку. Связанная со столетним мостом, она известна в Ханое как место наблюдения за поездами и ностальгических фото.",
    "Nằm ngay đầu cầu Long Biên phía nội thành, Ga Long Biên là một nhà ga nhỏ nhưng đậm chất hoài niệm của Hà Nội. Ga gắn liền với cầu Long Biên — cây cầu thép do Pháp xây dựng đầu thế kỷ XX, từng là biểu tượng của thủ đô và chứng nhân của nhiều biến cố lịch sử. Tàu từ Ga Long Biên chạy qua cầu, băng ngang sông Hồng đỏ nặng phù sa, tạo nên khung cảnh vừa cổ kính vừa nên thơ. Chính vì thế, khu vực ga và đầu cầu từ lâu đã trở thành điểm hẹn quen thuộc của giới trẻ và nhiếp ảnh gia, nhất là vào lúc bình minh hay hoàng hôn khi ánh sáng phủ lên những nhịp cầu thép hoen gỉ theo thời gian. Nằm sát khu phố cổ và chợ Long Biên nhộn nhịp, ga còn là nơi cảm nhận rõ nhịp sống đời thường của người Hà Nội. Dù quy mô khiêm tốn, Ga Long Biên vẫn là một mảnh ghép giàu ký ức trong bức tranh đô thị của thủ đô ngàn năm.",
    "Right at the inner-city end of Long Bien Bridge, Long Bien Station is a small but deeply nostalgic Hanoi station. It is bound to the Long Bien Bridge, a steel structure built by the French in the early 20th century that was once a symbol of the capital and a witness to many historical events. Trains from Long Bien Station cross the bridge over the silt-laden Red River, creating a scene both antique and poetic. For this reason the station and bridgehead have long been a favourite haunt of young people and photographers, especially at dawn or dusk when light falls on the time-worn steel spans. Beside the Old Quarter and the busy Long Bien market, the station is also a place to feel the everyday rhythm of Hanoi life. Modest though it is, Long Bien Station remains a memory-rich piece in the urban portrait of the thousand-year-old capital.",
    "Прямо у городского конца моста Лонгбьен станция Лонгбьен — маленькая, но очень ностальгическая станция Ханоя. Она связана с мостом Лонгбьен, стальным сооружением, построенным французами в начале XX века, который некогда был символом столицы и свидетелем многих исторических событий. Поезда от станции Лонгбьен идут по мосту над мутной от ила Красной рекой, создавая картину и старинную, и поэтичную. Поэтому станция и въезд на мост давно стали любимым местом молодёжи и фотографов, особенно на рассвете или закате, когда свет ложится на потемневшие от времени стальные пролёты. Рядом со Старым кварталом и оживлённым рынком Лонгбьен станция позволяет ощутить повседневный ритм ханойской жизни. Несмотря на скромные размеры, станция Лонгбьен остаётся полным памяти фрагментом городского портрета тысячелетней столицы.",
    ["Ga nhỏ ngay đầu cầu Long Biên hơn trăm tuổi bắc qua sông Hồng",
     "Điểm ngắm tàu, chụp ảnh hoài cổ nổi tiếng, gần phố cổ",
     "Đẹp nhất lúc bình minh, hoàng hôn trên những nhịp cầu thép"],
    ["A small station at the head of the century-old Long Bien Bridge",
     "A famous train-watching and nostalgic photo spot near the Old Quarter",
     "Loveliest at dawn and dusk over the steel spans"],
    ["Маленькая станция у столетнего моста Лонгбьен через Красную реку",
     "Известное место фото и наблюдения за поездами у Старого квартала",
     "Красивее всего на рассвете и закате над стальными пролётами"],
    {"hours_vi": "Theo lịch tàu; khu đầu cầu có thể ghé cả ngày.",
     "ticket_vi": "Không mất phí tham quan khu vực ga và đầu cầu.",
     "duration_vi": "Khoảng 30–45 phút.",
     "best_time_vi": "Bình minh hoặc hoàng hôn để chụp ảnh đẹp.",
     "tips_vi": "Tuyệt đối không đi bộ/đứng trên đường ray khi có tàu; chú ý an toàn giao thông đầu cầu."},
    ["railway", "historic", "photo", "bridge", "city"],
    [{"title": "Long Biên Bridge (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Long_Bi%C3%AAn_Bridge"}],
))
ITEMS.append(rec(
    "vn-lao-cai", "Lào Cai", "Miền Bắc", "ga-lao-cai",
    "Ga Lào Cai", "Lao Cai Railway Station", "Железнодорожный вокзал Лаокай",
    CATS, 22.4925, 103.9783,
    "Phường Phố Mới, thành phố Lào Cai, tỉnh Lào Cai",
    {"value": 4.2, "count": 1400, "source": "Google", "as_of": "2026-07"},
    "Du khách quốc tế và trong nước thường qua ga này để lên Sa Pa; khen ga sạch sẽ, thuận tiện, gần cửa khẩu; nhiều người đi tàu đêm Hà Nội – Lào Cai rồi trung chuyển lên núi.",
    "Ga Lào Cai là ga cuối tuyến đường sắt Hà Nội – Lào Cai, sát biên giới Việt – Trung. Đây là cửa ngõ đường sắt lên Sa Pa và sang Hà Khẩu (Trung Quốc), điểm trung chuyển quen thuộc của du khách.",
    "Lao Cai Station is the terminus of the Hanoi–Lao Cai line, close to the Vietnam–China border. It is the rail gateway to Sa Pa and to Hekou in China, a familiar transfer point for travellers.",
    "Вокзал Лаокай — конечная станция линии Ханой–Лаокай у вьетнамо-китайской границы. Это железнодорожные ворота в Сапу и в Хэкоу (Китай), привычный пересадочный пункт для путешественников.",
    "Toạ lạc ở phường Phố Mới sát sông Nậm Thi và đường biên giới Việt – Trung, Ga Lào Cai là điểm cuối của tuyến đường sắt Hà Nội – Lào Cai và là một trong những nhà ga biên giới quan trọng nhất cả nước. Với du khách, đây là cửa ngõ đường sắt quen thuộc để đến với Sa Pa mờ sương và vùng núi Tây Bắc: rất nhiều người chọn đi chuyến tàu đêm từ Hà Nội, sáng sớm xuống ga rồi bắt xe lên Sa Pa, vừa tiết kiệm thời gian vừa có trải nghiệm thú vị. Ga cũng nằm gần cửa khẩu quốc tế Lào Cai – Hà Khẩu, nơi có thể nối ray sang Trung Quốc, khiến nơi đây mang không khí giao thương sôi động của một đô thị biên giới. Nhà ga được đầu tư khang trang, sạch sẽ, có khu chờ và dịch vụ phục vụ lượng khách du lịch lớn quanh năm. Không chỉ là đầu mối giao thông, Ga Lào Cai còn là điểm khởi đầu cho hành trình khám phá ruộng bậc thang, chợ phiên và văn hóa các dân tộc vùng cao.",
    "In Pho Moi ward beside the Nam Thi River and the Vietnam–China border, Lao Cai Station is the terminus of the Hanoi–Lao Cai line and one of the most important border stations in the country. For travellers it is the familiar rail gateway to misty Sa Pa and the north-western mountains: many take the night train from Hanoi, arrive at dawn and catch a bus up to Sa Pa, saving time and enjoying the experience. The station is also near the Lao Cai–Hekou international border crossing, where the tracks can link into China, giving the place the lively trading air of a border town. Handsomely built and clean, it has waiting areas and services for the large flow of tourists all year. More than a transport hub, Lao Cai Station is the starting point for journeys to explore terraced rice fields, upland markets and the cultures of the mountain peoples.",
    "В квартале Фомой у реки Намтхи и вьетнамо-китайской границы вокзал Лаокай — конечная станция линии Ханой–Лаокай и один из важнейших пограничных вокзалов страны. Для путешественников это привычные железнодорожные ворота в туманную Сапу и северо-западные горы: многие едут ночным поездом из Ханоя, прибывают на рассвете и садятся на автобус до Сапы, экономя время и получая удовольствие. Вокзал также находится рядом с международным пунктом пропуска Лаокай–Хэкоу, где пути могут соединяться с Китаем, что придаёт месту оживлённую торговую атмосферу пограничного города. Благоустроенный и чистый, он имеет залы ожидания и услуги для большого потока туристов круглый год. Больше чем транспортный узел, вокзал Лаокай — отправная точка для знакомства с рисовыми террасами, горными ярмарками и культурой народов гор.",
    ["Ga cuối tuyến Hà Nội – Lào Cai, sát biên giới Việt – Trung",
     "Cửa ngõ đường sắt lên Sa Pa và sang Hà Khẩu (Trung Quốc)",
     "Điểm trung chuyển quen thuộc của tàu đêm cho du khách"],
    ["Terminus of the Hanoi–Lao Cai line, close to the China border",
     "Rail gateway to Sa Pa and to Hekou in China",
     "A familiar night-train transfer point for travellers"],
    ["Конечная линии Ханой–Лаокай у границы с Китаем",
     "Железнодорожные ворота в Сапу и в Хэкоу (Китай)",
     "Привычный пересадочный пункт ночного поезда"],
    {"hours_vi": "Theo lịch tàu; đông vào các chuyến tàu đêm và mùa du lịch Sa Pa.",
     "ticket_vi": "Vào ga không mất phí; vé tàu Hà Nội – Lào Cai tùy loại toa.",
     "duration_vi": "Khoảng 20–30 phút; chủ yếu là điểm trung chuyển.",
     "best_time_vi": "Quanh năm; sáng sớm khi tàu đêm về ga rồi nối chuyến lên Sa Pa.",
     "tips_vi": "Đặt trước xe/tour lên Sa Pa; giữ giấy tờ nếu qua khu vực cửa khẩu; chú ý tư trang."},
    ["railway", "border", "gateway", "sapa", "city"],
    [{"title": "Lào Cai station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/L%C3%A0o_Cai_station"}],
))
ITEMS.append(rec(
    "vn-lang-son", "Lạng Sơn", "Miền Bắc", "ga-dong-dang",
    "Ga Đồng Đăng", "Dong Dang Railway Station", "Железнодорожная станция Донгданг",
    CATS, 21.9458, 106.6975,
    "Thị trấn Đồng Đăng, huyện Cao Lộc, tỉnh Lạng Sơn",
    {"value": 4.1, "count": 700, "source": "Google", "as_of": "2026-07"},
    "Du khách thấy ga mang tính biểu tượng vì là ga liên vận quốc tế sát cửa khẩu; nhiều người biết đến ga qua sự kiện đón lãnh đạo quốc tế và các chuyến tàu đi Trung Quốc.",
    "Ga Đồng Đăng là ga đường sắt quốc tế cuối cùng của Việt Nam trước cửa khẩu Hữu Nghị, nối sang Bằng Tường (Trung Quốc). Khai trương từ 1889, đây là ga biên giới mang tính biểu tượng.",
    "Dong Dang Station is Vietnam's last international railway station before the Huu Nghi border gate, linking to Pingxiang in China. Opened in 1889, it is a symbolic border station.",
    "Станция Донгданг — последняя международная железнодорожная станция Вьетнама перед пограничным пунктом Хыунги, соединяющая с Пинсяном в Китае. Открытая в 1889 году, это символичная пограничная станция.",
    "Nằm ở thị trấn Đồng Đăng, huyện Cao Lộc, sát biên giới phía bắc, Ga Đồng Đăng là ga đường sắt liên vận quốc tế cuối cùng trên đất Việt Nam trước khi tuyến ray vượt qua cửa khẩu Hữu Nghị để sang ga Bằng Tường thuộc Quảng Tây, Trung Quốc. Được xây dựng từ năm 1889, ga có bề dày lịch sử gắn với tuyến đường sắt Hà Nội – Đồng Đăng và hoạt động giao thương, đi lại xuyên biên giới. Đây là nơi làm thủ tục cho các chuyến tàu liên vận quốc tế, và cũng từng được nhiều người biết đến khi đón các đoàn lãnh đạo cấp cao tới Việt Nam bằng tàu hỏa. Với khổ đường sắt lồng đặc thù cho phép cả tàu Việt Nam và Trung Quốc vận hành, Ga Đồng Đăng mang ý nghĩa quan trọng về giao thông và đối ngoại. Không gian ga nhuốm màu thời gian, cùng khung cảnh núi non biên ải và không khí giao thương nhộn nhịp của vùng cửa khẩu, tạo nên sức hút riêng đối với những du khách yêu thích lịch sử và đường sắt.",
    "In the town of Dong Dang, Cao Loc district, right on the northern border, Dong Dang Station is Vietnam's last international railway station before the tracks cross the Huu Nghi border gate to Pingxiang Station in Guangxi, China. Built in 1889, it has a long history tied to the Hanoi–Dong Dang line and to cross-border trade and travel. It is where international through-trains complete their formalities, and it became widely known when high-level leaders arrived in Vietnam by train. With its special dual-gauge track allowing both Vietnamese and Chinese trains, Dong Dang Station carries real importance for transport and diplomacy. The time-worn station, the frontier mountain scenery and the lively trading atmosphere of the border area give it a distinctive appeal for travellers who love history and railways.",
    "В городке Донгданг уезда Каолок, прямо на северной границе, станция Донгданг — последняя международная железнодорожная станция Вьетнама перед тем, как пути пересекают пограничный пункт Хыунги к станции Пинсян в Гуанси, Китай. Построенная в 1889 году, она имеет долгую историю, связанную с линией Ханой–Донгданг и трансграничной торговлей и поездками. Здесь международные прямые поезда проходят формальности, а известность станция получила, когда высокопоставленные руководители прибывали во Вьетнам поездом. Со своей особой совмещённой колеёй, позволяющей ходить и вьетнамским, и китайским поездам, станция Донгданг важна для транспорта и дипломатии. Тронутая временем станция, пограничные горные пейзажи и оживлённая торговая атмосфера приграничья придают ей особую привлекательность для любителей истории и железных дорог.",
    ["Ga liên vận quốc tế cuối cùng trước cửa khẩu Hữu Nghị sang Trung Quốc",
     "Khai trương 1889; khổ đường lồng cho cả tàu Việt Nam và Trung Quốc",
     "Ga biên giới biểu tượng, từng đón các đoàn lãnh đạo cấp cao"],
    ["Vietnam's last international station before the Huu Nghi gate to China",
     "Opened 1889; dual-gauge track for both Vietnamese and Chinese trains",
     "A symbolic border station that has welcomed high-level leaders"],
    ["Последняя международная станция перед пунктом Хыунги в Китай",
     "Открыта в 1889; совмещённая колея для вьетнамских и китайских поездов",
     "Символичная пограничная станция, встречавшая высоких руководителей"],
    {"hours_vi": "Theo lịch tàu liên vận và nội địa; thủ tục xuất nhập cảnh riêng.",
     "ticket_vi": "Vào ga không mất phí; vé tàu liên vận quốc tế mua theo quy định.",
     "duration_vi": "Khoảng 30–45 phút tham quan bên ngoài.",
     "best_time_vi": "Ban ngày; kết hợp tham quan cửa khẩu Hữu Nghị, đền Mẫu Đồng Đăng.",
     "tips_vi": "Mang theo giấy tờ tùy thân khi vào khu vực gần biên giới; tuân thủ hướng dẫn an ninh."},
    ["railway", "border", "historic", "international"],
    [{"title": "Đồng Đăng station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/%C4%90%E1%BB%93ng_%C4%90%C4%83ng_station"}],
))
ITEMS.append(rec(
    "vn-ninh-binh", "Ninh Bình", "Miền Bắc", "ga-ninh-binh",
    "Ga Ninh Bình", "Ninh Binh Railway Station", "Железнодорожная станция Ниньбинь",
    CATS, 20.2419, 105.9750,
    "Trung tâm thành phố Hoa Lư (TP Ninh Bình cũ), tỉnh Ninh Bình",
    {"value": 4.2, "count": 900, "source": "Google", "as_of": "2026-07"},
    "Du khách thấy ga tiện lợi để tới Tràng An, Tam Cốc, chùa Bái Đính; nhiều khách quốc tế đi tàu từ Hà Nội xuống rồi khám phá vùng di sản, khen ga gần trung tâm.",
    "Ga Ninh Bình nằm trên tuyến đường sắt Thống Nhất, ngay trung tâm thành phố. Đây là cửa ngõ đường sắt thuận tiện để đến với quần thể di sản Tràng An, Tam Cốc – Bích Động và chùa Bái Đính.",
    "Ninh Binh Station lies on the North–South railway right in the city centre. It is a convenient rail gateway to the Trang An heritage complex, Tam Coc–Bich Dong and Bai Dinh Pagoda.",
    "Станция Ниньбинь расположена на железной дороге Север–Юг прямо в центре города. Это удобные железнодорожные ворота к наследию Чанган, Тамкок–Бидьдонг и пагоде Байдинь.",
    "Nằm ngay trung tâm đô thị, Ga Ninh Bình là một điểm dừng quen thuộc trên tuyến đường sắt Thống Nhất Bắc – Nam và là cửa ngõ đường sắt lý tưởng để khám phá vùng đất cố đô Hoa Lư giàu di sản. Từ nhà ga, du khách chỉ mất một quãng đường ngắn là tới được những danh thắng nổi tiếng bậc nhất miền Bắc: Quần thể danh thắng Tràng An được UNESCO ghi danh, khu Tam Cốc – Bích Động thơ mộng với những chuyến đò luồn hang, chùa Bái Đính quy mô lớn, hay cố đô Hoa Lư ngàn năm tuổi. Vì thế, rất nhiều du khách, đặc biệt là khách quốc tế, lựa chọn đi tàu hỏa từ Hà Nội xuống Ninh Bình chỉ trong khoảng hai giờ, vừa ngắm cảnh đồng quê Bắc Bộ, vừa tiết kiệm chi phí. Nhà ga tuy không quá lớn nhưng sạch sẽ, thuận tiện, nằm gần các tuyến xe đi các điểm tham quan. Là điểm khởi đầu cho hành trình về với 'Hạ Long trên cạn', Ga Ninh Bình đóng vai trò quan trọng trong việc kết nối du khách với một trong những vùng du lịch hấp dẫn nhất Việt Nam.",
    "Right in the city centre, Ninh Binh Station is a familiar stop on the North–South Reunification railway and an ideal rail gateway to explore the heritage-rich land of the ancient capital of Hoa Lu. From the station it is only a short ride to some of the north's most famous sights: the UNESCO-listed Trang An Scenic Landscape Complex, the poetic Tam Coc–Bich Dong with its boat trips through caves, the vast Bai Dinh Pagoda and the thousand-year-old capital of Hoa Lu. Many travellers, especially international visitors, therefore take the train from Hanoi to Ninh Binh in about two hours, enjoying the northern countryside while saving money. The station is not large but is clean and convenient, close to transport to the sights. As the starting point for a journey to the land often called Ha Long Bay on land, Ninh Binh Station plays an important role in connecting travellers with one of Vietnam's most attractive tourist regions.",
    "Прямо в центре города станция Ниньбинь — привычная остановка на объединяющей железной дороге Север–Юг и идеальные железнодорожные ворота для знакомства с богатой наследием землёй древней столицы Хоалы. От станции лишь короткая поездка до самых знаменитых достопримечательностей севера: внесённого в список ЮНЕСКО ландшафтного комплекса Чанган, поэтичного Тамкок–Бидьдонг с прогулками на лодках сквозь пещеры, огромной пагоды Байдинь и тысячелетней столицы Хоалы. Поэтому многие путешественники, особенно иностранные, едут поездом из Ханоя в Ниньбинь примерно за два часа, любуясь северной сельской местностью и экономя средства. Станция невелика, но чистая и удобная, рядом с транспортом к достопримечательностям. Как отправная точка путешествия в край, который часто называют «сухопутной бухтой Халонг», станция Ниньбинь играет важную роль, связывая путешественников с одним из самых привлекательных туристических регионов Вьетнама.",
    ["Ga trên tuyến Thống Nhất, ngay trung tâm thành phố",
     "Cửa ngõ tới Tràng An, Tam Cốc – Bích Động, chùa Bái Đính, cố đô Hoa Lư",
     "Khách quốc tế thường đi tàu ~2 giờ từ Hà Nội xuống khám phá di sản"],
    ["A North–South line station right in the city centre",
     "Gateway to Trang An, Tam Coc–Bich Dong, Bai Dinh and Hoa Lu",
     "International visitors often ride ~2 hours from Hanoi to explore"],
    ["Станция на линии Север–Юг прямо в центре города",
     "Ворота к Чанган, Тамкок–Бидьдонг, Байдинь и Хоалы",
     "Иностранцы часто едут ~2 часа из Ханоя ради наследия"],
    {"hours_vi": "Theo lịch tàu Thống Nhất hằng ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu Hà Nội – Ninh Bình tùy loại toa.",
     "duration_vi": "Khoảng 15–30 phút; chủ yếu là điểm trung chuyển.",
     "best_time_vi": "Quanh năm; mùa lúa Tam Cốc (tháng 5–6) cảnh đẹp.",
     "tips_vi": "Đặt trước xe/tour đi Tràng An, Tam Cốc; đi tàu nên chọn chuyến ban ngày để ngắm cảnh."},
    ["railway", "gateway", "unesco", "city", "family"],
    [{"title": "Ninh Bình station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Ninh_B%C3%ACnh_station"}],
))
ITEMS.append(rec(
    "vn-thanh-hoa", "Thanh Hóa", "Miền Trung", "ga-thanh-hoa",
    "Ga Thanh Hóa", "Thanh Hoa Railway Station", "Железнодорожная станция Тханьхоа",
    CATS, 19.8128, 105.7678,
    "Trung tâm thành phố Thanh Hóa, tỉnh Thanh Hóa",
    {"value": 4.1, "count": 800, "source": "Google", "as_of": "2026-07"},
    "Du khách thấy ga thuận tiện để về xứ Thanh, đi Sầm Sơn, thành nhà Hồ, suối cá Cẩm Lương; ga nằm ngay trung tâm, dễ bắt xe đi các điểm.",
    "Ga Thanh Hóa là một trong những ga lớn trên tuyến đường sắt Thống Nhất, nằm ngay trung tâm thành phố. Đây là cửa ngõ đường sắt của xứ Thanh, thuận tiện đi biển Sầm Sơn và các di tích nổi tiếng.",
    "Thanh Hoa Station is one of the main stations on the North–South railway, right in the city centre. It is the rail gateway of the Thanh land, convenient for Sam Son beach and famous relics.",
    "Станция Тханьхоа — одна из крупных станций железной дороги Север–Юг, прямо в центре города. Это железнодорожные ворота земли Тхань, удобные для пляжа Шамшон и знаменитых памятников.",
    "Nằm ngay trung tâm thành phố, Ga Thanh Hóa là một trong những nhà ga lớn và quan trọng trên tuyến đường sắt Thống Nhất Bắc – Nam, đóng vai trò cửa ngõ đường sắt của cả vùng đất xứ Thanh giàu truyền thống. Từ nhà ga, du khách có thể dễ dàng di chuyển tới nhiều điểm đến hấp dẫn của tỉnh: bãi biển Sầm Sơn nổi tiếng chỉ cách chừng 15 km, Thành nhà Hồ — Di sản Thế giới được UNESCO ghi danh, suối cá thần Cẩm Lương kỳ lạ, hay Khu di tích Lam Kinh gắn với triều Hậu Lê. Là tỉnh đông dân và có vị trí bản lề giữa Bắc Bộ và Bắc Trung Bộ, Thanh Hóa có lượng hành khách đi tàu rất lớn, và nhà ga luôn nhộn nhịp người lên xuống, nhất là vào mùa hè và các dịp lễ, Tết. Nằm ngay trung tâm, ga thuận tiện kết nối với xe khách, xe buýt đi khắp tỉnh. Không chỉ là đầu mối giao thông, Ga Thanh Hóa còn là điểm khởi đầu cho hành trình khám phá biển, di sản và văn hóa của một trong những vùng đất địa linh nhân kiệt của Việt Nam.",
    "Right in the city centre, Thanh Hoa Station is one of the main and most important stations on the North–South Reunification railway, serving as the rail gateway of the whole tradition-rich Thanh land. From the station travellers can easily reach many appealing sites in the province: the famous Sam Son beach about 15 km away, the Ho Citadel, a UNESCO World Heritage Site, the strange sacred fish stream of Cam Luong and the Lam Kinh relic area linked to the Later Le dynasty. As a populous province in a pivotal position between the northern delta and the north-central coast, Thanh Hoa has a very large flow of rail passengers, and the station is always busy, especially in summer and at festivals and Tet. Central and well connected to coaches and buses across the province, it is more than a transport hub: Thanh Hoa Station is a starting point for exploring the beaches, heritage and culture of one of Vietnam's storied lands.",
    "Прямо в центре города станция Тханьхоа — одна из главных и важнейших станций объединяющей железной дороги Север–Юг, служащая железнодорожными воротами всей богатой традициями земли Тхань. От станции путешественники легко добираются до многих привлекательных мест провинции: знаменитого пляжа Шамшон примерно в 15 км, цитадели Хо — объекта Всемирного наследия ЮНЕСКО, удивительного ручья со священной рыбой Камлыонг и памятного комплекса Ламкинь, связанного с династией Поздняя Ле. Будучи многонаселённой провинцией на ключевом стыке северной дельты и северо-центрального побережья, Тханьхоа имеет очень большой поток пассажиров, и станция всегда оживлена, особенно летом, на праздники и Тет. Центральная и хорошо связанная с автобусами по всей провинции, она больше чем транспортный узел: станция Тханьхоа — отправная точка для знакомства с пляжами, наследием и культурой одной из легендарных земель Вьетнама.",
    ["Ga lớn trên tuyến Thống Nhất, ngay trung tâm thành phố",
     "Cửa ngõ đi biển Sầm Sơn, Thành nhà Hồ, suối cá Cẩm Lương, Lam Kinh",
     "Lượng khách đi tàu lớn, nhộn nhịp dịp hè và lễ, Tết"],
    ["A major North–South line station in the city centre",
     "Gateway to Sam Son beach, Ho Citadel, Cam Luong fish stream, Lam Kinh",
     "A busy station with heavy passenger flow in summer and holidays"],
    ["Крупная станция линии Север–Юг в центре города",
     "Ворота к пляжу Шамшон, цитадели Хо, ручью Камлыонг, Ламкинь",
     "Оживлённая станция с большим потоком летом и в праздники"],
    {"hours_vi": "Theo lịch tàu Thống Nhất hằng ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 15–30 phút; điểm trung chuyển.",
     "best_time_vi": "Mùa hè đi biển Sầm Sơn; quanh năm cho các di tích.",
     "tips_vi": "Đặt vé trước dịp hè và lễ Tết; sắp xếp xe tiếp chuyển tới điểm tham quan."},
    ["railway", "gateway", "city", "family"],
    [{"title": "Thanh Hóa station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Thanh_H%C3%B3a_station"}],
))
ITEMS.append(rec(
    "vn-nghe-an", "Nghệ An", "Miền Trung", "ga-vinh",
    "Ga Vinh", "Vinh Railway Station", "Железнодорожный вокзал Виня",
    CATS, 18.6883, 105.6644,
    "Trung tâm thành phố Vinh, tỉnh Nghệ An",
    {"value": 4.1, "count": 1000, "source": "Google", "as_of": "2026-07"},
    "Du khách đi tàu về Nghệ An thăm quê Bác (Kim Liên), biển Cửa Lò; khen ga lớn, hiện đại, tiện kết nối; là đầu mối quan trọng của Bắc Trung Bộ.",
    "Ga Vinh là một trong những ga lớn nhất Bắc Trung Bộ trên tuyến đường sắt Thống Nhất. Đây là cửa ngõ đường sắt về thành phố Vinh, quê hương Chủ tịch Hồ Chí Minh và biển Cửa Lò.",
    "Vinh Station is one of the largest stations in the north-central region on the North–South railway. It is the rail gateway to Vinh city, the homeland of President Ho Chi Minh, and to Cua Lo beach.",
    "Вокзал Виня — один из крупнейших вокзалов северо-центрального региона на железной дороге Север–Юг. Это железнодорожные ворота в город Винь, на родину президента Хо Ши Мина, и к пляжу Кыало.",
    "Toạ lạc ngay trung tâm thành phố Vinh, Ga Vinh là một trong những nhà ga lớn và sầm uất nhất khu vực Bắc Trung Bộ, giữ vai trò đầu mối quan trọng trên tuyến đường sắt Thống Nhất Bắc – Nam. Là thủ phủ của tỉnh Nghệ An đông dân, Vinh có lượng hành khách đi tàu rất lớn, và nhà ga được đầu tư khang trang, hiện đại để phục vụ nhu cầu đi lại quanh năm. Với du khách, Ga Vinh là cửa ngõ thuận tiện để về thăm những điểm đến giàu ý nghĩa của xứ Nghệ: Khu di tích Kim Liên — quê hương Chủ tịch Hồ Chí Minh chỉ cách chừng 15 km, bãi biển Cửa Lò lộng gió, đền Ông Hoàng Mười linh thiêng, hay ngược lên miền tây Nghệ An với vườn quốc gia Pù Mát. Nằm ở vị trí bản lề trên trục giao thông Bắc – Nam, ga còn kết nối thuận tiện với hệ thống xe khách đi khắp các tỉnh và sang nước bạn Lào. Không chỉ là nơi lên xuống tàu, Ga Vinh còn phản ánh nhịp sống năng động của một đô thị trung tâm vùng Bắc Trung Bộ.",
    "Right in the centre of Vinh city, Vinh Station is one of the largest and busiest stations in the north-central region and an important hub on the North–South Reunification railway. As the capital of populous Nghe An province, Vinh has a very large flow of rail passengers, and the station has been handsomely and modernly built to serve year-round demand. For travellers, Vinh Station is a convenient gateway to the meaningful sights of the Nghe land: the Kim Lien relic area, homeland of President Ho Chi Minh, about 15 km away, the breezy Cua Lo beach, the sacred Ong Hoang Muoi Temple, or west into Nghe An to Pu Mat National Park. In a pivotal position on the North–South axis, the station also connects well with coaches across the provinces and into neighbouring Laos. More than a place to board trains, Vinh Station reflects the dynamic life of a central city of the north-central region.",
    "Прямо в центре города Винь вокзал Виня — один из крупнейших и оживлённейших вокзалов северо-центрального региона и важный узел объединяющей железной дороги Север–Юг. Как столица многонаселённой провинции Нгеан, Винь имеет очень большой поток пассажиров, и вокзал построен благоустроенно и современно для круглогодичного спроса. Для путешественников вокзал Виня — удобные ворота к значимым местам земли Нге: памятному комплексу Кимлиен, родине президента Хо Ши Мина, примерно в 15 км, обдуваемому ветрами пляжу Кыало, священному храму Онгхоангмыой или на запад Нгеана к национальному парку Пумат. В ключевом положении на оси Север–Юг вокзал также хорошо связан с автобусами по провинциям и в соседний Лаос. Больше чем место посадки на поезда, вокзал Виня отражает динамичную жизнь центрального города северо-центрального региона.",
    ["Ga lớn bậc nhất Bắc Trung Bộ trên tuyến Thống Nhất",
     "Cửa ngõ về quê Bác (Kim Liên), biển Cửa Lò, đền Ông Hoàng Mười",
     "Đầu mối giao thông kết nối các tỉnh và sang Lào"],
    ["A leading north-central station on the North–South line",
     "Gateway to Ho Chi Minh's homeland (Kim Lien), Cua Lo beach, Ong Hoang Muoi Temple",
     "A hub connecting the provinces and into Laos"],
    ["Ведущий вокзал северо-центра на линии Север–Юг",
     "Ворота к родине Хо Ши Мина (Кимлиен), пляжу Кыало, храму Онгхоангмыой",
     "Узел, связывающий провинции и Лаос"],
    {"hours_vi": "Theo lịch tàu Thống Nhất hằng ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 15–30 phút; điểm trung chuyển.",
     "best_time_vi": "Mùa hè đi Cửa Lò; quanh năm về Kim Liên.",
     "tips_vi": "Đặt vé sớm dịp hè, lễ; kết hợp thăm quê Bác và tắm biển Cửa Lò."},
    ["railway", "gateway", "city", "family"],
    [{"title": "Vinh station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Vinh_station"}],
))
ITEMS.append(rec(
    "vn-thua-thien-hue", "Huế", "Miền Trung", "ga-hue",
    "Ga Huế", "Hue Railway Station", "Железнодорожный вокзал Хюэ",
    CATS, 16.4565, 107.5778,
    "2 Bùi Thị Xuân, phường Đúc, thành phố Huế, tỉnh Thừa Thiên Huế",
    {"value": 4.4, "count": 1300, "source": "Google", "as_of": "2026-07"},
    "Du khách khen ga Huế đẹp, mang kiến trúc Pháp cổ màu hồng vàng nổi bật; nhiều người thích đoạn tàu qua đèo Hải Vân xuất phát/đến Huế, coi là một trong những cung đường tàu đẹp nhất.",
    "Ga Huế là nhà ga cổ kính khánh thành năm 1906, mang kiến trúc Pháp duyên dáng ngay trung tâm cố đô. Đây là điểm dừng nổi tiếng, gần cung đường tàu vượt đèo Hải Vân ngoạn mục.",
    "Hue Station, opened in 1906, is a graceful French-style station in the heart of the old imperial city. It is a famous stop near the spectacular Hai Van Pass railway route.",
    "Вокзал Хюэ, открытый в 1906 году, — изящный вокзал во французском стиле в сердце старой императорской столицы. Это знаменитая остановка у зрелищного железнодорожного маршрута через перевал Хайван.",
    "Nằm ở cuối đường Lê Lợi bên bờ nam sông Hương, Ga Huế là một trong những nhà ga đẹp và cổ kính nhất Việt Nam, được người Pháp xây dựng và khánh thành năm 1906. Nhà ga khoác lối kiến trúc Pháp duyên dáng với gam màu vàng – hồng đặc trưng, mái ngói và những đường nét mềm mại rất hợp với vẻ trầm mặc, thơ mộng của xứ Huế. Là ga chính của cố đô trên tuyến đường sắt Thống Nhất, đây là điểm lên xuống tàu quen thuộc của du khách khi đến thăm Kinh thành, các lăng tẩm triều Nguyễn, chùa Thiên Mụ và thưởng thức ẩm thực cung đình. Đặc biệt, đoạn đường sắt từ Huế đi Đà Nẵng vượt qua đèo Hải Vân được xem là một trong những cung đường tàu đẹp nhất thế giới, với một bên là núi rừng, một bên là biển xanh; nhiều du khách chọn đi tàu chặng này chỉ để ngắm cảnh. Vì thế, Ga Huế không chỉ là đầu mối giao thông mà còn là một điểm đến mang giá trị kiến trúc, lịch sử và là khởi đầu cho những trải nghiệm du lịch đường sắt khó quên ở miền Trung.",
    "At the end of Le Loi Street on the south bank of the Perfume River, Hue Station is one of the most beautiful and antique stations in Vietnam, built by the French and opened in 1906. It wears graceful French architecture in its signature yellow-and-pink, with a tiled roof and soft lines that suit the serene, poetic character of Hue. As the imperial city's main station on the North–South railway, it is a familiar arrival point for visitors coming to see the Citadel, the Nguyen royal tombs, Thien Mu Pagoda and to taste the royal cuisine. Above all, the rail line from Hue to Da Nang over the Hai Van Pass is regarded as one of the most beautiful train routes in the world, with mountains on one side and blue sea on the other; many travellers ride this stretch just for the scenery. Hue Station is thus not only a transport hub but a destination of architectural and historical value, and the starting point for unforgettable rail-travel experiences in central Vietnam.",
    "В конце улицы Лелой на южном берегу Ароматной реки вокзал Хюэ — один из красивейших и самых старинных вокзалов Вьетнама, построенный французами и открытый в 1906 году. Он одет в изящную французскую архитектуру своего фирменного жёлто-розового цвета, с черепичной крышей и мягкими линиями, что созвучно безмятежному, поэтичному характеру Хюэ. Как главный вокзал императорской столицы на железной дороге Север–Юг, это привычный пункт прибытия для гостей, приезжающих осмотреть Цитадель, гробницы нгуенских императоров, пагоду Тхьенму и отведать императорскую кухню. Прежде всего, железнодорожная линия из Хюэ в Дананг через перевал Хайван считается одним из красивейших поездных маршрутов мира: с одной стороны горы, с другой — синее море; многие путешественники едут по этому участку ради пейзажей. Поэтому вокзал Хюэ — не только транспортный узел, но и достопримечательность архитектурной и исторической ценности, отправная точка незабываемых железнодорожных впечатлений в центральном Вьетнаме.",
    ["Ga khánh thành 1906, kiến trúc Pháp vàng – hồng duyên dáng ở cố đô",
     "Cửa ngõ tới Kinh thành Huế, lăng tẩm triều Nguyễn, chùa Thiên Mụ",
     "Gần cung đường tàu vượt đèo Hải Vân đẹp bậc nhất thế giới"],
    ["A station opened in 1906 with graceful yellow-pink French architecture",
     "Gateway to the Hue Citadel, Nguyen tombs and Thien Mu Pagoda",
     "Near the world-class Hai Van Pass railway route"],
    ["Вокзал 1906 года с изящной жёлто-розовой французской архитектурой",
     "Ворота к Цитадели Хюэ, гробницам Нгуенов и пагоде Тхьенму",
     "Рядом с маршрутом через перевал Хайван мирового класса"],
    {"hours_vi": "Theo lịch tàu Thống Nhất; sảnh ga mở ban ngày.",
     "ticket_vi": "Vào ga không mất phí; vé chặng Huế – Đà Nẵng qua đèo Hải Vân rất được ưa chuộng.",
     "duration_vi": "Khoảng 20–40 phút tham quan, chụp ảnh.",
     "best_time_vi": "Ban ngày; đi chặng Huế – Đà Nẵng ban ngày để ngắm đèo Hải Vân.",
     "tips_vi": "Đặt vé ghế cửa sổ phía biển khi qua đèo; tới sớm chụp ảnh mặt tiền ga."},
    ["railway", "historic", "photo", "architecture", "scenic", "top"],
    [{"title": "Huế station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Hu%E1%BA%BF_station"}],
))
ITEMS.append(rec(
    "vn-da-nang", "Đà Nẵng", "Miền Trung", "ga-da-nang",
    "Ga Đà Nẵng", "Da Nang Railway Station", "Железнодорожный вокзал Дананга",
    CATS, 16.0716, 108.2092,
    "202 Hải Phòng, quận Thanh Khê, thành phố Đà Nẵng",
    {"value": 4.2, "count": 2200, "source": "Google", "as_of": "2026-07"},
    "Du khách khen ga lớn, hiện đại, tiện đi trung tâm và các bãi biển; nhiều người đặc biệt thích chặng tàu Đà Nẵng – Huế vượt đèo Hải Vân ngắm cảnh.",
    "Ga Đà Nẵng là một trong năm ga lớn nhất Việt Nam trên tuyến đường sắt Thống Nhất, ngay trung tâm thành phố. Đây là cửa ngõ đường sắt tới các bãi biển, Hội An và cung đèo Hải Vân.",
    "Da Nang Station is one of the five largest stations in Vietnam on the North–South railway, right in the city centre. It is the rail gateway to the beaches, Hoi An and the Hai Van Pass.",
    "Вокзал Дананга — один из пяти крупнейших вокзалов Вьетнама на железной дороге Север–Юг, прямо в центре города. Это железнодорожные ворота к пляжам, Хойану и перевалу Хайван.",
    "Nằm ngay trung tâm thành phố biển năng động, Ga Đà Nẵng là một trong năm nhà ga lớn nhất cả nước và là đầu mối quan trọng bậc nhất của miền Trung trên tuyến đường sắt Thống Nhất. Mỗi ngày, ga đón lượng lớn hành khách trong nước và quốc tế, bởi Đà Nẵng vừa là điểm du lịch hàng đầu, vừa là cửa ngõ tới nhiều danh thắng lân cận. Từ nhà ga, du khách dễ dàng tới các bãi biển đẹp như Mỹ Khê, bán đảo Sơn Trà, danh thắng Ngũ Hành Sơn, khu du lịch Bà Nà Hills, và đặc biệt là phố cổ Hội An – Di sản Thế giới chỉ cách chừng 30 km. Một trải nghiệm được nhiều du khách yêu thích là đi tàu chặng ngắn Đà Nẵng – Huế, nơi con tàu men theo đèo Hải Vân hùng vĩ với biển xanh và núi rừng trải dài, được bình chọn là một trong những cung đường sắt đẹp nhất thế giới. Là ga hiện đại, quy mô lớn, kết nối thuận tiện với sân bay và trung tâm, Ga Đà Nẵng đóng vai trò quan trọng trong việc đưa du khách đến với 'thành phố đáng sống' và cả vùng di sản miền Trung.",
    "Right in the centre of the dynamic coastal city, Da Nang Station is one of the five largest stations in the country and a leading hub of central Vietnam on the North–South railway. Each day it handles a large flow of domestic and international passengers, for Da Nang is both a top tourist destination and a gateway to many nearby sights. From the station, travellers easily reach beautiful beaches such as My Khe, the Son Tra Peninsula, the Marble Mountains, Ba Na Hills and, above all, the ancient town of Hoi An, a World Heritage Site only about 30 km away. A favourite experience is the short train ride from Da Nang to Hue, where the train hugs the majestic Hai Van Pass with sweeping sea and mountains, voted one of the most beautiful railway routes in the world. A large, modern station well connected to the airport and the centre, Da Nang Station plays an important role in bringing visitors to this most liveable city and to the central heritage region.",
    "Прямо в центре динамичного приморского города вокзал Дананга — один из пяти крупнейших вокзалов страны и ведущий узел центрального Вьетнама на железной дороге Север–Юг. Каждый день он обслуживает большой поток внутренних и иностранных пассажиров, ведь Дананг — и топовое туристическое направление, и ворота ко многим окрестным достопримечательностям. От вокзала путешественники легко добираются до красивых пляжей, таких как Мичкхе, полуострова Шонча, Мраморных гор, Ба На Хиллс и, прежде всего, до древнего города Хойан — объекта Всемирного наследия всего в 30 км. Любимое впечатление — короткая поездка на поезде из Дананга в Хюэ, где поезд жмётся к величественному перевалу Хайван с широким видом на море и горы, признанному одним из красивейших ж/д маршрутов мира. Крупный современный вокзал, хорошо связанный с аэропортом и центром, вокзал Дананга играет важную роль, привозя гостей в этот самый пригодный для жизни город и в центральный регион наследия.",
    ["Một trong 5 ga lớn nhất Việt Nam, đầu mối quan trọng của miền Trung",
     "Cửa ngõ tới biển Mỹ Khê, Sơn Trà, Ngũ Hành Sơn, Bà Nà, Hội An",
     "Gần chặng tàu Đà Nẵng – Huế vượt đèo Hải Vân tuyệt đẹp"],
    ["One of Vietnam's five largest stations, a key central hub",
     "Gateway to My Khe beach, Son Tra, Marble Mountains, Ba Na, Hoi An",
     "Near the stunning Da Nang–Hue route over the Hai Van Pass"],
    ["Один из пяти крупнейших вокзалов Вьетнама, ключевой узел центра",
     "Ворота к пляжу Мичкхе, Шонча, Мраморным горам, Ба На, Хойану",
     "Рядом с чудесным маршрутом Дананг–Хюэ через перевал Хайван"],
    {"hours_vi": "Theo lịch tàu Thống Nhất hằng ngày.",
     "ticket_vi": "Vào ga không mất phí; vé chặng Đà Nẵng – Huế qua đèo Hải Vân được ưa chuộng.",
     "duration_vi": "Khoảng 20–30 phút; điểm trung chuyển.",
     "best_time_vi": "Quanh năm; đi chặng qua đèo Hải Vân vào ban ngày.",
     "tips_vi": "Đặt vé sớm mùa cao điểm; chọn ghế nhìn ra biển khi qua đèo Hải Vân."},
    ["railway", "gateway", "city", "scenic", "family"],
    [{"title": "Đà Nẵng station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/%C4%90%C3%A0_N%E1%BA%B5ng_station"}],
))
ITEMS.append(rec(
    "vn-gia-lai", "Gia Lai", "Miền Trung", "ga-dieu-tri",
    "Ga Diêu Trì", "Dieu Tri Railway Station", "Железнодорожная станция Зьеучи",
    CATS, 13.8072, 109.1436,
    "Thị trấn Diêu Trì, huyện Tuy Phước (khu vực Bình Định cũ), tỉnh Gia Lai",
    {"value": 4.1, "count": 700, "source": "Google", "as_of": "2026-07"},
    "Du khách đi tàu Bắc – Nam thường xuống Diêu Trì để vào Quy Nhơn; khen ga là đầu mối lớn, thuận tiện trung chuyển ra biển và các điểm du lịch.",
    "Ga Diêu Trì là một trong những ga lớn trên tuyến đường sắt Thống Nhất, đầu mối quan trọng của khu vực. Đây là cửa ngõ đường sắt để vào thành phố biển Quy Nhơn cách đó khoảng 10 km.",
    "Dieu Tri Station is one of the major stations on the North–South railway and an important regional hub. It is the rail gateway to the seaside city of Quy Nhon, about 10 km away.",
    "Станция Зьеучи — одна из крупных станций железной дороги Север–Юг и важный региональный узел. Это железнодорожные ворота к приморскому городу Куиньон примерно в 10 км.",
    "Nằm ở thị trấn Diêu Trì, huyện Tuy Phước thuộc khu vực Bình Định cũ (nay thuộc tỉnh Gia Lai sau sáp nhập), Ga Diêu Trì là một trong những nhà ga lớn và quan trọng bậc nhất trên tuyến đường sắt Thống Nhất Bắc – Nam. Do phần lớn các đoàn tàu Bắc – Nam đều dừng tại đây, Diêu Trì trở thành đầu mối trung chuyển sầm uất, nơi hành khách xuống tàu để tiếp tục vào thành phố biển Quy Nhơn cách chừng 10 km bằng tuyến nhánh hoặc xe. Những năm gần đây, Quy Nhơn nổi lên như một điểm đến biển hấp dẫn với bãi biển dài thơ mộng, Eo Gió, Kỳ Co, Ghềnh Ráng – Tiên Sa gắn với mộ Hàn Mặc Tử, tháp Chăm cổ kính và hải sản tươi ngon; nhờ đó lượng khách qua Ga Diêu Trì ngày càng đông. Nhà ga rộng rãi, có nhiều đường ray đón tiễn các đoàn tàu, và luôn nhộn nhịp cảnh lên xuống, trung chuyển. Là cửa ngõ đường sắt của cả vùng đất võ Bình Định, Ga Diêu Trì đóng vai trò quan trọng trong việc kết nối du khách với biển xanh Quy Nhơn và các di sản văn hóa Chăm đặc sắc của miền Trung.",
    "In the town of Dieu Tri, Tuy Phuoc district in the former Binh Dinh area (now part of Gia Lai province after the merger), Dieu Tri Station is one of the largest and most important stations on the North–South Reunification railway. Because most North–South trains stop here, Dieu Tri is a busy transfer hub where passengers alight to continue about 10 km into the seaside city of Quy Nhon by branch line or road. In recent years Quy Nhon has risen as an appealing beach destination with a long poetic shoreline, Eo Gio, Ky Co, Ghenh Rang–Tien Sa linked to the poet Han Mac Tu's grave, ancient Cham towers and fresh seafood, so the flow of passengers through Dieu Tri keeps growing. The station is spacious, with many tracks for arriving and departing trains, and is always lively with boarding and transfers. As the rail gateway to the martial-arts land of Binh Dinh, Dieu Tri Station plays an important part in connecting travellers to the blue sea of Quy Nhon and the distinctive Cham cultural heritage of central Vietnam.",
    "В городке Зьеучи уезда Туйфыок в бывшей провинции Биньдинь (ныне часть провинции Гиалай после слияния) станция Зьеучи — одна из крупнейших и важнейших станций объединяющей железной дороги Север–Юг. Поскольку здесь останавливается большинство поездов Север–Юг, Зьеучи — оживлённый пересадочный узел, где пассажиры сходят, чтобы проехать около 10 км в приморский город Куиньон по ветке или дорогой. В последние годы Куиньон стал привлекательным пляжным направлением с длинным поэтичным берегом, Эозьо, Кико, Гхеньзанг–Тьенша, связанным с могилой поэта Хан Мак Ты, древними чамскими башнями и свежими морепродуктами, поэтому поток пассажиров через Зьеучи растёт. Станция просторна, со многими путями для приёма поездов, и всегда оживлена посадкой и пересадками. Как железнодорожные ворота земли боевых искусств Биньдинь, станция Зьеучи важна для связи путешественников с синим морем Куиньона и самобытным чамским наследием центрального Вьетнама.",
    ["Ga lớn trên tuyến Thống Nhất, hầu hết tàu Bắc – Nam đều dừng",
     "Cửa ngõ vào thành phố biển Quy Nhơn (~10 km): Eo Gió, Kỳ Co",
     "Trung chuyển tới tháp Chăm, Ghềnh Ráng – Tiên Sa của đất võ Bình Định"],
    ["A major North–South station where most trains stop",
     "Gateway to seaside Quy Nhon (~10 km): Eo Gio, Ky Co",
     "Transfer to Cham towers and Ghenh Rang–Tien Sa in Binh Dinh"],
    ["Крупная станция линии Север–Юг, где останавливаются почти все поезда",
     "Ворота к приморскому Куиньону (~10 км): Эозьо, Кико",
     "Пересадка к чамским башням и Гхеньзанг–Тьенша в Биньдине"],
    {"hours_vi": "Theo lịch tàu Thống Nhất; nhiều tàu dừng ngày và đêm.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 15–30 phút; chủ yếu trung chuyển vào Quy Nhơn.",
     "best_time_vi": "Mùa khô (tháng 3–9) để đi biển Quy Nhơn.",
     "tips_vi": "Chuẩn bị xe vào Quy Nhơn (~10 km); đặt vé sớm mùa cao điểm hè."},
    ["railway", "gateway", "beach", "family"],
    [{"title": "Diêu Trì station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Di%C3%AAu_Tr%C3%AC_station"}],
))
ITEMS.append(rec(
    "vn-khanh-hoa", "Khánh Hòa", "Miền Trung", "ga-thap-cham",
    "Ga Tháp Chàm", "Thap Cham Railway Station", "Железнодорожная станция Тхапчам",
    CATS, 11.5972, 108.9500,
    "Phường Đô Vinh, thành phố Phan Rang – Tháp Chàm (khu vực Ninh Thuận cũ), tỉnh Khánh Hòa",
    {"value": 4.0, "count": 400, "source": "Google", "as_of": "2026-07"},
    "Du khách quan tâm lịch sử đường sắt biết Tháp Chàm là ga gốc của tuyến răng cưa lên Đà Lạt nổi tiếng một thời; ga gần tháp Chăm Po Klong Garai cổ kính.",
    "Ga Tháp Chàm là ga trên tuyến Thống Nhất, từng là điểm khởi đầu của tuyến đường sắt răng cưa độc đáo lên Đà Lạt. Ga nằm gần cụm tháp Chăm Po Klong Garai nổi tiếng.",
    "Thap Cham Station lies on the North–South railway and was once the start of the unique cog railway up to Da Lat. It stands near the famous Po Klong Garai Cham towers.",
    "Станция Тхапчам расположена на железной дороге Север–Юг и некогда была началом уникальной зубчатой железной дороги в Далат. Она стоит рядом со знаменитыми чамскими башнями Поклонгарай.",
    "Nằm ở khu vực Đô Vinh của thành phố Phan Rang – Tháp Chàm (thuộc Ninh Thuận cũ, nay là tỉnh Khánh Hòa sau sáp nhập), Ga Tháp Chàm là một nhà ga giàu giá trị lịch sử trên tuyến đường sắt Thống Nhất. Điều làm nên tên tuổi đặc biệt của ga là trong nửa đầu thế kỷ XX, đây chính là điểm khởi đầu của tuyến đường sắt răng cưa Tháp Chàm – Đà Lạt dài khoảng 84 km, một trong số rất ít tuyến răng cưa trên thế giới, giúp đoàn tàu leo lên cao nguyên Lâm Viên vượt những đoạn dốc lớn. Tuyến đường độc đáo này về sau ngừng hoạt động, nhưng câu chuyện về nó vẫn khiến Ga Tháp Chàm trở thành điểm đến hấp dẫn với những người yêu lịch sử đường sắt. Ngay gần ga là cụm tháp Chăm Po Klong Garai cổ kính xây từ thế kỷ XIII, một trong những di tích Chăm đẹp và nguyên vẹn nhất còn lại, cùng vùng đất Ninh Thuận đầy nắng gió với vườn nho, làng gốm Bàu Trúc và biển Ninh Chữ. Ga Tháp Chàm vì thế là điểm dừng thú vị, gắn kết giữa ký ức đường sắt và di sản văn hóa Chăm đặc sắc.",
    "In the Do Vinh area of Phan Rang–Thap Cham city (in former Ninh Thuan, now Khanh Hoa province after the merger), Thap Cham Station is a historically rich station on the North–South railway. What made its name special is that, in the first half of the 20th century, it was the starting point of the roughly 84 km Thap Cham–Da Lat cog railway, one of very few rack railways in the world, which let trains climb the Lang Bian plateau over steep gradients. That unique line later ceased operating, but its story still makes Thap Cham Station a draw for lovers of railway history. Right beside the station stand the ancient Po Klong Garai Cham towers, built in the 13th century, among the loveliest and best-preserved Cham relics, together with the sun-and-wind land of Ninh Thuan with its vineyards, the Bau Truc pottery village and Ninh Chu beach. Thap Cham Station is thus an interesting stop linking railway memory with the distinctive Cham cultural heritage.",
    "В районе Довинь города Фанранг–Тхапчам (в бывшей провинции Ниньтхуан, ныне провинция Кханьхоа после слияния) станция Тхапчам — богатая историей станция на железной дороге Север–Юг. Особую известность ей принесло то, что в первой половине XX века она была началом зубчатой железной дороги Тхапчам–Далат длиной около 84 км, одной из очень немногих зубчатых дорог мира, что позволяла поездам подниматься на плато Лангбьян по крутым уклонам. Эта уникальная линия позже прекратила работу, но её история по-прежнему делает станцию Тхапчам притягательной для любителей истории железных дорог. Прямо рядом со станцией стоят древние чамские башни Поклонгарай, построенные в XIII веке, среди красивейших и лучше всего сохранившихся чамских памятников, вместе с солнечно-ветреной землёй Ниньтхуан с виноградниками, гончарной деревней Баучук и пляжем Ниньтю. Станция Тхапчам — интересная остановка, связывающая память железных дорог с самобытным чамским культурным наследием.",
    ["Từng là điểm khởi đầu tuyến đường sắt răng cưa Tháp Chàm – Đà Lạt",
     "Một trong số ít tuyến răng cưa từng có trên thế giới",
     "Gần cụm tháp Chăm Po Klong Garai thế kỷ XIII và vùng Ninh Thuận nắng gió"],
    ["Once the start of the Thap Cham–Da Lat cog railway",
     "One of very few rack railways ever built in the world",
     "Near the 13th-century Po Klong Garai Cham towers and sunny Ninh Thuan"],
    ["Некогда начало зубчатой железной дороги Тхапчам–Далат",
     "Одна из немногих зубчатых дорог, когда-либо построенных в мире",
     "Рядом с чамскими башнями Поклонгарай XIII века и солнечным Ниньтхуаном"],
    {"hours_vi": "Theo lịch tàu Thống Nhất hằng ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 20–30 phút; kết hợp thăm tháp Po Klong Garai gần đó.",
     "best_time_vi": "Mùa khô nhiều nắng; kết hợp mùa nho Ninh Thuận.",
     "tips_vi": "Ghé tháp Po Klong Garai và làng gốm Bàu Trúc; mang mũ, nước vì trời nắng gắt."},
    ["railway", "historic", "cham", "heritage"],
    [{"title": "Tháp Chàm station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Th%C3%A1p_Ch%C3%A0m_station"}],
))
ITEMS.append(rec(
    "vn-khanh-hoa", "Khánh Hòa", "Miền Trung", "ga-nha-trang",
    "Ga Nha Trang", "Nha Trang Railway Station", "Железнодорожный вокзал Нячанга",
    CATS, 12.2483, 109.1842,
    "17 Thái Nguyên, phường Phước Tân, thành phố Nha Trang, tỉnh Khánh Hòa",
    {"value": 4.4, "count": 2000, "source": "Google", "as_of": "2026-07"},
    "Du khách khen ga Nha Trang đẹp, cổ kính, ngay trung tâm, đi bộ ra biển gần; nhiều người thích kiến trúc Pháp và đường ray vòng đặc trưng, coi là ga biển đẹp.",
    "Ga Nha Trang là nhà ga cổ xây thời Pháp (1936), kiến trúc duyên dáng ngay trung tâm thành phố biển. Đây là cửa ngõ đường sắt tới các bãi biển và đảo nổi tiếng của Nha Trang.",
    "Nha Trang Station is an old French-era station (1936) with graceful architecture right in the centre of the seaside city. It is the rail gateway to Nha Trang's famous beaches and islands.",
    "Вокзал Нячанга — старый вокзал французской эпохи (1936) с изящной архитектурой прямо в центре приморского города. Это железнодорожные ворота к знаменитым пляжам и островам Нячанга.",
    "Nằm ngay trung tâm thành phố biển Nha Trang, Ga Nha Trang là một nhà ga cổ kính và duyên dáng, được người Pháp xây dựng và đưa vào hoạt động năm 1936. Nhà ga mang kiến trúc Pháp cổ với gam màu vàng đặc trưng, mái ngói và những đường nét hài hòa, cùng một đường ray vòng (ray bao) độc đáo phía trước từng dùng để quay đầu tàu, tạo nên nét riêng hiếm thấy. Là ga chính trên tuyến đường sắt Thống Nhất phục vụ 'thủ phủ du lịch biển' của Việt Nam, đây là điểm lên xuống tàu quen thuộc của hàng triệu lượt khách mỗi năm. Từ nhà ga, du khách chỉ mất vài phút là ra tới bãi biển Nha Trang dài cát trắng, hay dễ dàng tới các điểm nổi tiếng như Tháp Bà Ponagar, chợ Đầm, Hòn Chồng và các tour đảo, lặn biển ở vịnh Nha Trang. Với vẻ đẹp kiến trúc, vị trí trung tâm và không khí nhộn nhịp của một thành phố du lịch, Ga Nha Trang không chỉ là đầu mối giao thông mà còn là một điểm check-in được nhiều du khách yêu thích khi đến với phố biển.",
    "Right in the centre of the seaside city, Nha Trang Station is an antique, graceful station built by the French and opened in 1936. It wears old French architecture in its signature yellow, with a tiled roof and harmonious lines, and a rare loop track at the front once used to turn locomotives around, giving it a distinctive character. As the main station on the North–South railway serving Vietnam's beach-tourism capital, it is a familiar arrival point for millions of passengers each year. From the station it is only minutes to Nha Trang's long white-sand beach, and easy to reach famous sights such as the Ponagar Cham Towers, Dam Market, Hon Chong and the island and diving tours of Nha Trang Bay. With its architectural beauty, central location and the lively air of a tourist city, Nha Trang Station is not only a transport hub but also a favourite check-in spot for many visitors to the coastal town.",
    "Прямо в центре приморского города вокзал Нячанга — старинный, изящный вокзал, построенный французами и открытый в 1936 году. Он одет в старую французскую архитектуру своего фирменного жёлтого цвета, с черепичной крышей и гармоничными линиями, а спереди — редкий кольцевой путь, некогда использовавшийся для разворота локомотивов, что придаёт ему особый характер. Как главный вокзал на железной дороге Север–Юг, обслуживающий столицу пляжного туризма Вьетнама, это привычный пункт прибытия для миллионов пассажиров ежегодно. От вокзала всего несколько минут до длинного белопесчаного пляжа Нячанга, и легко добраться до знаменитых мест: чамских башен Понагар, рынка Дам, Хончонга и островных и дайвинг-туров по заливу Нячанг. С архитектурной красотой, центральным расположением и оживлённой атмосферой туристического города вокзал Нячанга — не только транспортный узел, но и любимое место для фото у многих гостей приморского города.",
    ["Ga cổ thời Pháp (1936), kiến trúc vàng duyên dáng, có đường ray vòng",
     "Ngay trung tâm, đi bộ vài phút ra biển Nha Trang cát trắng",
     "Cửa ngõ tới Tháp Bà Ponagar, Hòn Chồng và tour đảo vịnh Nha Trang"],
    ["An old French-era station (1936) in graceful yellow, with a loop track",
     "Central, a few minutes' walk to Nha Trang's white-sand beach",
     "Gateway to Ponagar Towers, Hon Chong and Nha Trang Bay island tours"],
    ["Старый вокзал французской эпохи (1936) в изящном жёлтом, с кольцевым путём",
     "В центре, несколько минут пешком до белопесчаного пляжа Нячанга",
     "Ворота к башням Понагар, Хончонгу и островным турам залива Нячанг"],
    {"hours_vi": "Theo lịch tàu Thống Nhất; sảnh ga mở ban ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 20–40 phút tham quan, chụp ảnh.",
     "best_time_vi": "Mùa khô (tháng 3–8); ban ngày để chụp ảnh mặt tiền ga.",
     "tips_vi": "Kết hợp dạo biển, chợ Đầm gần ga; đặt vé sớm mùa cao điểm hè."},
    ["railway", "historic", "photo", "architecture", "beach", "top"],
    [{"title": "Nha Trang railway station (Wikidata)", "url": "https://www.wikidata.org/wiki/Q3097205"}],
))
ITEMS.append(rec(
    "vn-lam-dong", "Lâm Đồng", "Miền Trung", "ga-phan-thiet",
    "Ga Phan Thiết", "Phan Thiet Railway Station", "Железнодорожная станция Фантьет",
    ["other"], 10.9418, 108.0824,
    "Xã Phong Nẫm, thành phố Phan Thiết (khu vực Bình Thuận cũ), tỉnh Lâm Đồng",
    {"value": 4.0, "count": 500, "source": "Google", "as_of": "2026-07"},
    "Du khách đi tàu ra Phan Thiết – Mũi Né nghỉ biển; khen ga mới khang trang, thuận tiện; nhiều người đi tàu cuối tuần từ TP.HCM ra biển.",
    "Ga Phan Thiết là ga đầu mối phục vụ thành phố biển Phan Thiết – Mũi Né. Được xây mới khang trang, ga là cửa ngõ đường sắt tới thủ phủ resort và đồi cát nổi tiếng của miền Nam Trung Bộ.",
    "Phan Thiet Station serves the seaside city of Phan Thiet–Mui Ne. Newly and handsomely built, it is the rail gateway to the resort capital and famous sand dunes of the south-central coast.",
    "Станция Фантьет обслуживает приморский город Фантьет–Муйне. Заново и добротно построенная, она — железнодорожные ворота к столице курортов и знаменитым песчаным дюнам южно-центрального побережья.",
    "Nằm ở xã Phong Nẫm, cửa ngõ thành phố Phan Thiết (thuộc Bình Thuận cũ, nay là tỉnh Lâm Đồng sau sáp nhập), Ga Phan Thiết là nhà ga đầu mối phục vụ một trong những trung tâm du lịch biển sôi động nhất phía nam. Nhà ga hiện tại được xây mới khang trang, thay cho ga cũ trong nội thị, nhằm đáp ứng nhu cầu đi lại ngày càng lớn của du khách tới Phan Thiết – Mũi Né. Đây là điểm đến quen thuộc của những chuyến tàu du lịch cuối tuần, đặc biệt là tuyến Sài Gòn – Phan Thiết, đưa du khách từ Thành phố Hồ Chí Minh ra biển chỉ trong vài giờ. Từ nhà ga, du khách dễ dàng tới các bãi biển đẹp, khu nghỉ dưỡng ven biển, và nhất là Mũi Né với những đồi cát bay vàng – trắng trải dài, suối Tiên, làng chài và hải sản tươi ngon. Vùng đất Bình Thuận nắng gió còn nổi tiếng với tháp Chăm Po Sah Inư, Trường Dục Thanh và Bàu Trắng. Là cửa ngõ đường sắt tới 'thủ đô resort', Ga Phan Thiết đóng vai trò quan trọng trong việc kết nối du khách với vùng biển và đồi cát đặc trưng của Nam Trung Bộ.",
    "In Phong Nam commune at the gateway to Phan Thiet city (in former Binh Thuan, now Lam Dong province after the merger), Phan Thiet Station is the hub serving one of the liveliest beach-tourism centres in the south. The current station has been newly and handsomely built, replacing the old inner-city station to meet the growing flow of visitors to Phan Thiet–Mui Ne. It is a familiar destination for weekend tourist trains, especially the Saigon–Phan Thiet line, bringing travellers from Ho Chi Minh City to the sea in just a few hours. From the station, visitors easily reach beautiful beaches, seaside resorts and above all Mui Ne, with its sweeping yellow and white flying sand dunes, the Fairy Stream, fishing villages and fresh seafood. The sun-and-wind land of Binh Thuan is also famous for the Po Sah Inu Cham towers, the Duc Thanh School and Bau Trang. As the rail gateway to this resort capital, Phan Thiet Station plays an important role in connecting travellers with the distinctive coast and dunes of the south-central region.",
    "В общине Фонгнам у въезда в город Фантьет (в бывшей провинции Биньтхуан, ныне провинция Ламдонг после слияния) станция Фантьет — узел, обслуживающий один из самых оживлённых центров пляжного туризма юга. Нынешняя станция заново и добротно построена, заменив старую в черте города, чтобы удовлетворить растущий поток гостей в Фантьет–Муйне. Это привычная цель для туристических поездов выходного дня, особенно линии Сайгон–Фантьет, доставляющей путешественников из Хошимина к морю всего за несколько часов. От станции гости легко добираются до красивых пляжей, приморских курортов и прежде всего до Муйне с его раскинувшимися жёлтыми и белыми летящими дюнами, Ручьём фей, рыбацкими деревнями и свежими морепродуктами. Солнечно-ветреная земля Биньтхуан также известна чамскими башнями Пошаину, школой Зюкthань и Баучангом. Как железнодорожные ворота к столице курортов станция Фантьет важна для связи путешественников с характерным побережьем и дюнами южно-центрального региона.",
    ["Ga mới khang trang, cửa ngõ tới Phan Thiết – Mũi Né",
     "Tuyến tàu du lịch Sài Gòn – Phan Thiết ra biển chỉ vài giờ",
     "Gần đồi cát bay Mũi Né, suối Tiên, tháp Chăm Po Sah Inư"],
    ["A new, handsome station, gateway to Phan Thiet–Mui Ne",
     "The Saigon–Phan Thiet tourist line reaches the sea in a few hours",
     "Near the Mui Ne flying dunes, Fairy Stream and Po Sah Inu towers"],
    ["Новая добротная станция, ворота к Фантьет–Муйне",
     "Туристическая линия Сайгон–Фантьет достигает моря за несколько часов",
     "Рядом с летящими дюнами Муйне, Ручьём фей и башнями Пошаину"],
    {"hours_vi": "Theo lịch tàu; đông vào cuối tuần và mùa hè.",
     "ticket_vi": "Vào ga không mất phí; vé tàu Sài Gòn – Phan Thiết tùy loại toa.",
     "duration_vi": "Khoảng 20–30 phút; trung chuyển ra Mũi Né.",
     "best_time_vi": "Mùa khô (tháng 11–4) nắng đẹp; cuối tuần đi biển.",
     "tips_vi": "Chuẩn bị xe ra Mũi Né (~20 km); đặt vé tàu cuối tuần sớm."},
    ["railway", "gateway", "beach", "family"],
    [{"title": "Phan Thiết station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Phan_Thi%E1%BA%BFt_station"}],
))
ITEMS.append(rec(
    "vn-dong-nai", "Đồng Nai", "Miền Nam", "ga-bien-hoa",
    "Ga Biên Hòa", "Bien Hoa Railway Station", "Железнодорожная станция Бьенхоа",
    CATS, 10.9508, 106.8264,
    "Phường Quang Vinh (khu vực trung tâm), thành phố Biên Hòa, tỉnh Đồng Nai",
    {"value": 4.0, "count": 700, "source": "Google", "as_of": "2026-07"},
    "Hành khách khu vực Đông Nam Bộ thường dùng Ga Biên Hòa để đi tàu Bắc – Nam, tránh vào trung tâm TP.HCM; khen ga tiện, gần quốc lộ và các khu công nghiệp.",
    "Ga Biên Hòa là ga lớn ở cửa ngõ vùng Đông Nam Bộ trên tuyến đường sắt Thống Nhất. Đây là đầu mối quan trọng phục vụ Đồng Nai và khu vực lân cận TP.HCM.",
    "Bien Hoa Station is a major station at the gateway of the south-east region on the North–South railway. It is an important hub serving Dong Nai and the area around Ho Chi Minh City.",
    "Станция Бьенхоа — крупная станция у ворот юго-восточного региона на железной дороге Север–Юг. Это важный узел, обслуживающий Донгнай и окрестности Хошимина.",
    "Nằm ngay trung tâm thành phố Biên Hòa, Ga Biên Hòa là một trong những nhà ga lớn và quan trọng ở cửa ngõ vùng Đông Nam Bộ trên tuyến đường sắt Thống Nhất Bắc – Nam. Là đô thị công nghiệp đông dân nằm sát Thành phố Hồ Chí Minh, Biên Hòa có lượng hành khách đi tàu rất lớn; nhiều người dân và du khách ở khu vực phía đông chọn lên xuống tàu tại đây để thuận tiện, tránh phải vào tận trung tâm TP.HCM. Nhà ga là điểm kết nối giao thông đường sắt với hệ thống quốc lộ, bến xe đi các tỉnh miền Đông, Tây Nguyên và về miền Tây. Từ Biên Hòa, du khách có thể dễ dàng tới các điểm tham quan của Đồng Nai như Văn miếu Trấn Biên, chùa Ông, cù lao Phố, khu du lịch Bửu Long, thác Giang Điền hay Vườn quốc gia Cát Tiên. Với vai trò đầu mối bản lề giữa TP.HCM và các tỉnh phía bắc, Ga Biên Hòa góp phần quan trọng trong mạng lưới vận tải hành khách và hàng hóa của cả khu vực kinh tế trọng điểm phía Nam.",
    "Right in the centre of Bien Hoa city, Bien Hoa Station is one of the largest and most important stations at the gateway of the south-east region on the North–South Reunification railway. As a populous industrial city next to Ho Chi Minh City, Bien Hoa has a very large flow of rail passengers; many residents and travellers in the eastern area choose to board here for convenience, avoiding a trip into central Ho Chi Minh City. The station links the railway with the highway network and coach stations serving the eastern provinces, the Central Highlands and the western delta. From Bien Hoa, visitors easily reach Dong Nai's sights such as the Tran Bien Temple of Literature, Ong Pagoda, Cu Lao Pho, Buu Long tourist area, Giang Dien Waterfall and Cat Tien National Park. As a pivotal hub between Ho Chi Minh City and the northern provinces, Bien Hoa Station plays an important part in the passenger and freight network of the southern key economic region.",
    "Прямо в центре города Бьенхоа станция Бьенхоа — одна из крупнейших и важнейших станций у ворот юго-восточного региона на объединяющей железной дороге Север–Юг. Как многонаселённый промышленный город рядом с Хошимином, Бьенхоа имеет очень большой поток пассажиров; многие жители и путешественники восточной части выбирают посадку здесь ради удобства, избегая поездки в центр Хошимина. Станция связывает железную дорогу с сетью шоссе и автостанциями, обслуживающими восточные провинции, Центральное нагорье и западную дельту. Из Бьенхоа гости легко добираются до достопримечательностей Донгная: храма литературы Чанбьен, пагоды Онг, Кулаофо, туристической зоны Быулонг, водопада Зянгдьен и национального парка Каттьен. Как ключевой узел между Хошимином и северными провинциями станция Бьенхоа важна в пассажирской и грузовой сети южного ключевого экономического региона.",
    ["Ga lớn ở cửa ngõ Đông Nam Bộ trên tuyến Thống Nhất",
     "Thuận tiện lên xuống tàu, tránh vào trung tâm TP.HCM",
     "Gần Văn miếu Trấn Biên, Bửu Long, thác Giang Điền, cù lao Phố"],
    ["A major station at the south-east gateway on the North–South line",
     "Convenient boarding without going into central Ho Chi Minh City",
     "Near Tran Bien Temple of Literature, Buu Long, Giang Dien Waterfall"],
    ["Крупная станция у юго-восточных ворот на линии Север–Юг",
     "Удобная посадка без поездки в центр Хошимина",
     "Рядом с храмом Чанбьен, Быулонгом, водопадом Зянгдьен"],
    {"hours_vi": "Theo lịch tàu Thống Nhất hằng ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 15–30 phút; chủ yếu trung chuyển.",
     "best_time_vi": "Quanh năm; mùa khô (tháng 12–4) dễ đi lại.",
     "tips_vi": "Khách vùng phía đông có thể lên/xuống ở đây thay vì Ga Sài Gòn; đặt vé sớm dịp lễ Tết."},
    ["railway", "gateway", "city"],
    [{"title": "Biên Hòa station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Bi%C3%AAn_H%C3%B2a_station"}],
))
ITEMS.append(rec(
    "vn-ho-chi-minh", "TP. Hồ Chí Minh", "Miền Nam", "ga-sai-gon",
    "Ga Sài Gòn", "Saigon Railway Station", "Железнодорожный вокзал Сайгона",
    CATS, 10.7823, 106.6772,
    "1 Nguyễn Thông, phường 9, quận 3, Thành phố Hồ Chí Minh",
    {"value": 4.2, "count": 5000, "source": "Google", "as_of": "2026-07"},
    "Du khách coi Ga Sài Gòn là điểm cuối biểu tượng của tàu Thống Nhất; khen ga lớn, ngay trung tâm, dễ đi; nhiều người bắt đầu/ kết thúc hành trình xuyên Việt tại đây.",
    "Ga Sài Gòn (Ga Hòa Hưng) là ga cuối phía nam của tuyến đường sắt Thống Nhất, nằm ở quận 3. Đây là ga lớn nhất và là điểm cực nam của mạng lưới đường sắt Việt Nam.",
    "Saigon Station (Hoa Hung) is the southern terminus of the North–South railway, in District 3. It is the largest station and the southernmost point of Vietnam's rail network.",
    "Вокзал Сайгона (Хоахынг) — южная конечная станция железной дороги Север–Юг в 3-м районе. Это крупнейший вокзал и самая южная точка железнодорожной сети Вьетнама.",
    "Toạ lạc trên đường Nguyễn Thông, quận 3, Ga Sài Gòn (còn gọi là Ga Hòa Hưng) là ga cuối phía nam của tuyến đường sắt Thống Nhất Bắc – Nam và là nhà ga lớn nhất, sầm uất nhất khu vực phía Nam. Đây chính là điểm cực nam của mạng lưới đường sắt quốc gia: những đoàn tàu Thống Nhất khởi hành từ Hà Nội, sau hành trình hơn 1.700 km xuyên suốt chiều dài đất nước, sẽ kết thúc tại đây, khiến Ga Sài Gòn trở thành một điểm đến mang tính biểu tượng của hành trình xuyên Việt. Nhà ga hiện tại được đưa vào sử dụng từ năm 1983, có quy mô lớn với nhiều đường ray, sảnh chờ rộng rãi, phục vụ hàng triệu lượt khách mỗi năm đi khắp các tỉnh miền Trung, miền Bắc và các tuyến địa phương. Nằm ngay trung tâm thành phố năng động nhất Việt Nam, ga thuận tiện kết nối với hệ thống xe buýt, taxi và các điểm tham quan như chợ Bến Thành, Nhà thờ Đức Bà, Dinh Độc Lập. Với vai trò đầu mối và ý nghĩa biểu tượng, Ga Sài Gòn là một phần không thể thiếu trong nhịp sống và ký ức đi lại của người dân Thành phố Hồ Chí Minh.",
    "On Nguyen Thong Street in District 3, Saigon Station (also called Hoa Hung Station) is the southern terminus of the North–South Reunification railway and the largest, busiest station in the south. It is the southernmost point of the national rail network: the Reunification trains leaving Hanoi, after a journey of more than 1,700 km along the length of the country, end here, making Saigon Station a symbolic destination of the trans-Vietnam journey. The present station, in use since 1983, is large, with many tracks and spacious halls, serving millions of passengers a year to the central and northern provinces and on local lines. In the heart of Vietnam's most dynamic city, it connects conveniently with buses, taxis and sights such as Ben Thanh Market, Notre-Dame Cathedral and the Independence Palace. As both a hub and a symbol, Saigon Station is an inseparable part of the daily life and travel memories of the people of Ho Chi Minh City.",
    "На улице Нгуентхонг в 3-м районе вокзал Сайгона (также вокзал Хоахынг) — южная конечная станция объединяющей железной дороги Север–Юг и крупнейший, самый оживлённый вокзал юга. Это самая южная точка национальной железнодорожной сети: поезда воссоединения, отходящие из Ханоя, после пути более чем в 1700 км через всю страну заканчивают маршрут здесь, что делает вокзал Сайгона символической целью транс-вьетнамского путешествия. Нынешний вокзал, действующий с 1983 года, велик, со многими путями и просторными залами, обслуживает миллионы пассажиров в год в центральные и северные провинции и на местных линиях. В сердце самого динамичного города Вьетнама он удобно связан с автобусами, такси и достопримечательностями: рынком Бентхань, собором Нотр-Дам и Дворцом Независимости. Как узел и символ вокзал Сайгона — неотъемлемая часть повседневной жизни и дорожных воспоминаний жителей Хошимина.",
    ["Ga cuối phía nam, điểm cực nam của mạng đường sắt Việt Nam",
     "Kết thúc hành trình tàu Thống Nhất hơn 1.700 km từ Hà Nội",
     "Ngay trung tâm quận 3, gần chợ Bến Thành, Nhà thờ Đức Bà"],
    ["The southern terminus, the southernmost point of Vietnam's rail network",
     "End of the 1,700 km Reunification journey from Hanoi",
     "Central in District 3, near Ben Thanh Market and Notre-Dame Cathedral"],
    ["Южная конечная, самая южная точка ж/д сети Вьетнама",
     "Конец пути «воссоединения» длиной более 1700 км из Ханоя",
     "В центре 3-го района, у рынка Бентхань и собора Нотр-Дам"],
    {"hours_vi": "Theo lịch tàu Thống Nhất và các tuyến; sảnh ga mở gần cả ngày.",
     "ticket_vi": "Vào ga không mất phí; vé tàu tùy tuyến và loại toa.",
     "duration_vi": "Khoảng 20–40 phút; điểm đầu/cuối hành trình.",
     "best_time_vi": "Quanh năm; đặt vé sớm dịp lễ, Tết.",
     "tips_vi": "Tới sớm trước giờ tàu; giữ tư trang nơi đông người; dễ bắt taxi, xe công nghệ."},
    ["railway", "landmark", "city", "family", "top"],
    [{"title": "Saigon railway station (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Saigon_railway_station"}],
))
# __STATIONS_END__

# ---- Chèn an toàn theo từng file ----
from collections import defaultdict
bygroup = defaultdict(list)
for f, r in ITEMS:
    bygroup[f].append(r)

total_added = 0
for f, recs in bygroup.items():
    path = f"data/regions/{f}.json"
    d = json.load(open(path, encoding="utf-8")) if os.path.exists(path) else []
    have = {p["slug"] for p in d}
    add = [r for r in recs if r["slug"] not in have]
    d += add
    json.dump(d, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    total_added += len(add)
    print(f"{f}: +{len(add)} ({', '.join(r['slug'] for r in add)}) -> tong {len(d)}")
print("TONG DA THEM:", total_added)
