# -*- coding: utf-8 -*-
"""Builder: doc_eliseyev-emporium.json — noi dung nguyen goc tieng Viet."""
import json

doc = {
 "slug": "eliseyev-emporium",
 "name_vi": "Cửa hàng Eliseyev (Yeliseyevsky magazin)",
 "name_ru": "Елисеевский магазин",
 "name_en": "Eliseyev Emporium",
 "subtitle": "Cung điện của cái ăn cái uống trên đại lộ Nevsky: một kiệt tác Tân nghệ thuật với ô kính vòm khổng lồ và tượng đồng, vừa là cửa hàng thực phẩm cao cấp, vừa là nhà hát, vừa là kho giai thoại trải dài suốt hơn một thế kỷ của Saint Petersburg.",
 "sections": [
  {"heading": "Giới thiệu chung", "paras": [
   "Cửa hàng Eliseyev, người Nga quen gọi là Yeliseyevsky magazin, là một trong những địa chỉ lộng lẫy và dễ nhận ra nhất trên đại lộ Nevsky – trục phố xương sống của thành phố Saint Petersburg. Toà nhà toạ lạc tại số 56 đại lộ Nevsky, ngay góc giao với phố Malaya Sadovaya, được dựng lên trong hai năm 1902 và 1903 rồi khai trương vào năm 1903 cho thương hội của gia tộc Eliseyev. Ngay từ cái nhìn đầu tiên, du khách sẽ hiểu vì sao đây không đơn thuần là một cửa hàng thực phẩm: gần như toàn bộ mặt tiền bị nuốt trọn bởi một ô kính vòm khổng lồ, viền quanh là đá granite sẫm màu, điểm xuyết những pho tượng đồng đồ sộ. Đó là một khối kiến trúc vừa xa hoa vừa táo bạo, nơi mà việc mua bán thực phẩm được nâng lên thành một màn trình diễn nghệ thuật thực thụ.",
   "Điều khiến cửa hàng Eliseyev trở nên độc nhất vô nhị nằm ở chỗ nó gói ghém trong mình nhiều lớp căn tính khác nhau. Ở lớp vỏ ngoài, đây là một kiệt tác của phong cách Tân nghệ thuật, mà người Nga quen gọi là Style Moderne, từng gây tranh cãi dữ dội khi mới ra đời rồi dần dà được cả thành phố say mê. Bước vào bên trong, du khách như lạc vào một cung điện của cái ăn cái uống, nơi những mảng trần thạch cao mạ vàng, đèn chùm pha lê và các chi tiết trang trí kiểu cổ điển cùng nhau tôn vinh những món đặc sản nhập khẩu quý hiếm. Và ở tầng trên cùng, ngôi nhà còn cất giấu một nhà hát – một sự kết hợp hiếm thấy giữa chốn mua sắm sang trọng và chốn thưởng thức nghệ thuật.",
   "Với các đoàn khách Việt Nam, cửa hàng Eliseyev là một điểm dừng lý tưởng vì nhiều lẽ rất thiết thực. Trước hết, việc vào cửa hoàn toàn miễn phí, khách chỉ phải trả tiền nếu quyết định mua hàng, nên đây là nơi có thể ghé thăm bất cứ lúc nào mà không cần đặt vé hay xếp hàng. Thứ đến, mọi giác quan đều được đánh thức khi bước qua ngưỡng cửa: mùi cà phê rang và sô-cô-la thoang thoảng, ánh vàng lấp lánh của đồ trang trí, cùng những quầy kính dài trưng bày phô mai, trái cây nhiệt đới, rượu vang và bánh kẹo đủ loại. Sau cùng, mỗi ngóc ngách của toà nhà lại gắn với một câu chuyện riêng, từ trái dâu rừng giữa mùa đông năm 1812 cho tới chú mèo đồng bé nhỏ ngồi trên gờ tường phía ngoài phố.",
   "Trong tập tài liệu này, chúng ta sẽ lần lượt đi qua vị trí và cách di chuyển, lịch sử hình thành của cả một triều đại thương gia, những đặc điểm kiến trúc làm nên danh tiếng, các điểm nhấn không thể bỏ lỡ, ý nghĩa lịch sử và văn hoá, trải nghiệm dành cho du khách, những mẹo tham quan thực tế, các điểm đến lân cận, và sau cùng là kho giai thoại thú vị. Sau hơn một thế kỷ tồn tại, trải qua cách mạng, chiến tranh, những năm tháng bao cấp thiếu thốn rồi một cuộc trùng tu lớn, cửa hàng Eliseyev ngày nay vẫn mở cửa, vẫn buôn bán tấp nập, và vẫn khiến người qua đường phải dừng chân ngỡ ngàng. Chính điều đó đã làm nên sức sống bền bỉ hiếm có của một trong những địa chỉ biểu tượng bậc nhất Saint Petersburg."
  ]},
  {"heading": "Vị trí & cách di chuyển", "paras": [
   "Cửa hàng Eliseyev nằm ở số 56 đại lộ Nevsky, ngay tại góc giao với phố đi bộ Malaya Sadovaya, thuộc khu vực trung tâm lịch sử của Saint Petersburg. Toạ độ định vị của công trình vào khoảng 59.934167 độ vĩ bắc và 30.3375 độ kinh đông, tức là gần như ở chính giữa đoạn đẹp nhất và sầm uất nhất của đại lộ Nevsky. Đây là một trong những vị trí đắc địa nhất mà một cửa hàng có thể mơ ước: mặt tiền lớn quay ra trục phố chính, còn một mặt bên thì tựa vào con phố đi bộ nhỏ nhắn và thơ mộng. Chính nhờ toạ lạc ở ngã tư trung tâm này mà toà nhà dễ dàng lọt vào tầm mắt của bất cứ ai dạo bộ trên đại lộ Nevsky.",
   "Về phương tiện công cộng, cách thuận tiện nhất là dùng tàu điện ngầm, hệ thống metro nổi tiếng của thành phố. Ga gần nhất là Gostiny Dvor, chỉ cách cửa hàng khoảng một trăm đến hai trăm mét, tương ứng vài phút đi bộ thong thả. Một lựa chọn khác là ga Mayakovskaya, cũng nằm trên đại lộ Nevsky và cách đó một quãng đi bộ ngắn dọc theo trục phố chính. Từ cả hai ga này, du khách chỉ việc bước lên mặt đất và đi men theo đại lộ Nevsky là sẽ thấy ngay khối kiến trúc bề thế với ô kính vòm đặc trưng, gần như không thể nhầm lẫn với bất kỳ toà nhà nào khác.",
   "Cách tiếp cận đẹp nhất, và cũng được nhiều hướng dẫn viên ưa thích, là đi bộ dọc đại lộ Nevsky để toà nhà dần hiện ra trước mắt. Khi tiến lại gần góc phố Malaya Sadovaya, du khách sẽ thấy mặt tiền chính mở ra như một tấm kính hàng khổng lồ, còn phần góc nhà thì vươn cao với một chiếc tháp nhỏ trên đỉnh. Nếu đi từ hướng quảng trường Cung điện và trụ sở Bộ Tổng tham mưu tới, cửa hàng nằm bên tay trái sau khi qua khỏi khu thương xá Gostiny Dvor; nếu đi từ phía ga Moskovsky và quảng trường Vosstaniya lại, nó nằm bên tay phải. Dù xuất phát từ hướng nào, quãng đường bộ trên đại lộ Nevsky cũng luôn nhộn nhịp và giàu cảnh quan, nên bản thân việc đi bộ đã là một phần thú vị.",
   "Với các đoàn khách đi xe riêng, hướng dẫn viên và tài xế cần lưu ý rằng đại lộ Nevsky là tuyến phố cực kỳ đông đúc, xe cộ nhiều và việc dừng đỗ bị hạn chế nghiêm ngặt. Thông thường xe lớn sẽ thả khách ở một điểm thuận tiện gần đó rồi hẹn đón lại, bởi khu vực này không có bãi đỗ dành riêng cho xe du lịch cỡ lớn. Một điểm cộng lớn là phố Malaya Sadovaya ngay cạnh cửa hàng vốn là phố đi bộ, nên cả đoàn có thể tập trung, chụp ảnh và nghe thuyết minh một cách thoải mái mà không lo xe cộ. Về giờ giấc, cửa hàng thường mở cửa hằng ngày trong khung giờ khoảng mười giờ sáng đến mười một giờ đêm, và như đã nói, việc vào cửa là hoàn toàn miễn phí, khách chỉ trả tiền khi mua hàng hoặc dùng bữa tại các không gian ẩm thực bên trong."
  ]},
  {"heading": "Lịch sử hình thành và phát triển", "paras": [
   "Muốn hiểu cửa hàng, trước hết cần hiểu triều đại đã sinh ra nó, và câu chuyện ấy bắt đầu từ một giai thoại đẹp như cổ tích. Tương truyền, thuỷ tổ của dòng họ là ông Pyotr Eliseyev, vốn là một người làm vườn nông nô của Bá tước Sheremetev, một trong những gia tộc quý tộc giàu có nhất nước Nga. Vào đêm Giáng sinh năm 1812, giữa mùa đông giá buốt, ông đã dâng lên bàn tiệc của bá tước những trái dâu rừng tươi rói, thứ quả tưởng như không thể có được vào thời điểm ấy trong năm. Cảm kích trước tài khéo léo đó, vị bá tước đã trả tự do cho ông cùng một khoản tiền nhỏ, và với vốn liếng khiêm tốn ban đầu ấy, Pyotr Eliseyev đã trở thành một thương nhân thành đạt ở Saint Petersburg, đặt nền móng cho cả một đế chế buôn bán về sau.",
   "Trải qua vài thế hệ, gia tộc Eliseyev vươn lên thành một trong những nhà buôn giàu có bậc nhất nước Nga, mà nền tảng của khối tài sản khổng lồ ấy chính là nghề buôn rượu vang. Đến cuối thế kỷ 19, người thừa kế Grigory Grigorievich Eliseyev đã mua lại khu đất ở góc phố này vào năm 1898 và mời kiến trúc sư Gavriil Vasilyevich Baranovsky thiết kế một toà nhà thương mại xứng tầm. Công trình mới được xây dựng trong hai năm 1902 và 1903, khai trương ngay trong năm 1903 dưới danh nghĩa của thương hội «Anh em Eliseyev», chuyên kinh doanh các loại hàng hoá gọi là «hàng thuộc địa» – tức những mặt hàng thực phẩm ngoại nhập quý hiếm từ khắp nơi trên thế giới. Cũng cần lưu ý một chi tiết nhỏ mà thú vị: trang giới thiệu tiếng Anh của cửa hàng từng dịch nhầm loại quả trong giai thoại thành «quả mâm xôi», trong khi bản tiếng Nga ghi rõ đó là dâu rừng.",
   "Bước ngoặt lớn đầu tiên đến sau cuộc Cách mạng năm 1917. Cửa hàng bị quốc hữu hoá và được đổi tên thành «Gastronom số 1», nhưng người dân Leningrad, tên gọi của thành phố thời Liên Xô, vẫn một mực gọi nó theo lối cũ là Yeliseyevsky. Trong suốt những năm tháng khan hiếm hàng hoá của thời bao cấp, đây là một trong số rất ít nơi mà người ta còn có thể tìm mua được những món đặc sản, khiến cái tên Yeliseyevsky luôn gắn với hình ảnh của sự dồi dào và sang trọng trong tâm trí người dân. Chính sự bền bỉ của tên gọi cũ, bất chấp mọi thay đổi về chính trị, đã cho thấy vị trí đặc biệt của cửa hàng trong đời sống thường nhật của cả một thành phố.",
   "Những năm chiến tranh để lại dấu ấn bi tráng lên toà nhà. Ngay từ ngày 24 tháng 6 năm 1941, những tấm áp phích tuyên truyền thuộc loạt «Cửa sổ TASS» đã bắt đầu xuất hiện ở đây, biến mặt tiền cửa hàng thành một điểm cổ động tinh thần giữa lòng thành phố. Trong mùa đông khủng khiếp của cuộc phong toả Leningrad, khoảng những năm 1942 và 1943, khi cả thành phố chìm trong đói rét và bom đạn, các đoàn kịch vẫn kiên trì biểu diễn trên tầng hai của toà nhà, như một cách khẳng định rằng nghệ thuật và sự sống không thể bị dập tắt. Những chi tiết ấy khiến cửa hàng Eliseyev không chỉ là một địa chỉ mua sắm, mà còn là một chứng nhân lặng lẽ của những trang sử đau thương và kiêu hãnh nhất của thành phố.",
   "Thời hậu Xô-viết lại mở ra một chương đầy sóng gió. Cửa hàng rơi vào cảnh tranh chấp, nợ nần, thậm chí từng suýt bị biến thành một cửa hàng nước hoa, nhưng chính quyền thành phố đã ngăn lại để giữ gìn công năng và bản sắc vốn có. Đến tháng 1 năm 2007, toà nhà đóng cửa để bước vào một cuộc trùng tu kéo dài dưới sự giám sát của cơ quan bảo vệ di sản mang tên KGIOP, và năm 2010 nó được xếp hạng di sản được bảo vệ, nằm trong quần thể «Trung tâm lịch sử Saint Petersburg» đã được UNESCO công nhận. Cửa hàng chính thức mở cửa trở lại vào ngày mùng 8 tháng 3 năm 2012 với diện mạo mới mang tên «Kupetz Eliseevs Food Hall», và ngay trong ngày khai trương, dòng người xếp hàng đã kéo dài ra tận đại lộ Nevsky. Cũng cần nhắc thêm rằng cửa hàng chị em ở Moscow, nằm trên phố Tverskaya và do chính Grigory Eliseyev mở năm 1901, đã phải đóng cửa vào tháng 4 năm 2021 sau khoảng một trăm hai mươi năm hoạt động, trong khi cửa hàng ở Saint Petersburg thì vẫn còn đó."
  ]},
  {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
   "Linh hồn kiến trúc của công trình là kiến trúc sư Gavriil Vasilyevich Baranovsky, người đã tạo nên một trong những tác phẩm Tân nghệ thuật ấn tượng nhất, và cũng gây tranh cãi nhiều nhất, của Saint Petersburg. Vào thời điểm ra đời, không ít nhà phê bình đã chê bai công trình là phô trương, thậm chí thô kệch, nhưng chính sự táo bạo ấy lại làm nên nét độc đáo trường tồn của nó. Điểm mấu chốt về mặt kỹ thuật nằm ở chỗ toà nhà sử dụng một bộ khung thép, cho phép giải phóng các mặt tường khỏi vai trò chịu lực và nhờ đó có thể lắp những mảng kính lớn chưa từng thấy. Về phương diện này, cửa hàng Eliseyev có thể sánh với toà nhà Singer, tức Ngôi nhà Sách nổi tiếng, vốn hoàn thành trước đó chỉ một năm trên cùng đại lộ Nevsky.",
   "Đặc điểm chữ ký, cũng là thứ khiến ai cũng phải sững lại khi đi ngang qua, chính là ô kính vòm khổng lồ trên mặt tiền chính. Hơn một nửa diện tích mặt trước của toà nhà được chiếm trọn bởi một vòm kính duy nhất, ghép từ những tấm kính lớn, khiến cả mặt tiền trông như một ô cửa kính trưng bày hàng hoá có kích thước phi thường. Sắc đá granite sẫm màu bao quanh càng làm nổi bật vẻ trong suốt và lấp lánh của mảng kính, tạo nên sự tương phản mạnh mẽ giữa cái nặng nề của đá và cái nhẹ bẫng của thuỷ tinh. Vào ban đêm, khi ánh sáng từ bên trong hắt ra qua ô kính này, cả toà nhà như một chiếc đèn lồng khổng lồ chiếu sáng cả một góc đại lộ Nevsky.",
   "Trên mặt tiền, du khách sẽ thấy bốn pho tượng đồng lớn đã lên nước thời gian, tác phẩm của nhà điêu khắc người Estonia Amandus Heinrich Adamson thực hiện năm 1903. Bốn pho tượng này là những hình tượng ngụ ngôn, lần lượt tượng trưng cho Công nghiệp, Thương mại, Nghệ thuật và Khoa học – bốn trụ cột mà gia tộc Eliseyev muốn tôn vinh và cũng là bốn giá trị làm nên tinh thần của thời đại. Phía trên góc nhà, một chiếc tháp nhỏ cùng phần mái áp mái vươn lên như chiếc vương miện đội trên đầu toà nhà, giúp khối kiến trúc trở nên bề thế và dễ nhận ra từ xa. Sự kết hợp giữa kính, đá, đồng và những đường nét uốn lượn đặc trưng của Tân nghệ thuật đã biến mặt tiền thành một tác phẩm điêu khắc đô thị đúng nghĩa.",
   "Bên trong, không gian nguyên bản của cửa hàng được thiết kế như một cung điện thu nhỏ dành cho việc mua sắm. Đại sảnh bán hàng rộng lớn được phủ những mảng trần thạch cao mạ vàng, treo đèn chùm pha lê lộng lẫy, điểm xuyết các chi tiết trang trí kiểu cổ điển cùng những hoạ tiết hoa lá và cây cọ, tất cả nhằm tạo cảm giác choáng ngợp và sang trọng. Đáng chú ý là toà nhà không chỉ bán thực phẩm: nó còn từng có khu bán quần áo may sẵn, một ngân hàng và cả các khoá học kinh doanh mở cho công chúng, biến nơi đây thành một tổ hợp thương mại và văn hoá đa năng. Trên tầng cao nhất là không gian nhà hát, mảnh ghép cuối cùng khiến toà nhà trở thành một thế giới thu nhỏ, nơi người ta vừa có thể mua sắm, học hành, giao dịch lẫn thưởng thức nghệ thuật dưới cùng một mái nhà."
  ]},
  {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
   "Điểm nhấn đầu tiên và cũng nổi bật nhất chính là ô kính vòm khổng lồ trên mặt tiền, thứ đã trở thành biểu tượng nhận diện của cửa hàng. Hướng dẫn viên nên dành thời gian để khách đứng từ phía đối diện, trên vỉa hè đại lộ Nevsky, mà chiêm ngưỡng toàn cảnh mặt tiền: cách vòm kính chiếm lĩnh không gian, cách viền đá granite ôm lấy mảng kính, và cách toàn bộ toà nhà toát lên vẻ vừa cổ điển vừa hiện đại. Đây cũng là góc chụp ảnh đẹp nhất để lưu lại hình ảnh trọn vẹn của công trình. Vào buổi tối, khi đèn bên trong bật sáng, khung cảnh lại càng thêm phần huyền ảo và đáng nhớ.",
   "Điểm nhấn thứ hai là bốn pho tượng đồng của nhà điêu khắc Amandus Adamson. Hãy hướng dẫn khách nhận diện từng hình tượng ngụ ngôn tượng trưng cho Công nghiệp, Thương mại, Nghệ thuật và Khoa học, đồng thời chỉ cho họ thấy lớp nước đồng xanh mà thời gian đã phủ lên các bức tượng, làm chúng hoà quyện với sắc đá sẫm của mặt tiền. Những pho tượng này không chỉ là chi tiết trang trí, mà còn là một tuyên ngôn của gia tộc Eliseyev về niềm tin vào tiến bộ và văn minh. Việc dừng lại lý giải ý nghĩa của bốn hình tượng sẽ giúp khách hiểu sâu hơn về tinh thần của cả công trình.",
   "Một điểm nhấn hiện đại nhưng đã trở nên vô cùng được yêu thích là những ô cửa sổ ở phần góc nhà, nơi kể từ năm 2012 trưng bày các nhân vật chuyển động của vở «Kẹp Hạt Dẻ». Những mô hình sống động này do nghệ sĩ Mikhail Shemyakin sáng tạo và dành tặng cho thành phố, biến ô cửa góc thành một sân khấu tí hon luôn khiến người lớn lẫn trẻ nhỏ thích thú. Đây là một điểm chụp ảnh gần như bắt buộc, đặc biệt vào dịp Năm mới, khi cả đại lộ Nevsky ngập trong không khí lễ hội và ánh đèn trang trí. Hướng dẫn viên nên nhắc khách để ý chuyển động tinh tế của các nhân vật thay vì chỉ nhìn lướt qua.",
   "Ngay bên cạnh toà nhà, trên phố đi bộ Malaya Sadovaya, là một điểm nhấn nhỏ xíu nhưng cực kỳ dễ thương: chú mèo đồng tên Elisey ngồi vắt vẻo trên một gờ tường cao kể từ ngày 25 tháng 1 năm 2000. Ở phía bên kia đường còn có một cô mèo bạn đồng hành tên Vasilisa, và người qua đường có thói quen tung những đồng xu lên gờ tường để cầu may mắn, nếu đồng xu trụ lại được thì điều ước sẽ thành hiện thực. Đây là một trò chơi nhỏ vui nhộn mà khách Việt Nam rất thích thử. Ngoài ra, đừng quên rằng chính không gian bên trong cửa hàng mới là điểm nhấn lớn nhất, với đại sảnh mạ vàng, quán cà phê dưới tán cọ nhiệt đới, tầng hầm là nhà hàng trong hầm rượu cổ, và trên tầng cao là nhà hát – tất cả sẽ được nói kỹ hơn ở các phần sau."
  ]},
  {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
   "Trước hết, cửa hàng Eliseyev là một biểu tượng sống động của nước Nga thương gia thời trước cách mạng. Nó phản chiếu tham vọng, sự giàu có và gu thẩm mỹ của tầng lớp thương nhân mới nổi, những người không chỉ muốn buôn bán mà còn khao khát để lại dấu ấn văn hoá cho thành phố. Việc một gia đình xuất thân từ nông nô có thể vươn lên xây dựng một cung điện thương mại tráng lệ giữa lòng thủ đô cũ chính là minh chứng cho sự chuyển động mạnh mẽ của xã hội Nga cuối thế kỷ 19 đầu thế kỷ 20. Nền tảng của tất cả, như đã nói, chính là nghề buôn rượu vang, mà đỉnh cao là một trong những hầm rượu lớn và tốt bậc nhất châu Âu nằm ngay dưới lòng toà nhà.",
   "Về mặt kiến trúc, công trình là một cột mốc quan trọng của phong cách Tân nghệ thuật ở Nga. Nó từng bị chê là kệch cỡm khi mới ra đời, nhưng chính sự dũng cảm phá cách ấy đã mở đường cho một quan niệm mới về không gian thương mại, nơi cái đẹp và việc buôn bán không loại trừ mà tôn vinh lẫn nhau. Bộ khung thép và những mảng kính lớn cho thấy tinh thần đón nhận công nghệ mới của thời đại, đặt cửa hàng Eliseyev vào cùng dòng chảy đổi mới với những công trình tiên phong khác trên đại lộ Nevsky. Đối với giới nghiên cứu và sinh viên kiến trúc, đây là một ví dụ điển hình cho thấy nghệ thuật, kỹ thuật và thương mại có thể hoà quyện thành một khối thống nhất.",
   "Sang thời Xô-viết, ý nghĩa của toà nhà lại mang một sắc thái khác, gần gũi và đời thường hơn. Dưới cái tên chính thức «Gastronom số 1», nơi đây trở thành biểu tượng của sự sung túc hiếm hoi giữa những năm tháng thiếu thốn, là địa chỉ mà người dân tìm đến khi muốn có một món quà đặc biệt hay một thức ngon để dành cho dịp trọng đại. Việc người Leningrad kiên trì gọi cửa hàng bằng cái tên cũ Yeliseyevsky, bất chấp mọi thay đổi chính thức, cho thấy toà nhà đã ăn sâu vào ký ức tập thể và tình cảm của cả thành phố. Nó không chỉ là nơi mua bán, mà đã trở thành một phần của bản sắc đô thị.",
   "Sau cùng, cửa hàng Eliseyev còn là một chứng nhân lịch sử và một di sản được nhà nước bảo vệ. Những tấm áp phích «Cửa sổ TASS» xuất hiện từ ngày đầu chiến tranh, cùng hình ảnh các đoàn kịch vẫn biểu diễn trên tầng hai giữa mùa đông phong toả khắc nghiệt, đã khắc ghi vai trò tinh thần của toà nhà trong những giờ phút bi tráng nhất của Leningrad. Việc công trình được xếp hạng di sản được bảo vệ vào năm 2010 và nằm trong quần thể trung tâm lịch sử được UNESCO công nhận đã chính thức khẳng định giá trị của nó. Ngày nay, cửa hàng Eliseyev đứng đó như một tượng đài sống về nghệ thuật biến việc mua bán thành một màn trình diễn, một di sản mà thành phố vừa gìn giữ vừa tiếp tục sử dụng mỗi ngày."
  ]},
  {"heading": "Trải nghiệm dành cho du khách", "paras": [
   "Ngày nay, cửa hàng Eliseyev hoạt động như một khu ẩm thực cao cấp thực thụ, với nhiều gian hàng chuyên biệt và những quầy trưng bày dài tít tắp. Người ta ước tính nơi đây bày bán hơn ba nghìn mặt hàng khác nhau, từ sô-cô-la, bánh kẹo, phô mai, trà, cà phê cho tới trứng cá muối, rượu vang và vô số đặc sản nhập khẩu. Chỉ riêng việc dạo qua các quầy hàng, ngắm nhìn cách bài trí công phu và hít hà những mùi hương quyến rũ đã là một trải nghiệm đáng giá. Nhiều du khách ví von rằng bước vào đây giống như bước vào một viện bảo tàng mà mọi hiện vật đều có thể mua về được.",
   "Bên cạnh việc mua sắm, toà nhà còn có nhiều lựa chọn thưởng thức ẩm thực tại chỗ rất hấp dẫn. Ngay tầng trệt có một quán cà phê nằm dưới bóng một cây cọ nhiệt đới lớn, nơi khách có thể ngồi nhâm nhi cà phê và bánh ngọt giữa khung cảnh sang trọng. Trên tầng lửng là nhà hàng mang tên «Mezonin», còn dưới tầng hầm là một nhà hàng brasserie được bố trí ngay trong không gian của những hầm rượu cổ ngày xưa. Sự đa dạng này cho phép hướng dẫn viên linh hoạt gợi ý cho khách, từ việc ghé nhanh uống một tách cà phê cho tới một bữa ăn thong thả trong không gian đậm chất lịch sử.",
   "Một con số ấn tượng cho thấy sức hút của địa điểm: cửa hàng được cho là đón khoảng một trăm tám mươi nghìn lượt khách mỗi tháng, và phần lớn trong số đó đến không hẳn để mua sắm mà chủ yếu để chiêm ngưỡng không gian nội thất lộng lẫy. Điều này rất quan trọng để hướng dẫn viên định hình kỳ vọng cho đoàn: đây trước hết là một điểm tham quan để ngắm nhìn và tận hưởng, việc mua sắm chỉ là thứ yếu. Vì cửa vào miễn phí, khách hoàn toàn có thể thoải mái đi dạo, ngắm nghía và chụp ảnh mà không chịu bất kỳ áp lực nào phải chi tiền. Đây là một lợi thế lớn khi sắp xếp lịch trình cho các đoàn có ngân sách khác nhau.",
   "Về khía cạnh mua sắm quà tặng, cửa hàng Eliseyev là một địa chỉ lý tưởng để khách Việt Nam tìm mua những món quà mang đậm dấu ấn nước Nga. Những hộp sô-cô-la, hộp trà, các loại bánh kẹo đóng gói đẹp mắt hay một hũ trứng cá muối đều là những lựa chọn vừa ngon vừa sang, lại tiện mang về làm quà. Trải nghiệm ở đây là sự tổng hoà của mọi giác quan: mắt được chiêu đãi bởi ánh vàng và pha lê, mũi ngập trong hương cà phê và sô-cô-la, còn vị giác thì được nuông chiều bởi vô vàn thức ngon. Và nếu còn thời gian vào buổi tối, khách có thể cân nhắc thưởng thức một buổi diễn tại nhà hát trên tầng cao, để cảm nhận trọn vẹn tinh thần «cửa hàng kiêm nhà hát» độc đáo của nơi này."
  ]},
  {"heading": "Mẹo tham quan", "paras": [
   "Về giờ giấc, cửa hàng Eliseyev thường mở cửa tất cả các ngày trong tuần, trong khung giờ khoảng mười giờ sáng đến mười một giờ đêm, và việc vào cửa là hoàn toàn miễn phí. Chính vì mở cửa muộn, đây là một điểm đến rất linh hoạt: hướng dẫn viên có thể xếp đoàn ghé vào lúc chiều muộn hoặc đầu buổi tối, khi ánh đèn bên trong và trên mặt tiền tạo nên khung cảnh đẹp nhất. Buổi sáng và đầu giờ chiều thường vắng hơn, thích hợp cho những ai muốn thong thả ngắm nghía và chụp ảnh mà không bị chen lấn. Ngược lại, những ngày cuối tuần và các dịp lễ, đặc biệt là quanh Năm mới, lượng khách rất đông nên cần chuẩn bị tinh thần cho sự nhộn nhịp.",
   "Về chụp ảnh, có vài góc mà hướng dẫn viên nên chủ động gợi ý cho khách. Đẹp nhất để lấy trọn mặt tiền là đứng từ vỉa hè phía đối diện trên đại lộ Nevsky, hoặc lùi ra một chút ở góc phố Malaya Sadovaya để thu được cả ô kính vòm lẫn phần tháp góc. Bên trong, hãy hướng ống kính lên trần mạ vàng và những chiếc đèn chùm, cũng như về phía cây cọ nhiệt đới ở khu quán cà phê. Nếu ghé thăm vào dịp Năm mới, đừng bỏ lỡ ô cửa góc với các nhân vật chuyển động của vở «Kẹp Hạt Dẻ», một trong những khung hình được yêu thích nhất của cả đại lộ trong mùa lễ hội.",
   "Một trải nghiệm nhỏ mà khách Việt Nam thường rất thích là trò tung xu cầu may với chú mèo đồng Elisey trên phố Malaya Sadovaya. Hướng dẫn viên nên chuẩn bị sẵn vài đồng xu lẻ và giải thích luật chơi cho khách: ai tung được đồng xu trụ lại trên gờ tường bên cạnh chú mèo thì coi như điều ước sẽ ứng nghiệm. Đây là một hoạt động vui nhộn, tạo không khí gắn kết cho cả đoàn và cũng là dịp để chụp những bức ảnh sinh động. Sau đó, có thể dẫn khách sang ngắm cô mèo Vasilisa ở phía bên kia đường để hoàn thiện câu chuyện về đôi mèo bảo hộ của con phố.",
   "Cuối cùng, hãy luôn nhắc khách rằng đây là một cửa hàng đang hoạt động thực sự, chứ không đơn thuần là một điểm chụp ảnh. Vì thế nên giữ ý tứ khi di chuyển giữa các quầy hàng, tránh cản trở nhân viên và những vị khách đang mua sắm, đồng thời hỏi trước nếu muốn chụp cận cảnh một số khu vực nhất định. Về thanh toán, nên chuẩn bị phương án tiền mặt bằng đồng rúp, bởi thẻ ngân hàng quốc tế phát hành ngoài nước Nga thường gặp khó khăn khi giao dịch; hướng dẫn viên nên dặn dò khách chuẩn bị trước để tránh lúng túng tại quầy. Nếu muốn kết hợp một bữa ăn hay một buổi xem kịch, hãy tìm hiểu và đặt chỗ từ sớm, nhất là vào mùa cao điểm du lịch và các dịp lễ lớn."
  ]},
  {"heading": "Khám phá xung quanh", "paras": [
   "Một trong những lợi thế lớn nhất của cửa hàng Eliseyev là nó nằm ngay giữa lòng khu trung tâm, được bao quanh bởi hàng loạt điểm tham quan nổi tiếng, gần như tất cả đều trong tầm đi bộ. Ngay trước cửa là đại lộ Nevsky, trục phố huyết mạch và cũng là bảo tàng kiến trúc ngoài trời của thành phố, nơi du khách có thể thong thả dạo bộ và chiêm ngưỡng vô số dinh thự, nhà thờ và cửa hiệu lịch sử. Sát bên hông toà nhà là phố đi bộ Malaya Sadovaya, chỉ cách chừng hai mươi mét, với những chú mèo đồng Elisey và Vasilisa cùng bầu không khí thư thái rất đặc trưng. Chỉ riêng khu vực quanh ngã tư này đã đủ cho một buổi tản bộ thú vị.",
   "Cách cửa hàng khoảng một trăm năm mươi đến hai trăm mét là khu thương xá cổ kính Gostiny Dvor, một trong những trung tâm mua sắm lâu đời nhất châu Âu, đồng thời cũng là tên của ga metro gần nhất. Ở khoảng cách tương tự, tại số 48 đại lộ Nevsky, là thương xá Passage, một dãy phố mua sắm có mái kính duyên dáng rất đáng ghé qua. Sự tập trung dày đặc của các không gian thương mại lịch sử này cho thấy vì sao đoạn đại lộ Nevsky quanh cửa hàng Eliseyev từ lâu đã là trái tim mua sắm và giao thương của cả thành phố. Hướng dẫn viên có thể dễ dàng kết nối các địa điểm này thành một chuỗi tham quan liền mạch.",
   "Đi bộ thêm một quãng ngắn, khoảng hai trăm đến ba trăm mét, du khách sẽ tới Quảng trường Ostrovsky với Nhà hát Alexandrinsky bề thế, một trong những nhà hát kịch lâu đời và danh giá nhất nước Nga. Ngay giữa quảng trường là tượng đài Nữ hoàng Ekaterina Đại đế uy nghi, xung quanh có công viên nhỏ rợp bóng cây, là nơi lý tưởng để nghỉ chân và chụp ảnh. Khu vực này còn dẫn tới con phố Rossi nổi tiếng với tỷ lệ kiến trúc hài hoà đến mức được xem như mẫu mực. Đây là điểm dừng tuyệt vời để kết hợp câu chuyện về lịch sử sân khấu và quy hoạch đô thị của Saint Petersburg.",
   "Về phía đông, cách cửa hàng chừng bốn trăm năm mươi đến năm trăm năm mươi mét dọc theo đại lộ Nevsky, là cây cầu Anichkov bắc qua sông Fontanka, nổi tiếng với bốn nhóm tượng đồng «Người thuần ngựa» do nhà điêu khắc Peter Klodt tạo tác. Bốn cụm tượng khắc hoạ cuộc vật lộn đầy kịch tính giữa con người và những con tuấn mã, được xem là một trong những biểu tượng điêu khắc đẹp nhất của thành phố. Từ cửa hàng Eliseyev, hướng dẫn viên có thể thiết kế một lộ trình đi bộ hợp lý: bắt đầu từ ngã tư Malaya Sadovaya, đi dọc đại lộ Nevsky về phía cầu Anichkov, kết hợp ghé thăm các thương xá và quảng trường trên đường. Nhờ vậy, một điểm dừng ngắn tại cửa hàng có thể mở rộng thành cả một hành trình khám phá trung tâm thành phố."
  ]},
  {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
   "Giai thoại đáng kể đầu tiên, và cũng lãng mạn nhất, chính là câu chuyện về trái dâu rừng mùa đông năm 1812. Người ta kể rằng ông tổ của dòng họ, Pyotr Eliseyev, khi còn là người làm vườn nông nô cho Bá tước Sheremetev, đã làm cả bàn tiệc kinh ngạc khi dâng lên những trái dâu rừng tươi giữa đêm Giáng sinh giá lạnh. Vị bá tước cảm phục đến mức trả tự do cho ông cùng một khoản tiền, và từ hạt mầm nhỏ bé ấy đã mọc lên cả một triều đại thương gia. Hướng dẫn viên nên lưu ý một chi tiết vui: trang tiếng Anh của cửa hàng từng dịch nhầm loại quả thành «quả mâm xôi», trong khi bản gốc tiếng Nga khẳng định đó là dâu rừng, một sự khác biệt nhỏ nhưng khiến giai thoại thêm phần ly kỳ.",
   "Giai thoại thứ hai gắn với màn ra mắt đầy tai tiếng của toà nhà vào năm 1903. Khi công trình vừa hoàn thành, giới phê bình kiến trúc đã lời ra tiếng vào, cho rằng cái khối kính và đồng phô trương này là kệch cỡm, thậm chí thô tục, không xứng với vẻ trang nghiêm cổ điển của đại lộ Nevsky. Ấy vậy mà người dân Saint Petersburg lại nhanh chóng phải lòng nó, bị mê hoặc bởi sự táo bạo, lộng lẫy và có phần ngông nghênh của nó. Theo thời gian, chính công trình từng bị chê bai ấy đã trở thành một trong những biểu tượng được yêu mến nhất thành phố, một minh chứng thú vị cho thấy cái mới mẻ và gây tranh cãi hôm nay có thể trở thành di sản đáng tự hào của ngày mai.",
   "Một câu chuyện đặc biệt duyên dáng là chuyện toà nhà vừa là cửa hàng vừa là nhà hát. Ngay từ đầu, phần tầng trên đã được dành cho không gian sân khấu, cho thuê để các đoàn biểu diễn từ năm 1904, rồi trở thành một nhà hát cố định từ năm 1929, và ngày nay chính là Nhà hát Hài kịch mang tên đạo diễn N. P. Akimov. Người ta hình dung cảnh những quý ông thanh lịch đưa các quý bà tới đây, trước hết ghé qua tầng trệt mua trái cây, sô-cô-la và phô mai để nhâm nhi, rồi mới thong thả lên gác thưởng thức một vở kịch. Đáng tiếc là phần nội thất Tân nghệ thuật nguyên bản lộng lẫy của nhà hát đã bị phá bỏ trong một đợt cải tạo hồi thập niên 1960, nhưng câu chuyện về sự kết hợp độc đáo giữa ẩm thực và sân khấu thì vẫn còn được kể mãi.",
   "Không thể không nhắc tới hai biểu tượng gần gũi với du khách hôm nay: ô cửa «Kẹp Hạt Dẻ» và đôi mèo trên phố. Kể từ năm 2012, ô cửa sổ ở góc nhà trưng bày những nhân vật chuyển động của vở «Kẹp Hạt Dẻ» do nghệ sĩ Mikhail Shemyakin sáng tạo và dành tặng thành phố, trở thành điểm chụp ảnh yêu thích, nhất là vào mùa Năm mới. Còn chú mèo đồng Elisey thì đã ngồi trên gờ tường phố Malaya Sadovaya từ ngày 25 tháng 1 năm 2000, cùng cô bạn Vasilisa ở phía đối diện, và người qua đường vẫn tung xu lên cầu may. Cả trong thời Xô-viết, dù mang tên chính thức là «Gastronom số 1», người dân vẫn một mực gọi nơi này là Yeliseyevsky, cho thấy cái tên và tình cảm dành cho cửa hàng bền bỉ đến nhường nào.",
   "Sau cùng, có một giai thoại mang màu sắc trinh thám ít người biết. Vào năm 1881, ngay tại khu đất này, nhưng thuộc về một toà nhà cũ trước khi công trình hiện nay được xây, những nhà cách mạng đã bí mật đào một đường hầm từ tầng hầm ra phía dưới phố Malaya Sadovaya. Mục đích của họ là cài mìn trên tuyến đường mà Sa hoàng Aleksandr II thường đi qua, trong một âm mưu ám sát nhắm vào nhà vua. Chi tiết lịch sử đầy kịch tính này, ẩn sau vẻ ngoài hào nhoáng và ngọt ngào của một cửa hàng đặc sản, nhắc ta rằng ngay cả một địa chỉ mua sắm sang trọng cũng có thể cất giữ những trang sử ngầm đầy bất ngờ. Đó chính là chất liệu quý để hướng dẫn viên khép lại phần thuyết minh bằng một câu chuyện khiến cả đoàn phải trầm trồ."
  ]}
 ],
 "highlights": [
  "Ô kính vòm khổng lồ chiếm hơn nửa mặt tiền, khiến cả mặt trước toà nhà trông như một ô cửa kính trưng bày hàng hoá phi thường.",
  "Bốn pho tượng đồng của Amandus Adamson năm 1903, tượng trưng cho Công nghiệp, Thương mại, Nghệ thuật và Khoa học.",
  "Những nhân vật chuyển động của vở «Kẹp Hạt Dẻ» do Mikhail Shemyakin sáng tạo, trưng bày ở ô cửa góc từ năm 2012.",
  "Chú mèo đồng Elisey trên gờ tường phố Malaya Sadovaya từ năm 2000, cùng cô mèo Vasilisa bên kia đường, để khách tung xu cầu may.",
  "Đại sảnh bán hàng nội thất cung điện với trần thạch cao mạ vàng, đèn chùm pha lê và những quầy trưng bày dài lộng lẫy.",
  "Quán cà phê nằm dưới bóng một cây cọ nhiệt đới lớn ngay tầng trệt, một góc thư giãn sang trọng và độc đáo.",
  "Hầm rượu vang cổ dưới lòng toà nhà, từng thuộc hàng lớn nhất châu Âu, nay là không gian nhà hàng brasserie.",
  "Nhà hát Hài kịch Akimov ở tầng trên, minh chứng cho căn tính độc đáo của một toà nhà vừa là cửa hàng vừa là nhà hát."
 ],
 "images": [
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Spb%2006-2017%20img49%20Eliseevsky%20Shop.jpg", "caption": "Mặt tiền cửa hàng Eliseyev trên đại lộ Nevsky với ô kính vòm khổng lồ kiểu Art Nouveau."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Eliseevs'%20House%20SPB%2001.jpg", "caption": "Góc nhà nơi giao đại lộ Nevsky và phố Malaya Sadovaya."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/2528.%20St.%20Petersburg.%20Main%20building%20of%20the%20%22Eliseev%20Brothers%22%20trading%20house.jpg", "caption": "Toà nhà chính của thương hội «Anh em Eliseyev»."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Eliseyev%20shop%20boucherie.JPG", "caption": "Gian hàng bên trong với trang trí Art Nouveau mạ vàng lộng lẫy."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Скульптуры%20А.Г.%20Адамсона%20Промышленность%20,%20Наука%20.%20Дом%20торгового%20товарищества%20«Братья%20Елисеевы».%20Невский%20пр.,%2056%20(cropped).jpg", "caption": "Tượng đồng của Amandus Adamson tượng trưng cho Công nghiệp và Khoa học trên mặt tiền."}
 ],
 "references": [
  {"title": "Wikipedia (tiếng Anh) — Eliseyev Emporium (Saint Petersburg)", "url": "https://en.wikipedia.org/wiki/Eliseyev_Emporium_(Saint_Petersburg)"},
  {"title": "Wikipedia (tiếng Nga) — Елисеевский магазин", "url": "https://ru.wikipedia.org/wiki/Елисеевский_магазин"},
  {"title": "Trang chính thức — Kupetz Eliseevs (lịch sử)", "url": "https://www.kupetzeliseevs.ru/en/istoriya/"},
  {"title": "Trang chính thức — Kupetz Eliseevs", "url": "https://www.kupetzeliseevs.ru/"},
  {"title": "Saint-Petersburg.com — The Eliseyev Emporium", "url": "http://www.saint-petersburg.com/buildings/eliseyev-emporium/"},
  {"title": "56 Nevsky Prospect — Wikipedia (tiếng Anh)", "url": "https://en.wikipedia.org/wiki/56_Nevsky_Prospect"},
  {"title": "RFE/RL — Moscow’s Iconic No. 1 Grocery Store Shuts Down (2021)", "url": "https://www.rferl.org/a/moscow-iconic-no-1-grocery-store-shuts-down/31199596.html"}
 ],
 "sources": [
  "Bách khoa toàn thư mở Wikipedia bản tiếng Anh (mục Eliseyev Emporium, Saint Petersburg): niên đại xây dựng 1902 đến 1903, kiến trúc sư Gavriil Baranovsky, bốn pho tượng đồng của Adamson và công năng khu ẩm thực hiện nay.",
  "Wikipedia bản tiếng Nga (mục Елисеевский магазин): triều đại thương gia Eliseyev, tên gọi Gastronom số 1 thời Xô-viết, các đoàn kịch biểu diễn thời phong toả và không gian nhà hát trên tầng.",
  "Trang chính thức Kupetz Eliseevs (mục lịch sử): giai thoại trái dâu rừng mùa đông năm 1812, dòng họ Eliseyev và cuộc trùng tu, mở cửa lại năm 2012.",
  "Trang chính thức Kupetz Eliseevs (trang chủ): mô tả các gian hàng, quán cà phê dưới tán cọ, nhà hàng Mezonin và không gian trong hầm rượu cổ hiện nay.",
  "Trang Saint-Petersburg.com (mục The Eliseyev Emporium): phân tích phong cách Tân nghệ thuật, bộ khung thép cho phép lắp ô kính vòm lớn và sự tương phản giữa đá granite với kính.",
  "Wikipedia bản tiếng Anh (mục 56 Nevsky Prospect): tư cách di sản được bảo vệ, lịch sử nhà hát trên tầng và giai thoại đường hầm đào năm 1881 dưới phố Malaya Sadovaya.",
  "Đài RFE/RL (bài về việc cửa hàng số 1 mang tính biểu tượng ở Moscow đóng cửa năm 2021): số phận của cửa hàng chị em trên phố Tverskaya, mở năm 1901 và đóng cửa tháng 4 năm 2021.",
  "Tổng hợp dữ kiện thực tế (giờ mở cửa khoảng mười giờ sáng đến mười một giờ đêm, vào cửa miễn phí, toạ độ, ga metro Gostiny Dvor, ô cửa Kẹp Hạt Dẻ của Shemyakin, đôi mèo Elisey và Vasilisa): metadata dự án và thông tin tham quan hiện hành."
 ]
}

out_path = "/sessions/stoic-gallant-fermi/mnt/russia-tourism/_incoming/doc_eliseyev-emporium.json"
json.dump(doc, open(out_path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("OK words=", sum(len(p.split()) for s in doc["sections"] for p in s["paras"]))
for s in doc["sections"]:
    print("  -", s["heading"], ":", len(s["paras"]), "paras,", sum(len(p.split()) for p in s["paras"]), "words")
