# -*- coding: utf-8 -*-
"""Builder: doc_tolstoy-khamovniki-estate.json — noi dung nguyen goc tieng Viet.

Bao tang - Dien trang L. N. Tolstoy o Khamovniki, Moscow.
Tai lieu noi bo danh cho huong dan vien du lich Viet Nam.
"""
import json


def img(fname, cap):
    return {
        "url": "https://commons.wikimedia.org/wiki/Special:FilePath/" + fname.replace(" ", "%20"),
        "caption": cap,
    }


doc = {
    "slug": "tolstoy-khamovniki-estate",
    "name_vi": "Bảo tàng – Điền trang L.N. Tolstoy ở Khamovniki (Tôn-xtôi, Kha-mốp-ni-ki)",
    "name_ru": "Музей-усадьба Л. Н. Толстого «Хамовники»",
    "name_en": "Leo Tolstoy Estate Museum in Khamovniki",
    "subtitle": "Ngôi nhà gỗ hai tầng nơi văn hào Lev Tolstoy cùng đại gia đình sống qua mười chín mùa đông (1882–1901); nơi ra đời tiểu thuyết «Phục sinh» và gần một trăm tác phẩm, đồng thời là sân khấu cho cuộc «giản dị hoá» nổi tiếng của ông. Một trong những bảo tàng văn học lâu đời nhất nước Nga, mở cửa từ năm 1921 và vừa được trùng tu, mở lại ngày 3 tháng 1 năm 2025.",
    "sections": [
        {"heading": "Giới thiệu chung", "paras": [
            "Nằm khiêm nhường giữa khu phố Khamovniki của Moscow, chỉ cách vành đai Sadovoye (Vành đai Vườn) vài bước chân, Bảo tàng – Điền trang Lev Tolstoy không phải là một cung điện tráng lệ, mà là một ngôi nhà gỗ hai tầng ấm cúng ẩn sau hàng rào và tán cây. Đây chính là mái nhà ở Moscow của đại văn hào Lev Nikolayevich Tolstoy – tác giả của «Chiến tranh và Hoà bình» cùng «Anna Karenina» – nơi ông và gia đình đông đúc đã gắn bó suốt gần hai mươi năm cuối thế kỷ 19.",
            "Tên gọi đầy đủ của di tích là Bảo tàng – Điền trang tưởng niệm quốc gia «Khamovniki», một chi nhánh của Bảo tàng Quốc gia L. N. Tolstoy. Nhà văn mua lại khu đất này vào năm 1882, và từ đó cho tới mùa xuân năm 1901, gia đình ông sống ở đây trọn mười chín mùa đông, còn mùa hè thì trở về điền trang tổ tiên Yasnaya Polyana ở tỉnh Tula. Chính trong những bức tường gỗ này, ông đã chấp bút gần một trăm tác phẩm lớn nhỏ, trong đó có kiệt tác cuối đời «Phục sinh». Cần nhớ rằng đây là một gia đình rất đông con: trong mười ba người con của vợ chồng Tolstoy, có tới mười người từng lớn lên dưới mái nhà Moscow này, khiến các căn phòng lúc nào cũng rộn rã tiếng người.",
            "Điều khiến Khamovniki trở nên đặc biệt không nằm ở sự xa hoa, mà ở nghịch lý sống động mà nó lưu giữ. Đây là nơi một vị bá tước quý tộc tự nguyện sống như một người nông dân: ăn chay, tự quét dọn phòng riêng, bổ củi, gánh nước, và thậm chí học nghề đóng giày. Ngôi nhà mười sáu phòng của một dòng dõi thượng lưu lại toạ lạc ngay giữa một vùng ngoại ô công nghiệp ồn ào, bao quanh bởi các nhà máy dệt, xưởng nước hoa và lò bia – một khung cảnh phản chiếu đúng tấn bi kịch nội tâm và cuộc khủng hoảng tinh thần mà Tolstoy trải qua tại đây.",
            "Với giới bảo tàng, Khamovniki là một báu vật hiếm có: đây là một trong những bảo tàng văn học lâu đời nhất nước Nga, mở cửa từ ngày 20 tháng 11 năm 1921. Không gian bên trong được gìn giữ gần như nguyên vẹn, với khoảng sáu nghìn hiện vật gốc của chính gia đình Tolstoy – từ bàn viết, chiếc ghế cho tới bộ đồ nghề đóng giày. Bước qua ngưỡng cửa, du khách có cảm giác như gia chủ chỉ vừa mới rời đi, để lại mọi thứ nguyên vẹn trong nếp sống thường nhật. Chính sự chân thực ấy – chứ không phải quy mô hay sự lộng lẫy – mới là điều làm nên sức lay động đặc biệt của Khamovniki đối với người Nga cũng như với những ai yêu văn chương của Tolstoy.",
            "Sau một thời gian dài đóng cửa để trùng tu từ mùa thu năm 2022, ngôi nhà đã mở cửa trở lại vào ngày 3 tháng 1 năm 2025, khang trang hơn nhưng vẫn trung thành với diện mạo giữa thập niên 1890. Trong tập tài liệu này, hướng dẫn viên sẽ lần lượt tìm hiểu vị trí và cách di chuyển, lịch sử hình thành, kiến trúc, các điểm nhấn nổi bật, ý nghĩa văn hoá, trải nghiệm tham quan, những mẹo hữu ích, các điểm đến quanh vùng, và sau cùng là kho giai thoại thú vị gắn liền với ngôi nhà.",
        ]},
        {"heading": "Vị trí & cách di chuyển", "paras": [
            "Bảo tàng – Điền trang toạ lạc tại số 21 phố Lev Tolstoy (ulitsa Lva Tolstogo), thuộc quận Khamovniki ở phía tây nam trung tâm Moscow, với toạ độ khoảng 55,734202 vĩ bắc và 37,585907 kinh đông. Con phố vốn mang tên khác, nhưng về sau được đổi thành tên nhà văn để tưởng nhớ người cư dân lừng danh nhất của nó – một chi tiết nhỏ nhưng nói lên tầm vóc của Tolstoy trong lòng người Nga.",
            "Ga tàu điện ngầm gần nhất là Park Kultury, phục vụ cả tuyến vòng (Koltsevaya) lẫn tuyến đỏ; từ ga chỉ cần đi bộ chừng mười phút là tới cổng điền trang. Vị trí này nằm ngay bên trong Vành đai Vườn (Sadovoye Koltso), nên rất thuận tiện để kết hợp với các điểm tham quan ở trung tâm. Đây là lợi thế lớn khi thiết kế lịch trình, bởi khách không phải đi quá xa khỏi lõi thành phố. Với những ai muốn thong thả, có thể xuống ga Park Kultury rồi tản bộ qua vài dãy phố yên tĩnh mang dáng dấp Moscow cũ trước khi tới cổng bảo tàng.",
            "Bản thân cái tên Khamovniki đã hé lộ lịch sử của vùng đất: đây từng là một sloboda – khu định cư của thợ thủ công dệt vải lanh. Những người thợ dệt được đưa từ vùng Tver về đây định cư vào năm 1624, và từ «kham» trong tiếng Nga cổ chỉ loại vải lanh thô mà họ dệt nên. Đến thời Pyotr Đại đế, năm 1708, một xưởng dệt vải buồm cho hải quân cũng được lập tại đây, biến khu phố thành một trung tâm thủ công lâu đời.",
            "Vào thời Tolstoy dọn đến, Khamovniki đã trở thành một vùng ngoại ô công nghiệp của tầng lớp lao động, xen lẫn những khu vườn xanh mát. Xung quanh là hàng loạt nhà máy: xưởng lụa Giraud, một xưởng nước hoa và một lò bia. Chính nhà văn từng ghi lại cảm giác sống giữa lòng công nghiệp ấy: «Tôi sống giữa các nhà máy. Mỗi sáng 5 giờ, còi hụ bắt đầu, một cái, rồi cái nữa, rồi cả chục cái...». Câu than ấy giúp du khách hình dung một Moscow đang chuyển mình dữ dội.",
            "Đối với các đoàn khách Việt Nam, cách thuận tiện nhất vẫn là xe du lịch riêng đưa đến tận cổng, bởi khu phố tuy gần trung tâm nhưng đường sá quanh co. Với khách tự túc, tàu điện ngầm tới ga Park Kultury là lựa chọn nhanh và rẻ nhất. Từ đây, du khách có thể dễ dàng đi bộ kết hợp thăm bờ sông Moskva, Công viên Gorky hay công viên nghệ thuật Muzeon ở gần đó, biến một buổi tham quan thành trọn nửa ngày trải nghiệm. Ngoài ra, do khu phố khá đông đúc vào giờ cao điểm, hướng dẫn viên nên tính toán thời gian di chuyển dư dả để đoàn không bị cập rập khi khớp lịch với các điểm khác trong ngày.",
        ]},
        {"heading": "Lịch sử hình thành và phát triển", "paras": [
            "Ngôi nhà gỗ có tuổi đời còn lớn hơn cả sự nổi tiếng của nó. Công trình được dựng vào năm 1805 (một số tài liệu tiếng Anh ghi khoảng 1800–1805) dưới thời chủ nhân là Công tước Ivan Meshchersky. Đáng kinh ngạc là ngôi nhà đã sống sót qua trận Đại hoả hoạn Moscow năm 1812 – khi phần lớn thành phố chìm trong biển lửa lúc quân Napoléon chiếm đóng; bản thân ngôi nhà khi ấy được binh lính Pháp trưng dụng làm nơi trú quân, và có lẽ nhờ vậy mà thoát khỏi ngọn lửa.",
            "Trải qua nhiều đời chủ, đến năm 1874 ngôi nhà thuộc về Ivan Arnautov, một viên thư ký hạng collegiate. Chính từ tay Arnautov, Lev Tolstoy đã mua lại toàn bộ điền trang – gồm ngôi nhà chính, các công trình phụ và khoảng một hecta đất – vào năm 1882, với giá vào khoảng 36.000 rúp (một số nguồn tiếng Nga ghi 37.000 rúp). Đó là một khoản tiền đáng kể thời bấy giờ, cho thấy quyết tâm của nhà văn khi lập tổ ấm ở Moscow.",
            "Vì sao một người yêu điền trang thôn dã như Tolstoy lại chuyển về thành phố? Lý do chủ yếu là vì các con: những đứa con lớn cần được học hành tử tế, còn các cô con gái đến tuổi cần bước vào giới thượng lưu Moscow. Người hàng xóm, Tướng Adam Olsufyev, còn khéo léo thuyết phục ông bằng viễn cảnh có thể đi bộ từ nhà tới tận Đồi Chim Sẻ «mà không phải đặt chân lên vỉa hè», cứ men theo hết khu vườn này đến khu vườn khác. Gia đình chính thức dọn vào ngày 8 tháng 10 năm 1882.",
            "Kể từ đó, gia đình Tolstoy sống ở Khamovniki mười chín mùa đông liên tiếp, cho tới khi rời Moscow hẳn vào mùa xuân năm 1901. Sau khi nhà văn qua đời cuối năm 1910, đến năm 1911, bà Sofia Andreevna – vợ ông – đã bán ngôi nhà cho Hội đồng thành phố Moscow. Điều may mắn cho hậu thế là bà đã lập danh mục và đóng gói cẩn thận toàn bộ đồ đạc, chính nhờ vậy mà việc phục dựng nguyên trạng sau này mới có thể thực hiện một cách chính xác đến từng chi tiết. Cũng nên nói thêm rằng trong mười ba người con của gia đình, mười người đã sống tại ngôi nhà Moscow này; người con út – bé Vanechka – qua đời ngay tại đây năm 1895, một mất mát để lại dấu ấn sâu đậm lên những năm cuối gia đình còn gắn bó với Khamovniki.",
            "Sau Cách mạng, điền trang được quốc hữu hoá theo một sắc lệnh thời Lenin, và bảo tàng tưởng niệm chính thức mở cửa ngày 20 tháng 11 năm 1921 – trở thành một trong những bảo tàng văn học lâu đời nhất nước Nga. Giám đốc đầu tiên là Valentin Bulgakov, người thư ký cuối cùng của Tolstoy. Ngôi nhà đóng cửa trùng tu từ mùa thu 2022 và mở lại ngày 3 tháng 1 năm 2025. Đáng chú ý, giám đốc đương nhiệm của Bảo tàng Quốc gia L. N. Tolstoy hiện nay là ông Vladimir Ilyich Tolstoy, một hậu duệ của chính nhà văn.",
        ]},
        {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
            "Về bản chất, đây là một ngôi nhà gỗ hai tầng theo lối kiến trúc quý tộc tỉnh lẻ Nga, giản dị chứ không phô trương. Khi Tolstoy mua lại, ngôi nhà chưa hề có điện, nước máy hay hệ thống thoát nước – những tiện nghi mà một gia đình đông người rất cần. Người đứng ra quán xuyến toàn bộ việc sửa sang, cải tạo chính là bà Sofia Andreevna, vợ nhà văn, một người phụ nữ đảm đang và giàu năng lực tổ chức.",
            "Dưới thời Arnautov, ngôi nhà vốn chỉ có một tầng. Để có đủ chỗ cho gia đình đông đúc, Tolstoy đã cho nâng trần, xây thêm một tầng nữa, làm một cầu thang lớn hai vế và một phòng khách rộng để tiếp khách cùng tổ chức những buổi tối âm nhạc. Người phụ trách phần cải tạo kiến trúc này là kiến trúc sư Mikhail Nikiforov. Sau khi tu sửa, ngôi nhà có tổng cộng mười sáu phòng, nối với nhau bằng những hành lang dài đặc trưng. Chiếc cầu thang hai vế cùng phòng khách rộng không chỉ đáp ứng nhu cầu sinh hoạt, mà còn tạo nên sân khấu cho những buổi tiếp khách và hoà nhạc, nơi cả gia đình cùng bạn hữu quây quần mỗi tối mùa đông giá lạnh.",
            "Điền trang không chỉ có ngôi nhà chính, mà là cả một quần thể thu nhỏ. Trong khuôn viên còn có một dãy nhà phụ (flügel), nhà bếp, nhà người gác cổng, một chòi nghỉ (gazebo) và nhà để xe ngựa. Bố cục ấy giúp tái hiện trọn vẹn nếp sinh hoạt tự cấp tự túc của một gia đình quý tộc Nga cuối thế kỷ 19 ngay giữa lòng đô thị, nơi từng khu nhà đảm nhận một chức năng riêng trong đời sống thường ngày.",
            "Bao quanh nhà là một khu vườn rộng gần một hecta – một ốc đảo xanh hiếm có giữa vùng công nghiệp. Vườn có những gò đất nhỏ, lối đi quanh co, khóm hồng, chừng mười cây táo, ba mươi cây anh đào, cùng mận, mâm xôi, lý gai và hoàng liên gai. Trong vườn còn một giếng nước cũ; mỗi sáng, đích thân nhà văn ra gánh nước về nhà. Bà Sofia từng mang bảy mươi cây sồi và cây phong non từ Yasnaya Polyana về trồng, tiếc rằng chúng không bén rễ nổi trên đất Moscow. Dù vậy, khu vườn vẫn là niềm tự hào của gia đình và là nơi nhà văn tìm thấy sự tĩnh tại hiếm hoi giữa nhịp sống công nghiệp ồn ã đang bủa vây tứ phía.",
            "Đợt trùng tu gần đây (2022–2025) đã gia cố lại phần móng, phục hồi những lò sưởi ốp gạch men, sàn gỗ parquet cổ và các đường phào chỉ trên trần, đồng thời tái tạo lại giấy dán tường theo đúng mẫu xưa. Toàn bộ nội thất được phục dựng trung thành với diện mạo của ngôi nhà vào khoảng giữa thập niên 1890 – thời điểm gia đình Tolstoy sinh sống sung túc và đông đủ nhất tại đây, để du khách hôm nay được thấy đúng khung cảnh của những năm tháng ấy.",
        ]},
        {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
            "Trái tim của ngôi nhà là phòng làm việc của nhà văn. Tại đây trưng bày chiếc bàn viết có lan can gỗ tiện đặc trưng – nơi phần lớn tiểu thuyết «Phục sinh» đã ra đời. Bên bàn là một chi tiết khiến nhiều du khách bật cười thích thú: chiếc ghế bị cưa ngắn bớt bốn chân, bởi Tolstoy bị cận thị nặng và cần ngồi thật thấp, gí sát mắt xuống trang giấy mỗi khi viết. Chi tiết nhỏ ấy hé lộ cả một con người tận tuỵ với chữ nghĩa.",
            "Cũng trong phòng làm việc, du khách sẽ thấy những đôi ủng do chính tay bá tước đóng, cùng bộ đồ nghề thợ giày. Tolstoy học nghề này từ một người thợ giày tên Prokofy Vlasov, và say mê đến mức đóng cả một đôi ủng tặng nhà thơ Afanasy Fet. Đây là minh chứng vật chất sống động cho triết lý lao động chân tay mà ông theo đuổi – rằng một người trí thức cũng nên biết làm ra những vật dụng thiết thực bằng đôi tay của mình.",
            "Không xa đó là hai hiện vật bất ngờ khác: chiếc xe đạp và bộ tạ tay tập thể dục của nhà văn. Ít ai ngờ rằng ở tuổi sáu mươi bảy, vào năm 1895, Tolstoy mới bắt đầu học đi xe đạp – một thú vui tân thời khi ấy còn khá lạ lẫm với người Nga. Những món đồ này cho thấy một Tolstoy ham vận động, luôn khát khao thử thách bản thân cả về thể chất chứ không chỉ trên trang viết. Với nhiều du khách, hình ảnh một văn hào ngoài sáu mươi tuổi hào hứng tập giữ thăng bằng trên yên xe là một khám phá thú vị, phá vỡ hình dung cứng nhắc về một triết gia chỉ biết trầm tư suy tưởng.",
            "Cảm động nhất trong toàn bộ ngôi nhà có lẽ là căn phòng của bé Vanechka (Ivan), người con út của gia đình, mất vì bệnh tinh hồng nhiệt vào tháng 2 năm 1895 khi chưa tròn bảy tuổi. Căn phòng trẻ thơ được giữ nguyên với những món đồ chơi, con ngựa bập bênh, chiếc lồng chim, các quyển vở tập viết tiếng Pháp, và cả một mẩu truyện ngắn mà cậu bé từng ứng khẩu để người lớn chép lại. Đứng trước căn phòng, không ai không nghẹn lòng.",
            "Phòng ăn của gia đình được bài trí một cách giản dị đến mức cố ý, phản ánh quan niệm sống khắc kỷ của gia chủ. Trong khi đó, ở tầng trên, chiếc đàn dương cầm hiệu Becker lại là linh hồn của những buổi tối âm nhạc lừng danh. Và đừng quên chiếc cầu thang lớn hai vế – vừa là điểm nhấn kiến trúc bề thế của ngôi nhà, vừa gắn với biết bao kỷ niệm vui của lũ trẻ, như ta sẽ thấy trong phần giai thoại.",
        ]},
        {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
            "Ý nghĩa văn học của Khamovniki là điều không thể bàn cãi: tại đây, Tolstoy đã sáng tác khoảng một trăm tác phẩm. Bảo tàng ghi công ngôi nhà với tiểu thuyết «Phục sinh», các truyện «Cái chết của Ivan Ilyich», «Bản sonata Kreutzer» và «Cha Sergius», vở kịch «Quyền lực của bóng tối», vở hài kịch «Thành quả của khai minh», cùng khảo luận nổi tiếng «Nghệ thuật là gì?». Đây là một mùa gặt sáng tạo đồ sộ mà bất kỳ nhà văn nào cũng phải mơ ước.",
            "Nhưng Khamovniki còn là sân khấu cho một biến chuyển sâu sắc hơn: cuộc khủng hoảng tinh thần của Tolstoy trong thập niên 1880. Chính tại đây, ông đi đến quyết định «giản dị hoá» (tiếng Nga: oproshchenie) toàn bộ đời sống của mình. Ông trở thành người ăn chay, tự dọn phòng, bổ củi, nhóm lò sưởi và gánh nước – những việc mà một quý tộc thời ấy thường phó mặc hoàn toàn cho gia nhân. Ngôi nhà vì thế trở thành nơi chứng kiến sự lột xác của một tâm hồn lớn.",
            "Ngôi nhà đồng thời là một salon văn hoá bậc nhất Moscow. Bước qua ngưỡng cửa này từng có những tên tuổi lẫy lừng: nhà văn Anton Chekhov và Maxim Gorky, các danh hoạ Ilya Repin và Nikolai Ge, nhà thơ Afanasy Fet, triết gia Vladimir Solovyov, và cả bậc thầy sân khấu Konstantin Stanislavsky. Mỗi vị khách đều để lại dấu ấn trong đời sống tinh thần phong phú của gia đình, biến ngôi nhà thành một điểm hội tụ của giới trí thức Nga đương thời.",
            "Âm nhạc giữ vị trí trung tâm, bởi Tolstoy xem đây là loại hình nghệ thuật cao quý nhất. Bên chiếc dương cầm Becker ở tầng trên, những nghệ sĩ vĩ đại của nước Nga đã từng trình diễn: Sergei Rachmaninoff và Alexander Scriabin dạo phím, danh ca Fyodor Chaliapin cất giọng, còn Nikolai Rimsky-Korsakov và Sergei Taneyev cũng góp mặt. Có một nét độc đáo: gia chủ không câu nệ nghi thức tiếp khách, mà để mỗi người tự tìm lấy niềm vui riêng trong buổi tối. Cách tiếp khách phóng khoáng ấy phản ánh đúng tính cách Tolstoy: ông ghét sự khách sáo giả tạo và muốn mọi người được là chính mình, dù đó là một nhà soạn nhạc lừng danh hay một người nông dân tình cờ ghé thăm.",
            "Chính vì thế, khi trở thành bảo tàng vào năm 1921, Khamovniki không đơn thuần là một ngôi nhà cũ, mà là một lát cắt được bảo tồn nguyên vẹn của lịch sử văn hoá Nga. Việc lưu giữ được khoảng sáu nghìn hiện vật gốc của gia đình khiến nơi đây trở thành một trong những di tích tưởng niệm chân thực và giá trị nhất về đại văn hào, mang sức nặng học thuật lẫn cảm xúc mà ít nơi nào sánh được.",
        ]},
        {"heading": "Trải nghiệm dành cho du khách", "paras": [
            "Một chuyến thăm Khamovniki là hành trình bước vào không gian riêng tư của một gia đình vĩ đại. Về giờ giấc, bảo tàng đóng cửa thứ Hai; mở cửa thứ Ba và thứ Năm từ 12 giờ trưa đến 20 giờ; các ngày thứ Tư, thứ Sáu, thứ Bảy và Chủ nhật mở từ 10 giờ đến 18 giờ. Một số lịch cũ ghi giờ mở 10–18 giờ và nghỉ thêm ngày thứ Sáu cuối cùng của tháng, nên hướng dẫn viên cần kiểm tra lại lịch chính thức trước mỗi chuyến đi.",
            "Về giá vé, mức tham khảo là khoảng 300 rúp cho người lớn, khoảng 150 rúp cho học sinh, sinh viên và người hưu trí; các suất tham quan có hướng dẫn viên thuyết minh thường bắt đầu từ 500 rúp. Đây là mức giá rất phải chăng so với giá trị lịch sử mà du khách nhận được, và cũng nhẹ nhàng cho ngân sách của các đoàn khách đông người khi muốn thuê thêm dịch vụ thuyết minh. Vé và các dịch vụ đi kèm có thể thay đổi theo từng năm, vì vậy hướng dẫn viên nên xác nhận lại mức giá mới nhất trên trang chính thức của bảo tàng trước khi báo giá cho khách.",
            "Một chi tiết đặc trưng của các bảo tàng - nhà ở tại Nga mà du khách Việt cần được nhắc trước: khi vào trong nhà, mọi người phải mang một lớp bọc giày bằng vải hoặc nilon gọi là bahily, nhằm bảo vệ lớp sàn gỗ parquet lịch sử. Việc này hoàn toàn bình thường và thể hiện sự trân trọng đối với di sản, nên hướng dẫn viên hãy dặn khách chuẩn bị tâm lý và hợp tác vui vẻ, tránh bỡ ngỡ khi đến nơi.",
            "Bên trong, du khách sẽ đi qua chuỗi phòng ở, phòng làm việc, phòng ăn, phòng trẻ và phòng khách, mỗi nơi kể một mảnh chuyện đời của gia đình. Không khí trong nhà tĩnh lặng, ấm cúng và rất «đời», khác hẳn sự nguy nga lạnh lẽo của các cung điện. Chính sự gần gũi ấy khiến nhiều người xúc động, như thể được mời vào làm khách trong một buổi chiều Moscow xưa, ngồi lại bên bàn ăn hay bên phím đàn cùng gia đình văn hào.",
            "Đừng bỏ qua khu vườn bao quanh nhà – nơi lý tưởng để tản bộ, hít thở và hình dung cảnh Tolstoy gánh nước hay bổ củi mỗi sáng. Mùa hè, vườn xanh mát với cây trái trĩu cành; mùa thu lá vàng trải lối; còn mùa đông tuyết phủ lại mang đến một vẻ đẹp trầm mặc rất Nga. Tuỳ mùa mà hướng dẫn viên có thể gợi ý khách dành thêm thời gian thư thả ngoài vườn, coi đó như phần vĩ thanh êm dịu của chuyến thăm.",
        ]},
        {"heading": "Mẹo tham quan", "paras": [
            "Để chuyến thăm trọn vẹn, nên chọn khung giờ sáng sớm trong tuần, khi bảo tàng vắng khách và ánh sáng tự nhiên rọi vào các căn phòng đẹp nhất. Vào mùa cao điểm hè, các đoàn nên liên hệ đặt trước suất tham quan và hướng dẫn viên nói tiếng Anh (nếu cần), bởi không gian nhà gỗ khá nhỏ, mỗi lượt chỉ đón được số lượng khách hạn chế để bảo vệ hiện vật và giữ trải nghiệm yên tĩnh. Nếu đi vào cuối tuần, hãy lường trước rằng lượng khách trong nước có thể đông hơn, nên việc có mặt ngay khi bảo tàng vừa mở cửa sẽ giúp đoàn thong thả hơn nhiều.",
            "Về thanh toán, cần lưu ý rằng thẻ ngân hàng quốc tế phát hành ngoài nước Nga hầu như không dùng được. Du khách nên chuẩn bị sẵn tiền mặt rúp hoặc thẻ nội địa MIR để mua vé, thuê thuyết minh và mua đồ lưu niệm. Đây là điều hướng dẫn viên nên dặn khách ngay từ khâu chuẩn bị hành trình, để tránh tình huống lúng túng khó xử ngay tại quầy vé của bảo tàng.",
            "Một mẹo hay là kết hợp Khamovniki với bảo tàng văn học chính của hệ thống Tolstoy trên phố Prechistenka số 11, cách đó khoảng một cây số rưỡi. Nếu điền trang Khamovniki cho ta thấy Tolstoy «sống» như thế nào, thì bảo tàng Prechistenka lại trưng bày bản thảo, thư từ và tư liệu về sự nghiệp của ông – hai nơi bổ khuyết cho nhau rất đẹp, giúp khách hiểu trọn vẹn cả con người lẫn sự nghiệp của văn hào.",
            "Trong nhà, du khách nên đi nhẹ, nói khẽ và tuân thủ hướng tham quan một chiều để bảo vệ hiện vật. Nếu muốn chụp ảnh, hãy hỏi nhân viên về quy định và cân nhắc tắt đèn flash, vì ánh sáng mạnh có thể gây hại cho giấy dán tường, vải vóc và đồ gỗ đã hơn trăm tuổi. Việc giữ ý này không chỉ bảo vệ di sản mà còn giúp mọi du khách khác cùng có được một trải nghiệm trọn vẹn.",
            "Về trang phục, do phải đi bộ cả trong nhà lẫn ngoài vườn, nên chọn giày thoải mái; mùa đông cần mặc ấm và tính đến việc gửi áo khoác dày ở quầy giữ đồ. Sau cùng, để bài thuyết minh thêm cuốn hút, hướng dẫn viên nên chuẩn bị vài giai thoại đắt giá – như chuyện bá tước đóng giày hay chuyện học đi xe đạp ở tuổi sáu mươi bảy – rồi kể ngay tại chính căn phòng gắn với câu chuyện đó. Cách kể chuyện tại chỗ như vậy luôn để lại ấn tượng mạnh hơn nhiều so với việc liệt kê thông tin khô khan, và giúp du khách ghi nhớ Khamovniki như một trải nghiệm sống động chứ không chỉ là một điểm dừng chân.",
        ]},
        {"heading": "Khám phá xung quanh", "paras": [
            "Khamovniki nằm giữa một khu vực giàu điểm tham quan, rất tiện để thiết kế lịch trình nửa ngày. Ngay gần đó, cách chừng bốn trăm mét, là Nhà thờ Thánh Nikolai ở Khamovniki – một ngôi thánh đường lộng lẫy xây trong các năm 1679–1682, mang đậm phong cách kiến trúc sloboda Nga với sắc đỏ, trắng và những chi tiết trang trí cầu kỳ. Đây chính là trái tim tín ngưỡng của khu phố thợ dệt xưa, và là một trong những nhà thờ đẹp nhất Moscow.",
            "Cách khoảng năm trăm mét là khu Devichye Pole (Cánh đồng Trinh nữ), ngày nay là khuôn viên các cơ sở y khoa của Đại học Tổng hợp Moscow. Vùng đất này gắn với nhiều toà nhà bệnh viện và trường y cổ kính, cho thấy một Khamovniki không chỉ là nơi ở của văn hào mà còn là cái nôi của giáo dục và y học Moscow – một lớp lịch sử ít du khách để ý tới nhưng rất đáng nhắc đến. Những hàng cây cổ thụ và các toà nhà cũ quanh Devichye Pole cũng tạo nên khung cảnh dễ chịu để dạo bộ, nhất là khi đoàn còn dư chút thời gian trước hoặc sau giờ tham quan điền trang.",
            "Đi thêm chừng sáu đến tám trăm mét về phía Vành đai Vườn, du khách sẽ tới khu vực ga Park Kultury. Ngay bên kia là cầu Krymsky duyên dáng bắc qua sông Moskva và công viên nghệ thuật ngoài trời Muzeon với hàng trăm bức tượng, trong đó có nhiều tượng từ thời Xô-viết được di dời về. Đây là không gian dạo bộ lý tưởng để nối tiếp chuyến thăm điền trang bằng một buổi chiều thư giãn bên sông.",
            "Với người yêu văn học, bảo tàng Tolstoy chính trên phố Prechistenka (cách khoảng một cây số rưỡi) là điểm ghép đôi hoàn hảo. Ở hướng tây nam, cũng chừng một cây số rưỡi, là Tu viện Novodevichy cùng nghĩa trang nổi tiếng – một Di sản Thế giới được UNESCO công nhận, nơi an nghỉ của nhiều danh nhân Nga và là một trong những quần thể tu viện đẹp và thơ mộng nhất thủ đô.",
            "Bên kia sông, cách chừng một ki-lô-mét rưỡi, là Công viên Gorky trứ danh – lá phổi xanh và không gian giải trí sôi động bậc nhất Moscow. Nhờ mật độ điểm đến dày đặc trong bán kính nhỏ như vậy, hướng dẫn viên có thể linh hoạt kết hợp Khamovniki với nhà thờ cổ, tu viện di sản, bảo tàng văn học và công viên ven sông thành một hành trình vừa sâu sắc về văn hoá vừa thư giãn về tinh thần.",
        ]},
        {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
            "Chuyện mua nhà năm 1882 đã kèm theo một giai thoại đáng nhớ. Để chứng minh chất lượng gỗ của ngôi nhà, ông chủ cũ Arnautov đã cạy tung lớp ván ốp ngoài rồi vung rìu bổ thẳng vào tường gỗ, đắc chí khoe rằng những khúc gỗ này đã «hoá thành xương» – rắn chắc đến mức lưỡi rìu cũng khó phạt sâu vào. Màn quảng cáo có một không hai ấy hẳn đã góp phần thuyết phục vị văn hào vốn nổi tiếng khó tính chịu xuống tiền. Giai thoại nhỏ này thường khiến du khách bật cười, đồng thời hé lộ một sự thật: chính chất gỗ bền chắc ấy đã giúp ngôi nhà đứng vững qua hơn hai thế kỷ để đến được với chúng ta ngày hôm nay.",
            "Giai thoại được yêu thích nhất kể về vị bá tước đi đóng giày. Say mê lao động chân tay, Tolstoy tự tay đóng một đôi ủng tặng nhà thơ Afanasy Fet. Tương truyền, Fet đã trân trọng xếp đôi ủng ấy lên giá sách, ngay cạnh bộ tuyển tập tác phẩm của Tolstoy, và gọi vui đó là «tập 13» trong sự nghiệp của nhà văn – một lời khen hóm hỉnh mà cũng đầy trìu mến, nói lên tình bạn văn chương giữa hai con người tài hoa.",
            "Tolstoy chia một ngày của mình thành bốn «lượt» (tiếng Nga: upryazhka, vốn chỉ ca kéo xe của một con ngựa): một lượt cho lao động chân tay, một lượt cho lao động trí óc, một lượt cho nghề thủ công và một lượt cho giao tiếp xã hội. Mỗi sáng, ông đích thân ra giếng gánh nước về nhà, bất kể mình là bá tước hay là đại văn hào lừng danh khắp châu Âu. Đó là kỷ luật tự thân mà ông theo đuổi đến tận cuối đời.",
            "Nghịch lý lớn nhất của ngôi nhà là hình ảnh một bá tước ăn chay, sống khắc khổ như nông dân, lại cư ngụ trong dinh thự mười sáu phòng giữa vùng nhà máy khói bụi. Trong bữa ăn, ông thường dùng riêng vài món đạm bạc – khoai tây nghiền, hai quả trứng và một quả táo nướng – trong khi cả gia đình dùng những món thịnh soạn hơn. Vậy mà cũng chính dưới mái nhà ấy, tiếng đàn của Rachmaninoff và Scriabin vang lên, giọng ca Chaliapin ngân nga, còn Chekhov và Gorky đàm đạo ở phòng bên.",
            "Không phải mọi câu chuyện đều nghiêm trang: lũ trẻ trong nhà từng nghịch ngợm trượt xuống chiếc cầu thang lớn bằng những chiếc khay bưng thức ăn, biến không gian trang nghiêm thành sân chơi. Cảm động hơn cả là chuyện Tolstoy tập đi xe đạp ở tuổi sáu mươi bảy, không lâu sau nỗi đau mất bé Vanechka – như thể ông tìm trong chuyển động và thăng bằng một cách để nguôi ngoai. Căn phòng của cậu bé, với con ngựa bập bênh và những quyển vở tập viết, đến nay vẫn được giữ nguyên, lặng lẽ kể câu chuyện buồn nhất và cũng người nhất của ngôi nhà.",
        ]},
    ],
    "highlights": [
        "Ngôi nhà gỗ hai tầng – mái nhà ở Moscow của Tolstoy suốt mười chín mùa đông (1882–1901), nay là bảo tàng.",
        "Nơi ra đời tiểu thuyết «Phục sinh» cùng gần một trăm tác phẩm khác của đại văn hào.",
        "Phòng làm việc với bàn viết lan can gỗ và chiếc ghế bị cưa ngắn chân dành cho người cận thị nặng.",
        "Bộ đồ nghề và những đôi ủng do chính tay bá tước Tolstoy đóng – kể cả đôi tặng nhà thơ Fet.",
        "Căn phòng trẻ thơ của bé Vanechka được giữ nguyên vẹn, đầy xúc động.",
        "Salon âm nhạc nơi Rachmaninoff, Scriabin và Chaliapin từng trình diễn bên đàn Becker.",
        "Khu vườn gần một hecta – ốc đảo xanh giữa vùng công nghiệp Khamovniki xưa.",
        "Một trong những bảo tàng văn học lâu đời nhất nước Nga (1921), mở lại sau trùng tu ngày 3/1/2025.",
    ],
    "images": [
        img("Ge Tolstoy.jpg", "Chân dung Lev Tolstoy bên bàn viết, do hoạ sĩ Nikolai Ge vẽ năm 1884 - đúng giai đoạn ông sống ở Khamovniki."),
        img("Tolstoy by Repin 1901.jpg", "Chân dung Tolstoy của danh hoạ Ilya Repin, 1901."),
        img("L.N.Tolstoy Prokudin-Gorsky.jpg", "Ảnh màu hiếm hoi chụp Tolstoy (Prokudin-Gorsky, 1908)."),
        img("Family of L. Tolstoy.jpg", "Đại gia đình Tolstoy - mười người con từng sống trong ngôi nhà."),
        img("Moscow, Lva Tolstogo 14,14A Aug 2008 01.JPG", "Phố Lev Tolstoy (Ulitsa Lva Tolstogo) ở Khamovniki, nơi toạ lạc bảo tàng-điền trang."),
    ],
    "references": [
        {"title": "Bảo tàng chính thức — Điền trang «Khamovniki» (Bảo tàng Quốc gia L.N. Tolstoy)", "url": "https://tolstoymuseum.ru/about/museum-and-branches/khamovniki/"},
        {"title": "Wikipedia (tiếng Nga) — Музей-усадьба Льва Толстого в Хамовниках", "url": "https://ru.wikipedia.org/wiki/Музей-усадьба_Льва_Толстого_в_Хамовниках"},
        {"title": "Wikipedia (tiếng Anh) — Khamovniki", "url": "https://en.wikipedia.org/wiki/Khamovniki"},
        {"title": "Rusmania — Lev Tolstoy Estate-Museum in Khamovniki", "url": "https://rusmania.com/central/moscow-federal-city/moscow/khamovniki/beyond-the-garden-ring-around-devichye-pole/lev-tolstoy-estate-museum-in-khamovniki"},
        {"title": "DiscoverMoscow — Leo Tolstoy Estate and Museum in Khamovniki", "url": "https://discovermoscow.com/en/places/muzej/muzej-usadba-l-n-tolstogo-v-hamovnikah/"},
        {"title": "Uznai Moskvu (um.mos.ru) — Bảo tàng-điền trang L.N. Tolstoy", "url": "https://um.mos.ru/museums/muzey_usadba_lva_tolstogo_v_khamovnikakh/"},
        {"title": "Moskvich Mag — Dom nedeli: usadba Lva Tolstogo v Khamovnikakh", "url": "https://moskvichmag.ru/gorod/dom-nedeli-usadba-lva-tolstogo-v-hamovnikah/"},
    ],
    "sources": [
        "Thông tin chính thức về điền trang «Khamovniki» (chi nhánh của Bảo tàng Quốc gia L. N. Tolstoy): địa chỉ số 21 phố Lev Tolstoy, giờ mở cửa, giá vé, quá trình trùng tu và ngày mở cửa lại 3/1/2025 — trang chính thức của bảo tàng (tolstoymuseum.ru).",
        "Lịch sử ngôi nhà (dựng năm 1805, sống sót qua hoả hoạn 1812, các đời chủ Meshchersky và Arnautov, Tolstoy mua năm 1882 với giá khoảng 36.000 rúp), quá trình cải tạo và danh sách tác phẩm sáng tác tại đây — Wikipedia tiếng Nga về Bảo tàng - Điền trang Lev Tolstoy ở Khamovniki.",
        "Bối cảnh khu phố Khamovniki (sloboda thợ dệt vải lanh, thợ được đưa từ Tver năm 1624, xưởng vải buồm thời Pyotr I năm 1708, Nhà thờ Thánh Nikolai 1679–1682) — Wikipedia tiếng Anh về Khamovniki.",
        "Tiểu sử điền trang, số phòng, khu vườn, các công trình phụ và bối cảnh gia đình — Rusmania, Lev Tolstoy Estate-Museum in Khamovniki.",
        "Thông tin tham quan, mô tả nội thất và các phòng tiêu biểu — DiscoverMoscow, Leo Tolstoy Estate and Museum in Khamovniki.",
        "Chi tiết hiện vật và đồ dùng cá nhân (bàn viết, ghế cưa chân, đồ nghề đóng giày, xe đạp, phòng của bé Vanechka) cùng giá trị bảo tàng — Uznai Moskvu (um.mos.ru).",
        "Những giai thoại và chi tiết đời sống (chuyện bổ tường bằng rìu, đôi ủng tặng Fet, chia ngày thành bốn «lượt», các buổi tối âm nhạc, lời than về nhà máy) — Moskvich Mag, «Dom nedeli: usadba Lva Tolstogo v Khamovnikakh».",
        "Các dữ kiện tổng hợp (toạ độ, ga metro Park Kultury, giám đốc đầu tiên Valentin Bulgakov, giám đốc đương nhiệm Vladimir Tolstoy, quy định mang bọc giày bahily, các điểm lân cận như Devichye Pole, cầu Krymsky, Muzeon, Novodevichy, Công viên Gorky) được đối chiếu từ các nguồn nêu trên và kiến thức nền chung.",
    ],
}

json.dump(
    doc,
    open("/sessions/stoic-gallant-fermi/mnt/russia-tourism/_incoming/doc_tolstoy-khamovniki-estate.json", "w", encoding="utf-8"),
    ensure_ascii=False,
    indent=1,
)
print("OK words=", sum(len(p.split()) for s in doc["sections"] for p in s["paras"]))
for s in doc["sections"]:
    print("  -", s["heading"], ":", len(s["paras"]), "paras,", sum(len(p.split()) for p in s["paras"]), "words")
print("sections=", len(doc["sections"]), "highlights=", len(doc["highlights"]),
      "images=", len(doc["images"]), "refs=", len(doc["references"]), "sources=", len(doc["sources"]))
