# -*- coding: utf-8 -*-
"""Builder: doc_ryabushinsky-mansion.json — noi dung nguyen goc tieng Viet."""
import json

doc = {
 "slug": "ryabushinsky-mansion",
 "name_vi": "Dinh thự Ryabushinsky (Ria-bu-sin-xki) – Nhà-Bảo tàng Gorky",
 "name_ru": "Особняк Рябушинского",
 "name_en": "Ryabushinsky Mansion (Gorky House-Museum)",
 "subtitle": "Một kiệt tác Tân nghệ thuật của kiến trúc sư Fyodor Shekhtel, nơi cầu thang cẩm thạch cuộn mình như con sóng biển; đồng thời là mái nhà cuối cùng ở Moscow của đại văn hào Maxim Gorky và là chốn cất giấu một nhà nguyện bí mật của phái Tín đồ Cũ.",
 "sections": [
  {"heading": "Giới thiệu chung", "paras": [
   "Dinh thự Ryabushinsky, ngày nay quen thuộc với du khách dưới tên gọi Nhà-Bảo tàng Maxim Gorky, là một trong những công trình quyến rũ và nhiều tầng ý nghĩa bậc nhất ở ngay giữa lòng Moscow. Toà biệt thự nhỏ này do kiến trúc sư lừng danh Fyodor Osipovich Shekhtel thiết kế và dựng lên trong khoảng thời gian từ năm 1900 đến năm 1903, dành cho nhà tài phiệt ngân hàng trẻ tuổi Stepan Pavlovich Ryabushinsky. Giới nghiên cứu kiến trúc xem đây là một trong những tác phẩm khai sinh và tiêu biểu nhất của phong cách Tân nghệ thuật Nga, mà người Nga quen gọi là Style Moderne. Chỉ cần đứng trước ngôi nhà vài phút, người ta đã cảm nhận được rằng đây không phải một dinh thự thông thường, mà là một tuyên ngôn nghệ thuật được kết tinh bằng gạch men, đá cẩm thạch và kính màu.",
   "Sức hấp dẫn đặc biệt của công trình nằm ở chỗ nó chứa đựng hai tâm hồn trong cùng một mái nhà. Ở lớp vỏ ngoài và toàn bộ ngôn ngữ trang trí, đây là một khúc ca lãng mạn của trường phái Art Nouveau châu Âu đầu thế kỷ 20: từ tay nắm cửa hình cá ngựa, sàn gỗ uốn lượn như sóng nước, chiếc đèn hình con sứa cho đến dải khảm hoa diên vĩ chạy quanh mái nhà, mọi chi tiết đều thuộc về một câu chuyện thị giác thống nhất. Ở lớp nghĩa thứ hai, kể từ mùa xuân năm 1931, ngôi nhà trở thành nơi cư ngụ của Maxim Gorky, dần biến thành một thứ câu lạc bộ văn chương không chính thức, nơi những định hướng lớn của cả nền văn học Xô-viết từng được bàn thảo và định đoạt.",
   "Chính sự chồng lớp giữa vẻ đẹp tư sản tinh tế thời trước cách mạng và vai trò chính trị – văn hoá thời Xô-viết đã khiến ngôi nhà trở thành một điểm đến hiếm có. Đây vừa là một bảo tàng tưởng niệm nhà văn, vừa là một hiện vật kiến trúc sống động mà bản thân toà nhà mới thực sự là ngôi sao chính. Hiện nay công trình được xếp hạng di sản văn hoá cấp liên bang của nước Nga, đồng thời là thành viên của mạng lưới quốc tế Iconic Houses – nơi quy tụ những ngôi nhà mang tính biểu tượng của nền kiến trúc thế giới. Với các đoàn khách Việt Nam, đây là một điểm dừng lý tưởng để vừa thưởng thức nghệ thuật, vừa lắng nghe những trang sử đầy kịch tính của nước Nga trong thế kỷ 20.",
   "Điều mà mỗi hướng dẫn viên nên khắc ghi là ý tưởng xuyên suốt của Shekhtel: ông thiết kế toàn bộ ngôi nhà như một tác phẩm nghệ thuật tổng thể, mà tiếng Đức gọi là Gesamtkunstwerk. Mỗi tay nắm, mỗi ô kính, mỗi bậc thang đều là một mắt xích trong một câu chuyện ngụ ngôn lớn, dẫn dắt người xem đi từ đáy đại dương lên tới tận bầu trời. Trong tập tài liệu này, chúng ta sẽ lần lượt tìm hiểu vị trí và cách di chuyển, lịch sử hình thành, đặc điểm kiến trúc, những điểm nhấn nổi bật, ý nghĩa văn hoá, trải nghiệm tham quan, các mẹo hữu ích, những điểm đến quanh vùng và sau cùng là kho giai thoại thú vị gắn với ngôi nhà lạ lùng này."
  ]},
  {"heading": "Vị trí & cách di chuyển", "paras": [
   "Dinh thự Ryabushinsky toạ lạc tại địa chỉ phố Malaya Nikitskaya số 6/2, khối nhà số 5, thuộc quận Presnensky ở khu trung tâm lịch sử của Moscow. Toạ độ định vị của công trình vào khoảng 55.758154 vĩ độ bắc và 37.596363 kinh độ đông, ngay sát khu vực Cổng Nikitsky mà tiếng Nga gọi là Nikitskie Vorota. Đây là một góc phố yên tĩnh nhưng cực kỳ đắc địa, chỉ cách vành đai đại lộ trung tâm vài bước chân và nằm gọn trong bán kính đi bộ tới hàng loạt điểm tham quan trứ danh khác của thủ đô. Vị trí này khiến ngôi nhà rất dễ ghép vào một buổi đi bộ khám phá khu phố cổ quanh đại lộ Tverskaya.",
   "Về phương tiện công cộng, cách thuận tiện nhất là dùng tàu điện ngầm Moscow, hệ thống metro nổi tiếng vừa đẹp vừa hiệu quả. Ga gần nhất là Arbatskaya, cách ngôi nhà khoảng một ki-lô-mét, tương ứng chừng mười hai đến mười lăm phút đi bộ. Ngoài ra, du khách có thể xuống ở cụm ga Quảng trường Pushkin gồm Pushkinskaya, Tverskaya và Chekhovskaya, rồi thong thả đi bộ chừng mười lăm phút; hoặc chọn cụm ga Barrikadnaya và Krasnopresnenskaya ở hướng còn lại, cũng chỉ mất khoảng mười đến mười lăm phút đi bộ. Dù xuất phát từ hướng nào, quãng đường bộ đều đi qua những con phố rợp bóng cây và nhiều dinh thự cổ kính, nên bản thân việc đi bộ cũng đã là một phần thú vị của trải nghiệm.",
   "Có một chi tiết quan trọng mà hướng dẫn viên cần nhớ để không lúng túng trước cửa: lối vào bảo tàng ngày nay không phải là cổng chính hào nhoáng nhìn thẳng ra phố, mà là lối cửa phụ trước kia dành cho người phục vụ, nằm ở phía đường Spiridonovka. Cổng chính lộng lẫy với mái hiên kiểu hang động và dải khảm hoa diên vĩ chủ yếu để chiêm ngưỡng từ bên ngoài, còn khách tham quan sẽ đi vòng sang lối khiêm tốn hơn để vào trong. Việc biết trước điều này sẽ giúp cả đoàn không mất thời gian loay hoay tìm cửa, đặc biệt vào những ngày trời lạnh hay lúc đông người.",
   "Với các đoàn khách đi xe riêng, tài xế cần lưu ý rằng khu vực trung tâm Moscow có nhiều phố một chiều và quy định đỗ xe khá nghiêm ngặt, nên thường sẽ thả khách ở gần Cổng Nikitsky rồi hẹn đón tại một điểm thuận tiện gần đó. Do bản thân ngôi nhà không có bãi đỗ riêng cho xe lớn, phương án tối ưu vẫn là kết hợp metro với đi bộ, hoặc thả khách rồi cho xe chờ ở vòng ngoài. Nhìn chung, đây là một điểm đến rất thân thiện với người đi bộ, và cách tiếp cận đẹp nhất chính là tản bộ dọc phố Malaya Nikitskaya để ngôi nhà dần hiện ra sau những tán cây, đúng như dụng ý mà kiến trúc sư từng mong muốn khi lùi công trình vào trong khu vườn."
  ]},
  {"heading": "Lịch sử hình thành và phát triển", "paras": [
   "Muốn hiểu ngôi nhà, trước hết cần hiểu dòng họ đã đặt xây nó. Nhà Ryabushinsky là một trong những gia tộc thương gia lừng lẫy nhất nước Nga cuối thế kỷ 19 đầu thế kỷ 20, xuất thân từ tầng lớp nông dân rồi vươn lên gây dựng cả một đế chế dệt may hùng mạnh. Không dừng ở dệt may và ngân hàng, gia tộc này còn ghi dấu ấn tiên phong trong công nghiệp: họ sáng lập nhà máy sản xuất ô tô đầu tiên của nước Nga, mang tên AMO, vào năm 1916. Người anh em Dmitry Ryabushinsky thì lập ra Viện Khí động học Kuchino, một trung tâm nghiên cứu khoa học đi trước thời đại. Có thể nói, dựng nên ngôi nhà này là một gia đình vừa giàu có vừa cháy bỏng khát vọng hiện đại hoá đất nước.",
   "Chủ nhân trực tiếp của dinh thự là Stepan Pavlovich Ryabushinsky, sinh năm 1874, một nhà tài phiệt ngân hàng và nhà công nghiệp. Ông đồng thời là một tín đồ của phái Tín đồ Cũ – nhánh Chính thống giáo bảo thủ từng bị nhà nước Nga đàn áp suốt nhiều thế kỷ – và là một trong những nhà sưu tầm, phục chế thánh tượng cổ, tức các bức icon của Nga, nổi tiếng bậc nhất thời bấy giờ. Chính niềm say mê tôn giáo và nghệ thuật cổ này đã để lại dấu ấn sâu đậm lên ngôi nhà, từ bộ sưu tập thánh tượng đồ sộ cho tới nhà nguyện bí mật mà chúng ta sẽ nói tới ở phần sau.",
   "Ngôi nhà được khởi công và hoàn thành trong khoảng từ năm 1900 đến năm 1903, một số tài liệu ghi gọn là 1900 đến 1902; gia đình Ryabushinsky chính thức dọn vào sống từ năm 1903. Người được chọn mặt gửi vàng là Fyodor Shekhtel, khi ấy đang ở đỉnh cao sáng tạo. Công trình mang phong cách Tân nghệ thuật Moscow thời kỳ đầu, chịu ảnh hưởng rõ rệt từ kiến trúc sư Joseph Maria Olbrich ở Darmstadt và làn sóng Art Nouveau phương Tây, nhưng đồng thời được Shekhtel bản địa hoá bằng những mô-típ và biểu tượng rất riêng của tâm hồn Nga. Chỉ trong vài năm, một kiệt tác đã mọc lên giữa lòng thủ đô.",
   "Bước ngoặt lớn đến vào năm 1917. Cách mạng tháng Mười nổ ra, gia đình Ryabushinsky phải rời bỏ tất cả và lưu vong ra nước ngoài, còn ngôi nhà thì bị quốc hữu hoá. Từ đó, toà biệt thự lần lượt trải qua nhiều công năng đến chóng mặt: nơi đặt bộ phận cấp thị thực của cơ quan đối ngoại trong giai đoạn 1917 đến 1919, rồi trụ sở của Nhà xuất bản Quốc gia Gosizdat từ năm 1919 đến năm 1921. Đáng chú ý nhất, từ năm 1921 đến năm 1925, nơi đây là trụ sở của Hội Phân tâm học Nga cùng một nhà trẻ thực nghiệm theo phương pháp phân tâm học do bà Vera Schmidt điều hành, với học trò gồm cả con em của giới tinh hoa Xô-viết. Sau đó, ngôi nhà được giao cho VOKS, hội phụ trách quan hệ văn hoá với nước ngoài.",
   "Chương quan trọng nhất mở ra ngày 14 tháng 5 năm 1931, khi đại văn hào Maxim Gorky dọn về đây sống cho tới ít lâu trước khi qua đời vào ngày 18 tháng 6 năm 1936. Đây chính là nơi cư trú lâu dài nhất của ông tại Moscow. Trong Thế chiến thứ hai, từ năm 1942 đến năm 1945, nhà văn Aleksei N. Tolstoy từng sống trong một dãy nhà phụ bên cạnh, nay cũng đã trở thành một bảo tàng nhỏ. Ngôi nhà được chuyển giao cho Viện Hàn lâm Khoa học Liên Xô năm 1961, và bảo tàng chính thức mở cửa đón khách vào ngày 28 tháng 5 năm 1965, trực thuộc Viện Văn học Thế giới mang tên A. M. Gorky, tức IMLI RAN, cho tới tận ngày nay."
  ]},
  {"heading": "Kiến trúc & đặc điểm nổi bật", "paras": [
   "Linh hồn kiến trúc của ngôi nhà là Fyodor Osipovich Shekhtel, sống từ năm 1859 đến năm 1926, một trong những bậc thầy khai sáng của phong cách Tân nghệ thuật Nga. Trong sự nghiệp đồ sộ của mình, ông để lại nhiều công trình danh tiếng ở Moscow, nhưng dinh thự Ryabushinsky thường được xem là tác phẩm chữ ký, nơi tài năng của ông toả sáng trọn vẹn nhất. Shekhtel không chỉ vẽ mặt tiền, mà còn đích thân thiết kế gần như mọi thứ bên trong, từ cầu thang, đèn, kính màu cho tới tay nắm cửa, biến ngôi nhà thành một tổng thể nghệ thuật liền mạch không một chi tiết thừa.",
   "Điểm độc đáo đầu tiên nằm ở cách bố trí trên khu đất. Thay vì áp sát ngôi nhà ra mặt phố như thông lệ, Shekhtel cho lùi toà biệt thự vào trong một khu vườn, chỉ đẩy phần hiên cổng ra sát chỉ giới đường phố. Cách xử lý này tạo ra một khoảng đệm không khí, một quãng lặng thị giác giúp ngôi nhà được thở và khoe trọn vẹn hình khối. Quan trọng hơn, ông thiết kế công trình theo nguyên tắc từ trong ra ngoài: cầu thang lớn ở trung tâm chính là hạt nhân bố cục, và mọi căn phòng đều toả ra chung quanh nó như những cánh hoa xoay quanh nhuỵ.",
   "Mặt tiền của ngôi nhà là một bản hoà tấu của sự bất đối xứng có chủ ý. Tường ngoài ốp gạch men tráng màu hồng phớt, đường mái nhấp nhô không cân đối, còn các ô cửa sổ thì mỗi tầng một kích thước và hình dáng khác nhau, nhỏ dần khi lên cao để đánh lừa thị giác, khiến ngôi nhà trông cao hơn thực tế. Trên cùng, chạy quanh đỉnh tường là một dải khảm majolica rực rỡ, vẽ những khóm hoa diên vĩ và phong lan đang nở bung trên nền trời xanh điểm mây. Đó chính là chi tiết khiến bao du khách phải ngước nhìn và trầm trồ.",
   "Càng nhìn kỹ, người ta lại càng phát hiện nhiều dụng công tinh vi. Lan can ban công được tạo hình như những lớp vảy cá xếp chồng lên nhau, còn các song sắt bảo vệ cửa sổ thì uốn cong mềm mại như những mầm cây đang vươn lên. Rải rác trên bề mặt là những hoạ tiết xoắn ốc mà nhiều người ví như đôi mắt cú mèo, tạo cảm giác ngôi nhà đang lặng lẽ dõi theo khách qua đường. Tất cả những yếu tố ấy hợp lại khiến mặt tiền không đơn thuần là lớp áo trang trí, mà là một trang sách mở, kể chuyện thiên nhiên bằng ngôn ngữ của gạch, sắt và men màu.",
   "Ẩn sau vẻ đẹp nghệ thuật là một tư duy kỹ thuật rất tiên tiến so với thời đại. Ngôi nhà được lắp một hệ thống thông gió và điều hoà không khí sơ khai, đưa không khí luân chuyển qua các lò sưởi và một tấm lưới thông hơi đặt ngay dưới chân cầu thang, giúp không gian luôn thoáng đãng và ấm áp. Dưới tầng hầm là gian bếp, nối lên phòng ăn bằng một chiếc thang nâng thức ăn, để các món nóng có thể được chuyển lên bàn tiệc nhanh gọn mà người phục vụ không phải bê đỡ qua nhiều bậc thang. Những chi tiết này cho thấy Shekhtel và gia chủ không chỉ theo đuổi cái đẹp mà còn rất coi trọng sự tiện nghi trong đời sống hằng ngày."
  ]},
  {"heading": "Những điểm nhấn không thể bỏ lỡ", "paras": [
   "Nếu chỉ được nhớ một chi tiết duy nhất về ngôi nhà, đó chắc chắn phải là cầu thang sóng. Được đúc bằng đá cẩm thạch nhân tạo màu xám pha xanh lục và mài nhẵn bóng, lan can cầu thang được tạo hình như một con sóng biển đang cuộn mình, tượng trưng cho sự vận động bất tận của tự nhiên. Đây chính là trung tâm bố cục của cả ngôi nhà, điểm mà mọi ánh nhìn đều bị hút về. Ở đỉnh con sóng, Shekhtel đặt một chiếc đèn bằng kính và đồng có hình dáng như một con sứa biển đang buông những xúc tu; thế nhưng khi nhìn từ trên cao xuống, nhiều người lại thấy nó giống hình một con rùa. Chỉ riêng chi tiết này thôi đã xứng đáng cho cả chuyến tham quan.",
   "Toàn bộ tầng trệt được dàn dựng như một thế giới dưới đáy đại dương. Đá cẩm thạch xám lục, những bức tường phủ sắc xanh, sàn gỗ ghép theo hoạ tiết gợn sóng, tay nắm cửa được đúc thành hình những chú cá ngựa, cùng thứ ánh sáng được lọc dịu qua kính màu, tất cả hợp lại tạo cảm giác như đang thong thả bước đi dưới mặt nước. Đây là một thủ pháp sân khấu đầy chủ ý, mà nhiều nhà nghiên cứu liên tưởng tới cảnh trí dưới nước trong vở opera «Sadko» của nhà soạn nhạc Rimsky-Korsakov. Du khách nên chậm bước ở khu vực này để cảm nhận cách ánh sáng và màu sắc cùng nhau kể chuyện.",
   "Nối liền các tầng nhà là một cây cột cao, được Shekhtel ngầm ví như Cây Tri thức trong Kinh Thánh. Trên đầu cột chạm khắc bốn bông hoa loa kèn tượng trưng cho cái Thiện, xen lẫn những con kỳ giông và loài bò sát tượng trưng cho cái Ác, gói trọn cuộc giằng co muôn thuở giữa hai mặt của đời sống. Cây cột này còn là chìa khoá để đọc toàn bộ ngôi nhà theo ba tầng ý nghĩa: tầng trệt là thế giới dưới nước, tầng hai là cõi không khí và trần gian, còn tầng trên cùng thì vươn tới cõi trời. Cả ngôi nhà, vì thế, là một hành trình biểu tượng đi từ đáy biển sâu thẳm lên tới tận thiên đường.",
   "Kính màu là một nhân vật chính khác trong ngôi nhà. Shekhtel tự tay thiết kế những ô kính màu cho phòng ăn, phòng làm việc và đặc biệt là một ô cửa vẽ phong cảnh đặt ở sảnh vào; điều kỳ diệu là bức tranh kính ấy đổi màu tuỳ theo góc đứng và hướng nhìn của người xem. Những khoảng kính cao vút còn có nhiệm vụ dẫn ánh sáng tự nhiên rót xuống lồng cầu thang, khiến con sóng đá như lấp lánh và chuyển động theo từng thời khắc trong ngày. Hướng dẫn viên nên nhắc khách thử đứng ở vài vị trí khác nhau để tận mắt chứng kiến trò chơi ánh sáng biến ảo này.",
   "Hai điểm nhấn cuối cùng thuộc về hai chủ nhân khác nhau của ngôi nhà. Ẩn trên tầng áp mái là nhà nguyện bí mật của phái Tín đồ Cũ, một căn phòng cầu nguyện có mái vòm được giấu kín, không thể nhìn thấy từ ngoài phố, với những bức tường vẽ đầy hoạ tiết ngôi sao. Còn dấu ấn của Gorky đậm nét nhất chính là thư viện đồ sộ với khoảng mười hai nghìn cuốn sách, xếp trong bốn mươi bốn tủ sách đóng riêng, cùng bộ sưu tập tượng netsuke tí hon của Nhật Bản, chiếc bàn viết và những bản thảo của ông. Hai di sản ấy, một thuộc về tâm linh và một thuộc về trí tuệ, cùng lặng lẽ tồn tại dưới một mái nhà."
  ]},
  {"heading": "Ý nghĩa lịch sử – văn hoá", "paras": [
   "Trước hết, dinh thự Ryabushinsky là một cột mốc trong lịch sử kiến trúc. Nó được xem là một trong những công trình định hình phong cách Tân nghệ thuật ở Nga, và là tác phẩm tiêu biểu nhất khẳng định tên tuổi Shekhtel như bậc thầy hàng đầu của trào lưu này. Với giới kiến trúc sư và sinh viên mỹ thuật khắp thế giới, ngôi nhà là một giáo trình sống động về cách một tổng thể nghệ thuật thống nhất có thể được tạo dựng, khi mọi chi tiết lớn nhỏ đều cùng phục vụ cho một ý tưởng chung duy nhất.",
   "Ở tầng ý nghĩa tôn giáo, ngôi nhà lưu giữ một câu chuyện cảm động về tự do tín ngưỡng. Chủ nhân Stepan Ryabushinsky là tín đồ của phái Tín đồ Cũ, một cộng đồng từng bị pháp luật Nga cấm đoán và không được phép có nhà thờ riêng trong suốt một thời gian rất dài. Mãi tới khi Sắc lệnh Khoan dung Tôn giáo được Sa hoàng Nicholas II ban hành năm 1905, họ mới được thờ phụng công khai. Nhà nguyện bí mật giấu trên áp mái, vì vậy, không chỉ là một chi tiết kiến trúc ly kỳ, mà còn là chứng tích lặng lẽ của cả một cộng đồng buộc phải gìn giữ đức tin trong bí mật.",
   "Ngôi nhà cũng gắn liền với một trong những bộ sưu tập thánh tượng quan trọng nhất nước Nga. Stepan Ryabushinsky lưu giữ bộ sưu tập icon của mình, được đồn đại là lớn nhất cả nước, ở tầng hai; và tới năm 1904, ông biến gian phòng trưng bày trên tầng ba thành một xưởng phục chế thánh tượng. Chính tại đây, kỹ thuật khôi phục những lớp sơn cổ đã được nghiên cứu và thực hành một cách bài bản. Ngày nay, nhiều bức icon từng thuộc bộ sưu tập ấy đã trở thành hiện vật quý của Phòng trưng bày Tretyakov, viện bảo tàng mỹ thuật hàng đầu của nước Nga.",
   "Sang thời Xô-viết, ngôi nhà lại mang một trọng lượng chính trị – văn hoá đặc biệt. Dưới thời Gorky, nơi đây trở thành một câu lạc bộ văn chương trên thực tế, quy tụ giới cầm bút hàng đầu của đất nước. Trong những cuộc gặp gỡ tại đây vào tháng 10 năm 1932, có sự hiện diện của Stalin cùng các uỷ viên Bộ Chính trị, khái niệm Chủ nghĩa Hiện thực Xã hội chủ nghĩa đã được định hình, để rồi trở thành đường lối sáng tác chính thống của cả nền văn nghệ Liên Xô suốt nhiều thập niên. Cũng chính từ những cuộc trò chuyện ở ngôi nhà này, ý tưởng về Đại hội Nhà văn Xô-viết đầu tiên và về Viện Văn học mang tên Gorky đã dần thành hình.",
   "Như vậy, chỉ trong một toà biệt thự nhỏ, ba lát cắt lớn của lịch sử nước Nga đã giao thoa: nước Nga thương gia giàu có và mộ đạo trước cách mạng, cơn địa chấn của cách mạng và quốc hữu hoá, rồi guồng máy văn nghệ của nhà nước Xô-viết. Hiếm có công trình nào ở Moscow lại nén chặt nhiều tầng lịch sử đến vậy trong một không gian nhỏ nhắn. Với hướng dẫn viên, đây thực sự là một mỏ vàng để kể chuyện: mỗi căn phòng, mỗi món đồ đều là một cánh cửa mở vào một giai đoạn khác nhau trong số phận của dân tộc Nga."
  ]},
  {"heading": "Trải nghiệm dành cho du khách", "paras": [
   "Bước vào bên trong, du khách sẽ được chiêm ngưỡng năm căn phòng tưởng niệm được gìn giữ gần như nguyên vẹn theo cách bài trí thời Gorky những năm 1930, gồm thư viện, phòng làm việc, phòng ngủ, phòng ăn và phòng của thư ký. Những căn phòng này còn lưu giữ đồ đạc nguyên bản mà nhà văn từng sử dụng, mang lại cảm giác như thể ông chỉ vừa mới bước ra ngoài trong chốc lát. Đặc biệt, thư viện với khoảng mười hai nghìn đầu sách được xem là bộ sưu tập sách cá nhân lớn thứ hai của một nhà văn Nga, chỉ đứng sau thư viện của đại văn hào Lev Tolstoy.",
   "Một điều mà hướng dẫn viên nên lưu ý nhắc khách là sự tương phản thú vị giữa lớp vỏ và lớp ruột. Kiến trúc và phần trang trí cố định của ngôi nhà vẫn thuần chất Art Nouveau lộng lẫy, nhưng phần lớn đồ nội thất nguyên gốc theo phong cách Tân nghệ thuật của gia đình Ryabushinsky nay đã không còn; thay vào đó là bàn ghế, tủ kệ mang dấu ấn sinh hoạt giản dị hơn của Gorky. Chính sự lệch pha thú vị này, giữa một khung cảnh cầu kỳ và một con người tự nhận là không ưa sự phù phiếm, đã tạo nên một chiều sâu cảm xúc rất riêng cho chuyến thăm.",
   "Trải nghiệm cốt lõi của chuyến tham quan xoay quanh việc di chuyển qua các không gian và cảm nhận sự chuyển điệu tinh tế giữa chúng. Khách sẽ đi từ sảnh vào với thế giới dưới nước, dừng lại thật lâu bên cầu thang sóng và chiếc đèn sứa, ngước nhìn dải kính màu, rồi lên các tầng trên để khám phá thư viện và, nếu điều kiện cho phép, cả nhà nguyện bí mật trên áp mái. Không gian không quá rộng nên chuyến thăm mang tính chiêm nghiệm hơn là cưỡi ngựa xem hoa; đây là nơi để đi chậm, quan sát tỉ mỉ và lắng nghe từng câu chuyện được kể.",
   "Về mặt tổ chức, bảo tàng có quy mô vừa phải nên phù hợp với các nhóm nhỏ hoặc khách lẻ hơn là những đoàn quá đông; nếu đoàn lớn, hướng dẫn viên nên chủ động chia nhóm để không gây ùn tắc trong các hành lang hẹp. Thời lượng tham quan hợp lý thường vào khoảng bốn mươi lăm phút đến một tiếng đồng hồ, vừa đủ để thưởng thức trọn vẹn mà không thấy mệt. Đây cũng là một trong số ít bảo tàng ở Moscow mà bản thân toà nhà quan trọng ngang, thậm chí còn hơn cả những hiện vật trưng bày bên trong, nên hãy dành thật nhiều sự chú ý cho từng chi tiết kiến trúc."
  ]},
  {"heading": "Mẹo tham quan", "paras": [
   "Về giờ giấc, bảo tàng thường mở cửa từ thứ Tư đến Chủ nhật, trong khung giờ khoảng 10 giờ sáng đến 6 giờ chiều, và đóng cửa vào thứ Hai cùng thứ Ba hằng tuần. Ngoài ra, ngày thứ Năm cuối cùng của mỗi tháng thường là ngày vệ sinh định kỳ, bảo tàng đóng cửa để bảo dưỡng, nên hướng dẫn viên cần kiểm tra lịch thật kỹ trước khi xếp chương trình cho đoàn. Quầy bán vé thường ngừng phục vụ vào khoảng 5 giờ 30 chiều, tức là trước giờ đóng cửa, vì thế nên tới sớm để tránh lỡ giờ mua vé.",
   "Về giá vé, theo mức tham khảo cập nhật cho khoảng năm 2026, khách người lớn là công dân Nga trả chừng năm trăm năm mươi rúp, các đối tượng ưu đãi khoảng ba trăm năm mươi đến bốn trăm rúp, còn khách nước ngoài vào khoảng bảy trăm rúp. Nếu muốn chụp ảnh nghiệp dư bên trong bảo tàng, du khách mua thêm vé chụp ảnh khoảng hai trăm rúp. Trẻ nhỏ ở tuổi mẫu giáo và một số nhóm được miễn phí vào cửa. Một lưu ý quan trọng: các nguồn tiếng Anh cũ từng ghi rằng vào cửa miễn phí là thông tin đã lỗi thời, nên đừng dựa vào đó mà cần chuẩn bị đủ tiền vé cho khách.",
   "Kinh nghiệm thực tế cho thấy nên chuẩn bị sẵn tiền mặt rúp, bởi thẻ ngân hàng quốc tế phát hành ngoài nước Nga hầu như không sử dụng được để thanh toán tiền vé và đồ lưu niệm. Với các đoàn, việc liên hệ đặt trước và hỏi rõ về suất tham quan cũng như khả năng có hướng dẫn viên nói tiếng Anh là điều rất nên làm, vì bảo tàng không phải lúc nào cũng dồi dào nhân sự. Ngoài ra, nếu muốn ghé thăm cả nhà nguyện bí mật trên áp mái, nên hỏi trước tại quầy vé, vì khu vực này đôi khi chỉ mở theo lịch hoặc theo đoàn có hướng dẫn.",
   "Vài mẹo nhỏ sẽ giúp chuyến thăm thêm trọn vẹn: hãy nhắc khách ngước nhìn lên dải khảm hoa diên vĩ trên đỉnh mặt tiền và cúi xuống ngắm hoạ tiết sóng của sàn gỗ, bởi đó là hai chi tiết dễ bị bỏ sót nhất. Nên đứng ở vài góc khác nhau để ngắm chiếc đèn sứa và bức kính phong cảnh đổi màu. Về trang phục, do sàn cổ và không gian cần được bảo vệ, khách có thể được yêu cầu gửi áo khoác và đôi khi phải phủ bọc giày. Cuối cùng, buổi sáng các ngày trong tuần thường vắng hơn, là thời điểm lý tưởng để thong thả chụp ảnh cầu thang mà không bị vướng người qua lại."
  ]},
  {"heading": "Khám phá xung quanh", "paras": [
   "Một trong những cái duyên lớn nhất của ngôi nhà là nó nằm giữa cả một chòm sao các điểm tham quan trứ danh, gần như tất cả đều trong tầm đi bộ. Ngay gần đó, chỉ khoảng một trăm năm mươi mét, là khu Cổng Nikitsky và Nhà thờ Chúa Thăng Thiên Lớn, nơi ghi dấu một sự kiện lãng mạn bậc nhất trong lịch sử văn học Nga: chính tại đây, đại thi hào Aleksandr Pushkin đã làm lễ thành hôn với người đẹp Natalia Goncharova vào năm 1831. Với du khách yêu thơ ca, đây quả là một điểm dừng chân đầy xúc cảm.",
   "Đi thêm chừng sáu trăm mét, du khách sẽ tới Ao Tổ phụ, tiếng Nga gọi là Patriarshiye Prudy, một hồ nước nhỏ thơ mộng nép mình giữa phố phường. Với những ai mê văn chương, đây gần như là một thánh địa: chính nơi này mở màn cho cuốn tiểu thuyết trứ danh «Nghệ nhân và Margarita» của nhà văn Mikhail Bulgakov, khi nhân vật quỷ vương Woland xuất hiện một cách đầy bí ẩn. Ngồi bên hồ, nhâm nhi một tách cà phê và hình dung lại khung cảnh trong truyện là một trải nghiệm khó quên giữa lòng Moscow.",
   "Cũng trong bán kính năm đến sáu trăm mét là Nhạc viện Moscow mang tên Tchaikovsky, một trong những cái nôi âm nhạc cổ điển danh giá nhất thế giới, nơi thường xuyên diễn ra các buổi hoà nhạc tuyệt vời. Con phố Bolshaya Nikitskaya ngay sát bên là một trục phố lịch sử, dày đặc những dinh thự cổ, nhà hát và quán xá, rất thích hợp để dạo bộ và cảm nhận nhịp sống văn hoá của thủ đô. Hướng dẫn viên có thể gợi ý khách kết hợp một buổi tối nghe nhạc sau khi đã thăm bảo tàng vào ban ngày.",
   "Để nối tiếp mạch câu chuyện về kiến trúc sư Shekhtel, du khách có thể đi bộ chừng bốn trăm mét tới dinh thự Savva Morozov ở phố Spiridonovka số 17, cũng do chính Shekhtel thiết kế nhưng theo phong cách Tân Gothic hoàn toàn khác biệt, cho thấy sự đa tài đáng kinh ngạc của ông. Việc so sánh hai công trình cạnh nhau là một bài học kiến trúc thú vị và bổ ích. Xa hơn một chút, cách khoảng một ki-lô-mét ba, là Vườn thú Moscow, một điểm đến lý tưởng cho các gia đình có trẻ nhỏ muốn đổi không khí sau khi đã thăm thú các công trình văn hoá."
  ]},
  {"heading": "Câu chuyện & giai thoại thú vị", "paras": [
   "Có một nghịch lý thú vị mà hầu như du khách nào cũng thích thú khi được nghe: chính Maxim Gorky, người sống lâu nhất trong ngôi nhà lộng lẫy này, lại chẳng mấy ưa nó. Ông thấy lối trang trí cầu kỳ, uốn éo của phong cách Art Nouveau là phù phiếm, thậm chí gọi thẳng đây là một ngôi nhà «lố bịch». Người ta còn dẫn lại lời ông nói đại ý rằng «một ngôi nhà lố bịch, nhưng người ta vẫn làm việc được». Câu nói ấy vừa hài hước vừa hé lộ tính cách của một nhà văn xuất thân bình dân, quen với đời sống lam lũ và luôn coi trọng công việc hơn hình thức bề ngoài.",
   "Đằng sau vẻ hào nhoáng, ngôi nhà còn ẩn giấu một bầu không khí ngột ngạt rất đặc trưng của thời đại. Nhiều nguồn cho rằng chính quyền bố trí cho Gorky ở đây một phần cũng là để tiện bề giám sát ông. Trong sảnh nhà luôn có một viên chỉ huy của cơ quan an ninh OGPU ngồi ghi chép danh tính từng người khách ra vào. Đáng sợ hơn, trong đợt trùng tu hồi thập niên 1970, người ta còn phát hiện một thiết bị nghe lén được giấu ngay trong tường. Chính Gorky từng thốt lên một câu để đời, đại ý rằng «Sau mỗi cánh cửa đều có một cái tai» – một lời than thấm đẫm nỗi bất an của cả một thời kỳ.",
   "Một giai thoại nhỏ nhưng rất đắt về tính cách Gorky lại liên quan tới một chiếc lò sưởi. Trong nhà từng có một lò sưởi bằng đá cẩm thạch Carrara chạm khắc tinh xảo, trên đó có hình một nhân vật khoả thân nửa người. Chi tiết gợi cảm này khiến nhà văn ngượng ngùng đến mức ông cho tháo bỏ nó đi, và từ đó tác phẩm điêu khắc quý giá ấy thất lạc không còn dấu vết. Câu chuyện cho thấy một Gorky mộc mạc, có phần khắc kỷ, sẵn sàng loại bỏ cả cái đẹp xa hoa nếu nó khiến ông cảm thấy không thoải mái với chính mình.",
   "Ngôi nhà cũng bị phủ bóng bởi những số phận bi thương. Gia tộc Ryabushinsky mất trắng tất cả sau năm 1917 và tan tác khắp nơi; riêng chủ nhân Stepan qua đời trong cảnh lưu vong tại thành phố Milan của nước Ý vào năm 1942. Bản thân Gorky cũng nếm trải mất mát tột cùng: người con trai tên Maxim của ông đột ngột qua đời khi mới khoảng ba mươi tư tuổi vào năm 1934, và chỉ hai năm sau, năm 1936, chính nhà văn cũng ra đi giữa những lời đồn đại về nguyên nhân cái chết mà cho tới nay vẫn còn gây tranh cãi. Ngôi nhà đẹp đẽ này, vì thế, cũng là nơi từng chứng kiến không ít nước mắt.",
   "Nhưng giữa những trang buồn vẫn le lói ánh sáng của tình người. Người em trong dòng họ, nhà khoa học Dmitry Ryabushinsky, từng bị bắt năm 1918 với tội danh kẻ thù giai cấp; may thay, chính Gorky đã đứng ra can thiệp để cứu ông. Về sau, Dmitry sang Pháp và trở thành giáo sư tại Đại học Sorbonne danh giá, tiếp tục theo đuổi sự nghiệp khoa học. Sau cùng, đừng quên kể cho khách nghe về nhà nguyện bí mật trên áp mái và triết lý thiết kế tổng thể của Shekhtel: từ tay nắm hình cá ngựa, sàn gỗ hình sóng, chiếc đèn sứa, dải khảm diên vĩ cho tới đầu cột chạm hoa loa kèn và kỳ giông, tất cả cùng kể chung một câu chuyện ngụ ngôn duy nhất, dẫn dắt ta đi từ đáy biển sâu thẳm lên tới tận cõi thiên đường."
  ]}
 ],
 "highlights": [
  "Cầu thang cẩm thạch nhân tạo cuộn hình sóng biển – trái tim bố cục của cả ngôi nhà.",
  "Chiếc đèn kính và đồng hình con sứa trên đỉnh cầu thang, nhìn từ trên xuống lại hoá thành một con rùa.",
  "Tầng trệt dàn dựng như thế giới dưới đáy biển: tay nắm cửa hình cá ngựa, sàn gỗ gợn sóng, ánh sáng lọc qua kính màu.",
  "Dải khảm majolica hoa diên vĩ nở rộ trên nền trời xanh chạy quanh đỉnh mặt tiền.",
  "Nhà nguyện bí mật của phái Tín đồ Cũ giấu kín trên tầng áp mái, tường vẽ đầy hoạ tiết ngôi sao.",
  "Kiệt tác chữ ký của kiến trúc sư Fyodor Shekhtel, bậc thầy khai sáng của Tân nghệ thuật Nga.",
  "Thư viện khoảng mười hai nghìn cuốn của Gorky trong bốn mươi bốn tủ sách, lớn thứ hai trong giới văn hào Nga.",
  "Nơi khái niệm Chủ nghĩa Hiện thực Xã hội chủ nghĩa thành hình năm 1932 với sự hiện diện của Stalin."
 ],
 "images": [
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Moscow.%20Ryabushinsky%20House.%20Interiors.%20Main%20stairs%20-%20002.JPG", "caption": "cầu thang cẩm thạch hình con sóng và chiếc đèn hình sứa nổi tiếng."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Moscow.%20Ryabushinsky%20House.%20Interiors.%20Main%20stairs%20-%20004.JPG", "caption": "một góc khác của cầu thang sóng bằng cẩm thạch nhân tạo."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/RyabushinskiChapel1.jpg", "caption": "nhà nguyện bí mật của Tín đồ Cũ giấu trên tầng áp mái."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Особняк%20С.П.%20Рябушинского.%20Южный%20фасад.%202013-08-08%2014-52-23.jpg", "caption": "mặt tiền phía nam với cổng vào kiểu hang động và dải khảm hoa diên vĩ."},
  {"url": "https://commons.wikimedia.org/wiki/Special:FilePath/Особняк%20С.П.%20Рябушинского.%20Кабинет.%202013-07-28%2012-47-29.jpg", "caption": "phòng làm việc nơi văn hào Maxim Gorky từng sống và viết."}
 ],
 "references": [
  {"title": "Wikipedia (tiếng Anh) — Gorky Museum", "url": "https://en.wikipedia.org/wiki/Gorky_Museum"},
  {"title": "Wikipedia (tiếng Nga) — Особняк С. П. Рябушинского", "url": "https://ru.wikipedia.org/wiki/Особняк_С._П._Рябушинского"},
  {"title": "Bảo tàng chính thức (IMLI RAN) — Lịch sử ngôi nhà", "url": "https://museum.imli.ru/istoriya-doma"},
  {"title": "Bảo tàng chính thức — Nội thất", "url": "https://museum.imli.ru/muzej-kvartira"},
  {"title": "Russia Beyond — Ryabushinsky's mansion", "url": "https://www.rbth.com/arts/328070-ryabushinskys-mansion-extraordinary-house-with-tragic-fate"},
  {"title": "Iconic Houses Network — Ryabushinsky House / Gorky House Museum", "url": "https://www.iconichouses.org/houses/ryabushinsky-house-gorky-house-museum"},
  {"title": "W. C. Brumfield — The Origins of Modernism in Russian Architecture (chương Shekhtel)", "url": "https://publishing.cdlib.org/ucpressebooks/view?docId=ft1g5004bj"}
 ],
 "sources": [
  "Bách khoa toàn thư mở Wikipedia bản tiếng Anh (mục Gorky Museum): dữ kiện Gorky sống ở đây từ năm 1931 đến năm 1936, việc mở bảo tàng năm 1965 và tư cách chi nhánh của Viện IMLI RAN.",
  "Wikipedia bản tiếng Nga (mục Особняк С. П. Рябушинского): niên đại xây dựng 1900 đến 1903, chủ nhân Stepan Ryabushinsky và chuỗi công năng của ngôi nhà sau năm 1917.",
  "Trang chính thức của bảo tàng IMLI RAN (mục Lịch sử ngôi nhà): dòng họ Ryabushinsky, phái Tín đồ Cũ, nhà nguyện bí mật và bộ sưu tập thánh tượng.",
  "Trang chính thức của bảo tàng (mục Nội thất): mô tả cầu thang sóng, chiếc đèn hình sứa, chủ đề thế giới dưới nước và các phòng tưởng niệm của Gorky.",
  "Tạp chí Russia Beyond (bài về dinh thự Ryabushinsky): các giai thoại về việc Gorky không ưa ngôi nhà, hệ thống giám sát và số phận bi thương của gia tộc.",
  "Mạng lưới Iconic Houses (hồ sơ Ryabushinsky House / Gorky House Museum): vị thế di sản kiến trúc và tư cách thành viên mạng lưới nhà biểu tượng thế giới.",
  "Công trình nghiên cứu của W. C. Brumfield về nguồn gốc chủ nghĩa hiện đại trong kiến trúc Nga (chương về Shekhtel): phân tích phong cách cùng ảnh hưởng của Olbrich và Art Nouveau phương Tây.",
  "Tổng hợp dữ kiện thực tế (giờ mở cửa, giá vé tham khảo năm 2026, cách di chuyển bằng metro, lối vào phía Spiridonovka): metadata dự án và thông tin tham quan hiện hành."
 ]
}

out_path = "/sessions/stoic-gallant-fermi/mnt/russia-tourism/_incoming/doc_ryabushinsky-mansion.json"
json.dump(doc, open(out_path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("OK words=", sum(len(p.split()) for s in doc["sections"] for p in s["paras"]))
for s in doc["sections"]:
    print("  -", s["heading"], ":", len(s["paras"]), "paras,", sum(len(p.split()) for p in s["paras"]), "words")
