# -*- coding: utf-8 -*-
"""add_modern_places.py — Bổ sung các địa điểm nổi tiếng / hiện đại còn thiếu vào DB.

Cách dùng: python3 tools/add_modern_places.py
- Mỗi mục trong CANDIDATES sẽ được thêm vào data/regions/<region>.json nếu slug CHƯA có.
- Nội dung tiếng Việt là nguyên gốc (tự soạn), rating để trống nếu chưa có nguồn xác thực.
- Đây là "khung" để mở rộng dần: chỉ cần thêm mục mới vào CANDIDATES.
"""
import json, os, glob, urllib.parse, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REGIONS = os.path.join(ROOT, "data", "regions")
QUEUE = os.path.join(ROOT, "_source", "regions_queue.json")
try:
    TODAY = datetime.date.today().isoformat()
except Exception:
    TODAY = "2026-07-23"

RMETA = {}
if os.path.exists(QUEUE):
    for r in json.load(open(QUEUE, encoding="utf-8")).get("regions", []):
        RMETA[r["slug"]] = (r.get("name_vi", r["slug"]), r.get("federal_district", ""))


def maps(lat, lon):
    return {"yandex": f"https://yandex.com/maps/?pt={lon},{lat}&z=16&l=map",
            "google": f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"}


def wiki(name_en):
    return [{"title": "Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Special:Search?search=" + urllib.parse.quote(name_en)}]


def rec(region, slug, name_vi, name_ru, name_en, cats, lat, lon, addr, short, long, hl, tags, practical=None, sources=None, status="enriched", official_site=None):
    nv, fed = RMETA.get(region, (region, ""))
    return {
        "id": f"{region}-{slug}", "slug": slug, "region": region,
        "region_name_vi": nv, "federal_district": fed,
        "name_vi": name_vi, "name_ru": name_ru, "name_en": name_en,
        "categories": cats, "coordinates": {"lat": lat, "lon": lon}, "address_vi": addr,
        "rating": {"value": None, "count": None, "source": None, "as_of": None},
        "review_summary_vi": "",
        "presentation_short_vi": short, "presentation_long_vi": long,
        "highlights_vi": hl, "practical": practical or {},
        "photo": None, "photo_credit": None,
        "maps": maps(lat, lon), "official_site": official_site,
        "sources": sources or wiki(name_en), "tags": tags, "status": status, "last_updated": TODAY,
    }


CANDIDATES = [
    rec("moscow", "sokolniki",
        "Công viên Sokolniki (Xô-côn-ni-ki)", "Парк «Сокольники»", "Sokolniki Park",
        ["park_garden"], 55.79300, 37.67600,
        "Sokolnichesky Val 1, quận Sokolniki, phía đông Moskva (ngay cạnh metro Sokolniki)",
        "Một trong những công viên lâu đời và rộng lớn nhất Moskva (khoảng 516 ha), mọc lên từ khu rừng săn chim ưng của các đại công tước Nga xưa. Ngày nay là 'công viên văn hóa và nghỉ ngơi' sầm uất với những đại lộ cây tỏa hình nan quạt, hồ nước, sân trượt băng mùa đông và lễ hội bốn mùa.",
        "Nằm ở phía đông Moskva, Sokolniki là một trong những công viên lâu đời và được yêu thích nhất thành phố. Cái tên bắt nguồn từ 'sokol' — chim ưng trong tiếng Nga: đây từng là khu rừng nơi các đại công tước và Sa hoàng tổ chức những cuộc săn bằng chim ưng, và khu phố của những người nuôi chim ưng hoàng gia thế kỷ 17 đã đặt tên cho vùng đất. Trở thành công viên công cộng của thành phố từ năm 1878 và được quy hoạch thành 'công viên văn hóa và nghỉ ngơi' từ năm 1931, Sokolniki trải rộng khoảng 516 ha với bố cục đặc trưng: từ quảng trường đài phun nước ở trung tâm, những đại lộ cây thẳng tắp (gọi là 'luchi' — tia sáng) tỏa ra hình nan quạt vào rừng sâu. Năm 1959, công viên thành tâm điểm chú ý toàn cầu khi đăng cai Triển lãm Quốc gia Hoa Kỳ — nơi diễn ra 'Cuộc tranh luận Nhà bếp' nổi tiếng giữa Phó Tổng thống Mỹ Richard Nixon và lãnh đạo Liên Xô Nikita Khrushchev, thu hút khoảng 3 triệu lượt khách. Ngày nay Sokolniki là không gian giải trí bốn mùa: mùa hè có đạp xe, thuê thuyền trên hồ, sân khấu ngoài trời và lễ hội; mùa đông biến thành một trong những khu trượt băng ngoài trời lớn nhất châu Âu giữa rừng cây phủ tuyết. Vườn hồng, khu vui chơi trẻ em, quán cà phê và các trung tâm triển lãm khiến nơi đây hợp với mọi lứa tuổi.",
        ["Tên gọi bắt nguồn từ 'sokol' (chim ưng) — xưa là rừng săn chim ưng của các đại công tước và khu ở của thợ nuôi chim ưng hoàng gia.",
         "Rộng khoảng 516 ha; bố cục đại lộ cây tỏa hình nan quạt từ quảng trường đài phun nước trung tâm.",
         "Nơi diễn ra Triển lãm Quốc gia Hoa Kỳ 1959 và 'Cuộc tranh luận Nhà bếp' giữa Nixon và Khrushchev."],
        ["park", "outdoor", "family", "free", "history"],
        practical={"hours_vi": "Công viên mở cửa tự do hằng ngày; các khu vui chơi, sân trượt băng và trung tâm triển lãm có giờ và vé riêng.",
                   "ticket_vi": "Vào công viên miễn phí; một số hoạt động (thuê thuyền, trượt băng, triển lãm) thu phí riêng.",
                   "duration_vi": "2–3 giờ.",
                   "best_time_vi": "Mùa hè để đạp xe, chèo thuyền; mùa đông để trượt băng giữa rừng tuyết.",
                   "tips_vi": "Xuống metro Sokolniki là tới cổng chính; thuê xe đạp hoặc patin để đi hết các 'tia' đại lộ."},
        sources=[{"title": "Sokolniki Park — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Sokolniki_Park"},
                 {"title": "American National Exhibition (1959) — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/American_National_Exhibition"}],
        official_site="https://www.sokolniki.com"),

    rec("moscow", "museum-russian-impressionism",
        "Bảo tàng Trường phái Ấn tượng Nga (Muzey Russkogo Impressionizma)", "Музей русского импрессионизма", "Museum of Russian Impressionism",
        ["museum"], 55.78076, 37.57150,
        "Leningradsky Prospekt 15, toà 11 (khu tổ hợp nhà máy 'Bolshevik' cũ), Moskva (gần metro Dinamo/Belorusskaya)",
        "Bảo tàng tư nhân hiện đại khai trương năm 2016, chuyên về hội họa Ấn tượng Nga — dòng tranh giàu ánh sáng thường bị lu mờ trước Ấn tượng Pháp. Đặt trong khối nhà hình trụ bọc thép đục lỗ nổi bật, cải tạo từ kho chứa của nhà máy bánh kẹo 'Bolshevik' thời Xô-viết.",
        "Khai trương tháng 5 năm 2016, Bảo tàng Trường phái Ấn tượng Nga là một trong những bảo tàng tư nhân hiện đại đáng chú ý nhất Moskva. Bộ sưu tập khởi nguồn từ nhà sáng lập — doanh nhân Boris Mints — với hơn bảy mươi tác phẩm của các danh họa Nga như Konstantin Korovin, Igor Grabar, Konstantin Yuon, Pyotr Konchalovsky, Yuri Pimenov, cùng những bức chọn lọc của Valentin Serov và Boris Kustodiev. Bảo tàng dành riêng cho một dòng chảy thường bị xem nhẹ: hội họa Ấn tượng Nga — nơi các nghệ sĩ mang tinh thần phóng khoáng, chuộng ánh sáng và bút pháp của Ấn tượng Pháp hòa cùng phong cảnh, con người và khí hậu Nga. Công trình cũng là điểm nhấn kiến trúc: hãng John McAslan + Partners (Anh) đã biến một kho chứa hình trụ của nhà máy bánh kẹo 'Bolshevik' (Bôn-sê-vích) thời Xô-viết thành khối nhà bọc thép đục lỗ ánh bạc, nằm giữa khu công nghiệp cũ được cải tạo trên đại lộ Leningradsky. Bên trong là hơn 1.000 m² không gian trưng bày, một rạp chiếu phim, khu trải nghiệm đa phương tiện, xưởng giáo dục cho trẻ em, quán cà phê và cửa hàng lưu niệm. Cách bố trí hiện đại, nhiều tương tác khiến nơi đây đặc biệt thân thiện với gia đình và những ai muốn khám phá một góc ít biết của nghệ thuật Nga.",
        ["Khai trương năm 2016; bộ sưu tập khởi nguồn từ nhà sáng lập Boris Mints với hơn 70 tác phẩm (Korovin, Grabar, Yuon, Konchalovsky, Pimenov...).",
         "Chuyên về hội họa Ấn tượng Nga — dòng tranh giàu ánh sáng thường bị lu mờ trước Ấn tượng Pháp.",
         "Kiến trúc hình trụ bọc thép đục lỗ do hãng John McAslan + Partners cải tạo từ kho nhà máy bánh kẹo 'Bolshevik'."],
        ["modern", "museum", "art", "indoor", "family"],
        practical={"hours_vi": "Thường mở cửa hằng ngày (giờ thay đổi theo mùa và triển lãm); nên kiểm tra lịch trên trang chính thức.",
                   "ticket_vi": "Có thu phí; nên đặt vé theo khung giờ trên trang chính thức, có ưu đãi cho học sinh/sinh viên.",
                   "duration_vi": "1,5–2 giờ.",
                   "best_time_vi": "Quanh năm (không gian trong nhà); tránh cuối tuần đông nếu muốn yên tĩnh.",
                   "tips_vi": "Có audio guide; kết hợp dạo khu tổ hợp 'Bolshevik' cải tạo xung quanh."},
        sources=[{"title": "Museum of Russian Impressionism — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Museum_of_Russian_Impressionism"},
                 {"title": "Museum of Russian Impressionism — John McAslan + Partners", "url": "https://www.mcaslan.co.uk/work/museum-russian-impressionism"}],
        official_site="https://www.rusimp.su"),

    rec("saint-petersburg", "yelagin-palace",
        "Cung điện Yelagin & Đảo Yelagin (TsPKiO mang tên Kirov)", "Елагин дворец (Елагин остров)", "Yelagin Palace and Yelagin Island",
        ["palace", "park_garden"], 59.98060, 30.26220,
        "Elagin ostrov 4, quận Petrogradsky (bắc thành phố), Saint Petersburg",
        "Biệt điện Palladian thanh nhã do kiến trúc sư Carlo Rossi thiết kế (1818–1822) cho Hoàng thái hậu Maria Feodorovna — công trình lớn đầu tay của ông tại Saint Petersburg. Cả đảo Yelagin quanh cung điện nay là công viên văn hóa – nghỉ ngơi mang tên Kirov: không xe cộ, nhiều hồ nước, đình tạ và lối dạo rợp bóng cây.",
        "Ở mũi tây bắc thành phố, đảo Yelagin và tòa cung điện cùng tên tạo nên một trong những không gian nghỉ dưỡng thanh bình và duyên dáng nhất Saint Petersburg. Cung điện Yelagin được Hoàng đế Aleksandr I đặt xây năm 1818 làm nơi nghỉ hè cho mẹ mình — Hoàng thái hậu Maria Feodorovna — trên nền một dinh thự cũ từng thuộc về nhà quý tộc Ivan Yelagin thời Ekaterina Đại đế. Đây là công trình lớn đầu tay tại kinh đô của kiến trúc sư người Ý Carlo Rossi, người sau này định hình diện mạo cổ điển của cả Saint Petersburg. Rossi không chỉ dựng tòa biệt điện Palladian với hàng cột và mái vòm cân đối, mà còn thiết kế cả nhà bếp, chuồng ngựa, ba đình tạ trong vườn và phần lớn nội thất lộng lẫy bên trong — với tường giả cẩm thạch và cửa gỗ khảm tinh xảo. Bị tàn phá trong cuộc vây hãm Leningrad (1941–1944), cung điện được trùng tu công phu vào thập niên 1950 và nay là bảo tàng nghệ thuật trang trí – ứng dụng và nội thất thế kỷ 18–20. Toàn bộ hòn đảo, vốn là điền trang hoàng gia, từ sau năm 1917 trở thành công viên công cộng mang tên chính thức là Công viên Văn hóa và Nghỉ ngơi Trung tâm mang tên S. M. Kirov (TsPKiO). Không cho xe cơ giới, đảo là thiên đường đi dạo, đạp xe, chèo thuyền trên các hồ, ngắm thiên nga và đón hoàng hôn nơi mũi tây nhìn ra vịnh Phần Lan.",
        ["Công trình lớn đầu tay tại Saint Petersburg của Carlo Rossi (1818–1822), xây cho Hoàng thái hậu Maria Feodorovna.",
         "Rossi thiết kế trọn vẹn cả cung điện, đình tạ, nhà bếp, chuồng ngựa và nội thất; nay là bảo tàng nghệ thuật trang trí – ứng dụng.",
         "Cả đảo Yelagin là công viên không xe cộ (TsPKiO mang tên Kirov) — nơi chèo thuyền, đạp xe và ngắm hoàng hôn ra vịnh Phần Lan."],
        ["palace", "park", "outdoor", "history", "family"],
        practical={"hours_vi": "Đảo – công viên mở cửa hằng ngày (một số ngày/mùa có thể thu phí vào cổng); Cung điện – bảo tàng thường đóng cửa Thứ Hai, kiểm tra lịch chính thức.",
                   "ticket_vi": "Vào công viên thường miễn phí (đôi khi thu phí cuối tuần/lễ hội); tham quan cung điện – bảo tàng mua vé riêng.",
                   "duration_vi": "Nửa ngày (2–4 giờ) nếu kết hợp cung điện và dạo đảo.",
                   "best_time_vi": "Cuối xuân đến đầu thu; đẹp nhất lúc hoàng hôn ở mũi tây đảo.",
                   "tips_vi": "Thuê thuyền hoặc xe đạp để khám phá đảo; kết hợp dạo hai đảo lân cận Krestovsky và Kamenny."},
        sources=[{"title": "Yelagin Palace — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Yelagin_Palace"},
                 {"title": "Yelagin Island — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Yelagin_Island"}],
        official_site="https://elaginpark.org"),

    rec("saint-petersburg", "lakhta-center",
        "Trung tâm Lakhta (Lakhta Center)", "Лахта-центр", "Lakhta Center",
        ["monument"], 59.98700, 30.17760,
        "Quận Primorsky, ven vịnh Phần Lan, Saint Petersburg",
        "Toà nhà chọc trời cao nhất châu Âu (462 m) và là toà nhà cực Bắc thế giới — trụ sở tập đoàn Gazprom, biểu tượng hiện đại của Saint Petersburg bên vịnh Phần Lan.",
        "Khánh thành năm 2019, Lakhta Center cao 462 m với 87 tầng, mang hình khối xoắn ốc bằng kính vươn lên như một ngọn lửa. Đây là toà nhà cao nhất châu Âu và toà nhà chọc trời nằm ở cực Bắc nhất thế giới. Tổ hợp gồm văn phòng, không gian công cộng, đài quan sát ngắm toàn cảnh thành phố và vịnh — đặc biệt đẹp lúc hoàng hôn. Lakhta nằm liền kề Công viên 300 năm và Sân vận động Gazprom Arena, tạo thành cụm điểm đến hiện đại bậc nhất của thành phố.",
        ["Toà nhà cao nhất châu Âu (462 m)", "Đài quan sát ngắm toàn cảnh & vịnh Phần Lan", "Kiến trúc xoắn ốc bằng kính độc đáo"],
        ["modern", "landmark", "viewpoint", "skyscraper"],
        {"best_time_vi": "Chiều muộn – hoàng hôn", "tips_vi": "Đặt vé đài quan sát trước; kết hợp cùng Công viên 300 năm và Gazprom Arena."}),

    rec("saint-petersburg", "gazprom-arena",
        "Sân vận động Gazprom Arena (Krestovsky)", "Газпром Арена", "Gazprom Arena (Krestovsky Stadium)",
        ["monument"], 59.97260, 30.22060,
        "Đảo Krestovsky, quận Petrogradsky, Saint Petersburg",
        "Sân nhà của CLB Zenit — một trong những sân vận động hiện đại nhất nước Nga, có mái che di động và mặt cỏ trượt, từng tổ chức World Cup 2018 và EURO 2020.",
        "Nằm trên đảo Krestovsky, Gazprom Arena (còn gọi là sân Krestovsky) sức chứa khoảng 68.000 chỗ, nổi bật với mái che khép mở được và mặt sân cỏ có thể trượt ra – vào. Sân từng đăng cai các trận bán kết World Cup 2018 và nhiều trận EURO 2020, là sân nhà của câu lạc bộ bóng đá Zenit Saint Petersburg. Khu vực quanh sân có công viên, lối đi dạo ven vịnh và gần Công viên 300 năm cùng Lakhta Center — thích hợp cho một buổi chiều khám phá 'Saint Petersburg hiện đại'.",
        ["Một trong các SVĐ hiện đại nhất nước Nga", "Mái che di động & mặt cỏ trượt", "Từng tổ chức World Cup 2018 & EURO 2020"],
        ["modern", "sport", "stadium"],
        {"tips_vi": "Có tour tham quan sân vào ngày không thi đấu; kết hợp Lakhta & Công viên 300 năm."}),

    rec("saint-petersburg", "park-300-letiya",
        "Công viên 300 năm Saint Petersburg", "Парк 300-летия Санкт-Петербурга", "Park of the 300th Anniversary of Saint Petersburg",
        ["park_garden"], 59.98360, 30.22650,
        "Quận Primorsky, ven vịnh Phần Lan, Saint Petersburg",
        "Công viên ven vịnh khánh thành dịp thành phố tròn 300 tuổi (2003) — không gian mở rộng lớn, bãi cỏ, lối đi dạo bên nước, nhìn thẳng ra Lakhta Center.",
        "Được lập nhân kỷ niệm 300 năm thành lập Saint Petersburg (2003), công viên trải dài ven vịnh Phần Lan với những thảm cỏ rộng, hàng cây non, đài phun nước và bờ kè đi dạo. Đây là nơi người dân thành phố tập thể dục, đạp xe, thả diều và ngắm hoàng hôn trên vịnh; từ đây nhìn ra toà tháp Lakhta Center và Gazprom Arena rất ấn tượng. Không gian thoáng đãng, hiện đại, thích hợp thư giãn nhẹ nhàng cho cả gia đình.",
        ["Không gian ven vịnh thoáng đãng", "View đẹp ra Lakhta Center", "Đạp xe, đi dạo, ngắm hoàng hôn"],
        ["modern", "park", "waterfront"],
        {"best_time_vi": "Chiều tối mùa hè", "tips_vi": "Kết hợp cùng Lakhta Center và Gazprom Arena thành một cụm."}),

    rec("saint-petersburg", "sevkabel-port",
        "Sevkabel Port — không gian sáng tạo ven biển", "Севкабель Порт", "Sevkabel Port",
        ["square_street"], 59.92750, 30.23800,
        "Đảo Vasilievsky (bờ Tây), Saint Petersburg",
        "Nhà máy cáp cũ được cải tạo thành tổ hợp sáng tạo ven vịnh — quán xá, triển lãm, sự kiện âm nhạc và điểm ngắm hoàng hôn được giới trẻ yêu thích.",
        "Từng là nhà máy sản xuất cáp điện, Sevkabel Port nay trở thành một trong những không gian sáng tạo sôi động nhất Saint Petersburg: xưởng cũ được chuyển thành phòng triển lãm, studio, quán cà phê, nhà hàng và sân khấu ngoài trời bên bờ vịnh Phần Lan. Đây là nơi tổ chức lễ hội, chợ phiên, sự kiện nghệ thuật và là điểm ngắm hoàng hôn nổi tiếng — đại diện cho một Saint Petersburg trẻ trung, hiện đại bên cạnh vẻ cổ kính.",
        ["Khu công nghiệp cũ cải tạo sáng tạo", "Triển lãm, sự kiện, quán xá ven vịnh", "Điểm ngắm hoàng hôn của giới trẻ"],
        ["modern", "creative", "waterfront"],
        {"tips_vi": "Kiểm tra lịch sự kiện trước khi đến; đẹp nhất buổi chiều."}),

    rec("moscow", "ho-chi-minh-monument",
        "Tượng đài Chủ tịch Hồ Chí Minh", "Памятник Хо Ши Мину", "Monument to Ho Chi Minh",
        ["monument"], 55.68580, 37.56360,
        "Quảng trường Hồ Chí Minh, quận Akademichesky, Moskva (gần metro Akademicheskaya)",
        "Tượng đài Bác Hồ tại Quảng trường Hồ Chí Minh — biểu tượng tình hữu nghị Việt–Nga, khánh thành năm 1990, là điểm đến đầy ý nghĩa với cộng đồng và du khách Việt.",
        "Nằm ở Quảng trường Hồ Chí Minh thuộc quận Akademichesky (gần ga metro Akademicheskaya), tượng đài do nhà điêu khắc Vladimir Tsigal thực hiện, khánh thành năm 1990. Tác phẩm khắc hoạ hình ảnh Chủ tịch Hồ Chí Minh trên nền một đĩa tròn tượng trưng cho mặt trời đang lên. Đây là nơi cộng đồng người Việt tại Moskva thường lui tới trong các dịp lễ, và là điểm dừng chân giàu ý nghĩa cho du khách Việt muốn cảm nhận sợi dây gắn kết lịch sử giữa hai dân tộc.",
        ["Biểu tượng tình hữu nghị Việt–Nga", "Khánh thành năm 1990 (điêu khắc gia V. Tsigal)", "Gần metro Akademicheskaya"],
        ["monument", "vietnam", "friendship"],
        {"tips_vi": "Điểm dừng nhanh, kết hợp khi di chuyển ở khu Tây Nam Moskva."}),

    rec("moscow", "luzhniki-stadium",
        "Sân vận động Luzhniki (Lu-giơ-ni-ki)", "Стадион «Лужники»", "Luzhniki Stadium",
        ["monument"], 55.71528, 37.55389,
        "Luzhniki 24, quận Khamovniki, Moskva (gần metro Sportivnaya / Vorobyovy Gory)",
        "Sân vận động quốc gia lớn nhất nước Nga (khoảng 81.000 chỗ) — nơi tổ chức Thế vận hội Mùa hè 1980 và trận chung kết World Cup 2018, biểu tượng thể thao của Moskva.",
        "Nằm bên khúc uốn của sông Moskva dưới chân Đồi Chim Sẻ, Luzhniki là sân vận động quốc gia lớn nhất nước Nga và là một trong những đấu trường thể thao mang tính biểu tượng nhất châu Âu. Khánh thành năm 1956 với tên gọi Sân vận động Trung tâm Lenin, nơi đây từng là trái tim của Thế vận hội Mùa hè 1980 — kỳ Olympic đầu tiên tổ chức ở Đông Âu. Sau đợt đại tu kéo dài từ 2013 đến 2017, phần khán đài được xây mới gần như hoàn toàn trong khi vẫn giữ lại mặt tiền lịch sử, nâng sức chứa lên khoảng 81.000 chỗ. Chính tại đây, tối 15/7/2018, đội tuyển Pháp đã thắng Croatia 4–2 trong trận chung kết World Cup 2018; sân cũng từng đăng cai chung kết Champions League 2008 giữa Manchester United và Chelsea. Ngày nay Luzhniki là sân nhà của đội tuyển bóng đá quốc gia Nga và là tâm điểm của một tổ hợp thể thao khổng lồ gồm nhiều nhà thi đấu, bể bơi và lối dạo ven sông. Với du khách, đứng trước khối kiến trúc bề thế này là cách cảm nhận rõ nhất tầm vóc thể thao của Moskva; khu vực quanh sân cũng lý tưởng để tản bộ, ngắm sông và nhìn sang toà nhà chính Đại học Tổng hợp Moskva trên đồi.",
        ["Sân vận động lớn nhất nước Nga, sức chứa khoảng 81.000 chỗ.",
         "Nơi tổ chức Thế vận hội Mùa hè 1980 và chung kết World Cup 2018 (Pháp 4–2 Croatia).",
         "Đại tu 2013–2017: xây mới khán đài nhưng giữ lại mặt tiền lịch sử."],
        ["modern", "sport", "stadium", "landmark"],
        {"hours_vi": "Khuôn viên ngoài trời mở tự do; tham quan bên trong theo tour hoặc ngày có sự kiện.",
         "ticket_vi": "Khuôn viên miễn phí; vé tour sân và vé sự kiện tính riêng.",
         "duration_vi": "1–2 giờ (kể cả dạo khuôn viên).",
         "best_time_vi": "Chiều tối, hoặc ngày có trận đấu / sự kiện.",
         "tips_vi": "Kết hợp dạo Đồi Chim Sẻ và ngắm toàn cảnh từ đài quan sát Vorobyovy Gory gần đó."}),

    rec("moscow", "jewish-museum-tolerance-center",
        "Bảo tàng Do Thái và Trung tâm Khoan dung", "Еврейский музей и центр толерантности", "Jewish Museum and Tolerance Center",
        ["museum"], 55.78917, 37.60806,
        "Ulitsa Obraztsova 11, quận Marina Roshcha, Moskva (gần metro Novoslobodskaya / Maryina Roshcha)",
        "Một trong những bảo tàng Do Thái lớn nhất thế giới, đặt trong nhà để xe buýt Bakhmetevsky theo phong cách kiến tạo — trưng bày đa phương tiện, tương tác, khai trương năm 2012.",
        "Khai trương tháng 11/2012, Bảo tàng Do Thái và Trung tâm Khoan dung nhanh chóng trở thành một trong những bảo tàng Do Thái lớn và hiện đại nhất thế giới. Điều gây ấn tượng đầu tiên chính là toà nhà: đây vốn là nhà để xe buýt Bakhmetevsky, kiệt tác kiến trúc kiến tạo (constructivism) do Konstantin Melnikov và kỹ sư Vladimir Shukhov thiết kế cuối thập niên 1920, nổi bật với không gian rộng thoáng và những vì kèo đặc trưng. Bên trong, thay cho tủ kính truyền thống, bảo tàng kể chuyện bằng công nghệ: màn hình tương tác, phim tài liệu, không gian tái dựng và các trạm nghe – nhìn dẫn khách đi qua lịch sử và đời sống của người Do Thái ở Nga cùng Đông Âu, từ thế kỷ 19, qua các biến động cách mạng, chiến tranh và Holocaust, đến ngày nay. Một phần đặc biệt là Trung tâm Khoan dung — không gian giáo dục khuyến khích đối thoại về sự khác biệt, định kiến và lòng bao dung. Với du khách, đây là điểm đến bổ ích để hiểu một lớp lịch sử ít được kể của nước Nga, đồng thời chiêm ngưỡng cách một di sản kiến trúc tiên phong được hồi sinh.",
        ["Một trong những bảo tàng Do Thái lớn nhất thế giới, khai trương năm 2012.",
         "Đặt trong nhà để xe buýt Bakhmetevsky — kiệt tác kiến trúc kiến tạo của Melnikov & Shukhov.",
         "Trưng bày đa phương tiện, tương tác; có Trung tâm Khoan dung về đối thoại và bao dung."],
        ["museum", "modern", "history", "culture"],
        {"hours_vi": "Thường mở Chủ nhật–Thứ Sáu; đóng cửa Thứ Bảy (ngày Sabbath) và các ngày lễ Do Thái — nên kiểm tra lịch chính thức trước khi đến.",
         "ticket_vi": "Có thu phí; xem giá cập nhật trên trang chính thức.",
         "duration_vi": "2–3 giờ.",
         "best_time_vi": "Ngày thường để tránh đông; tránh Thứ Bảy vì đóng cửa.",
         "tips_vi": "Nên thuê audio-guide hoặc đi theo tour; nhiều nội dung tương tác cần thời gian trải nghiệm."}),

    rec("saint-petersburg", "grand-maket-rossiya",
        "Grand Maket Rossiya — Mô hình nước Nga thu nhỏ", "Гранд Макет Россия", "Grand Maket Rossiya (Grand Layout Russia)",
        ["museum"], 59.89278, 30.32639,
        "Tsvetochnaya ulitsa 16, Saint Petersburg (gần metro Moskovskiye Vorota)",
        "Mô hình nước Nga thu nhỏ lớn nhất cả nước và lớn thứ hai thế giới (khoảng 800 m², tỉ lệ 1:87) — cả đất nước sống động với tàu chạy và chu kỳ đèn ngày–đêm.",
        "Mở cửa chính thức tháng 6/2012, Grand Maket Rossiya là mô hình nước Nga thu nhỏ lớn nhất cả nước và lớn thứ hai trên thế giới, chỉ sau Miniatur Wunderland ở Hamburg (Đức). Trên diện tích khoảng 800 m² dựng theo tỉ lệ 1:87 (khổ HO), tác phẩm không tái hiện từng thành phố cụ thể mà khắc hoạ 'hình ảnh gộp' của các vùng miền — từ Viễn Đông, Siberia, dãy Ural đến miền Trung và các đô thị lớn — để người xem cảm nhận cả một đất nước trải dài nhiều múi giờ chỉ trong một gian phòng. Điều khiến khách mê mẩn là sự sống động: hàng nghìn toa tàu và đầu máy lăn bánh trên hơn 2.500 m đường ray, ô tô tự chạy dừng đèn đỏ rồi đi tiếp, và cứ khoảng 13 phút cả mô hình lại chuyển từ ngày sang đêm nhờ hơn 800.000 bóng đèn LED. Khắp không gian bố trí các nút bấm tương tác để khách tự 'kích hoạt' những cảnh sinh hoạt tí hon: hội hè, thể thao, lao động, thậm chí một pha vượt ngục hài hước. Dự án do doanh nhân Sergey Morozov khởi xướng, mất khoảng 5 năm và hơn một trăm người thực hiện. Đây là điểm đến lý tưởng cho gia đình có trẻ nhỏ và cho bất kỳ ai muốn 'đi hết nước Nga' chỉ trong một, hai giờ đồng hồ.",
        ["Mô hình lớn nhất nước Nga, lớn thứ hai thế giới (sau Miniatur Wunderland, Hamburg).",
         "Khoảng 800 m², tỉ lệ 1:87; hơn 2.500 m đường ray và hàng nghìn phương tiện chuyển động.",
         "Chu kỳ ngày–đêm đổi khoảng mỗi 13 phút với hơn 800.000 đèn LED; nhiều nút bấm tương tác."],
        ["modern", "family", "interactive", "museum"],
        {"hours_vi": "Thường mở cửa hằng ngày (khoảng 10:00–20:00); nên kiểm tra giờ cập nhật trên trang chính thức.",
         "ticket_vi": "Có thu phí (vé người lớn / trẻ em); xem giá mới nhất trên trang chính thức.",
         "duration_vi": "1–2 giờ.",
         "best_time_vi": "Ngày thường để tránh đông; nên đợi xem một chu kỳ ngày–đêm.",
         "tips_vi": "Gần metro Moskovskiye Vorota; canh xem cảnh chuyển đêm và thử các nút bấm tương tác cùng trẻ nhỏ."}),

    # === Đợt bổ sung 2026-07-24: 2 địa danh Moskva + 1 chùa Phật giáo SPb (còn thiếu) ===
    rec("moscow", "triumphal-arch",
        "Khải Hoàn Môn Moskva (Triumfalnaya Arka)", "Триумфальная арка", "Triumphal Arch of Moscow",
        ["monument"], 55.73675, 37.51992,
        "Quảng trường Chiến Thắng, Đại lộ Kutuzovsky, gần đồi Poklonnaya, Moskva (gần metro Park Pobedy)",
        "Khải Hoàn Môn Moskva là đài chiến thắng tôn vinh chiến công đánh bại Napoléon năm 1812. Cổng đá do kiến trúc sư Osip Bove dựng năm 1834, bị tháo dỡ thời Stalin rồi phục dựng năm 1968 trên Đại lộ Kutuzovsky, cạnh đồi Poklonnaya.",
        "Khải Hoàn Môn Moskva là khúc khải hoàn ca bằng đá và gang tôn vinh chiến thắng của nước Nga trước đạo quân Napoléon trong cuộc Chiến tranh Vệ quốc năm 1812. Cổng đá đầu tiên do kiến trúc sư Osip Bove thiết kế, dựng trong các năm 1829–1834 tại Quảng trường Tverskaya Zastava, thay cho một cổng gỗ tạm mà các cựu binh đã lập năm 1814 để đón đoàn quân chiến thắng trở về. Vòm cổng được ốp đá, trang trí bằng những hàng cột và tượng chiến binh bằng gang; trên đỉnh là cỗ xe sáu ngựa (quadriga) do nhà điêu khắc Ivan Vitali thực hiện. Năm 1936, trong đợt cải tạo trung tâm Moskva thời Stalin, cổng bị tháo dỡ, phần tượng được cất giữ tại bảo tàng kiến trúc trong khuôn viên Tu viện Donskoy. Mãi tới các năm 1966–1968, công trình mới được phục dựng theo đúng bản vẽ gốc của Bove, lần này đặt giữa Đại lộ Kutuzovsky — con đường mang tên vị Nguyên soái đã dẫn dắt nước Nga chiến thắng — ngay cạnh đồi Poklonnaya và Công viên Chiến Thắng. Khoảng không quanh cổng nay gọi là Quảng trường Chiến Thắng. Với du khách, đây là điểm dừng bề thế để chụp ảnh và cảm nhận niềm tự hào lịch sử, thường kết hợp cùng cụm tưởng niệm trên đồi Poklonnaya.",
        ["Tôn vinh chiến thắng trước Napoléon trong Chiến tranh Vệ quốc 1812.",
         "Kiến trúc sư Osip Bove; cỗ xe sáu ngựa trên đỉnh do Ivan Vitali điêu khắc.",
         "Dựng 1834 ở Tverskaya Zastava, tháo dỡ 1936, phục dựng 1966–1968 trên Đại lộ Kutuzovsky."],
        ["monument", "history", "landmark", "1812"],
        {"hours_vi": "Đài ngoài trời, tham quan tự do mọi thời điểm (chỉ ngắm từ bên ngoài).",
         "ticket_vi": "Miễn phí.",
         "duration_vi": "20–30 phút.",
         "best_time_vi": "Ban ngày để chụp ảnh; buổi tối có đèn chiếu sáng.",
         "tips_vi": "Cổng nằm giữa dải phân cách của đại lộ lớn — chú ý an toàn khi băng qua; kết hợp tham quan đồi Poklonnaya và Công viên Chiến Thắng gần đó."},
        [{"title": "Triumphal Arch of Moscow — Wikipedia", "url": "https://en.wikipedia.org/wiki/Triumphal_Arch_of_Moscow"}]),

    rec("moscow", "kotelnicheskaya-building",
        "Toà nhà bên bờ kè Kotelnicheskaya — một trong 'Bảy chị em Stalin'", "Жилой дом на Котельнической набережной", "Kotelnicheskaya Embankment Building",
        ["monument"], 55.74720, 37.64470,
        "Bờ kè Kotelnicheskaya 1/15, nơi hợp lưu sông Moskva và sông Yauza, Moskva (gần metro Taganskaya / Kitay-Gorod)",
        "Một trong 'Bảy chị em Stalin' — bảy toà nhà chọc trời tân cổ điển làm nên đường chân trời Moskva. Toà nhà cao 176 m bên chỗ hợp lưu sông Moskva và Yauza, hoàn thành năm 1952, từng là nhà cao nhất châu Âu và là chung cư danh giá của giới tinh hoa Xô-viết.",
        "Vươn lên từ nơi sông Yauza đổ vào sông Moskva, toà nhà bên bờ kè Kotelnicheskaya là một trong 'Bảy chị em Stalin' (Семь сестёр) — bảy toà tháp tân cổ điển được xây sau Thế chiến II để định hình đường chân trời của thủ đô Xô-viết. Khởi công năm 1947 và hoàn thành năm 1952 theo thiết kế của kiến trúc sư trưởng Moskva Dmitry Chechulin cùng Andrei Rostkovsky, công trình cao 176 m với tháp trung tâm 32 tầng, mang dáng 'bánh cưới' nhiều bậc bằng đá màu kem đặc trưng cho phong cách Đế chế Stalin. Trong khoảng 1952–1953, đây từng là toà nhà cao nhất châu Âu. Khác với các 'chị em' vốn là khách sạn, trường đại học hay bộ ngành, Kotelnicheskaya được dựng làm chung cư cao cấp cho tầng lớp tinh hoa: nghệ sĩ, nhà văn, tướng lĩnh và quan chức. Cư dân nổi tiếng nhất là Galina Ulanova, prima ballerina huyền thoại của Nhà hát Bolshoi, sống ở đây từ 1952 đến khi qua đời năm 1998; căn hộ của bà nay là nhà lưu niệm. Một phần công trình được xây bằng sức lao động của tù nhân — lát cắt gai góc trong lịch sử của nó. Du khách không vào khu căn hộ, nhưng có thể chiêm ngưỡng khối kiến trúc bề thế từ bờ kè và các cây cầu lân cận — một trong những góc chụp ảnh đẹp nhất để cảm nhận tinh thần kiến trúc Xô-viết.",
        ["Một trong 'Bảy chị em Stalin' — cụm nhà chọc trời tân cổ điển biểu tượng của Moskva.",
         "Cao 176 m, hoàn thành 1952; từng là toà nhà cao nhất châu Âu (1952–1953).",
         "Chung cư của giới tinh hoa Xô-viết; cư dân nổi tiếng nhất là nghệ sĩ ballet Galina Ulanova."],
        ["monument", "architecture", "soviet", "landmark", "skyscraper"],
        {"hours_vi": "Chỉ ngắm từ bên ngoài; khu căn hộ là nhà ở riêng, không mở tham quan.",
         "ticket_vi": "Miễn phí (ngắm ngoại thất).",
         "duration_vi": "20–30 phút.",
         "best_time_vi": "Sáng hoặc chiều muộn để chụp ảnh bên sông.",
         "tips_vi": "Góc chụp toàn cảnh đẹp nhất từ bờ kè đối diện hoặc các cầu bắc qua sông Moskva; tầng trệt có hiệu bánh và cửa hàng lâu đời."},
        [{"title": "Kotelnicheskaya Embankment Building — Wikipedia", "url": "https://en.wikipedia.org/wiki/Kotelnicheskaya_Embankment_Building"}]),

    rec("saint-petersburg", "datsan-gunzechoinei",
        "Chùa Phật giáo Datsan Gunzechoinei (Đa-xan Gun-dê-choi-nây)", "Дацан Гунзэчойнэй", "Datsan Gunzechoinei (Buddhist Temple)",
        ["church"], 59.98347, 30.25589,
        "Đại lộ Primorsky 91, khu Staraya Derevnya, quận Primorsky, Saint Petersburg (gần metro Staraya Derevnya)",
        "Ngôi chùa Phật giáo Tây Tạng ở cực Bắc châu Âu, xây năm 1909–1915 theo phong cách datsan Tây Tạng. Công trình do kiến trúc sư Gavriil Baranovsky thiết kế, với cửa kính màu của danh hoạ Nicholas Roerich — một góc phương Đông độc đáo giữa Saint Petersburg.",
        "Giữa một thành phố nổi tiếng với những nhà thờ Chính thống giáo mái vòm củ hành, Datsan Gunzechoinei mang đến một thanh âm hoàn toàn khác: đây là ngôi chùa Phật giáo Tây Tạng nằm ở cực Bắc của châu Âu. Công trình ra đời nhờ nỗ lực của Agvan Dorzhiev — nhà ngoại giao kiêm cao tăng, đại diện của Đức Đạt Lai Lạt Ma thứ 13 — người đã xin được phép của Sa hoàng Nicholas II để dựng chùa, bất chấp sự phản đối gay gắt của Giáo hội Chính thống đương thời. Được xây trong các năm 1909–1915 theo thiết kế của kiến trúc sư Gavriil Baranovsky (cũng là người thiết kế cửa hàng Eliseyev trứ danh trên Đại lộ Nevsky), ngôi chùa phỏng theo kiến trúc datsan Tây Tạng nhưng dùng vật liệu hiện đại: đá granite Phần Lan và bê tông cốt thép, điểm xuyết những ô cửa kính màu do danh hoạ Nicholas Roerich thiết kế. Lễ đầu tiên cử hành năm 1913, chùa khánh thành trọn vẹn năm 1915. Sau Cách mạng, chùa bị đóng cửa, cướp phá và trải qua thời kỳ đàn áp khắc nghiệt; mãi tới năm 1989 cộng đồng Phật tử mới được công nhận trở lại và nơi đây hồi sinh thành trung tâm tu học của phái Gelug (Mũ Vàng). Ngày nay, du khách có thể ghé thăm chính điện trang nghiêm, chiêm ngưỡng pho tượng Phật và tìm một khoảng lặng thiền định hiếm có ở phương Bắc.",
        ["Ngôi chùa Phật giáo Tây Tạng ở cực Bắc châu Âu.",
         "Xây 1909–1915; kiến trúc sư Gavriil Baranovsky, cửa kính màu của danh hoạ Nicholas Roerich.",
         "Khởi xướng bởi cao tăng Agvan Dorzhiev với sự cho phép của Sa hoàng Nicholas II; nay là trung tâm phái Gelug."],
        ["church", "buddhist", "unique", "culture", "history"],
        {"hours_vi": "Mở cửa gần như hằng ngày (thường từ sáng đến chiều); giờ có thể thay đổi theo lịch lễ — nên kiểm tra trước.",
         "ticket_vi": "Vào cửa tự do; hoan nghênh đóng góp tuỳ tâm.",
         "duration_vi": "45–60 phút.",
         "best_time_vi": "Buổi sáng yên tĩnh; tránh giờ hành lễ nếu chỉ muốn tham quan.",
         "tips_vi": "Ăn mặc kín đáo, cởi giày và giữ yên lặng khi vào chính điện; kết hợp dạo đảo Elagin và Công viên Trung tâm gần đó."},
        [{"title": "Datsan Gunzechoinei — Wikipedia", "url": "https://en.wikipedia.org/wiki/Datsan_Gunzechoinei"},
         {"title": "St Petersburg Datsan — Bảo tàng Lịch sử Saint Petersburg", "url": "https://www.spbmuseum.ru/exhibits_and_exhibitions/temporary_exhibitions/48012/?lang_ui=en"}]),

    # ==== Bổ sung ngày 2026-07-24 (tác vụ tự động bảo trì) ====
    rec("moscow", "nikolskaya-street",
        "Phố đi bộ Nikolskaya (Ni-côn-xkai-a)", "Никольская улица", "Nikolskaya Street",
        ["square_street"], 55.757261, 37.622683,
        "Nối Quảng trường Đỏ với Quảng trường Lubyanka, khu Kitay-gorod, Moskva 109012 (gần metro Ploshchad Revolyutsii và Lubyanka).",
        "Phố đi bộ Nikolskaya dài khoảng 630 m nối Quảng trường Đỏ với Quảng trường Lubyanka — một trong những con phố cổ và sầm uất nhất Moskva. Nơi đây gắn với nhà in đầu tiên của nước Nga và nổi tiếng với những vòm đèn lung linh, từng là tâm điểm ăn mừng của cổ động viên trong kỳ World Cup 2018.",
        "Nằm giữa lòng khu thương mại cổ Kitay-gorod, Nikolskaya là một trong những con phố lâu đời nhất Moskva, hình thành từ thế kỷ 13 như một phần của con đường Vladimir nối kinh đô với các thành cổ Vladimir, Suzdal và Rostov. Suốt nhiều thế kỷ, đây là trung tâm buôn bán và học thuật của thành phố. Chính tại con phố này, Nhà in Nhà nước (Pechatny Dvor) đã cho ra đời cuốn 'Apostol' năm 1564 — cuốn sách in có ghi niên đại đầu tiên của nước Nga, do Ivan Fyodorov và Pyotr Mstislavets thực hiện. Gần đó, Học viện Slav–Hy Lạp–Latinh, cơ sở giáo dục bậc cao đầu tiên của Nga (nơi nhà bác học Lomonosov từng theo học), cũng tọa lạc bên phố. Con phố quy tụ nhiều công trình đẹp: nhà thờ Kazan ở đầu phố, Xưởng đúc tiền cũ và tòa nhà Nhà in Thượng hội đồng mang phong cách tân Gothic độc đáo. Được chuyển thành phố đi bộ vào tháng 8 năm 2013, Nikolskaya ngày nay rực rỡ với những vòm đèn trang trí giăng ngang trời — hình ảnh đã lan truyền khắp thế giới khi nơi đây trở thành điểm tụ họp, ca hát của người hâm mộ bóng đá dịp World Cup 2018. Dạo bộ ở đây, du khách vừa ngắm kiến trúc, vừa ghé các cửa hiệu và quán cà phê sang trọng.",
        ["Một trong những phố cổ nhất Moskva (từ thế kỷ 13), thuộc khu thương mại lịch sử Kitay-gorod.",
         "Nơi ra đời 'Apostol' (1564) — sách in có niên đại đầu tiên của Nga; gần Học viện Slav–Hy Lạp–Latinh.",
         "Phố đi bộ với những vòm đèn nổi tiếng; từng là tâm điểm ăn mừng World Cup 2018."],
        ["free", "outdoor", "night", "walking", "history", "shopping"],
        practical={"hours_vi": "Phố mở suốt ngày đêm; đẹp nhất khi lên đèn buổi tối.",
                   "ticket_vi": "Miễn phí.",
                   "duration_vi": "30–60 phút.",
                   "best_time_vi": "Buổi tối để ngắm vòm đèn; dịp lễ hội có trang trí đặc biệt.",
                   "tips_vi": "Kết hợp tham quan Quảng trường Đỏ, cửa hàng GUM và ngõ Tretyakovsky; dọc phố có nhiều quán cà phê và nhà hàng."},
        sources=[{"title": "Nikolskaya Street — Wikipedia", "url": "https://en.wikipedia.org/wiki/Nikolskaya_Street"},
                 {"title": "Moscow Print Yard — Wikipedia", "url": "https://en.wikipedia.org/wiki/Moscow_Print_Yard"}]),

    rec("moscow", "art-theatre-chekhov",
        "Nhà hát Nghệ thuật Moskva mang tên Chekhov (Sê-khốp) – MKhT", "Московский Художественный театр имени А. П. Чехова", "Moscow Art Theatre (Chekhov)",
        ["theatre"], 55.76028, 37.61306,
        "Ngõ Kamergersky, số 3, Moskva 125009 (gần metro Teatralnaya, Okhotny Ryad và Ploshchad Revolyutsii).",
        "Nhà hát Nghệ thuật Moskva do Konstantin Stanislavski và Vladimir Nemirovich-Danchenko sáng lập năm 1898 — cái nôi của 'hệ thống Stanislavski' và của kịch Chekhov. Trụ sở lịch sử trong ngõ Kamergersky mang phong cách Art Nouveau, với cánh chim hải âu làm biểu tượng.",
        "Ra đời năm 1898 từ cuộc gặp gỡ lịch sử giữa đạo diễn Konstantin Stanislavski và nhà viết kịch Vladimir Nemirovich-Danchenko, Nhà hát Nghệ thuật Moskva đã tạo nên một cuộc cách mạng cho sân khấu thế giới. Thay cho lối diễn phô trương thịnh hành thời đó, nhà hát đề cao sự chân thực tâm lý và diễn xuất tự nhiên — nền tảng của 'hệ thống Stanislavski' mà về sau lan tỏa thành 'phương pháp diễn xuất' (Method acting) ở phương Tây. Cũng năm 1898, vở 'Chim hải âu' của Anton Chekhov — từng thất bại tại Saint Petersburg — được dàn dựng lại ở đây và thành công vang dội, mở ra mối lương duyên bền chặt giữa nhà hát và Chekhov; từ đó, cánh chim hải âu trở thành biểu tượng in trên tấm màn sân khấu. Nhà hát lần lượt công diễn các kiệt tác 'Cậu Vanya', 'Ba chị em' và 'Vườn anh đào'. Năm 1902, nhờ nhà bảo trợ Savva Morozov, đoàn chuyển về tòa nhà trong ngõ Kamergersky, được kiến trúc sư Fyodor Schechtel cải tạo theo phong cách Art Nouveau (Moderne) tinh tế. Năm 1987, nhà hát tách làm hai; nhánh ở ngõ Kamergersky mang tên Chekhov (MKhT) và tới nay vẫn là một trong những sân khấu danh giá, hiện đại bậc nhất nước Nga.",
        ["Do Stanislavski và Nemirovich-Danchenko sáng lập năm 1898; cái nôi của 'hệ thống Stanislavski'.",
         "Nơi 'Chim hải âu' của Chekhov thành công vang dội (1898) — hải âu trở thành biểu tượng nhà hát.",
         "Trụ sở trong ngõ Kamergersky do kiến trúc sư Fyodor Schechtel cải tạo theo phong cách Art Nouveau."],
        ["theatre", "culture", "history", "architecture", "indoor"],
        practical={"hours_vi": "Mở cửa theo suất diễn (thường buổi tối, thêm suất chiều cuối tuần); phòng vé mở ban ngày.",
                   "ticket_vi": "Giá vé thay đổi theo vở diễn và vị trí ghế; nên đặt trước, nhất là các vở kinh điển.",
                   "duration_vi": "Buổi diễn khoảng 2,5–3 giờ; ngắm ngoại thất 10–15 phút.",
                   "best_time_vi": "Buổi tối để xem diễn; lưu ý các vở diễn bằng tiếng Nga.",
                   "tips_vi": "Đặt vé trên trang chính thức; ngõ Kamergersky là phố đi bộ nhỏ xinh nhiều quán cà phê, gần Quảng trường Nhà hát và Nhà hát Bolshoi."},
        sources=[{"title": "Moscow Chekhov Art Theatre — Wikipedia", "url": "https://en.wikipedia.org/wiki/Moscow_Chekhov_Art_Theatre"},
                 {"title": "Moscow Art Theatre — Britannica", "url": "https://www.britannica.com/topic/Moscow-Art-Theatre"}],
        official_site="https://mxat.ru"),

    rec("saint-petersburg", "island-of-forts",
        "Công viên Bảo tàng 'Đảo Pháo đài' (Ô-xtrốp Phoóc-tốp), Kronstadt", "Музейно-исторический парк «Остров фортов»", "Island of Forts (Ostrov Fortov), Kronstadt",
        ["park_garden", "museum"], 59.99445, 29.74250,
        "Thành phố Kronstadt, đảo Kotlin, Saint Petersburg (cách trung tâm khoảng 40 km về phía tây, đi qua tuyến đê chắn KAD).",
        "Công viên hải quân đầu tiên và lớn nhất nước Nga, khai trương năm 2020 trên đảo Kotlin ở quân cảng Kronstadt. Điểm nhấn là Bảo tàng Vinh quang Hải quân với tàu ngầm hạt nhân đầu tiên của Liên Xô K-3 'Leninsky Komsomol'.",
        "Khánh thành giai đoạn đầu năm 2020, 'Đảo Pháo đài' là công viên chủ đề hải quân đầu tiên và lớn nhất nước Nga, nằm trên đảo Kotlin thuộc thành phố quân cảng lịch sử Kronstadt. Trung tâm công viên là 'Đại lộ Anh hùng Hải quân Nga' tái hiện hơn ba thế kỷ lịch sử hải quân kể từ thời Pyotr Đại đế, cùng 'Ngọn hải đăng Ký ức' khắc tên hàng trăm thủy thủ anh hùng qua các thời kỳ. Không gian rộng thoáng ven biển với lối đi dạo, khu vui chơi trẻ em, mô hình thuyền buồm và tổ hợp huấn luyện 'Anh hùng đích thực' khiến nơi đây thành điểm đến lý tưởng cho gia đình. Năm 2023, quần thể đón thêm Bảo tàng Vinh quang Hải quân với hiện vật trung tâm là tàu ngầm K-3 'Leninsky Komsomol' — tàu ngầm nguyên tử đầu tiên của Liên Xô và là chiếc thứ ba trên thế giới — được đưa từ Severodvinsk về lắp đặt tại đây. Con tàu khổng lồ được trưng bày trong một gian bảo tàng hiện đại, cho phép du khách bước vào bên trong khám phá đời sống dưới lòng biển. 'Đảo Pháo đài' là mảnh ghép hiện đại làm sống lại di sản pháo đài biển của Kronstadt, hòa quyện giữa nghỉ ngơi, giáo dục và niềm tự hào lịch sử.",
        ["Công viên hải quân đầu tiên và lớn nhất nước Nga (khai trương 2020) trên đảo Kotlin, Kronstadt.",
         "Bảo tàng Vinh quang Hải quân (2023) trưng bày tàu ngầm hạt nhân đầu tiên của Liên Xô K-3 'Leninsky Komsomol'.",
         "Đại lộ Anh hùng Hải quân và Ngọn hải đăng Ký ức tôn vinh hơn 300 năm lịch sử hải quân Nga."],
        ["modern", "park", "waterfront", "family", "navy", "museum", "free"],
        practical={"hours_vi": "Công viên mở cửa hằng ngày, tự do; Bảo tàng Vinh quang Hải quân có giờ mở riêng và cần vé (nên đặt trước).",
                   "ticket_vi": "Vào công viên miễn phí; tham quan tàu ngầm K-3 và bảo tàng phải mua vé.",
                   "duration_vi": "Nửa ngày (khoảng 2–4 giờ) nếu kết hợp công viên và bảo tàng.",
                   "best_time_vi": "Mùa hè và đầu thu khi thời tiết ven vịnh dễ chịu.",
                   "tips_vi": "Kết hợp tham quan Nhà thờ Hải quân Kronstadt và các pháo đài trên vịnh; đi từ Saint Petersburg bằng ô tô/xe buýt qua đê chắn khoảng 1 giờ."},
        sources=[{"title": "Museum and Historical Park 'Ostrov Fortov' — Visit Petersburg", "url": "https://www.visit-petersburg.ru/en/leisure/places/muzeynyy-kompleks-ostrov-fortov/"},
                 {"title": "Soviet submarine K-3 Leninsky Komsomol — Wikipedia", "url": "https://en.wikipedia.org/wiki/Soviet_submarine_K-3_Leninsky_Komsomol"}]),

    rec("saint-petersburg", "alexander-palace",
        "Cung điện Alexander (Aleksandrovsky Dvorets), Tsarskoye Selo", "Александровский дворец", "Alexander Palace (Tsarskoye Selo)",
        ["palace"], 59.72100, 30.39260,
        "Dvortsovaya ul., 2, thành phố Pushkin (Tsarskoye Selo), Saint Petersburg (cách trung tâm ~25 km về phía nam)",
        "Cung điện Tân cổ điển do kiến trúc sư Giacomo Quarenghi thiết kế theo lệnh Nữ hoàng Ekaterina Đại đế, và là nơi ở yêu thích cuối cùng của Sa hoàng Nicholas II cùng gia đình. Sau nhiều năm trùng tu, cung điện mở cửa trở lại năm 2021 với các căn phòng riêng của hoàng gia được phục dựng tinh xảo.",
        "Ẩn mình trong Công viên Alexander yên tĩnh, cách Cung điện Ekaterina lộng lẫy không xa, Cung điện Alexander mang vẻ đẹp trầm lặng và rất riêng tư. Công trình được Nữ hoàng Ekaterina Đại đế đặt xây năm 1792 làm quà cho người cháu yêu — vị hoàng đế tương lai Aleksandr I — do kiến trúc sư người Ý Giacomo Quarenghi thiết kế theo phong cách Tân cổ điển thanh nhã, nổi bật với hàng cột đôi ở mặt tiền. Nhưng cung điện được cả thế giới biết đến nhất với tư cách tổ ấm gắn bó của vị Sa hoàng cuối cùng Nicholas II: chính tại đây gia đình ông sống những năm tháng đời thường nhất, và cũng tại đây họ bị quản thúc sau khi chế độ quân chủ sụp đổ năm 1917, trước khi bị đưa đi Siberia. Hoàng hậu Aleksandra từng cho trang trí nhiều phòng theo phong cách Art Nouveau hiện đại thời bấy giờ, trong đó nổi tiếng nhất là 'Phòng Tím' (Mauve Boudoir). Sau đợt đại trùng tu kéo dài nhiều năm, cánh đông của cung điện — nơi đặt các phòng riêng của Nicholas II và hoàng hậu — đã mở cửa lại từ tháng 8 năm 2021, đưa du khách trở về không khí sinh hoạt của hoàng gia Nga những ngày cuối cùng.",
        ["Do kiến trúc sư Giacomo Quarenghi thiết kế (1792–1796) theo lệnh Ekaterina Đại đế, phong cách Tân cổ điển.",
         "Nơi ở yêu thích và cũng là nơi bị quản thúc cuối cùng của Sa hoàng Nicholas II cùng gia đình (1917).",
         "Mở cửa trở lại năm 2021 sau trùng tu; nổi bật 'Phòng Tím' của Hoàng hậu Aleksandra và các phòng riêng hoàng gia."],
        ["palace", "romanov", "history", "daytrip", "indoor"],
        practical={"hours_vi": "Thường 10:00–18:00, đóng cửa Thứ Ba và ngày vệ sinh cuối tháng (kiểm tra lịch chính thức).",
                   "ticket_vi": "Có thu phí; nên đặt vé theo suất giờ trước trên trang chính thức của bảo tàng.",
                   "duration_vi": "1,5–2 giờ.",
                   "best_time_vi": "Kết hợp trong ngày tham quan Tsarskoye Selo cùng Cung điện Ekaterina.",
                   "tips_vi": "Vé thường bán theo khung giờ và nhanh hết; đi cùng buổi với Cung điện Ekaterina và Công viên Alexander."},
        sources=[{"title": "Alexander Palace — Tsarskoye Selo State Museum", "url": "https://www.tzar.ru/en/objects/alexandrovsky"},
                 {"title": "Alexander Palace — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Alexander_Palace"}],
        official_site="https://tzar.ru"),

    rec("sverdlovsk", "yeltsin-center",
        "Trung tâm Yeltsin (Yeltsin Center), Yekaterinburg", "Ельцин-центр (Президентский центр Б. Н. Ельцина)", "Boris Yeltsin Presidential Center",
        ["museum"], 56.84450, 60.59110,
        "Ul. Borisa Yeltsina 3, ven sông Iset, trung tâm Yekaterinburg, tỉnh Sverdlovsk",
        "Tổ hợp văn hóa – giáo dục hiện đại khánh thành năm 2015 bên sông Iset, với điểm nhấn là Bảo tàng Boris Yeltsin kể lại lịch sử chính trị nước Nga thập niên 1990 qua 'bảy ngày' bước ngoặt. Năm 2017, nơi đây được Hội đồng châu Âu vinh danh là bảo tàng xuất sắc nhất châu Âu.",
        "Nằm bên bờ sông Iset giữa lòng Yekaterinburg, Trung tâm Yeltsin là một trong những không gian bảo tàng hiện đại và cũng gây tranh luận nhất nước Nga. Khánh thành năm 2015, công trình do kiến trúc sư Boris Bernaskoni thiết kế với khối kiến trúc tương lai, mặt ngoài bằng kim loại đục lỗ có thể biến thành màn hình media khổng lồ khi đêm xuống. Trái tim của tổ hợp là Bảo tàng Boris Yeltsin, dành cho vị Tổng thống đầu tiên của nước Nga và giai đoạn lịch sử đầy biến động cuối thập niên 1980 đến 1990. Lối trưng bày giàu tính điện ảnh: hành trình được chia thành 'bảy ngày' — bảy bước ngoặt như cuộc mít tinh đòi đổi thay, cuộc đảo chính tháng Tám 1991, những cải cách kinh tế đau đớn, sự ra đời của Hiến pháp mới — với các không gian tái dựng sống động căn hộ, đường phố và phòng làm việc của thời kỳ ấy. Năm 2017, Trung tâm được Hội đồng châu Âu trao giải Bảo tàng châu Âu xuất sắc, lần đầu tiên cho một bảo tàng Nga. Ngoài bảo tàng, nơi đây còn có phòng tranh nghệ thuật, rạp chiếu kiêm hội trường, hiệu sách và thường xuyên tổ chức hòa nhạc, liên hoan phim, các buổi diễn thuyết — trở thành điểm hẹn văn hóa sôi động của cả vùng Ural.",
        ["Khánh thành năm 2015; kiến trúc tương lai của Boris Bernaskoni, mặt ngoài biến thành màn hình media về đêm.",
         "Bảo tàng Boris Yeltsin kể lịch sử nước Nga thập niên 1990 qua 'bảy ngày' bước ngoặt, trưng bày giàu tính điện ảnh.",
         "Được Hội đồng châu Âu vinh danh Bảo tàng châu Âu xuất sắc 2017 — bảo tàng Nga đầu tiên đoạt giải."],
        ["modern", "museum", "history", "architecture", "indoor"],
        practical={"hours_vi": "Bảo tàng thường mở 10:00–21:00, đóng cửa Thứ Hai (kiểm tra lịch chính thức).",
                   "ticket_vi": "Có thu phí vé vào Bảo tàng Yeltsin; nhiều khu vực công cộng khác vào tự do.",
                   "duration_vi": "1,5–2,5 giờ.",
                   "best_time_vi": "Quanh năm (không gian trong nhà).",
                   "tips_vi": "Có audio guide; kết hợp dạo bờ kè sông Iset và khu Ekaterinburg-City gần đó."},
        sources=[{"title": "Boris Yeltsin Presidential Center — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Boris_Yeltsin_Presidential_Center"},
                 {"title": "Yeltsin Center — trang chính thức", "url": "https://yeltsin.ru/"}],
        official_site="https://yeltsin.ru"),

    rec("moscow", "novodevichy-cemetery",
        "Nghĩa trang Novodevichy (Novodevichye Kladbishche)", "Новодевичье кладбище", "Novodevichy Cemetery",
        ["monument", "park_garden"], 55.72472, 37.55417,
        "Luzhnetsky proezd, 2, quận Khamovniki, Moskva (liền kề Tu viện Novodevichy, gần metro Sportivnaya)",
        "Nghĩa trang danh giá bậc nhất nước Nga, nằm liền kề Tu viện Novodevichy — nơi an nghỉ của Chekhov, Gogol, Bulgakov, Prokofiev, Shostakovich cùng nhiều nguyên thủ và danh nhân. Không gian như một công viên điêu khắc ngoài trời với hàng nghìn bia mộ nghệ thuật.",
        "Nép bên bức tường phía nam của Tu viện Novodevichy cổ kính, Nghĩa trang Novodevichy không chỉ là nơi yên nghỉ mà còn là một 'bảo tàng điêu khắc' ngoài trời độc đáo và là biểu tượng ký ức của nước Nga. Được kiến trúc sư Ivan Mashkov quy hoạch và khánh thành năm 1898, nghĩa trang trở nên đặc biệt quan trọng từ thập niên 1930, khi hài cốt nhiều danh nhân — trong đó có văn hào Nikolai Gogol — được cải táng về đây sau khi các nghĩa địa tu viện cũ bị phá bỏ. Suốt thời Xô-viết, được an táng ở Novodevichy là vinh dự chỉ đứng sau Nghĩa trang Tường Kremlin. Dạo bước giữa hơn 26.000 ngôi mộ, du khách như đi qua cả pho lịch sử văn hóa Nga: nhà viết kịch Anton Chekhov và người khai sinh sân khấu hiện đại Konstantin Stanislavsky yên nghỉ trong khu 'Vườn Anh Đào'; gần đó là mộ nhà văn Mikhail Bulgakov, các nhà soạn nhạc Sergei Prokofiev và Dmitri Shostakovich, cùng những nhân vật chính trị như Nikita Khrushchev, Boris Yeltsin và Mikhail Gorbachev. Mỗi tấm bia là một tác phẩm nghệ thuật riêng, khắc họa cá tính người nằm dưới mộ. Với không gian tĩnh lặng, rợp bóng cây và đầy tượng đài tinh xảo, Novodevichy là điểm đến trầm mặc nhưng giàu chiều sâu cho ai muốn hiểu tâm hồn và lịch sử nước Nga.",
        ["Nghĩa trang danh giá bậc nhất nước Nga (chỉ sau Nghĩa trang Tường Kremlin); quy hoạch bởi Ivan Mashkov, mở năm 1898.",
         "Nơi an nghỉ của Chekhov, Gogol, Bulgakov, Prokofiev, Shostakovich, Stanislavsky và các nguyên thủ Khrushchev, Yeltsin, Gorbachev.",
         "Hơn 26.000 ngôi mộ với bia đá điêu khắc nghệ thuật — như một bảo tàng ngoài trời; nổi bật khu 'Vườn Anh Đào' của Chekhov và Stanislavsky."],
        ["monument", "history", "culture", "park", "outdoor"],
        practical={"hours_vi": "Thường mở cửa hằng ngày khoảng 09:00–17:00 (có thể thay đổi theo mùa).",
                   "ticket_vi": "Vào cửa miễn phí hoặc phí tượng trưng; có sơ đồ mộ danh nhân tại cổng.",
                   "duration_vi": "1–1,5 giờ.",
                   "best_time_vi": "Cuối xuân đến đầu thu, khi cây xanh và thời tiết dễ chịu.",
                   "tips_vi": "Hỏi sơ đồ tại văn phòng để tìm mộ danh nhân; kết hợp tham quan Tu viện Novodevichy và hồ nước liền kề; giữ thái độ trang nghiêm."},
        sources=[{"title": "Novodevichy Cemetery — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Novodevichy_Cemetery"},
                 {"title": "Novodevichy Cemetery — Atlas Obscura", "url": "https://www.atlasobscura.com/places/novodevichy-cemetery"}]),

    rec("moscow", "kremlin-armoury",
        "Bảo tàng Kho báu Kremlin (Oruzheynaya Palata)", "Оружейная палата", "Kremlin Armoury",
        ["museum"], 55.74951, 37.61331,
        "Bên trong Điện Kremlin, Moskva (góc tây nam; vào Kremlin qua Tháp Kutafya–Troitskaya, gần Tháp Borovitskaya)",
        "Bảo tàng kho báu hoàng gia nằm trong Điện Kremlin, trưng bày hơn bốn nghìn báu vật của các Sa hoàng: vương miện, quyền trượng, lễ phục đăng quang, vũ khí nghi lễ, xe ngựa dát vàng và bộ sưu tập trứng Phục sinh Fabergé lừng danh. Khách vào theo khung giờ cố định, vé tách riêng với vé tham quan Kremlin.",
        "Nằm ở góc tây nam bên trong Điện Kremlin, Oruzheynaya Palata — thường được dịch là 'Cung Vũ khí' — thực chất là kho báu và là một trong những bảo tàng lâu đời bậc nhất nước Nga. Khởi nguồn từ các xưởng chế tác vũ khí và đồ ngự dụng của triều đình từ thế kỷ 16, bộ sưu tập được mở như một bảo tàng công cộng từ đầu thế kỷ 19 và chuyển vào toà nhà tân-Nga hiện nay do kiến trúc sư Konstantin Thon thiết kế, hoàn thành năm 1851. Hơn bốn nghìn hiện vật bày trong chín gian phòng kể lại nghi lễ, quyền lực và đời sống xa hoa của các Sa hoàng: mũ miện Monomakh phủ lông chồn nạm đá quý — biểu tượng quyền lực Nga cổ; các vương miện, quyền trượng, quả cầu quyền lực; áo choàng và lễ phục đăng quang; kho vũ khí, áo giáp và yên cương lộng lẫy; đoàn xe ngựa cùng xe trượt tuyết nghi lễ từ thế kỷ 16–18. Nổi bật nhất với du khách quốc tế là mười quả trứng Phục sinh Hoàng gia do nhà kim hoàn Fabergé chế tác tặng hoàng hậu, mỗi quả giấu một 'bất ngờ' tinh xảo bên trong. Vì không gian hẹp và hiện vật vô giá, khách vào theo các khung giờ cố định trong ngày; nên đặt vé trực tuyến trước và lưu ý cấm chụp ảnh bên trong.",
        ["Mười quả trứng Phục sinh Hoàng gia Fabergé — bộ sưu tập trứ danh, mỗi quả ẩn giấu một 'bất ngờ' tinh xảo.",
         "Mũ miện Monomakh cùng dàn vương miện, quyền trượng và lễ phục đăng quang của các Sa hoàng.",
         "Đoàn xe ngựa, xe trượt tuyết nghi lễ và kho vũ khí — áo giáp dát vàng thế kỷ 16–18."],
        ["museum", "history", "indoor", "treasure", "must-see"],
        practical={"hours_vi": "Mở cửa hằng ngày trừ thứ Năm, 10:00–18:00; tham quan theo các khung giờ cố định: 10:00, 12:00, 14:30 và 16:30.",
                   "ticket_vi": "Khoảng 1.400 RUB/người lớn; dưới 16 tuổi khoảng 800 RUB; miễn phí trẻ dưới 7 tuổi. Vé Oruzheynaya Palata tách riêng với vé vào Kremlin, đặt tại tickets.kreml.ru.",
                   "duration_vi": "1,5–2 giờ.",
                   "best_time_vi": "Chọn khung giờ sáng (10:00) để tránh đông; đặt vé trước nhiều ngày vào mùa cao điểm.",
                   "tips_vi": "Cấm chụp ảnh bên trong. Đến sớm qua Tháp Kutafya–Troitskaya để kịp kiểm tra an ninh; kết hợp thăm Quảng trường Nhà thờ trong cùng buổi."},
        sources=[{"title": "Bảo tàng Điện Kremlin — Vé & thông tin (chính thức)", "url": "https://kreml.ru/en/tickets"},
                 {"title": "Kremlin Armoury Chamber — History and Highlights (MoscowPass)", "url": "https://moscowpass.com/blog/armoury-in-moscow-kremlin-armory-chamber-history-highlights/"},
                 {"title": "Moscow Kremlin: Tickets, What to See & Tips (Russiable)", "url": "https://russiable.com/kremlin-moscow-buy-tickets-online/"}],
        official_site="https://kreml.ru/en/"),

    rec("moscow", "zotov-center",
        "Trung tâm Zotov (Tsentr «Zotov»)", "Центр «Зотов»", "Zotov Center",
        ["museum"], 55.77030, 37.56461,
        "Khodynskaya Ulitsa 2, toà 1 (Nhà máy bánh mì số 5 cũ), quận Presnensky, Moskva (gần metro Ulitsa 1905 Goda)",
        "Trung tâm văn hoá hiện đại khai trương cuối năm 2022, là nơi đầu tiên ở Nga dành riêng cho việc nghiên cứu chủ nghĩa Kiến tạo (Constructivism). Đặt trong toà nhà máy bánh mì hình tròn năm 1931 — bản thân đã là một biểu tượng kiến trúc kiến tạo — vừa được trùng tu tinh tế.",
        "Khai trương cuối năm 2022, Trung tâm Zotov là không gian văn hoá đầu tiên tại Nga dành trọn cho chủ nghĩa Kiến tạo (Constructivism) — trào lưu nghệ thuật và kiến trúc tiên phong của thập niên 1920 — cùng ảnh hưởng của nó tới nghệ thuật đương đại. Điều đặc biệt là bản thân toà nhà đã là một 'hiện vật': đây nguyên là Nhà máy bánh mì số 5, xây năm 1931 theo hệ lò nướng vòng tự động do kỹ sư Georgy Marsakov sáng chế, với mặt bằng hình tròn đặc trưng — một biểu tượng của kiến trúc kiến tạo Xô-viết. Tên trung tâm lấy theo Vasily Zotov, người từng phụ trách xây dựng mạng lưới nhà máy bánh mì kiểu này và về sau trở thành Bộ trưởng công nghiệp thực phẩm. Từ năm 2018, nhóm kiến trúc sư của hãng SPEECH (Sergei Tchoban cùng cộng sự) đã trùng tu và cải tạo công trình theo nguyên tắc giữ lại tối đa 'các lớp thời gian': không chỉ phục dựng kiến trúc kiến tạo nguyên bản mà còn bảo tồn dấu vết biến đổi qua các thời kỳ sử dụng. Ngày nay Zotov là tổ hợp trưng bày sống động với các triển lãm chuyên đề, thư viện, hiệu sách, rạp chiếu phim, quán cà phê cùng chuỗi bài giảng, workshop cho trẻ em và người lớn, hoà nhạc thể nghiệm. Đây là điểm đến lý tưởng cho người yêu kiến trúc, thiết kế và lịch sử nghệ thuật thế kỷ 20.",
        ["Trung tâm đầu tiên ở Nga dành riêng cho chủ nghĩa Kiến tạo (Constructivism) — khai trương cuối năm 2022.",
         "Đặt trong Nhà máy bánh mì số 5 (1931) hình tròn theo hệ lò nướng vòng của kỹ sư Georgy Marsakov — biểu tượng kiến trúc kiến tạo.",
         "Trùng tu bởi hãng SPEECH (Sergei Tchoban), giữ lại 'các lớp thời gian'; nay là nơi triển lãm, giảng đường, rạp phim và hoà nhạc thể nghiệm."],
        ["museum", "architecture", "modern", "art", "indoor"],
        practical={"hours_vi": "Mở cửa theo lịch trung tâm (thường mở nhiều ngày trong tuần, đóng cửa muộn); nên kiểm tra lịch triển lãm và sự kiện trên trang chính thức trước khi đến.",
                   "ticket_vi": "Vé theo từng triển lãm; có vé combo và ưu đãi cho học sinh–sinh viên. Xem giá cập nhật tại centrezotov.ru.",
                   "duration_vi": "1,5–2 giờ.",
                   "best_time_vi": "Ngày thường để tránh đông; kết hợp dạo khu Presnya và cụm nhà máy cũ lân cận.",
                   "tips_vi": "Xuống metro Ulitsa 1905 Goda rồi đi bộ ít phút. Đừng bỏ lỡ chính toà nhà — để ý mặt bằng tròn và các chi tiết kiến tạo được phục dựng."},
        sources=[{"title": "Trung tâm Zotov — trang chính thức", "url": "https://centrezotov.ru/en/"},
                 {"title": "How a constructivist bread factory looks after restoration (RBTH)", "url": "https://www.rbth.com/arts/335533-constructivist-bread-factory-moscow"},
                 {"title": "Zotov Constructivism Center — SPEECH (The Plan)", "url": "https://www.theplan.it/eng/award-2024-Culture/zotov-constructivism-center-a-transformation-project-that-preserved-the-layers-of-time-speech-architectural-office"}],
        official_site="https://centrezotov.ru"),

    rec("saint-petersburg", "central-naval-museum",
        "Bảo tàng Hải quân Trung ương mang tên Hoàng đế Pyotr Đại đế", "Центральный военно-морской музей имени императора Петра Великого", "Central Naval Museum",
        ["museum"], 59.93028, 30.29323,
        "Ploshchad Truda (Quảng trường Lao động) 5, doanh trại Kryukov cũ, quận Admiralteysky, Saint Petersburg",
        "Một trong những bảo tàng lâu đời nhất nước Nga (khởi nguồn năm 1709 dưới thời Pyotr Đại đế) và là một trong những bảo tàng hàng hải lớn nhất thế giới. Từ năm 2013 chuyển về doanh trại Kryukov được cải tạo bên Quảng trường Lao động, lưu giữ hơn 800.000 hiện vật cùng bộ sưu tập mô hình tàu vào hàng phong phú nhất thế giới.",
        "Bảo tàng Hải quân Trung ương truy nguồn gốc về 'Phòng mô hình' (Model-kamera) do Pyotr Đại đế lập năm 1709 để lưu bản vẽ và mô hình đóng tàu — vì thế được xem là một trong những bảo tàng lâu đời nhất nước Nga, đồng thời là một trong những bảo tàng hàng hải lớn nhất thế giới. Sau nhiều lần đổi chỗ (trong đó có thời gian dài đặt tại toà Sở Giao dịch cũ trên mũi đảo Vasilievsky), từ năm 2013 bảo tàng chuyển về doanh trại Kryukov — một quần thể lịch sử được cải tạo hiện đại bên Quảng trường Lao động, gần đảo New Holland. Bộ sưu tập đồ sộ với hơn 800.000 hiện vật trải khắp mười chín gian trưng bày chính: vũ khí, quân phục, huân chương, cờ hiệu, tranh hải chiến, thư tịch và ảnh tư liệu ghi lại chặng đường của hải quân Nga từ thời Pyotr tới nay. Quý giá bậc nhất là bộ sưu tập mô hình tàu — gần hai nghìn chiếc, thuộc hàng phong phú nhất thế giới — cùng hiện vật biểu tượng: chiếc thuyền nhỏ 'botik' của Pyotr Đại đế, được người Nga trìu mến gọi là 'Ông tổ của Hải quân Nga'. Bảo tàng còn quản lý nhiều chi nhánh nổi tiếng, trong đó có tuần dương hạm Aurora. Không gian rộng rãi, hiện đại và giàu hiện vật khiến đây là điểm đến hấp dẫn cho người mê lịch sử và hàng hải.",
        ["Khởi nguồn từ 'Phòng mô hình' của Pyotr Đại đế năm 1709 — một trong những bảo tàng lâu đời nhất nước Nga.",
         "Bộ sưu tập gần 2.000 mô hình tàu — vào hàng phong phú nhất thế giới; tổng cộng hơn 800.000 hiện vật.",
         "Lưu giữ chiếc 'botik' của Pyotr Đại đế — 'Ông tổ của Hải quân Nga'; đồng thời quản lý tuần dương hạm Aurora."],
        ["museum", "history", "navy", "indoor", "family"],
        practical={"hours_vi": "Mở cửa gần như cả tuần (một ngày đầu tuần nghỉ để bảo trì); nên kiểm tra giờ chính xác trên trang chính thức navalmuseum.ru trước khi đến.",
                   "ticket_vi": "Vé bán tại chỗ và trực tuyến; có ưu đãi cho học sinh–sinh viên và người cao tuổi. Xem giá cập nhật tại navalmuseum.ru.",
                   "duration_vi": "1,5–2,5 giờ.",
                   "best_time_vi": "Buổi sáng để có thời gian đi hết 19 gian trưng bày; kết hợp dạo đảo New Holland gần đó.",
                   "tips_vi": "Gần Quảng trường Lao động và cầu Blagoveshchensky; tiện kết hợp tham quan đảo New Holland và Nhà thờ Hải quân St. Nicholas."},
        sources=[{"title": "Bảo tàng Hải quân Trung ương — trang chính thức (EN)", "url": "https://eng.navalmuseum.ru/about"},
                 {"title": "History of the museum — Central Naval Museum", "url": "https://eng.navalmuseum.ru/about/history"},
                 {"title": "Central Naval Museum (Rusmania)", "url": "https://rusmania.com/north-western/st-petersburg-federal-city/st-petersburg/central-islands/on-2-y-admiralteysky-island/central-naval-museum"}],
        official_site="https://navalmuseum.ru"),

    rec("moscow", "krasny-oktyabr",
        "Khu sáng tạo 'Tháng Mười Đỏ' (Krasny Oktyabr — nhà máy sô-cô-la cũ)", "Красный Октябрь", "Krasny Oktyabr (Red October)",
        ["square_street", "other"], 55.74090, 37.60930,
        "Bờ kè Bersenevskaya, Đảo Bolotny, quận trung tâm Moskva; đối diện Nhà thờ Chúa Cứu Thế, gần metro Kropotkinskaya.",
        "Quần thể gạch đỏ trên Đảo Bolotny từng là nhà máy bánh kẹo 'Tháng Mười Đỏ' lừng danh — nơi ra đời thanh sô-cô-la sữa 'Alyonka' với hình cô bé trùm khăn quen thuộc. Sau khi dây chuyền sản xuất dời đi năm 2007, cụm nhà xưởng thế kỷ 19 hồi sinh thành một trong những khu sáng tạo thời thượng bậc nhất Moskva với phòng tranh, quán bar, nhà hàng và studio thiết kế.",
        "Nằm trên Đảo Bolotny giữa sông Moskva và kênh Vodootvodny, ngay đối diện Nhà thờ Chúa Cứu Thế, 'Tháng Mười Đỏ' (Krasny Oktyabr) là một trong những địa chỉ văn hóa - giải trí sành điệu nhất thủ đô Nga. Quần thể gạch đỏ này nguyên là nhà máy bánh kẹo do doanh nhân người Đức Theodor Ferdinand von Einem lập vào nửa sau thế kỷ 19; sau Cách mạng Tháng Mười năm 1917, nhà máy được quốc hữu hóa và mang tên mới 'Krasny Oktyabr'. Đây chính là nơi khai sinh nhiều thương hiệu kẹo trứ danh của Nga, trong đó có thanh sô-cô-la sữa 'Alyonka' với hình cô bé trùm khăn đã trở thành ký ức tuổi thơ của nhiều thế hệ. Năm 2007, dây chuyền sản xuất được chuyển tới cơ sở mới, để lại khu xưởng lịch sử cho một cuộc 'lột xác': các tòa nhà cũ lần lượt biến thành phòng trưng bày nghệ thuật đương đại, trung tâm nhiếp ảnh, quán cà phê, nhà hàng, quán bar sân thượng, câu lạc bộ đêm, hiệu thời trang và văn phòng của các hãng kiến trúc, thiết kế. Suốt hơn một thập kỷ, nơi đây là biểu tượng cho một Moskva trẻ trung, sáng tạo bên cạnh vẻ cổ kính của Điện Kremlin: ban ngày hợp để dạo phòng tranh và ngắm sông, buổi tối lại rực sáng với đời sống về đêm sôi động. Danh sách cửa hàng và sự kiện thay đổi theo thời gian, nên du khách nên xem lịch trước khi tới.",
        ["Nguyên là nhà máy bánh kẹo của doanh nhân Đức Einem (thế kỷ 19), quốc hữu hóa sau năm 1917 và đổi tên 'Krasny Oktyabr' — cái nôi của thanh sô-cô-la 'Alyonka' huyền thoại.",
         "Sau khi sản xuất dời đi năm 2007, cụm xưởng gạch đỏ thành khu sáng tạo: phòng tranh, trung tâm nhiếp ảnh, quán bar, nhà hàng, studio thiết kế.",
         "Vị trí đắc địa trên Đảo Bolotny, đối diện Nhà thờ Chúa Cứu Thế và gần tượng đài Pyotr Đại đế — điểm dạo bộ, ngắm sông và tận hưởng đời sống về đêm."],
        ["modern", "creative", "art", "nightlife", "riverside"],
        practical={"hours_vi": "Khu phố mở tự do suốt ngày; mỗi phòng tranh, quán ăn, quán bar và câu lạc bộ có giờ giấc riêng (nhiều nơi mở tới khuya).",
                   "ticket_vi": "Dạo chơi trong khu miễn phí; một số triển lãm, sự kiện hoặc câu lạc bộ có thể thu phí vào cửa.",
                   "duration_vi": "1–2 giờ (lâu hơn nếu ăn tối hoặc xem triển lãm).",
                   "best_time_vi": "Chiều tối để cảm nhận không khí; mùa hè có sân thượng và quán ngoài trời.",
                   "tips_vi": "Danh sách cửa hàng/sự kiện thay đổi theo thời gian — nên xem trước; kết hợp đi bộ qua cầu Patriarshy sang Nhà thờ Chúa Cứu Thế."},
        sources=[{"title": "Krasny Oktyabr (confectionery brand) — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Krasny_Oktyabr_(confectionery_brand)"},
                 {"title": "Red October: The creative heart of Moscow (Liden & Denz)", "url": "https://lidenz.com/red-october-creative-heart-moscow/"},
                 {"title": "'Red October' Art Cluster (RestExpert)", "url": "https://tourism.restexpert.com/russia/place/red-october"}]),

    rec("saint-petersburg", "general-staff-building",
        "Tòa nhà Bộ Tổng Tham mưu (Glavny Shtab) — Cánh Đông Bảo tàng Hermitage", "Здание Главного штаба (Восточное крыло)", "General Staff Building (Hermitage East Wing)",
        ["museum"], 59.93810, 30.31720,
        "Quảng trường Cung điện (Dvortsovaya) số 6-8, Saint Petersburg; cánh Đông đối diện Cung điện Mùa Đông, gần metro Admiralteyskaya.",
        "Cánh Đông của tòa nhà Bộ Tổng Tham mưu hình vòng cung do kiến trúc sư Carlo Rossi thiết kế (1819-1829) nay là một phần hiện đại của Bảo tàng Hermitage. Đây là nơi trưng bày bộ sưu tập hội họa Ấn tượng và Hậu Ấn tượng lừng danh — Monet, Renoir, Van Gogh, Gauguin, Cézanne, Matisse, Picasso — cùng các gian nội thất phong cách Đế chế và bộ sưu tập Fabergé.",
        "Ôm lấy phía nam Quảng trường Cung điện bằng mặt tiền cong dài gần 580 mét, tòa nhà Bộ Tổng Tham mưu là kiệt tác phong cách Đế chế (Empire) do kiến trúc sư người Ý Carlo Rossi dựng nên trong các năm 1819-1829, với khải hoàn môn ở giữa tôn vinh chiến thắng trong Chiến tranh Vệ quốc năm 1812. Cánh Đông của tòa nhà được chuyển giao cho Bảo tàng Hermitage năm 1993 và trải qua cuộc cải tạo nội thất công phu từ năm 2008 đến 2014 do hãng kiến trúc Studio 44 (Nikita Yavein) thực hiện — biến chuỗi sân trong thành các 'quảng trường' bậc thang tràn ngập ánh sáng, một thiết kế bảo tàng được giới chuyên môn đánh giá cao. Không gian hiện đại này lưu giữ điều mà nhiều du khách coi là 'kho báu' của Hermitage: bộ sưu tập hội họa Ấn tượng và Hậu Ấn tượng vào hàng bậc nhất thế giới, với kiệt tác của Claude Monet, Auguste Renoir, Edgar Degas, Vincent van Gogh, Paul Gauguin, Paul Cézanne, và đặc biệt là những phòng dành riêng cho Henri Matisse và Pablo Picasso. Bên cạnh đó là các gian nội thất lộng lẫy theo phong cách Đế chế, Bảo tàng Cận vệ Hoàng gia, phòng trưng bày trang sức Fabergé và không gian nghệ thuật đương đại. Vé và lối vào tách riêng với Cung điện Mùa Đông, nên nơi đây thường vắng khách hơn — một lợi thế để thưởng lãm thong thả.",
        ["Mặt tiền cong gần 580 m và khải hoàn môn tôn vinh chiến thắng năm 1812 — kiệt tác phong cách Đế chế của Carlo Rossi (1819-1829).",
         "Nơi trưng bày bộ sưu tập Ấn tượng và Hậu Ấn tượng của Hermitage: Monet, Renoir, Van Gogh, Gauguin, Cézanne, cùng các phòng riêng cho Matisse và Picasso.",
         "Nội thất cải tạo 2008-2014 bởi Studio 44 với các sân trong bậc thang ngập sáng; vé và lối vào tách riêng với Cung điện Mùa Đông nên thường vắng hơn."],
        ["museum", "art", "impressionists", "indoor", "must-see"],
        practical={"hours_vi": "Thứ Ba, Sáu, Bảy: 11:00-20:00; Thứ Tư, Năm, Chủ nhật: 11:00-18:00; đóng cửa Thứ Hai. Giờ có thể thay đổi — nên kiểm tra trang chính thức.",
                   "ticket_vi": "Vé vào cánh Bộ Tổng Tham mưu bán riêng (khoảng 500 RUB vé theo khung giờ); có thể mua trong vé combo với Cung điện Mùa Đông. Đặt trước tại hermitagemuseum.org.",
                   "duration_vi": "1,5-2,5 giờ.",
                   "best_time_vi": "Buổi sáng ngày thường để tránh đông; kết hợp cùng Quảng trường Cung điện.",
                   "tips_vi": "Lối vào từ Quảng trường Cung điện, tách biệt với Cung điện Mùa Đông; nếu ưu tiên tranh Ấn tượng và Picasso/Matisse, hãy dành riêng một buổi cho tòa nhà này."},
        sources=[{"title": "The General Staff Building — Hermitage (chính thức)", "url": "https://www.hermitagemuseum.org/wps/portal/hermitage/explore/buildings/locations/complex/BC2"},
                 {"title": "General Staff Building (Saint Petersburg) — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/General_Staff_Building_(Saint_Petersburg)"},
                 {"title": "Hermitage Tickets, Routes & Hours 2026 (Russiable)", "url": "https://russiable.com/buy-tickets-hermitage-museum/"}],
        official_site="https://www.hermitagemuseum.org"),

    rec("saint-petersburg", "monument-heroic-defenders-leningrad",
        "Tượng đài Những Người Bảo vệ Anh hùng Leningrad (Quảng trường Chiến thắng)", "Монумент героическим защитникам Ленинграда", "Monument to the Heroic Defenders of Leningrad",
        ["monument", "museum"], 59.84170, 30.32190,
        "Quảng trường Chiến thắng (Ploshchad Pobedy), cuối đại lộ Moskovsky, phía nam Saint Petersburg (trên đường ra sân bay Pulkovo); cạnh metro Moskovskaya.",
        "Đài tưởng niệm hoành tráng ở cửa ngõ phía nam thành phố, khánh thành năm 1975 nhân 30 năm Chiến thắng, tưởng nhớ cuộc phòng thủ và cuộc vây hãm Leningrad kéo dài gần 900 ngày. Trung tâm là cây tháp cao 48 m, vòng tròn bị 'bẻ gãy' tượng trưng cho vòng vây bị phá vỡ, ngọn lửa vĩnh cửu và các nhóm tượng đồng; bên dưới là Sảnh Tưởng niệm — bảo tàng ngầm về cuộc phong tỏa.",
        "Đứng sừng sững giữa Quảng trường Chiến thắng ở cuối đại lộ Moskovsky — cửa ngõ đón khách từ sân bay Pulkovo vào thành phố — Tượng đài Những Người Bảo vệ Anh hùng Leningrad là công trình tưởng niệm quan trọng nhất về vai trò của thành phố trong Thế chiến II. Được khánh thành ngày 9 tháng 5 năm 1975 nhân kỷ niệm 30 năm Chiến thắng, tượng đài do các kiến trúc sư Sergei Speransky và Valentin Kamensky thiết kế, phần điêu khắc do nhà điêu khắc lừng danh Mikhail Anikushin thực hiện. Điểm nhấn là cây tháp đá granite cao 48 mét vươn lên trời; dưới chân là các nhóm tượng đồng khắc họa những người bảo vệ thành phố: binh sĩ, thủy thủ, xạ thủ, công nhân, người mẹ ôm con. Ấn tượng nhất là vòng tròn bê tông bị 'bẻ gãy' một đoạn — biểu tượng cho vòng vây phát-xít cuối cùng bị đập tan sau gần 900 ngày phong tỏa (1941-1944), một trong những cuộc vây hãm dai dẳng và bi thương nhất lịch sử nhân loại. Bên dưới quảng trường là Sảnh Tưởng niệm mở cửa năm 1978 — một bảo tàng ngầm trực thuộc Bảo tàng Lịch sử Saint Petersburg, nơi trưng bày hiện vật, thư từ, thước phim tư liệu và các bức tranh khảm mosaic về cuộc phong tỏa và chiến thắng, trong tiếng nhịp đều đặn của chiếc máy nhịp (metronome) từng vang trên đài phát thanh Leningrad thời chiến.",
        ["Khánh thành ngày 9/5/1975 nhân 30 năm Chiến thắng; kiến trúc sư Speransky và Kamensky, điêu khắc gia Mikhail Anikushin.",
         "Tháp đá cao 48 m, ngọn lửa vĩnh cửu và vòng tròn bê tông 'bị bẻ gãy' — biểu tượng vòng vây gần 900 ngày (1941-1944) bị phá vỡ.",
         "Sảnh Tưởng niệm ngầm (mở năm 1978) trưng bày hiện vật, thư từ, phim tư liệu và tranh khảm về cuộc phong tỏa Leningrad."],
        ["monument", "history", "wwii", "memorial", "free"],
        practical={"hours_vi": "Đài tưởng niệm ngoài trời mở tự do suốt ngày; Sảnh Tưởng niệm (bảo tàng ngầm) mở khoảng 10:00-18:00, nghỉ Thứ Tư và ngày Thứ Ba cuối tháng — nên kiểm tra lịch chính thức.",
                   "ticket_vi": "Tham quan tượng đài ngoài trời miễn phí; vào Sảnh Tưởng niệm có phí nhỏ (khoảng 90-150 RUB), miễn phí trong các ngày lễ như 27/1, 23/2 và 9/5.",
                   "duration_vi": "45 phút - 1,5 giờ (kể cả Sảnh Tưởng niệm).",
                   "best_time_vi": "Quanh năm; đặc biệt ý nghĩa vào ngày 27/1 (dỡ vây) và 9/5 (Chiến thắng).",
                   "tips_vi": "Xuống metro Moskovskaya là tới nơi; nên ghé cả bảo tàng ngầm để hiểu chiều sâu bi tráng của cuộc phong tỏa."},
        sources=[{"title": "Monument to the Heroic Defenders of Leningrad — State Museum of the History of St Petersburg (chính thức)", "url": "https://www.spbmuseum.ru/themuseum/museum_complex/monument_lenigrad/?lang_ui=en"},
                 {"title": "Victory Square, Saint Petersburg — Wikipedia (EN)", "url": "https://en.wikipedia.org/wiki/Victory_Square,_Saint_Petersburg"},
                 {"title": "Monument to the Heroic Defenders of Leningrad (Rusmania)", "url": "https://rusmania.com/north-western/st-petersburg-federal-city/st-petersburg/bezymyanny-island-and-the-south/around-moskovsky-prospekt/monument-to-the-heroic-defenders-of-leningrad"}],
        official_site="https://www.spbmuseum.ru"),
]


def main():
    added = {}
    for r in CANDIDATES:
        path = os.path.join(REGIONS, r["region"] + ".json")
        arr = json.load(open(path, encoding="utf-8")) if os.path.exists(path) else []
        if any(x.get("slug") == r["slug"] for x in arr):
            continue
        arr.append(r)
        json.dump(arr, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        added.setdefault(r["region"], []).append(r["slug"])
    if not added:
        print("Không có địa điểm mới (tất cả đã tồn tại).")
    for reg, slugs in added.items():
        print(f"+ {reg}: thêm {len(slugs)} → {', '.join(slugs)}")


if __name__ == "__main__":
    main()
