# -*- coding: utf-8 -*-
"""
Seed script — Saint Petersburg sample region.

Tạo file dữ liệu chuẩn: data/regions/saint-petersburg.json
Nội dung tiếng Việt là nguyên bản (viết mới từ dữ kiện thật + dữ liệu web),
KHÔNG sao chép sách nguồn. Sách chỉ dùng làm danh mục địa điểm.

Chạy:  python3 tools/seed_saint_petersburg.py
"""
import json, os, urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "data", "regions", "saint-petersburg.json")

REGION_SLUG = "saint-petersburg"
REGION_NAME_VI = "Saint Petersburg"
FEDERAL_DISTRICT = "Thành phố trực thuộc liên bang"
TODAY = "2026-07-15"


def maps(lat, lon):
    return {
        "yandex": f"https://yandex.com/maps/?pt={lon},{lat}&z=17&l=map",
        "google": f"https://www.google.com/maps/search/?api=1&query={lat},{lon}",
    }


def photo_url(filename):
    if not filename:
        return None
    return "https://commons.wikimedia.org/wiki/Special:FilePath/" + urllib.parse.quote(filename)


def wiki_source(name_en):
    return {
        "title": "Wikipedia (EN)",
        "url": "https://en.wikipedia.org/wiki/Special:Search?search=" + urllib.parse.quote(name_en),
    }


def place(slug, name_vi, name_ru, name_en, categories, lat, lon, address_vi,
          rating, review, short, long, highlights, practical,
          photo_file=None, official=None, tags=None, status="enriched"):
    return {
        "id": f"{REGION_SLUG}-{slug}",
        "slug": slug,
        "region": REGION_SLUG,
        "region_name_vi": REGION_NAME_VI,
        "federal_district": FEDERAL_DISTRICT,
        "name_vi": name_vi,
        "name_ru": name_ru,
        "name_en": name_en,
        "categories": categories,
        "coordinates": {"lat": lat, "lon": lon},
        "address_vi": address_vi,
        "rating": rating,
        "review_summary_vi": review,
        "presentation_short_vi": short,
        "presentation_long_vi": long,
        "highlights_vi": highlights,
        "practical": practical,
        "photo": photo_url(photo_file),
        "photo_credit": ("Wikimedia Commons" if photo_file else None),
        "maps": maps(lat, lon),
        "official_site": official,
        "sources": [wiki_source(name_en)],
        "tags": tags or [],
        "status": status,
        "last_updated": TODAY,
    }


PLACES = [
    place(
        "hermitage",
        "Bảo tàng Ẩn Cung (Hermitage) – Cung điện Mùa Đông",
        "Государственный Эрмитаж",
        "State Hermitage Museum",
        ["museum", "palace"],
        59.940556, 30.313611,
        "Số 34 bờ kè Cung điện (Dvortsovaya nab.), Saint Petersburg",
        {"value": 4.7, "count": 26762, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách choáng ngợp trước nội thất hoàng gia xa hoa và bộ sưu tập tầm cỡ thế giới (Da Vinci, Rembrandt, Raphael, Đồng hồ Công). Lời than phiền phổ biến nhất là bảo tàng quá rộng để xem hết trong một lần, hàng chờ vào dài và dễ lạc giữa các phòng.",
        "Bảo tàng nghệ thuật lớn bậc nhất thế giới, đặt trong Cung điện Mùa Đông lộng lẫy bên bờ sông Neva — nơi lưu giữ khoảng 3 triệu hiện vật, từ Da Vinci, Rembrandt đến chiếc Đồng hồ Công bằng vàng vẫn còn chạy.",
        "Bước qua ngưỡng cửa Cung điện Mùa Đông, bạn đang đặt chân vào nơi từng là dinh thự chính của các Sa hoàng Nga và ngày nay là một trong những bảo tàng vĩ đại nhất hành tinh. Hermitage ra đời năm 1764, khi Nữ hoàng Ekaterina Đại đế mua về bộ sưu tập hơn hai trăm bức tranh; gần ba thế kỷ sau, kho báu ấy đã lên tới khoảng ba triệu hiện vật, trải dài từ nghệ thuật Ai Cập cổ đại tới các kiệt tác của Leonardo da Vinci, Rembrandt, Raphael và Rubens. Những gian phòng dát vàng, cầu thang Đại sảnh tráng lệ, trần nhà chạm trổ và các chùm đèn pha lê khiến bản thân toà cung điện cũng là một tác phẩm nghệ thuật. Đừng bỏ lỡ chiếc Đồng hồ Công (Peacock Clock) bằng vàng vẫn còn hoạt động, hay phòng tranh của các danh hoạ Ý. Du khách thường choáng ngợp vì quy mô: đi hết các phòng có thể ngốn của bạn nhiều ngày, nên hãy chọn trước vài khu vực yêu thích. Và nếu gặp một chú mèo ung dung dạo bước, đừng ngạc nhiên — 'những chú mèo Hermitage' đã canh giữ kho tranh khỏi lũ chuột suốt hàng trăm năm.",
        [
            "Thành lập năm 1764 từ bộ sưu tập hơn 225 bức tranh của Ekaterina Đại đế; mở cửa cho công chúng năm 1852.",
            "Một trong những bảo tàng lớn nhất thế giới với khoảng 3 triệu hiện vật — chỉ một phần nhỏ được trưng bày.",
            "Cung điện Mùa Đông từng là nơi ở chính của các hoàng đế Nga; bảo tàng nổi tiếng với đàn 'mèo Hermitage' canh gác.",
        ],
        {
            "hours_vi": "Thứ Ba, Sáu, Bảy 11:00–20:00; Thứ Tư, Năm, CN 11:00–18:00; đóng cửa Thứ Hai.",
            "ticket_vi": "Khoảng 500 RUB (khách nước ngoài); vé mở ngày ~1.200 RUB; dưới 18 tuổi miễn phí.",
            "duration_vi": "3–4 giờ (nửa ngày).",
            "best_time_vi": "Sáng sớm giữa tuần để tránh đông; mùa hè (Đêm Trắng) đẹp nhất.",
            "tips_vi": "Mua vé online trước để đỡ xếp hàng; chọn trước 2–3 khu muốn xem; đi giày êm.",
        },
        photo_file="Winter_Palace_Panorama_4.jpg",
        official="https://www.hermitagemuseum.org",
        tags=["museum", "art", "indoor", "landmark", "top"],
    ),
    place(
        "savior-on-blood",
        "Nhà thờ Chúa Cứu Thế trên Máu Đổ (Spas na Krovi)",
        "Спас на Крови",
        "Church of the Savior on Spilled Blood",
        ["church"],
        59.940000, 30.328610,
        "Kênh Griboedov 2Б (nab. kanala Griboedova, 2Б), Saint Petersburg",
        {"value": 4.8, "count": 21728, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách liên tục xếp đây là điểm ấn tượng nhất Saint Petersburg, khen mái vòm củ hành rực rỡ bên ngoài và nội thất choáng ngợp với hơn 7.000 m² tranh khảm. Điểm trừ nhỏ: bên trong có thể đông, đôi khi có giàn giáo trùng tu che mặt tiền.",
        "Nhà thờ mái vòm củ hành sặc sỡ nhất Saint Petersburg, dựng ngay nơi Sa hoàng Aleksandr II bị ám sát, với nội thất phủ hơn 7.000 m² tranh khảm (mosaic) lấp lánh.",
        "Nổi bật giữa lòng thành phố với những mái vòm củ hành nhiều màu như bước ra từ cổ tích, Nhà thờ Chúa Cứu Thế trên Máu Đổ được xây trong các năm 1883–1907 ngay tại điểm Sa hoàng Aleksandr II trúng bom mưu sát năm 1881 — cái tên 'trên Máu Đổ' bắt nguồn từ bi kịch ấy. Khác hẳn phong cách Baroque và tân cổ điển thống trị Saint Petersburg, công trình cố tình mô phỏng kiến trúc Nga thời trung cổ, gợi nhớ Nhà thờ Thánh Basil ở Moskva. Nhưng điều khiến du khách sững sờ nằm ở bên trong: hơn bảy nghìn mét vuông tranh khảm mosaic phủ kín tường và trần, một trong những bộ sưu tập mosaic lớn nhất châu Âu, kể lại các tích Kinh Thánh bằng hàng triệu mảnh đá và thuỷ tinh. Thời Xô Viết, nhà thờ từng bị dùng làm kho chứa khoai tây, nên dân gian gọi vui là 'Đấng Cứu Thế trên Khoai tây'. Ngày nay đây là điểm được du khách chấm điểm cao nhất thành phố. Hãy đến sớm hoặc mua vé buổi tối mùa hè để chiêm ngưỡng không gian bớt chật, và dành thời gian ngẩng đầu ngắm từng vòm trần — mỗi centimet đều là nghệ thuật.",
        [
            "Xây 1883–1907 đúng nơi Hoàng đế Aleksandr II bị ám sát bằng bom năm 1881.",
            "Nội thất có hơn 7.000 m² tranh khảm mosaic — thuộc hàng lớn nhất châu Âu.",
            "Thời Xô Viết từng làm kho khoai tây, nên có biệt danh 'Đấng Cứu Thế trên Khoai tây'.",
        ],
        {
            "hours_vi": "10:30–18:00; đóng cửa Thứ Tư; mùa hè có suất tối tới ~22:30.",
            "ticket_vi": "~450 RUB người lớn (~400 RUB suất tối); trẻ dưới 7 tuổi miễn phí.",
            "duration_vi": "45–90 phút.",
            "best_time_vi": "Mùa hè, buổi tối muộn để tránh đông; ánh chiều làm mosaic rực rỡ.",
            "tips_vi": "Mua vé suất tối để vắng hơn; mang ống nhòm nhỏ để ngắm mosaic trên vòm cao.",
        },
        photo_file="The_Church_of_the_Savior_on_Spilled_Blood.jpg",
        official="https://eng.cathedral.ru",
        tags=["church", "art", "indoor", "landmark", "top"],
    ),
    place(
        "st-isaacs",
        "Nhà thờ Thánh Isaac (Isaakievsky)",
        "Исаакиевский собор",
        "Saint Isaac's Cathedral",
        ["church"],
        59.933994, 30.305969,
        "Quảng trường Thánh Isaac 4 (Isaakiyevskaya pl., 4), Saint Petersburg",
        {"value": 4.7, "count": 10350, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách trầm trồ trước quy mô hoành tráng, mái vòm dát vàng và nội thất xa hoa bằng malachite, lapis lazuli, tranh khảm; điểm nhấn với nhiều người là leo hàng cột ngắm toàn cảnh. Ít lời chê, chủ yếu là phải leo cầu thang và nên mua vé tại chỗ.",
        "Một trong những thánh đường Chính thống giáo lớn nhất thế giới, với mái vòm dát vàng rực rỡ; leo lên hàng cột (colonnade) trên cao để ngắm toàn cảnh Saint Petersburg.",
        "Sừng sững với mái vòm dát vàng dùng gần 100 kg vàng ròng, Nhà thờ Thánh Isaac là một trong những thánh đường Chính thống giáo lớn nhất hành tinh. Do kiến trúc sư người Pháp Auguste de Montferrand thiết kế, công trình mất tới 40 năm để hoàn thành (1818–1858). Những cột đá granite đỏ nguyên khối — cột lớn nhất nặng chừng 114 tấn — được dựng lên trước cả khi xây tường, một kỳ tích kỹ thuật của thế kỷ 19. Bên trong, du khách lạc vào một thế giới của malachite, lapis lazuli, tranh khảm và mạ vàng; vòm nhà thờ cao hơn 100 mét và có thể chứa tới 14.000 người. Nhưng phần thưởng được yêu thích nhất lại nằm bên ngoài: leo khoảng 200 bậc lên hàng cột quanh mái vòm, cả Saint Petersburg trải ra dưới chân bạn — từ dòng Neva, Cung điện Mùa Đông đến mũi nhọn Pháo đài Petropavlovsk. Ngày nay nhà thờ hoạt động như một bảo tàng nhà nước. Lời khuyên nhỏ: mua vé ngay tại quầy chính hãng để tránh giá 'cò', và nếu còn sức, hãy chinh phục colonnade vào lúc hoàng hôn.",
        [
            "Do Auguste de Montferrand thiết kế, xây suốt 40 năm (1818–1858); mái vòm dùng khoảng 100 kg vàng.",
            "Một trong những thánh đường Chính thống lớn nhất thế giới: vòm cao ~101,5 m, chứa được ~14.000 người.",
            "112 cột granite đỏ nguyên khối (cột lớn nhất ~114 tấn) được dựng trước khi xây tường.",
        ],
        {
            "hours_vi": "10:30–18:00; đóng cửa Thứ Tư; hàng cột mở tới ~22:30 vào mùa hè.",
            "ticket_vi": "Nhà thờ ~450 RUB; hàng cột ngắm cảnh thêm ~400 RUB; dưới 7 tuổi miễn phí.",
            "duration_vi": "1–1,5 giờ (gồm hàng cột).",
            "best_time_vi": "Hoàng hôn mùa hè để ngắm toàn cảnh từ colonnade.",
            "tips_vi": "Mua vé tại quầy chính hãng; vé nhà thờ và vé hàng cột tách riêng; chuẩn bị leo ~200 bậc.",
        },
        photo_file="Saint_Isaac's_Cathedral_Saint_Petersburg.jpg",
        official="https://eng.cathedral.ru",
        tags=["church", "viewpoint", "indoor", "landmark"],
    ),
    place(
        "kazan-cathedral",
        "Nhà thờ Kazan (Kazansky)",
        "Казанский собор",
        "Kazan Cathedral",
        ["church"],
        59.934116, 30.324432,
        "Đại lộ Nevsky 25 (Nevsky pr., 25), Saint Petersburg",
        {"value": 4.6, "count": 4185, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách khen hàng cột bán nguyệt hùng vĩ (thường ví với Thánh đường Thánh Peter ở Roma) và không khí trầm mặc của một giáo đường đang hoạt động với nến, biểu tượng và hợp xướng; vào cửa miễn phí là điểm cộng. Phàn nàn chính là đông vào giờ cao điểm và 'cò' chụp ảnh chèo kéo bên ngoài.",
        "Thánh đường đang hoạt động với hàng cột hình bán nguyệt 96 cột gợi nhớ Vương cung Thánh đường Thánh Peter ở Roma; nơi an nghỉ của Thống chế Kutuzov, vào cửa miễn phí.",
        "Vươn ra ôm lấy đại lộ Nevsky bằng hàng cột hình bán nguyệt chín mươi sáu chiếc, Nhà thờ Kazan là một trong những công trình bề thế và duyên dáng nhất Saint Petersburg. Do kiến trúc sư Andrei Voronikhin xây dựng trong các năm 1801–1811, hàng cột sải rộng của nhà thờ lấy cảm hứng trực tiếp từ Vương cung Thánh đường Thánh Peter ở Roma. Đây không chỉ là nơi thờ phụng: sau chiến thắng trước Napoléon năm 1812, Kazan trở thành đài tưởng niệm vinh quang của nước Nga, và Thống chế lừng danh Mikhail Kutuzov được an táng ngay bên trong. Trung tâm tinh thần của nhà thờ là bản sao được tôn kính của biểu tượng Đức Mẹ Kazan. Khác với nhiều điểm tham quan thu phí, Kazan mở cửa miễn phí và vẫn là một giáo đường sống động — bạn sẽ bắt gặp những ngọn nến lung linh, mùi hương trầm và tiếng hợp xướng vang vọng dưới mái vòm. Thời Xô Viết, nơi đây từng là 'Bảo tàng Lịch sử Tôn giáo và Vô thần'. Hãy giữ im lặng và ăn mặc kín đáo khi vào, và tránh những người mặc trang phục hoá trang mời chụp ảnh tính phí bên ngoài.",
        [
            "Xây 1801–1811 bởi Andrei Voronikhin; hàng cột 96 chiếc lấy cảm hứng từ Thánh đường Thánh Peter, Roma.",
            "Thống chế Mikhail Kutuzov an nghỉ bên trong; nhà thờ là đài tưởng niệm chiến thắng Napoléon 1812.",
            "Lưu giữ bản sao tôn kính của biểu tượng Đức Mẹ Kazan; thời Xô Viết từng là bảo tàng vô thần.",
        ],
        {
            "hours_vi": "Hằng ngày ~06:30 đến hết buổi lễ tối (thường ~20:00).",
            "ticket_vi": "Miễn phí (giáo đường đang hoạt động; hoan nghênh quyên góp).",
            "duration_vi": "30–45 phút.",
            "best_time_vi": "Trong giờ lễ để nghe hợp xướng; buổi tối khi lên đèn.",
            "tips_vi": "Ăn mặc kín đáo, giữ trật tự; tránh 'cò' chụp ảnh tính phí trước nhà thờ.",
        },
        photo_file="Kazan_Cathedral_Saint_Petersburg.jpg",
        official="https://kazansky-spb.ru",
        tags=["church", "free", "indoor", "landmark"],
    ),
    place(
        "russian-museum",
        "Bảo tàng Nga (Russkiy Muzey)",
        "Русский музей",
        "State Russian Museum",
        ["museum", "palace"],
        59.938610, 30.332220,
        "Phố Inzhenernaya 4 — Cung điện Mikhailovsky, Saint Petersburg",
        {"value": 4.7, "count": 3306, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách gọi bộ sưu tập nghệ thuật Nga là kho báu — Repin, Aivazovsky, Bryullov và các icon — trưng bày trong Cung điện Mikhailovsky thanh lịch, và thường thấy dễ chịu hơn Hermitage. Điểm trừ: đông vào ngày cao điểm, một số tranh bị loá sáng, đôi khi nhân viên chưa niềm nở.",
        "Bảo tàng nghệ thuật Nga đầu tiên của nhà nước, đặt trong Cung điện Mikhailovsky tân cổ điển; yên tĩnh hơn Hermitage, với kiệt tác của Repin, Aivazovsky, Bryullov.",
        "Nếu Hermitage tôn vinh nghệ thuật thế giới, thì Bảo tàng Nga (Russkiy Muzey) là ngôi đền của chính hội hoạ Nga. Được Hoàng đế Nikolai II thành lập năm 1895 để tưởng nhớ vua cha Aleksandr III, đây là bảo tàng nghệ thuật quốc gia đầu tiên của nước Nga, mở cửa năm 1898. Toà nhà chính — Cung điện Mikhailovsky — tự thân đã là kiệt tác tân cổ điển do kiến trúc sư Carlo Rossi thiết kế đầu thế kỷ 19. Bên trong là hơn 400.000 tác phẩm trải dài từ các biểu tượng (icon) cổ kính tới hội hoạ hiện đại: bạn sẽ được đứng trước 'Con sóng thứ chín' của Aivazovsky, 'Ngày cuối cùng của Pompeii' của Bryullov, cùng những bức chân dung và tranh lịch sử hùng tráng của Repin. Nhiều du khách thấy nơi đây dễ chịu và bớt choáng ngợp hơn Hermitage — một lựa chọn lý tưởng để thật sự thưởng thức tranh mà không bị đám đông cuốn đi. Hãy dành ít nhất hai giờ, và nếu có thời gian, dạo bước sang Vườn Mikhailovsky ngay bên cạnh.",
        [
            "Do Hoàng đế Nikolai II lập năm 1895 (mở cửa 1898) — bảo tàng nghệ thuật quốc gia đầu tiên của Nga.",
            "Toà nhà chính là Cung điện Mikhailovsky, kiệt tác tân cổ điển của Carlo Rossi (1819–1825).",
            "Sở hữu hơn 400.000 tác phẩm, gồm 'Con sóng thứ chín' (Aivazovsky) và 'Ngày cuối cùng của Pompeii' (Bryullov).",
        ],
        {
            "hours_vi": "Thứ 2,4,6,7,CN 10:00–18:00; Thứ 5 13:00–21:00; đóng cửa Thứ Ba.",
            "ticket_vi": "~500 RUB người lớn (Cung điện Mikhailovsky); sinh viên ~250 RUB; trẻ em miễn phí.",
            "duration_vi": "2–3 giờ.",
            "best_time_vi": "Giữa tuần, buổi sáng.",
            "tips_vi": "Kết hợp dạo Vườn Mikhailovsky kế bên; Thứ Năm mở muộn, ít đông hơn.",
        },
        photo_file="Russian_museam.JPG",
        official="https://rusmuseum.ru",
        tags=["museum", "art", "indoor"],
    ),
    place(
        "palace-square",
        "Quảng trường Cung điện (Dvortsovaya)",
        "Дворцовая площадь",
        "Palace Square",
        ["square_street", "monument"],
        59.939305, 30.315425,
        "Quảng trường Cung điện (Dvortsovaya pl.), Saint Petersburg",
        {"value": 4.7, "count": 5479, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách mô tả đây là quần thể bề thế phải xem — Cung điện Mùa Đông, Toà nhà Bộ Tổng tham mưu với cổng khải hoàn, và Cột Aleksandr sừng sững — đặc biệt huyền ảo khi lên đèn ban đêm hoặc có nghệ sĩ đường phố. Vài lời chê nhắc đến rào chắn và kiểm tra an ninh khi có sự kiện.",
        "Quảng trường trung tâm hoành tráng với Cung điện Mùa Đông, Toà nhà Bộ Tổng tham mưu hình vòng cung và Cột Aleksandr cao 47,5 m — sân khấu của những biến cố lịch sử Nga.",
        "Là trái tim nghi lễ của Saint Petersburg, Quảng trường Cung điện (Dvortsovaya Ploshchad) khiến bất kỳ ai lần đầu đặt chân tới cũng phải ngước nhìn. Ba mặt của quảng trường là ba kiệt tác: mặt tiền xanh-trắng của Cung điện Mùa Đông, đường cong hoành tráng của Toà nhà Bộ Tổng tham mưu do Carlo Rossi thiết kế với cổng khải hoàn kép được đội bằng cỗ xe chiến thắng bằng đồng, và ở chính giữa là Cột Aleksandr cao chừng 47,5 mét. Điều kỳ diệu về cây cột: nó chỉ đứng vững nhờ chính trọng lượng khổng lồ của mình, không hề gắn chặt vào bệ. Quảng trường này cũng là nơi lịch sử Nga sang trang — từ vụ thảm sát 'Ngày Chủ nhật đẫm máu' năm 1905 tới cuộc tấn công Cung điện Mùa Đông năm 1917. Ngày nay, không gian rộng lớn ấy là nơi diễn ra hoà nhạc, lễ hội và những nghệ sĩ đường phố; đẹp nhất là khi lên đèn về đêm. Vì đây là quảng trường ngoài trời, bạn có thể ghé bất cứ lúc nào, hoàn toàn miễn phí — điểm khởi đầu hoàn hảo cho hành trình khám phá thành phố.",
        [
            "Cột Aleksandr ở trung tâm (1830–1834) cao ~47,5 m, chỉ đứng vững nhờ trọng lượng, không gắn vào bệ.",
            "Chứng kiến nhiều bước ngoặt lịch sử: 'Ngày Chủ nhật đẫm máu' 1905 và cuộc tấn công Cung điện Mùa Đông 1917.",
            "Được bao quanh bởi Toà nhà Bộ Tổng tham mưu của Carlo Rossi với cổng khải hoàn kép đội cỗ xe nữ thần Chiến thắng.",
        ],
        {
            "hours_vi": "Mở cửa 24 giờ (quảng trường ngoài trời).",
            "ticket_vi": "Miễn phí.",
            "duration_vi": "20–45 phút.",
            "best_time_vi": "Buổi tối khi lên đèn; các dịp lễ hội.",
            "tips_vi": "Điểm khởi đầu lý tưởng, sát Hermitage; đề phòng rào chắn khi có sự kiện.",
        },
        photo_file="Palace_Square,_Saint_Petersburg,_Russia.JPG",
        official=None,
        tags=["square", "free", "outdoor", "landmark", "night", "top"],
    ),
    place(
        "peter-paul-fortress",
        "Pháo đài Petropavlovsk (Thánh Phêrô và Phaolô)",
        "Петропавловская крепость",
        "Peter and Paul Fortress",
        ["fortress", "church"],
        59.950191, 30.316346,
        "Đảo Zayachy (Zayachy Ostrov), Saint Petersburg",
        {"value": 4.4, "count": 5155, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách ca ngợi đây là nơi khai sinh lịch sử của Saint Petersburg — thánh đường mũi nhọn dát vàng với lăng mộ dòng họ Romanov, tầm nhìn sông Neva từ tường thành, và khẩu đại bác trưa. Phàn nàn thường gặp là đông vào mùa cao điểm và hầu hết bảo tàng bên trong đều bán vé riêng.",
        "Nơi khai sinh Saint Petersburg (1703), với thánh đường mũi nhọn dát vàng cao 122,5 m — lăng mộ các Sa hoàng — và khẩu đại bác bắn đúng trưa mỗi ngày.",
        "Mọi câu chuyện về Saint Petersburg đều bắt đầu từ đây. Ngày 27 tháng 5 năm 1703, Pyotr Đại đế đặt viên đá đầu tiên của Pháo đài Petropavlovsk trên một hòn đảo nhỏ giữa sông Neva — và thành phố ra đời từ khoảnh khắc ấy. Bên trong những bức tường thành, Nhà thờ Petropavlovsk vươn mũi nhọn dát vàng cao 122,5 mét lên bầu trời, từng là công trình cao nhất thành phố; dưới mái vòm là nơi an nghỉ của gần như toàn bộ các hoàng đế Nga từ Pyotr I tới Nikolai II. Pháo đài còn là nhà tù chính trị khét tiếng, từng giam giữ nhiều nhân vật lịch sử. Một truyền thống được du khách yêu thích: đúng 12 giờ trưa mỗi ngày, một khẩu đại bác trên pháo đài Naryshkin khai hoả — nghi thức có từ năm 1873. Dạo bước trên tường thành, bạn sẽ có tầm nhìn tuyệt đẹp ra sông Neva và đường chân trời của trung tâm lịch sử. Khuôn viên pháo đài vào cửa tự do; chỉ các bảo tàng và nhà thờ bên trong mới cần vé. Mùa hè, bãi cát ven thành còn là nơi người dân thành phố ra tắm nắng.",
        [
            "Pyotr Đại đế khởi dựng ngày 27/5/1703 — đánh dấu nơi khai sinh Saint Petersburg.",
            "Mũi nhọn Nhà thờ Petropavlovsk cao 122,5 m, là nơi an táng gần như mọi hoàng đế Nga từ Pyotr I đến Nikolai II.",
            "Khẩu đại bác bắn đúng 12 giờ trưa từ pháo đài Naryshkin, truyền thống có từ năm 1873.",
        ],
        {
            "hours_vi": "Khuôn viên ~09:30–20:00 (miễn phí); bảo tàng Thứ 5–Thứ 3 10:00–18:00, đóng cửa Thứ Tư.",
            "ticket_vi": "Khuôn viên miễn phí; vé combo các bảo tàng ~750 RUB.",
            "duration_vi": "2–3 giờ.",
            "best_time_vi": "Gần trưa để xem bắn đại bác; mùa hè.",
            "tips_vi": "Vào khuôn viên miễn phí; canh 12h trưa xem đại bác; vé nhà thờ và bảo tàng mua riêng.",
        },
        photo_file="PeterandPaulFortress2.JPG",
        official="https://www.spbmuseum.ru",
        tags=["fortress", "church", "outdoor", "viewpoint", "top"],
    ),
    place(
        "palace-bridge",
        "Cầu Cung điện (Dvortsovy Most)",
        "Дворцовый мост",
        "Palace Bridge",
        ["bridge"],
        59.941149, 30.308105,
        "Cầu Cung điện, bắc qua sông Neva, Saint Petersburg",
        {"value": 4.7, "count": 1658, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách mê mẩn cảnh nâng nhịp cầu về đêm mùa Đêm Trắng, đặc biệt góc nhìn mũi nhọn Nhà thờ Petropavlovsk lọt giữa hai cánh cầu, và xem đây là trải nghiệm phải thử. Điểm chê: ban ngày cầu khá đơn giản, và giờ nâng cầu đôi khi khó nắm chính xác nên nhiều người lỡ.",
        "Cây cầu bập bênh biểu tượng của Đêm Trắng — khi các nhịp cầu nâng lên trong đêm, mũi nhọn Nhà thờ Petropavlovsk hiện ra giữa khung cầu như một tấm bưu thiếp.",
        "Ban ngày, Cầu Cung điện (Dvortsovy Most) trông khá giản dị. Nhưng khi màn đêm buông xuống mùa Đêm Trắng, nó biến thành ngôi sao của cả thành phố. Được hãng Batignolles của Pháp xây dựng trong các năm 1912–1916, đây là cầu bập bênh (bascule) năm nhịp dài khoảng 260 mét bắc qua sông Neva. Trong mùa thông thuyền (khoảng cuối tháng Tư đến tháng Mười Một), vào rạng sáng mỗi đêm, hai cánh cầu trung tâm từ từ nâng lên để tàu lớn đi qua — và chính khoảnh khắc ấy tạo nên bức ảnh kinh điển của Saint Petersburg: mũi nhọn dát vàng của Nhà thờ Petropavlovsk lọt gọn giữa hai cánh cầu dựng đứng, in bóng trên nền trời không bao giờ tối hẳn. Hàng nghìn người tụ về hai bờ kè, hoà cùng nhạc và tiếng trầm trồ, chỉ để chứng kiến vài phút kỳ diệu ấy. Hãy tra kỹ lịch nâng cầu (thường quanh 01:10 và 03:10) vì giờ giấc có thể thay đổi, và chọn chỗ đứng phía bờ Cung điện Mùa Đông để có góc nhìn đẹp nhất. Một chuyến du thuyền đêm cũng là cách tuyệt vời để ngắm cầu mở.",
        [
            "Xây 1912–1916 bởi hãng Batignolles (Pháp), thông xe năm 1916.",
            "Cầu bập bênh 5 nhịp, dài ~260 m, rộng 27,8 m bắc qua sông Neva.",
            "Hai nhịp nâng lên, ôm lấy mũi nhọn Nhà thờ Petropavlovsk, là biểu tượng của Đêm Trắng.",
        ],
        {
            "hours_vi": "Đi lại 24/7; nâng cầu ban đêm mùa thông thuyền (cuối T4–T11), khoảng 01:10–02:50 và 03:10–04:55.",
            "ticket_vi": "Miễn phí (cầu công cộng).",
            "duration_vi": "15–30 phút (tới ~1 giờ nếu xem nâng cầu).",
            "best_time_vi": "Rạng sáng mùa Đêm Trắng (tháng 6–7).",
            "tips_vi": "Tra lịch nâng cầu trong đêm; đứng phía bờ Cung điện Mùa Đông; cân nhắc du thuyền đêm.",
        },
        photo_file="Saint Petersburg Palace Bridge IMG 5789 1280.jpg",
        official=None,
        tags=["bridge", "free", "outdoor", "night", "landmark", "top"],
    ),
    place(
        "bronze-horseman",
        "Kỵ sĩ Đồng (Medny Vsadnik)",
        "Медный всадник",
        "The Bronze Horseman",
        ["monument"],
        59.936424, 30.302245,
        "Quảng trường Thượng viện (Senatskaya pl.), Saint Petersburg",
        {"value": 4.5, "count": 1394, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách thán phục dáng tượng đầy kịch tính và tính biểu tượng, đặc biệt ấn tượng với bệ đá 'Tảng đá Sấm' khổng lồ và câu chuyện di chuyển nó. Nhiều người lưu ý đây là điểm dừng ngắn (dưới 1 giờ), hợp nhất khi đi cùng Nhà thờ Thánh Isaac và Quảng trường Thượng viện.",
        "Tượng đài Pyotr Đại đế cưỡi ngựa trên 'Tảng đá Sấm' khổng lồ — nguồn cảm hứng cho bài thơ nổi tiếng của Pushkin, đứng uy nghi trên Quảng trường Thượng viện.",
        "Trên Quảng trường Thượng viện, hướng ánh nhìn ra sông Neva, Pyotr Đại đế ghì cương con tuấn mã đang chồm lên — đó là Kỵ sĩ Đồng (Medny Vsadnik), một trong những tượng đài nổi tiếng nhất nước Nga. Do nhà điêu khắc người Pháp Étienne-Maurice Falconet thực hiện và khánh thành năm 1782 theo lệnh Ekaterina Đại đế, bức tượng khắc hoạ vị hoàng đế như người khai sáng, dẫn dắt nước Nga vươn tới tương lai. Nhưng kỳ công lớn nhất lại nằm ở phần bệ: 'Tảng đá Sấm', được cho là khối đá lớn nhất từng được con người di chuyển — ban đầu nặng chừng 1.500 tấn, được kéo suốt khoảng 6 km từ vùng Lakhta về đây. Bức tượng đã đi vào văn chương bất hủ qua bài thơ 'Kỵ sĩ Đồng' (1833) của Aleksandr Pushkin, và sống sót qua 900 ngày vây hãm Leningrad nhờ được che chắn bằng bao cát. Đây là điểm dừng ngắn nhưng đầy sức nặng lịch sử — hãy kết hợp với Nhà thờ Thánh Isaac và Quảng trường Thượng viện ngay bên cạnh trong một buổi tản bộ.",
        [
            "Do Ekaterina Đại đế đặt làm, nhà điêu khắc Étienne-Maurice Falconet thực hiện, khánh thành 1782.",
            "Bệ tượng 'Tảng đá Sấm' được xem là khối đá lớn nhất từng được con người di chuyển (~1.500 tấn, kéo ~6 km).",
            "Là nguồn cảm hứng cho bài thơ 'Kỵ sĩ Đồng' (1833) của Pushkin; sống sót qua cuộc vây hãm Leningrad.",
        ],
        {
            "hours_vi": "Mở cửa 24 giờ (tượng đài ngoài trời trên Quảng trường Thượng viện).",
            "ticket_vi": "Miễn phí.",
            "duration_vi": "15–30 phút.",
            "best_time_vi": "Buổi sáng ít người để chụp ảnh; kết hợp tản bộ quanh Thánh Isaac.",
            "tips_vi": "Đi cùng Nhà thờ Thánh Isaac gần đó; buổi sáng vắng hơn.",
        },
        photo_file="Bronze Horseman IMG 2908.JPG",
        official=None,
        tags=["monument", "free", "outdoor", "landmark"],
    ),
    place(
        "nevsky-prospect",
        "Đại lộ Nevsky (Nevsky Prospekt)",
        "Невский проспект",
        "Nevsky Prospect",
        ["square_street"],
        59.935944, 30.324097,
        "Đại lộ Nevsky (Nevsky Prospekt), Saint Petersburg",
        {"value": 4.5, "count": 4730, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách yêu kiến trúc bề thế, không khí sôi động và vô số cửa hàng, quán cà phê, nhà thờ, thắng cảnh dọc Nevsky, gọi đây là trái tim rực rỡ của thành phố, đặc biệt khi tản bộ buổi tối lúc lên đèn. Phàn nàn chính là quá đông giờ cao điểm và đôi khi vướng công trình trùng tu mặt tiền.",
        "Đại lộ chính dài ~4,5 km — trái tim sôi động của thành phố với kiến trúc tráng lệ, nhà thờ, cửa hàng và quán cà phê; nơi tản bộ lý tưởng cả ngày lẫn đêm.",
        "Nếu Saint Petersburg có một mạch máu chính, thì đó là Đại lộ Nevsky (Nevsky Prospekt). Được quy hoạch từ năm 1712 và mang tên hoàng thân trung cổ Aleksandr Nevsky, đại lộ dài khoảng 4,5 km này là nơi thành phố phô diễn trọn vẹn sự tráng lệ của mình. Dạo bước dọc Nevsky, bạn lần lượt đi qua Nhà thờ Kazan với hàng cột bán nguyệt, Nhà Singer (Nhà Sách) với mái vòm thuỷ tinh, Cung điện Stroganov theo phong cách Baroque và khu thương xá cổ Gostiny Dvor. Đây cũng là con phố đầu tiên ở Nga được thắp đèn đường bằng đèn dầu vào năm 1723. Nevsky từng in dấu trong những trang văn của Gogol và Dostoevsky, và đến nay vẫn không ngừng nhộn nhịp: cửa hàng, quán cà phê, hiệu sách, nghệ sĩ đường phố và dòng người bất tận. Ban ngày là nhịp sống thương mại hối hả; buổi tối, khi các mặt tiền lịch sử lên đèn, đại lộ khoác lên vẻ lãng mạn khó cưỡng. Hãy dành ít nhất hai đến ba giờ thong dong, sà vào một quán cà phê, và để thành phố tự kể câu chuyện của nó.",
        [
            "Đại lộ dài ~4,5 km, quy hoạch từ năm 1712, mang tên hoàng thân Aleksandr Nevsky.",
            "Năm 1723 trở thành con phố đầu tiên ở Nga có đèn đường (đèn dầu).",
            "Nối liền loạt thắng cảnh: Nhà thờ Kazan, Nhà Singer, Cung điện Stroganov, Gostiny Dvor; xuất hiện trong văn Gogol và Dostoevsky.",
        ],
        {
            "hours_vi": "Mở cửa 24 giờ (đường phố công cộng).",
            "ticket_vi": "Miễn phí.",
            "duration_vi": "2–3 giờ (tản bộ, khám phá).",
            "best_time_vi": "Buổi tối khi lên đèn; mùa hè.",
            "tips_vi": "Đi bộ là tốt nhất; kết hợp ghé Kazan, Nhà Singer; cẩn thận móc túi chỗ đông.",
        },
        photo_file="Nevsky Prospect, St. Petersburg, Russia.jpg",
        official=None,
        tags=["street", "free", "outdoor", "shopping", "night"],
    ),
    place(
        "kunstkamera",
        "Bảo tàng Kunstkamera (Nhân học & Dân tộc học)",
        "Кунсткамера",
        "Kunstkamera",
        ["museum"],
        59.941545, 30.304488,
        "Bờ kè Đại học 3 (Universitetskaya nab., 3), Saint Petersburg",
        {"value": 3.7, "count": 835, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách trân trọng bộ sưu tập dân tộc học đồ sộ và độc đáo, nhất là 'tủ kỳ vật' của Pyotr Đại đế với các tiêu bản giải phẫu (dù phản ứng trái chiều). Phàn nàn: đông đúc, bố cục chật và khó theo, hướng dẫn viên vội, và hụt hẫng khi khu tiêu bản đóng cửa trùng tu.",
        "Bảo tàng công cộng đầu tiên của Nga (1714), nổi tiếng với 'tủ kỳ vật' của Pyotr Đại đế và các tiêu bản giải phẫu — kỳ lạ nhưng đầy mê hoặc.",
        "Được Pyotr Đại đế sáng lập năm 1714, Kunstkamera là bảo tàng công cộng đầu tiên của nước Nga — và cũng là một trong những nơi kỳ lạ nhất Saint Petersburg. Nằm bên bờ sông Neva với tháp xanh đặc trưng (từng là đài thiên văn đầu tiên của Nga), bảo tàng lưu giữ gần hai triệu hiện vật dân tộc học từ khắp các châu lục. Nhưng thứ khiến Kunstkamera nổi danh — và gây tranh cãi — chính là 'tủ kỳ vật' của Pyotr: bộ sưu tập các tiêu bản giải phẫu và dị dạng mà vị hoàng đế mua lại từ nhà giải phẫu Hà Lan Frederik Ruysch và nhà tự nhiên học Albertus Seba. Pyotr tin rằng trưng bày những điều kỳ lạ sẽ giúp dân chúng bớt mê tín và cởi mở với khoa học. Ngày nay, phản ứng của du khách khá trái chiều: người thấy hấp dẫn, người thấy rùng mình. Ngoài khu tiêu bản, các gian trưng bày về văn hoá Nhật Bản, châu Phi, châu Mỹ và quả địa cầu Gottorp khổng lồ cũng rất đáng xem. Nếu đi cùng trẻ nhỏ hoặc dễ nhạy cảm, hãy cân nhắc trước khi vào khu giải phẫu.",
        [
            "Pyotr Đại đế lập năm 1714 — bảo tàng công cộng đầu tiên của nước Nga.",
            "Nổi tiếng với 'tủ kỳ vật' gồm tiêu bản giải phẫu mua từ Frederik Ruysch và Albertus Seba.",
            "Sưu tập gần 2 triệu hiện vật; tháp bảo tàng từng là đài thiên văn đầu tiên của Nga và chứa quả địa cầu Gottorp.",
        ],
        {
            "hours_vi": "Thứ Ba–CN 11:00–18:00; đóng cửa Thứ Hai.",
            "ticket_vi": "Người lớn ~300–400 RUB; sinh viên/trẻ em ~100 RUB.",
            "duration_vi": "1,5–2 giờ.",
            "best_time_vi": "Giữa tuần buổi sáng.",
            "tips_vi": "Cân nhắc nếu đi cùng trẻ nhỏ; kiểm tra khu giải phẫu có mở không trước khi đến.",
        },
        photo_file="Saint Petersburg Kunstkamera from Neva.jpg",
        official="https://www.kunstkamera.ru",
        tags=["museum", "indoor", "unusual"],
    ),
    place(
        "summer-garden",
        "Vườn Mùa Hè (Letny Sad)",
        "Летний сад",
        "Summer Garden",
        ["park_garden"],
        59.944908, 30.335553,
        "Vườn Mùa Hè (Letny Sad), bên sông Neva/Fontanka, Saint Petersburg",
        {"value": 4.5, "count": 886, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách khen khu vườn là chốn nghỉ chân tĩnh lặng, thanh lịch giữa trung tâm, với lối đi rợp cây, đài phun nước, hồ thiên nga và hàng tượng cẩm thạch (nay là bản sao). Điểm chê: đợt trùng tu thêm nhiều hàng rào khiến vài người thấy đổi nét cổ kính, đôi khi đài phun nước không chạy.",
        "Khu vườn cổ nhất Saint Petersburg (1704), do Pyotr Đại đế tự tay lên ý tưởng — những lối đi rợp bóng cây, đài phun nước, hồ thiên nga và hàng tượng cẩm thạch.",
        "Giữa lòng thành phố sôi động, Vườn Mùa Hè (Letny Sad) là một ốc đảo thanh bình được chính Pyotr Đại đế lên ý tưởng từ năm 1704 — một trong những khu vườn lâu đời nhất Saint Petersburg. Được thiết kế theo phong cách vườn Pháp cổ điển với những lối đi thẳng tắp rợp bóng cây, vườn từng được điểm tô bằng khoảng một trăm bức tượng cẩm thạch Venice. Ngày nay, khoảng 90 bản gốc được cất giữ trong nhà để bảo quản, thay bằng các bản sao ngoài trời, nhưng vẻ duyên dáng thì vẫn nguyên vẹn: đài phun nước róc rách, những hồ nước có thiên nga bơi lượn, và hàng rào sắt rèn tinh xảo dọc bờ Neva mà nữ thi sĩ Anna Akhmatova từng ngợi ca. Đây cũng là nơi đặt tượng đài nhà thơ ngụ ngôn Ivan Krylov — tượng đài dành cho một nhà thơ đầu tiên ở Đông Âu. Vườn đóng cửa suốt tháng Tư mỗi năm để bảo dưỡng, nên hãy tránh thời điểm ấy. Một buổi chiều thong dong ở đây, với một cuốn sách hoặc một cây kem, là cách hoàn hảo để nghỉ chân giữa hành trình khám phá.",
        [
            "Lên ý tưởng bởi Pyotr Đại đế từ năm 1704 — một trong những khu vườn lâu đời nhất Saint Petersburg.",
            "Từng có khoảng 100 tượng cẩm thạch Venice; nay ~90 bản gốc cất trong nhà, ngoài trời là bản sao.",
            "Hàng rào sắt rèn bên sông Neva được Anna Akhmatova ngợi ca; có tượng đài nhà thơ Ivan Krylov.",
        ],
        {
            "hours_vi": "1/5–30/9: 10:00–22:00; 1/10–31/3: 10:00–20:00; đóng cửa Thứ Ba và cả tháng Tư.",
            "ticket_vi": "Miễn phí.",
            "duration_vi": "1–1,5 giờ.",
            "best_time_vi": "Mùa hè, buổi chiều; tránh tháng Tư (đóng cửa).",
            "tips_vi": "Tránh tháng Tư; kết hợp dạo bờ sông Neva; mang theo sách hoặc kem để nghỉ chân.",
        },
        photo_file="Letniy Sad.jpg",
        official="https://igardens.ru",
        tags=["park", "free", "outdoor", "relax"],
    ),
    place(
        "peterhof",
        "Peterhof (Petergof) — Cung điện Lớn & đài phun nước",
        "Петергоф",
        "Peterhof Grand Palace and Fountains",
        ["palace", "park_garden"],
        59.884444, 29.908889,
        "Petergof, Razvodnaya ul. 2 (cách trung tâm ~30 km về phía tây)",
        {"value": 4.7, "count": 12817, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách trầm trồ trước Đại Thác nước và các đài phun mạ vàng ngoạn mục, nội thất cung điện xa hoa và khuôn viên rộng lớn được chăm chút, thường gọi đây là điểm nhấn của chuyến đi. Phàn nàn chính: đông và xếp hàng dài, giá vé cao hơn cho khách nước ngoài, và đồ ăn tại chỗ đắt.",
        "'Versailles của nước Nga' — quần thể cung điện và Công viên Hạ với hơn 60 đài phun nước mạ vàng chảy hoàn toàn bằng trọng lực; Di sản Thế giới UNESCO.",
        "Được Pyotr Đại đế cho khởi công từ năm 1714 như câu trả lời của nước Nga dành cho Versailles, Peterhof (Petergof) là bản giao hưởng của nước, vàng và quyền lực. Trái tim của quần thể là Đại Thác nước (Grand Cascade) trước Cung điện Lớn: hơn 60 đài phun nước và khoảng 200 pho tượng mạ vàng đổ xuống bậc thang, tất cả vận hành hoàn toàn bằng trọng lực, dẫn nước từ các mạch nguồn cách xa chừng 20 km mà không cần một chiếc máy bơm nào — một kỳ tích thuỷ lực của thế kỷ 18. Đứng giữa làn nước lấp lánh, hướng nhìn chạy dài theo con kênh ra tận Vịnh Phần Lan, bạn sẽ hiểu vì sao du khách gọi đây là điểm nhấn của cả chuyến đi. Bên trong Cung điện Lớn là chuỗi phòng khánh tiết lộng lẫy; ngoài vườn còn có những 'đài phun nước tinh nghịch' bất ngờ phun nước trêu khách. Trong Thế chiến II, Peterhof bị quân Đức chiếm đóng và tàn phá nặng nề, rồi được phục dựng công phu. Hãy đến vào mùa đài phun nước hoạt động (khoảng tháng Năm–Mười) và đi tàu cánh ngầm (hydrofoil) từ trung tâm thành phố để có trải nghiệm trọn vẹn nhất.",
        [
            "Pyotr Đại đế cho khởi công (từ 1714) như 'Versailles của nước Nga'.",
            "Đại Thác nước có hơn 60 đài phun và ~200 tượng mạ vàng, chảy hoàn toàn bằng trọng lực từ nguồn cách ~20 km.",
            "Di sản Thế giới UNESCO; bị tàn phá trong Thế chiến II rồi được phục dựng công phu.",
        ],
        {
            "hours_vi": "Công viên Hạ ~9:00–20:00 (đài phun nước ~T5–T10); Cung điện Lớn ~10:30–19:00, đóng cửa Thứ Hai.",
            "ticket_vi": "Công viên Hạ ~1.000 RUB; Cung điện Lớn ~1.200 RUB (khách nước ngoài cao hơn); dưới 16 tuổi miễn phí.",
            "duration_vi": "3–4 giờ (nửa ngày).",
            "best_time_vi": "Tháng 5–10 khi đài phun nước hoạt động; sáng để tránh đông.",
            "tips_vi": "Đi tàu cánh ngầm từ trung tâm cho nhanh và đẹp; mua vé trước; canh mùa đài phun nước.",
        },
        photo_file="Peterhof_-_Grand_Palace_and_Grand_Cascade.jpg",
        official="https://peterhofmuseum.ru",
        tags=["palace", "park", "fountains", "unesco", "outdoor", "top", "daytrip"],
    ),
    place(
        "catherine-palace",
        "Cung điện Ekaterina & Phòng Hổ phách (Tsarskoye Selo)",
        "Екатерининский дворец",
        "Catherine Palace (Amber Room)",
        ["palace"],
        59.716111, 30.395556,
        "Pushkin (Tsarskoye Selo), Sadovaya ul. 7 (~30 km phía nam)",
        {"value": 4.7, "count": 8689, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách choáng ngợp trước mặt tiền Rococo rực rỡ, Đại sảnh dát vàng và trên hết là Phòng Hổ phách được phục dựng — nhiều người gọi là khó quên. Phàn nàn thường gặp: quá đông và phải chờ lâu dù đã đặt vé, và bị hối đi nhanh qua các phòng vì dòng khách đoàn.",
        "Cung điện Rococo lộng lẫy ở Tsarskoye Selo với mặt tiền dài hơn 300 m và Phòng Hổ phách huyền thoại — từng bị Đức Quốc xã cướp phá và được phục dựng.",
        "Cách trung tâm Saint Petersburg khoảng 30 km, tại thị trấn Pushkin (Tsarskoye Selo), Cung điện Ekaterina hiện ra như một giấc mơ màu xanh và vàng. Được kiến trúc sư Bartolomeo Rastrelli thiết kế lại theo phong cách Rococo và hoàn thành năm 1756, cung điện có mặt tiền dài hơn 300 mét, dát vàng rực rỡ đến mức đương thời bị chê là quá xa hoa. Mang tên Nữ hoàng Ekaterina I, đây từng là hành cung mùa hè của hoàng gia Nga. Chuỗi phòng khánh tiết nối nhau bất tận, đỉnh cao là Đại sảnh dát vàng lộng lẫy. Nhưng viên ngọc thật sự là Phòng Hổ phách (Amber Room) — căn phòng ốp toàn hổ phách và vàng lá được mệnh danh 'kỳ quan thứ tám của thế giới'. Bản gốc bị quân Đức cướp đi trong Thế chiến II và biến mất bí ẩn cho đến nay; những gì bạn chiêm ngưỡng hôm nay là bản phục dựng công phu suốt các năm 1979–2003. Du khách gần như luôn choáng ngợp, dù thường phải chen chân giữa các đoàn khách. Hãy đặt vé trước, đến sớm, và dành thời gian dạo Công viên Ekaterina thơ mộng ngay bên cạnh.",
        [
            "Cung điện Rococo do Bartolomeo Rastrelli thiết kế lại, hoàn thành 1756, mặt tiền dài hơn 300 m.",
            "Nổi tiếng với Phòng Hổ phách — bản gốc bị Đức Quốc xã cướp trong Thế chiến II, phục dựng 1979–2003.",
            "Mang tên Nữ hoàng Ekaterina I; từng là hành cung mùa hè của hoàng gia Nga.",
        ],
        {
            "hours_vi": "Cung điện ~10:00–18:00, đóng cửa Thứ Ba và Thứ Hai cuối tháng; Công viên Ekaterina mở hằng ngày.",
            "ticket_vi": "Cung điện gồm Phòng Hổ phách ~1.500 RUB; Công viên thu phí nhỏ mùa hè (~150–200 RUB).",
            "duration_vi": "2–3 giờ.",
            "best_time_vi": "Sáng sớm, giữa tuần; mùa hè để dạo công viên.",
            "tips_vi": "Bắt buộc đặt vé trước; đến sớm; kết hợp dạo Công viên Ekaterina.",
        },
        photo_file="Catherine_Palace_in_Tsarskoe_Selo.jpg",
        official="https://tzar.ru",
        tags=["palace", "art", "indoor", "top", "daytrip"],
    ),
    place(
        "pavlovsk",
        "Cung điện & Công viên Pavlovsk",
        "Павловск",
        "Pavlovsk Palace and Park",
        ["palace", "park_garden"],
        59.685833, 30.453333,
        "Pavlovsk, Sadovaya ul. 20 (~30 km phía nam Saint Petersburg)",
        {"value": 4.7, "count": 1347, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách yêu Pavlovsk vì nội thất cung điện tao nhã, chừng mực và nhất là công viên phong cảnh kiểu Anh rộng lớn, tĩnh lặng, ít đông hơn hẳn Cung điện Ekaterina gần đó. Điểm chê: phải chờ vào, nhà vệ sinh hạn chế, vài phần cung điện bắt buộc theo tour tiếng Nga, và nhân viên đôi khi chưa niềm nở.",
        "Cung điện Palladian thanh nhã của Hoàng đế Pavel I, nằm giữa một trong những công viên phong cảnh kiểu Anh lớn nhất châu Âu (~600 ha) — yên tĩnh hơn hẳn các cung điện lân cận.",
        "Nếu Cung điện Ekaterina choáng ngợp bởi sự xa hoa, thì Pavlovsk chinh phục bằng sự thanh nhã và tĩnh lặng. Được kiến trúc sư người Scotland Charles Cameron xây dựng trong các năm 1782–1786 theo phong cách Palladian cho vị hoàng đế tương lai Pavel I và phu nhân Maria Feodorovna, cung điện có nội thất tinh tế, chừng mực — một gu thẩm mỹ cổ điển hiếm thấy. Nhưng điều khiến Pavlovsk thật sự đặc biệt là khu công viên bao quanh: rộng khoảng 600 ha, đây là một trong những công viên phong cảnh kiểu Anh lớn nhất châu Âu, với những dòng suối uốn lượn, cầu đá, đền đài nhỏ và rừng cây trải dài. Du khách yêu Pavlovsk chính vì nó vắng vẻ và thư thái hơn nhiều so với Tsarskoye Selo gần đó — nơi lý tưởng để đi dạo, đạp xe hay đơn giản là hít thở. Trong Thế chiến II, cung điện bị quân Đức chiếm đóng và thiêu rụi chỉ còn khung tường, rồi trở thành một trong những cung điện – bảo tàng Xô Viết đầu tiên được phục dựng hoàn chỉnh sau chiến tranh. Hãy kết hợp Pavlovsk với Tsarskoye Selo trong cùng một ngày, và dành thời gian lang thang trong công viên.",
        [
            "Xây 1782–1786 bởi kiến trúc sư Scotland Charles Cameron theo phong cách Palladian cho Hoàng đế Pavel I.",
            "Nằm trong công viên phong cảnh kiểu Anh rộng ~600 ha — một trong những công viên lớn nhất châu Âu.",
            "Bị thiêu rụi trong Thế chiến II, là một trong những cung điện–bảo tàng Xô Viết đầu tiên được phục dựng.",
        ],
        {
            "hours_vi": "Cung điện ~10:00–18:00 (đóng cửa Thứ Hai đầu tháng, vài phòng đóng Thứ Sáu); công viên mở hằng ngày.",
            "ticket_vi": "Cung điện ~700–900 RUB; công viên ~100–150 RUB (miễn phí mùa đông).",
            "duration_vi": "2–4 giờ (cung điện + công viên rộng).",
            "best_time_vi": "Mùa hè hoặc thu; kết hợp cùng Tsarskoye Selo.",
            "tips_vi": "Đi cùng ngày với Cung điện Ekaterina; dành thời gian cho công viên; mang giày đi bộ.",
        },
        photo_file="Pavlovsk_town_Pavlovsk_Palace_IMG_6257_1280.jpg",
        official="https://pavlovskmuseum.ru",
        tags=["palace", "park", "outdoor", "relax", "daytrip"],
    ),
    place(
        "mariinsky-theatre",
        "Nhà hát Mariinsky",
        "Мариинский театр",
        "Mariinsky Theatre",
        ["theatre"],
        59.925556, 30.296111,
        "Quảng trường Teatralnaya 1 (Teatralnaya pl., 1), Saint Petersburg",
        {"value": 4.6, "count": 2164, "source": "Tripadvisor", "as_of": "2026-07"},
        "Khán giả ca ngợi ballet và opera đẳng cấp thế giới, khán phòng dát vàng lịch sử và không khí trang trọng, nhiều người xem đây là trải nghiệm phải thử. Điểm chê: đôi khi diễn bắt đầu trễ, thỉnh thoảng vấn đề âm thanh dàn nhạc, và xếp hàng an ninh/gửi đồ hoặc chỗ ngồi–vé còn bất tiện.",
        "Thánh đường của ballet và opera Nga, nơi ra mắt 'Kẹp hạt dẻ' và 'Người đẹp ngủ trong rừng' của Tchaikovsky — khán phòng dát vàng lộng lẫy, quê nhà của đoàn Mariinsky (Kirov).",
        "Với những ai yêu ballet và opera, Nhà hát Mariinsky là một điểm hành hương. Khánh thành năm 1860 theo thiết kế của Alberto Cavos và mang tên Hoàng hậu Maria Aleksandrovna, nhà hát khoác lên mình khán phòng dát vàng, ghế nhung xanh và những chùm đèn lộng lẫy — một khung cảnh cổ điển khiến buổi diễn trở thành sự kiện trọng thể. Đây là nơi lịch sử nghệ thuật Nga được viết nên: các vở 'Kẹp hạt dẻ', 'Người đẹp ngủ trong rừng' của Tchaikovsky và 'Boris Godunov' của Mussorgsky đều ra mắt lần đầu trên sân khấu này. Mariinsky là quê nhà của đoàn ballet và opera lừng danh từng mang tên Kirov thời Xô Viết, nơi những Nureyev, Baryshnikov, Pavlova từng toả sáng. Dưới sự dẫn dắt của nhạc trưởng Valery Gergiev từ năm 1988, nhà hát vươn tầm thế giới, và sân khấu thứ hai hiện đại Mariinsky II mở cửa năm 2013. Hãy đặt vé sớm cho các buổi diễn nổi tiếng, ăn mặc lịch sự, và đến sớm để thưởng thức trọn vẹn không gian. Một đêm ở Mariinsky là trải nghiệm văn hoá khó quên của Saint Petersburg.",
        [
            "Khánh thành 1860 theo thiết kế Alberto Cavos, mang tên Hoàng hậu Maria Aleksandrovna.",
            "Nơi ra mắt 'Kẹp hạt dẻ', 'Người đẹp ngủ trong rừng' (Tchaikovsky) và 'Boris Godunov' (Mussorgsky).",
            "Quê nhà đoàn Mariinsky (Kirov); do nhạc trưởng Valery Gergiev dẫn dắt từ 1988; sân khấu Mariinsky II mở năm 2013.",
        ],
        {
            "hours_vi": "Buổi diễn thường bắt đầu 19:00 (đôi khi có suất matinee); phòng vé ~11:00–19:00.",
            "ticket_vi": "Tuỳ buổi diễn và chỗ ngồi, khoảng 1.000–8.000+ RUB.",
            "duration_vi": "~2,5–3 giờ (một buổi diễn).",
            "best_time_vi": "Mùa diễn (thu–xuân); đặt vé sớm cho vở nổi tiếng.",
            "tips_vi": "Đặt vé trước qua trang chính thức; ăn mặc lịch sự; đến sớm gửi áo khoác.",
        },
        photo_file="Санкт-Петербург,_Мариинский_театр,_фасад_(edited_version).jpg",
        official="https://www.mariinsky.ru",
        tags=["theatre", "culture", "indoor", "evening"],
    ),
    place(
        "alexander-nevsky-lavra",
        "Tu viện Aleksandr Nevsky (Lavra)",
        "Александро-Невская лавра",
        "Alexander Nevsky Lavra",
        ["church"],
        59.921111, 30.388889,
        "Nab. reki Monastyrki 1 (cuối Đại lộ Nevsky), Saint Petersburg",
        {"value": 4.6, "count": 413, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách trân trọng quần thể tu viện thanh bình, giàu tâm linh, Thánh đường Chúa Ba Ngôi tân cổ điển và nghĩa trang danh nhân nơi Dostoevsky, Tchaikovsky an nghỉ. Vài người thấy hơi được ca ngợi quá mức hoặc đang trùng tu nhiều, và lưu ý khuôn viên miễn phí nhưng nghĩa trang lịch sử thu phí.",
        "Tu viện Chính thống giáo bậc 'lavra' do Pyotr Đại đế lập năm 1710, với thánh đường Chúa Ba Ngôi tân cổ điển và nghĩa trang nơi Dostoevsky, Tchaikovsky an nghỉ.",
        "Ở đầu phía đông của Đại lộ Nevsky, nơi con phố kết thúc, là Tu viện Aleksandr Nevsky — một quần thể tôn giáo thanh tĩnh và giàu chiều sâu tâm linh. Được Pyotr Đại đế sáng lập năm 1710, đây là một trong số ít tu viện ở Nga được phong hàm 'lavra' (bậc cao nhất), danh hiệu nhận từ năm 1797. Trung tâm quần thể là Thánh đường Chúa Ba Ngôi (Troitsky) theo phong cách tân cổ điển do kiến trúc sư Ivan Starov xây dựng (1778–1790), nơi lưu giữ thánh tích của Thánh Aleksandr Nevsky — vị hoàng thân được phong thánh mà cả thành phố mang tên. Nhưng với nhiều du khách, điều cuốn hút nhất là các nghĩa trang danh nhân: tại Nghĩa trang Tikhvin, bạn có thể đứng trước mộ của những tên tuổi vĩ đại nhất văn hoá Nga — Dostoevsky, Tchaikovsky, Rimsky-Korsakov, Glinka và Borodin. Dạo bước giữa những bia mộ nghệ thuật ấy là một trải nghiệm trầm mặc và đầy cảm xúc. Khuôn viên và thánh đường vào cửa tự do; chỉ các nghĩa trang lịch sử mới bán vé. Hãy ăn mặc kín đáo, giữ yên lặng, và đến vào buổi sáng để cảm nhận trọn vẹn sự tĩnh lặng.",
        [
            "Pyotr Đại đế lập năm 1710; là một trong số ít tu viện mang hàm 'lavra' (từ năm 1797).",
            "Thánh đường Chúa Ba Ngôi tân cổ điển (1778–1790) của Ivan Starov lưu giữ thánh tích Thánh Aleksandr Nevsky.",
            "Nghĩa trang Tikhvin là nơi an nghỉ của Dostoevsky, Tchaikovsky, Rimsky-Korsakov, Glinka và Borodin.",
        ],
        {
            "hours_vi": "Khuôn viên & Thánh đường Chúa Ba Ngôi ~6:00–20:00; nghĩa trang bảo tàng ~9:30–18:00.",
            "ticket_vi": "Khuôn viên và thánh đường miễn phí; Nghĩa trang (Tikhvin/Lazarev) ~300–500 RUB.",
            "duration_vi": "1–2 giờ.",
            "best_time_vi": "Buổi sáng để yên tĩnh.",
            "tips_vi": "Ăn mặc kín đáo, giữ trật tự; mua vé nếu muốn thăm nghĩa trang danh nhân.",
        },
        photo_file="Троицкий_собор_Александро-Невской_Лавры_06.jpg",
        official="https://lavra.spb.ru",
        tags=["church", "free", "outdoor", "history"],
    ),
    place(
        "smolny-cathedral",
        "Nhà thờ Smolny",
        "Смольный собор",
        "Smolny Cathedral",
        ["church"],
        59.948611, 30.395000,
        "Quảng trường Rastrelli 3/1 (ploshchad Rastrelli), Saint Petersburg",
        {"value": 4.5, "count": 626, "source": "Tripadvisor", "as_of": "2026-07"},
        "Du khách trầm trồ trước mặt ngoài Baroque xanh-trắng nổi bật, một trong những kiệt tác của Rastrelli, và nội thất cao sáng, phấn chấn; vào cửa miễn phí được khen nhiều. Điểm chê: đang trùng tu, nội thất có phần trống trải/chưa hoàn thiện so với mặt tiền, và tháp chuông đồ sộ theo dự định ban đầu chưa bao giờ được xây.",
        "Kiệt tác Baroque xanh-trắng của Rastrelli, khởi công năm 1748 cho Nữ hoàng Elizaveta — mặt ngoài rực rỡ, nội thất sáng bừng, vào cửa miễn phí.",
        "Nổi bật trên nền trời với sắc xanh da trời và trắng tinh khôi, Nhà thờ Smolny là một trong những kiệt tác Baroque của bậc thầy Francesco Bartolomeo Rastrelli — cũng chính là kiến trúc sư của Cung điện Mùa Đông và Cung điện Ekaterina. Khởi công năm 1748 theo lệnh Nữ hoàng Elizaveta (người muốn lui về đây làm nữ tu), công trình có số phận trắc trở: việc xây dựng kéo dài hàng thập kỷ và chỉ hoàn tất vào khoảng năm 1835 dưới bàn tay kiến trúc sư Vasily Stasov. Tháp chuông trung tâm cao chừng 140 mét mà Rastrelli dự định dựng lên rốt cuộc không bao giờ thành hình vì thiếu kinh phí — nếu hoàn thành, nó đã là công trình cao nhất Saint Petersburg. Bên ngoài lộng lẫy bao nhiêu thì bên trong lại giản dị và tràn ngập ánh sáng bấy nhiêu, tạo cảm giác cao vút, thanh thoát. Sau thời gian dài được dùng làm phòng hoà nhạc, nhà thờ đã được tái thánh hiến cho hoạt động tôn giáo Chính thống giáo trong thập niên 2010. Vào cửa miễn phí; hãy đến vào ngày nắng để chiêm ngưỡng sắc xanh-trắng rực rỡ nhất, và cân nhắc leo lên đài quan sát trên tháp chuông để ngắm thành phố.",
        [
            "Kiệt tác Baroque của Francesco Bartolomeo Rastrelli, khởi công năm 1748 cho Nữ hoàng Elizaveta.",
            "Việc xây dựng kéo dài hàng chục năm, chỉ hoàn tất khoảng năm 1835 bởi Vasily Stasov.",
            "Tháp chuông dự định cao ~140 m chưa từng được xây vì thiếu kinh phí; nhà thờ được tái thánh hiến trong thập niên 2010.",
        ],
        {
            "hours_vi": "Hằng ngày ~7:00–20:00 (nay là thánh đường Chính thống đang hoạt động).",
            "ticket_vi": "Vào cửa miễn phí (hoan nghênh quyên góp); đài quan sát tháp chuông ~200–360 RUB.",
            "duration_vi": "30–60 phút.",
            "best_time_vi": "Ngày nắng để ngắm sắc xanh-trắng; buổi sáng.",
            "tips_vi": "Vào cửa miễn phí; cân nhắc leo tháp chuông ngắm cảnh; ăn mặc kín đáo.",
        },
        photo_file="Smolny_Convent.jpg",
        official="https://smolnyspb.ru",
        tags=["church", "free", "landmark", "viewpoint"],
    ),
]


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(PLACES, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(PLACES)} places -> {OUT}")


if __name__ == "__main__":
    main()
